### ISSUE TITLE
Several schemas for a single topic: how to use a union with AvroSerializer

### ISSUE THREAD

**Issue by quentinus95** [confluentinc/confluent-kafka-python#1003]
Description
===========

I'm trying to use a union of multiple schemas in `AvroSerializer` to use several schemas in a single topic using Avro. So far my code goes through the following steps:

1. Initializing a schema registry client and registering each individual schema. I can confirm it performs normally when I `curl` the registered subjects directly on the schema registry.
2. Initialize the key and value serializers using an union of all the namespaced schema names registered on (1.)

When doing so, I get a reference error:

> Unknown named schema 'my.schema', known names: [].

`my.schema` has been registered on (1.) and I can assert it is accessible under the schema name `my.schema` by searching it:

`curl my-registry:1234/subjects | grep my.schema` shows the subject name being available in the list.

I believe there is some steps I'm missing, but I'm having great troubles finding any hints in the documentation.

How to reproduce
================

The following code gives the previously mentioned error:

```py
schema_registry_client = SchemaRegistryClient({
     'url': 'http://my-registry:1234',
})

# A dictionary of schema names -> JSON parsed schemas
key_schemas_dict = load_schemas()

def build_schema(schema_item):
    subject_name, schema_dict = schema_item
    schema = Schema(json.dumps(schema_dict), "AVRO")

    return subject_name, schema

key_schemas = list(map(build_schema, key_schemas_dict.items()))

for subject_name, schema in key_schemas:
    schema_registry_client.register_schema(subject_name, schema)

serializers_config = {
    "auto.register.schemas": False,
    "subject.name.strategy": lambda context, namespaced_name: namespaced_name,
    "use.latest.version": True, # Undocumented, likely unefficient
}

keys_subject_names = list(dict(key_schemas).keys())
key_serializer = AvroSerializer(
    avro.loads(json.dumps(keys_subject_names)),
    schema_registry_client,
    conf=serializers_config,
)
```

Checklist
=========

Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): `('1.5.0', 17104896) ('1.5.0', 17105151)`
 - [x] Apache Kafka broker version: 5.4.1
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Ubuntu 18.04.5
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by TobiasBales** [comment]
Anything happening here?
We are running into the same thing while trying to adopt Kafka :D
