### ISSUE TITLE
KafkaError{code=UNKNOWN_MEMBER_ID,val=25,str="Commit failed: Broker: Unknown member"}

### ISSUE THREAD

**Issue by jianglijie** [confluentinc/confluent-kafka-python#1004]
Description
===========
I get the error  "KafkaError{code=UNKNOWN_MEMBER_ID,val=25,str="Commit failed: Broker: Unknown member"}"
when I assign_offsets  for Consumer

How to reproduce
================
```
offsets = {k: v + 1 for k, v in offsets.items()}  # the offset dict like{"0": 123, "1": 123}
par_list = []
for par, offset in partitions.items():
    par_list.append(TopicPartition(topic, int(par), offset))
consumer.commit(offsets=par_list, asynchronous=False)
```
I use version for 1.0.0  1.0.1 1.5.0 get the same error

Checklist
=========
Please provide the following information:

 - [x ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.0.0  1.0.1  1.5.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x ] Operating system: centos
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ x] Provide broker log excerpts  KafkaError{code=UNKNOWN_MEMBER_ID,val=25,str="Commit failed: Broker: Unknown member"}
 - [ ] Critical issue

**Comment by edenhill** [comment]
Is there another consumer that has joined the group (using subscribe()) with the same group.id ? That would prohibit your join-less consumer from committing.
