### ISSUE TITLE
Failed to resolve hosts - '['<bootstrap-server>:9092': Missing close-']'

### ISSUE THREAD

**Issue by benjaminelkrieff** [confluentinc/confluent-kafka-python#1007]
Description
===========

I failed on a very strange error today with the following log 
[thrd:sasl_ssl://['pkc-43n10.us-central1.gcp.confluent.cloud:9092/boo]: sasl_ssl://['pkc-43n10.us-central1.gcp.confluent.cloud:9092/bootstrap: Failed to resolve '['pkc-43n10.us-central1.gcp.confluent.cloud:9092': Missing close-']'

Where this damn [' could come from ? I checked 1000 times and it does not come from my configuration.
Anyway it should be sasl_ssl:/// exactly with 3 slashes so somehow the third slash is replaced by this damn ['

I have no idea where this could come from.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Pass bootstrap servers as string, not list.
