### ISSUE TITLE
_UNKNOWN_TOPIC error: How do I create a topic?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#101]
More of a question, really. If I do this in a python script:
```
conf = {'bootstrap.servers': '198.18.130.13',
        'group.id': 'mygroup',
        'debug': 'all',
        'socket.timeout.ms': 5000,
        'socket.max.fails': 1,
        'error_cb': my_kafka_error,
        'default.topic.config': {'message.timeout.ms': 4000},
        'session.timeout.ms': 3000}

kafka_producer = Producer(**conf)
kafka_producer.produce("Fred_topic", "Fred the dog went for a walk".encode('utf-8'), on_delivery=my_kafka_cb)
```
I get stuff like this in my output:
```
%7|1481562255.518|METADATA|rdkafka#producer-1| 198.18.130.13:9092/bootstrap: ===== Received metadata =====
%7|1481562255.518|METADATA|rdkafka#producer-1| 198.18.130.13:9092/bootstrap: 0 brokers, 1 topics
%7|1481562255.518|METADATA|rdkafka#producer-1| 198.18.130.13:9092/bootstrap:   Topic #0/1: Fred_topic with 0 partitions: Unknown broker error
%7|1481562255.518|METADATA|rdkafka#producer-1| 198.18.130.13:9092/bootstrap: Error in metadata reply for topic Fred_topic (PartCnt 0): Unknown broker error
%7|1481562255.518|STATE|rdkafka#producer-1| Topic Fred_topic changed state unknown -> notexists
%7|1481562255.518|PARTCNT|rdkafka#producer-1| Partitioning 1 unassigned messages in topic Fred_topic to 0 partitions
%7|1481562255.518|UAS|rdkafka#producer-1| 0/1 messages were partitioned in topic Fred_topic
%7|1481562255.518|UAS|rdkafka#producer-1| 1/1 messages failed partitioning in topic Fred_topic
************************** my_kafka_cb
************************** my_kafka_cb: error: code -188, name _UNKNOWN_TOPIC, str Fred the dog went for a walkI
************************** my_kafka_cb: msg: partition None, topic Fred_topic, value Fred the dog went for a walk
```

Note that in the above, "Fred_topic" was not registered or created in any way before the call to produce(). Am I supposed to be able to create a new topic from the confluent python client on the producer side? If so, how? Or is the idea that you must explicitly create topics out of band on the broker before you can produce() to them using the confluent python client?

**Comment by edenhill** [comment]
If auto topic creation is enabled on the **broker** then the client's request will automatically create whatever topic you produce to.
I would guess it isn't enabled in your case.

See `auto.create.topics.enable	` here:
http://kafka.apache.org/documentation.html#brokerconfigs

**Comment by johnrgregg3** [comment]
Hmm. It still didn't like it. I added the line:

auto.create.topics.enable=true

to the end of server.properties on my kafka broker (NOT the client/producer), then restarted the kafka broker service. Am I putting this in the right place? Someone online said that autocreate topics is the default behavior, so it is strange that I didn't see it work when there was no explicit parameter setting it to false. Unless I'm simply looking in the wrong set of files. I couldn't see in the document where exactly I should put the config parameters listed in the big table.

**Comment by edenhill** [comment]
Is there anything interesting in the broker logs when you run the client?

**Comment by johnrgregg3** [comment]
Only this, but I didn't understand it. Is it throwing the error during creation of the topic? I had thought it was the produce() that cause the error, but it makes more sense if it is topic creation.

[2016-12-12 20:26:15,509] ERROR [KafkaApi-1] Error when handling request {topics=[Fred_topic]} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
        at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
        at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
        at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
        at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:670)
        at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:666)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:666)
        at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:727)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:79)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
        at java.lang.Thread.run(Thread.java:745)

Looking at this log, my guess is that it is not disallowing the creation of the topic, it is just upset about the replication factor. So auto.create.topics.enable was never the problem. At the moment, I only have one broker up for testing. If I am interpreting this correctly, it refuses to create the topic with less than 3 brokers up (the replication factor). Although when I grep through the configs for "replication" or "factor" I don't get any hits, and the document says that default.replication.factor defaults to 1. I can't see why my replication factor is 3 here. Explicitly setting default.replication.factor=1 in server.properties did not seem to help.

**Comment by ewencp** [comment]
@johnrgregg3 `default.replication.factor` is the setting you need, but it defaults to 1 so that shouldn't be an issue unless it was already changed in `server.properties`. The broker was definitely bounced after the config change? The stacktrace is definitely for the topic auto-creation path.
