### ISSUE TITLE
Consumer group session timed out (in join-state started)

### ISSUE THREAD

**Issue by antoniodimariano** [confluentinc/confluent-kafka-python#1011]
Description
===========

* Client Configuration
```
'session.timeout.ms': 6000,
'enable.auto.commit': True,
'log.connection.close': True,

```

* Logic in code 

```
        try:
            self.consumer.subscribe(my_topic, on_assign=self.print_assignment)
            while True:
                incoming_message = self.consumer.poll(timeout=1.0)

                if incoming_message is None:
                    continue
                elif incoming_message.error() is None:
                        self.executor.submit(process_message, payload=incoming_message.value())

```

The code in function process messages and everything works good untile for some reason this error occurs:

```

[thrd:main]: Consumer group session timed out (in join-state started) after 6037 ms without a successful response from the group coordinator (broker 1, last error was Success): revoking assignment and rejoining group

```
As a result, no new messages are received unless I manually restart the consumer. 

How to reproduce
================

- confluent_kafka.version()
('1.5.0', 17104896)

- confluent_kafka.libversion()
('1.5.0', 17105151)

- Confluent Kafka broker version: 5.3 (community edition)

* Operating System: macOS  v10.14.6   and Debian 9

**Comment by XXRRL** [comment]
> # Description
> * Client Configuration
> 
> ```
> 'session.timeout.ms': 6000,
> 'enable.auto.commit': True,
> 'log.connection.close': True,
> ```
> 
> * Logic in code
> 
> ```
>         try:
>             self.consumer.subscribe(my_topic, on_assign=self.print_assignment)
>             while True:
>                 incoming_message = self.consumer.poll(timeout=1.0)
> 
>                 if incoming_message is None:
>                     continue
>                 elif incoming_message.error() is None:
>                         self.executor.submit(process_message, payload=incoming_message.value())
> ```
> 
> The code in function process messages and everything works good untile for some reason this error occurs:
> 
> ```
> 
> [thrd:main]: Consumer group session timed out (in join-state started) after 6037 ms without a successful response from the group coordinator (broker 1, last error was Success): revoking assignment and rejoining group
> ```
> 
> As a result, no new messages are received unless I manually restart the consumer.
> 
> # How to reproduce
> * confluent_kafka.version()
>   ('1.5.0', 17104896)
> * confluent_kafka.libversion()
>   ('1.5.0', 17105151)
> * Confluent Kafka broker version: 5.3 (community edition)
> 
> * Operating System: macOS  v10.14.6   and Debian 9

I also met this problem, have you solved it

**Comment by edenhill** [comment]
Is executor.submit() a blocking call? If so, does it block for longer than max.poll.interval.ms (which seems to be set to 6 seconds in your case, which is quite low)?

**Comment by antoniodimariano** [comment]
No, it's not a blocking call. It adds a task to a celery queue. 6 secs it's probably not much but the error occurs soon after the service starts, without any messages consumed yet.

**Comment by XXRRL** [comment]
this error occurs:
    [thrd:main]Topic xxx partition count changed from 1 to 0 
    [thrd:main]: Consumer group session timed out (in join-state started) after 77384 ms without a successful response from the 
         group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
without any messages consumed yet

**Comment by antoniodimariano** [comment]
> this error occurs:
> [thrd:main]Topic xxx partition count changed from 1 to 0
> [thrd:main]: Consumer group session timed out (in join-state started) after 77384 ms without a successful response from the
> group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
> without any messages consumed yet

What value for your `session.timeout.ms`. Can you share your consumer conf?

**Comment by XXRRL** [comment]
> > this error occurs:
> > [thrd:main]Topic xxx partition count changed from 1 to 0
> > [thrd:main]: Consumer group session timed out (in join-state started) after 77384 ms without a successful response from the
> > group coordinator (broker 0, last error was Success): revoking assignment and rejoining group
> > without any messages consumed yet
> 
> What value for your `session.timeout.ms`. Can you share your consumer conf?

session.timeout.ms is 6 secs

**Comment by edenhill** [comment]
Try to reproduce this on v1.6.0 when it is released (soon!), it has a bunch of consumer related fixes.

**Comment by omarkhalid79** [comment]
Am hitting this issue with the v1.6.0. Was this resolved in the past?
