### ISSUE TITLE
Roundrobin assignor failed on assert

### ISSUE THREAD

**Issue by talmachani** [confluentinc/confluent-kafka-python#1012]
Description
===========

Hi while running few consumers on the same topic,

they all exited with this error after about 10 minutes.

rdkafka_roundrobin_assignor.c:97: rd_kafka_roundrobin_assignor_assign_cb: Assertion `next < rd_list_cnt(&eligible_topic-> members)' failed.

How to reproduce
================

Not sure, looks like its related to the fact that no more messages were left to consume, 
but i'm not sure.

Checklist
=========
Please provide the following information:

confluent_kafka.libversion():
('1.5.0', 17105151)
confluent_kafka.version():
('1.5.0', 17104896)

Apache Kafka broker version:
 2.6.0

Client configuration: 
  {
                "bootstrap.servers": bootstrap_servers,
                "enable.auto.commit": True,
                "partition.assignment.strategy": "roundrobin",
                "socket.timeout.ms": 180000,
}

**Comment by edenhill** [comment]
Fixed in v1.5.3
https://github.com/edenhill/librdkafka/releases/tag/v1.5.3
