### ISSUE TITLE
Missing Consumer/Producer Config Values

### ISSUE THREAD

**Issue by areibman** [confluentinc/confluent-kafka-python#1015]
Description
===========
When instantiating a Producer or Consumer, there are several missing that are available to use when you create a Kafka Consumer. These config values are available in `org.apache.kafka.clients.consumer.ConsumerConfig` in Java.

The config values in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md are not exhaustive, and there doesn't appear to be an explanation as to why.

How to reproduce
================

I am trying to create a consumer with these configuration settings settings:
```
consumer {​​​​​​​
  kafka-clients {​​​​​​​
    request.timeout.ms = 600000
    group.id = xxxx
    metadata.max.age.ms = 180000
    connections.max.idle.ms = 180000
    bootstrap.servers = "xxxxx:9093"
    sasl.mechanism = PLAIN
    security.protocol = SASL_SSL
    sasl.jaas.config = "xxxx"
  }​​​​​​​
}​​​​​​​
```
However, **metadata.max.age.ms** will fail:

```
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "connections.max.idle.ms""}
...
During handling of the above exception, another exception occurred:
...
Exception: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "connections.max.idle.ms""}
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
confluent-kafka==1.5.0
 - [ ] Client configuration: 
```
{'bootstrap.servers': bootstrap_server,
                             'security.protocol': security_protocol,
                             'sasl.mechanism': sasl_mechanism,
                             'sasl.username': sasl_username,
                             'sasl.password': self.connection_string,
                             'group.id': self.consumer_group,
                             'auto.offset.reset': kafka_offset_reset,
                             'connections.max.idle.ms': 180000,
                             'request.timeout.ms': 600000,
                             'retries': 3,
                             'metadata.max.age.ms': 180000,
                             "api.version.request": True}
```
 -  Operating system: Alpine Linux

**Comment by edenhill** [comment]
librdkafka, which confluent-kafka-python (et.al) are based on, predates the Java clients and have a different implementation, so not all configuration properties available in the Java clients are available in librdkafka and vice versa.
We do strive to keep librdkafka configs as close to the Java counterparts, when it makes sense.
As for connections.max.idle.ms; there is no idle enforcement on the client in librdkafka, we rely on the broker for that.

**Comment by edenhill** [comment]
JAAS is a Java thing and not relevant to Python, but all SASL mechanisms are configurable through the standard librdkafka properties as seen in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
