### ISSUE TITLE
Docker/Python - Unable to Connect to SASL Enabled Kafka Cluster

### ISSUE THREAD

**Issue by q26646** [confluentinc/confluent-kafka-python#1016]
Description
===========

I need to connect to a SASL/Kerberos enabled Kafka cluster in Azure from a python/ubuntu 18.04 docker container. I am trying to 
a) create a base image with librdkafka and its dependencies installed first and then confluent_kafka from source
b) use the base image (from a docker registry) to create an application image which runs the python code to connect to kafka
I am getting the below issue:

> cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create producer: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM OAUTHBEARER"}

However, when I create a multi-stage docker image (in a single dockerfile) the same thing works.

How to reproduce
================

* Create a base image using the below
```
FROM ubuntu:18.04 
#Install librdkafka and dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y gnupg wget software-properties-common supervisor python3-pip git
RUN wget -qO - https://packages.confluent.io/deb/6.0/archive.key | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/6.0 stable main"
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libssl-dev libsasl2-2 libsasl2-dev libsasl2-modules-gssapi-mit librdkafka-dev krb5-config krb5-user && DEBIAN_FRONTEND=noninteractive apt-get -y upgrade -f
#install confluent kafka
RUN python3 -m pip install --no-binary :all: confluent-kafka

COPY supervisor-workers.conf /etc/supervisor/conf.d/

RUN useradd -m app && chown -R app:app /var/log/supervisor/ /var/run/ /etc/supervisor/

USER app

WORKDIR /opt/abc/servers

COPY requirements-base.txt ./
RUN python3 -m pip install --no-cache-dir -r requirements-base.txt

ENTRYPOINT ["supervisord"]
```
* Create an application image from the image (pushed to docker or any registry)
```
FROM $DOCKER_BASE_URL/base-image
ENV PATH="/home/app/.local/bin:${PATH}"
COPY . ./
COPY supervisor-workers.conf /etc/supervisor/conf.d/
ENV KRB5_KDC_PROFILE='/opt/abc/servers/krb5.conf'
ENV KRB5_CONFIG='/opt/abc/servers/krb5.conf'
RUN python3 -m pip install --no-cache-dir -r requirements.txt

EXPOSE 8082
```
* Below is the client code to connect to cluster
```python
from datetime import datetime
import os
from confluent_kafka import Producer
 class SNIProducer():
    def __init__(self):
        print("creating producer object", datetime.now())
        conf = {'bootstrap.servers': os.getenv('AZURE_HDINSIGHT_BROKERS'),'security.protocol': 'SASL_PLAINTEXT', 'sasl.mechanism':'GSSAPI', 'sasl.kerberos.service.name':'kafka','sasl.kerberos.principal':os.getenv('SA_KAFKA_USER')+'@DOMAIN.COM','sasl.kerberos.keytab':'/etc/keytab/'+os.getenv('SA_KAFKA_USER')+'.keytab' }
        self.kafka_producer = Producer(**conf)
```
Checklist
=========
Please provide the following information:

 - [x ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): librdkafka1:amd64 (1.5.0~1confluent6.0.1-1) & confluent-kafka-1.5.0
 - [x] Apache Kafka broker version: 2.1
 - [x] Client configuration: `{...}` - provided above. pls let me know if you need more details
 - [x] Operating system: Ubtunu 18.04
 - [x] Provide client logs (with `'debug': '..'` as necessary) - provided above
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Your base image works well Kerberos, so I'm guessing something is messed up later, maybe the pip install from requirements.txt reinstalls the wheel version of confluent_kafka?

**Comment by q26646** [comment]
Thanks for the response! 
I removed confluent_kafka from all requirement.txt files. I also am noticing that if I move the USER app to the app image from base image, it works fine. So it sounds like this needs to execute in the context of root. Is there such a requirement for librdkafka?

**Comment by edenhill** [comment]
No such requirement
