### ISSUE TITLE
Delete consumer group support

### ISSUE THREAD

**Issue by irux** [confluentinc/confluent-kafka-python#1021]
Hello, I see that the new version of librdkafka is out and I would like to know when will it compatible with this wrapper. I am interested in delete consumer groups function.

https://github.com/edenhill/librdkafka/releases/tag/v1.6.0

**Comment by mhowlett** [comment]
the python v1.6 release shouldn't be too far, but delete consumer groups hasn't been exposed yet in the binding.

**Comment by irux** [comment]
Hello, I see that we have a release for the v1.6.0 https://github.com/confluentinc/confluent-kafka-python/releases/tag/v1.6.0 but I don't see the delete consumergroups function exposed. Do you think would be a new feature in the next release of the library @mhowlett ? thank you!

**Comment by jliunyu** [comment]
I added this one to our backlog.

**Comment by SunnyQjm** [comment]
What's the progress? @jliunyu

**Comment by 4-TimurN** [comment]
i am interested too @jliunyu

**Comment by milindl** [comment]
Closing with v2.0.2 as it contains delete_consumer_groups
