### ISSUE TITLE
Question : issue with configuring SSL in python 

### ISSUE THREAD

**Issue by mataralhawiti** [confluentinc/confluent-kafka-python#1024]
Description
===========
I have a Kafka cluster deployed on Openshift via Strimzi operator. The cluster is configured with SSL for external connections.
I was able to connect my Java consumer to the cluster by extracting The Cluster certificate and then created Java trust store as following :

    oc extract secret/my-cluster-cluster-ca-cert --keys=ca.crt --to=- > ca.crt
    keytool -import -trustcacerts -alias root -file ca.crt -keystore truststore.jks -storepass password -noprompt

The issue I'm facing now is how to configure my ***Python consumer*** to use SSL connection.
I can extract the following files from my cluster :

 - ca.crt
 - ca.p12
 - ca.password

Following the documentation provided by Confluent team [Using SSL with librdkafka][1] I tried different options without luck.

My understating is Python only accepts PEM format so I have to convert my ca.crt to ca.pem :

    openssl x509 -in ca.crt -out cert.pem

Then in my Python consumer :

        'ssl.ca.location': "C:\kafka\cert",
        'ssl.certificate.location': "C:\kafka\cert\cert.pem"

 
However, I keep getting the error :

> %4|1612028623.497|BROKER|insert_consumer#consumer-1| [thrd:app]: Broker name "https://kafka-cluster-kafka-ext-xxxxxxxx.com:443" parse error: unsupported protocol "HTTPS"

I spent a lot time trying to debug and understand the issue without any luck. One major confusion I'm having is what **ca.p12** file actually is ?

Am I doing the certification's converting wrong ?

Any help or guidance would be very appreciated.
 

  [1]: https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

Checklist
=========
 - [ ] confluent-kafka-python and librdkafka version (`1.5.0`)
 - [ ] Operating system: Windows 10

**Comment by pratapagiri** [comment]
@mataralhawiti I'm facing the same issue. Can you please provide if you have found solution for this issue?

**Comment by mataralhawiti** [comment]
@pratapagiri sure, please note your security protocol might be different depending on your cluster setup.

```
"bootstrap.server": bootstrap-url,
'security.protocol": 'SASL SSL', 
'sasl.mechanism": "PLAIN",
"sasl.username": "dummyuser",
"sasl.password": "dummypass",
"group.id": "test-1",
"ssl.ca.location": r"my-kafka-cluster/path/ca.pem",

"schema.registry.ssl.ca.location":r"my-schem-cluster/path/cer.pem",
"schema.registry.url": sr-url,
"schema.registry.basic.auth.credentials.source": "SASL INHERIT",
"schema.registry.basic.auth.user.info": "myusername: mypassword"
```

**Comment by tommyJimmy87** [comment]
Hi @mataralhawiti how did you solve this issue? I'm also trying to connect with SSL from python to Strimzi without success. If you have any hint please let me know!
