### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by 2020testuser** [confluentinc/confluent-kafka-python#1027]
Hi,
Could anyone please shed some light on the below?

I'm sending avro messages to kafka using SerializingProducer successfully (by passing the schema string  and the schema registry url). 
When I get the message from kafka, how can I get the schema id from the message?
b'\x00\x00\x01\x1e\xaa\x10testuser\x0cdirector'

Is the schema id embedded here and I need to parse and get it? Thanks in advance!

**Comment by slominskir** [comment]
The Schema ID is included in the [RegisteredSchema](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/index.html#registeredschema) and you can obtain one via [SchemaRegistryClient.get_latest_version](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/index.html#confluent_kafka.schema_registry.SchemaRegistryClient.get_latest_version).    

If you're consuming the message though, you're likely using the [DeserializingConsumer](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/index.html#deserializingconsumer) and configuring it with an [AvroDeserializer](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/index.html#avrodeserializer) (or JSON, or Protobuff) and expect to obtain the Schema ID from one of these two objects, but I don't think you can.  

There are a lot of other ways to identify a schema too: subject, version, topic, name, namespace, and schema text.

**Comment by 2020testuser** [comment]
@slominskir -  Thanks Much for the explanation!
