### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by alvarodecastro74** [confluentinc/confluent-kafka-python#103]
This stuff is impossible to install on a raspberry: every single error under the sun comes up

And since the last issue here is from 19 days ago I dont think this issue would be solved so no point in adding much information

**Comment by edenhill** [comment]
Please provide the following information:
 * confluent-kafka-python version
 * means of installation: source, pip, ...
 * build logs
 * rpi model, os version, etc.

**Comment by alvarodecastro74** [comment]
I first ran apt-get install librdkafka-dev
apt-get install -t jessie python-dev

Then I ran pip install confluent-kafka and got all these errors:
==============================

In file included from confluent_kafka/src/confluent_kafka.c:17:0:

confluent_kafka/src/confluent_kafka.h:197:32: error: unknown type name ‘rd_kafka_topic_partition_list_t’

 PyObject *c_parts_to_py (const rd_kafka_topic_partition_list_t *c_parts);

                                ^

confluent_kafka/src/confluent_kafka.h:198:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’

 rd_kafka_topic_partition_list_t *py_to_c_parts (PyObject *plist);

 ^

confluent_kafka/src/confluent_kafka.c: In function ‘KafkaError_name’:

confluent_kafka/src/confluent_kafka.c:74:2: warning: implicit declaration of function ‘rd_kafka_err2name’ [-Wimplicit-function-declaration]

  return cfl_PyUnistr(_FromString(rd_kafka_err2name(self->code)));

  ^

In file included from confluent_kafka/src/confluent_kafka.c:17:0:

confluent_kafka/src/confluent_kafka.c:74:34: warning: passing argument 1 of ‘PyUnicodeUCS4_FromString’ makes pointer from integer without a cast

  return cfl_PyUnistr(_FromString(rd_kafka_err2name(self->code)));

                                  ^

confluent_kafka/src/confluent_kafka.h:71:38: note: in definition of macro ‘cfl_PyUnistr’

 #define cfl_PyUnistr(X) PyUnicode ## X

                                      ^

In file included from /usr/include/python2.7/Python.h:85:0,

                 from confluent_kafka/src/confluent_kafka.h:17,

                 from confluent_kafka/src/confluent_kafka.c:17:

/usr/include/python2.7/unicodeobject.h:281:31: note: expected ‘const char *’ but argument is of type ‘int’

 # define PyUnicode_FromString PyUnicodeUCS4_FromString

                               ^

/usr/include/python2.7/unicodeobject.h:477:23: note: in expansion of macro ‘PyUnicode_FromString’

 PyAPI_FUNC(PyObject*) PyUnicode_FromString(

                       ^

confluent_kafka/src/confluent_kafka.c: In function ‘TopicPartition_new’:

confluent_kafka/src/confluent_kafka.c:551:21: error: ‘RD_KAFKA_OFFSET_INVALID’ undeclared (first use in this function)

  long long offset = RD_KAFKA_OFFSET_INVALID;

                     ^

confluent_kafka/src/confluent_kafka.c:551:21: note: each undeclared identifier is reported only once for each function it appears in

confluent_kafka/src/confluent_kafka.c: At top level:

confluent_kafka/src/confluent_kafka.c:746:32: error: unknown type name ‘rd_kafka_topic_partition_list_t’

 PyObject *c_parts_to_py (const rd_kafka_topic_partition_list_t *c_parts) {

                                ^

confluent_kafka/src/confluent_kafka.c: In function ‘c_parts_to_py’:

confluent_kafka/src/confluent_kafka.c:750:28: error: request for member ‘cnt’ in something not a structure or union

  parts = PyList_New(c_parts->cnt);

                            ^

confluent_kafka/src/confluent_kafka.c:752:26: error: request for member ‘cnt’ in something not a structure or union

  for (i = 0 ; i < c_parts->cnt ; i++) {

                          ^

confluent_kafka/src/confluent_kafka.c:753:9: error: unknown type name ‘rd_kafka_topic_partition_t’

   const rd_kafka_topic_partition_t *rktpar = &c_parts->elems[i];

         ^

confluent_kafka/src/confluent_kafka.c:753:54: error: request for member ‘elems’ in something not a structure or union

   const rd_kafka_topic_partition_t *rktpar = &c_parts->elems[i];

                                                      ^

In file included from /usr/include/python2.7/Python.h:100:0,

                 from confluent_kafka/src/confluent_kafka.h:17,

                 from confluent_kafka/src/confluent_kafka.c:17:

confluent_kafka/src/confluent_kafka.c:756:12: error: request for member ‘topic’ in something not a structure or union

      rktpar->topic, rktpar->partition,

            ^

/usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’

 #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))

                                                                          ^

confluent_kafka/src/confluent_kafka.c:756:27: error: request for member ‘partition’ in something not a structure or union

      rktpar->topic, rktpar->partition,

                           ^

/usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’

 #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))

                                                                          ^

confluent_kafka/src/confluent_kafka.c:757:12: error: request for member ‘offset’ in something not a structure or union

      rktpar->offset, rktpar->err));

            ^

/usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’

 #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))

                                                                          ^

confluent_kafka/src/confluent_kafka.c:757:28: error: request for member ‘err’ in something not a structure or union

      rktpar->offset, rktpar->err));

                            ^

/usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’

 #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))

                                                                          ^

confluent_kafka/src/confluent_kafka.c: At top level:

confluent_kafka/src/confluent_kafka.c:769:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’

 rd_kafka_topic_partition_list_t *py_to_c_parts (PyObject *plist) {

 ^

confluent_kafka/src/confluent_kafka.c: In function ‘py_to_c_parts’:

confluent_kafka/src/confluent_kafka.c:770:2: error: unknown type name ‘rd_kafka_topic_partition_list_t’

  rd_kafka_topic_partition_list_t *c_parts;

  ^

confluent_kafka/src/confluent_kafka.c:779:2: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_new’ [-Wimplicit-function-declaration]

  c_parts = rd_kafka_topic_partition_list_new((int)PyList_Size(plist));

  ^

confluent_kafka/src/confluent_kafka.c:779:10: warning: assignment makes pointer from integer without a cast

  c_parts = rd_kafka_topic_partition_list_new((int)PyList_Size(plist));

          ^

confluent_kafka/src/confluent_kafka.c:790:4: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_destroy’ [-Wimplicit-function-declaration]

    rd_kafka_topic_partition_list_destroy(c_parts);

    ^

confluent_kafka/src/confluent_kafka.c:794:3: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_add’ [-Wimplicit-function-declaration]

   rd_kafka_topic_partition_list_add(c_parts,

   ^

confluent_kafka/src/confluent_kafka.c:796:23: error: invalid type argument of ‘->’ (have ‘int’)

         tp->partition)->offset =

                       ^

confluent_kafka/src/confluent_kafka.c: In function ‘error_cb’:

confluent_kafka/src/confluent_kafka.c:832:3: warning: implicit declaration of function ‘rd_kafka_yield’ [-Wimplicit-function-declaration]

   rd_kafka_yield(h->rk);

   ^

confluent_kafka/src/confluent_kafka.c: In function ‘producer_conf_set_special’:

confluent_kafka/src/confluent_kafka.c:973:13: error: ‘rd_kafka_msg_partitioner_consistent’ undeclared (first use in this function)

      tconf, rd_kafka_msg_partitioner_consistent);

             ^

confluent_kafka/src/confluent_kafka.c:976:13: error: ‘rd_kafka_msg_partitioner_consistent_random’ undeclared (first use in this function)

      tconf, rd_kafka_msg_partitioner_consistent_random);

             ^

In file included from confluent_kafka/src/confluent_kafka.c:17:0:

confluent_kafka/src/confluent_kafka.c:1003:6: error: ‘RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED’ undeclared (first use in this function)

      RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED,

      ^

confluent_kafka/src/confluent_kafka.h:98:35: note: in definition of macro ‘cfl_PyErr_Format’

   PyObject *_eo = KafkaError_new0(err, __VA_ARGS__); \

                                   ^

confluent_kafka/src/confluent_kafka.c: In function ‘common_conf_setup’:

confluent_kafka/src/confluent_kafka.c:1178:2: warning: implicit declaration of function ‘rd_kafka_conf_set_default_topic_conf’ [-Wimplicit-function-declaration]

  rd_kafka_conf_set_default_topic_conf(conf, tconf);

  ^

confluent_kafka/src/confluent_kafka.c: In function ‘KafkaError_add_errs’:

confluent_kafka/src/confluent_kafka.c:1299:2: warning: implicit declaration of function ‘rd_kafka_get_err_descs’ [-Wimplicit-function-declaration]

  rd_kafka_get_err_descs(&descs, &cnt);

  ^

confluent_kafka/src/confluent_kafka.c:1335:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   if (!descs[i].desc)

   ^

confluent_kafka/src/confluent_kafka.c:1335:13: error: dereferencing pointer to incomplete type

   if (!descs[i].desc)

             ^

confluent_kafka/src/confluent_kafka.c:1338:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   code = PyLong_FromLong(descs[i].code);

   ^

confluent_kafka/src/confluent_kafka.c:1338:31: error: dereferencing pointer to incomplete type

   code = PyLong_FromLong(descs[i].code);

                               ^

confluent_kafka/src/confluent_kafka.c:1340:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   PyDict_SetItemString(dict, descs[i].name, code);

   ^

confluent_kafka/src/confluent_kafka.c:1340:35: error: dereferencing pointer to incomplete type

   PyDict_SetItemString(dict, descs[i].name, code);

                                   ^

confluent_kafka/src/confluent_kafka.c:1344:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   _PRINT("| %-*.*s | %-*.*s |\n"

   ^

confluent_kafka/src/confluent_kafka.c:1346:33: error: dereferencing pointer to incomplete type

          _COL1_W, _COL1_W, descs[i].name,

                                 ^

confluent_kafka/src/confluent_kafka.c:1313:43: note: in definition of macro ‘_PRINT’

   _len = snprintf(tmpdoc, sizeof(tmpdoc), __VA_ARGS__); \

                                           ^

confluent_kafka/src/confluent_kafka.c:1344:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   _PRINT("| %-*.*s | %-*.*s |\n"

   ^

confluent_kafka/src/confluent_kafka.c:1347:33: error: dereferencing pointer to incomplete type

          _COL2_W, _COL2_W, descs[i].desc,

                                 ^

confluent_kafka/src/confluent_kafka.c:1313:43: note: in definition of macro ‘_PRINT’

   _len = snprintf(tmpdoc, sizeof(tmpdoc), __VA_ARGS__); \

                                           ^

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-bOrzFz/confluent-kafka/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TSG_1G-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-bOrzFz/confluent-kafka
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 75: ordinal not in range(128)
                                               ^
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-bOrzFz/confluent-kafka/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TSG_1G-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-armv6l-2.7

creating build/lib.linux-armv6l-2.7/confluent_kafka

copying confluent_kafka/__init__.py -> build/lib.linux-armv6l-2.7/confluent_kafka

creating build/lib.linux-armv6l-2.7/confluent_kafka/kafkatest

copying confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-armv6l-2.7/confluent_kafka/kafkatest

copying confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-armv6l-2.7/confluent_kafka/kafkatest

copying confluent_kafka/kafkatest/__init__.py -> build/lib.linux-armv6l-2.7/confluent_kafka/kafkatest

copying confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-armv6l-2.7/confluent_kafka/kafkatest

running build_ext

building 'confluent_kafka.cimpl' extension

creating build/temp.linux-armv6l-2.7

creating build/temp.linux-armv6l-2.7/confluent_kafka

creating build/temp.linux-armv6l-2.7/confluent_kafka/src

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c confluent_kafka/src/confluent_kafka.c -o build/temp.linux-armv6l-2.7/confluent_kafka/src/confluent_kafka.o

In file included from confluent_kafka/src/confluent_kafka.c:17:0:

confluent_kafka/src/confluent_kafka.h:197:32: error: unknown type name ‘rd_kafka_topic_partition_list_t’

 PyObject *c_parts_to_py (const rd_kafka_topic_partition_list_t *c_parts);

                                ^

confluent_kafka/src/confluent_kafka.h:198:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’

 rd_kafka_topic_partition_list_t *py_to_c_parts (PyObject *plist);

 ^

confluent_kafka/src/confluent_kafka.c: In function ‘KafkaError_name’:

confluent_kafka/src/confluent_kafka.c:74:2: warning: implicit declaration of function ‘rd_kafka_err2name’ [-Wimplicit-function-declaration]

  return cfl_PyUnistr(_FromString(rd_kafka_err2name(self->code)));

  ^

In file included from confluent_kafka/src/confluent_kafka.c:17:0:

confluent_kafka/src/confluent_kafka.c:74:34: warning: passing argument 1 of ‘PyUnicodeUCS4_FromString’ makes pointer from integer without a cast

  return cfl_PyUnistr(_FromString(rd_kafka_err2name(self->code)));

                                  ^

confluent_kafka/src/confluent_kafka.h:71:38: note: in definition of macro ‘cfl_PyUnistr’

 #define cfl_PyUnistr(X) PyUnicode ## X

                                      ^

In file included from /usr/include/python2.7/Python.h:85:0,

                 from confluent_kafka/src/confluent_kafka.h:17,

                 from confluent_kafka/src/confluent_kafka.c:17:

/usr/include/python2.7/unicodeobject.h:281:31: note: expected ‘const char *’ but argument is of type ‘int’

 # define PyUnicode_FromString PyUnicodeUCS4_FromString

                               ^

/usr/include/python2.7/unicodeobject.h:477:23: note: in expansion of macro ‘PyUnicode_FromString’

 PyAPI_FUNC(PyObject*) PyUnicode_FromString(

                       ^

confluent_kafka/src/confluent_kafka.c: In function ‘TopicPartition_new’:

confluent_kafka/src/confluent_kafka.c:551:21: error: ‘RD_KAFKA_OFFSET_INVALID’ undeclared (first use in this function)

  long long offset = RD_KAFKA_OFFSET_INVALID;

                     ^

confluent_kafka/src/confluent_kafka.c:551:21: note: each undeclared identifier is reported only once for each function it appears in

confluent_kafka/src/confluent_kafka.c: At top level:

confluent_kafka/src/confluent_kafka.c:746:32: error: unknown type name ‘rd_kafka_topic_partition_list_t’

 PyObject *c_parts_to_py (const rd_kafka_topic_partition_list_t *c_parts) {

                                ^

confluent_kafka/src/confluent_kafka.c: In function ‘c_parts_to_py’:

confluent_kafka/src/confluent_kafka.c:750:28: error: request for member ‘cnt’ in something not a structure or union

  parts = PyList_New(c_parts->cnt);

                            ^

confluent_kafka/src/confluent_kafka.c:752:26: error: request for member ‘cnt’ in something not a structure or union

  for (i = 0 ; i < c_parts->cnt ; i++) {

                          ^

confluent_kafka/src/confluent_kafka.c:753:9: error: unknown type name ‘rd_kafka_topic_partition_t’

   const rd_kafka_topic_partition_t *rktpar = &c_parts->elems[i];

         ^

confluent_kafka/src/confluent_kafka.c:753:54: error: request for member ‘elems’ in something not a structure or union

   const rd_kafka_topic_partition_t *rktpar = &c_parts->elems[i];

                                                      ^

In file included from /usr/include/python2.7/Python.h:100:0,

                 from confluent_kafka/src/confluent_kafka.h:17,

                 from confluent_kafka/src/confluent_kafka.c:17:

confluent_kafka/src/confluent_kafka.c:756:12: error: request for member ‘topic’ in something not a structure or union

      rktpar->topic, rktpar->partition,

            ^

/usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’

 #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))

                                                                          ^

confluent_kafka/src/confluent_kafka.c:756:27: error: request for member ‘partition’ in something not a structure or union

      rktpar->topic, rktpar->partition,

                           ^

/usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’

 #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))

                                                                          ^

confluent_kafka/src/confluent_kafka.c:757:12: error: request for member ‘offset’ in something not a structure or union

      rktpar->offset, rktpar->err));

            ^

/usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’

 #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))

                                                                          ^

confluent_kafka/src/confluent_kafka.c:757:28: error: request for member ‘err’ in something not a structure or union

      rktpar->offset, rktpar->err));

                            ^

/usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’

 #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))

                                                                          ^

confluent_kafka/src/confluent_kafka.c: At top level:

confluent_kafka/src/confluent_kafka.c:769:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’

 rd_kafka_topic_partition_list_t *py_to_c_parts (PyObject *plist) {

 ^

confluent_kafka/src/confluent_kafka.c: In function ‘py_to_c_parts’:

confluent_kafka/src/confluent_kafka.c:770:2: error: unknown type name ‘rd_kafka_topic_partition_list_t’

  rd_kafka_topic_partition_list_t *c_parts;

  ^

confluent_kafka/src/confluent_kafka.c:779:2: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_new’ [-Wimplicit-function-declaration]

  c_parts = rd_kafka_topic_partition_list_new((int)PyList_Size(plist));

  ^

confluent_kafka/src/confluent_kafka.c:779:10: warning: assignment makes pointer from integer without a cast

  c_parts = rd_kafka_topic_partition_list_new((int)PyList_Size(plist));

          ^

confluent_kafka/src/confluent_kafka.c:790:4: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_destroy’ [-Wimplicit-function-declaration]

    rd_kafka_topic_partition_list_destroy(c_parts);

    ^

confluent_kafka/src/confluent_kafka.c:794:3: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_add’ [-Wimplicit-function-declaration]

   rd_kafka_topic_partition_list_add(c_parts,

   ^

confluent_kafka/src/confluent_kafka.c:796:23: error: invalid type argument of ‘->’ (have ‘int’)

         tp->partition)->offset =

                       ^

confluent_kafka/src/confluent_kafka.c: In function ‘error_cb’:

confluent_kafka/src/confluent_kafka.c:832:3: warning: implicit declaration of function ‘rd_kafka_yield’ [-Wimplicit-function-declaration]

   rd_kafka_yield(h->rk);

   ^

confluent_kafka/src/confluent_kafka.c: In function ‘producer_conf_set_special’:

confluent_kafka/src/confluent_kafka.c:973:13: error: ‘rd_kafka_msg_partitioner_consistent’ undeclared (first use in this function)

      tconf, rd_kafka_msg_partitioner_consistent);

             ^

confluent_kafka/src/confluent_kafka.c:976:13: error: ‘rd_kafka_msg_partitioner_consistent_random’ undeclared (first use in this function)

      tconf, rd_kafka_msg_partitioner_consistent_random);

             ^

In file included from confluent_kafka/src/confluent_kafka.c:17:0:

confluent_kafka/src/confluent_kafka.c:1003:6: error: ‘RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED’ undeclared (first use in this function)

      RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED,

      ^

confluent_kafka/src/confluent_kafka.h:98:35: note: in definition of macro ‘cfl_PyErr_Format’

   PyObject *_eo = KafkaError_new0(err, __VA_ARGS__); \

                                   ^

confluent_kafka/src/confluent_kafka.c: In function ‘common_conf_setup’:

confluent_kafka/src/confluent_kafka.c:1178:2: warning: implicit declaration of function ‘rd_kafka_conf_set_default_topic_conf’ [-Wimplicit-function-declaration]

  rd_kafka_conf_set_default_topic_conf(conf, tconf);

  ^

confluent_kafka/src/confluent_kafka.c: In function ‘KafkaError_add_errs’:

confluent_kafka/src/confluent_kafka.c:1299:2: warning: implicit declaration of function ‘rd_kafka_get_err_descs’ [-Wimplicit-function-declaration]

  rd_kafka_get_err_descs(&descs, &cnt);

  ^

confluent_kafka/src/confluent_kafka.c:1335:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   if (!descs[i].desc)

   ^

confluent_kafka/src/confluent_kafka.c:1335:13: error: dereferencing pointer to incomplete type

   if (!descs[i].desc)

             ^

confluent_kafka/src/confluent_kafka.c:1338:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   code = PyLong_FromLong(descs[i].code);

   ^

confluent_kafka/src/confluent_kafka.c:1338:31: error: dereferencing pointer to incomplete type

   code = PyLong_FromLong(descs[i].code);

                               ^

confluent_kafka/src/confluent_kafka.c:1340:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   PyDict_SetItemString(dict, descs[i].name, code);

   ^

confluent_kafka/src/confluent_kafka.c:1340:35: error: dereferencing pointer to incomplete type

   PyDict_SetItemString(dict, descs[i].name, code);

                                   ^

confluent_kafka/src/confluent_kafka.c:1344:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   _PRINT("| %-*.*s | %-*.*s |\n"

   ^

confluent_kafka/src/confluent_kafka.c:1346:33: error: dereferencing pointer to incomplete type

          _COL1_W, _COL1_W, descs[i].name,

                                 ^

confluent_kafka/src/confluent_kafka.c:1313:43: note: in definition of macro ‘_PRINT’

   _len = snprintf(tmpdoc, sizeof(tmpdoc), __VA_ARGS__); \

                                           ^

confluent_kafka/src/confluent_kafka.c:1344:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’

   _PRINT("| %-*.*s | %-*.*s |\n"

   ^

confluent_kafka/src/confluent_kafka.c:1347:33: error: dereferencing pointer to incomplete type

          _COL2_W, _COL2_W, descs[i].desc,

                                 ^

confluent_kafka/src/confluent_kafka.c:1313:43: note: in definition of macro ‘_PRINT’

   _len = snprintf(tmpdoc, sizeof(tmpdoc), __VA_ARGS__); \

                                           ^

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-bOrzFz/confluent-kafka/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TSG_1G-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-bOrzFz/confluent-kafka
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 75: ordinal not in range(128)

**Comment by edenhill** [comment]
It looks like your librdkafka verison is too old, confluent-kafka-python requires v0.9.1 or later. What version are you on?
`dpkg -l librdkafka-dev`

**Comment by alvarodecastro74** [comment]
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  librdkafka-dev 0.8.5-2      armhf        library implementing the Apache K

**Comment by edenhill** [comment]
That's really old :)
See if you can find a newer version, e.g.:
http://mirrordirector.raspbian.org/raspbian/pool/main/libr/librdkafka/

**Comment by alvarodecastro74** [comment]
ok I did and now it says 
dpkg -i librdkafka-dev_0.9.1-1_armhf.deb
(Reading database ... 144353 files and directories currently installed.)
Preparing to unpack librdkafka-dev_0.9.1-1_armhf.deb ...
Unpacking librdkafka-dev:armhf (0.9.1-1) over (0.8.5-2) ...
dpkg: dependency problems prevent configuration of librdkafka-dev:armhf:
 librdkafka-dev:armhf depends on librdkafka1 (= 0.9.1-1); however:
  Version of librdkafka1:armhf on system is 0.8.5-2.
 librdkafka-dev:armhf depends on librdkafka++1 (= 0.9.1-1); however:
  Package librdkafka++1 is not installed.

dpkg: error processing package librdkafka-dev:armhf (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 librdkafka-dev:armhf

**Comment by edenhill** [comment]
You will need to install the dependencies, download all the 0.9.1 debs and try this:
`dpkg -i librdkafka.*0.9.1*deb`

**Comment by alvarodecastro74** [comment]
This is a nightmare to install. After I downloaded librdkafka++1 from https://packages.debian.org/sid/armhf/librdkafka++1/download now it says  
================
librdkafka++1:armhf depends on librdkafka1 (>= 0.9.1); however:
  Version of librdkafka1:armhf on system is 0.8.5-2.
 librdkafka++1:armhf depends on libssl1.0.2 (>= 1.0.2d); however:
  Package libssl1.0.2 is not installed.
 librdkafka++1:armhf depends on libstdc++6 (>= 5.2); however:
  Version of libstdc++6:armhf on system is 4.9.2-10.

I installed the kafka-python package and did not have to install all these hard to find packages. I appreciate the effort you guys put into this, but I have a life to live, so thanks :)

**Comment by jeffwidman** [comment]
Just want to say @edenhill I appreciate the work you put into being extra supportive in your answers even when the issue clearly isn't your code. As an open source maintainer, I know it's not always easy.

**Comment by renatosc** [comment]
This is how I was able to install confluent kafka in Raspberry Pi.

Downloaded the librdkafka files from the  [http://mirrordirector.raspbian.org/raspbian/pool/main/libr/librdkafka/](http://mirrordirector.raspbian.org/raspbian/pool/main/libr/librdkafka/) . The files downloaded were:
```
librdkafka++1_0.11.6-1.1_armhf.deb
librdkafka1_0.11.6-1.1_armhf.deb
librdkafka-dev_0.11.6-1.1_armhf.deb
```

then installed them by doing:
```
sudo dpkg -i librdkafka1*0.11.6*deb
sudo dpkg -i librdkafka++*0.11.6*deb
sudo dpkg -i librdkafka-dev*0.11.6*deb
```

after that I was able to install confluent-kafka-python by doing:
`pip install confluent_kafka`

**Comment by sylwekdec** [comment]
I tried to install confluent-kafka on Rpi, using provided solution, however I get errors:

 In file included from confluent_kafka/src/confluent_kafka.c:17:
  confluent_kafka/src/confluent_kafka.h:55:2: error: #error "confluent-kafka-python requires librdkafka v1.0.0 o                       r later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/                       current/installation.html"
   #error "confluent-kafka-python requires librdkafka v1.0.0 or later. Install the latest version of librdkafka                        from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
    ^~~~~
  confluent_kafka/src/confluent_kafka.c: In function ‘error_cb’:
  confluent_kafka/src/confluent_kafka.c:1226:20: error: ‘RD_KAFKA_RESP_ERR__FATAL’ undeclared (first use in this                        function); did you mean ‘RD_KAFKA_RESP_ERR__FAIL’?
           if (err == RD_KAFKA_RESP_ERR__FATAL) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~
                      RD_KAFKA_RESP_ERR__FAIL
  confluent_kafka/src/confluent_kafka.c:1226:20: note: each undeclared identifier is reported only once for each                        function it appears in
  confluent_kafka/src/confluent_kafka.c:1228:23: warning: implicit declaration of function ‘rd_kafka_fatal_error                       ’; did you mean ‘rd_kafka_last_error’? [-Wimplicit-function-declaration]
                   err = rd_kafka_fatal_error(rk, errstr, sizeof(errstr));
                         ^~~~~~~~~~~~~~~~~~~~
                         rd_kafka_last_error
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for confluent-kafka
  Running setup.py clean for confluent-kafka
Failed to build confluent-kafka


Librdkafka-dev is installed - i verified it with pykafka with (use_rdkafka=True) parameter.
And also apt-get tells me:
sudo apt-get install librdkafka-dev python                       -dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
librdkafka-dev is already the newest version (0.11.6-1.1).
python-dev is already the newest version (2.7.16-1).
0 upgraded, 0 newly installed, 0 to remove and 87 not upgraded

I'm looking forward for any ideas.

cheers
Sylwester

**Comment by edenhill** [comment]
You need librdkafka v1.0.0 or later.
If it is not available in your distro, uninstall the package and build it from source using the instructions [here](https://github.com/edenhill/librdkafka#build-from-source)

**Comment by kush-13** [comment]
> You need librdkafka v1.0.0 or later.
> If it is not available in your distro, uninstall the package and build it from source using the instructions [here](https://github.com/edenhill/librdkafka#build-from-source)

Thanks for the help .. It worked for me.

**Comment by sinonkt** [comment]
@edenhill Build from source, solved issue in my case (on Ubuntu over WSL).
