### ISSUE TITLE
describe_config for group doesnt appear to work

### ISSUE THREAD

**Issue by chrispward** [confluentinc/confluent-kafka-python#1033]
Description
===========
calling admin.describe_config to get group config.
ret = describe_configs(resources=[ConfigResource(restype=3, name='test')], request_timeout=180)
I get back
KafkaError{code=_BAD_MSG,val=-199,str="DESCRIBECONFIGS worker failed to parse response: DescribeConfigs response protocol parse failure: Local: Bad message format"}

if I trace this to the logs on kafka, the error is reported as 
[2021-02-12 22:00:51,023] ERROR [KafkaApi-1] Error when handling request: clientId=xxxxx, correlationId=3, api=DESCRIBE_CONFIGS, version=1, body={resources=[{resource_type=0,resource_name=test,config_names=null}],include_synonyms=true} (kafka.server.KafkaApis)
org.apache.kafka.common.errors.InvalidRequestException: Unexpected resource type UNKNOWN for resource test

note: Getting broker info and topic info works just fine.

How to reproduce
================
call admin api get config passing in resource type of 3 and a group
ret = describe_configs(resources=[ConfigResource(restype=3, name='test')], request_timeout=180)

Checklist
=========
Please provide the following information:
python confluent-kafka 1.6.0 

kafka 2.4.0 
using docker image -  docker pull confluentinc/cp-kafka:5.5.1
python verison 3.7.6
OS is windows 10 but we get the same issue when we run it in our docker container using latest python slim 3.7

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I don't think there's any config to be described for the group resource type.

**Comment by chrispward** [comment]
well there is a test in the code for it.
https://github.com/confluentinc/confluent-kafka-python/blob/master/tests/test_Admin.py  (line 225)
    fs = a.describe_configs([ConfigResource(confluent_kafka.admin.RESOURCE_TOPIC, "mytopic"),
                             ConfigResource(confluent_kafka.admin.RESOURCE_GROUP, "mygroup")],
                            request_timeout=0.123)
Also, why define the enums ie  confluent_kafka.admin.RESOURCE_GROUP if it cant be used. It implies it can be.

**Comment by edenhill** [comment]
That test is just a dumb API test to test timeouts.

We define all resources as future versions of the broker may support them.

**Comment by mhowlett** [comment]
this is a design decision shared with the Java client. you can expect similar things from other parts of the Admin API. i would usually prefer the api enforce allowed operations as your expecting, but the approach does simplify implementation of admin operations significantly and is at least consistent.
