### ISSUE TITLE
SASL Kerberos/GSSAPI without manual build please

### ISSUE THREAD

**Issue by bobbymlp** [confluentinc/confluent-kafka-python#1036]
Description
===========

I observe the following note on the README

NOTE: The pre-built Linux wheels do NOT contain SASL Kerberos/GSSAPI support. If you need SASL Kerberos/GSSAPI support you must install librdkafka and its dependencies using the repositories below and then build confluent-kafka using the command in the "Install from source from PyPi" section below.

Installing from source is not easy and requiresd root access on all development machines, I don't understand why the main wheel is not packaged with Kerberos support it is used in many corporate environments.

Can the standard wheel just come with this packaged?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ X] Critical issue

**Comment by edenhill** [comment]
confluent-kafka-python depends on the C library librdkafka, which in turn depends on cyrus-sasl/libsasl2 for GSSAPI support, which in turn depends on the mit or heimdal kerberos plugins.
While we successfully bundle most of librdkafka's dependencies (such as openssl), the way cyrus-sasl is constructed makes it complex and error-prone to bundle, and not recommended by cyrus-sasl itself:
https://www.cyrusimap.org/sasl/sasl/advanced.html

**Comment by bobbymlp** [comment]
Thanks for the insight Magnus.

If I understand correctly, were you to package cyrus with statically linked dependencies for the auth mechanisms, if any other library loaded in the same python runtime relied on dynamic linked to drop in a new auth mechanism they would run into trouble and by building locally we can retain the benefits of dynamic linking.

**Comment by pranavrth** [comment]
Closing this issue as the question is answered. Please open it again or raise a new issue if required.
