### ISSUE TITLE
Is it possible to pass metadata when committing offsets?

### ISSUE THREAD

**Issue by th-ch** [confluentinc/confluent-kafka-python#1039]
Description
===========
A Kafka offset commit message includes [optional metadata](https://kafka.apache.org/0100/protocol.html#protocol_messages) and some implementations (eg confluent-kafka-go) have an [optional metadata field](https://pkg.go.dev/github.com/confluentinc/confluent-kafka-go/kafka#TopicPartition) but it seems the Python implementation has [no metadata field in TopicPartition](https://confluent-kafka-python.readthedocs.io/en/latest/#confluent_kafka.TopicPartition.TopicPartition) - is there a way to pass metadata when committing offsets with the Python package?

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`1.4.0`)

**Comment by milindl** [comment]
Closing this, with merge of #1410
