### ISSUE TITLE
1.6.0 - subscribe fails when partition.assignment.strategy=cooperative-sticky

### ISSUE THREAD

**Issue by MiBaranowski** [confluentinc/confluent-kafka-python#1040]
When I try to specify partition.assignment.strategy=cooperative-sticky I get the following error during subscribe (the code does not use assign directly)

```
Group grp1": application *assign() call failed: Changes to the current assignment must be made using incremental_assign() or incremental_unassign() when rebalance protocol type is COOPERATIVE
```

confluent_kafka version 1.6.0
broker version: 2.6.0

The code works without any problems when partition.assignment.strategy is set to range or roundrobin

**Comment by edenhill** [comment]
We messed up the release notes, py 1.6.0 does not yet support incremental rebalancing, but the upcoming 1.6.1 release will.

**Comment by MiBaranowski** [comment]
Thanks for the info! Is there any planned date for 1.6.1?

**Comment by edenhill** [comment]
1.6.1 has been released
