### ISSUE TITLE
Getting Error "Unknown topic or partition" after upgrading to 1.6.0 from consumer when subscribing nonexistent topics

### ISSUE THREAD

**Issue by yanchunwang** [confluentinc/confluent-kafka-python#1041]
Description
===========
I am trying to upgrade the confluent-kafka to 1.6.0 to work with broker 5.5.3. I got the "Unknown topic or partition" exception when subscribe a message topic before it is created. I tried to add the following config in the avro consumer config
`'allow.auto.create.topics': True`
And I am sure the broker is enabled to auto create topics with
`auto.create.topics.enable = true`
I found the similar issue in this post for dotnet but could not find a working solution
https://github.com/confluentinc/confluent-kafka-dotnet/issues/1366 

I tried to use a admin client to create the topics before I subscribe it, and there is no exception after it sleeps for a little while before subscribing the message topic. However, this is not the solution we are after.

How to reproduce
================
Using confluent-kafka 1.6.0 to subscribe a nonexistent message topic. 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.6.0
 - [ ] Apache Kafka broker version: 5.5.3
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Ubuntu
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The proper solution is to handle (e.g., ignore) the exception.

**Comment by yanchunwang** [comment]
> The proper solution is to handle (e.g., ignore) the exception.

Thank you very much @edenhill . Just wondering shall I retry to subscribe the topic after receiving this exception?

**Comment by edenhill** [comment]
No, the subscription persists and it will automatically pick up the missing topic if it becomes available (metadata is queried every topic.metadata.refresh.interval.ms)

**Comment by hrchu** [comment]
@edenhill it's quite confusing. It will be better to remove `allow.auto.create.topics`  if you do not want users to use it.
