### ISSUE TITLE
Subscribe method does not support negative lookaheads in topic regex

### ISSUE THREAD

**Issue by minzey** [confluentinc/confluent-kafka-python#1044]
Description
===========
By definition, topics argument of consumer.subscribe() supports regular expressions. But when I pass a regex having a negative lookahead, I get the following error:
<img width="984" alt="Screenshot 2021-03-01 at 5 23 00 PM" src="https://user-images.githubusercontent.com/12856258/109494937-948e7c80-7ab4-11eb-8358-4142d089dff3.png">

My intention is to exclude certain topics by ensuring that regex expression for them evaluates to False.

How to reproduce
================
Set topics to `^((?!exclude_topic_substring).)*$`

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version = ('1.3.0', 16974079)
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Linux
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
On OSX and Linux we use the libc regex implementation (`man 3 regcomp`) and that's the feature set we're limited to.

You can use the `topic.blacklist` config property to filter out specific topics by regex.
