### ISSUE TITLE
How can i get the subscription relationship between consumer groups and topics? 

### ISSUE THREAD

**Issue by htaoji1988** [confluentinc/confluent-kafka-python#1045]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Use `client.list_groups()` to get a list of groups, and list_topics() to get all topics and partitions in the cluster and `client.get_watermark_offsets()` for the given topics.

Then for each consumer group instantiate a new consumer with the corresponding `group.id`, create a TopicPartition list to query committed offsets for and then call `c.committed()` to retrieve the committed offsets.
Subtract the committed offsets from the high watermark to get the consumer lag.
