### ISSUE TITLE
Undefined symbol: rd_kafka_consumer_group_metadata_write

### ISSUE THREAD

**Issue by sim-azan** [confluentinc/confluent-kafka-python#1047]
Description
===========
Get above error on 'from confluent_kafka.cimple import Consumer as _ConsumerImpl

How to reproduce
================
Download latest https://github.com/edenhill/librdkafka/archive/v1.6.1.zip
./configure --prefix=/usr
make
make install

Download latest confluent https://github.com/confluentinc/confluent-kafka-python/archive/v1.6.0.zip
python3 setup.py install

On importing still get above error.
Also tried with older versions of both packages i.e.1.5.0 but still same error

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version(1.6.0)` and `confluent_kafka.libversion(1.6.1)`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: Ubuntu 20.04.2 LTS
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
My guess is that you have a ubuntu package of librdkafka installed which is an older version.
Purge that first, then install librdkafka from source.

**Comment by sim-azan** [comment]
> My guess is that you have a ubuntu package of librdkafka installed which is an older version.
> Purge that first, then install librdkafka from source.

Hi Eden, thanks for your reply. I had checked this already and reinstalled librdkafka from source, and also confluent-kafka from source. But this error doesn't go away. I even tried using older versions of libdrkafka 1.5.0 and confluent but in vain. I also read that to use --prefix usr while .configure but that did not help either.

**Comment by edenhill** [comment]
Do a `find / -name librdkafka.so.1 2>/dev/null` and look for files that shouldn't be there.

**Comment by sim-azan** [comment]
> Do a `find / -name librdkafka.so.1 2>/dev/null` and look for files that shouldn't be there.

This is the output. Should these 2 files not be there?

find / -name librdkafka.so.1 2>/dev/null

/usr/lib/librdkafka.so.1
/usr/local/lib/librdkafka.so.1
/home/sim/.local/share/Trash/files/librdkafka-1.5.6.1/src/librdkafka.so.1
/home/sim/.local/share/Trash/files/librdkafka-1.4.6.1/src/librdkafka.so.1

**Comment by edenhill** [comment]
Recommend removing both of those in /usr..., and the corresponding rdkafka.h, and the reinstalling from source

**Comment by sim-azan** [comment]
Thanks eden. All seems to be working now.
