### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by chrisbeard** [confluentinc/confluent-kafka-python#1050]
Description
===========
The project URL (http://docs.confluent.io/current/clients/confluent-kafka-python) redirects to https://docs.confluent.io/home/overview.html, which is a generic confluent landing page.

The same URL is also in README.md under the [title](https://github.com/confluentinc/confluent-kafka-python/blob/928f75d0eafa621d5b3ff93913b05791a424e1be/README.md#confluents-python-client-for-apache-kafkatm):
```
See the [API documentation](http://docs.confluent.io/current/clients/confluent-kafka-python/index.html) for more info.
```

Also a heads up (though the docs are maintained outside of this project) - once you do navigate to the docs (https://docs.confluent.io/clients-confluent-kafka-python/current/overview.html), the links to "API Documentation" in the "Initialization" sections of the [producer](https://docs.confluent.io/clients-confluent-kafka-python/current/overview.html#initialization) and [consumer](https://docs.confluent.io/clients-confluent-kafka-python/current/overview.html#id1) are also broken.

**Comment by edenhill** [comment]
Thanks! We'll look into it
