### ISSUE TITLE
Unable to connect to confluent cloud with SASL Authentication

### ISSUE THREAD

**Issue by stripthesoul** [confluentinc/confluent-kafka-python#1051]
Description
===========
When I try to create a Producer or Consumer to use with confluent cloud, the following exception occurs:

%3|1615388646.769|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://pkc-xxxxx.us-east-1.aws.confluent.cloud:9092/bootstr]: sasl_ssl://pkc-xxxxx.us-east-1.aws.confluent.cloud:9092/bootstrap: SSL handshake failed: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (brew install openssl) (after 186ms in state CONNECT)

How to reproduce
================

Just try to instantiate a producer or consumer:

p = Producer({
    'bootstrap.servers': "pkc-xxxxx.us-east-1.aws.confluent.cloud:9092",
    'sasl.mechanism': 'PLAIN',
    'security.protocol': 'SASL_SSL',
    'sasl.username': 'username',
    'sasl.password': 'password',
    'linger.ms': 100
})

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version: confluent-kafka-python version 1.6.0
 - [x] Apache Kafka broker version: Confluent Cloud
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Recommend using certifi:
```python
import certifi

...
p = Producer({
...
 "ssl.ca.location": certifi.where()
})
```

**Comment by stripthesoul** [comment]
Resolved as per @edenhill  comment above
