### ISSUE TITLE
ProtobufSerializer is slow

### ISSUE THREAD

**Issue by bobbymlp** [confluentinc/confluent-kafka-python#1053]
I intent to use confluent kafka in python to produce batches of messages, writing tens of thousands of messages in bursts and I know the that underlying librdkafka library has no problem but the ProtobufSerializer takes around 20-30ms per record to serialise them and the records are small

I note you write performance is  "on par with the Java client for larger message sizes (where the overhead of the Python interpreter has less impact)"

Do you expect protobuf serialisation to be slow and any advise on how to quickly send thousands of records using this library?

**Comment by edenhill** [comment]
What's the approx message/object size for the 20-30ms / msg messages?

**Comment by bobbymlp** [comment]
around 100 bytes

**Comment by edenhill** [comment]
Okay, then I'm guessing it is not the actual serialization that  takes 20-30ms (unless you're on a 486), but that schema is registered with the schema-registry: however, unless each message has its own schema this should only happen once (per schema type).

**Comment by bobbymlp** [comment]
Is this a bug in your code or my usage. I see known_subjects is checked but not updated

https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/schema_registry/protobuf.py

it is being updated on the avro version?

**Comment by bobbymlp** [comment]
What is the eta to have this fix released? It is a very small change I can make the PR if you like

**Comment by mhowlett** [comment]
please do a PR and i'll review

**Comment by mbonnefoy** [comment]
Hi @mhowlett @bobbymlp,

I noticed the same problem while doing some performance profiling on the `ProtobufSerializer`.
I've opened a pull request for it.

Thanks,
Matthieu

**Comment by rvinzent** [comment]
Any updates on this?

**Comment by bobbymlp** [comment]
The issue was fixed in june here: https://github.com/confluentinc/confluent-kafka-python/pull/1133

But there hasn't been a release since, you can apply a patch locally if you really need this

**Comment by pranavrth** [comment]
This was released with the above PR in v1.8.2. Closing this issue.
