### ISSUE TITLE
ytest show test durations

### ISSUE THREAD

**Issue by rr-arnon-cohen** [confluentinc/confluent-kafka-python#1063]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Can you please provide more details on Description?

**Comment by rr-arnon-cohen** [comment]
I have no idea what is this issue. I don't remember opening this issue. You can close it.

**Comment by jliunyu** [comment]
> I have no idea what is this issue. I don't remember opening this issue. You can close it.

Thanks for your reply @rr-arnon-cohen
