### ISSUE TITLE
`avro-python3` is deprecated

### ISSUE THREAD

**Issue by frndlytm** [confluentinc/confluent-kafka-python#1067]
Description
===========
It seems like `avro-python3` was recently deprecated in favor of the base `avro` library according to the README below; however, `confluent-kafka` depends on `avro-python3`.

https://github.com/apache/avro/tree/master/lang/py3

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for bringing this to our attention, care to create a PR?

**Comment by frndlytm** [comment]
Haven't investigated the scope of the change much, but I can potentially throw something together outside working hours.

**Comment by jliunyu** [comment]
PR for this one: https://github.com/confluentinc/confluent-kafka-python/pull/1212

**Comment by pranavrth** [comment]
Closing as this is already merged.
