### ISSUE TITLE
Consumer starts from the wrong offset, going back in time

### ISSUE THREAD

**Issue by basvdl** [confluentinc/confluent-kafka-python#1069]
Description
===========
We are running 31 pods, each running a consumer fetchiinig data from Azure Eventhub. The topic has 31 partitions, and the data is partitioned by a key. The retention is set to 3 days. The consumers use manual commit.

We were running 1.4.2, yesterday we upgraded to 1.6.0, but the same behaviour was seen.

Around the time we redeploy our code, we see strange behaviour of consumers picking up the wrong offset and consuming "old" data. It looks like this:

```
At: 2021-03-18 08:47:50,613	pod: e2e-7b9978dd68-lj96l	consumes partition: 3	processing msg 20210318T075054Z

Another pod takes over the same partition, but the message is from previous day
At: 2021-03-18 08:48:02,602	pod: e2e-7b9978dd68-4cj6x	consumes partition: 3	processing msg 20210317T113556Z

The same pod reports a message from March 18 again
At: 2021-03-18 08:48:04,863	pod: e2e-7b9978dd68-4cj6x	consumes partition: 3	processing msg 20210318T075044Z

All pods were redeployed (see ID in pod name) and it continues processing messages from the previous day
At: 2021-03-18 08:48:29,792	pod: e2e-798d985565-zk7d5	consumes partition: 3	processing msg 20210317T113606Z
```

To back this up we started to monitor the `committed_offset` for the consumers in this consumer group per partition. And after deploying the code a couple of times we see that for random partitions the lag went from 0 (before re-deploy) to 8.000 (after re-deploy) for instance. We also see that the `committed_offset` reported by the consumer is dropped by the same number as the lag (from 494k back to 486k). During the deployment, takes around 10 min, the ingest speeds is around 24 msg per minute per partition.

How to reproduce
================
In our situation a redeploy of the code (trigger ci/cd) or scale down/up of the k8s deployment is enough to see this behaviour. The longer the time between redeploy the bigger the drop back we see in `committ_offset`. I was able to reproduce it around 5-6 times on our ACP environment in the last days.

Seen it in our PRD  and ACP  environment, which a separated env but running all the same versions of k8s, python libs, etc.

On DEV I have not seen this yet, we run at smaller scale with only a subset of data, with 2 partiitons.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Run the consumer with `"debug": "consumer"` (or `"cgrp"` for more details) set to see how it gathers the starting offset.

**Comment by basvdl** [comment]
For partition 6, after a redeploy, the offset is is dropped from 1336794 to 1336387

```
2021-03-19 19:29:49		e2e-865d4f4f88-8ghcm	%7|1616178589.202|FETCH|e2e#consumer-1| [thrd:main]: Partition unified-images [6] start fetching at offset 1336387 
2021-03-19 19:22:54		e2e-86d759db48-fxght	%7|1616178174.261|FETCH|e2e#consumer-1| [thrd:main]: Partition unified-images [6] start fetching at offset 1336794 
2021-03-19 19:21:19		e2e-86d759db48-ln2lg	%7|1616178079.551|FETCH|e2e#consumer-1| [thrd:main]: Partition unified-images [6] start fetching at offset 1336768 
2021-03-19 19:20:55		e2e-86d759db48-t9l2t	%7|1616178055.161|FETCH|e2e#consumer-1| [thrd:main]: Partition unified-images [6] start fetching at offset 1336758 
2021-03-19 19:19:54		e2e-86d759db48-ln2lg	%7|1616177994.358|FETCH|e2e#consumer-1| [thrd:main]: Partition unified-images [6] start fetching at offset 1336733 
2021-03-19 19:17:54		e2e-86d759db48-ln2lg	%7|1616177874.401|FETCH|e2e#consumer-1| [thrd:main]: Partition unified-images [6] start fetching at offset 1336728 
2021-03-19 19:16:15		e2e-86d759db48-ln2lg	%7|1616177775.680|FETCH|e2e#consumer-1| [thrd:main]: Partition unified-images [6] start fetching at offset 1336716 
```

**Comment by basvdl** [comment]
Sorry for the confusion, but I think we have found the problem after lots of debugging... In our application we keep a cache of 5 message. For every new message we push the oldest out and commit this manually...

Why we went back in time...


```
POD A - Partition 0

cache [5, 4, 3, 2, 1]
cache [6, 5, 4, 3, 2] commit 1

# POD B takes over Partition 0, and fills the cache


POD B - Partition 0

cache [6, 5, 4, 3, 2]
cache [7, 6, 5, 4, 3] commit 2
cache [8, 7, 6, 5, 4] commit 3
...many messages later...
cache [800, 799, 798, 797, 796] commit 795


# POD A takes over Partition 0 from were POD B stopped, but in memory the old cache [6, 5, 4, 3, 2] still exists

POD A - Partition 0

cache [796, 6, 5, 4, 3] commit 2
```


The way we solved this is to use the revoke callback. If i'm not mistaken, as soon as a consumer leaves the group, this callback is triggered on all the consumers in the group. At that moment we empty the cache within the pods.


Apologies for the confusion.
