### ISSUE TITLE
Consumer.close() blocks all threads

### ISSUE THREAD

**Issue by bjustin-ibm** [confluentinc/confluent-kafka-python#107]
I am working on a multi-threaded application with many consumers, each running in their own thread. I have noticed that calling `close()` from any thread completely blocks all threads, leaving my application otherwise unresponsive until the call to `close()` completes.

Gist showing the problem: https://gist.github.com/bjustin-ibm/5cacbefc969bc2fcfccb7b81cce3f450

confluent-kafka 0.9.2
librdkafka 0.9.2

**Comment by bjustin-ibm** [comment]
For what it's worth, this issue combined with https://github.com/edenhill/librdkafka/issues/1002 (which I am also experiencing) results in the entire application becoming indefinitely unresponsive due to a consumer being closed.

**Comment by ewencp** [comment]
Hmm, we do unlock the GIL before invoking the underlying C close function. @edenhill Is it possible the `rd_kafka_destroy()` that is called after `CallState_end` is blocking?

**Comment by edenhill** [comment]
@ewencp Yeah, destroy might block for some time waiting for internal threads and sockets to clean up.
So that should be an easy fix for the GIL, but the underlying librdkafka hang needs to be fixed too.
