### ISSUE TITLE
Question: Slowness in the consumer polling due to One Topic-One Partition- Four consumers with different group IDs

### ISSUE THREAD

**Issue by Udayaprasad** [confluentinc/confluent-kafka-python#1070]
Description
===========
I have the following situation with my consumer_app code.

1) Producer code pushes the sequence of image frames from Video (cv2.VideoOpened()) to a single Topic having a single partition (To maintain image sequences we had set unique key while producing images)
2) Consumer code has 4 Consumers (Threads), each having its own unique Group ID to poll the same message/image for each consumer.

Due to this above design, I saw slowness in the consumer reading (4 Consumers looking for one partition data). Is there a way to optimize the consumer polling?

We need this design to maintain video sequence at the same time each consumer thread will go through its own unique AI model to generate the stats.

@edenhill  Please suggest

================

Checklist
=========
Please provide the following information:

 - [X ] confluent-kafka-python and librdkafka version (1.5.0):
 - [ X] Apache Kafka broker version: (confluentinc/cp-kafka:5.5.3)
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If all threaded consumers read from the same partition, why not use a single consumer and then do thread-fanout?

**Comment by Udayaprasad** [comment]
Yeah, Let me try this design. Thank you for the quick suggestion.
