### ISSUE TITLE
Is it possible to implement a custom assignment strategy with this library?

### ISSUE THREAD

**Issue by MetcalfeTom** [confluentinc/confluent-kafka-python#1071]
Description
===========

We're trying to use bucket priorities as recommended by [Confluent](https://www.confluent.io/blog/prioritize-messages-in-kafka/) for our broker, but by using any of the given assignment strategies (`range`, `roundrobin` and in 1.6.1 `cooperative-sticky`) we're likely to encounter idle consumers (e.g. when one bucket is empty).

It would be better to have each consumer assigned minimum 3 partitions (i.e. two from platinum, one from gold) but I don't see where to write this code or access the `PartitionAssignor` in `confluent-kafka`

**Comment by MetcalfeTom** [comment]
I managed to do it:

1. Subscribe to a topic, with an `on_assign` callback to your `custom_assign()` function
2. `custom_assign()` then gets the member IDs from the Admin's `GroupMetadata` and the topics/partitions from the `TopicMetadata`
3. Implement your assignment strategy from these, returning mappings of `{member_id: strategy_assigned_partitions}`
4. Find the consumer's list of partitions from these mappings with `client.id`
5. Run `consumer.assign(strategy_assigned_partitions)`

One tricky part was that `librdkafka` adds a UUID to the `client.id` which is never returned to the Python client.  Would you consider saving this via some `consumer.client_id` property in future?

**Comment by Cap7Carps** [comment]
Hey, how were you able to access the Admin GroupMetadata from within the callback?

The only parameters available are the `consumer` and the `partitions`. The only relevant looking method I can see is on the consumer - `consumer_group_metadata()`, but this returns an un-useful binary.

I am hoping to achieve the following: Let Kafka do it's standard auto-assignment, but once the assignments are complete, use some custom logic to set the offset.

Would be great to see your implementation. Thanks

**Comment by karimtemsah** [comment]
@MetcalfeTom can you please post a sample code for what you did?

**Comment by MetcalfeTom** [comment]
Sure, it relies on a class instance so I've tried to recreate a minimum working example here, hope it's helpful!

```python
import logging
from typing import Dict, List

from confluent_kafka import DeserializingConsumer, TopicPartition
from confluent_kafka.admin import (
    AdminClient,
    ClusterMetadata,
    GroupMetadata,
    TopicMetadata,
)

logger = logging.getLogger(__name__)


class KafkaService:
    """Message broker which consumes from a Kafka topic."""

    def __init__(
        self,
        kafka_conf: Dict,
        input_topic: str = "some-topic",
        client_id: str = "some-id",
        group_id: str = "group-id",
    ):
        self.admin = AdminClient(kafka_conf)
        self.input_topic = input_topic
        self.client_id = client_id
        self.group_id = group_id

        self.consumer.subscribe([self.input_topic], on_assign=self.on_assign)

    def on_assign(
        self, consumer: DeserializingConsumer, assignment: List[TopicPartition]
    ):
        """Runs assignment strategies."""
        cluster_metadata: ClusterMetadata = self.admin.list_topics()
        topic_metadata: TopicMetadata = cluster_metadata.topics[self.input_topic]
        partitions = [
            TopicPartition(topic=self.input_topic, partition=partition)
            for partition in topic_metadata.partitions
        ]

        # you need to code this bit.  i've left the return types in for assistance
        # your function returns a dictionary of member IDs to assigned partitions
        # you can get member IDs with:
        #     group_metadata: GroupMetadata = [g for g in self.admin.list_groups() if g.id == self.group_id][0]
        #     member_ids = [m.client_id for m in group_metadata.members]
        group_assignment: Dict[str, List[TopicPartition]] = custom_assignment_strategy(
            partitions
        )

        assignment = [
            assignment
            for member_id, assignment in group_assignment.items()
            if member_id == self.client_id
        ][0]
        self.consumer.assign(assignment)
        logger.info(
            f"Consumer partitions updated to {[tp.partition for tp in assignment]}"
        )

```

**Comment by karimtemsah** [comment]
Thank you so much for your detailed response, I will try it out :)

**Comment by pranavrth** [comment]
Closing this as there is no issue here and the author is able to achieve what was required.
