### ISSUE TITLE
confluent_kafka.error.ValueSerializationError: KafkaError{code=_VALUE_SERIALIZATION,val=-161 

### ISSUE THREAD

**Issue by hegdemahendra** [confluentinc/confluent-kafka-python#1072]
Description
===========

I am new bee to python and trying to use 'confluent_kafka' for avro message produce. Using 'confluent_kafka.schema_registry.avro.AvroSerializer' for the same (referred : https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_producer.py)

It works for simple avro schema with dict(json converted to dict) input, but for below sample schema I am getting error :

**Schema** :
{
	"type": "record",
	"name": "Envelope",
	"namespace": "CoreOLTPEvents.dbo.Event",
	"fields": [{
		"name": "before",
		"type": ["null", {
			"type": "record",
			"name": "Value",
			"fields": [{
				"name": "EventId",
				"type": "long"
			}, {
				"name": "CameraId",
				"type": ["null", "long"],
				"default": null
			}],
			"connect.name": "CoreOLTPEvents.dbo.Event.Value"
		}],
		"default": null
	}, {
		"name": "after",
		"type": ["null", "Value"],
		"default": null
	}, {
		"name": "source",
		"type": {
			"type": "record",
			"name": "Source",
			"namespace": "io.debezium.connector.sqlserver",
			"fields": [{
				"name": "version",
				"type": "string"
			}, {
				"name": "connector",
				"type": "string"
			}],
			"connect.name": "io.debezium.connector.sqlserver.Source"
		}
	}, {
		"name": "op",
		"type": "string"
	}],
	"connect.name": "CoreOLTPEvents.dbo.Event.Envelope"
}

**Input JSON** :
{
    "after": null,
    "before": {
        "CoreOLTPEvents.dbo.Event.Value" : {
        "EventId": 1111111111,
        "CameraId": 222222222
    }
    },
    "source": {
        "version": "InitialLoad",
        "connector": "sqlserver"
    },
    "op": "C"
}

**Error** : ValueError: {'CoreOLTPEvents.dbo.Event.Value': {'EventId': 1111111111, 'CameraId': 222222222}} (type <class 'dict'>) do not match ['null', {'connect.name': 'CoreOLTPEvents.dbo.Event.Value', 'type': 'record', 'name': 'CoreOLTPEvents.dbo.Event.Value', 'fields': [{'name': 'EventId', 'type': 'long'}, {'default': None, 'name': 'CameraId', 'type': ['null', 'long']}]}] on field before

'before' field type is union (['null',record]), if I change it to only record (remove union) then it works fine. But I need to adjust my input such a way that it works for given schema.

(Note : I am reading json input using 'json.load(json_file)' so it gives dict output)

Any help would be much appreciated.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.6.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by hegdemahendra** [comment]
Solved.

**Comment by prakhara-kumar** [comment]
Do you mind elaborating a bit, as to how did you solve this issue?
