### ISSUE TITLE
invisible "offset committer", or: consumer ignores messages prior to its start-up

### ISSUE THREAD

**Issue by mushkevych** [confluentinc/confluent-kafka-python#1075]
Description
===========
We have been using Kafka for close to 5 years now; recently we moved from `pykafka` to 
`confluent-kafka-python`. At the same time we upgraded most of our stack (Kafka, kafka-connector, python, etc) and noticed an interesting phenomena. 
Out of two dozen topic and consumers, we have one that started behaving strangely. 

It has the same "config" as others:
```
kafka-configs.sh --bootstrap-server localhost:9092 --entity-type topics --describe --entity-name 36363636-fim-raw
Dynamic configs for topic 36363636-fim-raw are:
  retention.ms=2592000000 sensitive=false synonyms={DYNAMIC_TOPIC_CONFIG:retention.ms=2592000000}
```

but the Consumer is "ignoring the messages" unless they were published while it is up and listening. In other words - the code `message = consumer.poll(timeout=1)` returns `None` always, unless the message arrives while the consumer is subscribed.

Otherwise, the consumer behaves as if there are no offsets to consume, while there are:
```
python -m kafka_partitions localhost fim-message-enrichment-transformer 36363636-fim-raw
Topic [Partition]                                   Committed        Lag
========================================================================
36363636-fim-raw [0]                                        -          1
36363636-fim-raw [1]                                        -         92
36363636-fim-raw [2]                                        -          0
36363636-fim-raw [3]                                        -          0
36363636-fim-raw [4]                                        -          0
36363636-fim-raw [5]                                        -          1
36363636-fim-raw [6]                                        -          0
36363636-fim-raw [7]                                        -          0
36363636-fim-raw [8]                                        -          0
36363636-fim-raw [9]                                        1          0
36363636-fim-raw [10]                                       -          1
36363636-fim-raw [11]                                       -          0
36363636-fim-raw [12]                                       -          1
36363636-fim-raw [13]                                       -          0
36363636-fim-raw [14]                                       -          0
36363636-fim-raw [15]                                       -          1
```

To debug this issue I have used manual message publishing with:
```
/usr/lib/ironwood/kafka/bin/kafka-console-producer.sh --topic 36363636-fim-raw --bootstrap-server localhost:9092
```

_Important note_: due to budget restrictions this environment is using a single-node Kafka installation. In other words - there is a single Kafka broker. 

I am leaning towards thinking that this is a form of "mis-configuration". 
Perhaps you have seen similar synopsis before?

How to reproduce
================
NA

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```
 confluent_kafka.version()
('1.6.0', 17170432)
 confluent_kafka.libversion()
('1.6.0', 17170687)

```
 
 - [X] Apache Kafka broker version:
 ```
 sudo kafka-server-start.sh --version
2.7.0 (Commit:448719dc99a19793)
 ```
 
 - [X] Client configuration: 
 ```
 {
   "bootstrap.servers":"127.0.0.1:9092",
   "api.version.request":true,
   "broker.address.family":"v4",
   "group.id":"fim-message-enrichment-transformer",
   "session.timeout.ms":300000,
   "heartbeat.interval.ms":30000,
   "auto.offset.reset":"latest",
   "enable.auto.commit":false,
   "enable.auto.offset.store":true,
   "fetch.max.bytes":33554432,
   "receive.message.max.bytes":34603008,
   "on_commit":**<function commit_callback at 0x7fe6ed9c97b8>**,
   "partition.assignment.strategy":"range,roundrobin"
}
```
 - [X] Operating system: CentOS 7
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
With auto.offset.reset=latest and no previously committed offsets your consumer will start consuming at the end of the partition.

**Comment by mushkevych** [comment]
i think it was the combination of the 
```
  "auto.offset.reset":"latest",
  "enable.auto.commit":false,
```
which i changed to [earliest](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)
```
  "auto.offset.reset":"earliest",
  "enable.auto.commit":false,
```
