### ISSUE TITLE
Parameters in the Consumer.consume() API

### ISSUE THREAD

**Issue by liweixi100** [confluentinc/confluent-kafka-python#1076]
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Consumer.consume

I'm trying to use `Consumer.consume()` to get a batch of messages for parallel processing. 

How are the `num_messages` and `timeout` parameters related to the `fetch.min.bytes` and `fetch.wait.max.ms` configurations? 

(Based on this [thread](https://github.com/confluentinc/confluent-kafka-python/issues/580), the Python client internally gets batched messages from the broker; so it would be important to understand the relationship among these parameters.)

**Comment by edenhill** [comment]
They are unrelated.
The configuration parameters control the internal fetcher's pre-fetching into a fetch queue.
num_messages and timeout parameters only tells the consume() call how to grab messages from the fetch queue.
