### ISSUE TITLE
Backwards incompatible change in v1.6.1

### ISSUE THREAD

**Issue by Incognito** [confluentinc/confluent-kafka-python#1078]
Description
===========

The argument order in the constructor signature for AvroSerializer was altered in v1.6.1 

```
-    def __init__(self, schema_str, schema_registry_client,
+    def __init__(self, schema_registry_client, schema_str,
```

[link to diff](https://github.com/confluentinc/confluent-kafka-python/compare/v1.6.0...v1.6.1#diff-cefb407efbfa0dc0896f90edd1f27281b539205e51f8f06ed4794635ebfad736R274)

It's an unexpected change for teams who want a simple bugfix, and perhaps can't even modify some internals if the package is in-directed elsewhere (like some wrapper package for example)

I think any one of these options would make this less painful for package consumers:

- revoke tag 1.6.1 and release a backwards-compatible 1.6.2 (it may be too late, especially if people already upgraded)
- Update all docs to exclusively use kwargs as a best-practice to avoid this issue in the future.
- Enforce kwargs in the next major
- Add release linting tools to the CI pipeline that inspects changes and prevents backwards-incompatible changes in patch releases (I could try to help with it if you want to use some AST parsing).

How to reproduce
================

Upgrade to the latest patch level.

**Comment by dangreenisrael** [comment]
Kind of related: A static analysis tool that could detect backwards incompatible changes in CI would be awesome. Although, building it one off does seem out of scope for this project.

**Comment by rterry123** [comment]
Thanks for brining up this issue. The docs show the original argument order and I had no idea what I was doing wrong.

**Comment by mhowlett** [comment]
apologies - it was me who let that through in #1000. the rational was this is an improvement, AvroSerializer is designed to be used with SerializingProducer, and that class is still marked as experimental (apologies also that that is dragging out so long).

the docs are auto-generated from the code, and are currently at v1.5. we evidently need to get that automated as part of the release process as well.

leaving this issue open for the list of suggestions.

**Comment by Incognito** [comment]
Thanks for the background, I think it's a common thing that happens in lots of software packages.

There's another few possibilities I didn't mention above (I don't like these options as much).

- There could be tests for everything that is considered public API, but it also means that the person doing the change has to be in the mindset of "this test isn't to check that it functions, its to check that it is backwards compatible", usually this doesn't scale so I don't like it too much.
- Two packages, one for stable code and one for experimental code. I haven't read all the code in confluent-kafka-python so I don't how how realistic that is, it also adds development overhead.
- Two branches, one for stable code and one for experimental code.
- Have someone who is specifically responsible for ensuring all changes are backwards-compatible (not reviewing code, but focused on just that task), but this will slow down your development process and add overhead

**Comment by mhowlett** [comment]
yes, ideally we would have process like this - it's just a case of resourcing.

letting the change through was an explicit tradeoff I made between possibly causing a headache for a relatively small number of users now, vs everyone in the future, and the experimental marking on SerializaingProducer is what I took as the license to do this - if not for that I wouldn't have. we generally try to strictly adhere to semver.

**Comment by slominskir** [comment]
For fellow Googlers, the symptom in your log output is:

`AttributeError: 'SchemaRegistryClient' object has no attribute 'strip'`

I couldn't find the 1.6.1 API docs, so I couldn't quickly determine what the parameter order was supposed to be.   We need to get the 1.6.1 API docs released soon.

**Comment by slominskir** [comment]
The symptom for AvroDeserializer is:

`TypeError: the JSON object must be str, bytes or bytearray, not SchemaRegistryClient`
