### ISSUE TITLE
Are there any python APIs to do custom partitioning?

### ISSUE THREAD

**Issue by moneymase19** [confluentinc/confluent-kafka-python#1083]
Description
===========
I need to do custom partitioning because I'm working with video frames, need each partition to have video frames from only one source

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Not yet, but it is on our backlog.

Dup of #847
