### ISSUE TITLE
Deserializing consumer consume method is not implemented for bulk processing

### ISSUE THREAD

**Issue by Egg3141592654** [confluentinc/confluent-kafka-python#1084]
Description
===========
The documentation (and source code for the DeserializingConsumer is not implemented. For our use case, this makes adoption of the new deserialization consumer much more challenging over the legacy avroconsumer classes. Suggest implementation as attached in order to assist in adoption of new classes.

How to reproduce
================
- Create a DeserializingConsumer
- Call consume
- Exception thrown every time

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka-python version:1.6.1 librdkafka version: 1.6.1
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Linux (Centos76 + Ubuntu 20)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by Egg3141592654** [comment]
Awkward, I actually have a branch with an implementation but cannot push to repository... Will try to work on getting that branch linked to this issue

**Comment by Egg3141592654** [comment]
https://github.com/confluentinc/confluent-kafka-python/pull/1085 finally got it up

**Comment by nhaq-confluent** [comment]
Seems like the PR was closed, if this issue is still persisting, please open a new issue.
