### ISSUE TITLE
API Documentation pointing to 1.5.0 version

### ISSUE THREAD

**Issue by Harish-Sridhar** [confluentinc/confluent-kafka-python#1089]
In the README, the API Documentation link is pointing to version `1.5.0`.
Shouldn't this take to version `1.6.0`?

**Comment by mhowlett** [comment]
yes. we'll make sure this is fixed when we release 1.7.0, which is due soon.

**Comment by edenhill** [comment]
Let's close this when it is fixed, or we'll lose track of it.

**Comment by jliunyu** [comment]
API Documentation is pointing to v1.7.0 version now
