### ISSUE TITLE
Get sticky_assignor fix from librdkafka into python

### ISSUE THREAD

**Issue by jinoobaek-qz** [confluentinc/confluent-kafka-python#1090]
Description
===========

Can we get https://github.com/edenhill/librdkafka/commit/1b40aadfc2b2734299d79dbfb17717822e03d33b in a supported version in the python library?

I'm seeing a massive amount (100+ / second) of rebalances for an extended period of time (hours) when I use

```
 'partition.assignment.strategy': 'cooperative-sticky'
```

I wonder if this is the cause. I have also tried adjusting the session.timeout.ms and heartbeat.interval.ms as well with no luck.

How to reproduce
================

Deploy an app with 30+ consumers within the consumer group using v1.6.1

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version: 2.5.1
 - [x] Client configuration: `{'partition.assignment.strategy': 'cooperative-sticky'}`
 - [ ] Operating system: debian
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
there will be various fixes related to cooperative rebalancing in 1.7.0, which isn't too far away - we're currently testing RCs.
