### ISSUE TITLE
Producer.produce() runs infinitely if kafka is not started

### ISSUE THREAD

**Issue by selvakumaar5496** [confluentinc/confluent-kafka-python#1091]
Description
===========
Producer retries in an infinite loop. Is it possible to stop this after few seconds? and how to catch this exception

%3|1618842270.700|FAIL|sel#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1618842271.701|FAIL|sel#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1618842271.704|FAIL|sel#producer-2| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1618842272.701|FAIL|sel#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)

How to reproduce
================
Do not start kafka services. 
Initialize producer client Producer{'bootstrap.servers': 'localhost:9092'}
Call Producer.produce()

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python 1.5.0 
 - [ ] Apache Kafka broker version: kafka_2.13-2.7.0
 - [ ] Client configuration: `{'bootstrap.servers': 'localhost:9092'}`
 - [ ] Operating system: centos 7
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You can set up an error_cb and trigger on the `_ALL_BROKERS_DOWN` error code, which will be triggered from poll() or flush().

**Comment by mhowlett** [comment]
recurring conversation... but we should prioritize adding a blocking client initialize as a significant UX win, particularly as it's something new users often hit.

**Comment by diamo1213** [comment]
```
from confluent_kafka import Producer

#NO kafka server on 'localhost:9092

def onErr(err, msg):
  print(err, msg)

p = Producer({'bootstrap.servers': 'localhost:9092'})
print('Test connection..')
p.produce('', '', on_delivery=onErr)
```

the code sticks in loop of p = Producer({'bootstrap.servers': 'localhost:9092'}) !!!

how to test if kafka server is avilable?

why confluent kafka producer just don't rise some exception if server is unavailable in init time of Producer?
