### ISSUE TITLE
(Benchmark) High throughput but high latency

### ISSUE THREAD

**Issue by Manu10744** [confluentinc/confluent-kafka-python#1102]
Description
===========
I am trying to measure throughput and latency of Kafka using the `confluent-kafka-python` client. To start with a simple architecture, i am having Producer, Broker and Consumer running on the same machine (VM). 
The Broker is using `LogAppendTime`stamps for the messages, and the consumer is comparing it to the consumer time, so the current time using `time.time() * 1000`.

I am sending JSON data (tweets), each around 600 Bytes, 1 GB in total (1.448.500 messages).
The Problem now is, i am measuring around 80 MB/s on the producer side as throughput, which is quite nice considering i only have one producer. BUT: The consumer latency is going up to 200-300 ms in the 90% percentile, when i set up multiple executions of the benchmark ( = multiple GBs ) it is even worse.

For each received message, i only extract the timestamp, calculate the difference, and put the result into a list. So the message processing time also isnt be causing this, is it?

You can see my consumer and producer code here: https://github.com/Manu10744/Stream-Analytics/tree/master/kafka/analytics/one_broker

At first i thought that my consumer cannot keep up with the producer. So i measured the time (the throughput) also on the consumer side. And my results say that the Producer needed around 12 seconds to produce 1 GB and the Consumer needed also around ~12-13 seconds to consume 1 GB, so it looks like my consumer does not really have a problem to keep up with the Producer.

I would really be happy if somebody could help me with this, im relatively new to Streaming and i cannot tell what could be causing this high latency.

Note that i kept everything to the standard settings.

### Hardware:
2 VCPUs
9 GB RAM
1 GBit / s Bandwidth

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent_kafka says `('1.6.1', 17170688)` and for the libversion `('1.6.1', 17170943)`
 - [x] Apache Kafka broker version: 2.7.0
 - [x] Client configuration:
```python
 consumer_config = {
    "bootstrap.servers": "localhost:9092",
    "group.id": twitter-consumers,
    "client.id": "client-1",
    "enable.auto.commit": True,
    "session.timeout.ms": 6000,
    "default.topic.config": {"auto.offset.reset": "smallest"}
}
```
 - [x] Operating system: Ubuntu 20.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I think it'd be good to break down the latencies to see where they're coming from, and with the current LogAppendTime you have the part between the broker appending to the log until the application sees the message from the consumer.
To get the latency of the producing part you should extract the message.latency() in your delivery report callback.

Two other things:
 - librdkafka (which the python client is using under the hood) uses a bunch of internal threads for each client instance, we recommend a host with at least 4 vCPUs.
 - your consume loop has a consume timeout of zero, which means it will busy-loop when there are no messages (such as on the initial rebalance or when the consumer has catched up) - suggest using a timeout of 0.5s or so instead to avoid the busy looping.

**Comment by Manu10744** [comment]
Thank you for your quick answer @edenhill 

I upgraded my VM to 18 GB RAM and 4 vCPUs and start the Broker, Consumer and Producer there.
I noticed significant increase in throughput on both sides (MB/s, Messages/s) and also the latency finally decreased by a good bit. 

I started 5 executions á 1GB and:
Message Processing Speed is now 150k msgs / s instead of 100k
In 2 cases max latency is now ~120ms instead of 300-350ms
In 3 cases max latency is about 50ms

I really didnt know that CPU is so important for the consumer, lessons learned. Worst case latency of 120 is not bad but im sure i can decrease it even more, i think i am gonna test with 10 vCPUS and 45GB RAM, thats the maximum i can use on that cloud.

Another problem might be the network speed that seems to jump back and forth:

```python
for i in range(5):
    !curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
```

```bash
Retrieving speedtest.net configuration...
Testing from Leibniz-Rechenzentrum (138.246.3.42)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by JStorfingerDE (Munich) [3.67 km]: 15.905 ms
Testing download speed................................................................................
Download: 2030.20 Mbit/s
Testing upload speed......................................................................................................
Upload: 306.04 Mbit/s
Retrieving speedtest.net configuration...
Testing from Leibniz-Rechenzentrum (138.246.3.42)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by JStorfingerDE (Munich) [3.67 km]: 13.744 ms
Testing download speed................................................................................
Download: 733.62 Mbit/s
Testing upload speed......................................................................................................
Upload: 238.89 Mbit/s
Retrieving speedtest.net configuration...
Testing from Leibniz-Rechenzentrum (138.246.3.42)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by JStorfingerDE (Munich) [3.67 km]: 13.545 ms
Testing download speed................................................................................
Download: 731.36 Mbit/s
Testing upload speed......................................................................................................
Upload: 248.57 Mbit/s
Retrieving speedtest.net configuration...
Testing from Leibniz-Rechenzentrum (138.246.3.42)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by JStorfingerDE (Munich) [3.67 km]: 13.397 ms
Testing download speed................................................................................
Download: 2011.52 Mbit/s
Testing upload speed......................................................................................................
Upload: 270.91 Mbit/s
Retrieving speedtest.net configuration...
Testing from Leibniz-Rechenzentrum (138.246.3.42)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by JStorfingerDE (Munich) [3.67 km]: 14.578 ms
Testing download speed................................................................................
Download: 1565.18 Mbit/s
Testing upload speed......................................................................................................
Upload: 895.82 Mbit/s
```

But that's ok for now, im happy with the results
I don't want to finetune this until its 100% perfect but rather measure the performance of kafka as it comes out of the box, but i will check out if there is something i can adjust to improve the results.
Thank you very much for helping

**Comment by Manu10744** [comment]
@edenhill 
After adding one more broker to the cluster (10 vCPUs each) i noticed much worse consumer latency, here i used one topic, two brokers, two partitions while using 2 producers and 2 consumers running at the same time:
![image](https://user-images.githubusercontent.com/38779302/116575163-afdc0380-a90e-11eb-8d16-cfb05521f49b.png)
![image](https://user-images.githubusercontent.com/38779302/116575318-d26e1c80-a90e-11eb-88ba-b0a8b0fe243e.png)

When using 4 vCPUs for each broker, i dont get such weird results. It kinda seems like the brokers time to store and send records takes too long. I tried with increasing the `num.network.threads` but no luck. Any suggestions?

**Comment by edenhill** [comment]
Not really, I recommend monitoring CPU and network utilization as well as IO wait on the broker host.

**Comment by Manu10744** [comment]
Seems like i forgot to use `LogAppendTime` on the other broker(s), now the results make sense again in my 2 and 3 broker setup.
I dont know why, because according to my understanding, there shouldnt be much time between CreateTime and LogAppendTime but whatever.
Closing this, thanks for all the help
