### ISSUE TITLE
AdminClient class is missing Py function for `list_topics`

### ISSUE THREAD

**Issue by JeffreyGreenII** [confluentinc/confluent-kafka-python#1103]
Description
===========
`_AdminClientImpl` supports `list_topics`, which is a helpful function to have available on the Py equivalent `AdminClient`. While you can access it, it's be great if the Py class had these functions included, so that the documentation could be more consistent and other tools (such as IDE's) could auto-complete these Py functions.

How to reproduce
================
**Missing documentation**
If you read through the documentation listed below, you'll find no documentation for `list_topics`, even though the function exists on the Py class during runtime: https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html?highlight=clustermetadata#confluent_kafka.admin.AdminClient
**Auto-complete IDE's**
If using an IDE which can use a Python interpreter and have one of the `confluent-kafka` packages installed (we're using `confluent-kafka[avro]==1.6.0`), instantiate an `AdminClient` and it will not autocomplete the `list_topics` function (eg. `client.list_topics` would not auto-complete)

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
The documentation part is already fixed with https://github.com/confluentinc/confluent-kafka-python/pull/1101, will verify the auto-complete IDE part

**Comment by jliunyu** [comment]
Fix is merged to master: https://github.com/confluentinc/confluent-kafka-python/pull/1121
