### ISSUE TITLE
calling producer.produce() twice creates topic

### ISSUE THREAD

**Issue by selvakumaar5496** [confluentinc/confluent-kafka-python#1106]
Description
===========
calling producer.produce() creates topic and sends message. Why Unknown Topic or Partition error is raised ?

How to reproduce
================
Initialize Producer:

def send(producer, topic):
    producer.produce(topic, bytes("This is my message", 'utf-8')) #sending message as bytes

if __name__ == '__main__':
    try:
        producer = Producer({'bootstrap.servers': 'localhost:9092')}
        send(producer, 'my-topic')
    except Exception as e:
        time.sleep(10)
        send(producer, 'my-topic')

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python (`confluent_kafka.version(1.5.0)`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{'bootstrap.servers': 'localhost:9092'}`
 - [ ] Operating system: Centos
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
See this example for how to structure your producer, and then try to reproduce on the latest released version.
https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/producer.py
