### ISSUE TITLE
Plan to implement StreamsPartitionAssignor

### ISSUE THREAD

**Issue by g-clef** [confluentinc/confluent-kafka-python#1108]
Hello,

Are there any plans on the roadmap to allow python clients to use the Kafka Streams `StreamsPartitionAssignor` as a `partition.assignment.strategy` value? 

My use case: We're running a Kafka-Streams-like architecture, but are not in a position to use Kafka Streams directly (too much Python infrastructure to support a one-off Java application), and we're outrunning aiokafka and faust's capacity, so we're looking to rebuild on the confluent kafka client. I'd rather avoid re-implementing something that Confluent has already built, so I was hoping to use the existing co-partitioning assignor within the confluent kafka python client. 

If that's not possible, I'll figure something out, but I thought I should ask before going down this road.

Thanks.

**Comment by mhowlett** [comment]
`StreamsPartitionAssignor` looks pretty substantial, and this hasn't come up before that i'm aware of, so I'd say it's unlikely we'd prioritize an implementation any time soon.

**Comment by g-clef** [comment]
Ok. Thanks.
