### ISSUE TITLE
Handling KafkaError._PARTITION_EOF 

### ISSUE THREAD

**Issue by poutyface** [confluentinc/confluent-kafka-python#1111]
Description
===========
When EOF of partitions, 
confluent_kafka.DeserializingConsumer raise KafkaException, on the other hand
confluent_kafka.Consumer sets KafkaError._PARTITION_EOF to  message's error code (e.g. msg.error().code() == KafkaError._PARTITION_EOF)

Why are the implementations different?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version(1.6.1)` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The DeserializingConsumer aims to streamline the usage to only return properly deserialized messages from poll(), and raise exceptions for everyhing else.
