### ISSUE TITLE
When will v1.7.0 be released for python binding?

### ISSUE THREAD

**Issue by sgjurano** [confluentinc/confluent-kafka-python#1118]
Description
===========
I have problems with cooperative-sticky consumer strategy (like https://github.com/edenhill/librdkafka/issues/3306), have been waiting for these fixes for a couple of months.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
confluent-kafka-python v1.7.0 released this morning: https://github.com/confluentinc/confluent-kafka-python/releases/tag/v1.7.0
