### ISSUE TITLE
rd_kafka_message_errstr: symbol not found 

### ISSUE THREAD

**Issue by dendisuhubdy** [confluentinc/confluent-kafka-python#1123]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
```
from .cimpl import (Consumer, # noqa
ImportError: Error relocating /usr/local/lib/python3.7/site-packages/confluent_kafka/cimpl.cpython-37m-x86_64-linux-gnu.so: rd_kafka_message_errstr: symbol not found
```

How to reproduce
================
On Alpine

```
apk --no-cache add bash gcc g++ musl-dev python3-dev linux-headers libffi-dev openssl-dev libstdc++ cargo librdkafka krb5-dev curl zeromq-dev
```

then install `confluent-kafka-python`

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

- [x] confluent-kafka-python: `v1.3.0`
 - [x] librdkafka version (release number or git tag): `v1.7.0`
 - [x] Apache Kafka version: 2.8.0
 - [x] librdkafka client configuration: 
 
```
    CONSUMER_CONFIG = {
                "auto.offset.reset": "earliest",
                "enable.auto.commit": False,
                "api.version.request": True,
                "session.timeout.ms": 60_000
            }
```
 - [x] Operating system: Alpine

**Comment by edenhill** [comment]
I believe your librdkafka version is too old, try upgrading to v1.6.1 or later.
