### ISSUE TITLE
Idempotent producer fails due to sequence desynchronization with broker when an offline broker rejoins the cluster

### ISSUE THREAD

**Issue by prashantochatterjee** [confluentinc/confluent-kafka-python#1128]
Description
===========
We have a 3-node Kafka cluster. Using an indempotent producer. Tested by bringing down a node while performing a bulk production of messages. The producer continues to work fine until the offline broker is brought up and rejoins the cluster.

How to reproduce
================
1. Produce messages in bullk
2. Bring down a node in a 3-node cluster
3. After the parition leaders are re-assigned, bring up the offline node.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 >>> confluent_kafka.version()
('1.5.0', 17104896)
>>> confluent_kafka.libversion()
('1.5.0', 17105151)
>>> 

 - [ ] Apache Kafka broker version: 2.2.2
 - [ ] Client configuration: `{'batch.num.messages': 1000, 'linger.ms': 500, 'enable.idempotence': true}` 
 - [ ] Operating system: RHEL 8.3
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 `%7|1621945621.703|DRAIN|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: ingestion-tracker [9] beginning partition drain: wait for outstanding requests to finish before producing to new leader
%7|1621945621.703|BROADCAST|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: Broadcasting state change
%7|1621945621.703|TOPBRK|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Topic ingestion-tracker [11]: joining broker (rktp 0x7fa320012ed0, 0 message(s) queued)
%7|1621945621.703|FETCHADD|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Added ingestion-tracker [11] to active list (6 entries, opv 0, 0 messages queued): joining
%7|1621945621.703|DRAIN|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: ingestion-tracker [11] beginning partition drain: wait for outstanding requests to finish before producing to new leader
%7|1621945621.703|BROADCAST|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: Broadcasting state change
%7|1621945621.703|TOPBRK|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Topic ingestion-tracker [12]: joining broker (rktp 0x7fa3200132b0, 0 message(s) queued)
%7|1621945621.703|FETCHADD|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Added ingestion-tracker [12] to active list (7 entries, opv 0, 0 messages queued): joining
%7|1621945621.703|DRAIN|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: ingestion-tracker [12] beginning partition drain: wait for outstanding requests to finish before producing to new leader
%7|1621945621.703|BROADCAST|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: Broadcasting state change
%7|1621945621.703|TOPPAR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [3] all in-flight requests drained from queue
%7|1621945621.703|TOPPAR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [5] all in-flight requests drained from queue
%7|1621945621.703|TOPPAR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [6] all in-flight requests drained from queue
%7|1621945621.703|TOPPAR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [9] all in-flight requests drained from queue
%7|1621945621.703|TOPPAR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [11] all in-flight requests drained from queue
%7|1621945621.703|TOPPAR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [12] all in-flight requests drained from queue
2021-05-25 12:27:08,473 [werkzeug:_log:Thread-3482] INFO - 192.168.133.147 - - [25/May/2021 12:27:08] "^[[32mOPTIONS /webhooks/hookid HTTP/1.0^[[0m" 308 -
2021-05-25 12:27:11,628 [werkzeug:_log:Thread-3483] INFO - 192.168.133.146 - - [25/May/2021 12:27:11] "^[[32mOPTIONS /webhooks/hookid HTTP/1.0^[[0m" 308 -
2021-05-25 12:27:18,945 [werkzeug:_log:Thread-3484] INFO - 192.168.133.147 - - [25/May/2021 12:27:18] "^[[32mOPTIONS /webhooks/hookid HTTP/1.0^[[0m" 308 -
2021-05-25 12:27:21,971 [werkzeug:_log:Thread-3485] INFO - 192.168.133.146 - - [25/May/2021 12:27:21] "^[[32mOPTIONS /webhooks/hookid HTTP/1.0^[[0m" 308 -
%7|1621945643.495|TOPPAR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [0] 1 message(s) in xmit queue (1 added from partition queue)
%7|1621945643.495|NEWPID|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: ingestion-tracker [0] changed PID{Invalid} -> PID{Id:1004,Epoch:0} with base MsgId 1
%7|1621945643.495|RESETSEQ|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: ingestion-tracker [0] resetting epoch base seq from 0 to 1
2021-05-25 12:27:23,499 [cfx_eventintegration.kafka_producer:_delivery_notification:Thread-3486] ERROR - Local: Unknown partition
NoneType: None
%7|1621945643.502|TOPPAR|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: inbound-alerts [8] 1 message(s) in xmit queue (1 added from partition queue)
%7|1621945643.999|PURGE|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Purging queues with flags queue,non-blocking
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Purged 0 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Purged 0 message(s) from 0 partition(s)
%7|1621945643.999|PURGE|rdkafka#producer-2| [thrd:192.168.133.146:9092/bootstrap]: 192.168.133.146:9092/1: Purging queues with flags queue,non-blocking
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.146:9092/bootstrap]: 192.168.133.146:9092/1: Purged 0 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.146:9092/bootstrap]: 192.168.133.146:9092/1: Purged 0 message(s) from 0 partition(s)
%7|1621945643.999|PURGE|rdkafka#producer-2| [thrd:192.168.133.147:9092/bootstrap]: 192.168.133.147:9092/2: Purging queues with flags queue,non-blocking
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.147:9092/bootstrap]: 192.168.133.147:9092/2: Purged 0 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.147:9092/bootstrap]: 192.168.133.147:9092/2: Purged 0 message(s) from 0 partition(s)
%7|1621945643.999|PURGE|rdkafka#producer-2| [thrd::0/internal]: :0/internal: Purging queues with flags queue,non-blocking
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd::0/internal]: :0/internal: Purged 0 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd::0/internal]: :0/internal: Purged 0 message(s) from 0 partition(s)
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:main]: Purged 0 message(s) from 0 UA-partition(s)
%7|1621945644.003|TOPPAR|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: inbound-alerts [8] 1 message(s) in xmit queue (0 added from partition queue)
%7|1621945644.003|PRODUCE|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: inbound-alerts [8]: Produce MessageSet with 1 message(s) (1456 bytes, ApiVersion 7, MsgVersion 2, MsgId 205, BaseSeq 204, PID{Id:1000,Epoch:0}, uncompressed)
%7|1621945644.003|SEND|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Sent ProduceRequest (v7, 1517 bytes @ 0, CorrId 30)
%7|1621945644.007|RECV|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Received ProduceResponse (v7, 58 bytes, CorrId 30, rtt 4.11ms)
%7|1621945644.007|MSGSET|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: inbound-alerts [8]: MessageSet with 1 message(s) (MsgId 205, BaseSeq 204) delivered
2021-05-25 12:27:23,504 [werkzeug:_log:Thread-3486] INFO - 192.168.133.146 - - [25/May/2021 12:27:23] "POST /webhooks/hookid/47a763bc-2032-47e6-b604-7917c8ab1913 HTTP/1.1" 200 -
%7|1621945643.876|TOPPAR|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: inbound-alerts [8] 1 message(s) in xmit queue (0 added from partition queue)
%7|1621945643.995|TOPPAR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [0] 1 message(s) in xmit queue (0 added from partition queue)
%7|1621945643.995|PRODUCE|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [0]: Produce MessageSet with 1 message(s) (1382 bytes, ApiVersion 7, MsgVersion 2, MsgId 1, BaseSeq 0, PID{Id:1004,Epoch:0}, uncompressed)
%7|1621945643.995|SEND|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Sent ProduceRequest (v7, 1446 bytes @ 0, CorrId 132)
%7|1621945643.999|RECV|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Received ProduceResponse (v7, 61 bytes, CorrId 132, rtt 3.75ms)
%7|1621945643.999|REQERR|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ProduceRequest failed: Broker: Broker received an out of order sequence number: explicit actions Permanent,MsgPossiblyPersisted
%7|1621945643.999|MSGSET|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: ingestion-tracker [0]: MessageSet with 1 message(s) (MsgId 1, BaseSeq 0) encountered error: Broker: Broker received an out of order sequence number (actions Permanent,MsgPossiblyPersisted)
%0|1621945643.999|FATAL|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: Fatal error: Broker: Broker received an out of order sequence number: ProduceRequest for ingestion-tracker [0] with 1 message(s) failed due to sequence desynchronization with broker 3 (PID{Id:1004,Epoch:0}, base seq 0, idemp state change 12069896ms ago, last partition error NO_ERROR (actions , base seq 0..0, base msgid 0, -1ms ago)
%7|1621945643.999|DRAIN|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: Beginning partition drain for PID{Id:1004,Epoch:0} epoch bump for 1 partition(s) with in-flight requests: message sequence gap
%7|1621945643.999|IDEMPSTATE|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: Idempotent producer state change Assigned -> DrainBump
%7|1621945643.999|DRAIN|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: All partitions drained, bumped epoch to PID{Id:1004,Epoch:1}
%7|1621945643.999|IDEMPSTATE|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: Denying state change DrainBump -> Assigned since a fatal error has been raised
%7|1621945643.999|IDEMPSTATE|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: Idempotent producer state change DrainBump -> FatalError
%7|1621945643.999|WAKEUP|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Wake-up
%7|1621945643.999|WAKEUP|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.147:9092/2: Wake-up
%7|1621945643.999|WAKEUP|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.146:9092/1: Wake-up
%7|1621945643.999|PURGE|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Purging queues with flags queue,non-blocking
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Purged 0 in-flight, 0 retry-queued, 0 out-queue, 0 partially--sent requests
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Purged 0 message(s) from 0 partition(s)
%7|1621945643.999|PURGE|rdkafka#producer-2| [thrd:192.168.133.146:9092/bootstrap]: 192.168.133.146:9092/1: Purging queues with flags queue,non-blocking
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.146:9092/bootstrap]: 192.168.133.146:9092/1: Purged 0 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.146:9092/bootstrap]: 192.168.133.146:9092/1: Purged 0 message(s) from 0 partition(s)
%7|1621945643.999|PURGE|rdkafka#producer-2| [thrd:192.168.133.147:9092/bootstrap]: 192.168.133.147:9092/2: Purging queues with flags queue,non-blocking
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.147:9092/bootstrap]: 192.168.133.147:9092/2: Purged 0 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:192.168.133.147:9092/bootstrap]: 192.168.133.147:9092/2: Purged 0 message(s) from 0 partition(s)
%7|1621945643.999|PURGE|rdkafka#producer-2| [thrd::0/internal]: :0/internal: Purging queues with flags queue,non-blocking
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd::0/internal]: :0/internal: Purged 0 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd::0/internal]: :0/internal: Purged 0 message(s) from 0 partition(s)
%7|1621945643.999|PURGEQ|rdkafka#producer-2| [thrd:main]: Purged 0 message(s) from 0 UA-partition(s)
%7|1621945644.003|TOPPAR|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: inbound-alerts [8] 1 message(s) in xmit queue (0 added from partition queue)
%7|1621945644.003|PRODUCE|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: inbound-alerts [8]: Produce MessageSet with 1 message(s) (1456 bytes, ApiVersion 7, MsgVersion 2, MsgId 205, BaseSeq 204, PID{Id:1000,Epoch:0}, uncompressed)
%7|1621945644.003|SEND|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Sent ProduceRequest (v7, 1517 bytes @ 0, CorrId 30)
%7|1621945644.007|RECV|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: Received ProduceResponse (v7, 58 bytes, CorrId 30, rtt 4.11ms)
%7|1621945644.007|MSGSET|rdkafka#producer-1| [thrd:192.168.133.148:9092/bootstrap]: 192.168.133.148:9092/3: inbound-alerts [8]: MessageSet with 1 message(s) (MsgId 205, BaseSeq 204) delivered
2021-05-25 12:27:48,243 [cfx_eventintegration.kafka_producer:send:Thread-3491] ERROR - KafkaError{code=_FATAL,val=-150,str="Unable to produce message: Local: Fatal error"}
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfx_eventintegration/kafka_producer.py", line 55, in send
    self.producer.produce(self.topic_name, key=partition_key, value=message, on_delivery=self._delivery_notification)
cimpl.KafkaException: KafkaError{code=_FATAL,val=-150,str="Unable to produce message: Local: Fatal error"}
`
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What's the confluent-kafka-python / librdkafka versions?

Have you tried reproducing this on a more up to date broker version?

**Comment by prashantochatterjee** [comment]
Updated the issue with confluent-kafka-python and librdkafka versions. 
We are tied with this Kafka version as our platform uses this version. Any specific enhancements in this area, in the later versions, that you think will help us if we update our Kafka broker?

Another concern is that the idempotence property seems to be getting violated in the simplest of test scenarios. We brought down Node-2 in our 3-node cluster. Waited for the system to stabilize, evict the offline node from ISRs and assign new partition leaders. All this while we have a script that is constantly pumping in alerts via a Kafka producer at the rate of ~ 270 messages per minute. When we bring up Node-2, the producer complains about this and does not proceed further as this is a FATAL error.

**Comment by edenhill** [comment]
This sounds more like an issue with the cluster. 2.2.2 is quite old and there's been plenty of fixes and improvements to idempotency and transactions since, so I strongly suggest that you try to reproduce this on the latest Kafka release with the latest librdkafka/confluent-kafka-python.

Even if you're stuck with 2.2.2 in production you can set up a simple test environment with a newer Kafka version.

> Another concern is that the idempotence property seems to be getting violated in the simplest of test scenarios
> ..
> When we bring up Node-2, the producer complains about this and does not proceed further as this is a FATAL error.

If the producer can't proceed without breaking the idempotent guarantees it will raise a fatal error, so this is actually not a violation but according to design.

**Comment by prashantochatterjee** [comment]
I see. Appreciate your response. 
I agree with your assessment that it is actually not a violation but honouring the idempotence guarantee. What I meant is that the producer goes into this unrecoverable state in a very basic HA scenario - an offline node rejoining the cluster. 
I will try the producer against a recent stable release and verify. For now, I will have to turn the idempotence property off as we are heading for production deployment.
Thanks once again for taking the time to respond and clarify.

**Comment by qagwaai** [comment]
we are also seeing this error running kafka 6.1.0

ProduceRequest for <ourtopicname> [0] with 1 message(s) failed due to sequence desynchronization with broker 2 (PID{Id:3,Epoch:0}, base seq 0, idemp state change 12557250ms ago, last partition error NO_ERROR (actions , base seq 0..0, base msgid 0, -1ms ago)

we have no choice but to restart kafka and our dependent service

**Comment by edenhill** [comment]
@qagwaai Does it occur out of the blue or in correlation with some other event, e.g., new broker coming up?
Is there anything in the broker logs?

**Comment by nhaq-confluent** [comment]
Do these issues still persist with the latest Kafka version and the latest client versions? @prashantochatterjee

**Comment by prashantochatterjee** [comment]
> Do these issues still persist with the latest Kafka version and the latest client versions? Can it be closed? @prashantochatterjee

@nhaq-confluent I have not retried this since. Let me give it another shot and revert.

**Comment by prashantochatterjee** [comment]
@nhaq-confluent I dont see the idempotence issues anymore when enabled on the producer with a single node down in a 3-node cluster. Thank you for following up.

![image](https://github.com/confluentinc/confluent-kafka-python/assets/33247561/d3b103bc-10f8-4142-a3b3-f8863ffc9d04)
