### ISSUE TITLE
When does a delivery callback called with an error?

### ISSUE THREAD

**Issue by anveshagarwal** [confluentinc/confluent-kafka-python#1137]
I want to know what are the scenarios when this delivery callback is called with an error? 

I tried to shut down the kafka broker server and then produce and flush the message say `msgA` . But the callback was not called for the message with the error, rather the next time when I flushed other messages with the Kafka broker running, then the successful delivery callback for the `msgA` came first. So it seems like messages keep waiting in queue. So in what case i will get a failed delivery? Shouldn't I get a failed delivery report for `msgA` in this case?

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability
