### ISSUE TITLE
problem in consume messages after rebalance

### ISSUE THREAD

**Issue by deerluffy** [confluentinc/confluent-kafka-python#1138]
Description
===========
I suspect if there is some local cache in the client, which leads to a consumer inherit  offset from local which should be inherit form the kafka server？my situation can be described as below.
I start up 8 process to consume a 2 partition topic. all process's 'enable.auto.commit'  is set to  false.

-  T1: **process-1 consuming partition-1  to offset 1001**, **process-2 consuming partition-2 to offset 1002**
-  T2: a rebalance happened, process-1 start consume  partition-2  from offset 1003, , process-2 start consume  partition-1  from offset 1001
-  T3: **process-1 consuming partition-2  to offset 3001**, **process-2 consuming partition-1 to offset 3002**
-  T4: a rebalance happened, **process-1 start consume  partition-1  from offset 1001 which  should be 3002 ,  process-2 start consume  partition-2  from offset 1002 which should be 3001**

How to reproduce
================
not stable reproduce

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python:1.4.2 and librdkafka version 1.4.2
 - [ 1.0] Apache Kafka broker version: 1.0
 - [ ] Client configuration: `        self.__config = {
            "bootstrap.servers": ",".join(self.__servers),
            "group.id": self.__group,
            "auto.offset.reset": "latest" if not self.__earliest else "earliest",
            "fetch.message.max.bytes": str(self.__fetch_max_bytes),
            "enable.auto.commit": "false"
        }`
 - [ ] Operating system: cenos7
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please upgrade to the latest version 1.7.0 and see if the problem persists.

**Comment by deerluffy** [comment]
@edenhill  thanks,  i will try. 
Before that , I wonder if there is local cache in the consumer client?  
 What are the reasons do you think? just for directions, thanks

**Comment by jliunyu** [comment]
Please feel free to reopen it if any help is still needed from our side.
