### ISSUE TITLE
Question: how to get the consumer id assigned by Kafka?

### ISSUE THREAD

**Issue by fra-luc** [confluentinc/confluent-kafka-python#1139]
Is there a way to get the consumer id from the instance of the Consumer object after having subscribed to a Kafka topic?

Thanks!

**Comment by edenhill** [comment]
librdkafka has a `rd_kafka_memberid()` function, but it is not exposed in the Python client.

Easy enough to add though.

**Comment by fra-luc** [comment]
Thank you!
