### ISSUE TITLE
What determines when Consumer.poll() returns?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#114]
As I interpret the documentation at http://docs.confluent.io/3.1.1/clients/confluent-kafka-python/ , the parameter I give Consumer.poll() tells it to block for that amount of time (seconds? The document does not specify any units, it just says "maximum time to wait") if nothing interesting happens before the timeout. So I would imagine that when I call poll(2.0), if there was a message to receive, I would get that message immediately, but if not, I would block for 2 seconds. But it looks like I always return immediately, no matter what I give as a timeout to poll(), even when there are no messages or errors returned. Am I misinterpreting something?

I tried to understand the underlying rd_kafka_q_pop_serve(), but I'm not confident that I understand it. I wonder if my python callbacks (on_commit, on_assign, error_cb, stats_cb) should return a value, 0 or 1. Right now I just return, no value at all. The documentation does not mention any return value from the callbacks.

Thanks.

**Comment by edenhill** [comment]
Your understanding of its behaviour is correct, poll() will wait for up to timeout (seconds) for a new message, possibly calling any registered callbacks during this time.
You should not get a None return before the timeout has elapsed.

Signals might affect the internal queue-wait, is any other part of your program trigger signals?

Do you have a reliable way of reproducing this? If so: can you provide a small script snippet?

**Comment by edenhill** [comment]
Also, what is your Confluent Kafka Python and librdkafka versions?

**Comment by johnrgregg3** [comment]
Confluent Kafka Python: 0.9.2 (from setup.py)
librdkafka: 0.9.1 (#define RD_KAFKA_VERSION  0x000901ff)

**Comment by johnrgregg3** [comment]
Here is a chunk of my consumer test script:

    config = {
        'bootstrap.servers': kafka_broker,
        'session.timeout.ms': 6000,
        'group.id': consumer_group,
        'api.version.request': True,  # request negotiation of the latest features in broker handshake
        'error_cb': my_kafka_error,
        'stats_cb': my_stats_cb,
        'on_commit': my_on_commit,
        'enable.partition.eof': 1,
        'statistics.interval.ms': 1000,
        'socket.timeout.ms': 3000,
        'socket.max.fails': 1,
        
        'default.topic.config': {'auto.offset.reset': 'earliest'},
#        'debug': 'all',   # dumps stuff to stdout
    }

    try:
        c = Consumer(**config)
        print("consumer group {}, topic {}".format(consumer_group, topic))
        c.subscribe([topic], on_assign=print_assignment)
    except KafkaException as ke:
        err = ke.args[0]
        print("Consumer caught KafkaException: code {}, name {}, str {}".format(err.code(), err.name(), err.str()))
        sys.exit(1)

    while True:
        try:
            print('{} consume_from_broker: about to poll'.format(datetime.datetime.now().strftime('%a, %d %b %Y %H:%M:%S:%f GMT')))
            msg = c.poll(2.0)   # Arg is number or seconds to block before returning. No argument, returns immediately.
            print("{}: poll(2.0) {} returned, latest kafka_error_code {}, all_brokers_down {}".format(datetime.datetime.now().strftime('%a, %d %b %Y %H:%M:%S:%f GMT'), thread_data.kafka_broker, thread_data.kafka_error_code, thread_data.all_brokers_down))
            if not msg:
                print("poll() returned None")
            else:
...

And when I run, the output reads, in part:

Mon, 30 Jan 2017 22:14:19:997178 GMT consume_from_broker: about to poll
Mon, 30 Jan 2017 22:14:19:997255 GMT: poll(2.0) 23.79.234.201 returned, latest kafka_error_code 0, all_brokers_down False
poll() returned None

So from the timestamps, it looks like it returns immediately, and no callbacks were called (I print in those too, and didn't get anything).

**Comment by edenhill** [comment]
Thanks.

That script works as expected for me, the poll() blocks for 2s:
```
Mon, 30 Jan 2017 23:35:10:887368 GMT: poll(2.0) False returned, latest kafka_error_code False, all_brokers_down False
poll() returned None
Mon, 30 Jan 2017 23:35:10:887466 GMT consume_from_broker: about to poll
stats
stats
Mon, 30 Jan 2017 23:35:12:891710 GMT: poll(2.0) False returned, latest kafka_error_code False, all_brokers_down False
poll() returned None
Mon, 30 Jan 2017 23:35:12:891897 GMT consume_from_broker: about to poll
stats
stats
Mon, 30 Jan 2017 23:35:14:893627 GMT: poll(2.0) False returned, latest kafka_error_code False, all_brokers_down False
poll() returned None
Mon, 30 Jan 2017 23:35:14:893797 GMT consume_from_broker: about to poll
stats
```

I see you use thread, is your program doing anything else?

**Comment by johnrgregg3** [comment]
No, it just spawns one thread, and the main loop sits in a tight do-nothing loop:

    thread_data = threading.local()
    thread_list = []
    for broker in broker_set:
        thread = threading.Thread(target=consume_from_broker, args=(broker,))
        thread_list.append(thread)
        thread.daemon = True   # So Ctrl-C will kill the threads too
        thread.start()

    print("spawned {} threads, active count {}".format(len(thread_list), threading.active_count()))

    while True:
        try:
            time.sleep(10)
            print("{} main thread woke up".format(datetime.datetime.now().strftime('%a, %d %b %Y %H:%M:%S:%f')))

        except KeyboardInterrupt:
            sys.stderr.write('Aborted by user\n')
            sys.exit(0)
            break

There is only one broker in this case, so only one thread gets created and started.

**Comment by edenhill** [comment]
Weird.
What OS are you on, and Python version?

**Comment by johnrgregg3** [comment]
I'm on linux: 4.1.31-4.1.3-amd64-c220441ec3580c5e
Python 2.7.12

**Comment by edenhill** [comment]
Can you check if examples/consumer.py behaves in the same way on your system? (add a printout in the None-check after consume())

**Comment by johnrgregg3** [comment]
Initial testing looks like your script works fine. I added some timestamped print statements. Even without a producer, I get this:

Tue, 31 Jan 2017 17:12:25:646853 about to poll
Tue, 31 Jan 2017 17:12:26:645955 poll returned
No msg
Tue, 31 Jan 2017 17:12:26:646053 about to poll
Tue, 31 Jan 2017 17:12:27:645148 poll returned
No msg
Tue, 31 Jan 2017 17:12:27:645225 about to poll
Tue, 31 Jan 2017 17:12:28:644330 poll returned
No msg
Tue, 31 Jan 2017 17:12:28:644428 about to poll
Tue, 31 Jan 2017 17:12:29:643532 poll returned
No msg
Tue, 31 Jan 2017 17:12:29:643620 about to poll
Tue, 31 Jan 2017 17:12:30:642723 poll returned
No msg
Tue, 31 Jan 2017 17:12:30:642812 about to poll
Tue, 31 Jan 2017 17:12:31:642940 poll returned

That is, each poll a second apart, just as it should be. I'll play with my script and try to narrow down what the crucial difference is.

**Comment by johnrgregg3** [comment]
Arg. This is what happens when a C programmer becomes a python programmer. In my loop, I said "if not msg:", but your consumer.py said "if msg is None:". These are not the same thing. So I was getting all these _PARTITION_EOF messages but not seeing them, so the poll() was returning immediately for a good reason. If I am patient, I get to the end of these, and poll() starts blocking as it should.

I can pretty much ignore these _PARTITION_EOF errors, right? They just mean that as a consumer, I'm all caught up, and that's good, right? Will I ever get a message with a legitimate payload (msg.value()) that also has a _PARTITION_EOF "error"? Your consumer.py seems to suggest that the answer is no, that these are mutually exclusive cases: "Proper message" vs. error.

**Comment by ewencp** [comment]
@johnrgregg3 PARTITION_EOF "errors" should be ignorable. More generally, there should *either* be an error set *or* a payload. The PARTITION_EOF error is a bit weird in that it is an "error" in the sense that fetching more data failed, but from the perspective of most applications the only info that conveys is that there will be some backoff before trying to fetch again.

re: `if not x`, truthiness issues are probably one of the biggest sources of bugs in Python...

**Comment by edenhill** [comment]
Yes, PARTITION_EOF can be safely ignored, they are not really an error, just an indication of where things are at. Some applications might make use of it, most won't.
You can disable the generation of PARTITION_EOF by setting `enable.partition.eof` to False.

**Comment by costa** [comment]
Hi, I'm sorry for commenting on a closed issue, but this is exactly the question I'm having. It appears that `consumer.poll(10)` returns `None` after ~1s (it is pretty consistently close to 1s) in a loop, almost from its beginning, e.g. (no messages are really coming in):
```
...
2017-12-10 15:14:59,306.306.864023209:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:09,307.307.506084442:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:19,308.308.059930801:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:24,462.462.774991989:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:25,514.514.138936996:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:28,012.12.2649669647:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:29,529.529.97303009:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:30,322.322.052955627:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:31,163.163.568973541:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:32,298.298.716068268:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:33,295.295.047998428:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:34,281.281.608104706:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:35,385.385.059118271:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:36,303.303.379058838:root:139715425466112:INFO:1:No Vital messages for 10s...
2017-12-10 15:15:37,168.168.570041656:root:139715425466112:INFO:1:No Vital messages for 10s...
...
```

**Comment by edenhill** [comment]
@costa what confluent-kafka-python and librdkafka versions are you running?
(that is `confluent_kafka.version()` and `confluent_kafka.libversion()` respectively)

**Comment by costa** [comment]
@edenhill 
```
>>> confluent_kafka.version()
('0.11.0', 720896)
>>> confluent_kafka.libversion()
('0.9.5', 591359)
```

**Comment by edenhill** [comment]
Please upgrade librdkafka to 0.11.3
