### ISSUE TITLE
AttributeError: 'cimpl.Message' object has no attribute 'len'

### ISSUE THREAD

**Issue by maxamante** [confluentinc/confluent-kafka-python#1142]
Description
===========

AttributeError: 'cimpl.Message' object has no attribute 'len'

Docs seem to be incorrect: https://docs.confluent.io/5.3.1/clients/confluent-kafka-python/index.html#confluent_kafka.Message.len

How to reproduce
================

1. Create a consumer `consumer = Consumer(...)`
2. Poll for a message `msg = consumer.poll(0.1)`
3. Try to call `len`, `len = msg.len()`

Checklist
=========
Please provide the following information:
I'm running Kafka on a base Linux using Docker.

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.0.1', 16777472)
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by choogeboom** [comment]
In python you typically would call `length = len(msg)`. If you really want to call the method, then you need to do `length = msg.__len__()`.

**Comment by jack-mcivor** [comment]
But the documentation is simply wrong here? It's documented as an attribute that does not exist. It should be documented as a dunder if the len function is supposed to be used

**Comment by oleksiymumzhu** [comment]
Still doesnt work, and the documentation is not fixed... 
```
print(mess.len())
          ^^^^^^^^
AttributeError: 'cimpl.Message' object has no attribute 'len'
```
