### ISSUE TITLE
No README on PyPI

### ISSUE THREAD

**Issue by rbarrois** [confluentinc/confluent-kafka-python#1145]
Description
===========

The PyPI project page (at https://pypi.org/project/confluent-kafka/#description) is blank.
As a new user in the Python/Kafka landscape, I would consider such a blank project to be a work in progress or an abandoned one; 

How to reproduce
================

Go to https://pypi.org/project/confluent-kafka

The typical lines in a `setup.py` file for a `README.md` description would be:

```python
import os
with open(os.path.join(os.path.dirname(__file__), 'README.md'), encoding='utf-8') as f:
    long_description = f.read()

setup(
    ...
    long_description=long_description,
    long_description_content_type='text/markdown',
)
```

**Comment by edenhill** [comment]
Good point, care to submit a PR?

**Comment by Bowrna** [comment]
@edenhill I will take up this and submit a PR.

**Comment by Bowrna** [comment]
https://github.com/confluentinc/confluent-kafka-python/pull/1172
I have added the PR for this issue.
