### ISSUE TITLE
AttributeError: 'cimpl.Producer' object has no attribute 'len'

### ISSUE THREAD

**Issue by aviramha** [confluentinc/confluent-kafka-python#1150]
Description
===========
According to the docs https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Producer.len exists. In reality this method doesn't seem to exist.
Is it docs error?

How to reproduce
================

```py
from confluent_kafka import Producer
conf = {'bootstrap.servers': broker}

# Create Producer instance
p = Producer(**conf)
p.produce(topic, "dada")
p.len()
AttributeError: 'cimpl.Producer' object has no attribute 'len'
```

Checklist
=========
 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```py
confluent_kafka.version()
('1.7.0', 17235968)
confluent_kafka.libversion()
('1.7.0', 17236223)
```
 - [x] Apache Kafka broker version:
 2.8.0
 - [x] Operating system: macOS

**Comment by edenhill** [comment]
Use `len(p)` instead.

The documentation needs to be clearer here.
