### ISSUE TITLE
Getting Broker: Cluster authorization failed

### ISSUE THREAD

**Issue by mohammedaugie13** [confluentinc/confluent-kafka-python#1151]
Description
===========
Hi guys i am trying to implement idempotence producer. But every time trying to produce message with `enable.idempotence=true` i always get error

```2021-04-18 16:43:53.584[0;39m [31mERROR[0;39m [35m15524[0;39m [2m---[0;39m [2m[ad | producer-1][0;39m [36mo.a.k.clients.producer.internals.Sender [0;39m [2m:[0;39m [Producer clientId=producer-1] Aborting producer batches due to fatal error

org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.

[2m2021-04-18 16:43:53.585[0;39m [31mERROR[0;39m [35m15524[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mc.a.c.g.kafkaclient.PricerProducer      [0;39m [2m:[0;39m sending above record failed. java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed. 
```

How to reproduce
================
Set the producer config to `Producer({'bootstrap.servers': 'localhost:9092', 'acks':'all', 'enable.idempotence': True, 'max.in.flight.requests.per.connection':5})`. Im using librdkafka `('1.5.0', 17105151)` and confluent-kafka-python `('1.5.0', 17104896)`

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
> org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.

That looks like a Java producer error, not a Python producer error.

Either way, your ACLs are too strict.

**Comment by mohammedaugie13** [comment]
@edenhill ah okay thanks
