### ISSUE TITLE
ModuleNotFoundError: No module named 'avro.io'

### ISSUE THREAD

**Issue by Bha91** [confluentinc/confluent-kafka-python#1153]
Description
===========
No module named 'avro.io' after installing from pip as:

`pip install confluent-kafka[avro]`

How to reproduce
================

`from confluent_kafka import avro
`

```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-29-5e88e747ab1e> in <module>
----> 1 from confluent_kafka import avro

c:\projects\envs\commodity-scraper\lib\site-packages\confluent_kafka\avro\__init__.py in <module>
     28                                              KeySerializerError,
     29                                              ValueSerializerError)
---> 30 from confluent_kafka.avro.serializer.message_serializer import MessageSerializer
     31 
     32 

c:\projects\envs\commodity-scraper\lib\site-packages\confluent_kafka\avro\serializer\message_serializer.py in <module>
     27 
     28 import avro
---> 29 import avro.io
     30 
     31 from confluent_kafka.avro import ClientError

ModuleNotFoundError: No module named 'avro.io'
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
confluent_kafka.version(): ('1.7.0', 17235968)
confluent_kafka.libversion(): ('1.7.0', 17236223)
 - [x] Apache Kafka broker version: 2.7.0
 - [ ] Client configuration: `{...}`
 - [x] Operating system: windows 10 64
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What Python and avro version are you using?
`python -V` and `pip list | grep "avro"`

**Comment by jliunyu** [comment]
Please feel free to reopen it if any help is still needed from our side.
