### ISSUE TITLE
Is it possible to send additional parameters to the delivery callback function other than msg and error from Producer.produce()?

### ISSUE THREAD

**Issue by anveshagarwal** [confluentinc/confluent-kafka-python#1159]
Description
===========
For one of my use case, I want to make a callback using a lambda and here i want to send an `id` field in the callback:
```python
 producer.produce(topic=<topic_name>, value=<message>, callback=lambda err, msg, id: delivery_callback(err, msg, id))

def delivery_callback(err, msg, id=None):
        if err:
            sys.stderr.write('%% Message failed delivery: %s\n' % err)
        else:
            sys.stderr.write('%% Message with id %s delivered to %s [%d] @ %d\n' %
                             (id, msg.topic(), msg.partition(), msg.offset()))
```
It throws the error: `TypeError: <lambda>() missing 1 required positional argument: 'id'.`
How to send extra parameter in callback?

**Comment by edenhill** [comment]
No, the function signature needs to match the delivery callback signature. But you can bind any variable inside your lambda.
E.g.:
```python
   p.produce(topic=topic, value=myobj.serialize(), callback=lambda err,msg: delivery_callback(err, msg, myobj)
```

see [examples/avro-cli.py] for an example
