### ISSUE TITLE
Producer cannot be garbage collected when `group.id` set.

### ISSUE THREAD

**Issue by Kheldar** [confluentinc/confluent-kafka-python#116]
I've run into an issue where my script fails to terminate when the `group.id` config option is set on a Producer. It seems to be the case that when this option is set, the Producer cannot be garbage collected (hangs forever at the point garbage collection is attempted).

Here is a minimal script that consistently reproduces it on my environment.

``` python
import logging
import sys

# Set up logging
numeric_log_level = getattr(logging, "INFO", None)
logging.basicConfig(level=numeric_log_level, stream=sys.stdout)

from confluent_kafka import Producer

config = {
    'group.id': "something-valid"
}

logging.info("Configuration: {}".format(config))

producer = Producer(config)

logging.info("Regular producer created") # This line will run

del producer # It hangs here

logging.info("Regular producer deleted") # This line is never reached
```

**Comment by edenhill** [comment]
This is a known issue in librdkafka 0.9.1, it is fixed in 0.9.2 and later (0.9.3 is the latest).
The workaround is to not set group.id on producers
