### ISSUE TITLE
num_partitions should be optional for NewTopic

### ISSUE THREAD

**Issue by hrchu** [confluentinc/confluent-kafka-python#1160]
KIP-464 supports creating topics with default partitions and replication factor, but the current interface still asks for num_parititions. 

It will be better to let it also be optional, for less confusing.

![image](https://user-images.githubusercontent.com/3183314/125021769-dd32f380-e0ad-11eb-900c-c4060348436c.png)

https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.admin.NewTopic.NewTopic
 https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=113708722

**Comment by edenhill** [comment]
You're right.
Try passing -1 and see if that works until we fix this.

**Comment by nhaq-confluent** [comment]
I believe this was fixed in a newer version. The following worked on my end:
`    new_topics = NewTopic("python_test")
`

please open a new issue if it still persists
