### ISSUE TITLE
Pip3 installation doesn't work - RHEL7

### ISSUE THREAD

**Issue by dab92** [confluentinc/confluent-kafka-python#1166]
I have RHEL7 and I want to install confluent-kafka-python with Kerberos authentication.

I followed prerequisites and installed librdkafka as instructed.
librdkafka.x86_64                0.11.4-1.el7          @rhel-7-server-rpms
librdkafka-devel.x86_64          0.11.4-1.el7          @rhel-7-server-optional-rpms

I also have python-devel and python3-devel installed as well.
python-devel.x86_64              2.7.5-90.el7          @rhel-7-server-rpms
rh-python36-python-devel.x86_64  3.6.12-1.el7          @rhel-server-rhscl-7-rpms
python3-devel.x86_64             3.6.8-18.el7          @rhel-7-server-optional-rpms

However, when I try to install from source using below command, I get the following error. I've tried many proposed solutions, but I still get this.

(test_environment) [root@localhost test_environment]#  pip3 install --no-binary :all: confluent-kafka
Collecting confluent-kafka
  Using cached confluent-kafka-1.7.0.tar.gz (103 kB)
Skipping wheel build for confluent-kafka, due to binaries being disabled for it.
Installing collected packages: confluent-kafka
    Running setup.py install for confluent-kafka ... error
    ERROR: Command errored out with exit status 1:
     command: /root/test_environment/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b0t61klp/install-record.txt --single-version-externally-managed --compile --install-headers /root/test_environment/include/site/python3.6/confluent-kafka
         cwd: /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/
    Complete output (125 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/confluent_kafka
    copying src/confluent_kafka/error.py -> build/lib.linux-x86_64-3.6/confluent_kafka
    copying src/confluent_kafka/serializing_producer.py -> build/lib.linux-x86_64-3.6/confluent_kafka
    copying src/confluent_kafka/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka
    copying src/confluent_kafka/deserializing_consumer.py -> build/lib.linux-x86_64-3.6/confluent_kafka
    creating build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
    copying src/confluent_kafka/schema_registry/avro.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
    copying src/confluent_kafka/schema_registry/error.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
    copying src/confluent_kafka/schema_registry/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
    copying src/confluent_kafka/schema_registry/json_schema.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
    copying src/confluent_kafka/schema_registry/schema_registry_client.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
    copying src/confluent_kafka/schema_registry/protobuf.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
    creating build/lib.linux-x86_64-3.6/confluent_kafka/serialization
    copying src/confluent_kafka/serialization/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/serialization
    creating build/lib.linux-x86_64-3.6/confluent_kafka/admin
    copying src/confluent_kafka/admin/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/admin
    creating build/lib.linux-x86_64-3.6/confluent_kafka/avro
    copying src/confluent_kafka/avro/error.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
    copying src/confluent_kafka/avro/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
    copying src/confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
    copying src/confluent_kafka/avro/load.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
    creating build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    copying src/confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    copying src/confluent_kafka/kafkatest/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    copying src/confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    copying src/confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    creating build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
    copying src/confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
    copying src/confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
    running build_ext
    building 'confluent_kafka.cimpl' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/tmp
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-nme80i5e
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka
    creating build/temp.linux-x86_64-3.6/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/root/test_environment/include -I/usr/include/python3.6m -c /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c -o build/temp.linux-x86_64-3.6/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.o
    In file included from /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:17:0:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.h:66:2: error: #error "confluent-kafka-python requires librdkafka v1.6.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
     #error "confluent-kafka-python requires librdkafka v1.6.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
      ^
    In file included from /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:17:0:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.h:190:46: error: unknown type name ‘rd_kafka_error_t’
     PyObject *KafkaError_new_from_error_destroy (rd_kafka_error_t *error);
                                                  ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.h:393:1: error: unknown type name ‘rd_kafka_consumer_group_metadata_t’
     PyObject *c_cgmd_to_py (const rd_kafka_consumer_group_metadata_t *cgmd);
     ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.h:394:1: error: unknown type name ‘rd_kafka_consumer_group_metadata_t’
     rd_kafka_consumer_group_metadata_t *py_to_c_cgmd (PyObject *obj);
     ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:387:46: error: unknown type name ‘rd_kafka_error_t’
     PyObject *KafkaError_new_from_error_destroy (rd_kafka_error_t *error) {
                                                  ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1317:1: error: unknown type name ‘rd_kafka_consumer_group_metadata_t’
     PyObject *c_cgmd_to_py (const rd_kafka_consumer_group_metadata_t *cgmd) {
     ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c: In function ‘c_cgmd_to_py’:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1321:9: error: unknown type name ‘rd_kafka_error_t’
             rd_kafka_error_t *error;
             ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1323:9: warning: implicit declaration of function ‘rd_kafka_consumer_group_metadata_write’ [-Wimplicit-function-declaration]
             error = rd_kafka_consumer_group_metadata_write(cgmd, &buffer, &size);
             ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1323:15: warning: assignment makes pointer from integer without a cast [enabled by default]
             error = rd_kafka_consumer_group_metadata_write(cgmd, &buffer, &size);
                   ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1325:17: warning: implicit declaration of function ‘KafkaError_new_from_error_destroy’ [-Wimplicit-function-declaration]
                     cfl_PyErr_from_error_destroy(error);
                     ^
    In file included from /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:17:0:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.h:207:19: warning: initialization makes pointer from integer without a cast [enabled by default]
       PyObject *_eo = KafkaError_new_from_error_destroy(error); \
                       ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1325:17: note: in expansion of macro ‘cfl_PyErr_from_error_destroy’
                     cfl_PyErr_from_error_destroy(error);
                     ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c: At top level:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1340:1: error: unknown type name ‘rd_kafka_consumer_group_metadata_t’
     rd_kafka_consumer_group_metadata_t *py_to_c_cgmd (PyObject *obj) {
     ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c: In function ‘py_to_c_cgmd’:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1341:9: error: unknown type name ‘rd_kafka_consumer_group_metadata_t’
             rd_kafka_consumer_group_metadata_t *cgmd;
             ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1342:9: error: unknown type name ‘rd_kafka_error_t’
             rd_kafka_error_t *error;
             ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1349:9: warning: implicit declaration of function ‘rd_kafka_consumer_group_metadata_read’ [-Wimplicit-function-declaration]
             error = rd_kafka_consumer_group_metadata_read(&cgmd,
             ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1349:15: warning: assignment makes pointer from integer without a cast [enabled by default]
             error = rd_kafka_consumer_group_metadata_read(&cgmd,
                   ^
    In file included from /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:17:0:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.h:207:19: warning: initialization makes pointer from integer without a cast [enabled by default]
       PyObject *_eo = KafkaError_new_from_error_destroy(error); \
                       ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1353:17: note: in expansion of macro ‘cfl_PyErr_from_error_destroy’
                     cfl_PyErr_from_error_destroy(error);
                     ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c: In function ‘error_cb’:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1379:20: error: ‘RD_KAFKA_RESP_ERR__FATAL’ undeclared (first use in this function)
             if (err == RD_KAFKA_RESP_ERR__FATAL) {
                        ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1379:20: note: each undeclared identifier is reported only once for each function it appears in
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1381:17: warning: implicit declaration of function ‘rd_kafka_fatal_error’ [-Wimplicit-function-declaration]
                     err = rd_kafka_fatal_error(rk, errstr, sizeof(errstr));
                     ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c: In function ‘oauth_cb’:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:1550:9: warning: implicit declaration of function ‘rd_kafka_oauthbearer_set_token’ [-Wimplicit-function-declaration]
             err_code = rd_kafka_oauthbearer_set_token(h->rk, token,
             ^
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c: In function ‘common_conf_setup’:
    /tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/src/confluent_kafka/src/confluent_kafka.c:2086:17: warning: implicit declaration of function ‘rd_kafka_conf_set_oauthbearer_token_refresh_cb’ [-Wimplicit-function-declaration]
                     rd_kafka_conf_set_oauthbearer_token_refresh_cb(conf, oauth_cb);
                     ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/test_environment/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nme80i5e/confluent-kafka_74edc21712c9476f818256c1f592c74c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b0t61klp/install-record.txt --single-version-externally-managed --compile --install-headers /root/test_environment/include/site/python3.6/confluent-kafka Check the logs for full command output.

Also, tried installing using 'python3 -m pip install --no-binary :all: confluent-kafka', but it shows the same error.

**Comment by edenhill** [comment]
```#error "confluent-kafka-python requires librdkafka v1.6.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
```

Your librdkafka version is too old.
I recommend you install librdkafka from source (tag v1.7.0) to get the latest version.

**Comment by dab92** [comment]
Thank you. Your suggestion worked.

**Comment by dab92** [comment]
Ran into a problem when imitating those steps in a different RHEL7 machine.

./configure step worked. However, 'make' command gives the following error.

................
................
WARNING: librdkafka-static.a: Not creating self-contained static library librdkafka-static.a: no static libraries available/enabled 
Generating pkg-config file rdkafka-static.pc 
Checking librdkafka integrity 
librdkafka.so.1                OK 
librdkafka.a                   OK 
Symbol visibility              OK 
make[1]: Leaving directory `/home/user1/librdkafka-1.7.0/src' 
make[1]: Entering directory `/home/user1/librdkafka-1.7.0/src-cpp' 
Generating pkg-config file rdkafka++-static.pc 
Checking librdkafka++ integrity 
librdkafka++.so.1              OK 
librdkafka++.a                 OK 

make[1]: Leaving directory `/home/user1/librdkafka-1.7.0/src-cpp' 
Using ctags to generate TAGS 
fatal: Not a git repository (or any parent up to mount point /home) 
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 
cmp: TAGS: No such file or directory
