### ISSUE TITLE
Producer.send() does not throw error on successive calls

### ISSUE THREAD

**Issue by selvakumaar5496** [confluentinc/confluent-kafka-python#1168]
Description
===========
Producer.send() does not throw error on successive calls

How to reproduce
================

```
def error_cb(err):
    if err.code() == KafkaError._ALL_BROKERS_DOWN:
        raise GenericError(err.code(), "Kafka service(s) unavailable. %s", err)

try:
    p = Producer({'error_cb': error_cb})     # throws error
except Exception as e:
    print(e)
    try:
        p = Producer({'error_cb': error_cb})   # does not throws error
    except Exception as e:
        print(e)  
```
Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version - 1.5.0):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by selvakumaar5496** [comment]
@edenhill Could you please provide a solution for the above?

**Comment by mhowlett** [comment]
errors on `error_cb` don't align with produce calls. these 'errors' are informational only generally. all_brokers_down will only be emitted once when the condition is detected. instead, use delivery reports to be informed of per message errors: https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/producer.py#L45

this blog post might help you understand how to drive the python client a bit better: https://www.confluent.io/blog/kafka-python-asyncio-integration/
