### ISSUE TITLE
version of confluent-kafka-python/librdkafka available to client?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#117]
Is there any way, programatically, for a client (consumer or producer) to determine the version of the confluent-kafka-python it is using or that of the underlying librdkafka library? I imagine maybe a couple of fields in the big block passed into the stats_cb callback. If this does not exist, it would be nice to have.

**Comment by edenhill** [comment]
Yes!
 * `confluent_kafka.version()` for the Python module version
 * `confluent_kafka.libversion()` for the librdkafka version

**Comment by johnrgregg3** [comment]
Cool - thanks!
