### ISSUE TITLE
Is it safe to run multiple consumers, with different consumer groups, in the same python process?

### ISSUE THREAD

**Issue by ffissore** [confluentinc/confluent-kafka-python#1175]
Description
===========
We want to use kafka as both app events and configuration storage.

App events are the usual stuff: we consume, process, and commit.

Configuration events are deltas applied to a configuration object: each process has to read the whole configuration topic and apply the deltas until high watermark. The final configuration contains a list of "app" topics to consume.

The way we implemented this is by having 2 AvroConsumers in the same python process, one for app events with a fixed group.id, the other for configuration events with a group.id made of a prefix and a random string: the random group.id is necessary to ensure that all pods in a kubernetes deployment will be allowed the consume the configuration topic.

Some colleagues told us it's not recommended to create more than 1 consumer per process, but they were unable to provide any reference. Is it true? If so, are there workarounds?

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version: ('0.11.6', 722432) and ('0.11.6', 722687)
 - [X] Apache Kafka broker version: 2.1.1cp1
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: debian
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
It is less efficient to use multiple consumers, but if it makes writing the code easier, that'll normally be fine. At very high throughputs, there will be more broker requests (a significant determiner of max throughput). At very low throughputs, polling overhead will be comparable to data, and if you're using Confluent Cloud you're charged for all bandwidth, so an additional consumer will meaningfully increase cost.

**Comment by ffissore** [comment]
Thanks!
