### ISSUE TITLE
ProtobufSerializer cannot serialize messages deserialized by ProtobufDeserializer

### ISSUE THREAD

**Issue by rvinzent** [confluentinc/confluent-kafka-python#1181]
Description
===========

I have a simple DLQ use case where a message should be routed to a DLQ if processing fails. The message key and value both use the same schema. A deserializing consumer and a serializing producer constructed from the same generated  message type fails to serialize due to an `isinstance` check that will never succeed when the message was deserialized via `ProtobufDeserializer`.

The error originates from [here](https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/schema_registry/protobuf.py#L334-L336) and is unavoidable for message payloads deserialized with `ProtobufDeserializer` because the deserializer dynamically builds a new class.

Simply deleting the `isinstance` check correctly produces the serialized message. There should be another way to check the message type using a static value rather than a class that is potentially dynamically generated.

How to reproduce
================
- consume a message from some topic with any arbitrary protobuf schema
- attempt to produce the same message to a new topic using the same message

Given the schema for the messages are identical, I would expect the following to work:

```python
from ./my_message_pb2 import MyMessage

schema_registry_client = SchemaRegistryClient({"schema.registry.url": "http://localhost:8081"})

producer = SerializingProducer({
    "bootstrap.servers": "localhost:9092",
    "security.protocol": "PLAINTEXT",
    "auto.register.schemas": True,
    "key.serializer": StringSerializer("utf-8"),
    "value.deserializer": ProtobufSerializer(MyMessage, schema_registry_client),
})

consumer = DeserializingConsumer({
    "bootstrap.servers": "localhost:9092",
    "security.protocol": "PLAINTEXT",
    "group.id": "my-group",
    "enable.auto.commit": False, 
    "auto.offset.reset": "earliest",
    "debug": "consumer",
    "key.serializer": StringDeserializer("utf-8"),
    "value.deserializer": ProtobufDeserializer(MyMessage),
})

consumer.subscribe("some.topic")
msg = consumer.poll(1.0)
producer.produce("other.topic", key=msg.key(), value=msg.value())
producer.flush()
```

Raises:
```
ValueError: message must be of type <class 'my_message_pb2.MyMessage'> not <class 'MyMessage'>
```

The type check cannot succeed regardless of how the protobuf message class is imported

Consumer debug logs:
```
%7|1628630858.856|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v1.7.0 (0x10700ff) rdkafka#consumer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, STRIP STATIC_LINKING CC GXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x2000)
%7|1628630858.887|SUBSCRIBE|rdkafka#consumer-1| [thrd:main]: Group "my-group": subscribe to new subscription of 1 topics (join-state init)
%7|1628630858.887|JOIN|rdkafka#consumer-1| [thrd:main]: Group "my-group": postponing join until up-to-date metadata is available
%7|1628630858.891|REJOIN|rdkafka#consumer-1| [thrd:main]: Group "my-group": subscription updated from metadata change: rejoining group
%7|1628630858.891|REBALANCE|rdkafka#consumer-1| [thrd:main]: Group "my-group" initiating rebalance (NONE) in state up (join-state wait-metadata) with 0 assigned partition(s): Metadata for subscribed topic(s) has changed
%7|1628630858.891|REJOIN|rdkafka#consumer-1| [thrd:main]: Group "my-group": Rejoining group without an assignment: Metadata for subscribed topic(s) has changed
%7|1628630858.891|JOIN|rdkafka#consumer-1| [thrd:main]: 127.0.0.1:9092/0: Joining group "my-group" with 1 subscribed topic(s)
%7|1628630858.896|REJOIN|rdkafka#consumer-1| [thrd:main]: Group "my-group": Rejoining group without an assignment: JoinGroup error: Broker: Group member needs a valid member ID
%7|1628630858.896|JOIN|rdkafka#consumer-1| [thrd:main]: 127.0.0.1:9092/0: Joining group "my-group" with 1 subscribed topic(s)
%7|1628630859.906|ASSIGNOR|rdkafka#consumer-1| [thrd:main]: Group "my-group": "range" assignor run for 1 member(s)
%7|1628630859.913|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "my-group": new assignment of 1 partition(s) in join-state wait-assign-call
%7|1628630859.913|CLEARASSIGN|rdkafka#consumer-1| [thrd:main]: No current assignment to clear
%7|1628630859.913|ASSIGNMENT|rdkafka#consumer-1| [thrd:main]: Added 1 partition(s) to assignment which now consists of 1 partition(s) where of 1 are in pending state and 0 are being queried
%7|1628630859.913|OFFSET|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Fetch committed offsets for 1/1 partition(s)
%7|1628630859.918|FETCH|rdkafka#consumer-1| [thrd:main]: Partition some.topic [0] start fetching at offset 14
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version(1.7.0)` and `confluent_kafka.libversion('1.7.0', 17236223)`):
 - [x] Apache Kafka broker version: 2.5.1 - should not be relevant
 - [x] Client configuration: `{...}` See code.
 - [x] Operating system: MacOs Big Sur 11.4
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mattkindy** [comment]
For what it's worth, I was able to circumvent this problem by doing -- 
```
new_value = MyMessage()
new_value.CopyFrom(msg.value())
```
and sending `new_value`

**Comment by jliunyu** [comment]
Hi @rvinzent, thanks for reporting this.

Since this is same issue with https://github.com/confluentinc/confluent-kafka-python/issues/1307, let's close this one and using https://github.com/confluentinc/confluent-kafka-python/issues/1307 to track the status.
