### ISSUE TITLE
Add aarch64 wheels support

### ISSUE THREAD

**Issue by tbbharaj** [confluentinc/confluent-kafka-python#1182]
Description:
Wheels for confluent-kafka-python doesn't exists in [pypi](https://pypi.org/project/confluent-kafka/#files)

Solution:
This PR: #1161 addresses the issue to build and publish aarch64 wheels for confluent-kafka
Successful Builds: https://travis-ci.com/github/tbbharaj/confluent-kafka-python/builds/232243754

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): Build tested on 1.7.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by tbbharaj** [comment]
Following up on this the issue to build arm64 wheels.
There's PR open addressing this issue #1161 , hoping to get some reviews on it.

Thanks!

**Comment by tbbharaj** [comment]
Following up on this the issue to build arm64 wheels, hoping to get some reviews on PR. Thanks!

**Comment by jliunyu** [comment]
We need to wait for the CI to verify the PR.

**Comment by jalaziz** [comment]
Things just got worse with the 1.9.0 release. In our case, we're building arm64 docker images. We previously could install `librdkafka` using a linux package manager, but now that `librdkafka` 1.9.0 is required that is not easy to satisfy (without building it ourselves).

So you might then say, "well use Confluent's linux package repos". That doesn't work because they don't publish arm64 packages.

Can we please just get an arm64 wheel?

**Comment by jukeks** [comment]
M1 machines are quite common nowadays and using this library is painful currently if you use the wrong machine. Any updates on getting binary wheels for aarch64?

**Comment by sloppycoder** [comment]
the wheel is available for M1 Mac but still not available for linux/arm64. I'm having some issue trying to build an image for my Raspberry Pi K3S cluster.

https://pypi.org/project/confluent-kafka/#files

any update on when aarch64 support will be available?

Or if someone can provide some pointers maybe I can contribute.

**Comment by ChillarAnand** [comment]
I think this is dependant on next librdkafka release. 

https://github.com/confluentinc/librdkafka/discussions/4102

**Comment by ChillarAnand** [comment]
@sloppycoder What issue you are facing?

I am also building from source and using Linux arm64 builds. It is working fine.

**Comment by hsheth2** [comment]
It looks like the latest release has a manylinux aarch64 wheel https://pypi.org/project/confluent-kafka/2.3.0/#files. Seems like they were added starting with 2.1.0

**Comment by lvitti** [comment]
I still having issues installing on:

```
bash-4.2# pip install https://files.pythonhosted.org/packages/ae/26/fc985d8bb318c9e5d1214e70507e961d121676c459abe25dd3c6548be5d1/confluent_kafka-2.3.0-cp38-cp38-manylinux_2_28_aarch64.whl
ERROR: confluent_kafka-2.3.0-cp38-cp38-manylinux_2_28_aarch64.whl is not a supported wheel on this platform.
```

```
bash-4.2# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```

```
bash-4.2# uname -m
aarch64
```

**Comment by pranavrth** [comment]
arm64 wheels were added from v1.9.2 and linux arm64 wheels from v2.1.0.

Closing this issue.
