### ISSUE TITLE
confluent_kafka.Producer init sticks in infinite loop

### ISSUE THREAD

**Issue by almaz1213** [confluentinc/confluent-kafka-python#1184]
Description
===========

confluent_kafka.Producer init sticks in infinite loop

How to reproduce
================

```
from confluent_kafka import Producer

#NO kafka server on 'localhost:9092

def onErr(err, msg):
  print(err, msg)

p = Producer({'bootstrap.servers': 'localhost:9092'})
print('Test connection..')
p.produce('', '', on_delivery=onErr)
p.poll(0)
```

Checklist
=========
Please provide the following information:
 - [X] Critical issue

the code sticks in loop of p = Producer({'bootstrap.servers': 'localhost:9092'}) !!!

how to test if kafka server is avilable?

why confluent kafka producer just don't rise some exception if server is unavailable in init time of Producer?

**Comment by diamo1213** [comment]
i improved like:
```
.....
def onErr(err, msg):
      if err is not None and err.code() == KafkaError._ALL_BROKERS_DOWN:
        errprn(f"testConnection(): str={err.str()}, err={err.code()}, msg={msg}, KafkaError._ALL_BROKERS_DOWN={KafkaError._ALL_BROKERS_DOWN}")
        raise Exception(err)
.....
```
does not work

**Comment by edenhill** [comment]
`_ALL_BROKERS_DOWN` is a producer-level/generic error that will be propagated on the error callback, not the per-message delivery callback.

Create an error_cb with the same logic, but pass it as `'error_cb': your_error_cb` in the producer config dict.

**Comment by diamo1213** [comment]
@edenhill thanks, but i don't see it in docs https://docs.confluent.io/clients-confluent-kafka-python/current/overview.html#initialization

**Comment by diamo1213** [comment]
```
.....
p = Producer({'bootstrap.servers': 'localhost:9092', 'error_cb': onErr})
.....
```

onErr takes err: KafkaError{code=_TRANSPORT,val=-195,str="localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)"}

not KafkaError._ALL_BROKERS_DOWN

**Comment by diamo1213** [comment]
ok. we can get connection fail now. but how to stop the infinite loop of p = Producer(.....)? p = None does not stop it

**Comment by edenhill** [comment]
`del p`

**Comment by diamo1213** [comment]
in my case it does not stop the loop, too

**Comment by edenhill** [comment]
Can you describe the loop you're experiencing?

**Comment by edenhill** [comment]
Try calling `purge()` and then `flush()` to purge any queued messages before deleting the producer instance.

**Comment by diamo1213** [comment]
probably in my case reason is that producers work in separate threads....

**Comment by diamo1213** [comment]
now i need success connection event. how can know that connection was established?

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down
