### ISSUE TITLE
How can I assure if the client fails, the produced messages are not lost?

### ISSUE THREAD

**Issue by anveshagarwal** [confluentinc/confluent-kafka-python#1188]
reference: https://github.com/confluentinc/confluent-kafka-python/issues/137#issuecomment-455538961

If my client fails or restarts and the produced message has not made it to the broker yet, client can use some persistent storage mechanism to save my message while producing messages and if client won't get the delivery callback for the saved message then it can retry sending it again. 

But if the produced message has made it to broker, and then my client fails, then client won't be getting the acknowledgement of the message which actually is already sent. So if next time I retry it on the basis of `didn't get an acknowledgment` condition, then it will be sending duplicate message.

How can I assure that if my app fails, I can resend the message without this duplicating issue?

**Comment by adrian-vlad** [comment]
If your system cannot deal with duplicated messages, then try enabling idempotence (https://kafka.apache.org/documentation/#producerconfigs_enable.idempotence) or use producer transactions. This will ensure that even if the messages arrive at the broker, if the client doesn't receive the acknowledgment, the broker will not accept the messages.
Basically, it will make the whole underlying communication unimportant for you: if the delivery callback is called, then the broker received the messages; if not, it didn't.

**Comment by edenhill** [comment]
One think to note is that idempotence and transactions only mantain those guarantees during the lifetime of a single producer instance. If you want to ensure exactly-once with your application restarting you need to solve this outside the scope of Kafka itself, possibly by de-duplication on the consumer side.

**Comment by anveshagarwal** [comment]
Yes. I think it has to be handled outside kafka. Thanks.
