### ISSUE TITLE
poll(..) calls raising timeout exception, then flush() never returns

### ISSUE THREAD

**Issue by telles-simbiose** [confluentinc/confluent-kafka-python#119]
Hi,

I have a background thread that keeps calling `poll(1)` every 5 seconds, when my application got a heavy load, I started to get time out exceptions from `poll(1)` calls:

```
KafkaExceptions: (code=7, msg={"records":[{"fields":[{"field":"time_series_string_test_field","groups":["test4-non_time_series_topk","no_filter"],"value":"TFBUMQo=","timestamp":"2017-01-10T00:00:00Z"},{"field":"time_series_numeric_test_field","groups":["test4-non_time_series_topk","no_filter"],"value":300460,"timestamp":"2017-01-10T00:00:00Z"},{"field":"time_series_decimal_test_field","groups":["test4-non_time_series_topk","no_filter"],"value":68437.0,"timestamp":"2017-01-10T00:00:00Z"}],"rec_id":"7461009_03022017","rec_timestamp":1486)
[2017/02/03 14:42:48] ERROR: Job "__poll_all (trigger: interval[0:00:05], next run at: 2017-02-03 14:42:51 UTC)" raised an exception
    raise KafkaExceptions(error)
```

I got 4 exceptions like this, until the application ran `flush()` when exiting the process and it got stuck forever.

I think that the exceptions were not because of confluent-kafka-python, but I think `flush()` hanging forever is...

**Comment by edenhill** [comment]
This means the ProduceRequest timed out on the leader broker when it was waiting for replica brokers to ack the produced messages according to your producer's `acks` setting.
There's some more information on how to handle slow replicas here:
http://docs.confluent.io/3.1.2/kafka/post-deployment.html#lagging-replicas
