### ISSUE TITLE
should not use _SchemaCache in SchemaRegistryClient

### ISSUE THREAD

**Issue by puella2021** [confluentinc/confluent-kafka-python#1194]
Description
===========
_SchemaCache should not be used in SchemaRegistryClient , since the "delete_subject" method is provided and no update the cache.

**Comment by jliunyu** [comment]
Thanks for reporting this,  we are looking into it.

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1825
