### ISSUE TITLE
Lost of acknowledgement of messages

### ISSUE THREAD

**Issue by anveshagarwal** [confluentinc/confluent-kafka-python#1196]
Description
===========
To track lost acks, I am adding a redis key when a message is produced, and remove the redis key from the delivery callback function. And at the end of the day, I check the redis key in the redis db. I see high number of lost acks. 
My producer conf: 
```
config = {
    'bootstrap.servers': '127.0.0.1:9092',
    'client.id': socket.gethostname(),
    'socket.timeout.ms': 10 * 1000,
    'request.required.acks': -1,
    'queue.buffering.max.ms': 500,
    'partitioner': 'random',
}
```
I found that most of the messages whose acks are lost (whose redis keys are not deleted), already made to the broker, and are getting consumed by to consumer. That means I am not getting the acks for some messages which have already made to the broker. What can be the reason for this behaviour? Am I missing something here?

In my producer, I am calling poll(0) after every produced messages and producing about 200 messages per minute. And calling flush() when a worker restarts or shuts down.

**Comment by edenhill** [comment]
You should definitely get a delivery report for each message, given that you poll() at regular intervals.

Can you show us your producer loop code?

**Comment by anveshagarwal** [comment]
def produce_msg():
        try:
            producer = get_producer(config)
            producer.produce(
                topic=<topic_name>, value=<message>, callback=delivery_callback(err, msg)
            )
            producer.poll(0)
        except BufferError:
            producer.poll(5)
            producer.produce(
                topic=topic_name, value=message, callback=lambda err, msg: self.delivery_callback(err, msg, id)
            )
        except Exception:
            # log exception

delivery callback is just logging msg if successful else logs error.

**Comment by anveshagarwal** [comment]
I think I found the issue. Issue is with my application workers. When there is a shut down or restart of my application workers, then by using `atexit`, I capture signal and run producer.flush() from the cleanup function. But for some reason, for few unknown cases, cleanup function is not running.
