### ISSUE TITLE
Please implement support for KIP-610

### ISSUE THREAD

**Issue by jmcp** [confluentinc/confluent-kafka-python#1201]
Description
===========
Please implement support for KIP-610, [Error Reporting in Sink Connectors](https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors)

I'm spearheading a Data Mesh effort for $work, and I've had a number of colleagues ask me about how to handle error reporting with their Python consumers. Our current approach is "roll your own", but it would be considerably more effective if we could use the facility provided in KIP-610, which was integrated with Apache Kafka 2.6.0 (released 3 August 2020, https://archive.apache.org/dist/kafka/2.6.0/RELEASE_NOTES.html).

How to reproduce
================
n/a

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 ```python
>>> confluent_kafka.version()
('1.7.0', 17235968)
>>> confluent_kafka.libversion()
('1.7.0', 17236223)
```

 - [ n/a ] Apache Kafka broker version
 - [ n/a ] Client configuration
 - [ any ] Operating system
 - [ n/a ] Provide client logs (with `'debug': '..'` as necessary) 
 - [ n/a ] Provide broker log excerpts  
 - [ N ] Critical issue

**Comment by edenhill** [comment]
KIP-610 is a Connect feature though, not in the underlying Kafka clients.
I believe a DLQ is best implemented as a layer on top of the consumer, otherwise the consumer would also need to have a producer in it.

I recommend creating a layer on of the consumer that provides this functionality and providing it as a separate Python package.
