### ISSUE TITLE
passing sasl.jaas.config 

### ISSUE THREAD

**Issue by mrshanth** [confluentinc/confluent-kafka-python#1203]
Description
===========

I have the sasl.json.config value for authentication using SASL and PLAN. How to set this parameter?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (confluent-kafka==1.7.0 and `confluent_kafka.libversion()`): 
 - [ ] Apache Kafka broker version: 2.7.0
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
JAAS is a java phenomen. For confluent-kafka-python you configure SASL through the standard configuration properties:
```python
'security.protocol': 'SASL', # or 'SASL_SSL'
'sasl.mechanism': 'PLAIN',
'sasl.username': '...',
'sasl.password': '...'
```

**Comment by mrshanth** [comment]
Thanks for the response. I don't have username and password. I have a java kafka client which passes the config for authentication:
`com.security.providers.kafka.authentication.Client required 
client_id=xxxxx 
secret=<secret_access_key> 
streams_app=<app_name> 
policies=<encoded_policy>`

How do I convert this to python?

**Comment by edenhill** [comment]
What's the SASL mechanism used? if it is Plain I'd client client_id is the username and secret is the password, but you will need to ask your cluster operator for details.

**Comment by mrshanth** [comment]
Thanks

**Comment by mrshanth** [comment]
Thanks. Yes it's PLAIN.

**Comment by Pallabee94** [comment]
I'm facing the same issue but for me the SASL mechanism is OAUTHBEARER. Could anyone please help?
