### ISSUE TITLE
Missing documentation for AdminClient.list_groups

### ISSUE THREAD

**Issue by mikael-epigram** [confluentinc/confluent-kafka-python#1206]
There does not seem to be any [documentation](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#pythonclient-adminclient) for `[AdminClient.list_groups](https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/admin/__init__.py#L370)`.

The source code seems to indicate that there should be docs:
https://github.com/confluentinc/confluent-kafka-python/blob/e671bccb8a4f98302748ccf60d5d579f68c6613d/src/confluent_kafka/src/Metadata.c#L627

**Comment by jliunyu** [comment]
Hi @mikael-epigram, thanks for mentioning this. I updated the documentation version and we are able to see the list_groups there: https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html
