### ISSUE TITLE
SystemError: <method 'error' of 'cimpl.Message' objects> returned a result with an error set

### ISSUE THREAD

**Issue by balaji-skoruz** [confluentinc/confluent-kafka-python#1214]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @balaji-skoruz, can you please fill out the checklist?
