### ISSUE TITLE
Python 3.10 wheel build for confluent-kafka 1.7.0

### ISSUE THREAD

**Issue by Gyllsdorff** [confluentinc/confluent-kafka-python#1219]
Description
===========
Python 3.10 have been released but the latest `confluent-kafka` release `1.7.0` don't have a [prebuilt wheel](https://pypi.org/project/confluent-kafka/1.7.0/#files) for it.

It is easy to build it from source but it slows down some of the image build procedures quite a bit. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`)
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`: None
 - [x] Operating system: Linux
 - [x] Provide client logs (with `'debug': '..'` as necessary): none
 - [x] Provide broker log excerpts: none
 - [ ] Critical issue: No

**Comment by grutts** [comment]
Is there a plan to build a wheel for 3.10?

**Comment by david-walker-gfs** [comment]
Interested in this too. Seems 3.9 doesn't yet exist either.

**Comment by ahtik** [comment]
@david-walker-gfs, 3.9 wheels are available, https://pypi.org/project/confluent-kafka/1.7.0/#files

**Comment by johng** [comment]
This would be nice

**Comment by david-walker-gfs** [comment]
> @david-walker-gfs, 3.9 wheels are available, https://pypi.org/project/confluent-kafka/1.7.0/#files

Thanks for the link!

**Comment by edenhill** [comment]
v1.8.2 is now released, with py 3.6-3.9 wheels.  We'll look into v3.10 wheels for the next release.

**Comment by grutts** [comment]
This project releases about 3 times per year. Would you consider releasing a patch (v1.8.3) earlier than the typical release frequency, with 3.10 wheels included?

**Comment by edenhill** [comment]
The slow release cadence is due to severe CI issues during the latter part of 2021. We're soon moving to another solution which will allow us to release more often.

**Comment by grutts** [comment]
Good news! Thanks

**Comment by wkrt7** [comment]
When do you plan to release the wheel for Python 3.10?

**Comment by arroyofnxio** [comment]
Hi @edenhill! Is there any way the community can help to prioritize this issue?

**Comment by saabeilin** [comment]
Upvoting this as well ;-)

**Comment by grutts** [comment]
Hi @edenhill. Do you have an idea of when the next release, with this change included, will be? The release cadence of the project doesn't seem to have changed. Even a 1.8.3 release which just adds the wheels would be helpful.

**Comment by MicaelJarniac** [comment]
We're also relying on this. One thing that could help in the meantime is some clear instructions as to how we could build the lib ourselves.

**Comment by Lightjohn** [comment]
What would be the process to build 3.10 wheels?

**Comment by johng** [comment]
Any update here? It's been over 5 months since the last release

**Comment by AntonOfTheWoods** [comment]
While it is definitely annoying they aren't keeping up with the maintainer-recommended versions of Python, simply installing `librdkafka-dev` (debian derivatives), or the equivalent for your platform seems to do the trick.

**Comment by lpsinger** [comment]
confluent-kafka-python 1.9.0 is out now, but there are still no wheels for Python 3.10. Python 3.10 has been out for over 8 months. Please build wheels for Python 3.10!

**Comment by Lightjohn** [comment]
When I tried to build it locally:
In `tools/wheels/build-wheels.sh`:
* I had to bump `cibuildwheel` to newer (latest in my case) line 55
* Play a bit with CIBW_BUILD env  line 12 (which I added because I only wanted one wheel)
And it was enough for me.

**Comment by AntonOfTheWoods** [comment]
Further to my above comment that all that was required was installing `librdkafka-dev`, `1.9.0` now requires that you get the latest version, which of course is not in any distribution's repos. So you have to either add their repo or manually download and install the package. This is all just way to much hassle when there are equally performant alternatives that Just Work. I'm outta here.

**Comment by disrupted** [comment]
> This is all just way to much hassle when there are equally performant alternatives that Just Work. I'm outta here.

Can you suggest an alternative?

**Comment by edenhill** [comment]
Python 3.10 wheels are now available on PyPi for Linux, OSX (x64) and Windows

**Comment by lpsinger** [comment]
Thank you so much!

**Comment by pranavrth** [comment]
Hey @andreagrandi,

We don't have linux arm64 wheel as of now. We will provide that in the next release. Please check [this issue](https://github.com/confluentinc/confluent-kafka-python/issues/1466) where I am providing the updates.

**Comment by andreagrandi** [comment]
> We don't have linux arm64 wheel as of now. We will provide that in the next release. Please check https://github.com/confluentinc/confluent-kafka-python/issues/1466 where I am providing the updates.

hi @pranavrth and thanks for your reply!

I do apologise for the maybe dumb question, but I'm a bit confused with architectures and Docker 😅

The existing wheel is valid for M1/M2 CPUs but only if I `pip install confluent-kafka` directly on my Mac and not from a `Dockerfile` running on this Mac, is it correct?

If yes, how can our `Dockerfile` work when building on our CI (we use CircleCI) or AWS? I always assumed those servers where using arm64 CPUs 🤔

Thanks again for your help

**Comment by ChillarAnand** [comment]
> The existing wheel is valid for M1/M2 CPUs but only if I pip install confluent-kafka directly on my Mac and not from a Dockerfile running on this Mac, is it correct?

@andreagrandi  Yes. Currently, wheels are available for x86_64 & arm64. But they are not yet available for linux-aarch64.

A docker running on Mac M1(arm64) will be using linux-aarch64. You can run `uname -a` in the container and see the architecture. 

If you want to run it Docker inside Mac M1, you have to build it from source. See this thread on more details. https://github.com/confluentinc/librdkafka/issues/3546#issuecomment-1445646185
