### ISSUE TITLE
CachedSchemaRegistryClient fails on unhashable avro schemas

### ISSUE THREAD

**Issue by kwilcox** [confluentinc/confluent-kafka-python#122]
This is due to a bug in `avro` where schemas are not hashable (and therefore not able to be used as dict keys): https://issues.apache.org/jira/browse/AVRO-1737. Adding this issue to track upstream and so others with the same issue can easily search for a solution.

If you are presented with something like this:

```python
Traceback (most recent call last):
  ...
  .../site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 121, in register
    schema_id = schemas_to_id.get(avro_schema, None)
TypeError: unhashable type: 'EnumSchema'
```

You can patch the `__hash__` function for each schema type as a fix. Patching the parent `Schema` class does not work!

```python
# Monkey patch to get hashable avro schemas
# https://issues.apache.org/jira/browse/AVRO-1737
# https://github.com/confluentinc/confluent-kafka-python/issues/122
from avro import schema
def hash_func(self):
    return hash(str(self))
schema.EnumSchema.__hash__ = hash_func
schema.RecordSchema.__hash__ = hash_func
schema.PrimitiveSchema.__hash__ = hash_func
schema.ArraySchema.__hash__ = hash_func
schema.FixedSchema.__hash__ = hash_func
schema.MapSchema.__hash__ = hash_func
```

**Comment by edenhill** [comment]
@kwilcox Thanks for heads-up!

**Comment by blbradley** [comment]
@kwilcox I just experienced this. Thanks for the detailed report!

**Comment by rnpridgeon** [comment]
Although closed this has yet to be fixed upstream. Please first refer to AVRO-1737 if you run into issues

**Comment by kwilcox** [comment]
https://issues.apache.org/jira/browse/AVRO-1737
