### ISSUE TITLE
Disconnected errors after switching to Confluent Cloud cluster

### ISSUE THREAD

**Issue by nilansaha** [confluentinc/confluent-kafka-python#1223]
Description
===========

I used to use a self hosted Kafka cluster and recently switched to a confluent cloud kafka cluster. After switching I have seen these logs a couple of times in my consumers.

```
%6|1634316630.265|FAIL|rdkafka#consumer-2| [thrd:sasl_ssl://xxxxx.eu-west-1.aws.confluent.cloud:9092/14]: sasl_ssl://xxxx.aws.confluent.cloud:9092/14: Disconnected (after 34529063ms in state UP)
```
I need help understanding a few things - 
1. Are these logs actual failures that should be investigated or just extra verbose state transitions ?
2. If they are not actual failures that should be investigated is there any way to disable them from my side ?
3. If they are not actual failures why are the still logged as one. Shouldn't this be fixed on a library level ?
4. If these should be investigated what could be some possible scenarios for this to happen ?

**Comment by jliunyu** [comment]
Looks this is similar with https://github.com/confluentinc/confluent-kafka-python/issues/638, and the answer https://github.com/confluentinc/confluent-kafka-python/issues/638#issuecomment-511218433 from https://github.com/confluentinc/confluent-kafka-python/issues/638 could also be good for this one.
