### ISSUE TITLE
Check the alternative producer of AvroProducer

### ISSUE THREAD

**Issue by MarsSu0618** [confluentinc/confluent-kafka-python#1225]
### Description
According to [the confluent-kafka api document](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#), we found that the **AvroProducer** is marked **legacy**.
If we want to operate the same things like AvroProducer, how can we implement it with alternative methods? 
Hope someone can awsner. I will be appreciate it.

**Comment by jliunyu** [comment]
Hi @MarsSu0618 , thanks for asking. We can use serializing producer and consumer to produce and consume Avro messages as an alternative method. https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_producer.py and https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_consumer.py are examples.

**Comment by MarsSu0618** [comment]
@jliunyu OK, thanks. I also have implement through this solution.
