### ISSUE TITLE
Admin client fails to show updated topics immediately after create_topic through list_topics

### ISSUE THREAD

**Issue by OneRaynyDay** [confluentinc/confluent-kafka-python#1230]
Description
===========

I'm experiencing a flaky behavior where upon `AdminClient(...).create_topics([NewTopic(topic, ...)])` and I immediately `AdminClient.list_topics(timeout=-1)`, I don't see the topic. I suspect one of the following is happening:

 - `create_topics` not guaranteed to have actually created the topic (i.e. non-blocking)
 - Topics are accurately added to the same broker but I may be calling `list_topics` from other broker hosts which don't have the converged, updated information
 - Zookeeper has updated the information during `create_topics` but there's some caching layer above zookeeper which was stale for other brokers.

I might be wrong. Any info would be greatly appreciated!

How to reproduce
================

I am currently using Kafka 2.8.0 installed from [this mirror](https://ftp.wayne.edu/apache/kafka/2.8.0/kafka_2.13-2.8.0.tgz). The client I am using is `confluent-kafka==1.7.0`.

```
>>> confluent_kafka.libversion()
('1.7.0', 17236223)
>>> confluent_kafka.version()
('1.7.0', 17235968)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): provided above
 - [x] Apache Kafka broker version: provided above
 - [x] Client configuration: `{"bootstrap.servers": "hosta,hostb,hostc"}`. No additional settings.
 - [x] Operating system: Debian linux

**Comment by pranavrth** [comment]
You can't force the requests to go to the same broker.

Closing this issue as the question has been answered. Feel free to open it if required.
