### ISSUE TITLE
1.8.0 Release?

### ISSUE THREAD

**Issue by ElTav** [confluentinc/confluent-kafka-python#1233]
Description
===========

When can we anticipate the 1.8.0 release? We would like to pull in some of the changes from [librdkafka 1.8.0](https://github.com/edenhill/librdkafka/blob/master/CHANGELOG.md#fixes-2)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ElTav** [comment]
cc @jliunyu

**Comment by jliunyu** [comment]
Hi @ElTav, thanks for asking. Our release is blocked by CI test environment before. We will update to you once we have an ETA for release.

**Comment by ElTav** [comment]
@jliunyu Understood, do you an idea of how roughly how long you expect it to be (days/weeks/months)? And whether you'll release 1.8.2 at the same time?

**Comment by Atheuz** [comment]
@jliunyu do you have an update? I'm missing some changes from this PR: https://github.com/confluentinc/confluent-kafka-python/pull/1133

**Comment by jliunyu** [comment]
Hi @Atheuz , yes, the release change for 1.8.0 is under review now, we will release it very soon.

**Comment by Atheuz** [comment]
@jliunyu this week, next week, after new year?

**Comment by Atheuz** [comment]
This is out now it seems.

**Comment by edenhill** [comment]
v1.8.2 was released last week

**Comment by hannseman** [comment]
@edenhill looks like v1.8.2 is missing a source distribution on PyPI, I can only see wheels. Is this intentional?
