### ISSUE TITLE
Consumer doesn't raise error if `"group.id"` is a non-string, also doesn't get messages

### ISSUE THREAD

**Issue by rkoeninger** [confluentinc/confluent-kafka-python#1234]
Description
===========

(Enhancement suggestion; addition to work done in #506 )

While doing some testing, I tried using a generated group id to easily get messages from the beginning:

```python
consumer = Consumer({
    "bootstrap.servers": "my-server",
    "security.protocol": "SASL_SSL",
    "sasl.mechanisms": "PLAIN",
    "sasl.username": "my-username",
    "sasl.password": "my-password",
    "group.id": uuid4()
})
```

I forgot to `str` the UUID. Passing a non-string group id allowed the `Consumer` to be created and polled without error but never returned any messages. Calling `str` on the UUID fixed it like: `str(uuid4())`.

The code modified in PR #506 could be further modified to apply the `PyObject_Str` function to coerce the `group.id` to a string or a type check to confirm it is a string (raise error if not) before passing the value onto the underlying C library.

In my case, a `PyObject*` referring to a `uuid.UUID` was passed to `librdkafka` and undefined behavior happened.

How to reproduce
================

Try `poll`ing from a topic using a non-string `group.id` like the code above. `poll` should timeout every time, returning `None`.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
   - `confluent_kafka.version()` = `('1.7.0', 17235968)`
   - `confluent_kafka.libversion()` = `('1.7.0', 17236223)`
 - [x] Apache Kafka broker version:
   - using Confluent Cloud
 - [x] Client configuration: `{...}`
   - example given above
 - [x] Operating system:
   - Windows 10
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [x] Provide broker log excerpts

**Comment by jliunyu** [comment]
Hi @rkoeninger, thanks for reporting this. I tried to reproduce it with my mac, but it works fine with "group.id" : uuid4(). From our integration_test.py, it also use UUID without a str(). But I saw you are using Windows 10, can you please add `"debug": "all"` to the config and provide the logs?

**Comment by rkoeninger** [comment]
Closing this issue since I can no longer replicate based on the description. Not sure if I remember correctly, but I think the problem may have been that I needed to set `auto.offset.reset` to `earliest`.
