### ISSUE TITLE
Python.h: No such file or directory

### ISSUE THREAD

**Issue by bluecorridor** [confluentinc/confluent-kafka-python#1236]
Description
===========
confluent-kafka 1.7.0
rhel7
python3.8

Attempting to install confluent-kafka via Dockerfile (rhel7 and python3.8 image), but can't seem to resolve this error (log below)

I've tried to install python3-devel, and librdkafka-devel but both packages were not available. I did check that rh-python38-python-devel.x86_64 was installed.

I see a lot of references to "3.6" in the output, wondering if this is indicating that python 3.8 is not playing with with the confluent_kafka package that tries to install? Is it expecting 3.6? (we pull packages from an artifactory instance)

17.56 Installing collected packages: confluent-kafka
17.56   Running setup.py install for confluent-kafka: started
17.92     Running setup.py install for confluent-kafka: finished with status 'error'
17.92     Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yj3_4bet/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7ryn47ix-record/install-record.txt --single-version-externally-managed --compile:
17.92     running install
17.92     running build
17.92     running build_py
17.92     creating build
17.92     creating build/lib.linux-x86_64-3.6
17.92     creating build/lib.linux-x86_64-3.6/confluent_kafka
17.92     copying src/confluent_kafka/error.py -> build/lib.linux-x86_64-3.6/confluent_kafka
17.92     copying src/confluent_kafka/deserializing_consumer.py -> build/lib.linux-x86_64-3.6/confluent_kafka
17.92     copying src/confluent_kafka/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka
17.92     copying src/confluent_kafka/serializing_producer.py -> build/lib.linux-x86_64-3.6/confluent_kafka
17.92     creating build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
17.92     copying src/confluent_kafka/schema_registry/json_schema.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
17.92     copying src/confluent_kafka/schema_registry/error.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
17.92     copying src/confluent_kafka/schema_registry/schema_registry_client.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
17.92     copying src/confluent_kafka/schema_registry/protobuf.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
17.92     copying src/confluent_kafka/schema_registry/avro.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
17.92     copying src/confluent_kafka/schema_registry/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/schema_registry
17.92     creating build/lib.linux-x86_64-3.6/confluent_kafka/admin
17.92     copying src/confluent_kafka/admin/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/admin
17.92     creating build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
17.92     copying src/confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
17.92     copying src/confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
17.92     copying src/confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
17.92     copying src/confluent_kafka/kafkatest/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
17.92     creating build/lib.linux-x86_64-3.6/confluent_kafka/avro
17.92     copying src/confluent_kafka/avro/load.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
17.92     copying src/confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
17.92     copying src/confluent_kafka/avro/error.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
17.92     copying src/confluent_kafka/avro/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
17.92     creating build/lib.linux-x86_64-3.6/confluent_kafka/serialization
17.92     copying src/confluent_kafka/serialization/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/serialization
17.92     creating build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
17.92     copying src/confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
17.92     copying src/confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
17.92     running build_ext
17.92     building 'confluent_kafka.cimpl' extension
17.92     creating build/temp.linux-x86_64-3.6
17.92     creating build/temp.linux-x86_64-3.6/tmp
17.92     creating build/temp.linux-x86_64-3.6/tmp/pip-build-yj3_4bet
17.92     creating build/temp.linux-x86_64-3.6/tmp/pip-build-yj3_4bet/confluent-kafka
17.92     creating build/temp.linux-x86_64-3.6/tmp/pip-build-yj3_4bet/confluent-kafka/src
17.92     creating build/temp.linux-x86_64-3.6/tmp/pip-build-yj3_4bet/confluent-kafka/src/confluent_kafka
17.92     creating build/temp.linux-x86_64-3.6/tmp/pip-build-yj3_4bet/confluent-kafka/src/confluent_kafka/src
17.92     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/pip-build-yj3_4bet/confluent-kafka/src/confluent_kafka/src/confluent_kafka.c -o build/temp.linux-x86_64-3.6/tmp/pip-build-yj3_4bet/confluent-kafka/src/confluent_kafka/src/confluent_kafka.o
17.92     In file included from /tmp/pip-build-yj3_4bet/confluent-kafka/src/confluent_kafka/src/confluent_kafka.c:17:0:
17.92     /tmp/pip-build-yj3_4bet/confluent-kafka/src/confluent_kafka/src/confluent_kafka.h:18:20: fatal error: Python.h: No such file or directory
17.92      #include <Python.h>
17.92                         ^
17.92     compilation terminated.
17.92     error: command 'gcc' failed with exit status 1
17.92
17.92     ----------------------------------------
17.93 Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yj3_4bet/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7ryn47ix-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yj3_4bet/confluent-kafka/

How to reproduce
================

python3 -m pip install --index-url <removed> confluent_kafka

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @bluecorridor, thanks for asking, looks like you haven't properly installed the header files and static libraries for python dev, you can try with the following command: 
```
sudo yum install python-devel    # for python2.x installs
sudo yum install python3-devel   # for python3.x installs
```

Refer to https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory
