### ISSUE TITLE
Python consumer can't connect via SASL_SSL protocol

### ISSUE THREAD

**Issue by timotiusnico** [confluentinc/confluent-kafka-python#1238]
Description
===========
I tried to connect to a confluent kafka topic using sasl_ssl, however the following we got the following error

%3|1637030289.492|SSL|rdkafka#consumer-1| [thrd:app]: error:0906D06C:PEM routines:PEM_read_bio:no start line: **Expecting: ANY PRIVATE KEY**
Traceback (most recent call last):
  File "consumer.py", line 69, in <module>
    'ssl.keystore.password':'password'
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create consumer: ssl.key.location failed: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib"}

How to reproduce
================

The configuration is used for the python

    'bootstrap.servers': "<servers>",
    'group.id': '<groupid>',
    'auto.offset.reset': 'latest',
    'security.protocol':'SASL_SSL',
    'sasl.mechanisms':'GSSAPI',
    'sasl.kerberos.service.name': '<kerberosuser>',
    'sasl.kerberos.principal': '<kerberosuser>@domain',
    'sasl.kerberos.keytab': '<kerberosuser>.keytab',
    'ssl.ca.location':'kafka_broker.pem',
    'ssl.key.location':'kafka_broker.pem',
    'ssl.key.password':'password',
    'ssl.certificate.location':'kafka_broker.pem',
    'ssl.keystore.location':'kafka_broker.p12',
    'ssl.keystore.password':'password'

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):  confluent_kafka.version() : ('1.7.0', 17235968) &  confluent_kafka.libversion() : ('1.8.2', 17302271)
 - [ ] Apache Kafka broker version: 
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Red Hat Enterprise Linux 7.6
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
According to https://stackoverflow.com/questions/18460035/unable-to-load-private-key-pem-routinespem-read-biono-start-linepem-lib-c6, looks the format of your key is not correct.
