### ISSUE TITLE
install on RED HAT with python3 with GSSAPI/Kerberos support

### ISSUE THREAD

**Issue by bbirkental** [confluentinc/confluent-kafka-python#1243]
Description
===========
Hi.
I am using RED HAT Linux with python 3.6.
I want to install confluent-kafka Python package with GSSAPI/Kerberos support.

After reading the instruction here from the main page, this is what I did so far, but it is not good enough:
sudo yum install librdkafka-devel 
sudo yum install -y python3-devel.x86_64
sudo yum install openldap-devel
pip install --no-binary :all: confluent-kafka

How to reproduce
================
Please provide me a step by step guide for what to do in order to install confluent-kafka Python package with GSSAPI/Kerberos support.

**Comment by edenhill** [comment]
Please provide command output / logs

**Comment by jliunyu** [comment]
Please feel free to reopen it with command output / logs if you still need help from our side.
