### ISSUE TITLE
Build failing for arm64 

### ISSUE THREAD

**Issue by odidev** [confluentinc/confluent-kafka-python#1245]
I have been working on installing and testing confluent-kafka-python package for amd64 and arm64 architectures. I have added arm64 job in **.travis.yml** file, getting the below error on arm64 architecture for the command "tools/install-interceptors.sh" failed.
```
E: Unable to locate package confluent-librdkafka-plugins 
153The command "tools/install-interceptors.sh" failed and exited with 100 during. 
```
Further, I explored about it, got an [issue](https://github.com/confluentinc/confluent-kafka-go/issues/388#issuecomment-546895975) mention that source code is not available for confluent-librdkafka-plugins.

Could you please provide your feedback regarding this. 

Log for reference: https://app.travis-ci.com/github/odidev/confluent-kafka-python/jobs/550981853

**Comment by jliunyu** [comment]
Please use this one to track the arm 64 installation issue: https://github.com/confluentinc/confluent-kafka-python/issues/1260

**Comment by odidev** [comment]
Thanks @jliunyu for your response.

I followed the above issue in my local arm server and installed the confluent-kafka-python package on arm64. while testing this package using the “./tests/run.sh unit” command, getting the below error, after checking it a little bit I have found that the “confluentinc/cp-schema-registry“ image is not available for arm64. 
Can you please share some pointers on this. 

**Error:**
`E           subprocess.CalledProcessError: Command '(docker images -q "confluentinc/cp-schema-registry:latest" 2>/dev/null | grep -q ^.) || docker pull confluentinc/cp-schema-registry:latest' returned non-zero exit status 1. `

**Error logs:** [confluent-kafka-python_tests_arm64.txt](https://github.com/confluentinc/confluent-kafka-python/files/8377309/confluent-kafka-python_tests_arm64.txt)

**Comment by odidev** [comment]
@jliunyu Is there any update for the above issue ?

**Comment by odidev** [comment]
@jliunyu Can you please provide your feedback on the above issue ?
