### ISSUE TITLE
[docs] a little typo in API documentation

### ISSUE THREAD

**Issue by jaeykweon** [confluentinc/confluent-kafka-python#1246]
Description
===========

![image](https://user-images.githubusercontent.com/30148662/145175789-29b71d3e-1472-405c-9c2c-1fb4a6016aad.png)

> typo in https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Producer.produce

How to reproduce
================

> **dict|list** (_headers_) -> **headers** (_dict|list_)

**Comment by jliunyu** [comment]
Fix for it: https://github.com/confluentinc/confluent-kafka-python/pull/1294
