### ISSUE TITLE
Timestamps and api_version for v0.10

### ISSUE THREAD

**Issue by kyrsideris** [confluentinc/confluent-kafka-python#125]
I was trying to understand why our Java Kafka Stream application was complaining on `Extracted timestamp value is negative` and I captured/debug the packets of `confluent-kafka-python`. I realised that although I was setting the `'api.version.request': 'true'` in the producer, the `Produce Request` and `Produce Response` packets had `api_version` set to 1. Moreover, wiresharks kafka dissector was complaining with malformed packet in v0.10 (when `'api.version.request': 'true'`) only on `Produce Request`. Moreover, the Kafka broker reports that `message.timestamp.type -> CreateTime`.

I experimented with the following setups:

| librdkafka      | confluent-kafka-python           | `'api.version.request'`  |
| :------------: | :----------------------------: | :----------------------: |
| 0.9.2-RC1      | 0.9.2                                          | _not set_    |
| 0.9.3              | 0.9.2                                          | _not set_  |
| 0.9.3              | 0.9.2                                          |   `'true'`    |

In all cases the api_version is equal to 1 and the packet is malformed only in v0.10 case.
1) I understand that the kafka dissector may not be update for the latest Kafka version but the packet structure for the Produce Request is the same in all versions
2) Produce Response are not the same in all versions because the api version 2 (v0.10) has `timestamp => INT64`, but the dissector is not complaining on their packet format.
3) The api_version is 1 in all tries, I was expecting to see 2 in v0.10, correct?

I gained my understanding on packet format from the [protocol page](http://kafka.apache.org/protocol.html#protocol_messages).

I am attaching the three packet captures: [packet_captures.zip](https://github.com/confluentinc/confluent-kafka-python/files/771793/packet_captures.zip)

So my question are:
1) Should I have api_version set to 2 on v0.10 messages when I set `'api.version.request': 'true'`?
2) In this the reason that I don't get timestamped messages on Kafka Stream application, after the broker?
3) Do I need to set other flags for the timestamp-ing of messages for version v0.10?

Thanks a lot for your time! :)

**Comment by edenhill** [comment]
Thanks for a great report!

And you are absolutely right, librdkafka is sending the wrong ProduceRequestion version, sending 1 instead of 2.
I've discussed this with the Kafka core team and the broker actually doesn't correlate the message version to the produce requestion version, so it actually works anyway, but I'll make sure to fix this in librdkafka.

> In all cases the api_version is equal to 1 and the packet is malformed only in v0.10 case.

Is the broker complaining about the received request? (typically some Malformed../Invalid../Buffer.. exception)


Can you use another consumer (than Streams) to verify the timestamps of the messages?
E.g.: `kafkacat -b $BROKERS -G mygroup -X api.version.request=true -f '%t %p @ %o: %T\n' mytopic` should print the timestamps

**Comment by skyrocknroll** [comment]
@edenhill is this a blocker. We are using kafka 0.10 with schema registry and producer is written in java but consumer is written Python. Do we get into compatibility issues.

**Comment by edenhill** [comment]
@skyrocknroll No this issue only mildly affects the producer by not being able to return the assigned timestamp of a produced message back to the application (but Ive not seen a demand or use-case for that anyway).

**Comment by edenhill** [comment]
Upstream issue:
https://github.com/edenhill/librdkafka/issues/1087
