### ISSUE TITLE
avro_producer example is broken

### ISSUE THREAD

**Issue by DanielIhms** [confluentinc/confluent-kafka-python#1253]
Description
===========
The example "avro_producer.py" is broken due to wrong order of input parameters.

`avro_serializer = AvroSerializer(schema_str,
                                     schema_registry_client,
                                     user_to_dict)`

Error-Message
================
AttributeError: 'SchemaRegistryClient' object has no attribute 'strip'

How to fix
================
`avro_serializer = AvroSerializer(schema_registry_client,
                                     schema_str,
                                     user_to_dict)`

**Comment by jliunyu** [comment]
Thanks for reporting this @DanielIhms , I added this to our backlog, will fix it soon.

**Comment by jliunyu** [comment]
This one is fixed vis https://github.com/confluentinc/confluent-kafka-python/pull/1263/files
