### ISSUE TITLE
Unrecognized field: schemaType

### ISSUE THREAD

**Issue by alegue87** [confluentinc/confluent-kafka-python#1254]
Description
===========
Hi, i have encountered this error **Unrecognized field: schemaType (HTTP status code 422, SR code 422)** when i execute the [json_producer.py](https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/json_producer.py) example. I don't have modified anything in the code, so is the original.

How to reproduce
================

This is my docker-compose file:

`
version: '3.3'
services:
    postgres:
        container_name: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=shipment_db
            - PGPASSWORD=password
        image: 'debezium/postgres:13'

    zookeeper:
        container_name: zookeeper
        ports:
            - '2181:2181'
            - '2888:2888'
            - '3888:3888'
        image: 'debezium/zookeeper:1.7'

    kafka:
        container_name: kafka
        ports:
            - '9092:9092'
        links:
            - 'zookeeper:zookeeper'
        image: 'debezium/kafka:1.7'
        environment:
            ZOOKEEPER_CONNECT: zookeeper:2181
        #volumes:
        #    - ./kafka:/kafka/config:rw

    connect:
        image: debezium/connect:1.7
        hostname: connect
        container_name: connect
        ports:
            - 8083:8083
        environment:
            BOOTSTRAP_SERVERS: kafka:9092
            GROUP_ID: 1
            CONFIG_STORAGE_TOPIC: my_connect_configs
            OFFSET_STORAGE_TOPIC: my_connect_offsets
            STATUS_STORAGE_TOPIC: my_connect_statuses
            CONNECT_BOOTSTRAP_SERVERS: kafka:9092
            CONNECT_GROUP_ID: connect-cluster-A
            CONNECT_PLUGIN_PATH: /kafka/data, /kafka/connect
            #EXTERNAL_LIBS_DIR: /kafka/external_libs,/kafka/data
            CLASSPATH: /kafka/data/*
            KAFKA_CONNECT_PLUGINS_DIR: /kafka/data, /kafka/connect

        volumes:
            - type: bind
              source: ./plugins
              target: /kafka/data
        depends_on:
            - zookeeper
            - kafka
            - postgres
        links:
            - zookeeper
            - kafka
            - postgres

    schema-registry:
        image: confluentinc/cp-schema-registry:5.4.6
        hostname: schema-registry
        container_name: schema-registry
        depends_on:
            - zookeeper
            - kafka
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
            SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"

    ksqldb-server:
        image: confluentinc/ksqldb-server:0.23.1
        hostname: ksqldb-server
        container_name: ksqldb-server
        depends_on:
            - kafka
            - zookeeper
            - schema-registry
        ports:
            - "8088:8088"
        volumes:
            - "./confluent-hub-components/:/usr/share/kafka/plugins/"
        environment:
            KSQL_LISTENERS: "http://0.0.0.0:8088"
            KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
            KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
            KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
            KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
            KSQL_KSQL_CONNECT_URL: http://connect:8083`

The json_produce.py is executed in this way:
`$ python3 json_producer.py -b 0.0.0.0:9092 -s http://0.0.0.0:8081 -t test`
I have tryed also with localhost as address but the result is the same ( i don't think that the problem is here ).

The result stack trace is the following:

`Traceback (most recent call last):
  File "/home/alessio/fm_v2/python/confluent-kafka-python-master/examples/venv_examples/lib/python3.8/site-packages/confluent_kafka/serializing_producer.py", line 172, in produce
    value = self._value_serializer(value, ctx)
  File "/home/alessio/fm_v2/python/confluent-kafka-python-master/examples/venv_examples/lib/python3.8/site-packages/confluent_kafka/schema_registry/json_schema.py", line 190, in __call__
    self._schema_id = self._registry.register_schema(subject,
  File "/home/alessio/fm_v2/python/confluent-kafka-python-master/examples/venv_examples/lib/python3.8/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 336, in register_schema
    response = self._rest_client.post(
  File "/home/alessio/fm_v2/python/confluent-kafka-python-master/examples/venv_examples/lib/python3.8/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 127, in post
    return self.send_request(url, method='POST', body=body)
  File "/home/alessio/fm_v2/python/confluent-kafka-python-master/examples/venv_examples/lib/python3.8/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 174, in send_request
    raise SchemaRegistryError(response.status_code,
confluent_kafka.schema_registry.error.SchemaRegistryError: **Unrecognized field: schemaType (HTTP status code 422, SR code 422)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "json_producer.py", line 172, in <module>
    main(parser.parse_args())
  File "json_producer.py", line 151, in main
    producer.produce(topic=topic, key=str(uuid4()), value=user,
  File "/home/alessio/fm_v2/python/confluent-kafka-python-master/examples/venv_examples/lib/python3.8/site-packages/confluent_kafka/serializing_producer.py", line 174, in produce
    raise ValueSerializationError(se)
**confluent_kafka.error.ValueSerializationError: KafkaError{code=_VALUE_SERIALIZATION,val=-161,str="Unrecognized field: schemaType (HTTP status code 422, SR code 422)"}`**

Thanks for any reply.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x ] Apache Kafka broker version:
 - [ x] Client configuration: `{...}`
 - [ ] Operating system:
 - [x ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by alegue87** [comment]
resolved: https://stackoverflow.com/questions/70558327/confluent-kafka-python-json-producer-unrecognized-field-schematype/70633615#70633615

**Comment by anjali29singh** [comment]
I am getting same issue  i have  stored schema in .avsc file  . i am using kafka-confluent =2.8 
if conf['schemaConf']['avroFilePath'] is not None:
            schema_str = open(f'avroSchemas/{conf["schemaConf"]["avroFilePath"]}', 'r').read()
            self.schema_obj = Schema(
                schema_str,
                # schema_type='AVRO'
                    )
        else:
            self.schema_obj = None

        self.schema_subject = f"{conf['kafkaConf']['topic']}-value"

        self.schemaRegistryHelper = SchemaRegistryHelper(conf['schemaConf'])

        self.conf = conf

        self.schema_str = None
        self.avro_serializer = None
