### ISSUE TITLE
Breaking changes in 1.8.2 when compared to 1.7.0

### ISSUE THREAD

**Issue by Atheuz** [confluentinc/confluent-kafka-python#1258]
Description
===========
1.8.2 was recently released. This version introduced at least 2 breaking changes as far as I can tell:

(1)
> IMPORTANT: Added mandatory use.deprecated.format to ProtobufSerializer and ProtobufDeserializer.

When you upgrade to 1.8.2 from 1.7.0 you must now specify `use.deprecated.format`. This means that if you have an "unpinned" dependency, such as >=1.7.0 in your requirements for your application and you create a new version of your application, your application will now be bricked until you add the `use.deprecated.format` option to ProtobufSerializer and ProtobufDeserializer.
This is contrary to SemVer in that it appears, at least to me, to be a breaking change.

(2)
> IMPORTANT: Added mandatory use.deprecated.format to ProtobufSerializer and ProtobufDeserializer.

In 1.7.0 you had no ability to configure ProtobufDeserializer in that it didn't have a conf kwarg:
1.7.0:
https://github.com/confluentinc/confluent-kafka-python/blob/v1.7.0/src/confluent_kafka/schema_registry/protobuf.py#L351

1.8.0:
https://github.com/confluentinc/confluent-kafka-python/blob/v1.8.2/src/confluent_kafka/schema_registry/protobuf.py#L465

ProtobufSerializer "appears" to be unaffected, as it did have a conf kwarg:
1.7.0:
https://github.com/confluentinc/confluent-kafka-python/blob/v1.7.0/src/confluent_kafka/schema_registry/protobuf.py#L207

1.8.2:
https://github.com/confluentinc/confluent-kafka-python/blob/v1.8.2/src/confluent_kafka/schema_registry/protobuf.py#L230

But it actually fails here:
https://github.com/confluentinc/confluent-kafka-python/blob/v1.7.0/src/confluent_kafka/schema_registry/protobuf.py#L226-L228

Because use.deprecated.format is not a recognized property in 1.7.0.

As such, if you're using 1.7.0 and try to specify `use.deprecated.format` for ProtobufDeserializer you get a TypeError: 
"TypeError: got an unexpected keyword argument 'conf'"

And if you try to specify `use.deprecated.format` for ProtobufSerializer you get a ValueError:
"ValueError: Unrecognized properties: use.deprecated.format"

Basically meaning you're forced to either stay on 1.7.0 (and give up all the bug fixes) or upgrade to 1.8.2 for all protobuf kafka clients because their API's are mutually exclusive.

**Please advise?**

How to reproduce
================
1) Copy this file: https://github.com/confluentinc/confluent-kafka-python/blob/2ac0d72b24b14e5246445ad9ce66ec9c8828ef4e/tests/integration/schema_registry/gen/TestProto_pb2.py
2) Copy this code into a file called main.py:
```
from confluent_kafka.schema_registry.protobuf import (
    ProtobufSerializer,
    ProtobufDeserializer,
)
from confluent_kafka.schema_registry import SchemaRegistryClient
from TestProto_pb2 import TestMessage


def protobuf_serializer_no_conf():
    schema_registry_client = SchemaRegistryClient(
        {
            "url": "http://localhost",
        }
    )
    proto_serializer = ProtobufSerializer(
        TestMessage,
        schema_registry_client
    )

def protobuf_serializer():
    schema_registry_client = SchemaRegistryClient(
        {
            "url": "http://localhost",
        }
    )
    proto_serializer = ProtobufSerializer(
        TestMessage,
        schema_registry_client,
        conf={"use.deprecated.format": True},
    )


def protobuf_deserializer_no_conf():
    proto_deserializer = ProtobufDeserializer(
        TestMessage,
    )


def protobuf_deserializer():
    proto_deserializer = ProtobufDeserializer(
        TestMessage,
        conf={"use.deprecated.format": True},
    )


if __name__ == '__main__':
    try:
        print("In protobuf_serializer_no_conf:")
        protobuf_serializer_no_conf()
    except Exception as e:
        print(e)
    print("")

    try:
        print("In protobuf_serializer:")
        protobuf_serializer()
    except Exception as e:
        print(e)
    print("")

    try:
        print("In protobuf_deserializer_no_conf:")
        protobuf_deserializer_no_conf()
    except Exception as e:
        print(e)
    print("")

    try:
        print("In protobuf_deserializer:")
        protobuf_deserializer()
    except Exception as e:
        print(e)
    print("")
```
3) Create a virtualenv with confluent-kafka==1.7.0
4) Run python main.py, producing this output:
```
In protobuf_serializer_no_conf:

In protobuf_serializer:
Unrecognized properties: use.deprecated.format

In protobuf_deserializer_no_conf:

In protobuf_deserializer:
__init__() got an unexpected keyword argument 'conf'
```
5) Upgrade to confluent-kafka==1.8.2
6) Run python main.py, producing this output:
```
In protobuf_serializer_no_conf:
ProtobufSerializer: the 'use.deprecated.format' configuration property must be explicitly set due to backward incompatibility with older confluent-kafka-python Protobuf producers and consumers. See the release notes for more details

In protobuf_serializer:

In protobuf_deserializer_no_conf:
ProtobufDeserializer: the 'use.deprecated.format' configuration property must be explicitly set due to backward incompatibility with older confluent-kafka-python Protobuf producers and consumers. See the release notes for more details

In protobuf_deserializer:

```

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 
 For 1.7.0:
confluent_kafka.version(): ('1.7.0', 17235968)
confluent_kafka.libversion(): ('1.7.0', 17236223)

For 1.8.2:
confluent_kafka.version(): ('1.8.2', 17302016)
confluent_kafka.libversion(): ('1.8.2', 17302271)
 - [X] Apache Kafka broker version: Not relevant.
 - [X] Client configuration: Not relevant, see reproducible example above.
 - [X] Operating system: Ubuntu 20.04.3 LTS
 - [X] Provide client logs: Not relevant.
 - [X] Provide broker log excerpts: Not relevant.
 - [ ] Critical issue

**Comment by hkousha** [comment]
seeing the same issue,

**Comment by edenhill** [comment]
This was a deliberate breaking change because there was no way to fix this without breaking either old or new consumer/producers.  The added requirement of needing to configure the format makes sure data is not lost, and that users formulate an upgrade plan.

**Comment by Atheuz** [comment]
@edenhill I think it should be noted somewhere in the changelog that v1.8.2 is a deliberate breaking change then, because it's not obvious if you're just going off the semver. 

Like here:
https://github.com/confluentinc/confluent-kafka-python/blob/master/CHANGELOG.md#v182

Add:
"**NOTE:** v1.8.2 is a deliberate breaking change, if you're using ProtobufSerializer or ProtobufDeserializer and upgrade from 1.7.0 directly without making changes as described in the upgrade considerations you will run into errors on initialization of those objects."

**Comment by edenhill** [comment]
Thank you for your input.

We pretty much have that there already in this paragraph as part of the Upgrade considerations:
> This has now been fixed, but since the old defect serialization and the new correct serialization are mutually incompatible the user of confluent-kafka-python will need to make an explicit choice which serialization format to use during a transitory phase while old producers and consumers are upgraded.

Also note that the SerializingProducer and DeserializingConsumer interfaces are marked as experimental, so there are still no semver guarantees for this part of the code.
