### ISSUE TITLE
Pip installation failed for version 1.8.2

### ISSUE THREAD

**Issue by besil** [confluentinc/confluent-kafka-python#1259]
Description
===========

Trying to install latest versione from [pypi](https://pypi.org/project/confluent-kafka/1.8.2/#description), but seems the latest version (1.8.2) is not available.
Tools like poetry (which automatically try to upgrade no major versions) fail

How to reproduce
================

$ pip install -i https://pypi.org/simple confluent-kafka==1.8.2 
ERROR: Could not find a version that satisfies the requirement confluent-kafka==1.8.2 (from versions: 0.9.1.1, 0.9.1.2, 0.9.2, 0.9.4, 0.11.0, 0.11.4, 0.11.5, 0.11.6, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.6.0, 1.6.1, 1.7.0)
ERROR: No matching distribution found for confluent-kafka==1.8.2

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): not relevant
 - [x] Apache Kafka broker version: not relevant
 - [x] Client configuration: not relevant
 - [x] Operating system: Apple Intel
 - [x] Provide client logs (with `'debug': '..'` as necessary): not relevant
 - [x] Provide broker log excerpts: not relevant
 - [x] Critical issue: not relevant

**Comment by edenhill** [comment]
Sorry about that, forgot to upload the sdist.
Try now.

Den mån 10 jan. 2022 kl 12:29 skrev Silvio Bernardinello <
***@***.***>:

**Comment by besil** [comment]
Thank you very much, it works
