### ISSUE TITLE
When does Producer.flush() return?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#126]
I am running:

confluent_kafka.version ('0.9.2', 590080), confluent_kafka.libversion ('0.9.1', 590335)

I have a Producer, and I have a loop wherein I send a single short message followed immediately by a flush(). Since I have not explicitly set batch.num.messages or queue.buffering.max.ms in the config I handed in when I created the Producer, I assume these take their default values (10000 messages and 1000 ms, respectively). That is, if I send a single message, I would assume that it would sit on a queue for 1000 ms (one second), then get sent. Since flush() will block until Producer.len() is 0, I would expect flush to block for this amount of time (one second). In my production code, this is in fact what I see. In a test script, however, I see that flush() returns after about exactly 0.1 seconds, i.e. 100 ms. My config in this situation looks like this (Note that some things are commented out):

```
    conf = {'bootstrap.servers': kafka_broker,
        'group.id': 'mygroup',
#        'debug': 'all',   # dumps stuff to stdout
        'socket.timeout.ms': 3000,
        'socket.max.fails': 1,
        'error_cb': my_kafka_error,
        'stats_cb': my_stats_cb,
        'statistics.interval.ms': 1000,
        'client.id': "Master_BE_" + my_ip,
#        'batch.num.messages': 10000,  # default: 10000
#        'queue.buffering.max.ms': 1000, # default: 1000: "Maximum time, in milliseconds, for buffering data on the producer queue." I think this means that if anything is being batched, we will send after this amount of time regardless.
        'api.version.request': True,  # request negotiation of the latest features in broker handshake
#        'partition.assignment.strategy': 'range',
        'partition.assignment.strategy': 'roundrobin',
        'default.topic.config': {
            'message.timeout.ms': 3000,   # How long flush() will hang for
            'acks': 1,  # 1: broker at least writes to its own log before ACKing, and we wait for the ACK
            },
#        'session.timeout.ms': 3000,
        }

```

I see that Producer_flush calls Producer_poll0(500) calls rd_kafka_poll(tmout (i.e. 500)) calls rd_kafka_q_serve(timeout_ms) but then things get confusing to me. Although I notice that the confluent client seems to hardcode a timeout to 500 ms, but none of the times I am observing seem to be 500 ms., so there is something else going on.

**Comment by edenhill** [comment]
I don't have a good answer why you are seeing different behaviour in test and production environments, something is bound to be different, somehow.

You could enable debug: "msg,queue,broker"  to see when your message is actually being sent, which might explain the latency difference.

**Comment by johnrgregg3** [comment]
OK, I did that, and here is what I see:

Thu, 16 Feb 2017 20:25:34:456743 just produced (len 1)
%7|1487276734.456|TOPPAR|Master_BE_23.79.234.201#producer-2| a23-79-234-201.deploy.akamaitechnologies.com:9092/1: arya 
[6] 0+0 msgs
%7|1487276734.456|TOPPAR|Master_BE_23.79.234.201#producer-2| a23-79-234-201.deploy.akamaitechnologies.com:9092/1: arya 
[24] 0+0 msgs
%7|1487276734.456|TOPPAR|Master_BE_23.79.234.201#producer-2| a23-79-234-201.deploy.akamaitechnologies.com:9092/1: arya 
[0] 0+0 msgs
%7|1487276734.556|TOPPAR|Master_BE_23.79.234.201#producer-2| a23-79-234-201.deploy.akamaitechnologies.com:9092/1: arya 
[23] 0+0 msgs
%7|1487276734.556|TOPPAR|Master_BE_23.79.234.201#producer-2| a23-79-234-201.deploy.akamaitechnologies.com:9092/1: arya 
[17] 0+0 msgs


See how the timestamp jumps from 34.456 to 34.556? There is our missing tenth of a second. After that there are many, many log messages like this:

%7|1487276734.557|TOPPAR|Master_BE_23.79.234.201#producer-2| a23-79-234-201.deploy.akamaitechnologies.com:9092/1: arya [12] 0+0 msgs

And eventually I see one of these:

%7|1487276734.557|MSGSET|Master_BE_23.79.234.201#producer-2| a23-79-234-201.deploy.akamaitechnologies.com:9092/1: MessageSet with 1 message(s) delivered

Then my on_delivery callback gets called, followed by my print statement:

Thu, 16 Feb 2017 20:25:34:557849 after flush, len 0

Which, naturally, has the 34.557 timestamp, 0.10 seconds after I produced.

**Comment by edenhill** [comment]
0.9.1 checked when the last message was sent + queue.buffering.max.ms to decide if it should wait for more messages or send immediately, this has been changed on master to actually measure from the time the first message currently in queue was enqueued.

Do you think that could explain what you are seeing?

**Comment by johnrgregg3** [comment]
I don't think so. I have a tight loop:

        for i in range(10):
            try:
                payload = u"{}: {}, {}: Fred the dog went for a walk: topic {}".format(datetime.datetime.now().strftime('%a, %d %b %Y %H:%M:%S:%f'), j, i, topic)
                kafka_producer.produce(topic, payload.encode('utf-8'), on_delivery=my_kafka_cb)
                print("{} just produced (len {})".format(datetime.datetime.now().strftime('%a, %d %b %Y %H:%M:%S:%f'), len(kafka_producer)))
            except KafkaException as ke:
                print("************************** produce() caught KafkaException: {}".format(str(KafkaException)))
            except BufferError as be:
                print("************************** produce() caught BufferError: {}".format(str(be)))

            kafka_producer.flush()
            print("{} after flush, len {}".format(datetime.datetime.now().strftime('%a, %d %b %Y %H:%M:%S:%f'), len(kafka_producer)))

And the output says that the flush always takes 0.10 seconds. Given what you said about 0.9.1, I would think that maybe the first one might return right away, but each one after that would take 1000 ms, according to the default value of queue.buffering.max.ms.

Relevant output:

Thu, 16 Feb 2017 21:49:01:454483 just produced (len 1)
Thu, 16 Feb 2017 21:49:01:536250 my_kafka_cb, len 1
my_kafka_cb: msg: partition 13, topic arya, value Thu, 16 Feb 2017 21:49:01:454442: 0, 0: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:01:536332 after flush, len 0
Thu, 16 Feb 2017 21:49:01:536401 just produced (len 1)
Thu, 16 Feb 2017 21:49:01:636954 my_kafka_cb, len 1
my_kafka_cb: msg: partition 26, topic arya, value Thu, 16 Feb 2017 21:49:01:536364: 0, 1: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:01:637026 after flush, len 0
Thu, 16 Feb 2017 21:49:01:637109 just produced (len 1)
Thu, 16 Feb 2017 21:49:01:737594 my_kafka_cb, len 1
my_kafka_cb: msg: partition 11, topic arya, value Thu, 16 Feb 2017 21:49:01:637055: 0, 2: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:01:737658 after flush, len 0
Thu, 16 Feb 2017 21:49:01:737720 just produced (len 1)
Thu, 16 Feb 2017 21:49:01:838130 my_kafka_cb, len 1
my_kafka_cb: msg: partition 18, topic arya, value Thu, 16 Feb 2017 21:49:01:737688: 0, 3: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:01:838191 after flush, len 0
Thu, 16 Feb 2017 21:49:01:838251 just produced (len 1)
Thu, 16 Feb 2017 21:49:01:938847 my_kafka_cb, len 1
my_kafka_cb: msg: partition 27, topic arya, value Thu, 16 Feb 2017 21:49:01:838220: 0, 4: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:01:938926 after flush, len 0
Thu, 16 Feb 2017 21:49:01:938976 just produced (len 1)
Thu, 16 Feb 2017 21:49:02:039589 my_kafka_cb, len 1
my_kafka_cb: msg: partition 3, topic arya, value Thu, 16 Feb 2017 21:49:01:938944: 0, 5: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:02:039663 after flush, len 0
Thu, 16 Feb 2017 21:49:02:039711 just produced (len 1)
Thu, 16 Feb 2017 21:49:02:140292 my_kafka_cb, len 1
my_kafka_cb: msg: partition 6, topic arya, value Thu, 16 Feb 2017 21:49:02:039681: 0, 6: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:02:140382 after flush, len 0
Thu, 16 Feb 2017 21:49:02:140450 just produced (len 1)
Thu, 16 Feb 2017 21:49:02:240905 my_kafka_cb, len 1
my_kafka_cb: msg: partition 28, topic arya, value Thu, 16 Feb 2017 21:49:02:140408: 0, 7: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:02:240988 after flush, len 0
Thu, 16 Feb 2017 21:49:02:241035 just produced (len 1)
Thu, 16 Feb 2017 21:49:02:341572 my_kafka_cb, len 1
my_kafka_cb: msg: partition 2, topic arya, value Thu, 16 Feb 2017 21:49:02:241006: 0, 8: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:02:341651 after flush, len 0
Thu, 16 Feb 2017 21:49:02:341698 just produced (len 1)
Thu, 16 Feb 2017 21:49:02:442269 my_kafka_cb, len 1
my_kafka_cb: msg: partition 20, topic arya, value Thu, 16 Feb 2017 21:49:02:341669: 0, 9: Fred the dog went for a walk: topic arya
Thu, 16 Feb 2017 21:49:02:442373 after flush, len 0


I think I've seen other cases in which flush returns even more quickly, without seeming to wait the 1000 ms, but I don't have any hard data for that yet.

**Comment by edenhill** [comment]
Oh, flush() will return as soon as the output queue length reaches 0 (or timeout occurs)

**Comment by johnrgregg3** [comment]
Yes, but right after I produce() a single message, the queue length should not be 0 until 1000 ms have passed, given that the default of queue.buffering.max.ms is 100, right? That single message should sit on the queue for 1000 ms, then get sent, and only then will the queue length be 0, and only then will flush() return. In all the cases I'm talking about here, I only flush right after producing a message.

**Comment by edenhill** [comment]
Yes, you are right.
There's been alot of changes since 0.9.1 and we'll be releasing librdkafka 0.9.4 very soon.
Since this is probably not a blocker for you (right?), I suggest that we give this another go when 0.9.4 is released (or if you want to build off master yourself).
What do you think about that?

**Comment by johnrgregg3** [comment]
OK. I just upgraded to 0.9.3, and I still see the same 0.10 second delay. I'll wait for 0.9.4 and try again, and yes, it's not a blocker. I'm just trying to understand batching, so I can optimize a potentially high volume of messages. Mostly I'm surprised that I don't see the 1000 ms delay, and that makes me worry that no batching is taking place, which would be suboptimal from a performance point of view.

**Comment by edenhill** [comment]
librdkafka 0.9.4 has now been released, can you give it a go? Thanks

**Comment by johnrgregg3** [comment]
Tried 0.9.4, and now all seems well. My call to flush() in the producer blocks for a second, as I would expect.

**Comment by edenhill** [comment]
Great!
