### ISSUE TITLE
Unable to use confluent-kafka with Apple M1 Pro

### ISSUE THREAD

**Issue by pthalasta** [confluentinc/confluent-kafka-python#1260]
Description
===========
I installed the dependencies of librdkafka using `arch -arm64 /opt/homebrew/bin/brew install librdkafka` for M1 and installed confluent-kafka using pip. Though there were no issues during installation like other posts for M1, i'm having issues with using confluent-kafka. When i try to create a simple consumer i get the following error

```
from confluent_kafka.cimpl import Consumer as _ConsumerImpl
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/confluent_kafka/cimpl.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/confluent_kafka/cimpl.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cimpl.cpython-39-darwin.so' (no such file), '/usr/lib/cimpl.cpython-39-darwin.so' (no such file)
```

librdkafka version:
```
librdkafka: stable 1.8.2 (bottled), HEAD
Apache Kafka C/C++ library
https://github.com/edenhill/librdkafka
/opt/homebrew/Cellar/librdkafka/1.8.2 (36 files, 4.9MB) *
  Poured from bottle on 2022-01-10 at 15:51:36
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/librdkafka.rb
License: BSD-2-Clause
==> Dependencies
Build: pkg-config ✔, python@3.10 ✘
Required: lz4 ✔, lzlib ✔, openssl@1.1 ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 5,239 (30 days), 27,376 (90 days), 101,064 (365 days)
install-on-request: 3,451 (30 days), 19,131 (90 days), 66,378 (365 days)
build-error: 0 (30 days)
```

confluent-kafka version: `1.8.2`

 - [x] Operating system: `macOS Monterey 12.0.1 Apple M1 Pro`

Can guide on how to install confluent-kafka-python on M1 chips?

**Comment by jliunyu** [comment]
Hi @pthalasta , can you please try according to https://github.com/confluentinc/confluent-kafka-python/issues/1025#issuecomment-980793318?

**Comment by pthalasta** [comment]
@jliunyu i tried based on that issue comment that you pointed me to. However, when i try to execute `make` i run into the following issue

```
Generating pkg-config file rdkafka++-static.pc
Checking librdkafka++ integrity
librdkafka++.1.dylib           OK
librdkafka++.a                 OK
Using ctags to generate TAGS
cmp: TAGS: No such file or directory
```

**Comment by jliunyu** [comment]
We are looking at the M1 support issue, lets close this one to track the status on https://github.com/confluentinc/confluent-kafka-python/issues/1190
