### ISSUE TITLE
can't install v1.8.2 via pip on python2.7

### ISSUE THREAD

**Issue by chriselion** [confluentinc/confluent-kafka-python#1262]
Description
===========
Running `pip install confluent-kafka==1.8.2` on python 2.7 results in an error during the installation process. This is due to py2-incompatible code in setup.py:
https://github.com/confluentinc/confluent-kafka-python/blob/2ac0d72b24b14e5246445ad9ce66ec9c8828ef4e/setup.py#L12-L13

How to reproduce
================
```
docker run --rm -it python:2.7-slim-buster bash
pip install confluent-kafka==1.8.2
```
This produces the output:
```
# pip install confluent-kafka==1.8.2
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting confluent-kafka==1.8.2
  Downloading confluent-kafka-1.8.2.tar.gz (104 kB)
     |████████████████████████████████| 104 kB 1.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-HN9px5/confluent-kafka/setup.py'"'"'; __file__='"'"'/tmp/pip-install-HN9px5/confluent-kafka/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-HN9px5/confluent-kafka/pip-egg-info
         cwd: /tmp/pip-install-HN9px5/confluent-kafka/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-HN9px5/confluent-kafka/setup.py", line 12, in <module>
        with open(os.path.join(work_dir, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Per the updated instructions for this release, I have also run `apt-get update && apt-get install -y librdkafka-dev python-dev` and the error is the same (as expected, but just for completeness).

Additional version information:
```
root@4e5a688daa1d:/# python --version
Python 2.7.18
root@4e5a688daa1d:/# pip --version
pip 20.0.2 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): `confluent-kafka==1.8.2` `librdkafka==0.11.6-1.1`
 - [ ] Apache Kafka broker version: - n/a
 - [ ] Client configuration: -n/a
 - [x] Operating system: `Debian GNU/Linux 10` (buster)
 - [ ] Provide client logs (with `'debug': '..'` as necessary) - n/a
 - [ ] Provide broker log excerpts - n/a
 - [ ] Critical issue - we have pinned the dependency, may affect others though.

**Comment by jliunyu** [comment]
Hi @chriselion, we recommend to use python 3 since python 2 is not maintained anymore.

**Comment by jliunyu** [comment]
Thanks for the suggestion, I added this to our backlog.

**Comment by edenhill** [comment]
There's another issue with that long_description; the README.md does not pass markdown validation which causes setup.py to fail.
This is because README.md contains language-selection for code blocks, which seems to be a GH markdown extension.

I think we should just back out the longdescription commit.

**Comment by chriselion** [comment]
If you do revert that (and/or add the `python_requires` setting) and make a patch release, could you also "[yank](https://pypi.org/help/#yanked)" the current package? This will prevent anyone from accidentally installing it (unless they have the version pinned).

**Comment by jliunyu** [comment]
> There's another issue with that long_description; the README.md does not pass markdown validation which causes setup.py to fail. This is because README.md contains language-selection for code blocks, which seems to be a GH markdown extension.
> 
> I think we should just back out the longdescription commit.

Thanks for your response @edenhill, this is the back out for longdescription commit: https://github.com/confluentinc/confluent-kafka-python/commit/d2667e9bce37fe8629b9629d68f0c2b66d4b570e#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
