### ISSUE TITLE
warning: "Please migrate your Python Protobuf producers and consumers to 'use.deprecated.format':True"

### ISSUE THREAD

**Issue by martinskeem** [confluentinc/confluent-kafka-python#1265]
This warning does not make much sense to me:

https://github.com/confluentinc/confluent-kafka-python/blob/d2667e9bce37fe8629b9629d68f0c2b66d4b570e/src/confluent_kafka/schema_registry/protobuf.py#L491-L493

- Should a warning really be emitted if `'use.deprecated.format': False`? I would have thought that the warning was emitted only if using the deprecated format.

- Should the warning state _"... migrate ... producers and consumers to 'use.deprecated.format':**True**"_? I would have thought that producers and consumers should migrate to the format which is _not_ deprecated

**Comment by edenhill** [comment]
Ugh, that's embarrassing. This is what happens with double negations..

**Comment by Derfirm** [comment]
Hello!
 Any update on this issue?
 Are you planning make release with this fix?
 Thx.

**Comment by jliunyu** [comment]
> Hello! Any update on this issue? Are you planning make release with this fix? Thx.

The fix is merged and will be released with v1.9.0.
