### ISSUE TITLE
Add type hints for exposed API

### ISSUE THREAD

**Issue by moritz89** [confluentinc/confluent-kafka-python#1268]
Description
===========
It would be very helpful if types were added to the library. As it currently exports the classes via cimpl, indirect documentation of the classes would still be possible by the methods described by [PyRight](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md).

How to reproduce
================
Import the library in a modern Python editor such as VS Code.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.8.2 - NA
 - [x] Apache Kafka broker version: NA
 - [x] Client configuration: NA
 - [x] Operating system: Ubuntu 20.04
 - [x] Provide client logs (with `'debug': '..'` as necessary): NA
 - [x] Provide broker log excerpts: NA
 - [x] Critical issue: No

**Comment by jliunyu** [comment]
Thanks for providing this useful suggestion to us. But since the type hints are supporting from python 3.5, it's not compatible with python version lower than 3.5, we still have a lot of customers using python version lower than 3.5, it's hard for us to import this feature for now. But we may consider this feature later.

**Comment by antonagestam** [comment]
@jliunyu Type hints are compatible with versions including and less than 3.5, even 2.7. You can either use stubs, defined separately from the implementation in .pyi files, or [comment-style type hints](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html).

As this is an open source project, I think it'd be helpful to know whether PRs introducing such type hints would be considered.

**Comment by MartinSoto** [comment]
Hi, it is 2024 and this is the only Python library I use that lacks proper typing support. Are you planning to do something about this?

**Comment by antonagestam** [comment]
For anyone looking for a stop-gap, or a basis to build a full typeshed addition from, you can do what we do in Karapace, and create stubs only for the APIs that your application interacts with: https://github.com/Aiven-Open/karapace/tree/main/stubs/confluent_kafka.

**Comment by pushpesh-cometchat** [comment]
PyCharm is somehow able to do it, but not VS Code
<img width="579" alt="image" src="https://github.com/user-attachments/assets/616c8e44-2a5c-4908-a4ac-cd292179e079">
