### ISSUE TITLE
How to close a Producer instance?

### ISSUE THREAD

**Issue by jadsonmonteiro** [confluentinc/confluent-kafka-python#127]
Hello guys!
Is there any way to disable (close an instance) of the Producer?

**Comment by edenhill** [comment]
The producer is automatically garbage collected when it goes out of scope / all references are gone.
But you probably want to call flush() explicitly to make sure all outstanding messages have been delivered before that.

**Comment by ewencp** [comment]
@jadsonmonteiro Closing this since @edenhill explained how to use the producer (see the `examples/` if you're still unsure). Please reopen if you have further related questions.
