### ISSUE TITLE
Implement fetchq_cnt per partition

### ISSUE THREAD

**Issue by jack-mcivor** [confluentinc/confluent-kafka-python#1276]
Currently the fetchq_cnt statistic seems to be duplicated across partitions. According to https://github.com/confluentinc/confluent-kafka-python/issues/144#issuecomment-286543600, this is because there is a single fetchq serviced by all partitions.

Would it be possible to report on fetchq_cnt for partitions separately? Or, should the current fetchq_cnt be a top level statistic?

**Comment by jack-mcivor** [comment]
Can this also be calculated per partition as next_offset - app_offset?

**Comment by edenhill** [comment]
All partition queues are forwarded to a single consumer queue (so the application can get messages from all partitions in one single poll call), and fetchq_cnt thus reflects that single shared consumer queue.

Using next_offset - app_offset does sound like a reasonable workaround.
