### ISSUE TITLE
What is the KafKaError Type if the broker can not be connected?

### ISSUE THREAD

**Issue by MarsSu0618** [confluentinc/confluent-kafka-python#1278]
Description
===========
I am trying to implement error handling mechanism on application produce message. Then, I want to catch related error and execute corresponding process when the broker can not be connected or produced message from producer application. But I do not sure it will return KafkaError or ProduceError based on reproduce code. And I also do not sure that could catch these error on `on_delivery function` based on my scenario, hope someone can answer, thank you.

How to reproduce
================
```python
import certifi
from confluent_kafka import SerializingProducer
from confluent_kafka.schema_registry.avro import AvroSerializer
from confluent_kafka import KafkaError, KafkaException

class MskSerializingProducer:
    def __init__(self):
        config = dict()
        config['bootstrap.servers'] = 'SSL://broker-server'
        config['security.protocol'] = 'SSL'
        config['ssl.ca.location'] = certifi.where()
        
        schema_config = {
            'url': 'schema-registry-endpoint',
            'basic.auth.user.info': 'username:password'
        }
        
        sr_client = SchemaRegistryClient(schema_config)
        
        self.avro_serializer = AvroSerializer(
            schema_registry_client=sr_client,
            schema_str='schema_str'
        )
        
        config['value.serializer'] = self.avro_serializer
        self.producer = SerializingProducer(config)

    def send_message(self, message):
        self.producer.poll(0)
        
        self.producer.produce(
            topic='topic_name',
            value=message,
            on_delivery=self.__delivery_func)

    def __delivery_func(self, err, msg):
        raise err
        
if __name__ == '__main__':
    ..........
    p = MskSerializingProducer()
    
    for msg in messages:
        try:
            p.send_message()
        except:   ## KafkaError or ProduceError?
            ## handling process
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 * confluent_kafka version: `('1.7.0', 17235968)`
 * confluent_kafka.libversion(): `('1.7.0', 17236223)`
 - [x] Apache Kafka broker version: `AWS MSK 2.8.0`
 - [x] Client configuration:
 ```
{
    'bootstrap.servers': 'SSL://broker-server',
    'security.protocol': 'SSL',
    'ssl.ca.location': certifi.where(),
    'value.serializer': AvroSerializer
}
```
 - [x] Operating system: `ubuntu 20.04`
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @MarsSu0618 , thanks for asking.

For your code
```
for msg in messages:
        try:
            p.send_message()
        except:   ## KafkaError or ProduceError?
            ## handling process
```
I don't think you need to handle a KafkaError or ProduceError here. 

For the message delivery : they will be handled at the on_delivery callback function, the error will be a KafkaError: https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_producer.py#L80, if you caught any error, you can execute corresponding process there, for example: https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_producer.py#L93. 

For a broker can not be connected, if you register an error_cb you will get an _ALL_BROKERS_DOWN error if all broker connections go down.

**Comment by MarsSu0618** [comment]
@jliunyu I know your meaning. Thanks for your reply.
