### ISSUE TITLE
License info for confluent-for-kubernetes

### ISSUE THREAD

**Issue by vjvel** [confluentinc/confluent-kafka-python#1289]
we have deploy 3 node kafka broker using the confluent-for-kubernetes helm chart,  Just want to confirm the license model for the confluent kafka in kubernetes, is it opensource or all component are enterprise ?

kindly clarify this license model for the confluent-for-kubernetes. 

we are using the below component
confluen-kafka - 3 broker node
confluent-ksqldb
confluent-schemaregistry
confluent-zookper.

Only confluent-cost-center its ask for enterprise license.   can we run 3 node broker in k8s as free license?

**Comment by jliunyu** [comment]
@vjvel, thanks for asking, let me conform with the team.

**Comment by jliunyu** [comment]
If you are using the confluent platform community edition and apache kafka, they are free.

In CP 5.2 we did "confluent enterprise free for ever" for a single broker. For 3 nodes, I think a paid enterprise license is needed.

This is the license related FAQ: https://www.confluent.io/confluent-community-license-faq/

For more license question, the sales department can give professional answers.
