### ISSUE TITLE
how to set config about both batch.size and message.max.bytes?

### ISSUE THREAD

**Issue by MarsSu0618** [confluentinc/confluent-kafka-python#1290]
Description
===========
how to set config about both batch.size and message.max.bytes?
When I setting these config value follow as:
```
batch.size = 1024*1024*2
message.max.bytes = 1024*1024*2
```

But always get this error message in produce message:
```
cimpl.KafkaException: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Broker: Message size too large"}
```

Because my message sometimes have 1-2 MB size, and I want to improve high throughput simultaneously. (20k message/s) 
Based on this [reference](https://www.cloudkarafka.com/blog/kafka-producer-side-settings-explained-linger-ms-and-batch-size.html), we can adjust `linger.ms` and `batch.size` to achieve high throughput. But still not work after modify config.
But always get this error, hope someone can help and answer, thank you.

How to reproduce
=========
```python
import certifi
from confluent_kafka import SerializingProducer
from confluent_kafka.schema_registry.avro import AvroSerializer
from confluent_kafka import KafkaError, KafkaException

class MskSerializingProducer:
    def __init__(self):
        config = dict()
        config['bootstrap.servers'] = 'SSL://broker-server'
        config['security.protocol'] = 'SSL'
        config['ssl.ca.location'] = certifi.where()
        config['batch.size'] = 1024 * 1024
        config['message.max.bytes'] = 1024 * 1024 * 2
        config['linger.ms'] = 5000
        config['sticky.partitioning.linger.ms'] = 10000
        config['error_cb'] = self.__error_callback_func
        
        schema_config = {
            'url': 'schema-registry-endpoint',
            'basic.auth.user.info': 'username:password'
        }
        
        sr_client = SchemaRegistryClient(schema_config)
        
        self.avro_serializer = AvroSerializer(
            schema_registry_client=sr_client,
            schema_str='schema_str'
        )
        
        config['value.serializer'] = self.avro_serializer
        self.producer = SerializingProducer(config)

    def send_message(self, message):
        self.producer.poll(0)
        
        self.producer.produce(
            topic='topic_name',
            value=message,
            on_delivery=self.__delivery_func)

    def __delivery_func(self, err, msg):
        ...
        
    def __error_callback_func(self, err):
        ... 
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 * confluent_kafka version: `('1.7.0', 17235968)`
 * confluent_kafka.libversion(): `('1.7.0', 17236223)`
 - [x] Apache Kafka broker version: `AWS MSK 2.8.0`
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by MarsSu0618** [comment]
@edenhill 
Could you help me to solve this problem? I have done many experiments and still do not work after modify `batch.size`.
I will appreciate that you answer this.

**Comment by MarsSu0618** [comment]
@edenhill , I have adjusted this config, but get the same error.
```
{
     'message.max.bytes': 3000000,
     'batch.size': 2000000
}
```

Error Message:
```
cimpl.KafkaException: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Broker: Message size too large"}
```

**Comment by edenhill** [comment]
Those are client configs, you also need to set the broker-side topic configuration as shown in my link.

Also make sure that you set both client and broker configs slightly above the actual message size you are planning to send to account for the protocol framing overhead.

**Comment by MarsSu0618** [comment]
@edenhill I have adjust `max.message.byte` in my kafka broker config.
But I still get the same error about `Message size too large`. Do you have any idea or need to other config? Thank you.
