### ISSUE TITLE
Oauth not supported in Admin client?

### ISSUE THREAD

**Issue by Ycallaer** [confluentinc/confluent-kafka-python#1296]
Description
===========
Hi all,
I have a kafka cluster that uses OAUTHBEARER as SASL mechanism. When I am trying to produce or consume messages I can properly configure the respective method, authentication happens and all is well.

However we are currently trying with the Admin Client and it does not seem to support the oauth_cb parameter. If I create an AdminClient object and call the method `admin.list_groups(timeout=10)` it fails with a timeout.

When running in debug mode you can see the following config

```
%7|1646817877.230|CONF|rdkafka#producer-2| [thrd:app]:   client.software.name = confluent-kafka-python
%7|1646817877.230|CONF|rdkafka#producer-2| [thrd:app]:   client.software.version = 1.7.0-rdkafka-1.7.0
%7|1646817877.230|CONF|rdkafka#producer-2| [thrd:app]:   metadata.broker.list = *****:9092
%7|1646817877.230|CONF|rdkafka#producer-2| [thrd:app]:   message.max.bytes = 50331648
%7|1646817877.230|CONF|rdkafka#producer-2| [thrd:app]:   debug = generic,broker,topic,metadata,feature,queue,msg,protocol,cgrp,security,fetch,interceptor,plugin,consumer,admin,eos,mock,assignor,conf,all
%7|1646817877.230|CONF|rdkafka#producer-2| [thrd:app]:   error_cb = 0x7fbb58683970
%7|1646817877.230|CONF|rdkafka#producer-2| [thrd:app]:   background_event_cb = 0x7fbb58689a80
%7|1646817877.231|CONF|rdkafka#producer-2| [thrd:app]:   opaque = 0x7fbb54750888
%7|1646817877.231|CONF|rdkafka#producer-2| [thrd:app]:   security.protocol = sasl_ssl
%7|1646817877.231|CONF|rdkafka#producer-2| [thrd:app]:   sasl.mechanisms = OAUTHBEARER
%7|1646817877.231|CONF|rdkafka#producer-2| [thrd:app]:   oauthbearer_token_refresh_cb = 0x7fbb58683680
%7|1646817877.231|CONF|rdkafka#producer-2| [thrd:app]:   queue.buffering.max.messages = 15000
%7|1646817877.231|CONF|rdkafka#producer-2| [thrd:app]:   queue.buffering.max.ms = 0
...
%7|1646817886.226|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646817886.230|CONNECT|rdkafka#producer-2| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646817887.226|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646817887.230|CONNECT|rdkafka#producer-2| [thrd:main]: Cluster connection already in progress: no cluster connection
...
cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Failed to list groups: Local: Timed out"}
```
If I print the JWT token in the method where I construct the OAUTH cb, it is printed in a consumer / producer but never in the admin client.

I also looked at the source code in Admin.c but found no reference to oauth_cb

How to reproduce
================
Construct a conf with oauth_cb as per the example and then use this conf with the admin client.
The function will fail

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version: Apache kafka 2.7.0
 - [x] Client configuration: 
```
 {'bootstrap.servers': self.config["bootstrap_servers"],
                'security.protocol': sasl_ssl,
                'sasl.mechanisms': OAUTHBEARER,
                'oauth_cb': functools.partial(self._get_token),
                'message.max.bytes': self.config["kafkaMaxMessageBytes"],
                'queue.buffering.max.ms': self.config["queue.buffering.max.ms"],
                'queue.buffering.max.messages': self.config["queue.buffering.max.messages"],
                "debug": "all",
  }
```
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
When using OAUTHBEARER you will need to call `admin.poll()` once after client creation (and before doing anything else) to make sure the OAUTHBEARER refresh callback is triggered.

**Comment by Ycallaer** [comment]
Thanks a lot @edenhill that fixed it 👍

**Comment by twcurrie** [comment]
This is a non-obvious aspect of the library.  Can this be surfaced up to the documentation somewhere appropriate?
