### ISSUE TITLE
Python consumer doesn't pick up messages from auto created topic

### ISSUE THREAD

**Issue by kinghuang** [confluentinc/confluent-kafka-python#130]
I can't seem to figure out how to get a Python Consumer to receive messages from a topic that's auto-created after it starts polling. If I start both a Python Consumer and a kafka-console-consumer for the same topic that doesn't exist yet, then use a Python Producer to produce a message to that topic, the kafka-console-consumer gets the message, but the Python Consumer never does. I have to start the Python Consumer after the topic exists to receive messages.

My consumer is basically the example High-level Consumer in the README.

```
consumer = Consumer({'bootstrap.servers': 'kafka:9092', 'group.id': 'pssync'})
consumer.subscribe(['pssync-transactions'])
running = True
while running:
    message = consumer.poll(timeout=30)
    if not message:
        continue
    elif not message.error():
        print(message.value())
    elif message.error().code() != KafkaError._PARTITION_EOF:
        print(message.error())
        running = False
```

The console-consumer is being run like this.

```
kafka-console-consumer --topic pssync-transactions --zookeeper zookeeper:2181
```

Is this a limitation of the confluent-kafka-python Consumer, or am I doing something wrong?

**Comment by edenhill** [comment]
I believe this is a known issue in librdkafka that has been fixed on master and the very soon to be released 0.9.4.

The workaround for the time being is to re-subscribe.

**Comment by kinghuang** [comment]
Thanks, I'll watch `librdkafka` for it!

**Comment by kinghuang** [comment]
I can confirm that it appears to be working correctly with librdkafka v0.9.4-RC1.

**Comment by edenhill** [comment]
Fantastic, thanks!

**Comment by ewencp** [comment]
@edenhill Close this issue unless the problem comes up again post-0.9.4?

**Comment by edenhill** [comment]
@ewencp Aye, I'm going to close when Py 0.9.4 is released.

**Comment by pvanderlinden** [comment]
@kinghuang How did you get this working? I tried with v0.9.4 of confluent kafka with 0.9.4 of librdkafka. The only way I could get new topics was by creating a new consumer, then subscribe again. It doesn't automaticly subscribe to new topics matching the regex (or string), and resubscribing also most of the time doesn't work.

**Comment by edenhill** [comment]
@pvanderlinden Can you reproduce this with `"debug": "cgrp,metadata"`?

**Comment by pvanderlinden** [comment]
Sorry about this, after digging a bit deeper I found out that the metadata refresh by default is 10 minutes, which means new topics get picked up slow (to slow for manual testing)
