### ISSUE TITLE
AvroSerializer generates invalid JSON when schema references are in an array

### ISSUE THREAD

**Issue by RickTalken** [confluentinc/confluent-kafka-python#1302]
Description
===========

In the Confluent blog post [Putting Several Event Types in the Same Topic – Revisited](https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/), the author describes how to use [use Avro unions with schema references](https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/#avro-unions-with-schema-references). The example shows a schema where the schema references are in an array. However, the `confluent_kafka.schema_registry.avro._schema_loads` function generates a `Schema` that contains a `schema_str` that is not valid JSON if the schema references are in an array. 

The exception occurs in `AvroSerializer` in the following line when the serializer is instantiated:
https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/schema_registry/avro.py#L193

Given this example from the blog post:
```
[
  "io.confluent.examples.avro.Customer",
  "io.confluent.examples.avro.Product",
  "io.confluent.examples.avro.Payment"
]
```
The `Schema` object returned by the `_schema_loads` function will contain a `schema_str` value of:
```
'{"type":"["io.confluent.examples.avro.Customer","io.confluent.examples.avro.Product","io.confluent.examples.avro.Payment"]"}'
```
There are two issues with the `schema_str` that was generated:
1. The double-quotes are around the brackets rather than the schema references.  The Python JSONDecoder will raise an exception because the `schema_str` is invalid JSON.
2. The JSON object is a now a dictionary with a "type" key instead of an array.

The `_schema_loads` function should generate a `schema_str` that looks like this instead:
```
'["io.confluent.examples.avro.Customer","io.confluent.examples.avro.Product","io.confluent.examples.avro.Payment"]'
```

This can be easily corrected to generate valid JSON and AVRO with schema references in an array.  The [`_schema_loads` function](https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/schema_registry/avro.py#L48) currently does this when generating the `schema_str`:
```python
if schema_str[0] != "{":
    schema_str = '{"type":"' + schema_str + '"}'
```
It should instead do the following to generate valid JSON:
```python
if schema_str[0] != "{" and schema_str[0] != "[":
        schema_str = '{"type":"' + schema_str + '"}'
```

Correcting this will not itself solve the problems with schema references in an array but at least the function generates valid JSON with this change. The solution literally gets you one step closer as the next line in the `AvroSerializer.__init__()` will get an exception from the fastavro library here:
https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/schema_registry/avro.py#L193

Unfortunately, the fastavro library isn't able to parse schemas with schema references in an array.  That's an issue that needs to be fixed in fastavro. However, an issue in fastavro should not prevent correcting the code in Confluent-Kafka Python client from generating valid JSON/AVRO.

Issues [974](https://github.com/confluentinc/confluent-kafka-python/issues/974) and [1202](https://github.com/confluentinc/confluent-kafka-python/issues/1202) are related in that they deal with schema references.  However, those issues describe issues where the schema reference is nested in an AVRO record.  This issue is with schema references in an array.

How to reproduce
================

```python
from confluent_kafka.schema_registry.avro import AvroSerializer
from confluent_kafka.schema_registry import (
    SchemaRegistryClient,
    Schema,
    SchemaReference,
)
from fastavro import parse_schema
import json

schema_registry_client = SchemaRegistryClient({"url": "http://localhost:8081"})


def register_schemas():
    customer_schema_str = """
    {
        "name": "Customer",
        "type": "record",
        "fields": [
            {"name": "name", "type": "string"}
        ]
    }
    """
    customer_schema = Schema(
        schema_str=customer_schema_str, schema_type="AVRO"
    )
    schema_registry_client.register_schema(
        subject_name="customer",
        schema=customer_schema
    )
    product_schema_str = """
    {
        "name": "Product",
        "type": "record",
        "fields": [
            {"name": "name", "type": "string"},
            {"name": "price", "type": "int"}
        ]
    }
    """
    product_schema = Schema(
        schema_str=product_schema_str, schema_type="AVRO"
    )
    schema_registry_client.register_schema(
        subject_name="product",
        schema=product_schema
    )
    union_schema_str = """
    [
        {
            "name": "Customer",
            "type": "Customer"
        },
        {
            "name": "Product",
            "type": "Product"
        }
    ]
    """
    references = [
        SchemaReference(name="Customer", subject="customer", version=1),
        SchemaReference(name="Product", subject="product", version=1),
    ]
    union_schema = Schema(
        schema_str=union_schema_str, schema_type="AVRO", references=references
    )
    schema_registry_client.register_schema(
        subject_name="union-value", schema=union_schema
    )


def deserialize():
    named_schemas = {}
    customer_schema = schema_registry_client.get_latest_version("customer")
    parse_schema(
        json.loads(customer_schema.schema.schema_str), named_schemas
    )
    product_schema = schema_registry_client.get_latest_version("product")
    parse_schema(
        json.loads(product_schema.schema.schema_str), named_schemas
    )
    union_schema = schema_registry_client.get_latest_version("union-value")
    union_parsed_schema = parse_schema(
        json.loads(union_schema.schema.schema_str), named_schemas
    )

    avro_serializer = AvroSerializer(
        schema_registry_client=schema_registry_client,
        schema_str=json.dumps(union_parsed_schema),
        conf={"auto.register.schemas": False, "use.latest.version": True},
    )


if __name__ == "__main__":
    register_schemas()
    deserialize()
```

If you run the above, you will get an error from the Python JSON package that reads (see description for the reason):
```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 12 (char 11)
```

Next, comment out the call to `register_schemas()` as you won't need to do that again.  Then, apply my suggested change to the `confluent_kafka.schema_registry.avro._schema_loads` function.  After my suggested change are applied, you will get this error instead:
```
fastavro._schema_common.UnknownType: Customer
```

As described in the issue description, this is due to an issue in fastavro. Confluent is now creating a valid JSON string but fastavro is currently unable to process the references correctly.  That is a separate issue that will need to be addressed by fastavro but at least confluent-kafka has done its part to generate correct JSON.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):  confluent-kafka-python = ('1.8.2', 17302016), librdkafka = ('1.8.2', 17302271)
 - [x] Apache Kafka broker version: 6.1.0
 - [ ] Client configuration: `{...}`
 - [x] Operating system: MacOS
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @RickTalken, thanks for asking, the Schema Registry's schema references is not supported yet, this is the PR for it, https://github.com/confluentinc/confluent-kafka-python/pull/1088

**Comment by mhowlett** [comment]
combining with #1303
