### ISSUE TITLE
Produce with NodeJS and consume with Python

### ISSUE THREAD

**Issue by lourivaldo** [confluentinc/confluent-kafka-python#1314]
Description
===========
Consume a protobuff message produced by nodejs `https://www.npmjs.com/package/@kafkajs/confluent-schema-registry` causes error 
```
confluent_kafka.error.ValueDeserializationError: KafkaError{code=_VALUE_DESERIALIZATION,val=-159,str="Error parsing message with type 'User'"}
```

I use values:

`Schema ID`: 1
`Message`:
name '1'
favoritecolor '1'

When produce this message with `confluent-kafka-python` receives on consumer:
`b'\x00\x00\x00\x00\x01\x00\n\x011\x12\x011'` # works as expected
When produce message with `@kafkajs/confluent-schema-registry` receives on consumer:
`b'\x00\x00\x00\x00\x01\n\x011\x12\x011'` # causes ValueDeserializationError

it is possible to notice that the missing part `x00`. 

however the opposite works:
Produce `confluent-kafka-python` -> Consume  `@kafkajs/confluent-schema-registry` : WORKS
Produce `@kafkajs/confluent-schema-registry` -> Consume `confluent-kafka-python`  : ERROR

I thought there would be compatibility between the messages in the two libraries.

How to reproduce
================
user.proto
```
syntax = "proto3";

message User {
  string name = 1;
  string favoritecolor = 2;
}
```

producer.mjs
```
import {Kafka} from 'kafkajs'
import {COMPATIBILITY, SchemaRegistry, SchemaType} from "@kafkajs/confluent-schema-registry";
import {readFileSync} from "fs";

const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['kafka:9092'],
})

const options = {
  [SchemaType.PROTOBUF]: {
    messageName: 'User',
  },
};
const registry = new SchemaRegistry(
  {
    host: 'http://schema-registry:8081/',
    clientId: 'kafka-nodejs'
  },
  options
)

const schema = readFileSync('user.proto').toString();
const {id} = await registry.register(
  {
    type: SchemaType.PROTOBUF,
    schema,
  },
  {
    compatibility: COMPATIBILITY.BACKWARD,
    subject: 'user',
  }
)

const user = await registry.encode(id, {
  name: '1',
  favoritecolor: '1',
})

const producer = kafka.producer({})
await producer.connect()
await producer.send({
  topic: 'test-topic',
  messages: [
    {
      key: 'user-1',
      value: user
    },
  ],
})

await producer.disconnect()
```

consumer.py
```
import logging
import user_pb2
from confluent_kafka import DeserializingConsumer
from confluent_kafka.schema_registry.protobuf import ProtobufDeserializer
from confluent_kafka.serialization import StringDeserializer

topic = 'test-topic'

protobuf_deserializer = ProtobufDeserializer(
    user_pb2.User,
    {
        'use.deprecated.format': False
    }
)
string_deserializer = StringDeserializer('utf_8')

consumer_conf = {
     'bootstrap.servers': 'kafka:9092',
     'key.deserializer': string_deserializer,
     'value.deserializer': protobuf_deserializer,
     'group.id': 'test-group-2',
     'auto.offset.reset': 'latest'
}


consumer = DeserializingConsumer(consumer_conf)
consumer.subscribe([topic])

while True:
    try:
        msg = consumer.poll(1.0)
        if msg is None:
            continue
        if msg.error():
            raise KafkaException(msg.error())
        else:
            user = msg.value()
            print(str(msg))
            print(user)
            if user is not None:
                print("User record {}:\n"
                      "\tname: {}\n"
                      "\tfavoriteColor: {}\n"
                      .format(msg.key(), user.name, user.favoritecolor))
    except KeyboardInterrupt:
        sys.stderr.write('%% Aborted by user\n')

consumer.close()
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.8.2', 17302016) and ('1.8.2', 17302271)
 - [x] Apache Kafka broker version: 2.4.1.1
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
We don't develop or support the KafkaJS client. If you observe an issue producing with the java client (which we support), and consuming with the python client, we'll take a look.

With that said, this change may be relevant: 
https://github.com/confluentinc/confluent-kafka-python/pull/1256/files
