### ISSUE TITLE
Fail to install confluent-kafka on macbookpro m1 max osx Monterey

### ISSUE THREAD

**Issue by pancudaniel7** [confluentinc/confluent-kafka-python#1315]
Description
===========
Fail to install the client using **pip** 

How to reproduce
================
Run pip install confluent-kafka

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version: 3.1.0
 - [ ] Client configuration: `{...}`
 - [x] Operating system: macOS Monterey, Darwin Pancus-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

 - [x] Provide client logs (with `'debug': '..'` as necessary)
<img width="1728" alt="Screenshot 2022-04-06 at 12 38 53" src="https://user-images.githubusercontent.com/9675142/161946743-1874e4c8-eb22-4cd4-9375-587093671b20.png">
<img width="1728" alt="Screenshot 2022-04-06 at 12 39 03" src="https://user-images.githubusercontent.com/9675142/161946756-78489cf5-35d8-4a71-8e45-c98463c326e5.png">
<img width="1728" alt="Screenshot 2022-04-06 at 12 39 11" src="https://user-images.githubusercontent.com/9675142/161946767-61e46cb8-bd4e-4114-bdec-12a1510fa68d.png">

 - [ ] Provide broker log exception
 - [ ] Critical issue

**Comment by pancudaniel7** [comment]
I've also tried to install librdkafka by using:
```sh
brew install librdkafka
```

**Comment by pancudaniel7** [comment]
I also tried the next steps for fixing **librdkafka/rdkafka.h** problem:
```sh
sudo mkdir /usr/local/include && \
sudo ln -s /opt/homebrew/Cellar/librdkafka/1.8.2/include/librdkafka /usr/local/include/librdkafka && \
export C_INCLUDE_PATH=/usr/local/include  && \
pip3 install confluent-kafka
```
and I got other errors:
<img width="1728" alt="Screenshot 2022-04-06 at 17 27 07" src="https://user-images.githubusercontent.com/9675142/161998068-26b42ac4-8bca-4998-aadc-7ad7a3bfc91d.png">
<img width="1728" alt="Screenshot 2022-04-06 at 17 27 23" src="https://user-images.githubusercontent.com/9675142/161998131-2d445824-f8a4-43bd-a09d-8617ae7c2646.png">
<img width="1728" alt="Screenshot 2022-04-06 at 17 27 36" src="https://user-images.githubusercontent.com/9675142/161998173-7ffb26ac-8ed7-4ad6-9075-deab5235ebc4.png">

**Comment by edenhill** [comment]
See this:
https://github.com/confluentinc/confluent-kafka-python/issues/1190#issuecomment-1017410984

**Comment by pancudaniel7** [comment]
Thank you @edenhill
