### ISSUE TITLE
Expose the rebalance protocol in use to the client

### ISSUE THREAD

**Issue by fpacifici** [confluentinc/confluent-kafka-python#1317]
Description
===========

librdkafka exposes the current rebalance protocol via `rd_kafka_rebalance_protocol`. It would be very useful to access this from the python client. Specifically the use case I have in mind is the migration of a large consumer group from the eager protocol to the incremental one. 
In this case we may specify both eager and cooperative-sticky during the migration so it would be useful for the consumer to know which mode it is in.
Is there a specific reason for not supporting it?

**Comment by edenhill** [comment]
We do not support mixing eager and cooperative assignment protocols at this time.

**Comment by mhowlett** [comment]
there's no explicit reason this isn't exposed, except to err on the side of smaller api surface area unless there's a good use case, but as magnus says, unfortunately migration from eager -> cooperative assignors isn't supported yet (was cut to reduce scope to get the feature out).
