### ISSUE TITLE
Question: Are you planning to support AWS IAM?

### ISSUE THREAD

**Issue by Gatsby-Lee** [confluentinc/confluent-kafka-python#1320]
Hi,

This is not really an issue related.
I'd like to ask if this project is planning to support AWS IAM Auth?

Thank you

**Comment by mhowlett** [comment]
https://github.com/edenhill/librdkafka/issues/3402#issuecomment-861587315

**Comment by Gatsby-Lee** [comment]
@mhowlett Thank you

**Comment by Gatsby-Lee** [comment]
@mhowlett 
hi, I have a following question for your comment.
Does this mean that "confluent-kafka-python" can't support AWS IAM until librdkafka support it?

**Comment by Gatsby-Lee** [comment]
@mhowlett 
Can you tell me how I can use the forked version of librdkafka that supports AWS IAM with confluent-kafka-python?
( https://github.com/UrbanCompass/librdkafka )

**Comment by edenhill** [comment]
@Gatsby-Lee 
AWS IAM is a non-standard proprietary authentication scheme that is not part of Apache Kafka and thus not supported by Apache Kafka clients.
You will need to contact your provider for support.

**Comment by Gatsby-Lee** [comment]
@edenhill 
Thank you for your response.
