### ISSUE TITLE
 java consumer.wakeup function alternative for python?

### ISSUE THREAD

**Issue by puneet336** [confluentinc/confluent-kafka-python#1321]
Hi,
I am trying to convert a (kafka) java codebase to python. In java we handle the SIGINT and execute consumer.wakeup() to make the kafka consumer wakeup from the poll function.

I plan to use signal module , but i am unable to find pythonic alternative for wakeup function to interrupt consumer ( during poll function).

Could you please advice on a suitable method to interrupt poll method in python?
confluent_kafka version=1.8.2
python version = 3.8.10.
OS: linux mint 20.1

**Comment by edenhill** [comment]
librdkafka (the underlying Kafka client) has an `rd_kafka_queue_yield()` that could be used to wake up the consumer poll, but it is not (yet) exposed in the Python client.
Until it is the recommendation is to use a lower poll timeout, e.g., 100 ms or whatever makes sense for your application.
There's very little overhead in call poll().
