### ISSUE TITLE
Unable to install confluent-kafka in  Ubuntu 20.04 

### ISSUE THREAD

**Issue by parth5795** [confluentinc/confluent-kafka-python#1324]
Description
===========

Hello everyone,
When I try to run the following command: 'poetry run pip install --no-binary :all: confluent-kafka~=1.7.0'
It produces "Setup.py deprecated".
I have seen many similar issues in this repo but none of the solution seems to work.
I am getting follwoing error messge:

Collecting confluent-kafka~=1.7.0
  Using cached confluent-kafka-1.7.0.tar.gz (103 kB)
  Preparing metadata (setup.py) ... done
Skipping wheel build for confluent-kafka, due to binaries being disabled for it.
Installing collected packages: confluent-kafka
  Running setup.py install for confluent-kafka ... error
  error: subprocess-exited-with-error

  × Running setup.py install for confluent-kafka did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running install
      /home/parth/.cache/pypoetry/virtualenvs/consumer-example-uFbFFTxg-py3.9/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'confluent_kafka.cimpl' extension
      In file included from /tmp/pip-install-8lyjl6of/confluent-kafka_2a4a0033311546ab9d0545755d28c83f/src/confluent_kafka/src/Admin.c:17:
      /tmp/pip-install-8lyjl6of/confluent-kafka_2a4a0033311546ab9d0545755d28c83f/src/confluent_kafka/src/confluent_kafka.h:18:10: fatal error: Python.h: No such file or directory
         18 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> confluent-kafka

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/home/parth/.cache/pypoetry/virtualenvs/consumer-example-uFbFFTxg-py3.9/bin/python -m pip install --upgrade pip' command.

How to reproduce
================
poetry run pip install --no-binary :all: confluent-kafka~=1.7.0  (if poetry is installed)
pip install --no-binary :all: confluent-kafka~=1.7.0

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): Python 3.9.5 , confluent-kafka 1.7.0 , librdkafka (1.2.1-1ubuntu1)
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Windows Subsystem of Linux (Ubuntu 20.04 , Windows 10)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to install the Python development packages; e.g., `sudo apt install python3-dev`

**Comment by parth5795** [comment]
> You need to install the Python development packages; e.g., `sudo apt install python3-dev`

The same error is persisting even after the installation of python development pacakges.

**Comment by edenhill** [comment]
Please paste build output after installing python3-dev.

**Comment by parth5795** [comment]
Same error as earlier. 

Collecting confluent-kafka~=1.7.0
Using cached confluent-kafka-1.7.0.tar.gz (103 kB)
Preparing metadata (setup.py) ... done
Skipping wheel build for confluent-kafka, due to binaries being disabled for it.
Installing collected packages: confluent-kafka
Running setup.py install for confluent-kafka ... error
error: subprocess-exited-with-error

× Running setup.py install for confluent-kafka did not run successfully.
│ exit code: 1
╰─> [13 lines of output]
running install
/home/parth/.cache/pypoetry/virtualenvs/consumer-example-uFbFFTxg-py3.9/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
running build
running build_py
running build_ext
building 'confluent_kafka.cimpl' extension
In file included from /tmp/pip-install-8lyjl6of/confluent-kafka_2a4a0033311546ab9d0545755d28c83f/src/confluent_kafka/src/Admin.c:17:
/tmp/pip-install-8lyjl6of/confluent-kafka_2a4a0033311546ab9d0545755d28c83f/src/confluent_kafka/src/confluent_kafka.h:18:10: fatal error: Python.h: No such file or directory
18 | #include <Python.h>
| ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> confluent-kafka

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/home/parth/.cache/pypoetry/virtualenvs/consumer-example-uFbFFTxg-py3.9/bin/python -m pip install --upgrade pip' command.

> Please paste build output after installing python3-dev.

**Comment by edenhill** [comment]
Make sure that you intsall the Python 3.9 python3-dev package.

**Comment by klement97** [comment]
For Python version 3.10 refer to this answer: https://stackoverflow.com/a/72515120/9309611

**Comment by TyronMYoung11** [comment]
what about python 3.12?
