### ISSUE TITLE
copy config form parameter

### ISSUE THREAD

**Issue by PzaThief** [confluentinc/confluent-kafka-python#1332]
In case of using config form parameter, function uses copy and get value using pop() like [this](https://github.com/confluentinc/confluent-kafka-python/blob/d9a91a3d74c6447d53ba1c5733b0f99c2db2e259/src/confluent_kafka/schema_registry/schema_registry_client.py#L66)
I understood why function avoids to mutation original reference dictionary, but I don't know why don't use get() for get value and saving memory. If there are any race condition or any other issue, please let me know.

**Comment by mhowlett** [comment]
there may be an optimization to be made here, but any improvement seems like it would be pretty insignificant compared to everything else that is likely going on.
