### ISSUE TITLE
Under what conditions does Consumer.poll() return None?

### ISSUE THREAD

**Issue by aaronhays** [confluentinc/confluent-kafka-python#134]
The documentation for `Consumer.poll()` now indicates that `None` is a valid return value (I believe this  was changed at some point, see #18). I had been following the suggestion in #18 to just retry the `poll()` call if `None` was returned, but recently ran into a situation where that caused one of my applications to hang (I can't reproduce this, the kafka cluster was quite unhealthy when this happened). I would now like to be able to detect when the `None` return is signaling a transient system state that we expect to resolve itself and when it is an expected return.

It seems like once I get a `_PARTITION_EOF`, I will just get `None` after that until more data comes in. Is that correct? What are the other situations where I should expect `None` and which of them indicate some kind of bad system state that should resolve itself relatively quickly, and which are more "normal" conditions?

Thanks,
Aaron

**Comment by edenhill** [comment]
Are you using Consumer.poll() without a timeout?
What librdkafka version? (`confluent_kafka.libversion()`)

librdkafka &lt;v0.9.3 would return from `*poll()` prematurely if a callback was triggered.

**Comment by aaronhays** [comment]
I'm using librdkafka 0.9.1 and I see this behavior with a timeout set.

**Comment by edenhill** [comment]
It is most likely the issue mentioned with librdkafka &lt;0.9.3

**Comment by edenhill** [comment]
Most likely fixed in 0.9.4., please try it out and reopen if re seen
