### ISSUE TITLE
how do i use a custom partitioner and partitioner_cb

### ISSUE THREAD

**Issue by sanforever15** [confluentinc/confluent-kafka-python#1342]
Description
===========
I'm new to Kafka
how do i use a custom partitioner and partitioner_cb
there seems to be no docs or api for this

> config['partitioner'] = 'consistent'
config['partitioner_cb'] = self.__on_partitioner

i get this 

`cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Property "partitioner_cb" must be set through dedicated .._set_..() function"}`

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.8.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{'bootstrap.servers': server,'client.id': 'mytop',}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Custom partitioners are currently not supported.

And even if they were we would still recommend using one of the built-in partitioners, preferably `murmur2_random` (java compatible) for best compatibility.

**Comment by sanforever15** [comment]
> Custom partitioners are currently not supported.
> 
> And even if they were we would still recommend using one of the built-in partitioners, preferably `murmur2_random` (java compatible) for best compatibility.

ok
Thank you for replying so quickly
