### ISSUE TITLE
Option for disabling SSL certificate verification

### ISSUE THREAD

**Issue by aszac** [confluentinc/confluent-kafka-python#1346]
Description
===========
Is there an option that is an equivalent to edenhill/librdkafka enable.ssl.certificate.verification in order to disable the broker verification?

**Comment by edenhill** [comment]
You can simply set that configuration property in your consumer/producer config dict, e.g.:
```python
p = Producer({"bootstrap.servers": "..", "enable.ssl.certificate.verification": False})
```
