### ISSUE TITLE
Consumer: pause(partitions) and rebalancing

### ISSUE THREAD

**Issue by almaz1213** [confluentinc/confluent-kafka-python#1348]
Does Consumer.pause(partitions) cause other group members will poll messages? Will group rebalance be there? 

Thanks in advance

**Comment by mhowlett** [comment]
pausing causes the consumer to stop fetching messages for the specified partitions (and calls to poll will never return messages for these partiitons).

it is independent of the behavior of consumer groups - paused partitions will remain assigned to the consumer, and may or may not be moved on a group rebalance. paused state does not move between consumer instances - partitions on one consumer instance that are moved to another during a rebalance will not stay paused.

**Comment by mopitzdelica** [comment]
is there a simple way to pause and resume for all partitions? I am currently struggling with my healthcheck, as it appears to collide with the actual polling of the consumer, therefore I'd like to stop the polling before performing the healthcheck
