### ISSUE TITLE
Ho to Connect to kafka from python using truststore file ?

### ISSUE THREAD

**Issue by anvaari** [confluentinc/confluent-kafka-python#1350]
Description
===========
I have `properties.config` file and `kafka.client.truststore.jsk` and I can easily get data from kafka with `kafka-console-consumer` in console using : 
```bash 
kafka-console-consumer --topic test-topic --group group-id --bootstrap-server server:port --consumer.config config.properties
```
In config.properties file I have :
```txt
sasl_mechanism='PLAIN',
security_protocol='SASL_SSL',
sasl_jaas_config='''org.apache.kafka.common.security.plain.PlainLoginModule required \
username="sasl_username" \
password="sasl_password";'''
ssl_truststore_location='kafka.client.truststore.jks'
ssl_truststore_password='truststore_password'
```
But I want receive and process these data in python. So using `keytool` I convert jsk file to `CARoot.pem` and `certificate.pem` and use them in python-confluent-kafka :
```python
consumer_config = {
            'bootstrap.servers': server:port,
            'group.id': group_id,
            'auto.offset.reset': 'earliest',
            'enable.auto.commit': 'false',
            'max.poll.interval.ms': '86400000',
            'sasl.mechanism': 'PLAIN',
            'security.protocol': 'SASL_SSL',
            'ssl.ca.location':'CARoot.pem',
            'ssl.certificate.location':'certificate.pem',
            'sasl.username': 'sasl_username',
            'sasl.password': 'sasl_password'
        }
consumer = Consumer(consumer_config)
consumer.subscribe([test-topic])
```

But what i see in the console is : 
```log
%3|1653299842.609|FAIL|rdkafka#consumer-12| [thrd:sasl_ssl://server:port/bootstrap]: sasl_ssl://server:port/bootstrap: SASL authentication error: Authentication failed: Invalid username or password (after 179ms in state AUTH_REQ)
```
I expect to see data in output same as `kafka-console-consumer`.

I try pykafka and python-kafka too. But There is no difference. 

Note : I convert jsk to pem using [this](https://dev.to/adityakanekar/connecting-to-kafka-cluster-using-ssl-with-python-k2e) tutorial.

How to reproduce
================
You should have truststore.jks and enable sasl username and passwork. Now you can connect to kafka using command line but can't connect with [confluent-kafka-python](https://github.com/confluentinc/confluent-kafka-python)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):  ('1.8.2', 17302016) - ('1.8.2', 17302271) 
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: ubuntu 22.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Since SASL authentication takes places after the SSL/TLS connection has been set up we can conclude that your SSL configuration is fine, and that it is your SASL credentials that are the problem.

**Comment by anvaari** [comment]
@edenhill  You are right but username and password are same in code and `config.properties`. Can be relate to encoding of password? because there is some special character  in password. something like `\`, `%` and `,`.

**Comment by anvaari** [comment]
Thanks a lot. The problem was my password. password contains `\` when I remove that, It worked! But weird thing is password in my `config.properties`  file contains `\` and worked fine.
