### ISSUE TITLE
ValueError when serializing Protobuf Message 

### ISSUE THREAD

**Issue by MathisFasolo1** [confluentinc/confluent-kafka-python#1360]
Description
===========

Get ValueError when serializing Protobuf Message and send it in Kafka 

`ValueError: MessageDescriptor not found in file`

Localized in: _confluent-kakfa/schema_registry/protobuf.py_
```python
# find root's position in protofile
    for idx, msg_type_name in enumerate(msg_desc.file.message_types_by_name):
        if msg_type_name == current.name:
            msg_idx.appendleft(idx)
            found = True
            break
    if not found:
        raise ValueError("MessageDescriptor not found in file")
```
`if msg_type_name == current.name: `
Comparing _google._upb_message.Descriptor_ object with str name object. Possible fix:
`if msg_type_name.name == current.name: `

How to reproduce
================

1. Define Protobuf message and compile it into python object

```
syntax = "proto3";
message Message {
    string a = 1;
    string b = 2;
}
```

2. create Protobuf Serializer:

```
schema_registry_client = SchemaRegistryClient(schema_registry_conf)
    protobuf_serializer = ProtobufSerializer(
        Proto.Message,
        schema_registry_client,
        {'use.deprecated.format': True}
    )
    producer_conf = {
        'bootstrap.servers': kafka_host,
        'key.serializer': StringSerializer('utf_8'),
        'value.serializer': protobuf_serializer
    }
```

3. Run serialization

Error on Message.DESCRIPTOR.file.message_types_by_name: `ValueError: MessageDescriptor not found in file`

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka==1.8.2
 - [ ] Apache Kafka broker version: Docker Latest
 - [ ] Client configuration: `{
        'bootstrap.servers': kafka_host,
        'key.serializer': StringSerializer('utf_8'),
        'value.serializer': ProtobufSerializer(
            Proto.Message,
            schema_registry_client,
            {'use.deprecated.format': True}
    )
    }`
 - [ ] Operating system: Mac Docker Confluent Kafka Image
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by krasoffka** [comment]
Try to use python3.10 version

**Comment by MathisFasolo1** [comment]
I ran `pip install --upgrade google-api-python-client`
Thank you for your help everything is working now
