### ISSUE TITLE
NewTopic config not working

### ISSUE THREAD

**Issue by bradley-erickson** [confluentinc/confluent-kafka-python#1363]
Description
===========
When trying to create a new topic with a specific config, the config is not included when the topic is created.

How to reproduce
================
1. Create a new topic
```python

# create new compact topic
new_topic = NewTopic(
    'compact_topic5',
    1,
    1,
    config={
        'cleanup.policy': 'compact'
    }
)
topics_to_add = [new_topic]
admin_client.create_topics(topics_to_add)
```
2. Check Confluent Control center. 
![image](https://user-images.githubusercontent.com/26288699/172201464-8032237f-0079-4d29-9c7c-bb9eaf00d6a5.png)

Checklist
=========
Please provide the following information:

 - [x] Python version: 3.9.12
 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
    - Version: 1.8.2
    - Lib version: 1.8.2
 - [x] Apache Kafka broker version:
    - Control center version: 7.1.0 (using the standard Docker image)
    - Unsure of specific Broker version
 - [ ] Client configuration: `{...}`
 - [x] Operating system: macOS Monterey 12.4
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jonchiu** [comment]
@bradley-erickson If you log the exception like [here](https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/adminapi.py#L48), you'll get an error:

```
Failed to create topic compact_topic5: KafkaError{code=POLICY_VIOLATION,val=44,str="Topic replication factor must be 3"}
```

Confluent Cloud enforces a replication factor of 3: https://docs.confluent.io/cloud/current/clusters/broker-config.html#cloud-topic-config
