### ISSUE TITLE
stats_cb never called when time.sleep is used

### ISSUE THREAD

**Issue by jbfuzier** [confluentinc/confluent-kafka-python#138]
Hi,

I am seeing a behavior that I can't explain. I have a main loop which poll messages from the queue, those messages are then handled in this loop. 
However I need some rate limiting, basically I set a number of message to handle each seconds, once I reach this amont of messages, I check the time taken; if it is <1s, I sleep the remaining time; otherwise (=under target rate) I do nothing.

That looks like that :
```
target_events_per_sec = 100
tstart = time.time()
while True:
    msg = c.poll(timeout=5.0)
    handle_msg(msg)
    handled_msg += 1
    if handled_msg == target_events_per_sec:
        delta = time.time() - tstart
        if delta < 1:
            time.sleep(1 - delta)
        handled_msg = 0
        tstart = time.time()
```

What I noticed is that as long as I put a time.sleep within the loop, stats_cb is no longer called.
When I call the close function on the Consumer, all missed callbacks are proccessed at once.
 
Version : ('0.9.2', 590080)

**Comment by edenhill** [comment]
So you mean that following the time.sleep() and when the loop gets back to c.poll(), it won't raise the expected callbacks?
Only later when you exit the loop, no matter how many c.poll() calls you did (well, > 1 or 2), the callbacks are raised from c.close()?

**Comment by jbfuzier** [comment]
Yes that is exactly what I mean.

I tested with more than 10 c.poll() after the time the callback was supposed to be called (set it to every 10secs) and nothing. 

Example : 
```
       # with callback set to 10s, queue has 10000 events
        i = 0
        while True:
            msg = self.c.poll(timeout=5.0)
            time.sleep(1)
            i+=1
            if i == 100:
                print "Exiting"
                self.c.close()
                exit()
            continue
```
On the output you get nothing during 100s then Exiting is printed and then you get the 10 callbacks.

I noticed that when the queue is empty, callbacks are trigered as expected every 10sec.

**Comment by jbfuzier** [comment]
Going through the code I don't understand how stats_cb is called. When the timer in librdkafka triggers, it puts stats in rk_rep. rk_rep is served through rd_kafka_poll which is only called in the Producer binding code. It must be accessed from somewhere else as it works when queue is empty, but I can't find it :(

**Comment by jbfuzier** [comment]
Think I got it, rk_rep is redirected to rkcg_q so my understanding is that as stats events are in the same key as messages from Kafka, when the consumer is lagging behind (which is the case when doing rate limiting), stats callback are delayed until messages that are before on the key are processed.
Am I right ? If so would it be possible to put stats operation on top of the consumer key instead of putting it at the end ?

**Comment by edenhill** [comment]
Great investigation and analysis!

I think you are absolutely correct, since librdkafka pre-fetches messages there might be a horde of messages in-queue in front of any unrelated callbacks, such as stats.


Prioritizing non-consumer-specific callbacks sounds like a good idea, this will need to be done in librdkafka - I'll look into it.

Generally librdkafka has assumed that the application will keep up with the rate of incoming messages, which might not be a fair assumption looking at what speeds Kafka can push, especially when integrating through a slower high-level language like Python.

One similar problem that comes to mind is the same scenario for rebalance callbacks (on_assign, on_revoke) which we really want in-line with the messages, but they are not much good if delivered much later.

I will need to spend some time coming up with the best solution for this issue, but in the meantime you can remedy this problem by decreasing `queued.min.messages` to a value that corresponds to perhaps one second of your typical message rate.

**Comment by jbfuzier** [comment]
Thanks,

I think that it is precisely when things start to go wrong (ex : consumer not keeping up) that you need metrics to understand what is going on.

Changing `queued.min.messages` does not changes anything in my testing. On the bright side, as metrics are generated by librdkafka they are not "lost" (they are still generated at the timer frequency) but just delayed in their delivery to the python callback.

**Comment by edenhill** [comment]
What is your typical message size and what did you set queued.min.messages to?

**Comment by jbfuzier** [comment]
200Bytes messages, `'queued.min.messages': 10, 'statistics.interval.ms': 1000,`

**Comment by edenhill** [comment]
queued.min.messages is still limited (or maybe unlimited) to the message set size returned by the broker (originally batched by the producer). What this means in practice is that even if you have queued.min.messages=10 and 200 byte messages, a fetched message set may contain thousands of such messages and all of them will be enqueued.
If your per-message processing is long even a small queue like that may stall stats callbacks, et.al.

**Comment by jbfuzier** [comment]
I added 
```
if(rko->rko_type == RD_KAFKA_OP_STATS){
        printf("\r\nqueue %s len=%i size=%i", rkq->rkq_name, rkq->rkq_qlen, rkq->rkq_qsize);
}
```
in `src/rdkafka_queue.h : rd_kafka_q_enq` on line [279]( https://github.com/edenhill/librdkafka/blob/7a3987b105b17594135600e97f59d9d0deb3b6a2/src/rdkafka_queue.h#L279)

That seems to confirm that the queue grows further than `queued.min.messages` : 
`queue rd_kafka_cgrp_new len=19319 size=3651102`

Once queue length reaches 0, callbacks are honored.

**Comment by edenhill** [comment]
:+1: on digging that deep :)

Prioritizing these callbacks seems like the right thing to do

**Comment by edenhill** [comment]
This is now fixed on librdkafka master.
Only offset commit_cb's are currently up-prioritized but more callbacks (that are not subject to strict message-interleaved ordering) will be added going forward

**Comment by edenhill** [comment]
If you have the chance it would be great if you could verify the fix by installing librdkafka from master

**Comment by jbfuzier** [comment]
Thanks,

Shouldn't there be a call to `rd_kafka_op_set_prio` to prioritize stats around [here](https://github.com/edenhill/librdkafka/blob/15ecde1b263b32a3b61c688298621a604b0636fc/src/rdkafka.c#L1084) ?

**Comment by edenhill** [comment]
Sorry, mixed up the issues, the previous commit focused on commit_cb.

But you are absolutely right, stats should be fixed as well.
I was meaning to go over all ops to see what makes ense.

**Comment by edenhill** [comment]
@jbfuzier Stats (et.al) are fixed on librdkafka master now.

**Comment by jbfuzier** [comment]
Thanks, it is working flawlessly :+1:

**Comment by edenhill** [comment]
Great!
Big thanks for verifying
