### ISSUE TITLE
How to verify compress type of the message on consumer

### ISSUE THREAD

**Issue by wangchaoforever** [confluentinc/confluent-kafka-python#1380]
Description
===========
How to verify compress type of the message on consumer？

How to reproduce
================
I have too many topics(maybe 2000). I want to verify compress type of all topic.
I know kafka self's command kafka-dump-log.sh can show the compress type of message. But it must to login the kafka server and execute the command with the log file name.
I think this way is too slow.Does confluent-kafka-python support it?

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version(1.7.0)` and `confluent_kafka.libversion(1.7.0)`):
 - [x] Apache Kafka broker version: 2.7.0
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
i think (not 100% sure) if you enable debug logging (set debug config to all), this will be visible in the logs. at the very least you'll be able to infer it from the messageset sizes. there isn't an api call that allows you to determine this.
