### ISSUE TITLE
Documentation: default value for isolation.level should be updated to read_committed

### ISSUE THREAD

**Issue by AlexLitvino** [confluentinc/confluent-kafka-python#1399]
Description
===========
Section for [isolation.level](https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_isolation.level) states that default value isolation.level should be read_uncommitted.
But in [kafka-client-configuration](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#kafka-client-configuration) section of confluent-kafka-python it is stated refer to [librdkafka’s documentation](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) that specifies default value for isolation.level read_committed.

Section [isolation.level](https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_isolation.level) should be updated with default value read_committed.

How to reproduce
================
- Publish 'Message_not_in_transaction' message using non-transactional Producer.
- Publish messages 'Message1', 'Message2' using transactional Producer but NOT commit transaction.
- Consume messages from topic using Consumer not specifying isolation.level parameter.
- Observe that [b'Message_not_in_transaction'] message is consumed.
- Commit transaction.
- Consume messages from topic using Consumer not specifying isolation.level parameter.
- Observe that [b'Message1', b'Message2'] messages are consumed.

It proves that Consumer with default isolation.level reads messages published in transaction only after transaction is committed, that means default value for isolation.level is read_committed.

**Comment by mhowlett** [comment]
the confluent docs you point to refer to the java client, where it does indeed appear to be the case that the default value is `read_uncommitted` (which is surprising to me). in librdkafka, the default is `read_committed`.
