### ISSUE TITLE
When is a branch considered "released"?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#141]
I see that I can choose my branch ("master", "0.9.4", etc.) on the main code page and click "Clone or download" and select "Download ZIP" to get a snapshot. I also see that 0.9.4 is the newest numbered branch here, and if I'm reading this correctly, the latest commit to it was almost two weeks ago, while "master" changes every day. Does that mean that 0.9.4 is frozen, and will not change? Is there any visible status that reflects that a branch is finished/released/frozen and ready for users to take and use with some expectation of stability beyond what we might expect in a development or beta branch?

This same question applies to librdkafka as well.

**Comment by ewencp** [comment]
@johnrgregg3 We tag releases, so the relevant place to look for the official releases is the tags tab of the same dropdown. 0.9.4 is heading for release, but not quite there yet. But really the official release is when it shows up on PyPI.

librdkafka works the same way. For binaries, when we release the next version of Confluent we'll include packages for them (debs, rpms), the source code tgz downloads, and update the Homebrew package.

**Comment by johnrgregg3** [comment]
OK, I get PyPI - I see 0.9.2 up there. When confluent-kafka shows up there, it is fully baked. But I don't understand what you said about librdkafka. It won't show up in PyPI, since it is not python. Where should I look for the latest fully released version of librdkafka? I'm afraid I don't know what the Homebrew package is.

**Comment by ewencp** [comment]
@johnrgregg3 For librdkafka you can tell in a number of ways:

1) It will also get a tag, see https://github.com/edenhill/librdkafka/tree/v0.9.3 for example
2) It will be released with Confluent, so the [download page](https://www.confluent.io/download/) will be updated.
3) Github automatically generates source archives for tags, so you'll see an update [here](https://github.com/edenhill/librdkafka/releases)

The exact timing for all the clients may not quite line up, but they should all be released within a day or two of each other. In this case, librdkafka has actually been tagged already but the binary builds (i.e. the next Confluent version) isn't out quite yet.

**Comment by johnrgregg3** [comment]
Thanks! It looks like getting a tag is a necessary but not sufficient condition. For example, confluent-kafka has a 0.9.4 tag, but as you say, is not fully released yet. To know if it is really done, I should look at the "releases" page for any given project, and in addition for confluent-kafka, look for it on PyPI.

I couldn't make sense of the Confluent download page. I could not find any listing of confluent-kafka releases.

**Comment by edenhill** [comment]
For librdkafka the formal releases are what's on https://github.com/edenhill/librdkafka/releases
