### ISSUE TITLE
Does kafka-python support consumer rebalancing automatically?

### ISSUE THREAD

**Issue by alinaabramova** [confluentinc/confluent-kafka-python#143]
I create two consumers with the same group and assign to the same topic with 3 partitions. And each message from topic was received twice, by each consumer.

```

def consume(consumers, expected):
    received = []
    running = True
    while running:
        for c in consumers:
            if len(received) == expected:
                running = False
                break
            msg = c.poll(1)
            if not msg.error():
                print('Received message: %s' % msg.value().decode('utf-8'))
                received.append(msg.value().decode('utf-8'))
            elif msg.error().code() != KafkaError._PARTITION_EOF:
                print(msg.error())
                running = False
    return received

   consumer_config = {'bootstrap.servers': '127.0.0.1:9092', 'group.id': 'test_group', 'session.timeout.ms':    1000, "enable.auto.commit": "true",  'default.topic.config': { 'auto.offset.reset': 'earliest'}}

    c1 = Consumer(consumer_config)
    c2 = Consumer(consumer_config)
    c1.assign(list(map(lambda p: TopicPartition("test_topic", p), range(0,3))))
    c2.assign(list(map(lambda p: TopicPartition("test_topic", p), range(0,3))))
    received = consume([c1, c2], len(messages))
    print received
```

Messages in topic -  ['topic1v0', 'topic1v1', 'topic1v2']
received messages  - ['topic1v0', 'topic1v0', 'topic1v1', 'topic1v1', 'topic1v2', 'topic1v2']

Is this behavior expected?

kafka-python from 0.9.4 branch
librdkafka 0.9.1
kafka 0.9.0

**Comment by edenhill** [comment]
Consumers will only join the consumer group and get its partition assignment when you use subscribe().

assign() directly specifies the exact topic+partitions to consume and does not correlate that with any other consumers.

So my suggestion is to change cN.assign() to  cN.assign(['test_topic'])
