### ISSUE TITLE
Kafka ProtobufDeserializer with python

### ISSUE THREAD

**Issue by imadmoussa1** [confluentinc/confluent-kafka-python#1430]
Description
===========
It's there a way to Deserializer the protobuf kafka message without specifying  the ProtoMessageType ?
I am using this example https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/protobuf_consumer.py and looking for way to make the Deserialization more general without specifying the class  as in in example:
```
protobuf_deserializer = ProtobufDeserializer(user_pb2.User, {'use.deprecated.format': False})
```
So can I send different message type and Deserialize them without creating different instance. (Maybe by sending it in the key)
```
protobuf_deserializer = ProtobufDeserializer(msg.key(), {'use.deprecated.format': False})
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.9.2 and 1.9.2
 - [x] Apache Kafka broker version: 7.1.1
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: windows
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by mhowlett** [comment]
not with our serializers (yet).
you might consider using a union type to manage different types in the one topic.
