### ISSUE TITLE
How to consume from certain offset

### ISSUE THREAD

**Issue by SergeyLev** [confluentinc/confluent-kafka-python#1434]
Description
===========
Some consumed messages failed to parse due to datatype inconsistency and didn't get stored in db.
Requirement is to consume those messages to see what data needs to be addressed and then insert to db.
Use case - if offset range for partition is (1, 10) and I need to consume from offset 3 with batch size 4.

What I have tried:
topic = TopicPartition(topic, partition, starting_offset)
consumer.assign(topic)
messages = consumer.consume(batch_size, timeout=1.0)

Result:
Messages are consumed from the beginning e.g. offset 1 instead of offset 3.

How can I make consumer to start consuming from offset 3?

**Comment by SergeyLev** [comment]
Simply had do add consumer.commited(topic) as wait function and it works now.

**Comment by SergeyLev** [comment]
It worked once, then previous behavior.

**Comment by filpano** [comment]
See https://github.com/confluentinc/confluent-kafka-python/issues/11#issuecomment-230089107

**Comment by mhowlett** [comment]
you can use seek to control the consumer position.
committed offsets only come into play to determine the offset to consume from when the consumer is first assigned to a partition (possibly after a rebalance).
