### ISSUE TITLE
Difference between session.timeout.ms and max.poll.interval.ms

### ISSUE THREAD

**Issue by rkoystart** [confluentinc/confluent-kafka-python#1436]
Hi, I am new to the concept of kafka. I would like to know the difference between session.timeout.ms and max.poll.interval.ms. Both seems to be very confusing. 

https://archive.apache.org/dist/kafka/0.10.0.1/kafka_2.10-0.10.0.1.tgz
I am using the above version of kafka broker. 
 @edenhill please explain. Thanks in advance.

**Comment by pranavrth** [comment]
Please read about configurations here - https://docs.confluent.io/platform/current/clients/librdkafka/html/md_CONFIGURATION.html

Thanks.
