### ISSUE TITLE
monitor congestion on brokers with stats_cb/position/commited?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#144]
I have a consumer app and a producer app, and they will be exchanging possibly high-volume traffic over a kafka cluster. I don't get to put any of my own code on the cluster, it is just a generic kafka cluster. It would be interesting to me to see if the consumer is falling behind, and data was building up on the cluster from within my code (either producer or consumer). Is there a way to do this? On the consumer, I see that I can do consumer.position() and consumer.committed(), but their outputs don't look very interesting.

The stats_cb gives me a big blob of JSON, but I don't know how to interpret it. I can see each partition, and several different *_offset stats: hi_offset, next_offset, app_offset, eof_offset, and stored_offset. Sometimes these are all the same, some of them are -1001 (what does this mean?), and sometimes some are lower than others. When this is the case, is the difference an indication of how behind the consumer is? It seems that app_offset is always lower than or equal to hi_offset and next_offset, while eof_offset can be as high as hi_offset or lower than it.

Are the per-broker "throttle" stats what I want?

in general, is there a cheat sheet to help me interpret the stats_cb JSON blob? Barring that, is there a way to see what I want, that is, to determine if we are producing faster than we are consuming?

**Comment by ewencp** [comment]
@johnrgregg3 For tracking if you are falling behind, you combine your current position with the watermark offsets, which indicate what messages exist in Kafka. See http://docs.confluent.io/3.2.0/clients/confluent-kafka-python/index.html#confluent_kafka.Consumer.get_watermark_offsets

For statistics, you can find a listing of the statistics provided [here](https://github.com/edenhill/librdkafka/wiki/Statistics)

**Comment by johnrgregg3** [comment]
Thanks. The latest release is 0.9.2, which does not have this get_watermark_offsets(), does it? I have to wait for 0.9.4 to get officially released, right? Also, this does not take a TopicPartition list, so to get a snapshot of n partitions, I would have to call it n times, each time with a different TopicPartition? It seems I could get away with cached=True to avoid making inquiries back to the broker cluster n times, and I probably would still get pretty timely information, right?
I see that this returns a tuple of (high, low) but I don't know what that means. What exactly are these two numbers?

**Comment by edenhill** [comment]
v0.9.4 is officially released! See [PyPi](https://pypi.python.org/pypi/confluent-kafka/0.9.4).

And it has get_watermark_offsets()!

If you are actively consuming the partitions you should use cached=True and then the cost of calling it once per partition is miniscule (for the non-cached variant, not so much).
The high-watermark is updated on each Fetch response for the given partition, which should be every <= fetch.wait.max.ms (def 100ms).

The returned tuple is the high and low watermark offsets: the highest offset available in the partition (latest message) and the lowest offset available in the partition (the oldest message).

The high watermark is updated frequently as noted above, but the low watermark is updated every statistics.interval.ms - and if you don't need the low watermark then leave statistics.interval.ms set to 0 to avoid the extra requests.

**Comment by johnrgregg3** [comment]
So the high watermark is the offset of the most recent message in the partition that a producer produced? And the low watermark is the oldest message in the partition, even if it is days old? The low watermark will only ever change if the broker ages a message out to save space, regardless of what the consumer consumes or doesn't consume, or commits or doesn't commit, right?

From what you say, it sounds as if statistics.interval.ms controls how often the client issues some kind of a request over the network to the broker. I had imagined that somehow I was only controlling the rate of some internal query with that.

Moreover, are you saying that even if my consumer does a poll(3.0), under the covers there are frequent fetches from the consumer to the broker? Can I control their frequency, or just how quickly the broker responds to them with fetch.wait.max.ms?

Circling back to my original question, it looks like the magic number I want is consumer_lag in the stats block, right? Am I correct in thinking that this is exactly what I was asking for: how far is the consumer falling behind the producer? It looks like it is also introduced in 0.9.4, because I don't see it in my code, confluent-kafka-python 0.9.2/librdkafka 0.9.3.

**Comment by edenhill** [comment]
> So the high watermark is the offset of the most recent message in the partition that a producer produced? 
Yes
>And the low watermark is the oldest message in the partition, even if it is days old? 
Yes
> The low watermark will only ever change if the broker ages a message out to save space, regardless of what the consumer consumes or doesn't consume, or commits or doesn't commit, right?
Yes, according to the configured topic retention policy.

> From what you say, it sounds as if statistics.interval.ms controls how often the client issues some kind of a request over the network to the broker. I had imagined that somehow I was only controlling the rate of some internal query with that.

Fetching the low watermark requires an explicit protocol request, and it is probably overkill to fetch it every statistics.interval.ms (MAX(statistics_interval_ms, 60s) would probably be more than sufficient), but I don't think this is much of a concern unless you set statistics.interval.ms really low (sub-second).

> Moreover, are you saying that even if my consumer does a poll(3.0), under the covers there are frequent fetches from the consumer to the broker? Can I control their frequency, or just how quickly the broker responds to them with fetch.wait.max.ms?

Yes, poll() only checks the internal queue for new messages/callbacks. librdkafka will pre-fetch messages in the background to fullfill queued.min.messages or queued.max.messages.kbytes. The idea is that poll() should always be ready to return a new message to the application without having to perform a network request.  fetch.wait.max.ms is actually applied on the broker, making the FetchRequest block that long on the broker if there are no more messages to fetch - think of it as a long poll.


Yes, consumer_lag is what you want. The stats_cb was added in confluent-kafka-python 0.9.4.
There's a minimal example on how to use it here: https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/consumer.py#L27

**Comment by johnrgregg3** [comment]
I'm a little unclear on queued.min.messages and queued.max.messages.kbytes. It looks like the different fetch.* parameters help tune the performance of kafka, trading off response time against efficient use of the network, using buffering and stuff like that. I assume that I can just leave these alone and the defaults will be reasonable for me. But I could not make sense of queued.* from the CONFIGURATION.md. Is it the case that the local consumer will keep fetching until its local queue reaches queued.min.messages long? I assume the queue is fed by fetching from the broker, and drained by the app calling poll(). Once the queue gets queued.max.messages.kbytes long, does the consumer just stop doing fetches under the hood until the app drains the queue a bit? What consumer behavior changes when the queue gets queued.min.messages long? Or is that when we stop doing fetches?

I'm running confluent-kafka-python 0.9.2, and I have the stats_cb, so it was in at least that long ago, but I don't have consumer_lag. I'll upgrade to 0.9.4 soon.

**Comment by edenhill** [comment]
As usual you've got everything right :)

> I assume that I can just leave these alone and the defaults will be reasonable for me. 

Typically yes.

> But I could not make sense of queued.*

Messages are pre-fetched from the broker and inserted into a local queue (fetchq) that the application serves by calling poll().
Since messages are fetched in batches/messagesets (which are defined by the broker) we might get anything from 1 to thousand of messages per Fetch request and they all end up in the local fetchq.
The queued.min.messages and queued.max.messages.kbytes controls whether the fetcher should request a given partition again, or wait until the fetchq falls below those thresholds to start fetching again.

**Comment by johnrgregg3** [comment]
So if consumer_lag is 0, that's great - the consumer is caught up and nothing is building up on the broker. If consumer_lag is a positive integer, this is the number of messages behind the consumer is, that is, the number of messages waiting to be fetched from the broker (regardless of the length of the consumer's own fetchq)? What if consumer_lag is -1? I've seen that a few times (It looks like rd_kafka_stats_emit_toppar will give it this value if there is not (yet?) a valid hi_offset and fetch_offset, but I don't know why this condition would hold). Given the explanation of fetching above, it seems that the consumer app could fall pretty badly behind, with all the messages sitting on his local fetchq, even though the broker is happy, and consumer_lag is 0, right? Unless my interpretation of consumer_lag is incorrect. Consumer_lag tracks how far the consumer has fallen behind the broker, and not how far behind the app is from the fetchq's point of view?

**Comment by johnrgregg3** [comment]
It looks like only the off-book partition -1 has a consumer_lag of -1, so I can ignore that.

**Comment by edenhill** [comment]
> If consumer_lag is a positive integer, this is the number of messages behind the consumer is, that is, the number of messages waiting to be fetched from the broker (regardless of the length of the consumer's own fetchq)?

You are right again, again!
I think you've found a bug, the consumer_lag is calculated using the next fetch offset, not the offset where the application is currently at. This should be fixed in librdkafka.

What do you mean by off-book partition?

**Comment by johnrgregg3** [comment]
In the stats_cb, I get that big JSON blob, and within "partitions" there are sections for each partition, 1-n, plus one more, mysteriously called -1. That's what I'm calling the off-book partition, the secret hidden partition that I, as the app guy who set up my n partitions, know nothing about.

So if I want to know if my app is falling behind, I use consumer_lag to see if messages are accumulating on the broker, and also look at the length of my local fetchq to see if messages are accumulating locally. How can I see how long the fetchq is? Is it like the producer, that is, len(consumer)?

**Comment by edenhill** [comment]
Ah, yes, partition -1 is the UA/Unassigned partition which is an internal implementation detail (for the producer it holds messages that are not yet partitioned).
You should ignore it on the consumer.

There is no direct API to check each partition's fetchq apart, so you will need to use the fetchq metrics from the stats blob.

**Comment by johnrgregg3** [comment]
Could you explain why you think there is a bug? I guess I don't understand the difference between how you say consumer_lag is calculated, and how you say it should be calculated (next fetch offset vs. where the app is currently at?)

Am I right in saying that if the producer stopped producing, the consumer would have to consume consumer_lag + fetchq_cnt messages before it was completely caught up and had nothing more to do? Would fixing the bug you believe you have change that?

**Comment by johnrgregg3** [comment]
Just to test, I have set up a topic with 5 partitions. My producer test script sends 11 messages to this topic then exits. My consumer has set enable.partition.eof to False. I have introduced delays into my consumer to induce a falling-behind scenario. My consumer poll() only ever gets 11 non-None items (as I would expect), but according to my stats_cb, fetchq_cnt gets as high as 23, then goes back down to 0 less then one second later. What's more, the numbers for fetchq_cnt seem to be the same across all 5 partitions always. I assume this is because there is only one fetchq, and its stats are simply replicated throughout the stats block?

What are these other things on the fetchq that apparently do not ever manifest themselves in the form of messages or errors returned to my app by the poll()? I'm still trying to find the answer to what number or numbers should I pay attention to in order to determine how many messages behind my consumer is falling. It looks like fetchq_cnt probably includes that number, but some other stuff besides, and I would like to know how to subtract out that other stuff.

**Comment by edenhill** [comment]
> Am I right in saying that if the producer stopped producing, the consumer would have to consume consumer_lag + fetchq_cnt messages before it was completely caught up and had nothing more to do? Would fixing the bug you believe you have change that?

Yes. The code currently sort of assumes that the difference between the last fetched message and the last message handed to the application won't differ much, but with long processing time, or any Python code, that assumption might not be true.

I'm going to change the consumer_lag calculation from  'high_offset - last_fetched_offset' to 'high_offset - last_app_offset', i.e., the offset the latest message handed to the application - this is the true consumer lag.

> What's more, the numbers for fetchq_cnt seem to be the same across all 5 partitions always. I assume this is because there is only one fetchq, and its stats are simply replicated throughout the stats block?

Yes, with the high-level consumer (which the Python code always uses) all the fetchqs for all partitions are combined into one, so stats will report the same fetchq metrics for all partitions.


Until consumer_lag is fixed in librdkafka you should use `hi_offset - app_offset` to get the true consumer lag.

**Comment by johnrgregg3** [comment]
SO: hi_offset - app_offset is the true lag, the messages stacked up on the broker plus the ones stacked up on the local queue that the app has yet to take possession of with a poll(), right? What you are calling a bug is just the fact that you intended consumer_lag to mean this, the entire lag, but it actually only includes the messages on the broker, and not the ones on the fetchq (yet). Either way, if I just use hi_offset - app_offset, that is the number I want, and I can still use it even after you have fixed the bug, right?

**Comment by edenhill** [comment]
Right, but with the pre-fetching nature of the consumer there really isn't much value to the way consumer_lag is currently calculated (it could be seen as a network_lag perhaps, but still not interesting). The true lag is the difference between the app and the broker.

Yes, you can continue to use hi_offset - app_offset, they will not change meaning.

**Comment by johnrgregg3** [comment]
OK, but I'm still curious about all those other items on the fetchq that apparently I never see. How could fetchq_cnt every get larger than the number of things produced?

Are these offsets 32 bit numbers or 64? Should I worry about wrapping around back to 0?

If I have multiple consumers in the same consumer group, each consumer only gets messages from some subset of the partitions, even though it gets a full report of all the partitions in the stats_cb JSON blob. As I gather my statistics, I would like each consumer to only look at the numbers that pertain to it (if other consumers are falling behind, that's their problem). What is the surest way to distinguish between a partition that is aimed at this consumer and one that is aimed at some other consumer? My guess is fetch_state is "active", although the "desired" boolean might also work. Other than that, it looks like app_offset might stay pegged at INVALID (-1001) for partitions that are not "ours".

**Comment by edenhill** [comment]
The metric int widths are appropriate to what they message, a mix of 32 and 64 bits.
E.g. total bytes counter is 64 bits, while current message queue depth gauge is 32.
Thus there should be no risk of wrapping.

fetchq_cnt is the total sum of all queued messages for all partitions, shortly after a rebalance it is possible that this queue is larger than the number of available messages since it might have N pre-fetched messages for the previous assignment that are now outdated but not flushed, followed by M pre-fetched messages for the new assignment.
The outdated messages will be destroyed as soon as you call consume()

**Comment by edenhill** [comment]
Re partition state: librdkafka will create a local partition object for all partitions of a topic, even if it only makes use of a sub-set of them.  fetch_state=="active" means consumption is started for the given partition, so that seems like a good bet.  Do note though that there is a small time-window after rebalance where the client is collecting committed offsets, etc, where the fetch_state will not be active - but it won't consume any messages for that partition anyway so stats are not of value.
