### ISSUE TITLE
How do I adjust my offset to consume from this point forward?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#145]
So if I am a consumer, and I come to life and maybe I've been down for a long time, how can I set up a Consumer to subscribe to a given topic, with a given consumer group, and tell the broker, "advance my offset to the latest. I am not interested in anything produced up to right now, so don't send me any stale data."? I had thought that auto.offset.reset would do it, but this makes me think otherwise:
http://stackoverflow.com/questions/32390265/what-determines-kafka-consumer-offset
Given that my client is confluent-kafka-python, what can I do at init time to advance my offset to the present moment's offset?

**Comment by edenhill** [comment]
The assign() method takes a list of TopicPartition, if you don't set an explicit offset for a TopicPartition it will default to trying to get the last committed offset for that partition (and group), and if that fails falls back to auto.offset.reset (defaults to latest).

But in your case it sounds like you want to ignore the committed offsets at certain times, so in this case you should set the TopicPartition's offset to OFFSET_END which will make it seek directly to the end of the partition, ignoring any committed offsets.

Something like this:
```python
import confluent_kafka

if __name__ == '__main__':
    c = confluent_kafka.Consumer({"bootstrap.servers": "eden:9092", "group.id":"me"})

    def my_assign (consumer, partitions):
        for p in partitions:
            p.offset = confluent_kafka.OFFSET_END
        print('assign', partitions)
        consumer.assign(partitions)

    c.subscribe(["test"], on_assign=my_assign)

    while True:
        m = c.poll(1)
        if m is None:
            continue

        if m.error() is None:
            print('Received message', m)


    c.close()

```

**Comment by johnrgregg3** [comment]
Thanks! Does that have the effect of advancing my committed offsets to the END, and from then on I will consume from that point forward, and commit from that point forward as well? The broker maintains a per-consumer group offset, right?

Also, in my little test script, when I copy/pasted your code, I got this exception:

    p.offset = confluent_kafka.OFFSET_END
AttributeError: 'module' object has no attribute 'OFFSET_END'.

Is there some prefix I should have used? I tried a few shots in the dark, but I still got exceptions.

**Comment by johnrgregg3** [comment]
Using confluent-kafka-python, I get the above exception for confluent_kafka.OFFSET_END, confluent_kafka.TopicPartition.OFFSET_END, confluent_kafka.RD_KAFKA_OFFSET_END, and confluent_kafka.TopicPartition.RD_KAFKA_OFFSET_END. The one thing that works is simply:

p.offset = -1

which I know to do because of this in rdkafka.h:

#define RD_KAFKA_OFFSET_END       -1  /**< Start consuming from end of kafka

which will get my code to work for now, but I'd like a more symbolic way to do it.

**Comment by edenhill** [comment]
Good thing you know your way around the underlying C  code :)

If you upgrade the python client to v0.9.4  (and librdkafka too, for good measures) you should get the proper offset constants.

**Comment by aashu24ahuja** [comment]
I tried your code, it gives the offset = -1 but my message is not being consumed even though I had published a few. It displays none.

``conf['auto.offset.reset']` = 'latest'`

**Comment by setourneux** [comment]
> RD_KAFKA_OFFSET_END

Yes because DeserialisingConsumer herits from class Consumer
