### ISSUE TITLE
Support for Python 3.11?

### ISSUE THREAD

**Issue by thibaultbetremieux** [confluentinc/confluent-kafka-python#1452]
Description
===========

I tried installing `confluent-kafka` inside a conda environment with `python=3.11`. It did not work. It was working previously with `python=3.10.6` and I'd like to use some features from 3.11 :slightly_smiling_face: .

How to reproduce
================

1. Create conda environment with Python 3.11 (enter the commands one by one and accept prompts, this is not a script):

```
conda create -n test_confluent_kafka
conda activate test_confluent_kafka
conda install python=3.11 -c conda-forge
```

2. Attempt to install `confluent-kafka` inside the enviromnent

```
pip install confluent-kafka
```

<details>
<summary>Output</summary>
Collecting confluent-kafka
  Using cached confluent-kafka-1.9.2.tar.gz (109 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: confluent-kafka
  Building wheel for confluent-kafka (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka
      copying src/confluent_kafka/error.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka
      copying src/confluent_kafka/serializing_producer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka
      copying src/confluent_kafka/deserializing_consumer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka
      copying src/confluent_kafka/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      copying src/confluent_kafka/avro/error.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      copying src/confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      copying src/confluent_kafka/avro/load.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      copying src/confluent_kafka/avro/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      copying src/confluent_kafka/admin/_config.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      copying src/confluent_kafka/admin/_acl.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      copying src/confluent_kafka/admin/_resource.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      copying src/confluent_kafka/admin/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/error.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/schema_registry_client.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/json_schema.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/protobuf.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/avro.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/serialization
      copying src/confluent_kafka/serialization/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/serialization
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/avro/serializer
      copying src/confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro/serializer
      copying src/confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro/serializer
      running build_ext
      building 'confluent_kafka.cimpl' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/tmp
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src
      gcc -pthread -B /home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/include -fPIC -O2 -isystem /home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/include -fPIC -I/home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/include/python3.11 -c /tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src/Admin.c -o build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src/Admin.o
      In file included from /tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src/Admin.c:17:
      /tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: librdkafka/rdkafka.h: No such file or directory
         23 | #include <librdkafka/rdkafka.h>
            |          ^~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for confluent-kafka
  Running setup.py clean for confluent-kafka
Failed to build confluent-kafka
Installing collected packages: confluent-kafka
  Running setup.py install for confluent-kafka ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for confluent-kafka did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running install
      /home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka
      copying src/confluent_kafka/error.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka
      copying src/confluent_kafka/serializing_producer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka
      copying src/confluent_kafka/deserializing_consumer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka
      copying src/confluent_kafka/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      copying src/confluent_kafka/avro/error.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      copying src/confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      copying src/confluent_kafka/avro/load.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      copying src/confluent_kafka/avro/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      copying src/confluent_kafka/admin/_config.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      copying src/confluent_kafka/admin/_acl.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      copying src/confluent_kafka/admin/_resource.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      copying src/confluent_kafka/admin/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/admin
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/kafkatest
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/error.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/schema_registry_client.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/json_schema.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/protobuf.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/avro.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/schema_registry
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/serialization
      copying src/confluent_kafka/serialization/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/serialization
      creating build/lib.linux-x86_64-cpython-311/confluent_kafka/avro/serializer
      copying src/confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro/serializer
      copying src/confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-cpython-311/confluent_kafka/avro/serializer
      running build_ext
      building 'confluent_kafka.cimpl' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/tmp
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka
      creating build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src
      gcc -pthread -B /home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/include -fPIC -O2 -isystem /home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/include -fPIC -I/home/thibaultbetremieux/anaconda3/envs/test_confluent_kafka/include/python3.11 -c /tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src/Admin.c -o build/temp.linux-x86_64-cpython-311/tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src/Admin.o
      In file included from /tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src/Admin.c:17:
      /tmp/pip-install-hrf7miay/confluent-kafka_24487a6a36c04ac3bd52ab375f05fcd5/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: librdkafka/rdkafka.h: No such file or directory
         23 | #include <librdkafka/rdkafka.h>
            |          ^~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> confluent-kafka

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
</details>

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): `confluent-kafka-=1.9.2`, `librdkafka=?`
 - [ ] Apache Kafka broker version:  ?
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Pop!_OS 22.04 LTS
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ermakov-oleg** [comment]
For python 3.10 you used wheel and did not need to compile from source.
Wheels for python 3.11 are not ready yet and you need to install librdkafka v1.9.0 or later and try to install it again. 

@edenhill can you build a wheel for python 3.11?

**Comment by pranavrth** [comment]
We are planning to add a 3.11 wheel for our next release which is about a month out

**Comment by Hawax** [comment]
apt-get install -y --no-install-recommends gcc git libssl-dev g++ make && cd /tmp && git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure --prefix=/usr && make && make install 

works for me on 3.11 on ubuntu 18.04 😄

**Comment by RichardDally** [comment]
> apt-get install -y --no-install-recommends gcc git libssl-dev g++ make && cd /tmp && git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure --prefix=/usr && make && make install 
> 
> 
> 
> works for me on 3.11 on ubuntu 18.04 😄 

I've tried same steps in RH8 but repository is still using an old librdkafka so I had to compile it too. I would be very interested to compile confluent kafka wheel with a static version of librdkafka 1.9.0

**Comment by nitin-karolla** [comment]
Waiting for the 3.11 wheel release 🚀

**Comment by reupugi** [comment]
> apt-get install -y --no-install-recommends gcc git libssl-dev g++ make && cd /tmp && git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure --prefix=/usr && make && make install
> 
> works for me on 3.11 on ubuntu 18.04 smile

I tried your method - still get `ModuleNotFoundError` when I try to import confluent_kafka - Any suggestions?

**Comment by Hawax** [comment]
> > apt-get install -y --no-install-recommends gcc git libssl-dev g++ make && cd /tmp && git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure --prefix=/usr && make && make install
> > works for me on 3.11 on ubuntu 18.04 smile
> 
> I tried your method - still get `ModuleNotFoundError` when I try to import confluent_kafka - Any suggestions?

Have you tried to install Kafka with pip after these steps?

**Comment by reupugi** [comment]
> > > apt-get install -y --no-install-recommends gcc git libssl-dev g++ make && cd /tmp && git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure --prefix=/usr && make && make install
> > > works for me on 3.11 on ubuntu 18.04 smile
> > 
> > 
> > I tried your method - still get `ModuleNotFoundError` when I try to import confluent_kafka - Any suggestions?
> 
> Have you tried to install Kafka with pip after these steps?

yes I did this now and it works

**Comment by sbv-csis** [comment]
https://github.com/confluentinc/confluent-kafka-python/pull/1467 <--- getting there :+1:

**Comment by agates4** [comment]
Does the merge of #1467 mean this will be in the next release?

**Comment by nitin-karolla** [comment]
When is the next release? When can we expect the wheel for 3.11 to be available?

**Comment by wbarnha** [comment]
I've been running this in `python:3.11-slim-bullseye` while waiting for Confluent to release an update:
```Dockerfile
RUN apt-get update -y && apt-get install -y --no-install-recommends gcc git libssl-dev g++ make && cd /tmp && git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure --prefix=/usr && make && make install
RUN python -m pip install --upgrade 'confluent-kafka @ git+https://github.com/confluentinc/confluent-kafka-python@81e97dcad8520247c01b6ecded477b37815462f8'
```
Hopefully this makes someone's life more convenient. It'll make the image size increase by 300-400 MB but if you're just verifying your code for Python 3.11, it'll do.

**Comment by giacomomiolo** [comment]
Any updates on this? Thanks for the great work!

**Comment by y3ti** [comment]
If you want to build `*.whl` file:

```Makefile
.PHONY: build
build:
	DOCKER_BUILDKIT=1 docker build --output type=local,dest=./wheels .
```

```Dockerfile
###############################################################################
# BUILDER
###############################################################################
FROM quay.io/pypa/manylinux_2_24_x86_64 AS builder

ARG CONFLUENT_KAFKA_VERSION=1.9.2
ARG LIBRDKAFKA_VERSION=1.9.2
ENV PYBIN=/opt/python/cp311-cp311/bin/

RUN set -ex \
    &&  apt-get update \
    &&  apt-get install --no-install-recommends --yes \
            build-essential \
            git \
            libsasl2-dev \
            libssl-dev \
            libzstd-dev

# build and install librdkafka
WORKDIR /tmp/librdkafka
RUN set -ex \
    &&  git clone --branch v1.9.2 https://github.com/edenhill/librdkafka.git . \
    &&  ./configure --prefix=/usr \
    &&  make \
    &&  make install


# build confluent-kafka python wheel
WORKDIR /tmp/confluent-kafka-python
RUN set -ex \
    &&  git clone --branch v1.9.2 https://github.com/confluentinc/confluent-kafka-python.git . \
    &&  mkdir -p dist /wheels \
    &&  ${PYBIN}/python3.11 setup.py bdist_wheel -d dist \
    &&  auditwheel repair dist/*.whl -w /wheels

###############################################################################
# WHEELS
###############################################################################
FROM scratch AS wheels

COPY --from=builder /wheels/*.whl .
```

Build the python wheel for 3.11:

```bash
$ make build
...
$ ls wheels/
confluent_kafka-1.9.2-cp311-cp311-manylinux_2_24_x86_64.whl
```

The wheel includes all required shared libraries:
```
$ unzip -l wheels/confluent_kafka-1.9.2-cp311-cp311-manylinux_2_24_x86_64.whl 
Archive:  wheels/confluent_kafka-1.9.2-cp311-cp311-manylinux_2_24_x86_64.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
...
   113257  2023-01-02 11:51   confluent_kafka.libs/libsasl2-4427c928.so.2.0.25
   483537  2023-01-02 11:51   confluent_kafka.libs/libssl-6db5df62.so.1.1
 10700473  2023-01-02 11:51   confluent_kafka.libs/librdkafka-ddc374ef.so.1
  2833457  2023-01-02 11:51   confluent_kafka.libs/libcrypto-f5871c65.so.1.1
```

**Comment by rdasari5** [comment]
Hi Team,

I am getting below error while trying to install locust plugins, please check if its related to this issue. 

 C:\Users\532720\AppData\Local\Temp\pip-install-xs29pl_m\confluent-kafka_5fb7b110405e498a8ff4d4598602445f\src\confluent_kafka\src\confluent_kafka.h(23): fatal error C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory
 
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

**Comment by pranavrth** [comment]
We are planning to have the next release after librdkafka is released. So around end of January or early February.

**Comment by stegayet** [comment]
Thanks for the follow-up :+1:

**Comment by ehn-lpbezerra** [comment]
> If you want to build `*.whl` file:
> 
> `Makefile`:
> 
> ```makefile
> .PHONY: build
> build:
> 	DOCKER_BUILDKIT=1 docker build --output type=local,dest=./wheels .
> ```
> 
> `Dockerfile`:
> 
> ```dockerfile
> ###############################################################################
> # BUILDER
> ###############################################################################
> FROM quay.io/pypa/manylinux_2_24_x86_64 AS builder
> 
> ARG CONFLUENT_KAFKA_VERSION=1.9.2
> ARG LIBRDKAFKA_VERSION=1.9.2
> ENV PYBIN=/opt/python/cp311-cp311/bin/
> 
> RUN set -ex \
>     &&  apt-get update \
>     &&  apt-get install --no-install-recommends --yes \
>             build-essential \
>             git \
>             libsasl2-dev \
>             libssl-dev \
>             libzstd-dev
> 
> # build and install librdkafka
> WORKDIR /tmp/librdkafka
> RUN set -ex \
>     &&  git clone --branch v${LIBRDKAFKA_VERSION} https://github.com/edenhill/librdkafka.git . \
>     &&  ./configure --prefix=/usr \
>     &&  make \
>     &&  make install
> 
> 
> # build confluent-kafka python wheel
> WORKDIR /tmp/confluent-kafka-python
> RUN set -ex \
>     &&  git clone --branch v${CONFLUENT_KAFKA_VERSION} https://github.com/confluentinc/confluent-kafka-python.git . \
>     &&  mkdir -p dist /wheels \
>     &&  ${PYBIN}/python3.11 setup.py bdist_wheel -d dist \
>     &&  auditwheel repair dist/*.whl -w /wheels
> 
> ###############################################################################
> # WHEELS
> ###############################################################################
> FROM scratch AS wheels
> 
> COPY --from=builder /wheels/*.whl .
> ```
> 
> Build the python wheel for 3.11:
> 
> ```shell
> $ make build
> ...
> $ ls wheels/
> confluent_kafka-1.9.2-cp311-cp311-manylinux_2_24_x86_64.whl
> ```
> 
> The wheel includes all required shared libraries:
> 
> ```
> $ unzip -l wheels/confluent_kafka-1.9.2-cp311-cp311-manylinux_2_24_x86_64.whl 
> Archive:  wheels/confluent_kafka-1.9.2-cp311-cp311-manylinux_2_24_x86_64.whl
>   Length      Date    Time    Name
> ---------  ---------- -----   ----
> ...
>    113257  2023-01-02 11:51   confluent_kafka.libs/libsasl2-4427c928.so.2.0.25
>    483537  2023-01-02 11:51   confluent_kafka.libs/libssl-6db5df62.so.1.1
>  10700473  2023-01-02 11:51   confluent_kafka.libs/librdkafka-ddc374ef.so.1
>   2833457  2023-01-02 11:51   confluent_kafka.libs/libcrypto-f5871c65.so.1.1
> ```

How do I use this wheel file? I've managed to build the wheel following your instructions, but I don't know what to do with it. Any help would be much appreciated. 

Thanks in advance!

**Comment by y3ti** [comment]
@ehn-lpbezerra just install it via `pip3 install --no-index wheels/confluent_kafka-1.9.2-cp311-cp311-manylinux_2_24_x86_64.whl`

**Comment by pranavrth** [comment]
We have released [v2.0.2](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v2.0.2) with Python 3.11 wheels included.

**Comment by RichardDally** [comment]
OpenSSL 3 is required to use this wheel, right ?

**Comment by AXGKl** [comment]
On conda (micromamba) a `micromamba install librdkafka` before installing this with pip did the trick.
