### ISSUE TITLE
Losing Kafka old messages

### ISSUE THREAD

**Issue by youssefbenfarhat** [confluentinc/confluent-kafka-python#1464]
Last time I used Confluent Kafka was 2 months again, at that that time I used to have topics and different consumers and producers. 
Now when I start Kafka and try to see my clusters, I can't find all the previous work. Everything is empty. I can't understand, if I lost my messages and topics or what.

**Comment by pranavrth** [comment]
The default retention period for a topic in Kafka is 7 days. If you didn't change this property, you will lose the messages. Please refer - https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#topicconfigs_retention.ms
