### ISSUE TITLE
Message is pushed into incorrect Topic Partition

### ISSUE THREAD

**Issue by Gatsby-Lee** [confluentinc/confluent-kafka-python#1481]
Description
===========

The produced message goes into the incorrect Topic Partition.
The target Kafka Topic has 50 Partitions.

This below should go into Partition=40 ( based on Kafka Hashing ), 
it keep going into Partition=36.

I have two different Producers that they push this message into Partition=40
* MongoDB Kafka Source Connector
* Conductor ( Tool )

* Key
```
key = 'Struct{documentKey={"_id": "638d1b94ce8def06be68b439"}}'
```

* Value
```
value = '{"_id": "{\"_data\": \"from_kafka_push_mongo_delete_cdc_msg\"}", "documentKey": "{\"_id\": \"638d1b94ce8def06be68b439\"}", "clusterTime": "{\"$timestamp\": {\"t\": 1671029299, \"i\": 1}}", "operationType": "delete", "ns": {"db": "forethought", "coll": "org_feature"}, "fullDocument": null, "to": null, "txnNumber": null, "lsid": null}'
```

How to reproduce
================

With the above message, you can push the message with this code.

```
client.produce(
        topic=kafka_topic_name,
        key=key,
        value=value,
    )
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version
```
>>> import confluent_kafka
>>> confluent_kafka.version()
('1.8.2', 17302016)
>>> confluent_kafka.libversion()
('1.8.2', 17302271)
```
 - [x] Apache Kafka broker version: 2.6.2
 - [x] Client configuration: `{...}`
 ```
KAFKA_PRODUCER_EXTRA_CONFIG = {
    "batch.num.messages": 1000,  # default: 1000
    "queue.buffering.max.ms": 1000,  # default: 1000
    "queue.buffering.max.messages": 100000,  # default: queue.buffering.max.messages
    # `queue.buffering.max.kbytes` has higher priority than queue.buffering.max.messages
    "queue.buffering.max.kbytes": 4000000,  # default: 4000000
}
```
 - [x] Operating system: MacOS
 - [x] Critical issue

**Comment by edenhill** [comment]
The default partitioner is not compatible with the default java partitioner, so you will need to configure `'partitioner': 'murmur2_random'`  which is equivalent to the java partitioner.

**Comment by Gatsby-Lee** [comment]
> The default partitioner is not compatible with the default java partitioner, so you will need to configure `'partitioner': 'murmur2_random'` which is equivalent to the java partitioner.

Thank you very much!!
Is there documentation about this?
