### ISSUE TITLE
Unable to catch timeout/refused errors on the client 

### ISSUE THREAD

**Issue by ChillarAnand** [confluentinc/confluent-kafka-python#1491]
Related issue : https://github.com/confluentinc/confluent-kafka-python/issues/1222#issuecomment-1038753418

Description
===========

When client is polling for new messages, the following errors might happens.

```
FAIL [rdkafka#consumer-1] [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)

FAIL [rdkafka#consumer-3] [thrd:sasl_ssl://foo/3]: foo/3: 1 request(s) timed out: disconnect (after 154583ms in state UP, 1 identical error(s) suppressed)“
```

I am trying to silence these errors or handle in a different way.

How to reproduce
================

Use the below script to reproduce the error.

https://github.com/ChillarAnand/avilpage.com/blob/master/scripts/confluent_kafka_consumer.py

To avoid printing these messages, the context manager in the scripting can be used for now.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system: macOS
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [x] Provide broker log excerpts - None
 - [x] Critical issue - No

```py
>>> import confluent_kafka
>>> confluent_kafka.version()
('1.7.0', 17235968)
>>> confluent_kafka.libversion()
('1.9.2', 17367807)
```

**Comment by pranavrth** [comment]
If you want to silence these messages, please use filter in the logger. See - [logger.addFilter](https://docs.python.org/3/library/logging.html#logging.Logger.addFilter)

**Comment by ChillarAnand** [comment]
I tried to silence these via `consumer`, `confluent_kafka` loggers. But they are not working. However suppressing stderr, stdout is silencing the messages.

Can you please share the logger that is producing the messages? @pranavrth 

https://github.com/ChillarAnand/avilpage.com/blob/master/scripts/confluent_kafka_consumer.py

**Comment by pranavrth** [comment]
You can use something like this - 


```python
class ConnectionRefusedFilter(logging.Filter):
    def filter(self, record):
        return "Connection refused" not in record.getMessage()

logger = logging.getLogger(__file__)
logger.setLevel(logging.ERROR)
f = ConnectionRefusedFilter()
logger.addFilter(f)
```
