### ISSUE TITLE
Adding custom partitioner

### ISSUE THREAD

**Issue by MoudgilNikhil** [confluentinc/confluent-kafka-python#1508]
Description
===========
Hi guys, is there any way I can override the default partitioner in Confluent Kafka Cloud? I have done this on Kafka Python. But I am shifting to confluent cloud for better reliability and scalability.

**Comment by pranavrth** [comment]
Currently, python client support only in-built partitioners. Please check `partitioner` config property in [configuration properties](https://docs.confluent.io/platform/current/clients/librdkafka/html/md_CONFIGURATION.html). `partitioner_cb` is **not** supported in Python client.
