### ISSUE TITLE
confluent_kafka.version() returns wrong version

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#151]
In 0.9.4, even though setup.py says:
version='0.9.4'
in confluent_kafka.c we have:
static PyObject *version (PyObject *self, PyObject *args) {
        return Py_BuildValue("si", "0.9.2", 0x00090100);
}
which, if I'm reading it correctly, is not only wrong, but self-inconsistent.

**Comment by edenhill** [comment]
Hardcoded stuff.. so easy to forget.
