### ISSUE TITLE
Missing DeleteRecords equiv in AdminClient (KIP-107 method)

### ISSUE THREAD

**Issue by michaelandrepearce** [confluentinc/confluent-kafka-python#1513]
Description
===========

deleteRecords equiv from Java does not seem to be exposed in AdminClient, on checking librdkafka it exists in the underlying C++ lib, just not exposed up in python wrapper. Please can it be exposed/added.

https://github.com/confluentinc/librdkafka/blob/master/examples/delete_records.c

How to reproduce
================

expecting to see method something like: admin.delete_records , but cannot find.

Checklist
=========
Please provide the following information:

 - [1.9.2 ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [NA ] Apache Kafka broker version:
 - [NA ] Client configuration: `{...}`
 - [Windows/Linux ] Operating system:
 - [ NA] Provide client logs (with `'debug': '..'` as necessary)
 - [ NA] Provide broker log excerpts
 - [no ] Critical issue

**Comment by pranavrth** [comment]
Good find. We will add it to our backlog. Thanks.

**Comment by michaelandrepearce** [comment]
Any update here?

**Comment by mahajanadhitya** [comment]
Great find. We are working on the Python Client Delete Records which is the equivalent of the above method. Will update this thread when the feature is merged.

**Comment by michaelandrepearce** [comment]
@mahajanadhitya just checking in if there is any update here?

**Comment by michaelandrepearce** [comment]
@mahajanadhitya  is there any timeline?

**Comment by strafer** [comment]
I join the question. For my current task, it is required to delete messages in the topic/partition in the python script.

**Comment by pranavrth** [comment]
This is being worked upon and will be added as part of the upcoming release in late April. [PR](https://github.com/confluentinc/confluent-kafka-python/pull/1710)

**Comment by pranavrth** [comment]
The PR is merged and will be available in v2.5.0.
