### ISSUE TITLE
Deprecated methods

### ISSUE THREAD

**Issue by Gadzillion** [confluentinc/confluent-kafka-python#1518]
Description
===========

1. Where should i get analogue for ```protocol_type``` attribute from ```GroupMetadata``` in ```AdminClient``` if ```list_groups()``` method is going to be deprecated ? 

confluent-kafka-python: 2.0.2

**Comment by pranavrth** [comment]
With the latest release, we are not exposing `protocol_type` field anymore in `list_consumer_groups` or `describe_consumer_groups` apis. This was part of [KIP-222](https://cwiki.apache.org/confluence/display/KAFKA/KIP-222+-+Add+Consumer+Group+operations+to+Admin+API) which was long pending in non-java clients. We have added a flag `is_simple_consumer_group` which specifies whether the consumer group is simple or not. 

Having said this, can you tell your usecase around `protocol_type` field?

**Comment by Gadzillion** [comment]
I need to check is it ```consumer``` or not. What can be the values of the ```protocol_type``` variable ?

**Comment by pranavrth** [comment]
If it is `consumer`, then `is_simple_consumer_group` is `false`

**Comment by Gadzillion** [comment]
Thank you, its enough )
