### ISSUE TITLE
Repo tag for confluent-kafka 0.9.4

### ISSUE THREAD

**Issue by kinghuang** [confluentinc/confluent-kafka-python#153]
Which commit does the the [confluent-kafka 0.9.4](https://pypi.python.org/pypi/confluent-kafka/0.9.4) module correspond to? The [v0.9.4](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v0.9.4), [v0.9.4-RC1](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v0.9.4-RC1), and [v0.9.4-RC2](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v0.9.4-RC2) tags in this repo all point to the same commit: d415bb9.

**Comment by edenhill** [comment]
The `v0.9.4` tag is the final released version which is also what you will find on PyPi.

**Comment by mtrienis** [comment]
I still see v0.9.2 as the latest release in github. 

- https://github.com/confluentinc/confluent-kafka-python/releases

I assume v0.9.4 is officially released though?

**Comment by ewencp** [comment]
@mtrienis The PyPI releases are the official ones, so https://pypi.python.org/pypi/confluent-kafka/0.9.4 is officially released. I've just generated the release on GitHub as well.
