### ISSUE TITLE
Typo UNKOWN

### ISSUE THREAD

**Issue by robooo** [confluentinc/confluent-kafka-python#1537]
Description
===========
Is this a typo or just shorten string due to some conflict?
https://github.com/confluentinc/confluent-kafka-python/blob/1db305460656285cad56c9286a106262545ca573/src/confluent_kafka/_model/__init__.py#L76

**Comment by pranavrth** [comment]
Its a Typo. But let me think about it now if we want to correct or not.

**Comment by pranavrth** [comment]
Please use this value for now. We will fix this in next major version release.

**Comment by pranavrth** [comment]
We have decided to add a new value UNKNOWN along with the typo one. We suggest to use the newer one. PR - https://github.com/confluentinc/confluent-kafka-python/pull/1539
