### ISSUE TITLE
Kafka, getting that first message.

### ISSUE THREAD

**Issue by jmalacho** [confluentinc/confluent-kafka-python#156]
When trying to write an integration test for Kafka, I noticed I was frequently missing that first message.  I think I've finally gotten the hang of it by changing my subscribe call to something blocking like this:

```
def assignment(consumer, partitions):
   print('Assignment:', partitions)
   assignment.isAssigned=True


def test_consume():
   ...
   assignment.isAssigned=False
   c.subscribe( [ topic ], assignment )    
   while not assignment.isAssigned:
      print "Waiting for Subscription"
      msg=c.poll( timeout=1.0 )
```

Does this make sense? Or can someone elaborate? It seems like the subscribe call is effectively Asynchronous, and that if I don't wait for it, my 'offset' will be wrong.

**Comment by edenhill** [comment]
subscribe() sets the list of topics to subscribe and starts the join process in the background, not only is it asynchronous but you may receive any number of assignments during the lifetime of a consumer after the initial call to subscribe().
So you can't make any timing or assignment assumptions following subscribe(), you need to wait for the rebalance (either conciouscly using an on_assign callback or not (just wait for messages)) before you have any idea what partitions or offsets you will consume.

I don't know what you are trying to achieve, but with the above in mind I would restructure your program as so:
```
def assignment(consumer, partitions):
   print('Assignment:', partitions)
  # do something important

def test_consume():
   ...
   c.subscribe( [ topic ], on_assign=)    
   while running:
      msg = c.poll(timeout=1.0)
      if msg is None:
          continue # timeout
      else if msg.error():
           print(msg.error())  #or handle it
       else:
          handle_msg(msg)
```

**Comment by jmalacho** [comment]
Thanks for the quick feedback; and thanks for making librdkafka (I made an rpm of it just the other day).

I'm sorry I wasn't specific.  I was trying to "Verify that my docker container of kafka was 'good' / ready for deployment" (I'm trying to make docker container CI-pipelines, and I would like a a verification step).

So I started making a pytest file: https://github.com/jmalacho/kafka/blob/feature/test-works/files/test_kafka.py

A common Cucumber for a message framework might read:
```
Given a kafka service on port "9092"
When I send send "1" message to topic "t"
Then I receive "1" message on topic "t"
```
So I wanted to send a message then receive that message.  If I create the consumer from the beginning, then that topic would need to be cleaned out in someway ( I don't know if that's possible), or the consumer needs to be created before the producer.  
But even when I created the producer after I had created the consumer, I found I was frequently missing that first message.  I asked this question for clarification to make sure I understood how it was supposed to work.  I'm always trying to write tests that pass **everytime**, otherwise I don't think I know enough to write the application itself.

**Comment by edenhill** [comment]
Thanks for the explanation.

Creating the consumer before the producer makes sense, but since the consumer may take up to session.timeout.ms (def 30s, typically faster) to get an assignment it is possible that your producer manages to produce its message before the consumer has started consuming the topic.
With this in mind your first code snippet makes more sense and you should hold off creating the producer until you've seen a proper assignment.

I would probably do something like:
 * create consumer
 * subscribe to topic
 * consume: wait for message.error() == PARTITION_EOF (end of partition reached, implies an assignment)
 * start producer, produce(), flush(), destroy producer
 * consume: you should see the message now
