### ISSUE TITLE
JSONSerializer unnecessary schema validation on every call

### ISSUE THREAD

**Issue by liukas321** [confluentinc/confluent-kafka-python#1564]
Description
===========

Schema validation is coupled with object validation in **JSONSerializer.__call__()**. Every time an object is being serialized, the schema (JSONSerializer._parsed_schema) is being validated alongside the object dict validation:
[https://github.com/confluentinc/confluent-kafka-python/blob/baf71ea0ed54c71948208bfc5c352f4ee57054dd/src/confluent_kafka/schema_registry/json_schema.py#L267](url)

This is due to use of **jsonschema.validators.validate** as the validation method, which validates schema before validating the object every time:
```
if cls is None:
    cls = validator_for(schema)    # Determines the best validator

cls.check_schema(schema)    # Uses MetaSchema of the validator to validate the schema
validator = cls(schema, *args, **kwargs)    # Initializes new validator
error = exceptions.best_match(validator.iter_errors(instance))    # Validates the object
```

As a result, JSON serialization is slow and unusable in the current state.

JSONDeserializer suffers from exactly the same problem.

How to reproduce
================

1) Create an instance of JSONSerializer with any valid parameters
2) Call it to serialize 10,000 random objects

```
def test():
    ctx = SerializationContext(topic=TOPIC, field=MessageField.VALUE)
    for _ in range(10_000):
        obj = DummyObject.random_obj()
        json_serializer(obj, ctx)
```

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
version: ('2.1.0', 33619968); libversion: ('2.1.0', 33620223)
 - [ ] Apache Kafka broker version:
NA
 - [ ] Client configuration: `{...}`
 NA
 - [X] Operating system:
 Win10-x64
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 NA
 - [ ] Provide broker log excerpts
 NA
 - [ ] Critical issue
Not critical

**Comment by rayokota** [comment]
Added a validate flag in https://github.com/confluentinc/confluent-kafka-python/pull/1852

**Comment by js-lowes** [comment]
@rayokota I strongly urge for this issue to re-opened until [PR#1565](https://github.com/confluentinc/confluent-kafka-python/pull/1565) is merged. Validation should still be called but the schema should only have to be validated once. In the current implementation it will validate BOTH schema and the record data for every record. [PR#1565](https://github.com/confluentinc/confluent-kafka-python/pull/1565) seems to handle this issue by only validating the schema once and then caching it for future use.

Internally we have a large schema and we tested it by using the default Schema Registry code. It took ~72-75 secs per 1,000 records when using a schema that is validated using the default code. When validating once and then posting to the queue it took ~1-2 secs per 1,000 records when the schema was validate once and then cached.

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1918
