### ISSUE TITLE
symbol not found in flat namespace '_rd_kafka_AdminOptions_destroy'

### ISSUE THREAD

**Issue by sarth886** [confluentinc/confluent-kafka-python#1570]
Description
===========
Getting Error:

python3 -c 'import confluent_kafka; print(confluent_kafka.libversion())'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/snasit/.pyenv/versions/data-collection/lib/python3.6/site-packages/confluent_kafka/__init__.py", line 2, in <module>
    from .cimpl import (Consumer,  # noqa
ImportError: dlopen(/Users/snasit/.pyenv/versions/data-collection/lib/python3.6/site-packages/confluent_kafka/cimpl.cpython-36m-darwin.so, 0x0002): symbol not found in flat namespace '_rd_kafka_AdminOptions_destroy'

confluent-kafka==1.2.0
librdkafka@2.1.1
Arch : arm64
Python: 3.6

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by pranavrth** [comment]
confluent_kafka==1.2.0 is very old. Try installing the latest one which is v2.1.1. 

Also, we don't provide wheels for python 3.6 for arm64 arc. Preferably, try with >3.9 version of Python.

**Comment by sarth886** [comment]
My service is dependent on that version ........... can you tell anything about the error.
And I am able to install confluent_kafka without any issue but while importing it fails with above error.

Can it be a issue with librdkafka version ?

**Comment by sarth886** [comment]
how can i install librdkafka version 1.2.0...i did not find them in brew

**Comment by pranavrth** [comment]
You will need to install librdkafka from source. Use this [commit](https://github.com/confluentinc/librdkafka/tree/v1.2.0) and these [instructions](https://github.com/confluentinc/librdkafka/tree/v1.2.0#build-from-source).

Much better would to upgrade your service to be at the latest version. In this way, we would understand if this is a real issue or not.

**Comment by sarth886** [comment]
The issue was solved by using librdkafka version 2.0.1 which needs to be build from source as mentioned above.

Thank you for the help.
