### ISSUE TITLE
Mismatching parameter name in web documentation

### ISSUE THREAD

**Issue by amues** [confluentinc/confluent-kafka-python#1579]
Description
===========
Is the documentation for `KafkaError` in https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#kafkaerror correct?

One of the parameters listed there is named `error_code`, but I get
```
>>> dir(KafkaError)
[
(...)
 'code', <-
 'fatal',
 'name',
 'retriable',
 'str',
 'txn_requires_abort']
```

I don't have much experience with C/Python integration, but it seems to me that the underlying C type comes from https://github.com/confluentinc/confluent-kafka-python/blob/baf71ea0ed54c71948208bfc5c352f4ee57054dd/src/confluent_kafka/src/confluent_kafka.c#L61, while the documentation is written in https://github.com/confluentinc/confluent-kafka-python/blob/baf71ea0ed54c71948208bfc5c352f4ee57054dd/src/confluent_kafka/src/confluent_kafka.c#L313.

How to reproduce
================
n/a

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): `('2.1.1', 33620224)`, `('2.1.1', 33620479)`
 - [x] Apache Kafka broker version: n/a
 - [x] Client configuration: n/a
 - [x] Operating system: n/a
 - [x] Provide client logs (with `'debug': '..'` as necessary): n/a
 - [x] Provide broker log excerpts: n/a
 - [ ] Critical issue

**Comment by pranavrth** [comment]
The field name is 'error'.

https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/src/confluent_kafka.c#L267

Fixed as part of one of the ongoing PR - https://github.com/confluentinc/confluent-kafka-python/pull/1582

**Comment by amues** [comment]
Ah, sorry about the `code` part, I realised now I was looking at the documentation for the constructor and missed the methods below the table of error codes.
