### ISSUE TITLE
First call to Producer.flush takes 1 second for each topic

### ISSUE THREAD

**Issue by r-owen** [confluentinc/confluent-kafka-python#1581]
Description
===========
I am trying to upgrade from confluent_kafka 1.9.2 to 2.1.1 and have a new problem: the first call to Producer.flush takes 1 second for each topic. I always create the topic (rather than relying on automatic creation) if it does not exist, and I see the same 1 second delay regardless of whether the topic already exists.

I am guessing I need additional configuration, but so far I have not been able to figure out what that might be.

How to reproduce
================

Run the attached self-contained code, after setting KAFKA_BROKER_ADDR appropriately

[minimal_write.py.zip](https://github.com/confluentinc/confluent-kafka-python/files/11715487/minimal_write.py.zip)

With confluent_kafka 2.1.1 I see the following (repeatably, even after the initial run that creates the topic)
```
minimal_write.py  -n 100  
KAFKA_BROKER_ADDR='127.0.0.1:9092'
topic 'trivial.test.topic' already exists
Create a producer with acks=0
Produce 100 messages
First flush took 1.01 seconds
Wrote 16472.8 messages/second: Namespace(number=100, partitions=1) (after the first message)
```

whereas the same command using confluent_kafka 1.9.2 (and the same exact Kafka service) gives:
```
First flush took 0.00 seconds
Wrote 17433.4 messages/second: Namespace(number=100, partitions=1) (after the first message)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):

confluent_kafka.version(): ('2.1.1', 33620224)
confluent_kafka.libversion() ('2.1.1', 33620479)
installed via conda
   
 - [x] Apache Kafka broker version:
 I am running Kafka using docker-compose and these images:
 
confluentinc/cp-enterprise-kafka            7.3.3      3f5b09fb55d3   2 months ago   984MB
confluentinc/cp-zookeeper                   7.3.3      4cd5998eddd9   2 months ago   839MB

which should be Kafka 3.3.x

 - [x] Client configuration: `{...}`
There is no client. The producer configuration is:
```
            "acks": 0,
            "queue.buffering.max.ms": 0,
            "bootstrap.servers": KAFKA_BROKER_ADDR,
```

 - [x] Operating system:
 Producer is running on macOS 13.4

 - [ ] Provide client logs (with `'debug': '..'` as necessary)
I'm not sure what to do here
 
- [ ] Provide broker log excerpts
 I'm not sure what to do here
 
 - [ ] Critical issue
No

**Comment by r-owen** [comment]
Here is the docker-compose file that I use to run Kafka. For this test I had zookeeper, broker and schema-registry running (even though I was not using the schema registry for this particular code)

[docker-compose.yaml.zip](https://github.com/confluentinc/confluent-kafka-python/files/11723533/docker-compose.yaml.zip)

**Comment by pranavrth** [comment]
I was able to check the issue. The issue is that the `KAFKA_ADVERTISED_LISTENERS` in your docker file is `localhost` but you are connecting with `127.0.0.1` in the code. If you use `localhost` to connect, then you would not face this issue.

I checking more on the exact reason. But this is my current understanding:- what's happening is inside the client, `localhost` and `127.0.0.1` are not the same brokers. When `127.0.0.1` is given as bootstrap broker, initial connection is established with it but the leader for the topic is `localhost`. And hence it waits for 1s to check for the leader again for the partition.

**Comment by r-owen** [comment]
I closed this, but should this still be open? It seems like a misfeature that might be worth fixing.

(Also for the record: using localhost everywhere didn't help my larger code base.)

**Comment by pranavrth** [comment]
I can see that v1.9.2 is working as expected. I will try to investigate on this further.

**Comment by r-owen** [comment]
Here is a simple example showing 1.0 seconds to flush even with the workaround. As far as I can tell, the significant difference is that the new example registers a schema. I also stumbled across the following bit in my code, which I have preserved in the example. I wonder if it has anything to do with the delay.
```
        # Work around
        # https://github.com/confluentinc/confluent-kafka-dotnet/issues/701
        # a 1 second delay in the first message for a topic.
        self.producer.list_topics()
```
[write_with_schema.py.zip](https://github.com/confluentinc/confluent-kafka-python/files/11737877/write_with_schema.py.zip)

When I run this new example with confluent_kafka 2.1.1 I see:
```
Make AdminClient with bootstrap.servers=localhost:9092
new_topic_list=[NewTopic(topic=lsst.test.Test.logevent_logMessage,num_partitions=1)]
Create SchemaRegistryClient with url=http://localhost:8081
Make producer with acks=1, bootstrap.servers=localhost:9092
Produce lsst.test.Test.logevent_logMessage took 0.99 seconds to flush  # note the long delay
Produce lsst.test.Test.logevent_logMessage took 0.00 seconds to flush
```
When I run it with 1.9.2 I see no such initial delay
```
...
Produce lsst.test.Test.logevent_logMessage took 0.00 seconds to flush
Produce lsst.test.Test.logevent_logMessage took 0.00 seconds to flush
```

**Comment by r-owen** [comment]
For the record: I still see this performance degradation in confluent_kafka 2.2.0 (I'm using the conda distribution -- python-confluent-kafka -- though I hope that is not relevant).

**Comment by tribeiro** [comment]
Hi @pranavrth , would it be possible to re-open this ticket? we still experience this with python-confluent-kafka=2.4.0

We are trying to upgrade our systems to python 3.12 which does not provide a build of python-confluent-kafka 1.9.2, so it is becoming a blocker for us.
