### ISSUE TITLE
How to use loguru to capture connection timeout information

### ISSUE THREAD

**Issue by helloHKTK** [confluentinc/confluent-kafka-python#1587]
Description
===========
When the kafka address is filled in incorrectly, the following code cannot capture the exception log. I want to use loguru to print logs of connection timeout. What should I do?

```python
from confluent_kafka import Consumer

c = Consumer({
    'bootstrap.servers': 'mybroker',
    'group.id': 'mygroup',
    'auto.offset.reset': 'earliest'
})

c.subscribe(['mytopic'])

while True:
    msg = c.poll(1.0)

    if msg is None:
        continue
    if msg.error():
        print("Consumer error: {}".format(msg.error()))
        continue

    print('Received message: {}'.format(msg.value().decode('utf-8')))

c.close()


```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
You can use `error_cb` property in client configuration while creating the client. Please refer [this](https://docs.confluent.io/platform/current/clients/librdkafka/html/md_CONFIGURATION.html).
