### ISSUE TITLE
Do you know if this library is appropriate to use for sending across regions?

### ISSUE THREAD

**Issue by mtrienis** [confluentinc/confluent-kafka-python#159]
A typical deployment of Kafka might include a cluster in each region where the producer applications write to the local (i.e. same region) Kafka cluster. From there you can use mirror maker to mirror the messages over to an aggregate Kafka cluster. 

However, that requires maintaining a Kafka cluster in each region (i.e. extra storage, maintenance, time costs). So would it be an appropriate use case to use this library to write directly to the aggregate Kafka cluster that lives in another region?

Do you see any problems with the additional latency of writing across regions?

**Comment by edenhill** [comment]
I know that wikimedia (the wikipedia people) are using librdkafka (the underlying C library that confluent-kafka-python uses) to produce messages from clients in europe to brokers in US data centers.

Afaik they've been doing this successfully for years now, right @ottomata?

**Comment by ottomata** [comment]
Yup!  But we also have network engineers who know how to make such things reliable(ish).  We have had occasions where network hiccups have caused librdkafka queues to fill up to the point where it has to drop messages.  Most of the time it works, but not always!

If you are sending data for analytics purposes, where lost messages aren't a huge deal, then yeah, go for it.  But, if you want to keep Kafka's at least once guarantee, and a dropped message would mean loss of a client transaction or something, then I wouldn't recommend doing this.

**Comment by mtrienis** [comment]
Thank you!
