### ISSUE TITLE
SSL Error while connecting to kafka

### ISSUE THREAD

**Issue by pyjads** [confluentinc/confluent-kafka-python#1602]
Description
===========
I receive following error:
```
%3|1688835774.635|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://datarecorder-dev.servicebus.windows.net:9093/bootstr]: sasl_ssl://queue-1209.servicebus.windows.net:9093/bootstrap: Receive failed: error:0A000126:SSL routines::unexpected eof while reading (after 600554ms in state UP)
```

How to reproduce
================
bootstrap.servers=queue-1209.servicebus.windows.net:9093
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.username=$ConnectionString
sasl.password=placeholder
group.id=$Default
enable.auto.commit=False
request.timeout.ms=60001
session.timeout.ms=60000
max.poll.interval.ms=1200000
auto.offset.reset=smallest
broker.version.fallback=1.0.0

confluent-kafka-python = 2.1.1
confluent-kakba.libversion() = 2.1.1

Apache Kafka Broker Version - Using Azure Eventhub with kafka endpoint (v1.0.0)
Operating system: linux

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
We have released v2.2.0 with the fix for this. Please check and reopen the issue if you feel it is still happening.
