### ISSUE TITLE
Consumer offset still being committed with `enable.auto.offset.store` = False

### ISSUE THREAD

**Issue by galenhwang** [confluentinc/confluent-kafka-python#1609]
Kafka version 3.3.1
`confluent_kafka`: ('2.1.1', 33620224)
`librdkafka`: ..., 33620479

Description
===========
code:
```
import asyncio
from confluent_kafka import Consumer

consumer = Consumer({
    'bootstrap.servers': 'localhost:9092',
    'group.id': 'my_group',
    'auto.offset.reset': 'earliest',
    'enable.auto.offset.store': False,
})

consumer.subscribe(["my_topic"])

# 10 messages exist in topic
for i in range(10):
    msg = consumer.consume(num_messages=1, timeout=1.0)
    print("offset is", msg[0].offset())
    if i > 4:
        print("should not consume more than 5 messages")
        continue
    consumer.store_offsets(msg[0])
    await asyncio.sleep(1)
```
prints    
```
offset is 0
offset is 1
offset is 2
offset is 3
offset is 4
offset is 5
should not consume more than 5 messages
offset is 6
should not consume more than 5 messages
offset is 7
should not consume more than 5 messages
...
```
perhaps I am missing a config somewhere?

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by galenhwang** [comment]
may be dupe of https://github.com/confluentinc/confluent-kafka-python/issues/1299

It also occurs with:
* `consumer.poll()`
* `enable.auto.commit` as False

**Comment by pranavrth** [comment]
It doesn't always check for committed offset to return messages to the application. Internally, messages are already cached and those messages are returned to the application.

Can you help me understand what do you want to achieve here? I might be able to help you better.

**Comment by galenhwang** [comment]
I want to manually update the offset myself after I consume messages. With `enable.auto.offset.store` = False, I expect to call `consumer.consume()` multiple times and return the same messages each time.

**Comment by pranavrth** [comment]
You can just use the same message again without calling `consumer.consume()`. Call `consumer.consume()` only when you are storing this offset.

**Comment by galenhwang** [comment]
this was a misunderstanding on my side. what you suggested makes sense. 

thank you for clarifying!
