### ISSUE TITLE
Add metadata() API

### ISSUE THREAD

**Issue by Ycallaer** [confluentinc/confluent-kafka-python#161]
Hi,
I am currently using confluent kafka v0.9.2 and I was wondering if it is possible to retrieve the number of partitions for a given topic.
In java you can reach this information when using org.apache.kafka.common.Cluster but does something similar exist in the python implementation ?
I've quickly browsed the python implementation but couldn't find anything similar.
One possibility is probably using kazoo and retrieve this info from zookeeper but if possible I want to avoid this.

thanks for any insight you can provide

**Comment by edenhill** [comment]
This requires the metadata API which is not yet available in the Python client.
There is a PR to add it here: https://github.com/confluentinc/confluent-kafka-python/pull/154

But it needs some loving before being merged.

**Comment by rnpridgeon** [comment]
This should be handled with the recently merged #309. It currently lives off trunk(master) but we plan to merge it with the main line soon. Closing for now
