### ISSUE TITLE
How do I describe all users using the admin client?

### ISSUE THREAD

**Issue by donovanbai-dd** [confluentinc/confluent-kafka-python#1616]
Description
===========
The `describe_user_scram_credentials` method was added to the admin client recently but I'm unable to find a way to describe all users. The equivalent Kafka CLI command for what I'm trying to do is `kafka-configs.sh --describe --entity-type users`. I also see that librdkafka supports this functionality https://github.com/confluentinc/librdkafka/blob/7cc860d4d099bfe4c53f60950189ea139a660128/src/rdkafka.h#L8716-L8717 

How to reproduce
================
I tried passing in an empty user list but it doesn't work
```
admin_client.describe_user_scram_credentials([]) # just returns empty map
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('2.2.0', 33685504) and ('2.2.0', 33685759)
 - [x] Apache Kafka broker version: 3.3.1
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Mac
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mahajanadhitya** [comment]
Will get the bug fix for Python Client merged quickly, merging may take extra 2 days. Will get back soon.
