### ISSUE TITLE
Offset Explorer's last commit time was not refreshed

### ISSUE THREAD

**Issue by DragonFangQy** [confluentinc/confluent-kafka-python#1618]
Description
===========
<img width="1460" alt="image" src="https://github.com/confluentinc/confluent-kafka-python/assets/87315637/c05d38ee-67c3-4108-aeaf-d32744d7b6bd">
<img width="1456" alt="image" src="https://github.com/confluentinc/confluent-kafka-python/assets/87315637/19335e77-4873-420f-be64-7d928f952ca2">

As shown in the figure，offset can be submitted normally，but the last commit time is never refreshed.

How to reproduce
================

`enable.auto.commit=true` or `enable.auto.commit=false` make no difference.
This does not affect the function，but it bothers me。

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 > ('2.1.1', 33620224)    and    ('2.1.1', 33620479)
 - [x] Apache Kafka broker version:
 > docker image , version: bitnami/kafka:3.5.0
 - [x] Client configuration: `{...}`
 > KAFKA_CONSUMER_CONF = { 
    "bootstrap.servers": KAFKA_BROKER,
    "group.id": KAFKA_GROUP,
    "session.timeout.ms": 6000,
    "auto.offset.reset": "latest",
    "enable.auto.offset.store": False, 
    "enable.auto.commit": True,
}
 - [x] Operating system:
>  mac:  12.3
>  Offset Explorer: version 2.3.2
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
Its not defined by the client. You can check the broker.
