### ISSUE TITLE
Python 3.12 Support

### ISSUE THREAD

**Issue by mkmoisen** [confluentinc/confluent-kafka-python#1629]
Last time when Python 3.11 was released, confluent_kafka was delayed in building the wheels. Please see the [issue](https://github.com/confluentinc/confluent-kafka-python/issues/1452) here for a long discussion on it.

Python 3.12 is [supposed](https://www.python.org/downloads/release/python-3120rc1/) to drop on October 2nd, about 1.5 months from now.

It would be great to have confluent_kafka ready for 3.12 around that time.

**Comment by pranavrth** [comment]
I will have a look at this.

**Comment by lpsinger** [comment]
Python 3.12 is now ABI stable: https://www.python.org/downloads/release/python-3120rc1/

Cibuildwheel now builds Python 3.12 wheels by default: https://cibuildwheel.readthedocs.io/en/stable/changelog/#v2150

So there should be no obstacles from the Python tooling and community side to releasing Python 3.12 wheels, even though the stable release of Python 3.12 is not yet out.

**Comment by mkmoisen** [comment]
@pranavrth @lpsinger 

Python 3.12 release candidate two just dropped a few hours ago. I received an email from python-announce mailer saying that now is the time to produce a wheel:

> There will be *no ABI changes* from this point forward in the 3.12 series.
The intent is for the final release of 3.12.0, scheduled for Monday,
2023-10-02, to be identical to this release candidate. *This is the last
chance to find critical problems in Python 3.12.*

> We strongly encourage maintainers of third-party Python projects to prepare
their projects for 3.12 compatibilities during this phase, and where
necessary publish Python 3.12 wheels on PyPI to be ready for the final
release of 3.12.0. Any binary wheels built against Python 3.12.0rc2 will
work with future versions of Python 3.12.

May we please get the 3.12 wheel ready for confluent_kafka now?

**Comment by mkmoisen** [comment]
@pranavrth @lpsinger 

Sorry to keep bumping this. We have 9 more days until Python 3.12 is released, on Tuesday October 2nd.

Would you please get the wheels ready when you have a moment?

Thanks very much!

**Comment by lpsinger** [comment]
@mkmoisen, I don't know why you are tagging me. I don't maintain this package.

**Comment by Zmrzka** [comment]
I would like to bup this, I have tested 3.12 support on our system but only confluent is blocking us. I have tried to get around some error messages by instaling librdkafka from apt but it just crashes somewhat later.

**Comment by aadant** [comment]
@pranavrth any update ?

**Comment by pranavrth** [comment]
I have raised the PR for adding 3.12 wheels. We are planning a release next week or so. It should be available in that release. 

https://github.com/confluentinc/confluent-kafka-python/pull/1649/files

**Comment by gaborbernat** [comment]
Is it still happening?

**Comment by pranavrth** [comment]
Released v2.3.0 with Python 3.12 wheels. Please check.
