### ISSUE TITLE
Can I control num_partitions, replication factor, when I produce to a new topic?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#163]
By default, my kafka broker will auto-create a new topic as soon as I produce to it. It will apply its configured defaults to decide how many partitions it should have, and what its replication factor should be. Is there a way to control this kind of thing explicitly from the producer client at the time I publish to the new topic?

Also, will the eventual resolution of https://github.com/confluentinc/confluent-kafka-python/issues/161 allow us to read the replication factor as well as the number of partitions?

**Comment by edenhill** [comment]
Yes and no!
The recent addition of [KIP-4](https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations) adds protocol support for creating topics with specific configuration.

That feature has not yet landed in librdkafka or its sibblings yet though, but it will, eventually.

For now I suggest pre-creating your topics with kafka-topics.sh.

While the replication factor itself will not be exposed as a gettable in KIP-4, it might be possible to derive it from metadata looking at the replica set for a topic.

**Comment by davideberra** [comment]
Hi Magnus! 
in the end... did you introduce the chance to create topics with a specific configuration? it would be very useful

**Comment by rnpridgeon** [comment]
@davideberra this will be included in the 0.11.5 release which should be available by next week. As soon as the librdkafka 0.11.5 release is cut we will get this one released as well. 

https://github.com/confluentinc/confluent-kafka-python/releases

**Comment by edenhill** [comment]
Example here: https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/adminapi.py#L34
