### ISSUE TITLE
Expose seek functionality

### ISSUE THREAD

**Issue by davidblewett** [confluentinc/confluent-kafka-python#164]
I was looking for a method of rewinding a given consumer group's offset in a given topic by using https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-HowcanIrewindtheoffsetintheconsumer? , but didn't find it immediately obvious. The Go wrapper exposes the "seek" interface ( https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/consumer.go#L197 ), but I don't see something similar in the Python binding.

**Comment by davidblewett** [comment]
For context, this functionality would be used in a controlled maintenance window. I.e., we stop all members of the consumer group, run a script to rewind their offsets, then restart everything.

**Comment by edenhill** [comment]
Until seek() is added to the Python client you can use assign() by specifying each partition's offset.

**Comment by davidblewett** [comment]
@edenhill I think I tried that, but it didn't seem to "stick". What's the correct method to check the stored value then?

**Comment by edenhill** [comment]
Do you want to rewind a running consumer, or the committed offsets?

**Comment by davidblewett** [comment]
The desired effect is to rewind where a given consumer group is in a topic. The least error prone method I thought would be to stop all consumer processes in the group, run a script to rewind the committed offset for each parttion, then restart all consumer processes.

Our previous environment was using ZooKeeper-based offsets. In that environment, we would stop the group, issue ZooKeeper commands to rewind the offset, then restart the group.

**Comment by edenhill** [comment]
You could do the same using committed() (to get the committed offsets) and commit() (to rewrite the offsets).

**Comment by craigtmoore** [comment]
I was able to do it by unassigning and then reassigning the consumer at a given offset, using the topic partition. Example:

` consumer.commit(offsets=[topic_partition], async=False)`
`consumer.unassign()`
`topic_partition.offset = 0`
`consumer.assign([topic_partition])`

**Comment by affansyed** [comment]
@edenhill when is this feature actually be the "next feature"? if no one is taking up, can you point to where in the code one can look at to help and fix?

**Comment by edenhill** [comment]
PR here: https://github.com/confluentinc/confluent-kafka-python/pull/312

**Comment by edenhill** [comment]
Available in v0.11.4
