### ISSUE TITLE
segfault in AdminClient.delete_consumer_groups 

### ISSUE THREAD

**Issue by elbaro** [confluentinc/confluent-kafka-python#1640]
Description
===========

waiting for futures returned by AdminClient.delete_consumer_groups() fails assertions.

How to reproduce
================

```py
def reset(conf):
    admin_client = AdminClient(conf)
    futures: dict[str, _] = admin_client.delete_consumer_groups([CONSUMER_GROUP])
    for _consumer, future in futures.items():
        future.result()  # panics

reset({"bootstrap.servers": bootstrap_servers})
```

```sh
python3.11: rdkafka_queue.h:1052: rd_kafka_enq_once_del_source_return: Assertion `eonce->refcnt > 0'
failed.
Aborted                 (core dumped) python3.11 my_script.py
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
   - version = ('2.2.0', 33685504)
 - [ ] Apache Kafka broker version:
   - cluster version 0.1
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
Can you please explain little more as in which condition this issue is happening?
Can you provide the debug logs as well? You can enable debug logs using config `'debug': 'admin'`.

**Comment by nhaq-confluent** [comment]
@elbaro Wanted to follow up for @pranavrth's request for some more information that could help us evaluate later. 

If this issue is no longer needed, please advise so we can close. Thank you!

**Comment by elbaro** [comment]
Closing this as I no longer work on this
