### ISSUE TITLE
Missing docs?

### ISSUE THREAD

**Issue by jawnb** [confluentinc/confluent-kafka-python#165]
As of 3.2.0 the docs for the various classes are missing here: http://docs.confluent.io/3.2.0/clients/confluent-kafka-python/#topicpartition

Compared to the full docs http://docs.confluent.io/3.0.1/clients/confluent-kafka-python/#topicpartition

**Comment by edenhill** [comment]
Ouch, I wonder what happened there.

Thanks for letting us know!

**Comment by demowl** [comment]
@edenhill Maybe the above problem has been solved at a certain point, but now the docs seem to be _very_ empty: http://docs.confluent.io/3.2.1/clients/confluent-kafka-python/.
I can't find what could have caused this change though.

**Comment by edenhill** [comment]
@demowl Yikes, thanks, looking.

**Comment by demowl** [comment]
Any news on this? I would really like to check the `Producer` docs.

**Comment by edenhill** [comment]
This is on our immediate roadmap to fix.

Until then you can build the docs yourself by checking out the confluent-kafka-python git repository and then doing:

    $ pip install sphinx sphinx_rtd_theme
    $ make docs

The documentation is then available in docs/_build/html

**Comment by maxzheng** [comment]
Docs are fixed now. We will look into adding a validation step to ensure this doesn't happen again.
Sorry for the inconvenience @demowl and @jawnb and thanks for reporting it @jawnb

**Comment by jawnb** [comment]
Thanks Max.
