### ISSUE TITLE
certificate verify failed in Linux, but worked in windows.

### ISSUE THREAD

**Issue by DonkeyJason** [confluentinc/confluent-kafka-python#1651]
Description
===========
My configuration is as follows.
It's worked in windows PC.
But when it's deployed in Linux server, will occur "SSL: CERTIFICATE_VERIFY_FAILED".

The tricky thing is I need to add more than 10 CA files, so I just copy & paste to one CA file.

schema_registry_client = SchemaRegistryClient({
        'url': kafka_setting["schema_url"],
        "ssl.ca.location": kafka_setting['ca_location'],
        "basic.auth.user.info": f"""{kafka_setting['sasl_plain_username']}:{kafka_setting['sasl_plain_password']}"""
    })

    avro_deserializer = AvroDeserializer(schema_registry_client)

    consumer_conf = {
        'bootstrap.servers': kafka_setting['bootstrap_servers'],
        'sasl.mechanisms': 'PLAIN',
        'ssl.ca.location': kafka_setting['ca_location'],
        'security.protocol': 'SASL_SSL',
        'sasl.username': kafka_setting['sasl_plain_username'],
        'sasl.password': kafka_setting['sasl_plain_password'],
        'group.id': kafka_setting['group_name'],
        'auto.offset.reset': "earliest"
    }
    consumer = Consumer(consumer_conf)
    consumer.subscribe([kafka_setting['topic_name']])

Bug: Max retries exceeded with url: /ccloud-schema-registry/prod/schemas/ids/2002 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka(1.9.2), 
 - [ ] Apache Kafka broker version: 
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:  Docker Image: FROM python:3.8-slim-buster
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
Does CA location for Schema Registry is also `kafka_setting['ca_location']`? I think this is the culprit. Try without this setting?

```
schema_registry_client = SchemaRegistryClient({
'url': kafka_setting["schema_url"],
"ssl.ca.location": kafka_setting['ca_location'],
"basic.auth.user.info": f"""{kafka_setting['sasl_plain_username']}:{kafka_setting['sasl_plain_password']}"""
})
```

**Comment by DonkeyJason** [comment]
@pranavrth Many Many Many Many Many thanks!!! It's worked!!!
