### ISSUE TITLE
Cannot install confluent-kafka with pip on Mac

### ISSUE THREAD

**Issue by ellatorfa** [confluentinc/confluent-kafka-python#166]
On macOS Sierra:
Installing confluent-kafka with pip fails on  "'librdkafka/rdkafka.h' file not found" even though librdkafka 0.9.4 is already installed.

I've tried uninstalling and reinstalling librdkafka using brew and it doesn't help.

**$ brew --version**
Homebrew 1.1.11
Homebrew/homebrew-core (git revision 30c4e; last commit 2017-03-31)

**$ pip --version**
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)

**$ python --version**
Python 2.7.12

**$ brew list librdkafka**
/usr/local/Cellar/librdkafka/0.9.4/include/librdkafka/ (2 files)
/usr/local/Cellar/librdkafka/0.9.4/lib/librdkafka++.1.dylib
/usr/local/Cellar/librdkafka/0.9.4/lib/librdkafka.1.dylib
/usr/local/Cellar/librdkafka/0.9.4/lib/pkgconfig/ (2 files)
/usr/local/Cellar/librdkafka/0.9.4/lib/ (4 other files)

**$ pip install confluent-kafka**
Collecting confluent-kafka
  Using cached confluent-kafka-0.9.4.tar.gz
Installing collected packages: confluent-kafka
  Running setup.py install for confluent-kafka ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/th/pkc5plrj2ss47rpqcc08wfvs_2t9hp/T/pip-build-TwY6hX/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/th/pkc5plrj2ss47rpqcc08wfvs_2t9hp/T/pip-5ZUwHl-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-intel-2.7
    creating build/lib.macosx-10.12-intel-2.7/confluent_kafka
    copying confluent_kafka/__init__.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka
    creating build/lib.macosx-10.12-intel-2.7/confluent_kafka/avro
    copying confluent_kafka/avro/__init__.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka/avro
    copying confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka/avro
    creating build/lib.macosx-10.12-intel-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/__init__.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_client.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka/kafkatest
    creating build/lib.macosx-10.12-intel-2.7/confluent_kafka/avro/serializer
    copying confluent_kafka/avro/serializer/__init__.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka/avro/serializer
    copying confluent_kafka/avro/serializer/message_serializer.py -> build/lib.macosx-10.12-intel-2.7/confluent_kafka/avro/serializer
    running build_ext
    building 'confluent_kafka.cimpl' extension
    creating build/temp.macosx-10.12-intel-2.7
    creating build/temp.macosx-10.12-intel-2.7/confluent_kafka
    creating build/temp.macosx-10.12-intel-2.7/confluent_kafka/src
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c confluent_kafka/src/confluent_kafka.c -o build/temp.macosx-10.12-intel-2.7/confluent_kafka/src/confluent_kafka.o
    In file included from confluent_kafka/src/confluent_kafka.c:17:
    confluent_kafka/src/confluent_kafka.h:21:10: fatal error: 'librdkafka/rdkafka.h' file not found
    #include <librdkafka/rdkafka.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/th/pkc5plrj2ss47rpqcc08wfvs_2t9hp/T/pip-build-TwY6hX/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/th/pkc5plrj2ss47rpqcc08wfvs_2t9hp/T/pip-5ZUwHl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/th/pkc5plrj2ss47rpqcc08wfvs_2t9hp/T/pip-build-TwY6hX/confluent-kafka/
$

**Comment by edenhill** [comment]
Thanks for a great report!

It seems as if pip/setup.py is not using the correct include path, can you try this:
`pip install --global-option=build_ext --global-option="-I/usr/local/Cellar/librdkafka/0.9.4/include" --global-option="-L/usr/local/Cellar/librdkafka/0.9.4/lib"  confluent-kafka`

**Comment by ellatorfa** [comment]
Thanks for a very quick response @edenhill !
This worked like a charm with adding --user as well:
pip install --global-option=build_ext --global-option="-I/usr/local/Cellar/librdkafka/0.9.4/include" --global-option="-L/usr/local/Cellar/librdkafka/0.9.4/lib" --user  confluent-kafka

**Comment by jaredwilli** [comment]
@edenhill That did not work for me, I'm getting the same error. Any ideas?

```JAREDW-M-Q1F4:platform-core jaredw$ pip install --global-option=build_ext --global-option="-I/usr/local/Cellar/librdkafka/0.9.4/include" --global-option="-L/usr/local/Cellar/librdkafka/0.9.4/lib" confluent-kafka
/usr/local/lib/python2.7/site-packages/pip/commands/install.py:180: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting confluent-kafka
  Downloading https://artifactory.cloudlock.com/api/pypi/pypi/packages/96/36/516a2b7f592376968296d10de10a20f1ce411e5ff24a86b1a23d5a5f4042/confluent-kafka-0.11.0.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 4.5MB/s 
Skipping bdist_wheel for confluent-kafka, due to binaries being disabled for it.
Installing collected packages: confluent-kafka
  Running setup.py install for confluent-kafka ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/0f/hgmxd5js68dbszj_mchvx2bh0000gn/T/pip-build-fRh1JI/confluent-kafka/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" build_ext -I/usr/local/Cellar/librdkafka/0.9.4/include -L/usr/local/Cellar/librdkafka/0.9.4/lib install --record /var/folders/0f/hgmxd5js68dbszj_mchvx2bh0000gn/T/pip-oNYUkV-record/install-record.txt --single-version-externally-managed --compile:
    running build_ext
    building 'confluent_kafka.cimpl' extension
    creating build
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/confluent_kafka
    creating build/temp.macosx-10.11-x86_64-2.7/confluent_kafka/src
    clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/librdkafka/0.9.4/include -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c confluent_kafka/src/confluent_kafka.c -o build/temp.macosx-10.11-x86_64-2.7/confluent_kafka/src/confluent_kafka.o
    In file included from confluent_kafka/src/confluent_kafka.c:17:
    confluent_kafka/src/confluent_kafka.h:21:10: fatal error: 'librdkafka/rdkafka.h' file not found
    #include <librdkafka/rdkafka.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/0f/hgmxd5js68dbszj_mchvx2bh0000gn/T/pip-build-fRh1JI/confluent-kafka/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" build_ext -I/usr/local/Cellar/librdkafka/0.9.4/include -L/usr/local/Cellar/librdkafka/0.9.4/lib install --record /var/folders/0f/hgmxd5js68dbszj_mchvx2bh0000gn/T/pip-oNYUkV-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/0f/hgmxd5js68dbszj_mchvx2bh0000gn/T/pip-build-fRh1JI/confluent-kafka/
```

**Comment by edenhill** [comment]
@jaredwilli which version of librdkafka do you have installed? Note the version number in the include path and modify it to your installed version:

```
pip install --global-option=build_ext --global-option="-I/usr/local/Cellar/librdkafka/0.9.4/include" --global-option="-L/usr/local/Cellar/librdkafka/0.9.4/lib" confluent-kafka
```

**Comment by puneetlakhina** [comment]
FYI for anyone on OSX who runs into this issue, if you use homebrew you can do the following

1. `brew install librdkafka`
2. `pip install confluent_kafka`

**Comment by giannisp** [comment]
Using the latest `pipenv`, I had to do:  
`pipenv run pip install --global-option=build_ext --global-option="-I/usr/local/Cellar/librdkafka/0.11.3/include" --global-option="-L/usr/local/Cellar/librdkafka/0.11.3/lib" confluent-kafka`

**Comment by shibicr93** [comment]
I had the same issue, after usingt he latest confluent-kafka and librdkafka 1.8.2 the issue got resolved!

**Comment by vinnyyo** [comment]
I am having the same issue. I have librdkafka 1.8.2, python 3.10.4, and macOS Monterey 12.3.1 and an M1 mac chip
I tried 
`pip3 install --global-option=build_ext --global-option="-I/usr/local/Cellar/librdkafka/1.8.2/include" --global-option="-L/usr/local/Cellar/librdkafka/1.8.2/lib" --user confluent-kafka`
and i still get
`
WARNING: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
Collecting confluent-kafka
  Using cached confluent-kafka-1.8.2.tar.gz (104 kB)
  Preparing metadata (setup.py) ... done
Skipping wheel build for confluent-kafka, due to binaries being disabled for it.
Installing collected packages: confluent-kafka
  Running setup.py install for confluent-kafka ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for confluent-kafka did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running build_ext
      building 'confluent_kafka.cimpl' extension
      creating build
      creating build/temp.macosx-10.9-universal2-3.10
      creating build/temp.macosx-10.9-universal2-3.10/private
      creating build/temp.macosx-10.9-universal2-3.10/private/var
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka
      creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/usr/local/Cellar/librdkafka/1.8.2/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src/Admin.c -o build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src/Admin.o
      In file included from /private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src/Admin.c:17:
      /private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: 'librdkafka/rdkafka.h' file not found
      #include <librdkafka/rdkafka.h>
               ^~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> confluent-kafka

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
`
WHAT DO I DO?!

**Comment by vinnyyo** [comment]
> I am having the same issue. I have librdkafka 1.8.2, python 3.10.4, and macOS Monterey 12.3.1 and an M1 mac chip I tried `pip3 install --global-option=build_ext --global-option="-I/usr/local/Cellar/librdkafka/1.8.2/include" --global-option="-L/usr/local/Cellar/librdkafka/1.8.2/lib" --user confluent-kafka` and i still get
> 
> `WARNING: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option. Collecting confluent-kafka Using cached confluent-kafka-1.8.2.tar.gz (104 kB) Preparing metadata (setup.py) ... done Skipping wheel build for confluent-kafka, due to binaries being disabled for it. Installing collected packages: confluent-kafka Running setup.py install for confluent-kafka ... error error: subprocess-exited-with-error
> 
> × Running setup.py install for confluent-kafka did not run successfully. │ exit code: 1 ╰─> [22 lines of output] running build_ext building 'confluent_kafka.cimpl' extension creating build creating build/temp.macosx-10.9-universal2-3.10 creating build/temp.macosx-10.9-universal2-3.10/private creating build/temp.macosx-10.9-universal2-3.10/private/var creating build/temp.macosx-10.9-universal2-3.10/private/var/folders creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6 creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144 creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/usr/local/Cellar/librdkafka/1.8.2/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src/Admin.c -o build/temp.macosx-10.9-universal2-3.10/private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src/Admin.o In file included from /private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src/Admin.c:17: /private/var/folders/hb/6cg7wxxs199g90g1_vnwxf6r0000gp/T/pip-install-8_y_aor6/confluent-kafka_d1a7af803fe24d0896e67404ead91144/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: 'librdkafka/rdkafka.h' file not found #include <librdkafka/rdkafka.h> ^~~~~~~~~~~~~~~~~~~~~~ 1 error generated. error: command '/usr/bin/clang' failed with exit code 1 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure
> 
> × Encountered error while trying to install package. ╰─> confluent-kafka
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.` WHAT DO I DO?!

This is what fixed it, it was a problem with the m1 chip.

**Comment by AssetOverflow** [comment]
Hi, I had this issue installing on Mac OSX Monterey M1 Pro - went through all of these solutions and found this to be the best

--global-option=build_ext --global-option="-I/opt/homebrew/Cellar/librdkafka/1.9.1/include" --global-option="-L/opt/homebrew/Cellar/librdkafka/1.9.1/lib" confluent-kafka

i even simply add this to my "requirements .txt" (for my personal projects) 
because I am using virtual environments and had issues trying to install it each time i had requirements.txt.

so my requirements.txt looks like this lol.

starts below this line
-----------------------------------------

--global-option=build_ext --global-option="-I/opt/homebrew/Cellar/librdkafka/1.9.1/include" --global-option="-L/opt/homebrew/Cellar/librdkafka/1.9.1/lib" confluent-kafka
fastavro==1.4.11
fastapi[all]== 0.75.1
python-dotenv==0.20.0
Faker==13.3.4

-----------------------------------------
ends above this line
