### ISSUE TITLE
from confluent_kafka.avro import AvroProducer class Deprecated. what does it mean ?

### ISSUE THREAD

**Issue by sawan-tamang** [confluentinc/confluent-kafka-python#1700]
We have been using below classes in prod for a long time, and I just noticed in the confluent documentation that they have been Deprecated ?

confluent_kafka.avro import AvroProducer
confluent_kafka.avro import AvroConsumer

Here is the documentation URL I am referring to:
https://docs.confluent.io/platform/7.5/clients/confluent-kafka-python/html/index.html#avroproducer-legacy 

**Questions:**
What impacts it will have if it is removed by confluent? 
Does removing means it will never be upgraded or updated by confluent but if someone is using for a while they can keep using it without an impact? 

please help.

**Comment by pranavrth** [comment]
> What impacts it will have if it is removed by confluent?

It is not maintained actively by confluent. It will be removed in next major version release.

> Does removing means it will never be upgraded or updated by confluent but if someone is using for a while they can keep using it without an impact?

Ideally, we won't upgrade or fix issue on these deprecated classes. If you are using it, you can continue using it but it won't be supported. There are alternatives that you can use like AvroSerializer and AvroDeserializer with producer and consumer.
