### ISSUE TITLE
V2.3.0 not support python2.7.8

### ISSUE THREAD

**Issue by ING-XIAOJIAN** [confluentinc/confluent-kafka-python#1714]
Description
===========

confluent-kafka-python v2.3.0 exists python3 grammar result in error in python2.7.8
code path:  src/confluent_kafka/_model/__init__.py
![image](https://github.com/confluentinc/confluent-kafka-python/assets/31104990/16f1a0c3-8d67-4877-ab75-290c83ed3094)
![image](https://github.com/confluentinc/confluent-kafka-python/assets/31104990/7be0c310-c3c3-4273-b4e7-f022bf407abc)

How to reproduce
================
in python2.7.8 use v2.3.0
any one encounter this issue？

**Comment by johng** [comment]
You should not sure python 2.7
