### ISSUE TITLE
Producer in child process not sending messages

### ISSUE THREAD

**Issue by ajrgrubbs** [confluentinc/confluent-kafka-python#172]
I was looking into using python's multiprocessing library to handle producing messages from a child process. However, it seems that messages are not being sent when produced from a child process. My (simplified) setup:

```python
import multiprocessing

from confluent_kafka import Producer


class MyProducer(multiprocessing.Process):
    def __init__(self, kafka_bootstrap: str, kafka_topic: str, queue: multiprocessing.JoinableQueue):
        multiprocessing.Process.__init__(self)
        self.daemon = True
        self.kafka_topic = kafka_topic
        conf = {
            'bootstrap.servers': kafka_bootstrap,
            'api.version.request': True
        }
        self.producer = Producer(**conf)
        self.queue = queue

    def run(self):
        while True:
            msg = self.queue.get()
            if msg is None:
                print('Shutting down child process...')
                break
            self.producer.produce(self.kafka_topic, msg)
            print('flushing')
            self.producer.flush()  # Added in temporarily to show this issue
            print('flushed')  # Never prints
            self.queue.task_done()

if __name__ == '__main__':
    msg_queue = multiprocessing.JoinableQueue()
    child = MyProducer('localhost:9092', 'mytopic', msg_queue)
    child.start()

    messages = ['M1', 'M2', 'M3', None]
    for m in messages:
        msg_queue.put(m)

    msg_queue.join()
```

The above prints the output `flushing`, but never prints `flushed`.

If, instead of forking off a child process, I take the logic of `MyProducer.run()` and execute it in the main process instead, the script works as expected. Any insight into what's happening here?

**Comment by edenhill** [comment]
librdkafka, the underlying C library that implements the actual Kafka client, uses background threads, but threads will not survive a fork, so when your script forks off a copy of itself the child processes' client will not function.

I suggest you create the Producer in the child process.
