### ISSUE TITLE
future is done but cannot return result() in delete_topics

### ISSUE THREAD

**Issue by ttnicoleau** [confluentinc/confluent-kafka-python#1720]
Description
===========
confluent-kafka-python version: 2.3.0
python version: Python 3.11.5 

I tried to delete topics via `delete_topics` and it always returns errors when I try to get the result
the `f.result` always returns error no matter how long it waits

How to reproduce
================
``` 
  try:
    topic = NewTopic(channel_name)
    fs = admin_client.delete_topics([topic], operation_timeout=30)
    # Wait for operation to finish.
    for topic, f in fs.items():
      try:
          #f.result()  # The result itself is None
          while f.running():
            print("still running?  {} ".format(f))
            time.sleep(1)
          while f.done() is False:
            time.sleep(1)
            print("Not done?")
          print ('Done: {}'.format(f.done()))
    
          print("Result result?  {} ".format(f.result()))
          print("Topic {} deleted".format(topic))
      except Exception as e:
          print(" inside Failed to delete topic {}: {}".format(topic, e))

  except Exception as e:
      logging.error("Failed to delete topic -  {}: {}".format(channel_name, e))
      sys.exit(2)
```

Error output:
```
Processing ...
still running?  <Future at 0x105289150 state=running>
Done: True
 inside Failed to delete topic NewTopic(topic=test-channel-0): Topic NewTopic(topic=test-channel-0) not found in future-map: {NewTopic(topic=test-channel-0): <Future at 0x105289150 state=running>}
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ttnicoleau** [comment]
does anyone can give an advice?

**Comment by pranavrth** [comment]
`delete_topics` function takes list of topic names as string as input. Have you tried that?

https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#pythonclient-adminclient

**Comment by ttnicoleau** [comment]
thank you for your effort! You're right, I made a dump mistake
