### ISSUE TITLE
TopicCollection is missing in __all__

### ISSUE THREAD

**Issue by pavelschon** [confluentinc/confluent-kafka-python#1732]
Importing TopicCollection as
```
from confluent_kafka import TopicCollection
```

raises:
```
error: Module "confluent_kafka" has no attribute "TopicCollection"
```

The type is not listed in `__all__` at
https://github.com/confluentinc/confluent-kafka-python/blob/5a87879681d28375a55203c4839338b13b668046/src/confluent_kafka/__init__.py#L25

**Comment by pranavrth** [comment]
I am not facing this issue. Can you please provide the output of `confluent_kafka.version()` command and also the python version you are using.

**Comment by pavelschon** [comment]
I'm sorry, this was not ImportError, but mypy's complaint:
```
error: Module "confluent_kafka" does not explicitly export attribute "TopicCollection"  [attr-defined]
```

Python: 3.12.1
Confluent-Kafka version: ('2.3.0', 33751040)

**Comment by pranavrth** [comment]
Got it. I will investigate and update here. No harm in adding in __all__ though. Will raise a PR soon.
