### ISSUE TITLE
Cannot install confluent-kafka with pip on Mac

### ISSUE THREAD

**Issue by Lunatictwo** [confluentinc/confluent-kafka-python#174]
On **OS X EI Capitan**:
There are the configurations :
**$ brew --version**
Homebrew 1.1.12
Homebrew/homebrew-core (git revision d679; last commit 2017-04-10)

**$ pip --version**
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)

**$ python --version**
Python 2.7.10

**$ brew list librdkafka**
/usr/local/Cellar/librdkafka/0.9.4_1/include/librdkafka/ (2 files)
/usr/local/Cellar/librdkafka/0.9.4_1/lib/librdkafka++.1.dylib
/usr/local/Cellar/librdkafka/0.9.4_1/lib/librdkafka.1.dylib
/usr/local/Cellar/librdkafka/0.9.4_1/lib/pkgconfig/ (2 files)
/usr/local/Cellar/librdkafka/0.9.4_1/lib/ (4 other files)

**Then I got error:**

**$ sudo pip install confluent-kafka**
`Collecting confluent-kafka
  Downloading confluent-kafka-0.9.4.tar.gz (40kB)
    100% |################################| 40kB 37kB/s
Installing collected packages: confluent-kafka
  Running setup.py install for confluent-kafka ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-eFYkWE/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-79BW0i-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-intel-2.7
    creating build/lib.macosx-10.11-intel-2.7/confluent_kafka
    copying confluent_kafka/__init__.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka
    creating build/lib.macosx-10.11-intel-2.7/confluent_kafka/avro
    copying confluent_kafka/avro/__init__.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka/avro
    copying confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka/avro
    creating build/lib.macosx-10.11-intel-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/__init__.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_client.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka/kafkatest
    creating build/lib.macosx-10.11-intel-2.7/confluent_kafka/avro/serializer
    copying confluent_kafka/avro/serializer/__init__.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka/avro/serializer
    copying confluent_kafka/avro/serializer/message_serializer.py -> build/lib.macosx-10.11-intel-2.7/confluent_kafka/avro/serializer
    running build_ext
    building 'confluent_kafka.cimpl' extension
    creating build/temp.macosx-10.11-intel-2.7
    creating build/temp.macosx-10.11-intel-2.7/confluent_kafka
    creating build/temp.macosx-10.11-intel-2.7/confluent_kafka/src
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c confluent_kafka/src/confluent_kafka.c -o build/temp.macosx-10.11-intel-2.7/confluent_kafka/src/confluent_kafka.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c confluent_kafka/src/Producer.c -o build/temp.macosx-10.11-intel-2.7/confluent_kafka/src/Producer.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c confluent_kafka/src/Consumer.c -o build/temp.macosx-10.11-intel-2.7/confluent_kafka/src/Consumer.o
    cc -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.11-intel-2.7/confluent_kafka/src/confluent_kafka.o build/temp.macosx-10.11-intel-2.7/confluent_kafka/src/Producer.o build/temp.macosx-10.11-intel-2.7/confluent_kafka/src/Consumer.o -lrdkafka -o build/lib.macosx-10.11-intel-2.7/confluent_kafka/cimpl.so
    ld: warning: ignoring file /usr/local/lib/librdkafka.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/librdkafka.dylib
    running install_lib
    copying build/lib.macosx-10.11-intel-2.7/confluent_kafka/cimpl.so -> /Library/Python/2.7/site-packages/confluent_kafka
    running install_data
    copying LICENSE -> /System/Library/Frameworks/Python.framework/Versions/2.7/
    error: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/LICENSE'

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-eFYkWE/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-79BW0i-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-eFYkWE/confluent-kafka/`

**Comment by edenhill** [comment]
> `running install_data
copying LICENSE -> /System/Library/Frameworks/Python.framework/Versions/2.7/
error: [Errno 1] Operation not permitted: `

This looks like a permission problem.
Try installing to your local user instead with `pip install --user confluent_kafka` or create a virtualenv and install from within it.

**Comment by Lunatictwo** [comment]
@edenhill thanks,you save my day!
