### ISSUE TITLE
confluent-kafka does not build on PyPy

### ISSUE THREAD

**Issue by lpsinger** [confluentinc/confluent-kafka-python#1747]
Description
===========

This package does not build on PyPy because it uses `PyException_HEAD` which does not exist in the PyPy headers.

How to reproduce
================

See https://github.com/conda-forge/python-confluent-kafka-feedstock/pull/85

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
We support CPython based pythons and which are compatible with CPython. PyPy is not compatible with CPython.

**Comment by pranavrth** [comment]
Closing this issue.
