### ISSUE TITLE
Support comma-separated list of schema registry URLs

### ISSUE THREAD

**Issue by morrone** [confluentinc/confluent-kafka-python#1756]
Description
===========

It would be nice if the SchemaRegistryClient() support a "url" string which is a comma-separated list of schema registry URLs instead of just a single schema registry URL. I believe that libserdes supports a comma-separated list in schema.registry.url (see [libserdes README](https://github.com/confluentinc/libserdes/blob/master/README.md)).

How to reproduce
================

Try putting a comma-separated string of URLs as the value of the "url" configuration option.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by vivekkoya** [comment]
Hello, I would like to take up this task. Can you please point me to the relevant files and directories?

Thanks for the help

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1866
