### ISSUE TITLE
Python 3.13 Support for October 1st 2024

### ISSUE THREAD

**Issue by mkmoisen** [confluentinc/confluent-kafka-python#1768]
Description
===========
When Python 3.11 and Python3.12 came out, it took some time before `confluent_kafka` was compatible. 

Python 3.13 is supposed to drop on [October 1st](https://peps.python.org/pep-0719/), 2024, about 3 months from now.

As of now the ABI is stable and will not have any changes.

It would be really great if Confluent could have `confluent_kafka` ready for Python3.13 the day it comes out so we don't have to wait.

Thank you.

@pranavrth

**Comment by pranavrth** [comment]
I will have this in my Radar. Thanks for reminding this to us.

**Comment by mkmoisen** [comment]
Hi @pranavrth do you know if we are on schedule to support Python 3.13 by Oct 1st? Thanks.

**Comment by Lancetnik** [comment]
> I will have this in my Radar. Thanks for reminding this to us.

Hello there! Have you any updates on it?

**Comment by pranavrth** [comment]
Published [v2.6.0](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v2.6.0) with [Python 3.13 wheels](https://pypi.org/project/confluent-kafka/). Closing this issue. Please raise a new issue if you face any problem.
