### ISSUE TITLE
kafka consume one message and stop listening

### ISSUE THREAD

**Issue by ishitat** [confluentinc/confluent-kafka-python#177]
Hi,

I want to achieve something like this. Consumer connect to kafka node. Fetch a message (If exists) and return.

How can I do it with this lib?

**Comment by edenhill** [comment]
Look at the consumer example and modify it to exit after the first message has been received or the PARTITION_EOF event:

https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/consumer.py#L100
