### ISSUE TITLE
v2.5.0 breaking on Docker build with AWS Lambda Python 3.11

### ISSUE THREAD

**Issue by gleake-reorg** [confluentinc/confluent-kafka-python#1779]
Description
===========

Previously I used `confluent-kafka v2.4.0` and was able to build my image using the following, without any issues:

`FROM public.ecr.aws/lambda/python:3.11`

Once bumped to `v2.5.0`, the build started failing with the following:

```plaintext
26.68 Failed to build confluent-kafka
26.68 ERROR: Could not build wheels for confluent-kafka, which is required to install pyproject.toml-based projects
```

I downgraded back to `v2.4.0` and everything built/worked fine without any problems. The only change made was v2.5.0 -> v2.4.0.

How to reproduce
================

Use the above AWS Lambda Python 3.11 image and try to build with confluent-kafka v2.5.0

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emasab** [comment]
That version of `public.ecr.aws/lambda/python` has glibc 2.26. We now use for building `manylinux_2_28` that corresponds to glibc 2.28 and these distro versions.

```
Debian 10+
Ubuntu 18.10+
Fedora 29+
CentOS/RHEL 8+
```

You can use `public.ecr.aws/lambda/python:3.12` that is based on Amazon Linux 2022 and has glibc 2.34, otherwise you need to build from source.

`manylinux2014` cannot be used anymore as it's based on CentOS 7 that is EOL and doesn't receive public security updates.

**Comment by gleake-reorg** [comment]
Thanks so much for the quick response!! That's super helpful, really appreciate it 🎉

**Comment by phanicode** [comment]
@gleake-reorg can you please share a docker makefile or some way to replicate python 3.12 lambda function. I keep getting librkafka errors. Thanks a ton!

**Comment by ujjwal-m1208** [comment]
> @gleake-reorg 
same could you please provide dockerfile for 3.12 lambda function.

**Comment by pcollinscode** [comment]
> > [@gleake-reorg](https://github.com/gleake-reorg)
> > same could you please provide dockerfile for 3.12 lambda function.

replace `<YOUR APP NAME>` with the directory where your code lives.

Once you bump the lambda image to 3.12 you no longer need to install librdkafka or gcc

```
FROM public.ecr.aws/lambda/python:3.12 AS base

ENV PATH=${PATH}:/root/.local/bin \
    PYTHONPATH=${LAMBDA_TASK_ROOT}/<YOUR APP NAME> \
    POETRY_VERSION=2.1.3

RUN curl -sSL https://install.python-poetry.org | python - && \
    poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ${LAMBDA_TASK_ROOT}

COPY ./lambda_data_loader ${LAMBDA_TASK_ROOT}/<YOUR APP NAME>/

RUN poetry install --only main

FROM base AS prod

CMD [ "main.handler" ]

FROM base AS dev

COPY ./tests ${LAMBDA_TASK_ROOT}/tests/

RUN poetry install --with dev

CMD [ "main.handler" ]
```
