### ISSUE TITLE
How to Integrate Keytab/truststore/jass.conf/krb5.conf

### ISSUE THREAD

**Issue by bgayathri** [confluentinc/confluent-kafka-python#178]
Is there a way to integrate the usage of these files along with the producer code using python?
(In java it has been done using system.properties)

Files:
krb5.conf
kafka.client.jaas.conf
truststore.jks
keytab file

**Comment by edenhill** [comment]
Not directly, but almost.
Follow this guide to configure the librdkafka based Python client:
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

**Comment by bgayathri** [comment]
Thanks for the reply.

Should I do something like below to add all the configurations?
conf = {'bootstrap.servers': 'mybroker.com',
        'group.id': 'mygroup', 'session.timeout.ms': 6000,
        'on_commit': my_commit_callback,
        'default.topic.config': {'auto.offset.reset': 'smallest'}}
from confluent_kafka import Producer
p = Producer(**conf)

**Comment by edenhill** [comment]
Yes, exactly, the configuration properties on the librdkafka wiki corresponds to the dict's keys & values that you pass to Producer()

**Comment by bgayathri** [comment]
Is there a git page that I can follow to enable SASL_SSL in librdkafka?

command - 'security.protocol': 'SASL_SSL'
Error - cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Invalid value for configuration property "security.protocol""}

**Comment by edenhill** [comment]
You need to build librdkafka with support for SSL and SASL, which require the development packages fo OpenSSL and Cyrus-SASL respectively.

Alternatively install a prebuilt librdkafka package.

What OS and Distro are you using?

For Debian and RPM packages, set up the apt or yum repositories as described here:
http://docs.confluent.io/3.2.0/installation.html

and then do `sudo apt-get install librdkafka-dev` or `yum install librdkafka-devel`.
Make sure it installs librdkafka v0.9.4 or later.

For OSX, use `brew install librdkafka`

**Comment by bgayathri** [comment]
Thanks for the reply. I'm using RHEL AMI (ec2) to test my Kafka Producer-Consumer model.

**Comment by edenhill** [comment]
Yep, that should be fine.

**Comment by bgayathri** [comment]
I have completed all the other steps except pip install.

The pip install is failing with below error,

confluent_kafka/src/confluent_kafka.h:17:20: fatal error: Python.h: No such file or directory

**Comment by edenhill** [comment]
You will need to install the `python-devel` package too, e.g.:
`sudo yum install python-devel`

Then you should be good to go!

**Comment by bgayathri** [comment]
Thank you so much for the help and support. All the installations worked fine for me. 
Now its time to test my code :)

**Comment by edenhill** [comment]
Glad to hear that!

**Comment by bgayathri** [comment]
I was able to give all the required configurations (code below)

Error:
  File "test.py", line 18, in <module>
    p = Producer(**conf)
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create producer: No error"}

Code:
from confluent_kafka import Producer
import os
os.environ['KRB5_CONFIG'] = 'xxxkrb5.conf'

conf = {
'bootstrap.servers': 'xxx.com:9092',
'group.id': 'testgroup',
'session.timeout.ms': 6000,
'enable.auto.commit': 'TRUE',
'sasl.kerberos.principal': 'xxx@xxx.COM',
'sasl.kerberos.keytab': 'xxx.keytab',
'sasl.kerberos.service.name': 'kafka',
'security.protocol': 'SASL_SSL',
'sasl.mechanisms': 'GSSAPI',
'ssl.certificate.location': 'xxx.pem',
'ssl.ca.location': 'xxx.jks'}

p = Producer(**conf)

data_source = ["Hello", "Howareyou"]

for data in data_source:
    p.produce('topic', data.encode('utf-8'))
    p.flush()

**Comment by edenhill** [comment]
I'm guessing you are on librdkafka v0.9.4 or so.
librdkafka v0.9.5 fixes error reporting for SSL errors, so it might help to upgrade.

But looking at your config this looks kind of strange:
`'ssl.ca.location': 'xxx.jks'` <-- OpenSSL  (which librdkafka uses for SSL support) does not support Java key stores, you need to provide a proper certificate file instead.

**Comment by bgayathri** [comment]
This is what I have done. Let me know if you feel its okay.

I have provided both pem and jks file. 
My jks file is generated using my pem file using the keytool command.
I did all this locally and then moved my pem and jks to ec2.
And then I'm using those files in my conf.

**Comment by edenhill** [comment]
You can't use jks (**java** key stores) with OpenSSL, you need to extract the PEM file from it.

**Comment by bgayathri** [comment]
I have the pem file, which I'm providing it as,

'ssl.certificate.location': 'xxx.pem',
'ssl.ca.location': 'xxx.jks'}

Do you recommend I get rid of the jks part?

**Comment by edenhill** [comment]
ssl.ca.location should point to your CA certificates, not a JKS.

**Comment by bgayathri** [comment]
Ok, will try and let you know. I think I have the cert too. I was referring to https://github.com/edenhill/librdkafka/issues/783 when I tried to prep my conf file.

Any instructions available on upgrading librdkafka?

**Comment by edenhill** [comment]
What OS and distro are you using?

**Comment by bgayathri** [comment]
Linux/RHEL 7.3(AMI-Ec2)

**Comment by edenhill** [comment]
You dont really need to upgrade to v0.9.5., all it fixes (in this regard) is the error reporting of SSL configuration errors, but I think we've already identified what is wrong  (using JKS instead of PEM file).

Confluent has not yet released RPMs for v0.9.5, but I saw that Remi did just the other day so you could use his RPMs in the meantime:
http://rpmfind.net/linux/rpm2html/search.php?query=librdkafka&submit=Search+...

**Comment by bgayathri** [comment]
This is the error I'm receiving now.
I have the CA cert so i have placed it in the ssl.ca.location. I have removed the usage of jks and I dont have any pem's.

Error:
%3|1493043303.488|ERROR|rdkafka#producer-1| sasl_ssl://xxx.com:9092/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-4)): SASL(-4): no mechanism available: No worthy mechs found

Code:
from confluent_kafka import Producer
import os
os.environ['KRB5_CONFIG'] = 'xxxkrb5.conf'

conf = {
'bootstrap.servers': 'xxx.com:9092',
'group.id': 'testgroup',
'session.timeout.ms': 6000,
'enable.auto.commit': 'TRUE',
'sasl.kerberos.principal': 'xxx@xxx.COM',
'sasl.kerberos.keytab': 'xxx.keytab',
'sasl.kerberos.service.name': 'kafka',
'security.protocol': 'SASL_SSL',
'sasl.mechanisms': 'GSSAPI',
'ssl.ca.location': 'xxx.cert'}

p = Producer(**conf)

data_source = ["Hello", "Howareyou"]

for data in data_source:
p.produce('topic', data.encode('utf-8'))
p.flush()

**Comment by edenhill** [comment]
That might be because your redhat install is missing GSSAPI Kerberos auth libraries, did you install krb5-libs?
I'm no expert on RHEL packages, so I'm not sure which one is required, but Cyrus SASL is modular and the authentication methods themselves are installed through addon packages, such as for Kerberos/GSSAPI

**Comment by bgayathri** [comment]
I think I was able to fix the error by installing "yum install cyrus-sasl-gssapi"

Now I'm facing below error,
"Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0))"

Should I add the below command to conf?
"'sasl.kerberos.kinit.cmd': 'kinit -S "%{sasl.kerberos.service.name}/%{broker.name}" -k -t "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}'}"

If yes, what should I give broker.name as ? (i have other props filled)

Thanks!

**Comment by edenhill** [comment]
I dont think you need to modify the kinit.cmd, the defaults are generally good.
But you might want to enable debugging in the client `'debug': 'security'` and if that doesn't tell you enough enable debugging in the broker (add 'debug' to the jaas configuration)

**Comment by bgayathri** [comment]
And in the kinit.cmd, the broker.name - does it refer to bootstrap.servers?
Are broker.name & bootsrap.servers one and the same?

**Comment by edenhill** [comment]
The kinit command is called for each broker connection, so the broker.name is exchanged for each broker.

**Comment by bgayathri** [comment]
Which property should I use for passing jaas configuration file?

And, also I think it is expecting krb5.conf file as one of the properties.
Although I'm specifying it, as "os.environ['KRB5_CONFIG'] = 'xxxkrb5.conf'", I'm doubtful if it is taken into account.

**Comment by edenhill** [comment]
The client is not Java based so it will not support a JAAS config file, that is for the Java client and broker.
You can enable kerberos debugging in the broker by adding `debug` to this line in your jaas config file:
`com.sun.security.auth.module.Krb5LoginModule required`.

The KRB5_CONFIG environment variable is used by kinit, etc, which is executed by the client to refresh its ticket key.

Make sure the broker name (as specified in bootstrap.servers) exactly matches principal name.

**Comment by bgayathri** [comment]
When you say principal name are you referring to 'sasl.kerberos.principal'?

**Comment by edenhill** [comment]
Sorry, I meant the broker service name.
Did you follow the steps here:
http://docs.confluent.io/current/kafka/sasl.html#authentication-using-sasl-kerberos
and here:
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka
?

**Comment by bgayathri** [comment]
Thanks for pointing it out. Let me check and let you know.

**Comment by bgayathri** [comment]
Hi -
I think everything from code point of view looks good. Something is missing from infrastructure side and I'm inquiring the same with my infrastructure team.

Thank you for helping me so far and I will post if I still have any issues/questions.

The issue I'm battling currently is as below.

Command tried à kinit -S "kafka/xxx.com" -k -t "/xxx/xxx.keytab" xxx@xxx.COM
 
Error received à kinit: Server not found in Kerberos database while getting initial credentials
SASL key refresh failed: kinit -S "kafka/xxx.capitalone.com" -k -t "xxx/xxx.keytab" xxx@xxx.COM: exited with code 1

Looks like something going on with AD/Centrify groups.

**Comment by bgayathri** [comment]
@edenhill The error I'm receiving now is 

SASL key refreshed
My supported SASL mechanisms: GSS-SPNEGO GSSAPI EXTERNAL ANONYMOUS
" Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database)".

Could you please let me know why I'm receiving this error?

**Comment by edenhill** [comment]
Is it a DNS issue?
http://stackoverflow.com/a/13860921/1821055

**Comment by bgayathri** [comment]
I confirmed that it it's not a DNS issue by hitting the same broker using the below command,

I'm able to consume/produce by executing the shell scripts present in Kafka library. This also uses keytab and kerberos authentication.

However, I'm not able to do the same programatically.

 /home/ec2-user/Kafka/bin/kafka-console-producer.sh -broker-list broker --topic topic --producer.config /home/ec2-user/Kafka/config/consumer.properties

/home/ec2-user/Kafka/bin/kafka-console-consumer.sh --new-consumer --bootstrap-server server --topic topic --from-beginning --consumer.config /home/ec2-user/Kafka/config/consumer.properties

**Comment by edenhill** [comment]
If you enable `debug=security` in librdkafka and look for any logs referencing the broker SPN (including the kinit execution), does the hostname part of the SPN differ in any way to what the Java client is using?

**Comment by edenhill** [comment]
That is "kafka/HOSTNAME@REALM@, the HOSTNAME part.

**Comment by bgayathri** [comment]
There are no differences in the "kafka/HOSTNAME@REALM@, the HOSTNAME part. 
Java is also using the same realm/host/keytab. The only change I had to do for python is using the pem file instead of the jks.

I have enabled debug=security in librdkafka.

However for the KINIT command I had to make a slight modification in order to get it working. I had to remove the -S part along with the args. If i use the below command, my SASL keys are getting refreshed. As soon as it refreshes I get the below error,
"sasl_ssl://server:port/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database)"

'sasl.kerberos.kinit.cmd': 'kinit -kt "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}'}

**Comment by edenhill** [comment]
Do you get any logs or printouts saying that the kinit command fails?
What happens if you execute the kinit commands manually, any issues with that?

I'm not sure it will work with removing the service principal option (-S):
```
    -S principal, --server=principal
             Get a ticket for a service other than krbtgt/LOCAL.REALM.
```

The client needs to get a ticket for the kafka service (or whatever you set sasl.service.name to).

**Comment by bgayathri** [comment]
kinit -S "kafka/xxx.xxx.xxx.com" -k -t "/home/ec2-user/xxx.keytab" xxx@xx.xx.xxx.COM
kinit: Server not found in Kerberos database while getting initial credentials 

(Similar error that we see now after SASL refresh is happening)
My streaming team / infrastructure team who owns the brokers advised me not to use it with -S.

**Comment by edenhill** [comment]
Can you figure what kinit command the Java client is using?

**Comment by bgayathri** [comment]
I think java kinit also has only -k -t options,

https://docs.oracle.com/javase/8/docs/technotes/tools/windows/kinit.html

My team mate uses java for producer/consumer code and he feels it uses only -kt options but its hidden even from the logs.

**Comment by edenhill** [comment]
@rnpridgeon Can you have a quick look at this when you get a chance to see if there is anything obvious?

**Comment by automaticgiant** [comment]
we've done some digging, but haven't solved it yet.

what we know:
- dev realm != prod realm
- dev broker service principal is in dev realm
- all other principals are in prod realm
- can't `kinit -S $devspn` from prod user in prod realm (server not found)

librdkafka findings:
- kafkacat (surrogate for the python lib) works from prod to prod cluster easily enough.
- only seen to work against dev with broker spn (dev realm)

misc/idk:
- this is not a problem with jvm/jaas
- the java kinit is only a thing afaik for windows, where an implementation is shipped with the jdk, 

theories:
- there is some code in librdkafka, or cyrus, that assumes a realm when it shouldn't
  - supported by it being a non-issue with jvm client
- it's our AD(kdc) problem and when we can `kinit -S something` from prod to dev, it will start working

these might both be somewhat right, but idk yet.

**Comment by rnpridgeon** [comment]
Hey everyone sorry I am late to the party, 

Thanks for the summary at the end there automaticgiant. 

So based on what I have gathered from the summary and scanning a few of the previous comments this looks as if you do not currently have AD(kdc) or the Centrify integration configured correctly. 

Executing `kinit kafka/{instance(FQDN)}@REALM -k -t kafka.keytab` should be used as your baseline test for functionality. `-S` isn't necessary, at least with the MIT implementation, although it shouldn't hurt anything.  

Performing this basic test allows you to rule out/in the client library as this is the most basic means of authentication with regard to Kerberos. If you cannot procure a TGT from the KDC with this command it will not work with any client implementation. 

Based on 'What we know' you wish to allow for cross-realm communication between DEV and PROD. In order to do this you will need to properly configure the KDC with cross-realm trusts. I don't know how this is handled with AD or Centrify but the basics for setting up cross-realm trusts with MIT Kerberos can be found here:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Deployment_Guide/sec-kerberos-crossrealm.html

With cross-realm trusts enabled the Ticket Granting Service should trust principals that have been authenticated by the DEV realm's KDC.

One thing that may be causing us issues however is how the Service Ticket request is being formed. I think the Kafka services always assume that the service they wish to talk to resides in the same realm. As a result it will request a service granting ticket for kafka/{instance(FQDN)}/OWN_REALM. This will likely result in the service not found in KDC error. Since kafka/prod.hostname@DEV will not reside within the KDC.

**Comment by automaticgiant** [comment]
so the big but is that the jvm client works under the same cross-realm conditions, even without being able to get a service ticket, but idk why. so we can lean on the AD folks, but there's something we are missing. and afaik, we have cross-realm trusts. we'll get back to you.

**Comment by rnpridgeon** [comment]
Interesting, I'm not sure how the JVM is going to acquire a TGT if you can't get one from the command line alone. Can you verify the JAAS is using the DEV principal

**Comment by bgayathri** [comment]
I have verified this by running the below commands,

export KAFKA_OPTS='-server -Xms1024m -Xmx1024m -Djava.security.auth.login.config=kafka.client.jaas.conf -Djava.security.krb5.conf=/etc/krb5.conf'

/home/ec2-user/Kafka/bin/kafka-console-producer.sh -broker-list broker --topic topic --producer.config /home/ec2-user/Kafka/config/consumer.properties

/home/ec2-user/Kafka/bin/kafka-console-consumer.sh --new-consumer --bootstrap-server server --topic topic --from-beginning --consumer.config /home/ec2-user/Kafka/config/consumer.properties

**Comment by automaticgiant** [comment]
an interesting addtion, that circles back to one of my initial (yet unmentioned) concerns.
```
kafkacat -b cname:9092 ...
...
2017-05-03T14:45:53 set-error: -1765328377: Server  unknown
2017-05-03T14:45:53 krb5_sendto_context DEVREALM done: 0 hosts 1 packets 1 wc: 0.014729 nr: 0.000672 kh: 0.003992 tid: 00170001
2017-05-03T14:45:53 set-error: -1765328377: Server (kafka/bulkload-fqdn@DEVREALM) unknown
```
so we have our brokers set up with cnames and cname spns. however, we also have our ec2 ip space mapped into dns via bulk-load fqdns. something that librdkafka/kafkacat seems to do, but that the jvm kafka console consumer/producer (or jvm lib in general) does not, is an unavoidable reverse-resolution. now it's possible that on a normal linux box i could configure that away in krb5.conf, but on my osx laptop I don't have that option. testing teh other scenario is harder.

any librdkafka devs here know if that's something you can control in librdkafka?

**Comment by edenhill** [comment]
@automaticgiant Did you try setting rdns=false?
https://web.mit.edu/kerberos/krb5-1.13/doc/admin/princ_dns.html#reverse-dns-mismatches

**Comment by automaticgiant** [comment]
i don't have anywhere to set that on my mac afaik. i'll see about testing on a centrify/linux box.

**Comment by bgayathri** [comment]
@edenhill I tried to add the option "rdns = false" in my "krb5.conf" file and retried the producer code. Still facing the same issues.

**Comment by automaticgiant** [comment]
but to be clear, there's not any explicit reverse resolution happening in kafkacat/librdkafka, that you know of? (that was my hope because it's arguably easier to change than our centrify shenanigans)

**Comment by edenhill** [comment]
There is not, librdkafka will only do forward dns resolution (name to address).
But cyrus-sasl/libsasl2 & the gssapi modules might very well do so.

You might need to set the KRB5_CONF env var too.

**Comment by automaticgiant** [comment]
thanks. you can probably close now. i'm fairly confident that it's not your problem and it will be obviated anyway.

**Comment by geocine** [comment]
When I try to use this configuration , this `sasl.kerberos.keytab` doesn't exist anymore, how do we set this up now?

**Comment by edenhill** [comment]
See **Install from source from PyPi (requires librdkafka + dependencies to be installed separately):** here: https://github.com/confluentinc/confluent-kafka-python#install
