### ISSUE TITLE
How to detect Producer Errors? KafkaException doesn detect it

### ISSUE THREAD

**Issue by Nabil-Miri** [confluentinc/confluent-kafka-python#1803]
Description
===========
Something errors occurs with the Producer and I want to catch the exception but I am not able to. 
Code:
```
    try:
        producer.produce(
            topic, value="Hello, world!".encode("utf-8"), callback=on_delivery
        )
    except KafkaException as ke:
        kafka_error = ke.args[0]
        # Handle KafkaException
        print("Error: KafkaException during reconnection: " + str(kafka_error))
```
The bootstrap_server is something invalid to create an error. If I added a poll after produce, then an error is printed into the terminal but the exception is not caught.
```
    try:
        producer.produce(
            topic, value="Hello, world!".encode("utf-8"), callback=on_delivery
        )
        producer.poll(1)
    except KafkaException as ke:
        kafka_error = ke.args[0]
        # Handle KafkaException
        print("Error: KafkaException during reconnection: " + str(kafka_error))
```
Error printed into the terminal after adding poll:
_%3|1724746307.546|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://invalid_host:9092/bootstrap]: sasl_ssl://invalid_host:9092/bootstrap: Failed to resolve 'invalid_host:9092': Name or service not known (after 13ms in state CONNECT)_

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 2.5.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Ubuntu 22.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
The produce call is asynchronous and would not raise exception immediately. Please use `error_cb` for catching the exceptions. Please refer [Produce Deliver Failures](https://github.com/confluentinc/librdkafka/blob/master/INTRODUCTION.md#producer-message-delivery-failure) for more information related to the Producer errors.

**Comment by Nabil-Miri** [comment]
Noted. Thanks for your reply.
