### ISSUE TITLE
How to recover after a disconnection

### ISSUE THREAD

**Issue by wuhongsheng** [confluentinc/confluent-kafka-python#1810]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
Please fill out all the details from next time you raise any issue.

For you question, the client automatically tries to recover from any disconnection.
