### ISSUE TITLE
does new Consumer.subscribe() add to or replace previous subscriptions?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#183]
Let's say I start out with Consumer.subscribe([topic_A, topic_B, topic_C]) but later decide that I also want to subscribe to topic_D on the same consumer. If I just do a Consumer.subscribe([topic_D]), it seems that while I successfully subscribe to topic_D, I am no longer subscribed to topic_A, topic_B, or topic_C. So in order to make the new subscription additive, I would have to do Consumer.subscribe([topic_A, topic_B, topic_C, topic_D]) . Is this correct and expected?

**Comment by ewencp** [comment]
@johnrgregg3 That's correct, as mentioned in the [API docs for subscribe()](http://docs.confluent.io/current/clients/confluent-kafka-python/index.html#confluent_kafka.Consumer.subscribe):

> This replaces a previous subscription.
