### ISSUE TITLE
jsonschema version is not constrained: jsonschema.RefResolver is deprecated as of v4.18.0

### ISSUE THREAD

**Issue by timonviola** [confluentinc/confluent-kafka-python#1840]
Description
===========
`jsonschema` version is not constrained by this package and we are seeing warning in our test runs.

`jsonschema                4.23.0    An implementation of JSON Schema valid`

```
============================== warnings summary ===============================
.venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/json_schema.py:23
.venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/json_schema.py:23
  /Users/timon/work/kafka-log/kafka-log/.venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/json_schema.py:23: DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
    from jsonschema import validate, ValidationError, RefResolver
```

How to reproduce
================
Create a fresh installation of the package with json extras.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
     - confluent-kafka           2.6.0
     - confluent_kafka.libversion() ('2.3.0', 33751295)
 - [x] Critical issue: Not a critical issue, but it will be, when `jsonschema` releases a new breaking change

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1852
