### ISSUE TITLE
2.6.0 "broker might require SASL authentication" error

### ISSUE THREAD

**Issue by nrlulz** [confluentinc/confluent-kafka-python#1842]
Description
===========

After upgrading to 2.6.0 I am receiving the following error from the consumer on startup:

    Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication

But I am not using SASL authentication (using plaintext) and nothing has changed on the broker. After downgrading back to 2.5.3, things are working normally again. I did try explicitly setting `security.protocol` to `plaintext` in the client config, which did not make any difference.

On 2.6.0, it does not happen in my local dev environment, which uses a newer broker version (whichever the docker image `confluentinc/cp-kafka:7.4.1` uses). So I assume this has something to do with the older version of broker we are running?

How to reproduce
================

Unfortunately I don't have a minimal reproduction since it involves AWS resources. I am hoping the client logs can provide enough information to tell what happened. There is one for normal operation in version 2.5.3 and one for the failure in 2.6.0. Let me know if there is any other info I can provide.

[logs-2.5.3.txt](https://github.com/user-attachments/files/17482903/logs-2.6.0.txt)
[logs-2.6.0.txt](https://github.com/user-attachments/files/17482902/logs-2.5.3.txt)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): both 2.6.0
 - [x] Apache Kafka broker version: AWS MSK 2.6.2
 - [x] Client configuration: see attached logs
 - [x] Operating system: linux (AWS EKS)
 - [x] Provide client logs (with `'debug': '..'` as necessary): see attached logs
 - [ ] Provide broker log excerpts
 - [ ] #1844

**Comment by tarmacx** [comment]
Same here ! First time with the library, I wasted my whole day yesterday trying to figure this out until I found this post this morning ! Downgraded to 2.5.3 made it all work fine !

**Comment by anhg** [comment]
Have same issue in https://github.com/confluentinc/confluent-kafka-dotnet version 2.6.0

**Comment by xiaozi0513** [comment]
I also meet the same error. My kafka version is 1.0.0, in version 2.6.0, it not work; version 2.5.3 works fine.

**Comment by korchak-aleksandr** [comment]
Also meet this error and downgraded to 2.5.3 😿

**Comment by nrlulz** [comment]
> @anhg: Have same problem in https://github.com/confluentinc/confluent-kafka-dotnet version 2.6.0
> @korchak-aleksandr: Same problem in https://github.com/confluentinc/confluent-kafka-dotnet version 2.6.0

I would guess that this is actually a problem with librdkafka if you guys are seeing it over in dotnet too. Maybe we should file an issue over there instead?

> btw, @nrlulz the log file names are switched (2.5.3.log contains logs for 2.6.0)...

Whoops! I updated the version names. Thanks for catching that.

**Comment by jonbuffington** [comment]
Seems to be fixed in librdkafka according to https://github.com/confluentinc/librdkafka/issues/4870 but has not been released yet.

**Comment by blockjon-dd** [comment]
I've spent maybe 8 hours trying to solve this before resorting to googling and finally I see I'm not crazy and others are also suffering with a known bug. Thanks to those who participated above.

**Comment by blockjon-dd** [comment]
@pranavrth Could you share when the next version will go out with the improvements mentioned above? Thank you so much.

**Comment by lignah** [comment]
I really struggled with this issue. Thanks a lot!

**Comment by pranavrth** [comment]
We will be releasing the client by 19th Nov, 2024.

**Comment by pranavrth** [comment]
[v2.6.1](https://pypi.org/project/confluent-kafka/2.6.1/) is release which includes this fix.

**Comment by nrlulz** [comment]
I can confirm that v2.6.1 resolves the issue. Thanks @pranavrth!
