### ISSUE TITLE
Errors with installing confluent_kafka in python3.8.10

### ISSUE THREAD

**Issue by yintian710** [confluentinc/confluent-kafka-python#1848]
Description
===========

os: Ubuntu 16.04.1 LTS (GNU/Linux 4.15.0-142-generic x86_64)
Python 3.8.10
pip: 20.1.1
librdkafka-dev：0.8.6-1.1

when I run "pip install confluent_kafka"，I meet some errors
I can install it when VERSION<2.4.0, when I want update, it error
[error0.log](https://github.com/user-attachments/files/17743200/error0.log)

when I update pip to 24.3.1

[error1.log](https://github.com/user-attachments/files/17743201/error1.log)

**Comment by pranavrth** [comment]
Ubuntu 16.04 is pretty old. From v2.5.0, we only support OS which supports glibc 2.28. There are a few options for you:

- Upgrade to Ubuntu 20.04+ and you can directly install the latest version
- Use older version of the client <2.5.0
- Install librdkafka and this client from source

Please refer [this thread](https://github.com/confluentinc/confluent-kafka-python/issues/1784) for more information.
