### ISSUE TITLE
Failed to install an older version of confluent-kafka-python with librdkafka (librdkafka/rdkafka.h not found) (Python 3.7.7)

### ISSUE THREAD

**Issue by uoyniXnaH** [confluentinc/confluent-kafka-python#1849]
Description
===========
I have a python application container by docker from python:3.7.7-alpine3.11 (I know it is quite old, but I cannot upgrade that easily)
I would like to use confluent-kafka-python in this application. So I modified the Docekrfile like the follows:
```Dockerfile
RUN apk update \
   && apk --no-cache add gcc libc-dev librdkafka-dev linux-headers \
   && pip install --no-cache-dir -r requirements.txt \
   # it seems that the image could only install librdkafka up to 1.2.2, so I choose confluent-kafka 1.2.0
   && pip install confluent-kafka==1.2.0 \
   && apk del gcc linux-headers
```

Then I got an error saying librdkafka/rdkafka.h not found
My environment:
OS: Windows 11/WSL 2.3.26.0
Docker: 27.0.2

How to reproduce
================
In the Dockerfile:
```Dockerfile
FROM python:3.7.7-alpine3.11
# ...
RUN apk update \
   && apk --no-cache add gcc libc-dev librdkafka-dev linux-headers \
   && pip install --no-cache-dir -r requirements.txt \
   # it seems that the image could only install librdkafka up to 1.2.2, so I choose confluent-kafka 1.2.0
   && pip install confluent-kafka==1.2.0 \
   && apk del gcc linux-headers
# ...
```

Build the image with `docker compose build`.
Then wait for the error.

I appreciate any suggestions.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka-python: 1.2.0 librdkafka: 1.2.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system:　Windows 11/WSL 2.3.26.0
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
Since you can't upgrade the Python version, I would suggest to install [librdkafka ](https://github.com/confluentinc/librdkafka?tab=readme-ov-file#build-from-source) and [this client](https://github.com/confluentinc/confluent-kafka-python/blob/master/INSTALL.md#install-from-source) from source. Make sure to skip the part to install librdkafka-dev for this client when you follow the guide.
