### ISSUE TITLE
Getting this package work with asyncio

### ISSUE THREAD

**Issue by amitripshtos** [confluentinc/confluent-kafka-python#185]
Hey guys,
great job on this package!

I wanted to know if there is a way to use asyncio with this package, since I saw some code that using "async await" thingy

If does, there is any example? 
thanks,
Amit

**Comment by edenhill** [comment]
Hi,
we're currently looking into making it compatible with asyncio.

Stay tuned!

related issue:
https://github.com/confluentinc/confluent-kafka-python/issues/100

**Comment by ask** [comment]
Are there any updates on this?  Is anyone working on it?

**Comment by vineet-rh** [comment]
+1

**Comment by edenhill** [comment]
Not yet, community contributions are very much welcome.
Some initial research on what needs to be done would be great!

**Comment by nurikk** [comment]
+1

**Comment by jeffwidman** [comment]
In the meantime, https://github.com/aio-libs/aiokafka is a kafka library that supports asyncio

**Comment by marirs** [comment]
Hi, just checking, is it yet compatiable with asyncio

**Comment by secretmike** [comment]
Hi, I started looking at this a bit.

asyncio has the ability to watch file descriptors for read availability (https://docs.python.org/3/library/asyncio-eventloop.html#watch-file-descriptors)

librdkafka can write to a file descriptor when a queue is readable with `rd_kafka_queue_io_event_enable()` (https://github.com/edenhill/librdkafka/blob/7478b5ef16aadd6543fe38bc6a2deb895c70da98/src/rdkafka.h#L2362)

Would it be possible to expose `rd_kafka_queue_io_event_enable()` in the python API? I don't believe the queues are exposed currently, so confluent-kafka-python would have to attach the appropriate internal queue itself.

Ideally you should be able to pass a file descriptor and a payload. When the file descriptor becomes readable, call `poll()` or `consume()`.

There are still a handful of synchronous operations (like `commit()`, `committed()`, etc.) but consuming and producing messages is still the most heavily used operation.

asyncio support could probably be integrated more directly in this library, but the above might be a good starting point to allow for an asycio wrapper.

**Comment by tongda** [comment]
Since go-lang wrapper can benefit `channel` mechanism, which makes the go-lang wrapper more idiom, `async/await` support may get inspired from it.

**Comment by vineetgoel** [comment]
Any updates here?

**Comment by CrazyWisdom** [comment]
+1

**Comment by StarLightPL** [comment]
+1

**Comment by andreportela** [comment]
+1

**Comment by madisvain** [comment]
Leaving this here for reference until this feature gets implemented. It's possible to process the messages with Asyncio it seems.

https://stackoverflow.com/a/55498503

_I have not tried this out myself yet but might be of help._

**Comment by h12w** [comment]
I guess some people might just want it working with asyncio, not working with maximum efficiency. So here is an example that works now:

```python
import asyncio

async def run_consumer(consumer):
    while True:
        msg = consumer.poll(timeout=0)
        if msg is None:
            await asyncio.sleep(delay=0)
            continue
        # handle msg
        consumer.commit(msg, asynchronous=True)

await run_consumer(consumer)
```

**Comment by matrixise** [comment]
The main issue is the support of the Schema Registry, this one does not exist with aiokafka.

**Comment by gjcarneiro** [comment]
> asyncio has the ability to watch file descriptors for read availability (https://docs.python.org/3/library/asyncio-eventloop.html#watch-file-descriptors)

Yes, but keep in mind that this API is not very portable, e.g. it does not work with Windows ProactorEventLoop.

**Comment by mhowlett** [comment]
keep an eye on the confluent blog over the next couple of weeks for an in depth blog post on this client and asyncio. it walks through the producer only, though. @h12w - your solution will busy loop and will be very inefficient. to be efficient, you need to do blocking consumer calls, and to do that you'll need another thread.

**Comment by sangmeshcp** [comment]
@mhowlett any update on the detailed blog.. couldn't search for it

**Comment by mhowlett** [comment]
https://www.confluent.io/blog/kafka-python-asyncio-integration/

**Comment by galen211** [comment]
Has anyone been able to successfully connect to `Confluent Cloud` with `AIOKafka`?  I tried using a modified version of the `ssl_consume_produce.py` example from the `AIOKafka` repo at <https://github.com/aio-libs/aiokafka/blob/master/examples/ssl_consume_produce.py> and was unsuccessful.  I've configured my `AIOKafkaConsumer` and `AIOKafkaProducer` with what I believe to be the correct parameters but am getting the below runtime error.  I've also included my modified script and config further below.
```
/Users/galen/opt/anaconda3/envs/ds/bin/python /Volumes/ThunderBlade/github/kafka/aiokafka/examples/ssl_consume_produce.py
Traceback (most recent call last):
  File "/Volumes/ThunderBlade/github/kafka/aiokafka/examples/ssl_consume_produce.py", line 57, in <module>
    loop.run_until_complete(task)
  File "/Users/galen/opt/anaconda3/envs/ds/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Volumes/ThunderBlade/github/kafka/aiokafka/examples/ssl_consume_produce.py", line 52, in <module>
    loop.run_until_complete(task)
  File "/Users/galen/opt/anaconda3/envs/ds/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Volumes/ThunderBlade/github/kafka/aiokafka/examples/ssl_consume_produce.py", line 23, in produce_and_consume
    await producer.start()
  File "/Users/galen/opt/anaconda3/envs/ds/lib/python3.7/site-packages/aiokafka/producer/producer.py", line 171, in start
    await self.client.bootstrap()
  File "/Users/galen/opt/anaconda3/envs/ds/lib/python3.7/site-packages/aiokafka/client.py", line 203, in bootstrap
    version_hint=version_hint)
  File "/Users/galen/opt/anaconda3/envs/ds/lib/python3.7/site-packages/aiokafka/conn.py", line 90, in create_conn
    await conn.connect()
  File "/Users/galen/opt/anaconda3/envs/ds/lib/python3.7/site-packages/aiokafka/conn.py", line 214, in connect
    await self._do_sasl_handshake()
  File "/Users/galen/opt/anaconda3/envs/ds/lib/python3.7/site-packages/aiokafka/conn.py", line 281, in _do_sasl_handshake
    payload, expect_response = res
RuntimeError: await wasn't used with future
Unclosed AIOKafkaProducer
producer: <aiokafka.producer.producer.AIOKafkaProducer object at 0x7f9bc818d350>
```
My adapted version of the code is:
```python
import asyncio
from ssl import create_default_context, Purpose
from aiokafka import AIOKafkaProducer, AIOKafkaConsumer
from kafka.common import TopicPartition

import ccloud_lib

ssl_context = create_default_context(Purpose.SERVER_AUTH, cafile='cacert.pem')
conf = ccloud_lib.read_ccloud_config('kafka_config.conf')

async def produce_and_consume(loop):
    # Produce
    producer = AIOKafkaProducer(
        bootstrap_servers=conf['bootstrap.servers'],
        loop = loop,
        security_protocol='SASL_SSL',
        ssl_context=ssl_context,
        sasl_mechanism='PLAIN',
        sasl_plain_password=conf['sasl.password'],
        sasl_plain_username=conf['sasl.username']
    )

    await producer.start()
    try:
        msg = await producer.send_and_wait(
            'my_topic', b"Super Message", partition=0)
    finally:
        await producer.stop()

    consumer = AIOKafkaConsumer(
        bootstrap_servers=conf['bootstrap.servers'],
        loop=loop,
        ssl_context=ssl_context,
        security_protocol='SASL_SSL',
        sasl_mechanism='PLAIN',
        sasl_plain_password=conf['sasl.password'],
        sasl_plain_username=conf['sasl.username']
    )
    await consumer.start()
    try:
        consumer.seek(TopicPartition('my_topic', 0), msg.offset)
        fetch_msg = await consumer.getone()
    finally:
        await consumer.stop()

    print("Success", msg, fetch_msg)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    task = loop.create_task(produce_and_consume(loop))
    try:
        loop.run_until_complete(task)
    finally:
        loop.run_until_complete(asyncio.sleep(0, loop=loop))
        task.cancel()
        try:
            loop.run_until_complete(task)
        except asyncio.CancelledError:
            pass
```
My obfuscated configuration `conf` looks like this:
```
bootstrap.servers=*****.us-central1.gcp.confluent.cloud:9092
ssl.endpoint.identification.algorithm=https
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username\="********************" password\="****************************************";
sasl.username=********************
sasl.password=********************************************************************************
basic.auth.credentials.source=USER_INFO
schema.registry.basic.auth.user.info=********************:********************
schema.registry.url=https://********************.us-central1.gcp.confluent.cloud
```
Is there something about my configuration which is incorrect or missing?
[NB: also posted at [StackOverflow](https://stackoverflow.com/questions/60032086/confluentapache-kafka-connecting-to-confluent-cloud-with-aiokafka-client), but thought it might have a better audience here]

**Comment by jeffwidman** [comment]
@galen211 you should post the issue on https://github.com/aio-libs/aiokafka/issues or email confluent support... this repo is unrelated to either that lib or that cloud.

**Comment by rnpridgeon** [comment]
As @jeffwidman pointed out you will need to take this up with aiokafka. I'm closing this issue with @mhowlett's blog being the resolution.
