### ISSUE TITLE
Schema Registry support: delete_version does not support the "permanent" flag

### ISSUE THREAD

**Issue by xdgrulez** [confluentinc/confluent-kafka-python#1851]
Description
===========

In the REST API, the Schema Registry supports "permanent=True" (hard delete) not only on subjects, but also on versions. This is missing in confluent_kafka.

How to reproduce
================

Just compare the spec of

delete_version(subject_name, version)

with the REST API spec:

https://docs.confluent.io/platform/current/schema-registry/develop/api.html#delete--subjects-(string-%20subject)-versions-(versionId-%20version)

Checklist
=========
Please provide the following information:

 - [X ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): latest (2.6.0)
 - [ ] Apache Kafka broker version: not relevant for this issue
 - [ ] Client configuration: `{...}` not relevant for this issue
 - [ ] Operating system: not relevant for this issue
 - [ ] Provide client logs (with `'debug': '..'` as necessary) not relevant for this issue
 - [ ] Provide broker log excerpts not relevant for this issue
 - [ ] Critical issue

**Comment by allamiro** [comment]
Ensure alignment with the official Schema Registry API documentation:
- [ ] Add examples for the permanent flag in the library's usage guide.
- [ ] Provide a clear distinction between soft and hard delete behavior.

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1867
