### ISSUE TITLE
ProtobufDeserializer uses deprecated class

### ISSUE THREAD

**Issue by qed-** [confluentinc/confluent-kafka-python#1863]
Description
===========
This line 
https://github.com/confluentinc/confluent-kafka-python/blob/31640d72bcac771e9a682e1c8c06c2e08bf0b4dd/src/confluent_kafka/schema_registry/protobuf.py#L513

generates the following warning

`
/usr/local/lib/python3.10/site-packages/confluent_kafka/schema_registry/protobuf.py:513: UserWarning: MessageFactory class is deprecated. Please use GetMessageClass() instead of MessageFactory.GetPrototype. MessageFactory class will be removed after 2024.`

It seems like the deprecated method will be removed altogether very soon:
https://github.com/protocolbuffers/protobuf/commit/c261b49a9575226efc9e5d269f6e5319a05d526e

How to reproduce
================
Create a ProtobufDeserializer instance with probuf library protobuf==5.29.1 installed

 - [X] confluent-kafka-python  (2.6.1, 33947904)
 - [X] librdkafka version (2.6.1, 33948159)

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1852
