### ISSUE TITLE
No module named 'attrs' with v2.6.2

### ISSUE THREAD

**Issue by bcaure** [confluentinc/confluent-kafka-python#1879]
Description
===========
When installing the latest release (2.6.2), some modules are suddenly missing: "httpx", "attrs", "cachetools"

How to reproduce
================
In requirements.txt
`confluent-kafka==2.6.2`

Make sure you test in a new environment or clean all previously installed modules.
Then:

`pip install`

Then run your application, you will find: `No module named 'attrs'`
(also  `No module named 'cachetools'`
or `No module named 'httpx'`)

Checklist
=========
Please provide the following information:

 - [x ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 2.6.2
 - [x ] Apache Kafka broker version: N/A
 - [ x] Client configuration: N/A
 - [ x] Operating system: Windows 11
 - [x ] Provide client logs (with `'debug': '..'` as necessary):

```
from .kafka_config import * backend_orchestrator/src/utils/kafka/kafka_config.py:4: in <module> 
from confluent_kafka.schema_registry import SchemaRegistryClient /usr/local/lib/python3.11/site-packages/confluent_kafka/schema_registry/init.py:20: in <module>
from .schema_registry_client import ( /usr/local/lib/python3.11/site-packages/confluent_kafka/schema_registry/schema_registry_client.py:27: in <module> 
from attrs import define as _attrs_define E ModuleNotFoundError: No module named 'attrs'
```

 - [ x] Provide broker log excerpts: N/A
 - [ x] Critical issue

**Comment by rayokota** [comment]
Try  `pip install -'confluent-kafka[avro,schemaregistry]'`

**Comment by bcaure** [comment]
> Try `pip install 'confluent-kafka[avro,schemaregistry]'` or put the following in your requirements:
> 
> `confluent-kafka[avro,schemaregistry]==2.6.2`

It works! thanks
