### ISSUE TITLE
Process hanging on producer.flush()

### ISSUE THREAD

**Issue by cah-jeffgraham** [confluentinc/confluent-kafka-python#188]
I'm having an issue with producer.flush() not completing - similar to (https://github.com/confluentinc/confluent-kafka-python/issues/137). I'm consuming 465k messages to topic A and producing into B within 60 seconds, but I've let it set on flush() for 1 hour with no completion.  Messages appear to be in produced into topic B.  I tried following your recommendations to snehamj with no luck.  During debug it appears to continue going into delivery_callback(err, msg) without end.

Thanks for the help.
 
**Output**
> Copying topic from t-A into t-B
> Topic tsi-A 100,000 messages consumed.
> Topic tsi-A 200,000 messages consumed.
> Topic tsi-A 300,000 messages consumed.
> Topic tsi-A 400,000 messages consumed.
> Topic tsi-A 464,865 messages consumed.
> No more messages to process
> Messages copied: 464,865
> 

**Code**
```
def delivery_callback(err, msg):
    if err:
        sys.stderr.write('%% Message failed delivery: %s\n' % err)
    # else:
    #     sys.stderr.write('%% Message delivered to %s [%d]\n' % (msg.topic(), msg.partition()))


def cpTopic():
    conf = {'group.id': uuid.uuid1(),
            'bootstrap.servers': 'host:9093',
            'security.protocol': 'ssl',
            'ssl.ca.location': 'CARoot.pem',
            'ssl.certificate.location': 'certificate.pem',
            'ssl.key.location': 'key.pem',
            'session.timeout.ms': 6000,
            'compression.codec': 'snappy',
            'default.topic.config': {
                'auto.offset.reset': 'earliest'
            }
            }

    c = Consumer(**conf)
    p = Producer(**conf)
    # Subscribing to a topic will start a background thread
    c.subscribe([topic])

    last = int(time.time())
    timeout = 10
    msg_cnt = 0

    try:
        while True:
            # print 'timeout: ' + str(int(time.time()) - last)
            if (int(time.time()) - last) > timeout:
                print 'Topic %s %s messages consumed.' % (topic, format(msg_cnt, ",d"))
                print 'No more messages to process'
                break

            msg = c.poll(timeout=1.0)
            if msg is None:
                continue
            if msg.error():
                # Error or event
                if msg.error().code() == KafkaError._PARTITION_EOF:
                    # End of partition event
                    continue
                    # sys.stderr.write('Topic %s partition %d reached end at offset %d\n' %
                    #                  (msg.topic(), msg.partition(), msg.offset()))
                elif msg.error():
                    # Error
                    raise KafkaException(msg.error())
            else:
                # Proper message
                msg_cnt += 1
                last = int(time.time())

                if not msg_cnt % 100000:
                    print 'Topic %s %s messages consumed.' % (msg.topic(), format(msg_cnt, ",d"))

                try:
                    p.produce(target_topic, msg.value(), callback=delivery_callback)

                except BufferError as e:
                    sys.stderr.write('%% Local producer queue is full ' \
                                     '(%d messages awaiting delivery): try again\n' %
                                     len(p))
                p.poll(0)


    except KeyboardInterrupt:
        print('Aborted by user')

    print 'Messages copied: %s' % format(msg_cnt, ",d")

    # Close down consumer to commit final offsets.
    c.close()
    # Flush messages produced
    p.flush()


if __name__ == "__main__":
    start = time.time()
    topic = sys.argv[1] 
    target_topic = sys.argv[2]  

    print 'Copying topic from %s into %s' % (topic, target_topic)
    cpTopic()
    end = time.time() - start
    print 'Time to complete: {0:.{1}f} seconds'.format(end, 2)
```

**Comment by edenhill** [comment]
Your code looks fine.

What confluent-kafka-python and librdkafka versions are you on?

**Comment by cah-jeffgraham** [comment]
**$ pip show confluent_kafka**
Name: confluent-kafka
Version: 0.9.4
Summary: Confluent's Apache Kafka client for Python
Home-page: https://github.com/confluentinc/confluent-kafka-python
Author: Confluent Inc
Author-email: support@confluent.io
License: UNKNOWN
Location: /mydirs/
Requires: 
**$ pip show pip show librdkafka**
Name: pip
Version: 9.0.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /mydirs/
Requires: 

Also, I've let it run longer with the following output:

> Copying topic from tsi-IPC into temp-IPC
> Topic tsi-IPC 100,000 messages consumed.
> Topic tsi-IPC 200,000 messages consumed.
> Topic tsi-IPC 300,000 messages consumed.
> Topic tsi-IPC 400,000 messages consumed.
> Topic tsi-IPC 464,865 messages consumed.
> No more messages to process
> Messages copied: 464,865
> %3|1494508858.195|FAIL|rdkafka#producer-2| ssl://host:9093/2: Receive failed: No error
> %3|1494508858.195|ERROR|rdkafka#producer-2| ssl://host:9093/2: Receive failed: No error
> %3|1494509458.522|FAIL|rdkafka#producer-2| ssl://host:9093/2: Receive failed: No error
> %3|1494509458.522|ERROR|rdkafka#producer-2| ssl://host:9093/2: Receive failed: No error

**Comment by edenhill** [comment]
```
$ pip show pip show librdkafka
Name: pip
Version: 9.0.1
Summary: The PyPA recommended tool for installing Python packages.
...
```

I think you need to do that again, without the extra "show pip" part :)

**Comment by cah-jeffgraham** [comment]
Oops:

$ brew info librdkafka
librdkafka: stable 0.9.1
The Apache Kafka C/C++ library
https://github.com/edenhill/librdkafka
/usr/local/Cellar/librdkafka/0.9.1 (14 files, 1.3MB) *
  Built from source on 2017-03-11 at 14:22:26
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/librdkafka.rb
==> Dependencies
Build: pkg-config ✘
Required: lzlib ✔, openssl ✔

**Comment by edenhill** [comment]
There were some bugs with previous librdkafka versions' flush() calls, please upgrade to the latest on brew, which I think is 0.9.5

**Comment by cah-jeffgraham** [comment]
That makes sense as I ran it on a CentOS vm with no issues.  I did, however, run into a brew upgrade issue:

```
$ brew upgrade librdkafka
Error: librdkafka: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/librdkafka.rb:4: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/librdkafka.rb:15: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/librdkafka.rb:25: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
```

**Comment by edenhill** [comment]
Uhm, that looks like a merge conflict in the brew formula?!

You might want to follow the steps here:
https://github.com/Homebrew/legacy-homebrew/issues/4580

**Comment by edenhill** [comment]
Did this get sorted?
