### ISSUE TITLE
Skip tombstone messages when using Avro decoder with pyspark streaming

### ISSUE THREAD

**Issue by shardnit** [confluentinc/confluent-kafka-python#189]
I am using the [Avro decoder](https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/serializer/message_serializer.py#L198) with pyspark streaming module. It works just fine for Avro messages (with `schema-registry`) but [crashes](http://spark.apache.org/docs/2.1.0/api/python/pyspark.streaming.html#pyspark.streaming.kafka.KafkaUtils.createStream) for tombstone (`null`) messages. 

The [createStream](http://spark.apache.org/docs/2.1.0/api/python/pyspark.streaming.html#pyspark.streaming.kafka.KafkaUtils.createStream) method accepts a `valueDecoder` param.
```python
kafka_stream = KafkaUtils.createStream(streaming_context,
                                       <zookeeper>,
                                       "spark-streaming-consumer",
                                       <topic_dict>,
                                       valueDecoder=avro_decoder)
```
The Kafka connect adaptor, I am using, generates `null` messages, so they also have to accounted for while processing.

**Comment by ewencp** [comment]
@shardnit This looks like we just missed the `None` case during deserialization, I've created https://github.com/confluentinc/confluent-kafka-python/pull/190 to fix this.

**Comment by shardnit** [comment]
👍
