### ISSUE TITLE
my offset in mysql in updated to -1001

### ISSUE THREAD

**Issue by zhangmoon** [confluentinc/confluent-kafka-python#195]
I store the consumer offset in mysql. I update the offset in mysql at consumer function and in on_revoke function.
I found the value of offset is -1001 in mysql sometimes.
there is the two function:
<pre>def consumer_function(self):
    try:
        while self._is_alive:
            record = self._consumer.poll(5)
            if record is None:
                continue
            if record.error():
                if record.error().code() == KafkaError._PARTITION_EOF:
                    # End of partition event
                    logger.error('%% %s [%d] reached end at offset %d' %
                                     (record.topic(), record.partition(), record.offset()))
                elif record.error():
                    # Error
                    raise KafkaException(record.error())
            else:
                try:
                    self.call_back(record)
                except Exception as e:
                    logger.error("%s consume msg[%s:%d:%d] failed msg:%s" %(self._groupId, record.topic(),record.partition(),record.offset(),record.value()))
                    logger.error("exception:%s", e)
                mi_data_db = DBConnector().connect(db='midatadb')
                mi_data_cur = mi_data_db.cursor()
                mi_data_cur.execute("update r_kafka_consumer_offset set offset = %s"
                                    " where group_id = %s and topic = %s and partition = %s",
                                    [record.offset(), self._groupId, record.topic(), record.partition()])
                mi_data_db.commit()
                mi_data_db.close()
    except Exception as e:
        self._consumer.close()
        print ("Error:%s", (format(e)))</pre>

<pre>
def on_revoke_callback(consumer, partitions):
    mi_data_db = DBConnector().connect(db='midatadb')
    mi_data_cur = mi_data_db.cursor()
    group_id = consumer_group_id_dict[consumer]
    offset_to_upsert = []
    for partition in partitions:
        offset_to_upsert.append([group_id, partition.topic, partition.partition, consumer.position([partition])[0].offset])
    mi_data_cur.executemany("insert into r_kafka_consumer_offset values(%s,%s,%s,%s)"
                            " on duplicate key update offset = values(offset)", offset_to_upsert)
    mi_data_db.commit()
    mi_data_db.close()
</pre>

**Comment by edenhill** [comment]
The offset is not set (-1001 is the default/unset/invalid value) in the on_assign/on_revoke callbacks, if you want the current offset call .position() and make sure to only commit offsets that are >= 0.
