### ISSUE TITLE
Memory leak in cfl_PyUnistr_AsUTF8

### ISSUE THREAD

**Issue by stephan-hof** [confluentinc/confluent-kafka-python#198]
In `confluent_kafka.h` this function has the following definition: `#define cfl_PyUnistr_AsUTF8(X) PyBytes_AsString(PyUnicode_AsUTF8String(X))`

The problems is that `PyUnicode_AsUTF8String` returns a new reference which is never released via `Py_DECREF` later on. Which means the return value of `PyUnicode_AsUTF8String` leaks memory.

I know a proper fix is hard, because the `Py_DECREF` must be deferred to the point where the result of `PyUnicode_AsUTF8String` is not used any more (considering also error cases ..).

I did not have problems with this leak yet, because the places where it happens are not triggered often in my code. However as soon as this is called frequently, for example `TopicPartition_str0` with an `errstr` set, it will have an impact.

**Comment by edenhill** [comment]
Ooh, good catch, thanks!
