### ISSUE TITLE
How to reset offset of (multiple) topics?

### ISSUE THREAD

**Issue by pvanderlinden** [confluentinc/confluent-kafka-python#201]
I try to reset the offset of a group for a topic (or better: regex of topics). But I can't get it working with confluent kafka:

The script:
```
def reset_offsets(group_id, topic, bootstrap_servers):
    consumer = Consumer({'bootstrap.servers': bootstrap_servers, 'group.id': group_id})
    def reset_offset(consumer, partitions):
        for p in partitions:
            p.offset = OFFSET_BEGINNING
        print('assign', partitions)
        consumer.commit(offsets=partitions, async=False)
    consumer.subscribe([topic], on_assign=reset_offset)
    consumer.poll(1)
    consumer.close()
```
The error:
```
Traceback (most recent call last):
  File "scripts/reset_consumer_group.py", line 29, in <module>
    reset_offsets(sys.argv[2], sys.argv[3], sys.argv[1])
  File "scripts/reset_consumer_group.py", line 23, in reset_offsets
    while consumer.poll(10000):
  File "scripts/reset_consumer_group.py", line 21, in reset_offset
    consumer.commit(offsets=partitions, async=False)
cimpl.KafkaException: KafkaError{code=_NO_OFFSET,val=-168,str="Commit failed: Local: No offset stored"}
Segmentation fault (core dumped)
```

**Comment by fpietka** [comment]
You need to replace 
```python
consumer.commit(offsets=partitions, async=False)
```
with 
```python
consumer.assign(partitions)
```

Also I found that I needed to wait for the first message before closing.

**Comment by pvanderlinden** [comment]
I'm still struggling with how to get this working. I tried assigning, assigning and then committing (without the offsets), which both don't work.

The commit method doesn't seem to work at all, it always raises an exception no matter how you use it.

**Comment by fpietka** [comment]
In my case I didn't committed anything about the partitions (don't know if it's the way it's intended). But, as I said, I had to poll from the same consumer instance right away.

**Comment by pvanderlinden** [comment]
I tried the following:
- assign, with auto commit off, then commit: exception
- assign, then poll till you get a message: that seems to reset the partition/topic to the beginning + 1 off the topic/partition you happened to get a message from, not everything, and not actually to the beginning (because you actually consume a message)

**Comment by fpietka** [comment]
I end up having that situation too, so I (for now) only apply rewind before starting polling my topic.

If there is a way to rewind without having to start polling right away, I'd be really interested ^^

**Comment by pvanderlinden** [comment]
We might have different use cases as well, I just need to be able to restart it every now and then (mainly while testing consuming the feed), but in general continue where I left of.

**Comment by edenhill** [comment]
The following snipper will (re)set the committed offsets for a given group and topic partition:
```
from confluent_kafka import Consumer, TopicPartition

c = Consumer({'bootstrap.servers':'eden','group.id':'x2'})
parts = [TopicPartition('test',0,15),TopicPartition('test',1,90)]
print('Current committed offsets: ', c.committed(parts))
# Commit new offsets
c.commit(offsets=parts, async=False)
print('New committed offsets: ', c.committed(parts))
```

**Comment by pvanderlinden** [comment]
@edenhill 
While that works, it is not usable though:
- you have to know which partitions exist, as there is no way to get the partitions
- relative offsets don't work at all (beginning/end, -x time)

**Comment by messense** [comment]
I am using:

```python
reset_offset = ...

def on_assign(consumer, partitions):
    consumer.assign(partitions)
    for part in partitions:
        low_mark, high_mark = consumer.get_watermark_offsets(part)
        if reset_offset == 'earliest':
            part.offset = low_mark
        elif reset_offset == 'latest':
            part.offset = high_mark
    consumer.commit(offsets=partitions, async=False)
```

seems working.

**Comment by DachuanZhao** [comment]
> I am using:
> 
> ```python
> reset_offset = ...
> 
> def on_assign(consumer, partitions):
>     consumer.assign(partitions)
>     for part in partitions:
>         low_mark, high_mark = consumer.get_watermark_offsets(part)
>         if reset_offset == 'earliest':
>             part.offset = low_mark
>         elif reset_offset == 'latest':
>             part.offset = high_mark
>     consumer.commit(offsets=partitions, async=False)
> ```
> 
> seems working.

How to get partitions ?

**Comment by DachuanZhao** [comment]
> @edenhill
> While that works, it is not usable though:
> 
> * you have to know which partitions exist, as there is no way to get the partitions
> * relative offsets don't work at all (beginning/end, -x time)

Have you found the best solution ?   : )

**Comment by nicai** [comment]
What works for me is:

reset_offset = ...

def on_assign(consumer, partitions):
    consumer.assign(partitions)
    for part in partitions:
        low_mark, high_mark = consumer.get_watermark_offsets(part)
        if reset_offset == 'earliest':
            part.offset = low_mark
        elif reset_offset == 'latest':
            part.offset = high_mark
        consumer.seek(part)
    consumer.commit(offsets=partitions, async=False)
