### ISSUE TITLE
Build error during pip install

### ISSUE THREAD

**Issue by srawat** [confluentinc/confluent-kafka-python#202]
Failed to build/install confluent-kafka using pip.
Below is the error i am getting. 
librdkafka-dev is already the newest version. 

sudo pip install confluent-kafka

Collecting confluent-kafka
  Using cached confluent-kafka-0.9.4.tar.gz
Building wheels for collected packages: confluent-kafka
  Running setup.py bdist_wheel for confluent-kafka ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pr10V1/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpWORCRKpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/confluent_kafka
  copying confluent_kafka/__init__.py -> build/lib.linux-x86_64-2.7/confluent_kafka
  creating build/lib.linux-x86_64-2.7/confluent_kafka/avro
  copying confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-x86_64-2.7/confluent_kafka/avro
  copying confluent_kafka/avro/__init__.py -> build/lib.linux-x86_64-2.7/confluent_kafka/avro
  creating build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
  copying confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
  copying confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
  copying confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
  copying confluent_kafka/kafkatest/__init__.py -> build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
  creating build/lib.linux-x86_64-2.7/confluent_kafka/avro/serializer
  copying confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-2.7/confluent_kafka/avro/serializer
  copying confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-2.7/confluent_kafka/avro/serializer
  running build_ext
  building 'confluent_kafka.cimpl' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/confluent_kafka
  creating build/temp.linux-x86_64-2.7/confluent_kafka/src
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c confluent_kafka/src/confluent_kafka.c -o build/temp.linux-x86_64-2.7/confluent_kafka/src/confluent_kafka.o
  In file included from confluent_kafka/src/confluent_kafka.c:17:0:
  confluent_kafka/src/confluent_kafka.h:227:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’
   PyObject *c_parts_to_py (const rd_kafka_topic_partition_list_t *c_parts);
   ^
  confluent_kafka/src/confluent_kafka.h:228:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’
   rd_kafka_topic_partition_list_t *py_to_c_parts (PyObject *plist);
   ^
  confluent_kafka/src/confluent_kafka.h:253:2: error: unknown type name ‘rd_kafka_timestamp_type_t’
    rd_kafka_timestamp_type_t tstype;
    ^
  confluent_kafka/src/confluent_kafka.c: In function ‘KafkaError_name’:
  confluent_kafka/src/confluent_kafka.c:72:2: warning: implicit declaration of function ‘rd_kafka_err2name’ [-Wimplicit-function-declaration]
    return cfl_PyUnistr(_FromString(rd_kafka_err2name(self->code)));
    ^
  confluent_kafka/src/confluent_kafka.c:72:2: warning: passing argument 1 of ‘PyUnicodeUCS4_FromString’ makes pointer from integer without a cast [enabled by default]
  In file included from /usr/include/python2.7/Python.h:85:0,
                   from confluent_kafka/src/confluent_kafka.h:17,
                   from confluent_kafka/src/confluent_kafka.c:17:
  /usr/include/python2.7/unicodeobject.h:281:31: note: expected ‘const char *’ but argument is of type ‘int’
   # define PyUnicode_FromString PyUnicodeUCS4_FromString
                                 ^
  /usr/include/python2.7/unicodeobject.h:477:23: note: in expansion of macro ‘PyUnicode_FromString’
   PyAPI_FUNC(PyObject*) PyUnicode_FromString(
                         ^
  confluent_kafka/src/confluent_kafka.c: In function ‘Message_new0’:
  confluent_kafka/src/confluent_kafka.c:557:2: warning: implicit declaration of function ‘rd_kafka_message_timestamp’ [-Wimplicit-function-declaration]
    self->timestamp = rd_kafka_message_timestamp(rkm, &self->tstype);
    ^
  confluent_kafka/src/confluent_kafka.c: In function ‘TopicPartition_init’:
  confluent_kafka/src/confluent_kafka.c:609:21: error: ‘RD_KAFKA_OFFSET_INVALID’ undeclared (first use in this function)
    long long offset = RD_KAFKA_OFFSET_INVALID;
                       ^
  confluent_kafka/src/confluent_kafka.c:609:21: note: each undeclared identifier is reported only once for each function it appears in
  confluent_kafka/src/confluent_kafka.c: At top level:
  confluent_kafka/src/confluent_kafka.c:816:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’
   PyObject *c_parts_to_py (const rd_kafka_topic_partition_list_t *c_parts) {
   ^
  confluent_kafka/src/confluent_kafka.c: In function ‘c_parts_to_py’:
  confluent_kafka/src/confluent_kafka.c:820:28: error: request for member ‘cnt’ in something not a structure or union
    parts = PyList_New(c_parts->cnt);
                              ^
  confluent_kafka/src/confluent_kafka.c:822:26: error: request for member ‘cnt’ in something not a structure or union
    for (i = 0 ; i < c_parts->cnt ; i++) {
                            ^
  confluent_kafka/src/confluent_kafka.c:823:3: error: unknown type name ‘rd_kafka_topic_partition_t’
     const rd_kafka_topic_partition_t *rktpar = &c_parts->elems[i];
     ^
  confluent_kafka/src/confluent_kafka.c:823:54: error: request for member ‘elems’ in something not a structure or union
     const rd_kafka_topic_partition_t *rktpar = &c_parts->elems[i];
                                                        ^
  In file included from /usr/include/python2.7/Python.h:100:0,
                   from confluent_kafka/src/confluent_kafka.h:17,
                   from confluent_kafka/src/confluent_kafka.c:17:
  confluent_kafka/src/confluent_kafka.c:826:12: error: request for member ‘topic’ in something not a structure or union
        rktpar->topic, rktpar->partition,
              ^
  /usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’
   #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))
                                                                            ^
  confluent_kafka/src/confluent_kafka.c:826:27: error: request for member ‘partition’ in something not a structure or union
        rktpar->topic, rktpar->partition,
                             ^
  /usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’
   #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))
                                                                            ^
  confluent_kafka/src/confluent_kafka.c:827:12: error: request for member ‘offset’ in something not a structure or union
        rktpar->offset, rktpar->err));
              ^
  /usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’
   #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))
                                                                            ^
  confluent_kafka/src/confluent_kafka.c:827:28: error: request for member ‘err’ in something not a structure or union
        rktpar->offset, rktpar->err));
                              ^
  /usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’
   #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))
                                                                            ^
  confluent_kafka/src/confluent_kafka.c: At top level:
  confluent_kafka/src/confluent_kafka.c:839:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’
   rd_kafka_topic_partition_list_t *py_to_c_parts (PyObject *plist) {
   ^
  confluent_kafka/src/confluent_kafka.c: In function ‘py_to_c_parts’:
  confluent_kafka/src/confluent_kafka.c:840:2: error: unknown type name ‘rd_kafka_topic_partition_list_t’
    rd_kafka_topic_partition_list_t *c_parts;
    ^
  confluent_kafka/src/confluent_kafka.c:849:2: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_new’ [-Wimplicit-function-declaration]
    c_parts = rd_kafka_topic_partition_list_new((int)PyList_Size(plist));
    ^
  confluent_kafka/src/confluent_kafka.c:849:10: warning: assignment makes pointer from integer without a cast [enabled by default]
    c_parts = rd_kafka_topic_partition_list_new((int)PyList_Size(plist));
            ^
  confluent_kafka/src/confluent_kafka.c:860:4: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_destroy’ [-Wimplicit-function-declaration]
      rd_kafka_topic_partition_list_destroy(c_parts);
      ^
  confluent_kafka/src/confluent_kafka.c:864:3: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_add’ [-Wimplicit-function-declaration]
     rd_kafka_topic_partition_list_add(c_parts,
     ^
  confluent_kafka/src/confluent_kafka.c:866:23: error: invalid type argument of ‘->’ (have ‘int’)
           tp->partition)->offset =
                         ^
  confluent_kafka/src/confluent_kafka.c: In function ‘error_cb’:
  confluent_kafka/src/confluent_kafka.c:902:3: warning: implicit declaration of function ‘rd_kafka_yield’ [-Wimplicit-function-declaration]
     rd_kafka_yield(h->rk);
     ^
  confluent_kafka/src/confluent_kafka.c: In function ‘producer_conf_set_special’:
  confluent_kafka/src/confluent_kafka.c:1075:13: error: ‘rd_kafka_msg_partitioner_consistent’ undeclared (first use in this function)
        tconf, rd_kafka_msg_partitioner_consistent);
               ^
  confluent_kafka/src/confluent_kafka.c:1078:13: error: ‘rd_kafka_msg_partitioner_consistent_random’ undeclared (first use in this function)
        tconf, rd_kafka_msg_partitioner_consistent_random);
               ^
  In file included from confluent_kafka/src/confluent_kafka.c:17:0:
  confluent_kafka/src/confluent_kafka.c:1105:6: error: ‘RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED’ undeclared (first use in this function)
        RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED,
        ^
  confluent_kafka/src/confluent_kafka.h:106:35: note: in definition of macro ‘cfl_PyErr_Format’
     PyObject *_eo = KafkaError_new0(err, __VA_ARGS__); \
                                     ^
  confluent_kafka/src/confluent_kafka.c: In function ‘common_conf_setup’:
  confluent_kafka/src/confluent_kafka.c:1314:2: warning: implicit declaration of function ‘rd_kafka_conf_set_default_topic_conf’ [-Wimplicit-function-declaration]
    rd_kafka_conf_set_default_topic_conf(conf, tconf);
    ^
  confluent_kafka/src/confluent_kafka.c: In function ‘KafkaError_add_errs’:
  confluent_kafka/src/confluent_kafka.c:1438:2: warning: implicit declaration of function ‘rd_kafka_get_err_descs’ [-Wimplicit-function-declaration]
    rd_kafka_get_err_descs(&descs, &cnt);
    ^
  confluent_kafka/src/confluent_kafka.c:1474:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
     if (!descs[i].desc)
     ^
  confluent_kafka/src/confluent_kafka.c:1474:13: error: dereferencing pointer to incomplete type
     if (!descs[i].desc)
               ^
  confluent_kafka/src/confluent_kafka.c:1477:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
     code = PyLong_FromLong(descs[i].code);
     ^
  confluent_kafka/src/confluent_kafka.c:1477:31: error: dereferencing pointer to incomplete type
     code = PyLong_FromLong(descs[i].code);
                                 ^
  confluent_kafka/src/confluent_kafka.c:1479:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
     PyDict_SetItemString(dict, descs[i].name, code);
     ^
  confluent_kafka/src/confluent_kafka.c:1479:35: error: dereferencing pointer to incomplete type
     PyDict_SetItemString(dict, descs[i].name, code);
                                     ^
  confluent_kafka/src/confluent_kafka.c:1483:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
     _PRINT("| %-*.*s | %-*.*s |\n"
     ^
  confluent_kafka/src/confluent_kafka.c:1485:33: error: dereferencing pointer to incomplete type
            _COL1_W, _COL1_W, descs[i].name,
                                   ^
  confluent_kafka/src/confluent_kafka.c:1452:43: note: in definition of macro ‘_PRINT’
     _len = snprintf(tmpdoc, sizeof(tmpdoc), __VA_ARGS__); \
                                             ^
  confluent_kafka/src/confluent_kafka.c:1483:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
     _PRINT("| %-*.*s | %-*.*s |\n"
     ^
  confluent_kafka/src/confluent_kafka.c:1486:33: error: dereferencing pointer to incomplete type
            _COL2_W, _COL2_W, descs[i].desc,
                                   ^
  confluent_kafka/src/confluent_kafka.c:1452:43: note: in definition of macro ‘_PRINT’
     _len = snprintf(tmpdoc, sizeof(tmpdoc), __VA_ARGS__); \
                                             ^
  confluent_kafka/src/confluent_kafka.c: In function ‘_init_cimpl’:
  confluent_kafka/src/confluent_kafka.c:1561:56: error: ‘RD_KAFKA_TIMESTAMP_NOT_AVAILABLE’ undeclared (first use in this function)
    PyModule_AddIntConstant(m, "TIMESTAMP_NOT_AVAILABLE", RD_KAFKA_TIMESTAMP_NOT_AVAILABLE);
                                                          ^
  confluent_kafka/src/confluent_kafka.c:1562:54: error: ‘RD_KAFKA_TIMESTAMP_CREATE_TIME’ undeclared (first use in this function)
    PyModule_AddIntConstant(m, "TIMESTAMP_CREATE_TIME", RD_KAFKA_TIMESTAMP_CREATE_TIME);
                                                        ^
  confluent_kafka/src/confluent_kafka.c:1563:58: error: ‘RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME’ undeclared (first use in this function)
    PyModule_AddIntConstant(m, "TIMESTAMP_LOG_APPEND_TIME", RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME);
                                                            ^
  confluent_kafka/src/confluent_kafka.c:1568:54: error: ‘RD_KAFKA_OFFSET_INVALID’ undeclared (first use in this function)
           PyModule_AddIntConstant(m, "OFFSET_INVALID", RD_KAFKA_OFFSET_INVALID);
                                                        ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for confluent-kafka
  Running setup.py clean for confluent-kafka
Failed to build confluent-kafka
Installing collected packages: confluent-kafka
  Running setup.py install for confluent-kafka ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pr10V1/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-r8ZCdw-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/confluent_kafka
    copying confluent_kafka/__init__.py -> build/lib.linux-x86_64-2.7/confluent_kafka
    creating build/lib.linux-x86_64-2.7/confluent_kafka/avro
    copying confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-x86_64-2.7/confluent_kafka/avro
    copying confluent_kafka/avro/__init__.py -> build/lib.linux-x86_64-2.7/confluent_kafka/avro
    creating build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/__init__.py -> build/lib.linux-x86_64-2.7/confluent_kafka/kafkatest
    creating build/lib.linux-x86_64-2.7/confluent_kafka/avro/serializer
    copying confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-2.7/confluent_kafka/avro/serializer
    copying confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-2.7/confluent_kafka/avro/serializer
    running build_ext
    building 'confluent_kafka.cimpl' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/confluent_kafka
    creating build/temp.linux-x86_64-2.7/confluent_kafka/src
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c confluent_kafka/src/confluent_kafka.c -o build/temp.linux-x86_64-2.7/confluent_kafka/src/confluent_kafka.o
    In file included from confluent_kafka/src/confluent_kafka.c:17:0:
    confluent_kafka/src/confluent_kafka.h:227:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’
     PyObject *c_parts_to_py (const rd_kafka_topic_partition_list_t *c_parts);
     ^
    confluent_kafka/src/confluent_kafka.h:228:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’
     rd_kafka_topic_partition_list_t *py_to_c_parts (PyObject *plist);
     ^
    confluent_kafka/src/confluent_kafka.h:253:2: error: unknown type name ‘rd_kafka_timestamp_type_t’
      rd_kafka_timestamp_type_t tstype;
      ^
    confluent_kafka/src/confluent_kafka.c: In function ‘KafkaError_name’:
    confluent_kafka/src/confluent_kafka.c:72:2: warning: implicit declaration of function ‘rd_kafka_err2name’ [-Wimplicit-function-declaration]
      return cfl_PyUnistr(_FromString(rd_kafka_err2name(self->code)));
      ^
    confluent_kafka/src/confluent_kafka.c:72:2: warning: passing argument 1 of ‘PyUnicodeUCS4_FromString’ makes pointer from integer without a cast [enabled by default]
    In file included from /usr/include/python2.7/Python.h:85:0,
                     from confluent_kafka/src/confluent_kafka.h:17,
                     from confluent_kafka/src/confluent_kafka.c:17:
    /usr/include/python2.7/unicodeobject.h:281:31: note: expected ‘const char *’ but argument is of type ‘int’
     # define PyUnicode_FromString PyUnicodeUCS4_FromString
                                   ^
    /usr/include/python2.7/unicodeobject.h:477:23: note: in expansion of macro ‘PyUnicode_FromString’
     PyAPI_FUNC(PyObject*) PyUnicode_FromString(
                           ^
    confluent_kafka/src/confluent_kafka.c: In function ‘Message_new0’:
    confluent_kafka/src/confluent_kafka.c:557:2: warning: implicit declaration of function ‘rd_kafka_message_timestamp’ [-Wimplicit-function-declaration]
      self->timestamp = rd_kafka_message_timestamp(rkm, &self->tstype);
      ^
    confluent_kafka/src/confluent_kafka.c: In function ‘TopicPartition_init’:
    confluent_kafka/src/confluent_kafka.c:609:21: error: ‘RD_KAFKA_OFFSET_INVALID’ undeclared (first use in this function)
      long long offset = RD_KAFKA_OFFSET_INVALID;
                         ^
    confluent_kafka/src/confluent_kafka.c:609:21: note: each undeclared identifier is reported only once for each function it appears in
    confluent_kafka/src/confluent_kafka.c: At top level:
    confluent_kafka/src/confluent_kafka.c:816:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’
     PyObject *c_parts_to_py (const rd_kafka_topic_partition_list_t *c_parts) {
     ^
    confluent_kafka/src/confluent_kafka.c: In function ‘c_parts_to_py’:
    confluent_kafka/src/confluent_kafka.c:820:28: error: request for member ‘cnt’ in something not a structure or union
      parts = PyList_New(c_parts->cnt);
                                ^
    confluent_kafka/src/confluent_kafka.c:822:26: error: request for member ‘cnt’ in something not a structure or union
      for (i = 0 ; i < c_parts->cnt ; i++) {
                              ^
    confluent_kafka/src/confluent_kafka.c:823:3: error: unknown type name ‘rd_kafka_topic_partition_t’
       const rd_kafka_topic_partition_t *rktpar = &c_parts->elems[i];
       ^
    confluent_kafka/src/confluent_kafka.c:823:54: error: request for member ‘elems’ in something not a structure or union
       const rd_kafka_topic_partition_t *rktpar = &c_parts->elems[i];
                                                          ^
    In file included from /usr/include/python2.7/Python.h:100:0,
                     from confluent_kafka/src/confluent_kafka.h:17,
                     from confluent_kafka/src/confluent_kafka.c:17:
    confluent_kafka/src/confluent_kafka.c:826:12: error: request for member ‘topic’ in something not a structure or union
          rktpar->topic, rktpar->partition,
                ^
    /usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’
     #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))
                                                                              ^
    confluent_kafka/src/confluent_kafka.c:826:27: error: request for member ‘partition’ in something not a structure or union
          rktpar->topic, rktpar->partition,
                               ^
    /usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’
     #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))
                                                                              ^
    confluent_kafka/src/confluent_kafka.c:827:12: error: request for member ‘offset’ in something not a structure or union
          rktpar->offset, rktpar->err));
                ^
    /usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’
     #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))
                                                                              ^
    confluent_kafka/src/confluent_kafka.c:827:28: error: request for member ‘err’ in something not a structure or union
          rktpar->offset, rktpar->err));
                                ^
    /usr/include/python2.7/listobject.h:62:74: note: in definition of macro ‘PyList_SET_ITEM’
     #define PyList_SET_ITEM(op, i, v) (((PyListObject *)(op))->ob_item[i] = (v))
                                                                              ^
    confluent_kafka/src/confluent_kafka.c: At top level:
    confluent_kafka/src/confluent_kafka.c:839:1: error: unknown type name ‘rd_kafka_topic_partition_list_t’
     rd_kafka_topic_partition_list_t *py_to_c_parts (PyObject *plist) {
     ^
    confluent_kafka/src/confluent_kafka.c: In function ‘py_to_c_parts’:
    confluent_kafka/src/confluent_kafka.c:840:2: error: unknown type name ‘rd_kafka_topic_partition_list_t’
      rd_kafka_topic_partition_list_t *c_parts;
      ^
    confluent_kafka/src/confluent_kafka.c:849:2: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_new’ [-Wimplicit-function-declaration]
      c_parts = rd_kafka_topic_partition_list_new((int)PyList_Size(plist));
      ^
    confluent_kafka/src/confluent_kafka.c:849:10: warning: assignment makes pointer from integer without a cast [enabled by default]
      c_parts = rd_kafka_topic_partition_list_new((int)PyList_Size(plist));
              ^
    confluent_kafka/src/confluent_kafka.c:860:4: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_destroy’ [-Wimplicit-function-declaration]
        rd_kafka_topic_partition_list_destroy(c_parts);
        ^
    confluent_kafka/src/confluent_kafka.c:864:3: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_add’ [-Wimplicit-function-declaration]
       rd_kafka_topic_partition_list_add(c_parts,
       ^
    confluent_kafka/src/confluent_kafka.c:866:23: error: invalid type argument of ‘->’ (have ‘int’)
             tp->partition)->offset =
                           ^
    confluent_kafka/src/confluent_kafka.c: In function ‘error_cb’:
    confluent_kafka/src/confluent_kafka.c:902:3: warning: implicit declaration of function ‘rd_kafka_yield’ [-Wimplicit-function-declaration]
       rd_kafka_yield(h->rk);
       ^
    confluent_kafka/src/confluent_kafka.c: In function ‘producer_conf_set_special’:
    confluent_kafka/src/confluent_kafka.c:1075:13: error: ‘rd_kafka_msg_partitioner_consistent’ undeclared (first use in this function)
          tconf, rd_kafka_msg_partitioner_consistent);
                 ^
    confluent_kafka/src/confluent_kafka.c:1078:13: error: ‘rd_kafka_msg_partitioner_consistent_random’ undeclared (first use in this function)
          tconf, rd_kafka_msg_partitioner_consistent_random);
                 ^
    In file included from confluent_kafka/src/confluent_kafka.c:17:0:
    confluent_kafka/src/confluent_kafka.c:1105:6: error: ‘RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED’ undeclared (first use in this function)
          RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED,
          ^
    confluent_kafka/src/confluent_kafka.h:106:35: note: in definition of macro ‘cfl_PyErr_Format’
       PyObject *_eo = KafkaError_new0(err, __VA_ARGS__); \
                                       ^
    confluent_kafka/src/confluent_kafka.c: In function ‘common_conf_setup’:
    confluent_kafka/src/confluent_kafka.c:1314:2: warning: implicit declaration of function ‘rd_kafka_conf_set_default_topic_conf’ [-Wimplicit-function-declaration]
      rd_kafka_conf_set_default_topic_conf(conf, tconf);
      ^
    confluent_kafka/src/confluent_kafka.c: In function ‘KafkaError_add_errs’:
    confluent_kafka/src/confluent_kafka.c:1438:2: warning: implicit declaration of function ‘rd_kafka_get_err_descs’ [-Wimplicit-function-declaration]
      rd_kafka_get_err_descs(&descs, &cnt);
      ^
    confluent_kafka/src/confluent_kafka.c:1474:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
       if (!descs[i].desc)
       ^
    confluent_kafka/src/confluent_kafka.c:1474:13: error: dereferencing pointer to incomplete type
       if (!descs[i].desc)
                 ^
    confluent_kafka/src/confluent_kafka.c:1477:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
       code = PyLong_FromLong(descs[i].code);
       ^
    confluent_kafka/src/confluent_kafka.c:1477:31: error: dereferencing pointer to incomplete type
       code = PyLong_FromLong(descs[i].code);
                                   ^
    confluent_kafka/src/confluent_kafka.c:1479:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
       PyDict_SetItemString(dict, descs[i].name, code);
       ^
    confluent_kafka/src/confluent_kafka.c:1479:35: error: dereferencing pointer to incomplete type
       PyDict_SetItemString(dict, descs[i].name, code);
                                       ^
    confluent_kafka/src/confluent_kafka.c:1483:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
       _PRINT("| %-*.*s | %-*.*s |\n"
       ^
    confluent_kafka/src/confluent_kafka.c:1485:33: error: dereferencing pointer to incomplete type
              _COL1_W, _COL1_W, descs[i].name,
                                     ^
    confluent_kafka/src/confluent_kafka.c:1452:43: note: in definition of macro ‘_PRINT’
       _len = snprintf(tmpdoc, sizeof(tmpdoc), __VA_ARGS__); \
                                               ^
    confluent_kafka/src/confluent_kafka.c:1483:3: error: invalid use of undefined type ‘struct rd_kafka_err_desc’
       _PRINT("| %-*.*s | %-*.*s |\n"
       ^
    confluent_kafka/src/confluent_kafka.c:1486:33: error: dereferencing pointer to incomplete type
              _COL2_W, _COL2_W, descs[i].desc,
                                     ^
    confluent_kafka/src/confluent_kafka.c:1452:43: note: in definition of macro ‘_PRINT’
       _len = snprintf(tmpdoc, sizeof(tmpdoc), __VA_ARGS__); \
                                               ^
    confluent_kafka/src/confluent_kafka.c: In function ‘_init_cimpl’:
    confluent_kafka/src/confluent_kafka.c:1561:56: error: ‘RD_KAFKA_TIMESTAMP_NOT_AVAILABLE’ undeclared (first use in this function)
      PyModule_AddIntConstant(m, "TIMESTAMP_NOT_AVAILABLE", RD_KAFKA_TIMESTAMP_NOT_AVAILABLE);
                                                            ^
    confluent_kafka/src/confluent_kafka.c:1562:54: error: ‘RD_KAFKA_TIMESTAMP_CREATE_TIME’ undeclared (first use in this function)
      PyModule_AddIntConstant(m, "TIMESTAMP_CREATE_TIME", RD_KAFKA_TIMESTAMP_CREATE_TIME);
                                                          ^
    confluent_kafka/src/confluent_kafka.c:1563:58: error: ‘RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME’ undeclared (first use in this function)
      PyModule_AddIntConstant(m, "TIMESTAMP_LOG_APPEND_TIME", RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME);
                                                              ^
    confluent_kafka/src/confluent_kafka.c:1568:54: error: ‘RD_KAFKA_OFFSET_INVALID’ undeclared (first use in this function)
             PyModule_AddIntConstant(m, "OFFSET_INVALID", RD_KAFKA_OFFSET_INVALID);
                                                          ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pr10V1/confluent-kafka/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-r8ZCdw-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-pr10V1/confluent-kafka/

**Comment by edenhill** [comment]
Your librdkafka version is too old, please install librdkafka 0.9.4 or later:
http://docs.confluent.io/current/installation.html#installation-apt

**Comment by ddehghan** [comment]
in case anyone else gets here: this works for docker installs:


```
RUN apt-get update && \
    apt-get install -y \
    software-properties-common apt-transport-https


RUN wget -qO - https://packages.confluent.io/deb/4.0/archive.key | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.0 stable main"

RUN apt-get update && \
    apt-get install -y \
    librdkafka-dev

RUN pip install -r /data/requirements.txt
```
