### ISSUE TITLE
_INVALID_ARG for config param 'bootstrap.servers'

### ISSUE THREAD

**Issue by jmwilkinson** [confluentinc/confluent-kafka-python#203]
Getting a weird error when trying to create a `Producer`. Not sure what to do to troubleshoot/fix it.

```python
Python 2.7.13 (default, Apr 25 2017, 10:13:13)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from confluent_kafka import Producer
>>> p = Producer({'bootstrap.servers': 'Kafka01:9092'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such config
>>>
```

Checked `librdkafka-devel`, confluent-kafka used to build:

```bash
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
 * epel: mirrors.cat.pdx.edu
 * extras: mirror.cisp.com
Installed Packages
Name        : librdkafka-devel
Arch        : x86_64
Version     : 0.9.5_confluent3.2.1
Release     : 1.el7
Size        : 1.7 M
Repo        : installed
From repo   : Confluent.dist
Summary     : The Apache Kafka C library (Development Environment)
URL         : https://github.com/edenhill/librdkafka
License     : BSD-2-Clause
Description : librdkafka is the C/C++ client library implementation of the Apache Kafka protocol, containing both Producer and Consumer support.
            :
            : This package contains headers and libraries required to build applications
            : using librdkafka.
```

It seems to me that it should work. I also don't know why the error message when trying to create the `Producer` seems to be cut off.

EDIT: This is on Centos7

**Comment by jmwilkinson** [comment]
It appears this has to do with having built python from source. I need to install `confluent-kafka` without the package `python-devel`, instead specifying manually the location of the  python headers. Not sure how to do this.

**Comment by jmwilkinson** [comment]
Ok, so I needed to follow the instructions to build from source:

I downloaded the latest version of the `confluent-kafka` package:

```bash
wget https://github.com/confluentinc/confluent-kafka-python/archive/v0.9.4.tar.gz
```

I unpacked it, and went into the directory:

```bash
tar -xvf v0.9.4.tar.gz && cd confluent-kafka-python-0.9.4/
```

I built the package using my header files location:

```bash
C_INCLUDE_PATH=/usr/local/include/python2.7 python setup.py build
```

I then copied the output to my site-packages location:

```bash
cp build/lib.linux-x86_64-2.7/confluent_kafka /usr/local/lib/python2.7/site-packages/ -R
```

This solved my problem. It appears to be working now.

**Comment by edenhill** [comment]
That does look weird indeed and I don't have a good explanation to explain why this happened more than it might be caused by the module being built for another version of Python than the interpreter version you are using, but that's just a guess.

Happy you solved it.
