### ISSUE TITLE
consumer segmentation fault upon subscribe a second time

### ISSUE THREAD

**Issue by zhaojack** [confluentinc/confluent-kafka-python#204]
Hi,

I don't know much about kafka, so it's very possible I'm using it incorrectly, in which case apologies in advance.

I have a Consumer object. I subscribed it to a kafka topic and was able to receive messages fine with it. I'm having the consumer stop consuming and closing upon reaching end of partition. However, if I were to then use the same consumer to subscribe again to the same topic, I get a segmentation fault.

**Versions**
python 2.7.5, confluent_kafka 0.9.4, librdkafka 0.9.4

```
[confluent-kafka] > pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
certifi (2017.4.17)
chardet (3.0.4)
confluent-kafka (0.9.4)
dnspython (1.12.0)
funcsigs (1.0.2)
idna (2.5)
mock (2.0.0)
pbr (3.0.1)
pip (9.0.1)
py (1.4.34)
pytest (3.0.1)
pytest-runner (2.9)
requests (2.17.3)
setuptools (36.0.1)
six (1.10.0)
urllib3 (1.21.1)
wheel (0.30.0a0)
```

```
[confluent-kafka] > rpm -qa | grep librdkafka
librdkafka-0.9.4-1.el7.x86_64
librdkafka-devel-0.9.4-1.el7.x86_64
```

**Steps To Reproduce**

1. start up kafka
(I followed this: https://github.com/confluentinc/cp-docker-images/wiki/Getting-Started)
```
docker run -d --net=host --name=zookeeper -e ZOOKEEPER_CLIENT_PORT=32181 -e ZOOKEEPER_TICK_TIME=2000 confluentinc/cp-zookeeper:3.0.0
docker run -d --net=host --name=kafka -e KAFKA_ZOOKEEPER_CONNECT=localhost:32181 -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092 confluentinc/cp-kafka:3.0.0
docker run --net=host --rm confluentinc/cp-kafka:3.0.0 kafka-topics --create --topic test.topic --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:32181
```
(I also tested against our production kafka and saw the same segfault)

2. run following code:
```python
from confluent_kafka import Producer, Consumer, KafkaError, KafkaException

KAFKA_SERVER = 'localhost:29092'
KAFKA_TOPIC = 'test.topic'
CONSUMER_GROUP = 'test-group'

CONSUMER_CONFIG = {'bootstrap.servers': KAFKA_SERVER,
                   'enable.auto.commit': False,
                   'group.id': CONSUMER_GROUP,
                   'default.topic.config': {'auto.offset.reset': 'earliest'}}


def sendKafkaMessage(topic, message):
    producer = Producer({'bootstrap.servers': KAFKA_SERVER})
    producer.produce(topic, message)
    producer.flush()


def getKafkaMessages(consumer):
    messages = []

    consumer.subscribe([KAFKA_TOPIC])
    try:
        while True:
            message = consumer.poll(timeout=1.0)
            if message is None:
                continue
            error = message.error()
            if error:
                if error.code() == KafkaError._PARTITION_EOF:
                    break
                else:
                    raise KafkaException(error)
            else:
                messages.append(message.value())
                consumer.commit(async=False)
    finally:
        consumer.close()

    return messages


if __name__ == '__main__':
    consumer = Consumer(**CONSUMER_CONFIG)

    sendKafkaMessage(KAFKA_TOPIC, 'message1')
    sendKafkaMessage(KAFKA_TOPIC, 'message2')
    sendKafkaMessage(KAFKA_TOPIC, 'message3')
    sendKafkaMessage(KAFKA_TOPIC, 'message4')
    sendKafkaMessage(KAFKA_TOPIC, 'message5')
    print getKafkaMessages(consumer)

    sendKafkaMessage(KAFKA_TOPIC, 'message6')
    sendKafkaMessage(KAFKA_TOPIC, 'message7')
    sendKafkaMessage(KAFKA_TOPIC, 'message8')
    sendKafkaMessage(KAFKA_TOPIC, 'message9')
    sendKafkaMessage(KAFKA_TOPIC, 'message10')
    print getKafkaMessages(consumer)
```

This will segfault during the second `getKafkaMessages` call, specifically when `consumer.subscribe` runs again. I'm expecting that the consumer would be able to subscribe again and pick up where it left off via consumer group and commit.

Is this a bug or user error?

Thanks for your time!
Jack

**Comment by zhaojack** [comment]
I'm currently working around this by recreating the consumer every time. I don't know whether this is the right thing to do. Any guidance would be great.

Thanks,
Jack

**Comment by edenhill** [comment]
You're not allowed to use the consumer again after you call close() on it,
I suggest removing the close() call, possibly replacing it with unsubscribe() (which is optional),
or creating a new consumer.


Also, creating a producer for each message will be very slow due to the startup costs of the client (initiating connections, acquiring metadata, etc), it is better to reuse an existing producer throughout your application.

**Comment by zhaojack** [comment]
I see. Thanks for the quick answer!

**Comment by amrx101** [comment]
@edenhill Upon unsubscribing and re-subscribing will the consumption start form the time when  it was unsubscribed?

Thanks

**Comment by edenhill** [comment]
When you unsubscribe() the consumer will commit the final offsets that you have consumed, and the subsequent subscribe() will pick them up as the partitions are assigned to the client again.
