### ISSUE TITLE
Possible memory leak? 

### ISSUE THREAD

**Issue by mtrienis** [confluentinc/confluent-kafka-python#206]
> yum list installed | grep librdka
> librdkafka1.x86_64                0.9.5_confluent3.2.1-1.el6        @Confluent.dist
> pip freeze | grep confluent
> confluent-kafka==0.9.4
> cat /etc/redhat-release
> CentOS release 6.8 (Final)

![screen shot 2017-06-18 at 4 35 25 pm](https://user-images.githubusercontent.com/1813821/27265105-5edab760-5444-11e7-9d0a-20518e67421c.png)

I'm running the following command 10 times in a docker container against a 10 broker Kafka cluster in AWS:
```
nohup python27 confluent.py &
```

```
import resource
import time
import confluent_kafka
import json
import logging
import sys


brokers = [
    'xx.xx.xx.xxx:9092'
]

def setup_custom_logger(name):
    formatter = logging.Formatter(fmt='%(asctime)s %(levelname)-8s %(message)s',
                                  datefmt='%Y-%m-%d %H:%M:%S')
    handler = logging.FileHandler('log.txt', mode='w')
    handler.setFormatter(formatter)
    screen_handler = logging.StreamHandler(stream=sys.stdout)
    screen_handler.setFormatter(formatter)
    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    logger.addHandler(handler)
    logger.addHandler(screen_handler)
    return logger


def _stats_callback(jsonStr):
    producer_metrics = json.loads(jsonStr)
    print producer_metrics['msg_cnt']
    print time.time()
    for broker in producer_metrics['brokers']:
        print producer_metrics['brokers'][broker]['throttle']

logger = setup_custom_logger("confluent")

def life_cycle():
    producer_config = {
        'bootstrap.servers': ','.join(brokers),
        'client.id':'anonymous',
        'retry.backoff.ms': 100,
        'message.send.max.retries': 5,
        'stats_cb': _stats_callback,
        'queue.buffering.max.kbytes': 50240,
        'default.topic.config': {'request.required.acks': 1, 'request.timeout.ms': 5000, 'message.timeout.ms': 300000},
        'queue.buffering.max.messages': 100000,
        'queue.buffering.max.ms': 1000,
        'statistics.interval.ms': 60000,
        'socket.timeout.ms': 60000,
        'api.version.request':True,
        'retry.backoff.ms':100,
        'debug':'all'
    }

    producer = confluent_kafka.Producer(producer_config)

    while True:
        current_maximum_memory = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        logger.debug("Maximum memory used = {} KBytes".format(current_maximum_memory))
        time.sleep(5.0)

life_cycle()
```

For a single process the script outputs
> 2017-06-18 17:21:03 DEBUG    Maximum memory used = 15036 KBytes
After an hour we can see that the memory increases  
> 2017-06-18 18:16:07 DEBUG    Maximum memory used = 15556 KBytes

**Comment by edenhill** [comment]
You have stats enabled (with an interval of 1 minute), but you are not calling poll() so the stats will remain queued in librdkafka waiting for your application to dispatch them (through poll()).

**Comment by mtrienis** [comment]
Thank you very much!

**Comment by chengcheng-pei** [comment]
> You have stats enabled (with an interval of 1 minute), but you are not calling poll() so the stats will remain queued in librdkafka waiting for your application to dispatch them (through poll()).

can I call `consume()` instead of `poll()` to dispatch them?
