### ISSUE TITLE
consumer call consumer.poll() failed

### ISSUE THREAD

**Issue by 15663671003** [confluentinc/confluent-kafka-python#207]
I want to know how to solve this problem，
msg = consumer.poll() ,  
msg.error.code()!=KafkaError._PARTITION_EOF
abnormal:
%3|1500587240.288|FAIL|rdkafka#producer-1| [thrd:10.255.84.150:9092/bootstrap]: 10.255.84.150:9092/1: Receive failed: Disconnected
%3|1500587240.288|ERROR|rdkafka#producer-1| [thrd:10.255.84.150:9092/bootstrap]: 10.255.84.150:9092/1: Receive failed: Disconnected
%3|1500587240.288|ERROR|rdkafka#producer-1| [thrd:10.255.84.150:9092/bootstrap]: 1/1 brokers are down
%3|1500587840.410|FAIL|rdkafka#producer-1| [thrd:10.255.84.150:9092/bootstrap]: 10.255.84.150:9092/1: Receive failed: Disconnected
%3|1500587840.410|ERROR|rdkafka#producer-1| [thrd:10.255.84.150:9092/bootstrap]: 10.255.84.150:9092/1: Receive failed: Disconnected
%3|1500588440.537|FAIL|rdkafka#producer-1| [thrd:10.255.84.150:9092/bootstrap]: 10.255.84.150:9092/1: Receive failed: Disconnected
%3|1500588440.537|ERROR|rdkafka#producer-1| [thrd:10.255.84.150:9092/bootstrap]: 10.255.84.150:9092/1: Receive failed: Disconnected
%3|1500588440.537|ERROR|rdkafka#producer-1| [thrd:10.255.84.150:9092/bootstrap]: 1/1 brokers are down

but server has running

**Comment by edenhill** [comment]
That log indicates the broker closed the connection, you should check the broker logs for an exception to see why.
It could also be the broker's idle connection reaper that kicks in if a client has been silent for 10 minutes (default).

The client will reconnect instantly when the connection goes down.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected

**Comment by 15663671003** [comment]
Yes, this set up to verify the problem, thank you
