### ISSUE TITLE
after Consumer group  is rebalancing, all consumers can't get new msg

### ISSUE THREAD

**Issue by cc3630** [confluentinc/confluent-kafka-python#208]
I use Kafka as the message queue, then I set 1 topic, 4 partition and 3 consumer. When I start 3consumer, I check the status of the group, 
Warning: Consumer group 'BASE_GD' is rebalancing.

TOPIC  PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG  CONSUMER-ID  HOST     CLIENT-ID
-             -                          -                       -                     -     rdkafka-fbca5204 /192.168.1.44     rdkafka
-              -                         -                          -                  -     rdkafka-9b6c1ffb   /192.168.1.45    rdkafka
-              -                         -                          -                 -      rdkafka-fd26f7de  /192.168.1.41    rdkafka
BASE_GD                   1          13100           20100           7000       -                                                 -                              -
BASE_GD                   3          100             10100           10000      -                                                 -                              -
BASE_GD                   0          244080          252080          8000       -                                                 -                              -
BASE_GD                   2          10100           20100           10000      -                                                 -  

last:
Consumer group 'BASE_GD' has no active members.

TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG        CONSUMER-ID                                       HOST                           CLIENT-ID
BASE_GD                   1          13100           20100           7000       -                                                 -                              -
BASE_GD                   3          100             10100           10000      -                                                 -                              -
BASE_GD                   0          244080          252080          8000       -                                                 -                              -
BASE_GD                   2          10100           20100           10000      -                                                 -                              -

Please help me, Thanks! :(

**Comment by edenhill** [comment]
Sorry for the slow reply, are you still having issues with this?
