### ISSUE TITLE
Support for non-avro message key in AvroConsumer and AvroProducer

### ISSUE THREAD

**Issue by iharkaroza** [confluentinc/confluent-kafka-python#211]
Hi! At the moment we have a number of clients who produce/consume messages with string keys and payload encoded with avro schema. Some of them choose to use python for message consumption and unable to do so for messages with string keys, because AvroConsumer expects all the keys to be encoded with avro schema. 
Just want to know if there is a reason behind this avro message key approach? It looks restricting to me and I think it would be nice to have support for string message keys in AvroConsumer and AvroProducer.

**Comment by edenhill** [comment]
That sounds reasonable, there is no overwhelming reason to force an Avro schema on the key.

**Comment by michelazzo** [comment]
Is there any work being developed on that? That's a feature I need badly.

**Comment by sebastianneubauer** [comment]
Am I right in my understanding that this issue prohibits the use of ksql together with the python AvroProducer as ksql cannot work with avro format keys? If yes, are there any workarounds?

**Comment by rmoff** [comment]
@sebastianneubauer the workaround is to ensure that the key is also available in the value fields, and use KSQL's `PARTITION BY` functionality to repartition your streams with `STRING` keys (which KSQL does support).

**Comment by sebastianneubauer** [comment]
The issue is, that the avro producer can only generate streams with avro keys. So for the workaround one would create a dummy avro schema for the key in the produced stream and complete ignore it and create another stream using partition by, right?

**Comment by rmoff** [comment]
>  So for the workaround one would create a dummy avro schema for the key in the produced stream and complete ignore it and create another stream using partition by, right?

Yes.

**Comment by cricket007** [comment]
Link https://github.com/confluentinc/confluent-kafka-python/issues/428#issuecomment-444320103
