### ISSUE TITLE
consumer: what does it mean if on_assignment never gets called?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#214]
I have set up a consumer, and my on_assignment never gets called:

        c = Consumer(**config)
        print("consumer group {}, topic {}".format(consumer_group, topic))
        c.subscribe([topic], on_assign=print_assignment)

Usually I would expect that after my first poll() or two, I would see my print_assignment() routine get called, but in this case I do not. Moreover, I do not seem to be able to consume properly either.

The only thing I see that looks funny when I enable **debug: all** is this:

%7|1498588125.952|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: 198.18.130.35:9092/1: Group "cg_11" GroupCoordinator response error: Broker: Group coordinator not available

I do, however, get statistics callbacks. Any clue what is wrong here, or what might cause this?

**Comment by edenhill** [comment]
Sorry for the delay.

When the coordinator is not available (broker-side error) it typically means the __consumer_offsets topic is under-replicated prevent a coordinator to be elected for the group.
Could this have been the case for you?

**Comment by johnrgregg3** [comment]
Do you mean that the replication factor is 2, but only 1 broker in the cluster is up? Or maybe zookeeper is down? What conditions would fall under this category?

**Comment by edenhill** [comment]
The first case, where there are not enough available replica brokers to reach the replication factor of the __consumer_offsets topic, this will prevent consumer groups from functioning as no coordinator broker can be elected.

**Comment by yuwash** [comment]
I had a similar issue with the same error. In my case, it was occuring using the "high-level consumer" from the [README](README.md). When adding `'session.timeout.ms': 6000,` to the Consumer configuration, it worked. (the [consumer under "examples"](examples/consumer.py) worked as well without modification)
