### ISSUE TITLE
consumer call consumer.poll() failed

### ISSUE THREAD

**Issue by 15663671003** [confluentinc/confluent-kafka-python#215]
%3|1498729176.263|ERROR|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 10.255.84.140:9092/1: 1 request(s) timed out: disconnect (average rtt 578.287ms)
%3|1498729176.263|ERROR|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 1/1 brokers are down
%3|1498729177.364|FAIL|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 10.255.84.140:9092/1: 1 request(s) timed out: disconnect (average rtt 578.287ms)
%3|1498729177.364|ERROR|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 10.255.84.140:9092/1: 1 request(s) timed out: disconnect (average rtt 578.287ms)
^C%3|1498729238.454|FAIL|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 10.255.84.140:9092/1: 1 request(s) timed out: disconnect (average rtt 578.287ms)
%3|1498729238.454|ERROR|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 10.255.84.140:9092/1: 1 request(s) timed out: disconnect (average rtt 578.287ms)
%3|1498729238.454|ERROR|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 1/1 brokers are down
%3|1498729239.554|FAIL|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 10.255.84.140:9092/1: 1 request(s) timed out: disconnect (average rtt 578.287ms)
%3|1498729239.554|ERROR|rdkafka#consumer-1| [thrd:10.255.84.140:9092/bootstrap]: 10.255.84.140:9092/1: 1 request(s) timed out: disconnect (average rtt 578.287ms)

please help me - -

**Comment by edenhill** [comment]
Seems like you have connectivity or stability problems with your broker.
Check the broker logs for hints.
