### ISSUE TITLE
Slow producer

### ISSUE THREAD

**Issue by nautilus28** [confluentinc/confluent-kafka-python#218]
With the following setup

```
p = Producer({'bootstrap.servers': 'localhost:9092',
              'default.topic.config': {'produce.offset.report': True}})
url = 'http://edition.cnn.com/2017/07/11/politics/trump-jr-russia-lawyer-emails/index.html'
p.produce('test', url.encode('utf-8'))
p.flush()
```

The `produce` method took 1.085s to complete. As an asynchronous operation, I would expect it to be much faster. Do you have any idea, why? Is there any bad practice in my configurations?

Thanks in advance,
Canh

**Comment by edenhill** [comment]
That is because of `queue.buffering.max.ms` that defaults to 1s in the current librdkafka releases (next release will minimize it by default).

See this wiki for more info
https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency

**Comment by nautilus28** [comment]
I set queue.buffering.max.ms = 5

```
p = Producer({'bootstrap.servers': 'localhost:9092',
              'queue.buffering.max.ms': 5,
              'socket.keepalive.enable': True,
              'default.topic.config': {'produce.offset.report': True}})

```

Now it took 1.004s of the `produce` method.

**Comment by edenhill** [comment]
Try setting `socket.blocking.max.ms` to 1.

What confluent-kafka-python and librdkafka versions are you on?

**Comment by nautilus28** [comment]
librdkafka v0.9.5
confluent-kafka-python v0.9.4

There was my mistake after reconfiguration. Now, it takes 47ms to complete the `produce` method. It's acceptable performance for my purpose.

Thanks @edenhill much appreciated for your help!
