### ISSUE TITLE
Question: Is it possible to configure a consumer to not automatically reconnect?

### ISSUE THREAD

**Issue by bjustin-ibm** [confluentinc/confluent-kafka-python#219]
This may seem like an odd question, but I have a need to better control when a consumer reconnects. I have an application with many consumers, and I need to ensure that they all connect and (more importantly) reconnect in a very orderly manner.  I am aware of `reconnect.backoff.jitter.ms` but this doesn't help as my consumers are in separate processes, and I need to coordinate their reconnections over time.

As I see it, there are two possibilities that would help:
- A way to configure the consumer to never reconnect automatically. I would also need to be aware of when the consumer became disconnected (throwing an error from `poll()` would be fine).
- Failing that, a way to become aware that a consumer has been disconnected, and is about to reconnect. This would allow me to manually intervene to shut down the consumer and restart it at a time that is appropriate.

After digging around the docs a little, I don't see that either of these things are possible, but I'm hoping that someone can prove me wrong 😉

**Comment by edenhill** [comment]
While not exposed to Python (which would be hard), the C interface has a `connect_cb()` that can be used to monkey patch the connect behaviour.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1334
