### ISSUE TITLE
When does on_assign() get called after initial subscription?

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#220]
I do this:
consumer.subscribe(list(topic_set), on_assign=log_kafka_assignment)
And my routine, log_kafka_assignment, gets called pretty soon. But then it gets called at other times too, without my subscribing to any new topics or anything. Why does it do this? Is Kafka repartitioning or something? If so, why might it do this? Does it mean a broker in the cluster died or came back up? I don't think my brokers are flapping.

**Comment by ah-** [comment]
Are you running multiple consumers with the same group_id? If a new one comes up the topics would get rebalanced, and all of them would get a new assignment.

What does the log_kafka_assignment show?

**Comment by edenhill** [comment]
What Andreas said:
 * topic partition count changes
 * regex-matched topic subscription matching new topic(s)
 * member churn
 * network/broker instability causing coordinator switchover

**Comment by johnrgregg3** [comment]
It could be the case that other consumers with the same group_id are flapping. What happens if there are multiple consumers with the same group_id, but they all subscribe to different topics? Would we still expect to see on_assignment get called like this?

**Comment by edenhill** [comment]
The group is re-assigned in its entirety, even if the parting consumer had a unique topic subscription.
