### ISSUE TITLE
offsets_for_times support?

### ISSUE THREAD

**Issue by severun** [confluentinc/confluent-kafka-python#225]
I've written a Kafka consumer using the CPP version of librdkafka, and it works great! However, I am currently trying to recreate this consumer in a more light-weight Python version but I am running into some issues with regards to starting from a specific offset.

In my CPP code I used the following calls to set the partition offsets to a before a specific timestamp:
```
partition->set_offset(ts);
...
consumer->offsetsForTimes(partitions, 5000);
```

The `offsetsForTimes` call uses the `rd_kafka_offsets_for_times` function to retrieve specific offset values for a given timestamp, but I cannot find the corresponding call in the Python version of the Kafka consumer. I could not find a similar function in confluent_kafka.c so I was wondering if this feature is support in the Python client, and if so, how to use it.

**Comment by ewencp** [comment]
You're correct that this hasn't been exposed in the Python client yet. We focused on the core, most commonly used functionality and expose other features as we see demand for it.

This is a pretty small addition that would probably be a pretty small patch if you have any interest in contributing a PR -- you'd just need to wrap the `rd_kafka_offsets_for_times` in a function that gets exposed as a method on the consumer, https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/src/Consumer.c#L234-L254 might be a good example of a roughly similar function.

**Comment by edenhill** [comment]
Corresponding code in the Go client, for reference: https://github.com/confluentinc/confluent-kafka-go/pull/83/commits/41568707edf59870cca411554f1c4810d98f0924
