### ISSUE TITLE
Cannot connect to a server that is only binding 'localhost'

### ISSUE THREAD

**Issue by aseigneurin** [confluentinc/confluent-kafka-python#229]
In development, my local Kafka broker only binds `localhost`:

```
listeners=PLAINTEXT://localhost:9093
```

If I use the "High-level Consumer" code example code from [the documentation](https://github.com/confluentinc/confluent-kafka-python#usage), the consumer fails to connect to my broker:

```
%3|1502723013.325|FAIL|rdkafka#consumer-1| [thrd:localhost:9093/bootstrap]: localhost:9093/bootstrap: Connect to ipv6#[::1]:9093 failed: Connection refused
%3|1502723013.325|ERROR|rdkafka#consumer-1| [thrd:localhost:9093/bootstrap]: localhost:9093/bootstrap: Connect to ipv6#[::1]:9093 failed: Connection refused
%3|1502723013.325|ERROR|rdkafka#consumer-1| [thrd:localhost:9093/bootstrap]: 1/1 brokers are down
```

This seems to be because this consumer resolves `localhost` to an IPv6 address, but the broker doesn't bind this address.

A Java consumer doesn't have this problem.

Tested with Kafka 0.10 and 0.11.

**Comment by edenhill** [comment]
librdkafka (the underlying C client that powers the python client) will use the system resolver to solve the broker hostname. On some systems, OSX in particular, the `localhost` entry in `/etc/hosts` resolves both to an IPv4 and IPv6 address, so librdkafka will in a round-robin fashion attempt to connect to all addresses the hostname resolves to.

To limit what address families it tries to connect to you can set the `broker.address.family` configuration property to `v4`.

**Comment by aseigneurin** [comment]
Ok. This solves this issue.

Thanks!

**Comment by nitishnference** [comment]
> librdkafka (the underlying C client that powers the python client) will use the system resolver to solve the broker hostname. On some systems, OSX in particular, the `localhost` entry in `/etc/hosts` resolves both to an IPv4 and IPv6 address, so librdkafka will in a round-robin fashion attempt to connect to all addresses the hostname resolves to.
> 
> To limit what address families it tries to connect to you can set the `broker.address.family` configuration property to `v4`.

Where can I find this configuration file to edit this field broker.address.family

**Comment by edenhill** [comment]
@nitishnference That's a python client configuration property that you specify in the config dict you pass to the client constructor, e.g:
`p = Producer({'bootstrap.servers': .., 'broker.address.family': 'v4'})`

**Comment by nitishnference** [comment]
> @nitishnference That's a python client configuration property that you specify in the config dict you pass to the client constructor, e.g:
> `p = Producer({'bootstrap.servers': .., 'broker.address.family': 'v4'})`

Thanks a lot.

**Comment by gtangthousandeyes** [comment]
i was also running into this error when setting up a kafka cluster on my local machine. Adding the config to my kafka producer solved the issue 👍 

```
%3|1623107870.886|ERROR|rdkafka#producer-1| [thrd:localhost:9092/0]: localhost:9092/0: Connect to ipv6#[::1]:9092 failed: Connection refused```
