### ISSUE TITLE
Custom partitioner support

### ISSUE THREAD

**Issue by sakshamgupta1** [confluentinc/confluent-kafka-python#231]
Is there any documentation around using custom partitioners with producer?

**Comment by edenhill** [comment]
Custom partitioners are currently not exposed in the Python client due to threading issues. The partitioner may be called from an internal librdkafka thread and this does not play well with the Python interpreter. We're looking into alternatives.

**Comment by edenhill** [comment]
The next version of librdkafka (the underlying Kafka client) will expose the builtin partitioners as configuration properties, allowing you to change to an alternative builtin partitioner, such as the Java compatible murmur2_random partitioner.

Search for 'partitioner' here: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md


Custom partitioners are not yet exposed in the Python client though.

**Comment by ltucker** [comment]
@edenhill does the partition argument of Producer.produce() work? (ie can I execute a routing strategy not in a callback assuming I know the partition count and have enough other info on hand? )

**Comment by edenhill** [comment]
Yes it does!

**Comment by rnpridgeon** [comment]
@edenhill Do you think exposing the built-in partitioners here is enough or do we intend to make upstream changes to librdkafka to make this possible. Unless there are any objections I say we mark this as closed in favor of #396 for the time being. If any compelling arguments can be made for customer partitioners beyond those which are provided we can reopen .

**Comment by edenhill** [comment]
Sounds good to me, close as wontfix with a reference to the built-ins.

2018-06-29 21:20 GMT+02:00 Ryan P <notifications@github.com>:

**Comment by rnpridgeon** [comment]
Marked as `won't fix` with the addition of  #396 which exposes the built-in partitioners.

**Comment by Bec-k** [comment]
So there is still no support for custom partitioners and assignments?
