### ISSUE TITLE
Getting available topic list to avoid stalling requesting non existing topic

### ISSUE THREAD

**Issue by fpietka** [confluentinc/confluent-kafka-python#233]
This may sound like a dumb question, but I can't find a way to get available topics for the library. Am I missing something?

My main issue is when the subscribed topic isn't available (typo, or plain wrong topic), the `Consumer.poll()` call is stalling.

Thanks for your help.

**Comment by edenhill** [comment]
You want the metadata() API which is not yet added but tracked in issue #161

**Comment by fpietka** [comment]
Thank you
