### ISSUE TITLE
EOS support - Idempotent/Transactional Producer

### ISSUE THREAD

**Issue by vineetgoel** [confluentinc/confluent-kafka-python#234]
Are there plans of adding support for Idempotent/Transactional Producers? If yes, what is the expected timeline?

**Comment by edenhill** [comment]
Yes, we don't have an exact time frame for you yet but we're looking at early 2018 to provide this functionality in all librdkafka-based clients.

**Comment by bigorc** [comment]
We need this feature too.

**Comment by JohnRoach** [comment]
Will this be worked on? Are there any plans around this?

**Comment by rnpridgeon** [comment]
@JohnRoach yes, its still undergoing the design phase in librdkafka but we are making progress on that front albeit at a slightly slower pace than we had originally intended. I believe the expectation is that EOS support will be added before the end of 2018 but this is of course tentative.

**Comment by JohnRoach** [comment]
Thank you @rnpridgeon for the update! 

Is the related ticket https://github.com/edenhill/librdkafka/issues/1308 ?

**Comment by rnpridgeon** [comment]
Indeed it is. Once it's in librdkafka we can begin work on the python bindings

**Comment by mrubin** [comment]
What is the status of this given that idempotent producer support has been released (https://github.com/edenhill/librdkafka/releases/tag/v1.0.0)?

**Comment by rtnpro** [comment]
According to the `v1.0.0` release note here: https://github.com/confluentinc/confluent-kafka-python/releases/tag/v1.0.0, `confluent-kafka-python` is already using `librdkafka` `v1.0.0.`, which has `EOS` support. So, I presume that if we just set `enable.idempotence` to `true` in `config` when instantiating a `Producer` object, `EOS` should start working with this library as well.

However, it will be great if an upstream can confirm this. @rnpridgeon What do you say?

**Comment by edenhill** [comment]
@rtnpro Yes, that is sufficient.
See the "Idempotent Producer" section of the release notes you linked.

**Comment by edenhill** [comment]
Full EOS supported now
