### ISSUE TITLE
How to pass ssl.keystore.location to AvroProducer

### ISSUE THREAD

**Issue by e3aa3b** [confluentinc/confluent-kafka-python#236]
Hi,

I wanted to understand how we can pass following params to AvroProducer:
- ssl.keystore.location
- ssl.truststore.location

avroProducer = AvroProducer({'bootstrap.servers':'server:9093', 'ssl.keystore.location':'/location/kafka.client.keystore.jks'})

throws this error:
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "ssl.keystore.location""}

Thanks

**Comment by edenhill** [comment]
keystores are Java specific, what you want is the `ssl.key.location` and a PEM key.
See instructions here:
https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka
