### ISSUE TITLE
Document the limitations of C/Python interaction?

### ISSUE THREAD

**Issue by jeffwidman** [confluentinc/confluent-kafka-python#238]
At my day job, from time to time we consider switching to this library. 

However, there's some fears about the C/Python interaction, none of us have ever played much with C/Python interactions and we're wondering whether there will be some limitations because it's not pure python.

For example, it's unclear to me whether https://github.com/confluentinc/confluent-kafka-python/issues/209#issuecomment-321257157 is a limitation of `librdkafka` or of the C/Python interaction.

Additionally, I see https://github.com/confluentinc/confluent-kafka-python/blob/d0b8563461df5854bede5566d62e0a4c11869885/confluent_kafka/src/confluent_kafka.c#L22-L34 but not sure if that's a complete list...

Can you document somewhere the limitations inherent in wrapping librd so that we are more aware of the tradeoffs rather than shooting in the dark?

**Comment by edenhill** [comment]
Hey Jeff, that's a good idea. I'll try to summarize the current obstacles and ideas how to overcome them.
Generally I'd say there aren't that many, the API lag in the Python client (compared to librdkafka) is mostly not technical, but due to prioritization of other endeavours. Community feedback/voting on desired APIs plays a large role to here.

**Comment by jeffwidman** [comment]
> the API lag in the Python client (compared to librdkafka) is mostly not technical, but due to prioritization of other endeavours.

Yeah, I'm not too worried about feature lag, I just want to know which features are technically impossible/difficult due to the C layer so that down the road as the feature set matures and we begin to seriously evaluate switching that we do that with our eyes wide open.

And regarding feature lag, I have a hunch that the feature set of this driver will surpass the other python drivers in 2-3 years simply because Confluent is putting resources into this, versus the other drivers are volunteer run (and I say this as one of the maintainers of `kafka-python`). I am not 100% sure, since the non-pure python nature of this lib makes it more difficult for drive-by committers, but that's my hunch.

**Comment by jeffwidman** [comment]
nudge
