### ISSUE TITLE
Kafka error GroupCoordinator response error: Local: Broker transport failure

### ISSUE THREAD

**Issue by PGryllos** [confluentinc/confluent-kafka-python#240]
Hi, 

I am experiencing issues in my connectivity with the Broker. After some time consuming I always get this error
> Kafka error GroupCoordinator response error: Local: Broker transport failure

and the consumer is not able to resume consuming

Some of my configs with which the error occurs

```     
**{
    'bootstrap.servers': self.config["bootstrap_servers"],
    'api.version.request': True,
    'group.id': <group_id>,
    'fetch.message.max.bytes': 125829120,
    'fetch.wait.max.ms': 60000,
    'queued.min.messages': 1,
    'session.timeout.ms': 298,
    'enable.auto.commit': 'false',
    'receive.message.max.bytes': 603316706,
    'heartbeat.interval.ms': 60000,
    'topic.metadata.refresh.interval.ms': 600000,
    'debug': 'cgrp,protocol,topic,broker',
    'default.topic.config': {
        'auto.offset.reset': 'earliest'
    }
}

```

I use the consumer api and not the iterator; like that

```python
while not self.shutdown:
    msg = self.consumer.poll()
    self.logger.info('Consuming message from partition {}'.format(str(msg.partition())))

    if self.shutdown:
        break

    if msg.error():
        self.logger.warn('Kafka error {}'.format(msg.error().str()))
        continue

    retry_until_success(10, self.process_msg, msg)
    self.consumer.commit(message=msg, async=True)

self.consumer.close()
self.logger.info("Consumer Terminated")
```

If I set `'topic.metadata.refresh.interval.ms': -1` the problem does not occur naturally but in case one of the brokers goes down, although the consumer is able to find to rest of the brokers, the data consumption is not resumed.

some of the debug messages are

> %7|1504272252.885|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic sensor-topic partition 161 Leader 3
%7|1504272252.885|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic sensor-topic partition 0 Leader 2
%7|1504272252.885|METADATA|rdkafka#consumer-1| [thrd:main]: external-ip2.compute.amazonaws.com:9092/bootstrap: 1/1 requested topic(s) seen in metadata
%7|1504272252.886|BROKERFAIL|rdkafka#consumer-1| [thrd:external-ip.compute.amazonaws.com:9092/bootstrap]: external-ip.compute.amazonaws.com:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection refused)
%7|1504272252.886|FAIL|rdkafka#consumer-1| [thrd:external-ip.compute.amazonaws.com:9092/bootstrap]: external-ip.compute.amazonaws.com:9092/bootstrap: Connect to ipv4#ip:9092 failed: Connection refused
%7|1504272252.886|STATE|rdkafka#consumer-1| [thrd:external-ip.compute.amazonaws.com:9092/bootstrap]: external-ip.compute.amazonaws.com:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1504272252.891|RECONNECT|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Delaying next reconnect by 55ms
%7|1504272252.946|CONNECT|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: broker in state DOWN connecting
%7|1504272252.947|CONNECT|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Connecting to ipv4#ip:9092 (plaintext) with socket 20
%7|1504272252.947|STATE|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Broker changed state DOWN -> CONNECT
%7|1504272252.948|RECONNECT|rdkafka#consumer-1| [thrd:ip.internal2:9092/2]: ip.internal2:9092/2: Delaying next reconnect by 459ms
%7|1504272252.974|CONNECT|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Connected to ipv4#ip:9092
%7|1504272252.974|CONNECTED|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Connected (#70)
%7|1504272252.974|STATE|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1504272252.975|SEND|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Sent ApiVersionRequest (v0, 25 bytes @ 0, CorrId 272)
%7|1504272253.027|RECV|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Received ApiVersionResponse (v0, 132 bytes, CorrId 272, rtt 52.22ms)
%7|1504272253.027|STATE|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Broker changed state APIVERSION_QUERY -> UP
%7|1504272253.029|SEND|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Sent FetchRequest (v2, 1611 bytes @ 0, CorrId 273)
%7|1504272253.090|BROKERFAIL|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: failed: err: Local: Broker transport failure: (errno: Resource temporarily unavailable)
%3|1504272253.090|FAIL|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Receive failed: Disconnected
%3|1504272253.091|ERROR|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Receive failed: Disconnected
%7|1504272253.091|STATE|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Broker changed state UP -> DOWN
%7|1504272253.092|RETRY|rdkafka#consumer-1| [thrd:ip.internal:9092/3]: ip.internal:9092/3: Retrying FetchRequest (v2, 1611 bytes, retry 1/2)
%7|1504272253.093|SEND|rdkafka#consumer-1| [thrd:external-ip2.compute.amazonaws.com:9092/bootstra]: external-ip2.compute.amazonaws.com:9092/bootstrap: Sent MetadataRequest (v2, 59 bytes @ 0, CorrId 90)
%7|1504272253.134|RECV|rdkafka#consumer-1| [thrd:external-ip2.compute.amazonaws.com:9092/bootstra]: external-ip2.compute.amazonaws.com:9092/bootstrap: Received MetadataResponse (v2, 6200 bytes, CorrId 90, rtt 40.99ms)
%7|1504272253.134|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic sensor-topic partition 137 Leader 3
%7|1504272253.134|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic sensor-topic partition 146 Leader 3
%7|1504272253.134|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic sensor-topic partition 92 Leader 3

**Comment by PGryllos** [comment]
__update__

I figured that If I wait long enough (around 20min) the consumer is able to resume consuming. Is this normal? For a consumer to take 20 min trying to communicate with the broker while the broker is still up?  Can this timeframe be affected by some configuration value?

**Comment by edenhill** [comment]
The session timeout looks incorrect, it is usually not possible to set it under 6000ms:
`    'session.timeout.ms': 298,` 

And I'm suspecting the very high fetch timeout is causing enqueued requests to time out, is there a reason you are setting it this high? Since the same broker connection will be used for other requests and the Fetch request is blocking it is not recommended to have a value higher than say 1000ms for this:

`'fetch.wait.max.ms': 60000,`

You should leave the heartbeat at its default value (which will then be set to a third of the session.timeout.ms) or make sure that the value is well below the session timeout):

`'heartbeat.interval.ms': 60000,`

**Comment by PGryllos** [comment]
my mistake! `session timeout` is set to 298000 ms. With the session timeout, should I still reduce the `'fetch.wait.max.ms'` and / or the `'heartbeat.interval.ms'`?

**Comment by edenhill** [comment]
Yes, the above recommendations are regardless of session timeout.

**Comment by PGryllos** [comment]
@edenhill thanks a lot. I will try out those and see if I still get transport failures. Are there cases where we should shutdown a consumer after a specific error is received? Or the expected behaviour is that the consumer will be always able to recover given the broker is available?

**Comment by PGryllos** [comment]
I tried with the suggested configuration updates and I still cannot specify under what conditions but I get the `Kafka error GroupCoordinator response error: Local: Broker transport failure` error and it seems like its not recovering from that.

**Comment by edenhill** [comment]
@PGryllos Can you share your updated configuration?

**Comment by PGryllos** [comment]
```python
**{
    'bootstrap.servers': self.config["bootstrap_servers"],
    'api.version.request': True,
    'group.id': self.config["kafka_consumer_group_id"],
    'fetch.message.max.bytes': 125829120,
    'fetch.wait.max.ms': 1000,
    'queued.min.messages': 5,
    'session.timeout.ms': 299000,
    'enable.auto.commit': 'false',
    'receive.message.max.bytes': 603316706,
    'default.topic.config': {
        'auto.offset.reset': 'earliest'
    }
}
```

**Comment by edenhill** [comment]
Can you run with `'debug': 'protocol'` and provide the logs? I suspect the Fetch requests are slow.

**Comment by PGryllos** [comment]
@edenhill thanks a lot for taking the time. you mean catch the debug messages that are spawned when the error occurs?  If yes, usually there is a constant stream of debug messages when the fail happens. I've captured some in the first comment here.Should I look for some specific output?

**Comment by edenhill** [comment]
I would like to see a new log using the modified configuration.

**Comment by PGryllos** [comment]
It seems like the errors were due to problems with our Kafka broker and I cannot reproduce it in an isolated environment. For the most part when the brokers are healthy the consumers work with no problem. Thanks a lot for the help.
