### ISSUE TITLE
KIP-4 - CreateTopics API

### ISSUE THREAD

**Issue by doron-levi** [confluentinc/confluent-kafka-python#244]
Is this exposed via the python API?

**Comment by edenhill** [comment]
The metadata() API to gather broker and topic metadata information is not yet exposed in the Python bindings. This is on the roadmap, issue #161.

The APIs to create and manipulate topics, as defined in [KIP-4](https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations), are not yet implemented.

However, if your broker is configured with automatic topic creation (`auto.create.topics.enable=true`) you can create the topic from the client by simply producing to it.

**Comment by doron-levi** [comment]
OK, thanks for us auto.create.topics.enable=false... I will handle topic creation elsewhere, I wish there where more examples or more docs about the configuration dict option that is passed in the Producer\Consumer constructor

**Comment by edenhill** [comment]
Is there a particular subject/use-case with regards to the configuration dict that you are interested in?

**Comment by rnpridgeon** [comment]
fixed with #382
