### ISSUE TITLE
`offsetsForTimes` support

### ISSUE THREAD

**Issue by johnistan** [confluentinc/confluent-kafka-python#247]
Description
===========

I can't find the `consumer.offsetsForTimes` method in the docs. Is this a supported feature? 

[Java API](https://kafka.apache.org/0102/javadoc/org/apache/kafka/clients/consumer/Consumer.html#offsetsForTimes(java.util.Map))

**Comment by edenhill** [comment]
The offsets_for_times() is available in librdkafka but not yet introduced in the Python client.
It is on the backlog though.

**Comment by edenhill** [comment]
#225
