### ISSUE TITLE
Segfault after calling a closed consumer

### ISSUE THREAD

**Issue by johnistan** [confluentinc/confluent-kafka-python#255]
Description
===========

Once a Consumer has been closed, calling any subsequent method references the inter handle `self->rk` which is now `NULL` and causes a segfault.

The consumer should instead raise an exception for the application code to handle. 

How to reproduce
================

```
c = Consumer()
c.close()
c.assignment() # SEGFAULT
```

**Comment by edenhill** [comment]
Could we use RuntimeError("Consumer closed...")?

**Comment by johnistan** [comment]
Sounds good
