### ISSUE TITLE
consumer group ignoring topic assigned to a group

### ISSUE THREAD

**Issue by rugging24** [confluentinc/confluent-kafka-python#261]
Description
===========
I have a list of 150 topics consumed by 3 consumers in a consumer group using a regex specified topic list/ While it consumes messages from majority of the topics, it skips some topics even though the regex is specified.
Does someone have an explanation and perhaps a suggestion on how to fix this ?

How to reproduce (my code)
================

```
keepRunningConsumer = True 
consumer.subscribe(["^used_regex_here.*"],on_assign=onConsumerAssigncb)
while keepRunningConsumer:
                    msg = consumer.poll(2)
                    if msg is None:
                         continue
                    elif not msg.error():
                         # consumer payload 
                         print msg.value() 
                    elif msg.error().code() == confluent_kafka.KafkaError._PARTITION_EOF:
                         pass 
                    else:
                         logger.error('%s', msg.error().str())

consumer.close()


def onConsumerAssigncb(self,consumer,partitions):
          # -2 = from the beginning
          # -1 = from the end
          # perform some check 
          if check_suceeds:
               for partition in partitions:
                    partition.offset = -2
          consumer.assign(partitions)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 0.11.0~1confluent3.3.0-1 
 - [x] Apache Kafka broker version: 0.10
 - [x] Client configuration: bootstrap.servers : kafka1:9099,kafka2:9099,kafka3:9099
     session.timeout.ms: 6000
     broker.version.fallback : '0.10.0.1'
     producer:
          batch.num.messages : 100
          request.required.acks: -1
          message.max.bytes: 209715200
          default.topic.config : {'auto.offset.reset': 'earliest','acks': 'all'}
     consumer :
          enable.auto.commit : False
          heartbeat.interval.ms: 3000
          fetch.message.max.bytes : 209715200
 - [x] Operating system: Debian GNU/Linux 8.9 (jessie)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It would be interesting to know if the topics are successfully matched by the regex and included in the subscription, what topics are assigned to which consumer, and if the consumers are trying to fetch the given topics and partitions.

How many messages are there in each topic+partition?
How long do you wait for all messages to be consumed?


Make sure to read this:
https://github.com/edenhill/librdkafka/wiki/FAQ#how-are-partitions-fetched

To troubleshoot this issue you will need to enable `debug` `cgrp,fetch` (which will be very noisy with that many topics) and look for the topics that you are not receiving messages for.

**Comment by rugging24** [comment]
-- streamlined the topics to a sizable amount.
