### ISSUE TITLE
Lookup consumer lag

### ISSUE THREAD

**Issue by johnistan** [confluentinc/confluent-kafka-python#269]
I am in the process of switching to use this client however I have a use case which doesn't seem supported. Basically I have a service that reports consumer lag and helps scale workers to keep up with streams. It reads my configuration service gets a list of topics and consumer groups that are active. It then queries kafka for these topic/consumer groups and does its work.

I guess i could start a consumer with the group, not subscribe to a topic but use `committed`. However, i have no way of knowing the partition count without a metadata api. Am i missing something or this something already supported.

**Comment by edenhill** [comment]
I suggest you to register a stats callback and extract `consumer_lag` (per partition) from the emitted JSON (format here: https://github.com/edenhill/librdkafka/wiki/Statistics).

Alternatively use the caching variant of get_watermark_offsets() to compare the current consume offset (latest message) with the high watermark off the partition.

**Comment by johnistan** [comment]
Thanks, but this would still be inside of the kafka consumer application that is subscribed to the topic right? I have a need for a separate process to query this lag. There is no way for this work right?

**Comment by edenhill** [comment]
Oh, sorry.
In that case you would need to set the same group.id as you are monitoring, extract the partition counts for your monitored topics somehow (since the Python client does not yet expose a Metadata API :( ), and call committed(), yes.

**Comment by johnistan** [comment]
Thanks! I guess add this as a +1 on the Metadata API.

**Comment by austinnichols101** [comment]
Also see #223
