### ISSUE TITLE
AvroProducer  - How to access from Postgresql table and write to aTopic

### ISSUE THREAD

**Issue by annusri** [confluentinc/confluent-kafka-python#270]
Description
===========
Since based on my google search, I didn't any information and hence posting my question here.
How do I select from postgresql table and published to AvroProducer Topic.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by deckardbsd** [comment]
Hello !
How could I be able to write data using avro union ? 
I have an avro schema which is a union of records, but I can't find a proper way of constructing a data dictionary in order to write that to kafka.
I can provide the schema if necessary

Thanks !
