### ISSUE TITLE
Manual commit not working properly

### ISSUE THREAD

**Issue by simonwahlgren** [confluentinc/confluent-kafka-python#271]
Checklist
===========
confluent-kafka-python : ('0.11.0', '720896')
librdkafka: ('0.9.4-134-g75013b', 591104)
Kafka broker version: 0.11.0.0 running on Docker (confluentinc/cp-kafka:latest)
OS: Arch Linux
No exceptions in the Kafka log.

The provided logs (cgrp,topic,protocol,broker) includes the scenario described in the "How to reproduce" section.
[consumer.log.gz](https://github.com/confluentinc/confluent-kafka-python/files/1421491/consumer.log.gz)

Description
===========
Manually committing the consumer offsets more then once hangs the consumer process and the CPU usage becomes very high.

I've nailed down to where the problem was introduced and it seems like it stopped working after this commit: https://github.com/confluentinc/confluent-kafka-python/commit/6ef1ae40efc5f044bf497d1cb4903d0fb968edcf

How to reproduce
================
1. Install latest version of confluent-kafka-python (commit 7ebc807).
```sh
pip install -U git+git://github.com/confluentinc/confluent-kafka-python.git@master
```
2. Start a consumer with auto commit disabled.
```python
from confluent_kafka import Consumer

config = {
    'bootstrap.servers': 'localhost:9092',
    'group.id': 'foobar.group',
    'enable.auto.commit': False
}
consumer = Consumer(**config)
consumer.subscribe(['foobar'])

try:
    while True:
        msg = consumer.poll(timeout=0.1)
        if msg is None:
            continue
        if msg.error():
            continue
        message = msg.value().decode('utf-8')
        print(message)
        print("Committing consumer offsets")
        consumer.commit()
finally:
    consumer.close()
```
3. Produce a message
```sh
echo $(date) | kafkacat -P -b localhost -t foobar
```
4. The first message is consumed and committed correctly, but if you produce another message the consumer process will hung on the `poll` method and the CPU usage becomes very high. If you restart the consumer process it will catch up on the previous message because the offset was never committed, but as soon as you produce another message the same problem occurs.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Can you try with librdkafka v0.11.1?

**Comment by simonwahlgren** [comment]
@edenhill Thanks for the quick response!

I just verified with the latest librdkafka ('0.0.63-RC1-24-gbbcfdd', 721151) and I still have the same issue. The only difference now is that my CPU is not burning up.

If I install the latest tagged version of confluent-kafka-python everything works perfectly.

**Comment by simonwahlgren** [comment]
I reproduced the problem in a Docker environment so it should be easy to verify, if you have time please have a look:
https://github.com/simonwahlgren/confluent_consumer

**Comment by edenhill** [comment]
@simonwahlgren 
Sorry for the long delay, finally got around to testing your docker env but I can't reproduce it, producing two messages with 12 seconds in between does not seem to hang the consumer:
```
consumer_1   | tis 9 jan 2018 20:33:23 CET
consumer_1   | Committing consumer offsets
consumer_1   | tis 9 jan 2018 20:33:35 CET
consumer_1   | Committing consumer offsets
consumer_1   | tis 9 jan 2018 20:33:40 CET
consumer_1   | Committing consumer offsets
```

It does seem like it is running librdkafka v0.9.5, while your readme states 0.11.1:
```
 docker-compose exec consumer python
Python 3.6.2 (default, Jul 18 2017, 23:04:54)
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import confluent_kafka
>>> confluent_kafka.version()
('0.11.0', 720896)
>>> confluent_kafka.libversion()
('0.9.5', 591359)
```

**Comment by simonwahlgren** [comment]
@edenhill No problem. I'll try to reproduce it again and see why the version is different from mine.

**Comment by edenhill** [comment]
success?

**Comment by simonwahlgren** [comment]
Yes! I don't know what fixed the issue, but I can't reproduce it again.
