### ISSUE TITLE
Cannot install on Ubuntu 16.04

### ISSUE THREAD

**Issue by mohsenSy** [confluentinc/confluent-kafka-python#272]
Description
===========
I am trying to install confluent-kafka library on my Ubuntu 16.04 desktop using the instructions found in README file, I executed `sudo apt-get install librdkafka-dev python-dev` successfully but when I execute 
`sudo pip install confluent-kafka`

I get the following error message, it can be found [here](https://pastebin.com/WshEj8a3)

How to reproduce
================
Try to install kafka on Ubuntu 16.04 by following the instruction in the README file

Checklist
=========

 - [ ] Operating system: Ubuntu 16.04
 - [ ] Critical issue

**Comment by edenhill** [comment]
It seems that you are stuck on an old version of librdkafka (0.8.x something, very old).

Add the confluent apt repo to make sure you always get the latest version of librdkafka, see instructions here:
https://docs.confluent.io/current/installation/installing_cp.html#debian-and-ubuntu
