### ISSUE TITLE
Client consumer taking a long time to subscribe when run alongside other consumers

### ISSUE THREAD

**Issue by kierkegaard13** [confluentinc/confluent-kafka-python#273]
I'm running with python 3.6.2, librdkafka 0.11.1, and confluent-kafka 0.11.0.

My application can run in one of two ways. In the first configuration, it uses two high level producers to send two types of jobs on two different topics. When those jobs are completed, messages get sent back on an additional two topics which are subscribed to by two additional high level consumers. These producers and consumers are run inside of processes created by python's multiproccessing.Process. When the consumers are created, they use
```
consumer.subscribe([topic], on_assign=reset_offsets)
```
and
```
def reset_offsets(consumer, partitions):
  self._partition_count = len(partitions)
  for p in partitions:
    current_offsets = consumer.get_watermark_offsets(p)
    p.offset = current_offsets[1]
  consumer.assign(partitions)
  status['assigned'] = True
```
to ignore old messages and to set the status flag when the consumer is subscribed. This flag is used to indicate when the producers can start sending out jobs. In the first configuration, subscription is relatively quick and happens after a few seconds.

In the second configuration, a consumer runs in the main process which listens for job requests from an API. When a request comes in, a function is called which spawns the additional consumers and producers as described above. However, in this second configuration, job subscription takes much longer (about 1 or 2 minutes), and I'm wondering why this happens. I've tried looking at the logs, but I didn't see anything useful or any glaring error messages. Are these consumers interacting with each other or sharing resources?

The consumer and producer are using SSL to connect in both application configurations, but beyond that the only optional config option that I set is 'auto.offset.reset': 'smallest'. I should be able to provide client logs if needed.

**Comment by kierkegaard13** [comment]
Okay, so I was able to fix the issue by running the function in the second configuration inside of a ThreadPoolExecutor thread asynchronously. Interestingly, if I wait for the result with _ = future.result(), the consumers once again take a long time to subscribe.

**Comment by kierkegaard13** [comment]
More interesting tidbits, if multiple jobs are submitted to the ThreadPoolExecutor, the first job will execute with no subscribe lag, but the following ones will take a long time to subscribe.

**Comment by kierkegaard13** [comment]
I think I found the issue. 'session.timeout.ms' defaults to 30 seconds which was roughly the time it was taking to subscribe in the worst case scenarios described above. Setting it to 10 seconds then caused subscription to take 10 seconds.

**Comment by kierkegaard13** [comment]
One other thing I found, setting 'session.timeout.ms' to a value of 5000 causes INVALID_SESSION_TIMEOUT errors when the librdkafka documentation notes that valid values lie in the range 1 .. 3600000.

**Comment by edenhill** [comment]
@kierkegaard13 the session timeout is enforced by the broker, see `group.min.session.timeout.ms` on the broker.

**Comment by kierkegaard13** [comment]
Oh okay. I think because I resolved the above issues, I'll close this out. Thanks for the help @edenhill.
