### ISSUE TITLE
kafka consumer changing group is not polling any messages

### ISSUE THREAD

**Issue by annusri** [confluentinc/confluent-kafka-python#275]
Description
===========
running consumer code with different groups each time is not polling any messages from a topic,
inspite of default.topic.config : {'auto.offset.reset': 'earliest'}

How to reproduce
================

1)  Ran produce code as below
    
```     
     from confluent_kafka import Producer

def acked(err, msg):
    if err is not None:
        print("Failed to deliver message: {0}: {1}"
              .format(msg.value(), err.str()))
    else:
        print("Message produced: {0}".format(msg.value()))

p = Producer({'bootstrap.servers': 'kafka01, kafka02, kafka03'})

try:
    for val in xrange(11, 20):
        p.produce('test', 'myvalue #{0}'
                  .format(val), callback=acked)
        p.poll(0.5)

except KeyboardInterrupt:
    pass

p.flush(30)
```

2) run consumer 
```
   from confluent_kafka import Consumer, KafkaError

settings = {
        'bootstrap.servers': 'kafka01,kafka02, kafka03', 
        'default.topic.config': {'auto.offset.reset': 'earliest'}
         ,'group.id' :'test'} 

c = Consumer(settings)

c.subscribe(['test'])

try:
    while True:
        msg = c.poll(0)
     
        if msg is None:
            continue
        elif not msg.error():
            print('Received message: {0}'.format(msg.value()))
        elif msg.error().code() == KafkaError._PARTITION_EOF:
            print('End of partition reached {0}/{1}'
                          .format(msg.topic(), msg.partition()))
            break   
        else:
            print('Error occured: {0}'.format(msg.error().str()))

except KeyboardInterrupt:
    pass

finally:
    c.close()
```
Result - Consumer is polling messages.

3) Now change the consumer group.id to test1
     ran consumer - No messages are getting polled . why ?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you completely sure there are no existing commits for group test1? Try a truly random group name.

Also: you might want to use a higher timeout (or no timeout, which is block-indef) on your poll() call to avoid busy-looping.

**Comment by eytienne** [comment]
@edenhill  I have the exact same issue with the Java API so I made a question here: https://stackoverflow.com/questions/73309760/consumer-not-polling-any-messages-with-random-group-id
