### ISSUE TITLE
Message value has payload argument that causes ide warning

### ISSUE THREAD

**Issue by PGryllos** [confluentinc/confluent-kafka-python#276]
Description
===========
The returned Kafka messages value method expects an argument `payload`
that makes the ide mark the calling of the method as problematic. It's not a real issue but 
I wonder where it stems from.

for instance

```python
msg = consumer.poll()
process_msg_value(msg.value())
```
will give a warning in pycharm as if I am missing an input on the value method.

The method I find is the following

```python

    def value(self, payload): # real signature unknown; restored from __doc__
        """
        :returns: message value (payload) or None if not available.
          :rtype: str|bytes or None
        """
        pass

```

How to reproduce
================
On pycharm (my version 2017.1) call `msg.value()`

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 0.9.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: MacOS
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
msg.value() is a CPython function and does not have a payload argument.
I'm not sure where you are seeing that Python method definition?

**Comment by PGryllos** [comment]
The ide find and abstract definition of the consumer in `confluent_kafka/cimpl.py`

**Comment by edenhill** [comment]
Okay, I'm not sure what to make of it.
As far as I can tell the confluent_kafka module does not export a method with that signature.

**Comment by PGryllos** [comment]
My bad, the full path is 
> /Users/user/Library/Caches/PyCharmCE2017.1/python_stubs/160944109/confluent_kafka/cimpl.py

I am also not sure what to make out of it because I cannot find the value method signature but probably it's an pycharm error

**Comment by ShukujiNeel13** [comment]
I'm facing the exact same issue. 
Python: 3.7
Package: confluent-kafka, version: 1.3.0

In fact when I navigate to the function definition (as pointed by PGryllos ) above
at the file Path <user>/Library/Caches/PyCharm2019.2/python_stubs/-2090162168/confluent_kafka/cimpl.py
the functions in this file have a comment on the side: "real signature unknown"
Also, this particular function has more to the comment: "; restored from __doc__"

It seems it is specific to the IDE, since it is using an IDE specific cached file for this package...

**Comment by Lakritsbiten** [comment]
I'm facing the exact same issue.
Python: 3.7.4
Package: confluent-kafka, version: 1.5.0

**Comment by edenhill** [comment]
@Lakritsbiten What IDE are you using? Can you paste a screenshot or provide some kind of output?

**Comment by Lakritsbiten** [comment]
![image](https://user-images.githubusercontent.com/61198677/92732986-70f53f80-f377-11ea-8737-6d12836667c2.png)
Sure, I am using PyCharm 2020.2.1

**Comment by debradley** [comment]
This may be a bug or limitation in PyCharm's parsing of [the C source code](https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/src/confluent_kafka.c#L550) into binary skeletons where [it is forced to rely on inline docs](https://stackoverflow.com/a/38384411) and gets the details wrong.

**Comment by jpuskar** [comment]
This problem still exists with:

- PyCharm 2023.1.3 (Community Edition) Build #PC-231.9161.41, built on June 20, 2023
- On ARM (MacOS 12.6.5 (21G531)).
- Using confluent-kafka 2.1.1.
- Using Python 3.9.
