### ISSUE TITLE
Lost messages via None returned by Consumer.poll()

### ISSUE THREAD

**Issue by rjurney** [confluentinc/confluent-kafka-python#278]
Description
===========

I keep getting None for message objects returned by Consumer.poll() These messages never reappear in the queue, they are lost. Please help!

My client code is derived from the docs and looks like this:

```
from confluent_kafka import Consumer, KafkaError
kafka_consumer = Consumer({
  "bootstrap.servers": master_config["kafka"]["brokers"][0],
  "security.protocol": 'ssl',
  "ssl.key.location": master_config["kafka"]["service.key"],
  "ssl.certificate.location": master_config["kafka"]["service.cert"],
  "ssl.ca.location": master_config["kafka"]["ca.pem"],
  "group.id": 0,
  "log.connection.close": False,
  "log_level": 3,
  "log.queue": False
})
kafka_consumer.subscribe([master_config["kafka"]["topic"]])

running = True
while running:
  message_object = kafka_consumer.poll()
  if message_object and not message_object.error():
    print('Received message: %s' % message_object.value().decode('utf-8'))
    ... do processing
  elif message_object and message_object.error().code() != KafkaError._PARTITION_EOF:
      print(message_object.error())
      running = False
  else:
    print("Got None for message_object!")
```

How to reproduce
================

Setup an Aiven Kafka cluster. Run the previous Kafka code. Watch messages disappear sometimes.

Checklist
=========
Please provide the following information:

 - [*] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('0.11.0', 720896) and ('0.11.0', 721151)
 - [*] Apache Kafka broker version: 0.11.0.1
 - [*] Client configuration: `{
  "bootstrap.servers": master_config["kafka"]["brokers"][0],
  "security.protocol": 'ssl',
  "ssl.key.location": master_config["kafka"]["service.key"],
  "ssl.certificate.location": master_config["kafka"]["service.cert"],
  "ssl.ca.location": master_config["kafka"]["ca.pem"],
  "group.id": 0,
  "log.connection.close": False,
  "log_level": 3,
  "log.queue": False
}`
 - [*] Operating system: Mac OS X 10.12.5 (16F73)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [*] Provide broker log excerpts - [https://gist.github.com/rjurney/03d585ca3ca177bc933d08d406be599d](https://gist.github.com/rjurney/03d585ca3ca177bc933d08d406be599d)
 - [*] Critical issue - sure is irritating

**Comment by rjurney** [comment]
Not sure how to provide client logs. Can't find it by searching. Can you please advise?

**Comment by edenhill** [comment]
`poll()` should only return `None` when it times out waiting for a message or event, but since you are not specifying a timeout it should block until a proper message or event is received.
This might indicate a bug in the client, but first I want you to correct the None checking, change your code to check for `message_object is not None` and `message object is None` accordingly.
Thus:
```
...
while running:
  message_object = kafka_consumer.poll()
  if message_object is None:
    print('poll timeout, weird..')
  elif not message_object.error():
    print('Received message: %s' % message_object.value().decode('utf-8'))
    ... do processing
  elif message_object.error().code() != KafkaError._PARTITION_EOF:
      print(message_object.error())
      running = False
  else:
    print("Reached EOF for %s" % message_object)
```

**Comment by PGryllos** [comment]
I cal also confirm that on version `('0.9.2', 590080)` we see None messages without specifying a timeout.

**Comment by edenhill** [comment]
@PGryllos What librdkafka version?

**Comment by PGryllos** [comment]
librdkafka version: `('0.9.5', 591359)`

**Comment by edenhill** [comment]
Can you try to reproduce with latest librdkafka (master or v0.11.1)?

**Comment by PGryllos** [comment]
I will try to find some time later to try it out and let you know
