### ISSUE TITLE
Check whether a Topic exists before creating.

### ISSUE THREAD

**Issue by sree80** [confluentinc/confluent-kafka-python#280]
Description
===========

confluent_kafka.TopicPartition

1) Created the Topic.
    Checking to see whether the Topic exists or not
    TopicPartition('test',0,0)
     Returns err=None

2) Topic doesn't exist.
     TopicPartition('test1',0,0)
     Returns err=None

Not sure why in case 2 It is returning err=None

so how do I check whether a Topic exists or not, before creating it.

**Comment by edenhill** [comment]
`TopicPartition()` is just a local tuple type that holds a couple of values for a Topic and Partition. Its actual use depends on which API you pass it to.

**Comment by sree80** [comment]
can I get an example of how do I check whether a Topic exists or not, before creating

**Comment by edenhill** [comment]
You would need to use the Metadata API for that, but that API has not yet been added to the Python bindings.
Tracking issue is here: #161
