### ISSUE TITLE
Repeated _PARTITION_EOF errors when there are still messages in the partition

### ISSUE THREAD

**Issue by kkraus14** [confluentinc/confluent-kafka-python#283]
Description
===========
Consumer returning `_PARTITION_EOF` errors when there are still messages in the topic and partition that haven't been read yet. Running into this problem when using a single kafka broker and a topic with a single partition. Running Kafka 1.0.0 in docker from `confluentinc/cp-kafka:4.0.0`.

* confluent_kafka-python `('0.11.0', 720896)`
* librdkafka `('0.11.0', 721151)`
* Apache Kafka broker version `1.0.0`
* Client config `See reproduce code below`
* Operating System `Ubuntu 16.04.3 kernel 4.4.0-98`

How to reproduce
================
Create topic
```
docker exec -it kafka kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test
```

Continually push messages to topic (sample via Python)
```
from confluent_kafka import Producer
import uuid
import time

producer = Producer({'bootstrap.servers': 'localhost'})
topic = 'test'

while True:
    producer.produce(topic, str(uuid.uuid4()))
    time.sleep(0.25)
```

Create a consumer and subscribe to topic and try to "catch up"
```
from confluent_kafka import Consumer, KafkaError

consumer = Consumer({'bootstrap.servers': 'localhost', 'group.id': 'my-group', 'default.topic.config': {'auto.offset.reset': 'latest'}})
consumer.subscribe([topic])

def catch_up():
    running = True
    while running:
        msg = consumer.poll()
        if not msg.error():
            pass
        else:
            if msg.error().code() == KafkaError._PARTITION_EOF:
                print("Caught up at offset: " + str(msg.offset()))
                running = False
            else:
                print(msg.error())
                running = False

catch_up()
time.sleep(10)
catch_up()
```

The second printed message ends up being 1 offset higher which is much less than expected. Confirm the offset is incorrect using
```
docker exec -it kafka kafka-run-class kafka.tools.GetOffsetShell --broker-list localhost:9092 --topic test
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you print the topic(), partition() and offset() of both messages and EOF and also add a printout when catch_up() is called, and provide some of that output here so we can understand exactly what you are seeing?

**Comment by kkraus14** [comment]
New Catch Up Definition
```
def catch_up():
    running = True
    while running:
        msg = consumer.poll()
        if not msg.error():
            print("Good Message:")
            print("    Topic: " + str(msg.topic()))
            print("    Partition: " + str(msg.partition()))
            print("    Offset: " + str(msg.offset()))
            pass
        else:
            if msg.error().code() == KafkaError._PARTITION_EOF:
                print("Error Message:")
                print("    Topic: " + str(msg.topic()))
                print("    Partition: " + str(msg.partition()))
                print("    Offset: " + str(msg.offset()))
                print("    Error: " + str(msg.error()))
                running = False
            else:
                print(msg.error())
                running = False
```

New calls
```
print("\nCalling First Catch Up...")
catch_up()
print("\nWaiting for 10 seconds for broker to repopulate...")
time.sleep(10)
print("\nCalling Second Catch Up...")
catch_up()
```

Output
```
Calling First Catch Up...
Good Message:
    Topic: test
    Partition: 0
    Offset: 11547
Error Message:
    Topic: test
    Partition: 0
    Offset: 11548
    Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}

Waiting for 10 seconds for broker to repopulate...

Calling Second Catch Up...
Good Message:
    Topic: test
    Partition: 0
    Offset: 11548
Error Message:
    Topic: test
    Partition: 0
    Offset: 11549
    Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
```

**Comment by edenhill** [comment]
Ah yes, an EOF event will be pushed on the consumer queue as soon as the consumer reaches the current end-offset for a new offset, this is all done automatically in the background regardless if the app calls poll() or not.

If the produce rate is slow it is possible that we see something like this:
 * consumer reads msg 1, which is also EOF - emits EOF event
 * app calls poll() and sees msg 1 and EOF
 * producer produces msg 2
 * consumer reads msg 2 - which is also EOF - emits EOF event
 * producer produces msg 3
 * consumer reads msg 3, which is also EOF - emits EOF event
 * .. repeat producer + consumer cycle
 * app calls poll(), now sees 2, EOF, 3, EOF, 4, EOF, ..

The workaround is to set the poll timeout to 0 (immediate) when EOF is reached but continue polling until None (timeout) is returned.

**Comment by kkraus14** [comment]
This explains exactly what I'm seeing, thanks for the detailed explanation!

**Comment by massenz** [comment]
I am seeing the same behavior, but I don't really think the "explanation" explains it.
I have a simple Producer, that publishes a message every 3 seconds; this has now been running for a while, there are probably a hundred or so messages in the topic:
```
In [6]: while True:
   ...:     p.produce('test-topic', '{} - test message'.format(time.ctime()))
   ...:     time.sleep(3)
```
however, the Consumer (which I'd expect to quickly "catch up" consuming all messages in the queue, then wait a beat) sees every other message a `_PARTITION_EOF` error: the following quickly scrolls through (also looking at the timestamp, I know there still are messages pending).

```
In [40]: while True:
    ...:     msg = c.poll(0)
    ...:     if msg is not None:
    ...:         if msg.error():
    ...:             print("Error:", msg.error())
    ...:         else:
    ...:             print(msg.value().decode('utf-8'))
    ...:     else:
    ...:         time.sleep(5)
    ...:         
Thu Feb  8 18:01:23 2018 - test message
Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
Thu Feb  8 18:01:26 2018 - test message
Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
Thu Feb  8 18:01:29 2018 - test message
Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
Thu Feb  8 18:01:32 2018 - test message
Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
Thu Feb  8 18:01:35 2018 - test message
Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
Thu Feb  8 18:01:38 2018 - test message
Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
Thu Feb  8 18:01:41 2018 - test message
Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
Thu Feb  8 18:01:44 2018 - test message
Error: KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"}
Thu Feb  8 18:01:47 2018 - test message
```

I also have the impression that the `Message` class has a different behavior, when testing: `if not msg:` v. 'if msg is not None` - but haven't really been able to figure out where this differs (in Python 3, the behavior ought to be identical, shouldn't it?)

I have tried several variations of that code, the interleaving of valid messages and EOF error is pretty consistent.

**Comment by edenhill** [comment]
How many partitions do you have for that topic?

The point of _PARTITION_EOF is to allow certain applications to know when they've reached the end of a partition, one use case is "read all available messages and then exit/do other stuff".
This event can be safely ignored, or turned off with `enable.partition.eof=false`

**Comment by massenz** [comment]
Thanks for your reply.
This is just a dev deployment: just the one partition, with a single Kafka running in a container.

And, I forgot to mention, this is a version 0.10.2.1 Kafka (the Dockerfile is [here](https://github.com/massenz/docker-kafka).

>The point of _PARTITION_EOF is to allow certain applications to know when they've reached the end of a partition, 

that's what I figured (and what I hoped to be able to use it for), and why that confused me: there were definitely still several hundred messages while I was doing my testing, but I saw that "error" popping up every other message, consistently.

**Comment by edenhill** [comment]
An EOF event will be pushed on the internal message queue (served by poll()) each time the consumer hits a fresh end offset, regardless if your application does not call poll() for 10 seconds.

If the produce rate is less than fetch.wait.max.ms it is likely that there will be an EOF event for each produced message.

**Comment by massenz** [comment]
> each time the consumer hits a fresh end offset

ok, let me freely admit that I probably don't fully understand this sentence.

If we rewind back a little, as a Developer, I would like my `Consumer` to know whether there are still messages in the queue, and if so fetch them and do something with them; or not, in which case I can `sleep()` or work on other stuff (I am writing an `asyncio`-compatible `KafkaListener` so not blocking is imperative).

For this purpose, in my (admittedly, limited) experimentation, the `_EOF` "error" is eminently useless - the only alternative that appears to be viable is to have a very short (possibly 0) timeout in the `poll()` call and check for `None` as the return value - and just ignore the `_EOF` messages as just an endearing quirk of the kafka python client.

>If the produce rate is less than fetch.wait.max.ms it is likely that there will be an EOF event for each produced message.

Of course, but what if the messages are already in the queue? Although my Producer (by design) only produces a message at a very leisurely pace of one every 3 seconds, it started long before the Consumer went to fetch them: so there are, I don't know, say 100-120 sitting there - and, yet, every other fetched message results in a `_EOF` error.

It is entirely possible that this is "intended behavior" (although, I'm kinda hard-pressed to understand its usefulness) but shouldn't it be documented somewhere?

**Comment by edenhill** [comment]
There are two things here:
 * detection of EOF: when a consumer asks for messages starting at offset X and gets back an empty response with the partition HighwaterMark set to offset X the consumer knows it has reached the end of that partition at that specific point in time. A later point in time, be it 1 ms or 1 day may have the same end offset, or a later one if new messages were produced.
 * signaling of EOF: the fetching of messages (and thus the detection of EOF) is detached from application's perspective of receiving a message (by calling poll()) -> the fetching code attempts to pre-fetch messages to provide optimal performance and minimal latency. As messages are fetched they are enqueued on an internal queue (the fetchq) for the application to consume, this same queue will also contain errors and events (such as EOF). Once a message or event has been appended to this queue by the fetcher it no longer maintains any state or knowledge of what was put in there, so even if the end offset of the partition progresses (by new messages being produced) the original EOF event will linger in the queue. The situation you are seeing with multiple EOFs in-queue will only happen when the applications consume rate is lower than the produce rate, which means the consumer will not be able to catch up and that could be a real problem.

Should EOF events be removed from the fetchq when they are "outdated" by new messages? Possibly.
Would it be worthwhile to scan the fetchq? Possibly not

The workaround to disable partition EOF exists for these use-cases, whether it should be the default setting: possibly yes, but changing defaults is problematic for existing applications.

**Comment by massenz** [comment]
@edenhill - thank you so much for the detailed explanation.

My guess is that in "real-life" applications this does work just fine and it was my contrived example to trigger the confusing behavior.

>Should EOF events be removed from the fetchq when they are "outdated" by new messages? Possibly.
>Would it be worthwhile to scan the fetchq? Possibly not

I agree that with the current mechanism, scanning and updating the `fetchq` would be desirable, but inadvisable; the only true "solution" would be for the EOF event to be instead an "out-of-band" (i.e., off-queue) flag that gets set/reset according to the availability of messages in the partition.

Again, thanks for following up - my workaround to ignore the EOF and rely instead on the timeout to signal an "empty" partition, should work just fine for my use case.
