### ISSUE TITLE
Producer sometimes fails to deliver when a broker is shutdown.

### ISSUE THREAD

**Issue by dstruck** [confluentinc/confluent-kafka-python#284]
Description
===========

The producer sometimes fails to deliver messages when a broker is shutdown.

1. Baseline test. Result: All messages were delivered.
2. One broker shutdown upfront. Result: All messages were delivered.
3. One broker shutdown during the delivery of the messages. Result: Two times all messages were delivered and two times some messages failed to be delivered. The error message was:
>message failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}

and in one fail case:
>_MSG_TIMED_OUT: kafka3:9092/3: 3 request(s) timed out: disconnect (average rtt 73.366ms)

Could it be that librdkafka sometimes fails to switch to the new leader of a partition after a broker is shutdown?

**Test setup:** 4 servers; 1 producer, 3 * kafka broker

**Topic setup:** bin/kafka-topics.sh --create --zookeeper kafka1:2181 --replication-factor 3 --partitions 3 --topic test

**confluent-kafka-python:** commit 7ebc807827b83e1d94861e2a59b4fb9bb12c10f0 (Oct 19 2017)

**librdkafka:** commit b9dd3a6e0ae127b76081cfee726bfb961cbd2649 (Dec 4 2017)
Apache Kafka: 1.0.0

How to reproduce
================

**Test script:**
```
import sys, time
from confluent_kafka import Producer

topic = "test"

def error_cb(kafka_error):

    with open("/tmp/kafa_errors", "a") as w:
        print("ERR", kafka_error.name(), kafka_error.str(), file=sys.stderr)
        w.write("{}: {}\n".format(kafka_error.name(), kafka_error.str()))


count_errors, count_success = 0, 0

def delivery_cb(err, msg):

    global count_errors
    global count_success

    if err:
        print('message failed:', err, file=sys.stderr)
        with open("/tmp/kafa_failed", "a") as w:
            w.write(str(msg.value()) + "\n")
        count_errors += 1
    else:
        count_success += 1


conf = {
    'error_cb': error_cb,
    'on_delivery': delivery_cb,
    'bootstrap.servers': 'kafka1:9092,kafka2:9092,kafka3:9092',
    "queue.buffering.max.ms": 100,
    "retries": 10000000,
    "socket.timeout.ms": 500,
    "default.topic.config": {
        "acks": "all",
        "message.timeout.ms": 5000,
    }
}

p = Producer(**conf)

with open("/tmp/kafa_test", "w") as w:

    for i in range(1000000):
        msg = "X" * 1000
        w.write(msg + "\n")

        while 1:
            try:
                p.produce('test', msg)
                break
            except BufferError as e:
                print(e, file=sys.stderr)
                time.sleep(1)  # queue full, wait
            p.poll(0)

p.flush()

print("total errors:", count_errors)
print("total success:", count_success)
print("total:", count_errors + count_success)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [ ] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ctrochalakis** [comment]
This could be related to https://github.com/edenhill/librdkafka/issues/1432

**Comment by dstruck** [comment]
Thanks for the hint. Seems to be the same issue. I hope it will get fixed in librdkafka, then I will re-test the problem with my test setup.

**Comment by edenhill** [comment]
Fixed in librdkafka.
