### ISSUE TITLE
Missing units in timeout values in the docs

### ISSUE THREAD

**Issue by Poochieb** [confluentinc/confluent-kafka-python#285]
I was perusing the docs here: https://docs.confluent.io/current/clients/confluent-kafka-python/index.html, and noticed that the methods that have timeout values as parameters don't specify the units they're in.

Examples are:
poll()
committed()
get_watermark_offsets()
position() - timeout is referenced in the parameter list, but not mentioned in the explanation below it

This was especially an issue for me transitioning from kafka-python to the Confluent library, as the timeout values I used in that library were in ms, and the Confluent ones seem to be in seconds.

Could we change it so that the units are specified for the timeout fields in the documentation? I'm new to github, so I'm not familiar with anything more than filing an issue at this point, but if this is a straightforward thing to change, I'd be happy to help out.

Thanks!
- Blake

**Comment by mmgutsche** [comment]
I can confirm, that this needs to be addressed. I am not even sure that this are seconds. For me the call does not block, independent of what time I set it to.
