### ISSUE TITLE
how to specify the arguments for compression codec in the conf dictionary for producer

### ISSUE THREAD

**Issue by datta90** [confluentinc/confluent-kafka-python#286]
Description
===========
i am writing like this
Producer({'bootstrap.servers': '172.25.0.208:9092,172.25.0.209:9092,172.25.0.57:9092',
              'compression.codec': '2',
               'compression.topics': 'datta'
               }
              )
i get this when i run
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "compression.topics""}
i am using libdrkakfa 0.11 
os ubuntu 16.04.3
kafka version 0.11.2

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 0.11 0.11.1
 - [x] Apache Kafka broker version: 0.11.2
 - [x] Client configuration: `{...}`
 - [x] Operating system: ubuntu 16.04.3
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by datta90** [comment]
thanks edenhill just 1 query the parameter compression.codec should be specified in the global config property or in the topic config property

**Comment by edenhill** [comment]
You should set it on the default.topic.config sub-dict:
`p = Producer({'bootstrap.servers':'...', 'default.topic.config': {'compression.codec': 'snappy'}})`
