### ISSUE TITLE
Support for Message headers

### ISSUE THREAD

**Issue by johnistan** [confluentinc/confluent-kafka-python#287]
Description
===========
[KIP-82](https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers) adds support for message headers. The librdkafka support is in a PR here https://github.com/edenhill/librdkafka/pull/1480

I wanted to track python support here and discuss the python api when it lands upstream.

The headers are an ordered multimap with `string key -> binary value` where a key can be repeated.

There are a couple ways to support this in producer and message api.

List of Tuples/Lists:
```
headers_to_send = [('key1', b'value1'), ('key2', b'value2'), ('key1', b'repeated_key')]
producer.produce('topic_name', b'message_value', headers=headers_to_send)
```

Ordered dict. Python doesn't have a multimap built in, but we could build one or just use an ordered map where values are always nested in lists.
```
headers_to_send = OrderedMultiDict()
headers_to_send['key1'] = [b'value1',  b'repeated_key']
headers_to_send['key2'] = [b'value1']

OR

headers_to_send = OrderedMultiDict()
headers_to_send['key1'] = b'value1'
headers_to_send['key1'].append(b'repeated_key')
headers_to_send['key2'] = b'value1'

producer.produce('topic_name', b'message_value', headers=headers_to_send)
```

What ever the api for producer the consumer `msg.headers()` should return the same format as the producer input. Also for multi-version kafka support mirror the `msg.timestamp()` return flag of `(int, X)` could be used.
```
msg = consumer.poll()
supported_flag, list_of_tuples = msg.headers()
print(list_of_tuples)  # [('key1', b'value1'), ('key2', b'value2'), ('key1', b'repeated_key')]
```

This isn't an exhaustive list of options but i wanted to get the discussion started.

**Comment by edenhill** [comment]
Good input, @johnistan !

The nested list approach does seem like the easiest to work with from a user's perspective.
We can also add support for a standard dict in the produce() call since it is probably rare for an application to add multiple headers with the same name (interceptors might).

Another alternative is to have a richer Headers class with basic CRUD methods, as well as a "supported()" method.

**Comment by edenhill** [comment]
fyi: Message headers have now landed in librdkafka.
