### ISSUE TITLE
How to consume tombstone messages with Consumer.poll()?

### ISSUE THREAD

**Issue by rmechler** [confluentinc/confluent-kafka-python#288]
Description
===========
Consumer.poll() does not seem to return messages that have a key but no value. My application needs to know when a value is deleted. How can I make poll() return these messages, is there configuration I can set?

How to reproduce
================
Use Producer.produce() to send a message that has a key but no value (for a compacted topic). Try to Consume using Consumer.poll().

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 0.11.0, 0.11.1~1confluent4.0.0-1
 - [ ] Apache Kafka broker version: 0.11.0
 - [ ] Client configuration: `{
    'bootstrap.servers': BOOTSTRAP_SERVERS,
    'group.id': GROUP_ID,
    'security.protocol': 'ssl',
    'ssl.ca.location': 'ssl/kafka-ca.crt',
    'ssl.certificate.location': 'ssl/kafka-client.crt',
    'ssl.key.location': 'ssl/kafka-client.key',
    'default.topic.config': {
        'auto.offset.reset': 'earliest'
    }
}`
 - [ ] Operating system: Debian 8

**Comment by rmechler** [comment]
Tried also on MacOS, and upgraded to librdkafka 0.11.3 in case the problem was related to this:

https://github.com/edenhill/librdkafka/issues/1386

but it still doesn't work.

**Comment by rmechler** [comment]
So turns out it does work. The problem I was having was in how I was checking for a timed out poll:
```
    while True:
        msg = c.poll(timeout=2)
        if not msg:
            continue
        ...
```
I should have been checking for None explicitly, i.e.,
```
    while True:
        msg = c.poll(timeout=2)
        if msg == None:
            continue
        ...
```
So my bad. Although I wouldn't have expected 'not msg' to evaluate to true just because there is no message value (and I'm not really clear on why it does).

**Comment by edenhill** [comment]
The boolean object check (`if not msg`) will use `Message.len()` which for empty value messages will return 0, thus False.

It is generally advisable to explicitly check for None, like you do now.

**Comment by jeffwidman** [comment]
@rmechler I just stumbled across this issue while researching something else... FYI for future reference, it should be `msg is None`, not `msg == None`... in python, identity and equality are not the same.
