### ISSUE TITLE
subscribe doesn't seem to accept wildcard topic names

### ISSUE THREAD

**Issue by ronnocol** [confluentinc/confluent-kafka-python#29]
Is there anyway to subscribe to topics using a wildcard/regex using confluent-kafka-python? I know there are other clients (based on librdkafka) that support this functionality (e.g. kafka-python), but this one doesn't seem to.

**Comment by edenhill** [comment]
To enable regex matching you need to prefix the subscribed topic with `^`, e.g.,`^logs_.*`
