### ISSUE TITLE
How to handle (or prevent) MSG_SIZE_TOO_BIG

### ISSUE THREAD

**Issue by cmusser** [confluentinc/confluent-kafka-python#290]
Description
===========
I'm sending a set of messages into a topic and one is big enough to trigger a  MSG_SIZE_TOO_BIG message from the broker. This particular message is 62723 bytes (at least according to the Python len() function called on the payload string. That is lower than the default message.max.bytes (1000012) in the broker. However, the documentation for that seems to indicate that's the maximum size of a "batch" of messages. Is the problem actually that my producer is somehow exceeding the total batch size, maybe because it doesn't send often enough?

How to reproduce
================
This is the send loop:

```
tx = 0
for item in data.items():
    msg = json.dumps(item, default=db.to_serializable)
    try:
        producer.produce('my-topic', msg)
        tx += 1
        producer.poll(0)
        if tx % 1000 == 0:
            print('added {} items to log'.format(tx), end='\r')
        if tx % 100 == 0:
            producer.flush()

    except KafkaException as e:
        print('Kafka error: {}, message was {} bytes'.format(e, len(msg)))
        
producer.flush()
```

1. If the impact is confined to a single message (the big one), maybe just let it slide (or take other action like ensuring that the source data is of reasonable size)?

2. If it's affecting a whole batch, is there a better way to ensure that no overrun is happening? The flush every X messages is a hamfisted way of doing flow control. That might be a separate issue entirely, and spiffing that up might not help anything related to too big messages.

3. As an aside, the consumer program is also getting a TOO_BIG notification as well, when it polls. I suspect, but am unable to confirm, that it's due to this same big message (there's only one of them in the set). What is the meaning of this message in the context of a consumer?

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version: ('0.11.0', 720896) ('0.11.0', 721151)
 - [x] Apache Kafka broker version: kafka_2.12-0.11.0.2
 - [x] Client configuration: 
```producer = Producer({'bootstrap.servers': kafka_server,
                         'message.max.bytes': 50000})
```
 - [x] Operating system: Ubuntu 16.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts: I'll have to rejigger our container to get more verbose logging.
 - [ ] Critical issue

**Comment by treziac** [comment]
Can you give the exact error you get?

In your configuration, you set `'message.max.bytes': 50000`, which is smaller than 62723, so your message can never be sent. Is this intended?
It is recommended to set the same value on clients and broker for `message.max.bytes`

**Comment by wyfSunflower** [comment]
INFO:__main__:time: <module 'time' from '/usr/lib64/python2.7/lib-dynload/timemodule.so'>, name: WebShell, e: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Unable to produce message: Broker: Message size too large"}
INFO:werkzeug:172.20.211.115 - - [19/Dec/2019 10:03:59] "POST / HTTP/1.1" 200 -
INFO:__main__:time: <module 'time' from '/usr/lib64/python2.7/lib-dynload/timemodule.so'>, name: WebShell, e: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Unable to produce message: Broker: Message size too large"}
I also met this error, could anyone give me some advise. Thanks!
