### ISSUE TITLE
Consumer.subscribe(["^*"]) fails

### ISSUE THREAD

**Issue by theguruofreason** [confluentinc/confluent-kafka-python#292]
Description
===========
While attempting to subscribe to all topics, my code crashes with KafkaError{code=_INVALID_ARG,val=-186,str="Failed to set subscription: Local: Invalid argument or configuration"}. Changing the topic to any regex with a static first character works. It seems wildcards are not allowed as the first character, as any topic I pass with * as the first character throws this error.

How to reproduce
================
Open python > 3.5, import confluent kafka consumer, initialize a consumer, run consumer.subscribe(['^*'])

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 0.11.0, 720896; 0.11.1, 721407, respectively
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Ubuntu 16.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by agis** [comment]
What was the actual issue here?

**Comment by edenhill** [comment]
I think the issue was that it was an illegal regel, should be ^. *

**Comment by agis** [comment]
Thank you!
