### ISSUE TITLE
Producer's partitioner

### ISSUE THREAD

**Issue by lxyscls** [confluentinc/confluent-kafka-python#293]
Description
===========

Because I can't assign a custom partitioner due to [#231](https://github.com/confluentinc/confluent-kafka-python/issues/231), so I am curious about the default partitioner. Is it use hash on the key string, or something else?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Yes, it use crc32 hash of the key (or random when no key), modulo partition count. When using random, it also ensures the partition is available.

https://github.com/edenhill/librdkafka/blob/35f28e241240c12c213041b76910e008dbee12ab/src/rdkafka_msg.c#L525

For now, it's not possible to assign the murmur2 partitioner used by default java client (or another custom one) by conf, but it may be in non-prioritzed future given some messages from @edenhill.

You can also kind of mimic a partitioner by calling it before producing: you can get partition count from metadata, so apply whatever algorithm you want and set `partition `in you `produce `call

**Comment by lxyscls** [comment]
Thank you very much @treziac

**Comment by lxyscls** [comment]
@treziac How to get the metadata? My app is just a producer. Below is the API list, I can't find it@_@
https://docs.confluent.io/current/clients/confluent-kafka-python/index.html
