### ISSUE TITLE
_INVALID_ARG errors in Producer when attempting SSL conf

### ISSUE THREAD

**Issue by rudenoise** [confluentinc/confluent-kafka-python#296]
Description
===========

I'm attempting to get the example from the `README.md` working with SSL but get the following error:

```
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create producer: ssl.ca.location failed: No error"}
```

How to reproduce
================

```python
    avro_producer = AvroProducer({
        'security.protocol': "ssl",
        'bootstrap.servers': os.environ['SERVICE_URI'],
        'schema.registry.url': os.environ['SCHEMA_REGISTRY_CON_STR'],
        'ssl.ca.location': './ca.pem',
        'ssl.key.location': './service.key',
        'ssl.certificate.location': './service.cert'
    }, default_key_schema=key_schema, default_value_schema=value_schema)
```

Checklist
=========
Please provide the following information:

 - [x] ('0.11.0', 720896) AND ('0.11.1', 721407):
 - [x ] 1.0.0:
 - [x] `{'security.protocol': "ssl", 'bootstrap.servers': os.environ['SERVICE_URI'], 'schema.registry.url': os.environ['SCHEMA_REGISTRY_CON_STR'], 'ssl.ca.location': './ca.pem', 'ssl.key.location': './service.key', 'ssl.certificate.location': './service.cert'}`
 - [x] Alpine Linux 3.7 (container) :
 - [x] Provide client logs (with `'debug': '..'` as necessary)

**Comment by edenhill** [comment]
OpenSSL error reporting is tricky to get right, which explains the "No error" part.

Can you try reproducing with `'debug': 'security'` and see if the it gives you any more information?
Also make sure ca.pem is indeed in the current directory and is readable and in PEM format.

**Comment by rudenoise** [comment]
With that setting I get a little more detail:
```%7|1515514789.706|SSL|rdkafka#producer-1| [thrd:app]: Loading CA certificate(s) from file ./ca.pem```

if I print the content of the `pem` it appears all on one line, so I guess that is invalid (and therefore my fault!)

I'm passing the contents of the `pem` to the container as an env var and printing it back to a file. I expect I'm doing this wrong.

Thanks for the advice!

**Comment by rudenoise** [comment]
Yep, it was my error not passing the credential files to my container correctly.

Thanks again for the help!
