### ISSUE TITLE
Improve current CachedSchemaRegistryClient implementation

### ISSUE THREAD

**Issue by d0ivanov** [confluentinc/confluent-kafka-python#297]
Description
===========

Currently CachedSchemaRegistryClient sends request to the schema registry by directly calling
get / post / put / delete methods from the requests package. This isn't flexible and provides no control over how requests are performed. Moreover this approach does not take advantage of features provided in the requests package like connection pooling for example.

My proposal is to refactor the CachedSchemaRegistryClient in the following way:
  1. Create a schema registry client which utilizes an instance of requests.Session to perform 
      requests. This instance should be provided to the registry client's constructor so that client code
      can configure it however it sees fit.
2. Build the caching schema registry client on top of that.

**Comment by edenhill** [comment]
This is a palatable idea but we want to avoid exposing `requests` in our public API.

Also, most clients use a small number of schemas (typically 1) during their lifetime, which are cached internally, and there are thus few gains with optimizing for session reuse, etc.

The general idea is to expose relevant http-level configuration through the client's standard dict config interface, such as auth.
