### ISSUE TITLE
Support pypy? Or any plan to support pypy?

### ISSUE THREAD

**Issue by EBWi11** [confluentinc/confluent-kafka-python#298]
Hi,i use confluent-kafka-python for my project,but it can't run with pypy,error is :**KafkaError{code=_UNKNOWN_GROUP,val=-179,str="Failed** to set subscription: Local: Unknown group"} 
but it can perfect run with python3,my rdkafka is :0.9.5,so i think confluent-kafka-python may not support pypy.
Thanks!

**Comment by edenhill** [comment]
PyPy is not supported and there are no plans to add support for it.
Community contributions are very much welcomed though!
