### ISSUE TITLE
ImportError: **/cimpl.so: undefined symbol: PyErr_NewExceptionWithDoc

### ISSUE THREAD

**Issue by isusion** [confluentinc/confluent-kafka-python#301]
hi , in my  machine(centos 6.5) I tried to use conlfuent kafka python like this

1.sudo yum install librdkafka-devel python-devel 
and the result is
`Running Transaction
  Installing : librdkafka-devel-0.9.2_confluent3.1.2-1.el6.x86_64                                                                                                                                       1/1
  Verifying  : librdkafka-devel-0.9.2_confluent3.1.2-1.el6.x86_64                                                                                                                                       1/1

Installed:
  librdkafka-devel.x86_64 0:0.9.2_confluent3.1.2-1.el6

Complete!`

2. sudo pip install confluent-kafka

then I tried to use it. somehow I always get this error message
  File "/home/app/kafka-test/python/kafka_client.py", line 13, in <module>
    from confluent_kafka.cimpl import Producer, Consumer, KafkaError
  File "/usr/lib64/python2.6/site-packages/confluent_kafka/__init__.py", line 2, in <module>
    from .cimpl import (Consumer,  # noqa
ImportError: /usr/lib64/python2.6/site-packages/confluent_kafka/cimpl.so: undefined symbol: PyErr_NewExceptionWithDoc

I have tried to replace the confluent-kafka version to 0.9.2 , but the problem still exist.

how to solve this problem?

**Comment by edenhill** [comment]
It looks like you built confluent_kafka with Python >= 2.7 but trying to run it using Python 2.6 (which lacks PyErr_NewExceptionWithDoc).
If you rebuild it on Python 2.6 you should be fine, or upgrade your runtime to 2.7

**Comment by isusion** [comment]
thanks，when I update the python version to 2.7, the error message not happen any more

**Comment by isusion** [comment]
thanks，when I update the python version to 2.7, the error message not happen any more
