### ISSUE TITLE
Not able to consume from partitions

### ISSUE THREAD

**Issue by rohitgcs** [confluentinc/confluent-kafka-python#308]
Description
===========
Certain partitions don't get consumed from.

Topic: test-topic

There were originally 5 partitions all been consumed from equally.
Now, all of a sudden (even with a restart of the consumer) I am not able to consume from one of the partitions.
It is not a producer issue because I've been working with the same data (it's a simple "{'data':'Hello World'}"

Logs:
%7|1517251396.145|OFFSET|esConsumer#consumer-2| [thrd:main]: Topic test-topic [2]: stored offset -1001, committed offset 139586
%7|1517251396.145|OFFSET|esConsumer#consumer-3| [thrd:main]: Topic test-topic [1]: stored offset -1001, committed offset 139635
%7|1517251396.146|OFFSET|esConsumer#consumer-3| [thrd:main]: Topic test-topic [1]: setting offset INVALID for commit
%7|1517251396.146|COMMIT|esConsumer#consumer-3| [thrd:main]: OffsetCommit internal error: Local: No offset stored
%7|1517251396.146|COMMIT|esConsumer#consumer-3| [thrd:main]: OffsetCommit for 1 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1517251396.146|UNASSIGN|esConsumer#consumer-3| [thrd:main]: Unassign not done yet (0 wait_unassign, 1 assigned, 0 wait commit): OffsetCommit done (__NO_OFFSET)
%7|1517251396.145|OFFSET|esConsumer#consumer-2| [thrd:main]: Topic test-topic [2]: setting offset INVALID for commit
%7|1517251396.146|COMMIT|esConsumer#consumer-2| [thrd:main]: OffsetCommit internal error: Local: No offset stored
%7|1517251396.146|COMMIT|esConsumer#consumer-2| [thrd:main]: OffsetCommit for 1 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1517251396.146|UNASSIGN|esConsumer#consumer-2| [thrd:main]: Unassign not done yet (0 wait_unassign, 1 assigned, 0 wait commit): OffsetCommit done (__NO_OFFSET)
%7|1517251396.145|OFFSET|esConsumer#consumer-1| [thrd:main]: Topic test-topic [0]: stored offset -1001, committed offset 455504
%7|1517251396.146|OFFSET|esConsumer#consumer-1| [thrd:main]: Topic test-topic [0]: setting offset INVALID for commit
%7|1517251396.146|COMMIT|esConsumer#consumer-1| [thrd:main]: OffsetCommit internal error: Local: No offset stored
%7|1517251396.146|COMMIT|esConsumer#consumer-1| [thrd:main]: OffsetCommit for 1 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1517251396.146|UNASSIGN|esConsumer#consumer-1| [thrd:main]: Unassign not done yet (0 wait_unassign, 1 assigned, 0 wait commit): OffsetCommit done (__NO_OFFSET)
%7|1517251396.146|OFFSET|esConsumer#consumer-4| [thrd:main]: Topic test-topic [4]: stored offset -1001, committed offset 139843
%7|1517251396.146|OFFSET|esConsumer#consumer-4| [thrd:main]: Topic test-topic [4]: setting offset INVALID for commit
%7|1517251396.146|COMMIT|esConsumer#consumer-4| [thrd:main]: OffsetCommit internal error: Local: No offset stored
%7|1517251396.146|COMMIT|esConsumer#consumer-4| [thrd:main]: OffsetCommit for 1 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1517251396.146|UNASSIGN|esConsumer#consumer-4| [thrd:main]: Unassign not done yet (0 wait_unassign, 1 assigned, 0 wait commit): OffsetCommit done (__NO_OFFSET)
%7|1517251396.148|HEARTBEAT|esConsumer#consumer-2| [thrd:main]: 172.31.230.127:9092/2: Heartbeat for group "test-topic" generation id 21
%7|1517251396.148|HEARTBEAT|esConsumer#consumer-1| [thrd:main]: 172.31.230.127:9092/2: Heartbeat for group "test-topic" generation id 21
%7|1517251396.148|OFFSET|esConsumer#consumer-5| [thrd:main]: Topic test-topic [3]: stored offset -1001, committed offset 135002
%7|1517251396.148|OFFSET|esConsumer#consumer-5| [thrd:main]: Topic test-topic [3]: setting offset INVALID for commit
%7|1517251396.148|COMMIT|esConsumer#consumer-5| [thrd:main]: OffsetCommit internal error: Local: No offset stored
%7|1517251396.148|COMMIT|esConsumer#consumer-5| [thrd:main]: OffsetCommit for 1 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1517251396.148|UNASSIGN|esConsumer#consumer-5| [thrd:main]: Unassign not done yet (0 wait_unassign, 1 assigned, 0 wait commit): OffsetCommit done 

How to reproduce
================

def launchConsumer():
        consumer = Consumer({'bootstrap.servers': KAFKA_BROKER, \
        'group.id': FROM_TOPIC, 'client.id':'esConsumer',\
        'enable.auto.commit': True,'debug':'cgrp',\
        'default.topic.config': {'auto.offset.reset': 'end'}})
        consumer.subscribe([FROM_TOPIC], on_assign=print_assignment)
        print consumer.assignment()
        hasData = True
        while hasData:
                        print "Running..."
                        message = consumer.poll()
                        if message:
                                        msg = loads(message.value())
                                        logger.debug(msg)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):('0.11.0', 720896), ('0.11.0', 721151)
 - [x] Apache Kafka broker version: 0.9
 - [x] Client configuration: `{...}`
 - [x] Operating system: Linux
 - [x] Provide client logs (with `'debug': '..'` as necessary)
  - [x] Critical issue
- [ ] Provide broker log excerpts

**Comment by edenhill** [comment]
Which partition is it?

**Comment by rohitgcs** [comment]
Partition 2.
This is when I set my config to 'earliest' btw
When I set it back to latest and consume with new data, it fetches.

**Comment by edenhill** [comment]
Okay, can you reproduce with debug=cgrp,topic,fetch and then grep for `thetopicname \[2\]` and provide the logs?
