### ISSUE TITLE
Access to watermark offsets API in python

### ISSUE THREAD

**Issue by aaronhays** [confluentinc/confluent-kafka-python#31]
I just ran across https://github.com/edenhill/librdkafka/issues/503 after spending some time hacking in a solution using the available Python APIs that I'm too embarrassed to discuss publicly. It works fine for initial offset queries, but is not sufficient for keeping track of the current highwater mark during consumption. It would be great to get access to these APIs in Python. Is this on the roadmap anywhere?

I would prefer not to hack this in myself because I'm not quite sure how to correctly manage the memory for those `int64_t *` output parameters (`low` and `high`) between C and Python, as I'm not proficient with the Python C-API. I would probably adapt the interface to return a tuple of `low` and `high` and raise an exception in the case of error, but I don't know if that is the best way to proceed.

**Comment by edenhill** [comment]
Merged!
