### ISSUE TITLE
how to get the broker a msg polled from when i consumed from multiple broker?

### ISSUE THREAD

**Issue by MythRen** [confluentinc/confluent-kafka-python#310]
Description
===========
when i construct a Consumer with conf `{"metadata.broker.list": "broker1,broker2,broker3"}`, 
how can i know the msg polled from the broker is which broker ? 

How to reproduce
================
*not a bug*

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): *any*
 - [x] Apache Kafka broker version: *any*
 - [ ] Client configuration: `{"metadata.broker.list": "broker1,broker2,broker3"}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by MythRen** [comment]
#

**Comment by edenhill** [comment]
That is currently not possible.
Why do you need to know what broker you received the message from?

**Comment by MythRen** [comment]
we consume from many kafka nodes, so we want to know the msg we get is from which node.

Or can i modify the msg before they saved into kafka to add extra fields ?

**Comment by edenhill** [comment]
The receiving or transmitting broker isn't very interesting, especially not when using replication (which you should) since the message may be produced to broker 1 and later consumed from broker 1, 2 or 3.

**Comment by MythRen** [comment]
thanks for your nice explanation. i will learn more about kafka .

and i will close this issue.
