### ISSUE TITLE
Unable to consume from kafka topics - brokers version 0.8.2.1 

### ISSUE THREAD

**Issue by ravikiranks** [confluentinc/confluent-kafka-python#320]
Description
===========
1) Even though the configs are set as per the documentation , unable to consume from kafka 0.8.2.1 cluster topic! details as given below
2) used assign method since the brokers version is 0.8.2.1

How to reproduce
================
used configuration as below ,
    conf = {'bootstrap.servers': broker,
            'group.id': group,
            #'session.timeout.ms': 100000,
            'broker.version.fallback': '0.8.2.1',
            'api.version.request': 'false',
            'default.topic.config': {'auto.offset.reset': 'smallest'}
            }

Used assign method --
    tp1 = TopicPartition(topics[0], 1)
    tp2 = TopicPartition(topics[0], 2)
    tp3 = TopicPartition(topics[0], 3)
    c.assign([tp1,tp2,tp3])

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):

librdkafka-devel-0.11.1_confluent4.0.0-1.el7.x86_64
/usr/lib64/python2.7/site-packages/confluent_kafka-0.11.0-py2.7.egg-info:

 - [ ] Apache Kafka broker version:
0.8.2.1

 - [ ] Client configuration: `{...}`
    conf = {'bootstrap.servers': broker,
            'group.id': group,
            #'session.timeout.ms': 100000,
            'broker.version.fallback': '0.8.2.1',
            'api.version.request': 'false',
            'default.topic.config': {'auto.offset.reset': 'smallest'}
            }

 - [ ] Operating system:
centos 2.7

 - [ ] Provide client logs (with `'debug': '..'` as necessary)

just prints this -- 
%3|1519110795.665|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: Broker: Unknown topic or partition: Broker: Unknown topic or partition
%3|1519110795.665|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: Broker: Unknown topic or partition: Broker: Unknown topic or partition
%3|1519110795.665|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: Broker: Unknown topic or partition: Broker: Unknown topic or partition
%3|1519110796.637|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: Broker: Unknown topic or partition: Broker: Unknown topic or partition
%3|1519110796.637|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: Broker: Unknown topic or partition: Broker: Unknown topic or partition
%3|1519110796.637|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: Broker: Unknown topic or partition: Broker: Unknown topic or partition
%3|1519110797.638|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: Broker: Unknown topic or partition: Broker: Unknown topic or partition
%3|1519110797.638|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: Broker: Unknown topic or partition: Broker: Unknown topic or partition

 - [ ] Provide broker log excerpts

 - [ ] Critical issue

**Comment by edenhill** [comment]
Also set config key `'debug': 'cgrp,fetch,topic,broker,protocol'` and provide about a 100 lines of output

**Comment by ravikiranks** [comment]
Hi Team,

Thank you for response!
I have set the config 'debug': 'cgrp,fetch,topic,broker,protocol' and attached the stack trace!

[stack_trace.log](https://github.com/confluentinc/confluent-kafka-python/files/1742236/stack_trace.log)


Thank you
Ravi

**Comment by edenhill** [comment]
> `%7|1519167605.036|METADATA|rdkafka#consumer-1| [thrd:main]: Error in metadata reply for topic sylog-bench (PartCnt 0): Broker: Unknown topic or partition`

It seems `sylog-bench` does not exist in the cluster. Did you perhaps mean `syslog-bench`?

**Comment by ravikiranks** [comment]
Thanks a lot, edenhill! 
you are right, the topic indeed got messed up as I was trying to mirror from a 0.8.2.1 cluster to a 0.10.1.0 cluster!

**Comment by ravikiranks** [comment]
Hi edenhill,

For kafka cluster 0.8.2.1 , we need to always manually specify how many partitions specific topic has and use assign method? Is there a way we can make program discover the number of partitions for a specific topic?

Used assign method --
tp1 = TopicPartition(topics[0], 1)
tp2 = TopicPartition(topics[0], 2)
tp3 = TopicPartition(topics[0], 3)
c.assign([tp1,tp2,tp3])


Many thanks
Ravi

**Comment by edenhill** [comment]
Currently no, there is a PR to add the listTopics() API that will give you this information, but it is not yet ready for merging.

**Comment by ravikiranks** [comment]
@edenhill  Thank you!
related question - can we use single consumer object to consume from more than one topic? 

We are setting up a mirrormaker  using the examples provided in this project 
consume from - 0.8.2.1 cluster
produce to - 0.10.1.0 cluster (with SASL_PLAINTEXT)

so the real question is do we need to use a separate consumer and producer for each topic??

tp1 = TopicPartition(topics[0], 1)
tp2 = TopicPartition(topics[0], 2)
tp3 = TopicPartition(topics[0], 3)

tp4 = TopicPartition(topics[1], 1)
tp5 = TopicPartition(topics[1], 2)
tp6 = TopicPartition(topics[1], 3)

c.assign([tp1,tp2,tp3,tp4,tp5,tp6])

**Comment by edenhill** [comment]
You can consume any number of topics+partitions with a single consumer (and you should, it is more effective that way)

**Comment by ravikiranks** [comment]
Like a mirror maker I am consuming from 0.8.2.1 non-secure cluster and producing to secure cluster.

Question - Will this code work effectively ? I read in this link that thread-pool will work better, could you pls explain further. apologize didn't have time to go in deep.

currently example code tweaked as below --

producer_conf = {'bootstrap.servers': 'xyz:9092',
                     'group.id': 'grp_bikafka_mar1_produce',
                     'session.timeout.ms': 3600000,
                     'default.topic.config': {'auto.offset.reset': 'latest','acks':1},
                     #'debug': 'cgrp,fetch,topic,broker,protocol',
                     'queue.buffering.max.messages': 10000000,
                     'queue.buffering.max.kbytes': 2097151,
                     #'queue.buffering.max.ms': 900000,
                     'queue.buffering.max.ms': 0,
                     'security.protocol': 'sasl_plaintext',
                     'sasl.mechanisms': 'GSSAPI',
                     'sasl.kerberos.service.name': 'kafka',
                     'sasl.kerberos.keytab': '/home/logshipper/logshipper.keytab',
                     'sasl.kerberos.principal': 'logshipper/logshipper@CORPMZ.COM'
                    }

    def delivery_callback(err, msg):
        if err:
            sys.stderr.write('%% Message failed delivery: %s\n' % err)
        #else:
        #    sys.stderr.write('%% Message delivered to %s [%d] @ %o\n' %
        #                     (msg.topic(), msg.partition(), msg.offset()))

    # Create Producer instance
    p = Producer(**producer_conf)

    # Read messages from Kafka, print to stdout
    try:
        while True:
            msg = c.poll(timeout=1.0)
if msg is None:
                continue
            if msg.error():

                # Error or event
                if msg.error().code() == KafkaError._PARTITION_EOF:
                    # End of partition event
                    #sys.stderr.write('%% %s [%d] reached end at offset %d\n' % (msg.topic(), msg.partition(), msg.offset()))
                    pass
                elif msg.error():
                    # Error
                    raise KafkaException('%% %s [%d] reached end at offset %d\n' % (msg.error()))

                '''
                #if msg.error():
                    # Error
                raise KafkaException('%% Message failed delivery: %s\n' % (msg.error()))
                '''
            else:
                # Proper message
                p.produce(msg.topic(), msg.value(), callback=delivery_callback)
                p.poll(0)
    except BufferError as e:
        sys.stderr.write('%% Local producer queue is full (%d messages awaiting delivery): try again\n' %  len(p))
        p.poll(0)

    except KeyboardInterrupt:
        sys.stderr.write('%% Aborted by user\n')

    # Close down consumer to commit final offsets.
    c.close()
        # Wait until all messages have been delivered
    sys.stderr.write('%% Waiting for %d deliveries\n' % len(p))
    p.flush()

**Comment by edenhill** [comment]
I think your code looks good, you might want to increase `queue.buffering.max.ms` to promote larger batches and thus higher throughput, 50ms seems to be a reasonable value.

You also need to set `'api.version.request': False, 'broker.version.fallback=0.8.2.1'` on clients interacting with older brokers.
