### ISSUE TITLE
Inconsistent constructor usage in docs

### ISSUE THREAD

**Issue by ecksun** [confluentinc/confluent-kafka-python#321]
Description
===========

The examples in the README does not correspond to the API documentation.

For example in the README it says:

```python
from confluent_kafka import Consumer, KafkaError

c = Consumer({'bootstrap.servers': 'mybroker', 'group.id': 'mygroup',
              'default.topic.config': {'auto.offset.reset': 'smallest'}})
```

However in the [API docs](https://docs.confluent.io/current/clients/confluent-kafka-python/index.html#confluent_kafka.Consumer.Consumer) the constructor looks like this:

```
Consumer(**kwargs)
```

This was rather confusing when starting out. Moreover my IDE considered the form in the README to be invalid (it did not match the signature).

[The examples](https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/consumer.py#L74) also look like what I would expect.

Thus I suggest to change the README to `Consumer(**{...})`.

Edit: The same is also true for the constructors of `Producer` and the Avro constructors as well

How to reproduce
================
N/A

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): N/A
 - [x] Apache Kafka broker version: N/A
 - [x] Client configuration: N/A
 - [x] Operating system: N/A
 - [x] Provide client logs (with `'debug': '..'` as necessary): N/A
 - [x] Provide broker log excerpts: N/A
 - [ ] Critical issue

**Comment by edenhill** [comment]
We actually support both kwargs and a dict, and we're trying to move away from the `**conf` notation because it confuses people and serves no purpose.

**Comment by ecksun** [comment]
> We actually support both kwargs and a dict, and we're trying to move away from the **conf notation because it confuses people and serves no purpose.

Right, that make sense.

Then perhaps the right thing to do is to change the API to be `Consumer(config, **kwargs)` ?

**Comment by edenhill** [comment]
Yeah, that'd work.

What IDE are you using btw?

**Comment by ecksun** [comment]
> What IDE are you using btw?

IntelliJ with the python plugin normally but I ran into some issue with it not wanting to understand the .so file of confluent-kafka so for the project that uses confluent-kafka I use PyCharm

**Comment by ecksun** [comment]
Looks good to me, thank you :)
