### ISSUE TITLE
Offset Doesn't Commit Properly

### ISSUE THREAD

**Issue by rohitgcs** [confluentinc/confluent-kafka-python#322]
Description
===========

I have a topic with 5 partitions and I'm trying to consume from them.
When initially I consume from them with offset reset to latest, it doesn't consume anything.
So I set it to earliest and I noticed this in the debug statements that I found interesting.

Why does the offest recorded get overwritten in the next line as INVALID?
```
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [0]: stored offset -1001, committed offset 902
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [0]: setting offset INVALID for commit
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [1]: stored offset -1001, committed offset 902
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [1]: setting offset INVALID for commit
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [2]: stored offset 1904, committed offset 1854
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [2]: setting stored offset 1904 for commit
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [3]: stored offset -1001, committed offset 952
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [3]: setting offset INVALID for commit
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [4]: stored offset -1001, committed offset 952
%7|1519428505.107|OFFSET|bulk#consumer-1| [thrd:main]: Topic partitiontesttopic [4]: setting offset INVALID for commit
```

**Comment by edenhill** [comment]
`stored offset` represents the offset (+1) of the last (highest) message consumed by the application,
if your application has not consumed a message, or you have disabled `enable.auto.offset.store` and not called `store_offsets()` then there will be no offset to commit.

**Comment by rohitgcs** [comment]
But this is in the span on consuming some values.And I haven't explicitly set enable.auto.offset.store to disable, so I assume it is one by default? What else can I look for to figure out why?

**Comment by edenhill** [comment]
Use `"debug":"fetch,cgrp"` to see why and what the consumer is fetching
