### ISSUE TITLE
setting max.request.size doesn't work?

### ISSUE THREAD

**Issue by Data-drone** [confluentinc/confluent-kafka-python#325]
Description
===========

`max.request.size` doesn't work when initialising kafka producer in python
trying to follow: https://stackoverflow.com/a/39026744/1687633

How to reproduce
================

```
from confluent_kafka import Producer
import json
import numpy as np

kaf_producer = Producer({
       'bootstrap.servers': 'localhost:29092',
       'max.request.size': 5242880
})

kaf_producer.produce('test_topic', json.dumps(np.random.randint(size=50000).tolist()) )
```

output is:

`KafkaException: KafkaError(code=INVALID_ARG, value=-186,str="No such configuration property: "max.request.size"")`

but according to the stackoverflow post we need to set max.request.size to send the larger message on the producer?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent_kafka_python = 0.11.0 libversion=0.11.3
 - [ ] Apache Kafka broker version: latest confluent kafka docker
 - [ ] Client configuration: `{...}` confluent kafka docker with 
                                                  KAFKA_REPLICA_FETCH_MAX_BYES set to 8388608
                                                  KAFKA_MESSAGE_MAX_BYTES set to 7340032
 - [ ] Operating system: linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts - No broker errors
 - [ ] Critical issue

**Comment by edenhill** [comment]
confluent-kafka-python is based on librdkafka which tries to follow the official Java/Scala client configuration properties, but the latter have changed over time so there is no longer a 1:1 mapping.

See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md for the full list.

What you are looking for is `message.max.bytes`
