### ISSUE TITLE
Cannot make weakref to consumer

### ISSUE THREAD

**Issue by martindurant** [confluentinc/confluent-kafka-python#327]
Description
===========

I would like to use weakref to clean up consumers when they are no longer needed.
The exception is as follows:
```
TypeError: cannot create weak reference to 'cimpl.Consumer' object
```

How to reproduce
================

```python

In [1]: import confluent_kafka as ck

In [2]: consumer = ck.Consumer({'bootstrap.servers': 'localhost:9092', 'group.id': 'tester'})

In [3]: import weakref

In [4]: weakref.ref(consumer)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-63a6473c3f9f> in <module>()
----> 1 weakref.ref(consumer)

TypeError: cannot create weak reference to 'cimpl.Consumer' object
```

Checklist
=========

version: ('0.11.0', 720896)
libversion: ('0.9.4', 591103)
kafka broker: any
osx 10.12.6 Python 3.5.3 |Anaconda custom (x86_64)

**Comment by edenhill** [comment]
We'll look into this after the next release.

https://docs.python.org/2.4/lib/weakref-extension.html

**Comment by mrocklin** [comment]
I found these docs as well, which might be a bit more up-to-date: https://docs.python.org/3/extending/newtypes.html#weakref-support
