### ISSUE TITLE
Incomplete test exclusion in setup script

### ISSUE THREAD

**Issue by hoefling** [confluentinc/confluent-kafka-python#332]
The current test exclusion only excludes the `tests` package, but not the subpackages:

https://github.com/confluentinc/confluent-kafka-python/blob/cd90d4274f5bbfbdadb0b302785b544cacf4db47/setup.py#L24

Therefore, the package `tests.avro` is included in the distribution:

```python
In [1]: from setuptools import find_packages

In [2]: find_packages(exclude=("tests",))
Out[2]:
['confluent_kafka',
 'tests.avro',
 'confluent_kafka.avro',
 'confluent_kafka.kafkatest',
 'confluent_kafka.avro.serializer']
```

Suggestion: extend the exclusion list to include all subpackages in `tests`:

```python
packages=find_packages(exclude=("tests", "tests.*",)),
```

**Comment by edenhill** [comment]
Would you like to (re)open a PR for this?

**Comment by hoefling** [comment]
No, because I don't want to leak my private data in signing the license agreement. But it's just one LOC anyway.

**Comment by rnpridgeon** [comment]
I got ya covered @hoefling! Thanks for the PR
