### ISSUE TITLE
Exception handling doesn't work with python 3

### ISSUE THREAD

**Issue by davidemicelisky** [confluentinc/confluent-kafka-python#335]
Description
===========
Exception handling doesn't work with python 3.
You should use instead `except Exception as e:` that works on both versions.

How to reproduce
================
On Ubuntu 16.04 LTS on python3 console:
```python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from confluent_kafka import avro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/confluent_kafka/avro/__init__.py", line 8, in <module>
    from confluent_kafka.avro.load import load, loads  # noqa
  File "/usr/local/lib/python3.5/dist-packages/confluent_kafka/avro/load.py", line 42, in <module>
    from avro import schema
  File "/usr/local/lib/python3.5/dist-packages/avro/schema.py", line 340
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`0.11.0` and `0.11.1`):
 - [x] Apache Kafka broker version: 4.0
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Linux Ubuntu 16.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It looks like you have a Python 2 version of avro installed.

**Comment by davidemicelisky** [comment]
Thanks @edenhill for the response, yeah as you said the issue was a different version of avro package installed.

I resolved uninstalling the python 2 lib of avro with `pip3 uninstall avro avro-python3` and reinstall only `avro-python3`.

You can close this issue.. thanks again!
