### ISSUE TITLE
What unit is Customer.poll's timeout?

### ISSUE THREAD

**Issue by estrehle** [confluentinc/confluent-kafka-python#336]
The `Customer.subscribe()` method takes an optional argument `timeout`. The [documentation](https://docs.confluent.io/current/clients/confluent-kafka-python/index.html#consumer) does not specify the unit of this variable. Is it seconds?

**Comment by edenhill** [comment]
Yes, seconds (float). The underlying granularity is milliseconds.

**Comment by rnpridgeon** [comment]
Marking as closed as it looks like the relevant changes have been made to the docs on master as well.
