### ISSUE TITLE
Error creating AvroConsumer

### ISSUE THREAD

**Issue by rpwils** [confluentinc/confluent-kafka-python#348]
Description
===========
I am trying to create a AvroConsumer with a protocol of SSL and i am getting this error. 

 File "/Library/Python/2.7/site-packages/confluent_kafka/avro/__init__.py", line 95, in __init__
    super(AvroConsumer, self).__init__(config)
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create consumer: Error reading PKCS#12 file: asn1_lib.c:157: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long: "}

 
How to reproduce
================
Create a simple consumer using this to initiate : 

c = AvroConsumer({
        'bootstrap.servers': 'mybootstrapserver:0000',
        'security.protocol': 'ssl',
        'ssl.key.location':'./dst/my_client_keystore.pem',
        'schema.registry.url': 'http://kafka-sr.mm:8081',
        'ssl.ca.location' : './kafka_ca.cert',
        'ssl.certificate.location':'./dst/my_kafka_client.cert',
        'ssl.keystore.location' : './dst/my_kafka_client_keystore.jks',
        'ssl.keystore.password' : 'XXXXXX',
        'ssl.key.password': 'XXXXXXX',
        'group.id': 'mygroup',
        "default.topic.config": {"auto.offset.reset": "smallest"}
    })

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):  0.11.1 and   0.9.4
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `{...}` above
 - [x] Operating system: mac Sierra 10.12.6
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are passing a java keystore when a PKCS#12 is expected.
https://stackoverflow.com/questions/2846828/converting-jks-to-p12
