### ISSUE TITLE
python Kafka producer does not work with multi worker python framework like sanic and japronto.

### ISSUE THREAD

**Issue by souravroy0708** [confluentinc/confluent-kafka-python#351]
Description
===========

I am implementing python sanic web framework to produce message in kafka topic.So when I am using worker more than one in my application then kafka produce not able to produce message but when i am using worker as 1 then kafka client able to produce the message.

So is there any way to work kafka producer with python multiprocessing.After running python app.py I am able to that it is running in multiple processes.

501 14712 14709   0  7:56AM ttys002    0:00.03 python app.py
501 14713 14709   0  7:56AM ttys002    0:00.03 python app.py

Sanic reference -  http://sanic.readthedocs.io/en/latest/sanic/deploying.html#workers

**Comment by edenhill** [comment]
The Kafka client uses internal threads and since threads will not survive a fork()/subprocess.. you will not be able to use a client instance instantiated in the parent process from a child process.
Instantiate a client in each child instead.

**Comment by rhaarm** [comment]
A work around that I've used with Falcon web framework which uses gunicorn. In the gunicorn settings file, the function definition of post_worker_init can setup the global kafka producer/consumer for that worker thread/process.

**Comment by edenhill** [comment]
Join with issue #100
