### ISSUE TITLE
Does python binding support exactly once semantics?

### ISSUE THREAD

**Issue by hrchu** [confluentinc/confluent-kafka-python#357]
Does python binding support exactly once semantics in producer/consumer side in Kafka 0.11.0.0? I don't see any document mentioned it.

**Comment by edenhill** [comment]
It does not, we're looking to add EoS support in Q3

**Comment by hrchu** [comment]
Related question: Is transactional producer/consumer available now or in Q3?  ( I will like to do exactly-once delivery when processing data between Kafka topics)

**Comment by edenhill** [comment]
No, idempotent producer, transactions and EoS will be released together in Q3

**Comment by lcary** [comment]
@edenhill Do you have an update or an ETA for the [above-mentioned](https://github.com/confluentinc/confluent-kafka-python/issues/357#issuecomment-384718559) release? [v0.11.5](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v0.11.5) didn't appear to have any related changes. Thanks in advance.

**Comment by edenhill** [comment]
@lcary We're currently working on the idempotent producer in librdkafka, which will be released in a month or so, including support in the Python, Go and .NET clients.
It provides exactly once and ordering **producer** guarantees.

Transaction support in the consumer (which boils down to filtering out uncommitted messages) will come soon after.

As for Producer Transaction support, we don't currently have a scheduled release date.

This issue tracks demand for the different EOS  features, please cast your vote there:
https://github.com/edenhill/librdkafka/issues/1308

**Comment by lcary** [comment]
@edenhill thanks so much for the link and update. I just cast my votes.

**Comment by tarunagra** [comment]
Wondering, if idempotent support for Python Producer is released?

**Comment by edenhill** [comment]
Target is within two weeks, all systems are go.

**Comment by russellpierce** [comment]
👋 Looking for an update on this issue.

**Comment by mhowlett** [comment]
idempotent producer is included in 1.0, which is now released.
transactions are not here yet, but we have begun work on the first part of that (consumer side only) which will be done this quarter.

**Comment by hrchu** [comment]
@mhowlett any update on this?

**Comment by mhowlett** [comment]
support in the consumer to ignore aborted transactions is almost merged and a release containing this is currently on track for a few weeks. work on the producer side of transactions hasn't begun yet.

**Comment by alexpirine** [comment]
@mhowlett  I am sorry, I didn't comment on the right project (https://github.com/confluentinc/confluent-kafka-dotnet/issues/1091#issuecomment-590960136). I was wondering about the status of the transactions integration for the Python library…

There are some other implementations (kafka-python and aiokafka) and we wonder if we should wait for transactions support or switch to one of these.

Thank you

**Comment by mhowlett** [comment]
I don't think those libraries have support for either idempotent producer or transactions. v1.4.0 of this client is not far off and will include support for transactions (it already provides idempotent producer).

**Comment by lsorber** [comment]
Now that v1.4.0 has been released, is this issue resolved?

Would someone be so kind as to update the docs with details about EOS?

**Comment by edenhill** [comment]
EOS is now fully supported
