### ISSUE TITLE
Failed to create consumer: No provider for SASL mechanism GSSAPI

### ISSUE THREAD

**Issue by ghsl18** [confluentinc/confluent-kafka-python#361]
Description
===========

confluent-kafka-python: 0.11.4
librdkafka: 0.11.3
apache kafka: 0.9.0
operating system: CentOS 7

On version 0.11.4 I get the following error when I try to instantiate a Consumer:

`cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create consumer: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM"}
`

The identical code works fine on 0.11.0. This if my conf:

```
conf = {
    'bootstrap.servers': '{}:9093'.format(kafka_broker),
    'group.id': group,
    'session.timeout.ms': 6000,
    'sasl.kerberos.principal': 'user_test/user_test@MY.REALM',
    'sasl.kerberos.keytab': '$HOME/user_test.keytab',
    'security.protocol': 'SASL_PLAINTEXT',
    'default.topic.config': {'auto.offset.reset': 'smallest'},
    }
```

How to reproduce
================

`c = Consumer(conf)`

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [N/A] Provide broker log excerpts
 - [no] Critical issue

**Comment by edenhill** [comment]
This is hidden in the README:
The pre-built Linux wheels do NOT contain SASL Kerberos support. If you need SASL Kerberos support you must install librdkafka and its dependencies using the above repositories and then build confluent-kafka from source.

**Comment by rnpridgeon** [comment]
Opened a PR to make the SASL disclosure more visible in the README

https://github.com/confluentinc/confluent-kafka-python/pull/378
