### ISSUE TITLE
Use custom Login Module instead of PlainLoginModule

### ISSUE THREAD

**Issue by mddubey** [confluentinc/confluent-kafka-python#363]
We are using the confluent-kafka-python to connect to our Kafka-instances. To access this we need to be authenticated and it is not plain username/password authentication, we need to get an access_token from an Identity-Service and use it to access the Kafka-instances.

Can someone please help me with the configuration for this in kafka-python? It is same as doing something below in java:-

KafkaClient {
  com.mykafka.KafkaIdentityClientLoginModule required;
};
Where KafkaIdentityClientLoginModule is the name of the custom login module.

Thanks

**Comment by edenhill** [comment]
Custom auth modules are not currently supported in confluent-kafka-python (nor the underlying librdkafka).

Our clients roadmap is customer and community driven, the more interest there is for a feature the more likely it is to be included in a future release.

**Comment by mddubey** [comment]
Hey @edenhill, Thanks for your response!

I am quite new to python so right now facing a lot of challenges regarding the same. Is there a workaround for this or any other Kafka-package(library) which supports it?

Thanks.

**Comment by mddubey** [comment]
I will give it a try, thanks.

**Comment by rnpridgeon** [comment]
This seems to be a reference to JAAS which is specific to Java. While both Python and librdkafka both support SASL as an authentication model but to my knowledge neither C nor Python offer JAAS equivalent out of the box.
