### ISSUE TITLE
Surviving "Commit failed: Broker: Specified group generation id is not valid" on Broker restart

### ISSUE THREAD

**Issue by bretthoerner** [confluentinc/confluent-kafka-python#368]
* Version 0.11.4 of both confluent-kafka-python and librdkafka.
* Ubuntu Trusty.
* Kafka 0.11.0.0 (CP 3.3.0), 3 brokers, replication=3, min.insync=2

```
consumer_config = {
    'enable.auto.commit': False,
    'bootstrap.servers': bootstrap_server,
    'group.id': group_id,
    'default.topic.config': {
        'auto.offset.reset': 'error',
    }
}
```

My manually committing consumer is unable to survive a broker stopping. Maybe this is expected, but I'm not sure how people typically handle this use case:

* I poll until I have a desirable batch size to write to an external DB.
* I write the batch to the external DB.
* I call `consumer.commit(asynchronous=False)` to ensure the matching offsets are committed to the broker.

(Note that I write a batch and commit to Kafka at minimum every ~10 seconds, and the flush to external DB happens in under ~2 seconds. I don't think I'm running up against any timeouts. My brokers run pretty much the default configuration.)

The issue is I'd like for my consumer to survive a broker restart, but I get the following when I stop one of my 3 brokers and I was in the middle of a DB write (which means a commit happens seconds later):

```
2018-05-07 17:37:27,135 140218522564480 Flushing 13588 items: forced:False size:False time:True
2018-05-07 17:37:28,574 140218522564480 Worker flush took 1438ms, committing to Kafka
2018-05-07 17:37:39,399 140218522564480 Flushing 10606 items: forced:False size:False time:True
%3|1525714660.065|FAIL|rdkafka#consumer-1| [thrd:192.168.208.112:9092/3]: 192.168.208.112:9092/3: Receive failed: Disconnected
%3|1525714660.065|ERROR|rdkafka#consumer-1| [thrd:192.168.208.112:9092/3]: 192.168.208.112:9092/3: Receive failed: Disconnected
%3|1525714660.166|FAIL|rdkafka#consumer-1| [thrd:192.168.208.112:9092/3]: 192.168.208.112:9092/3: Connect to ipv4#192.168.208.112:9092 failed: Connection refused
%3|1525714660.166|ERROR|rdkafka#consumer-1| [thrd:192.168.208.112:9092/3]: 192.168.208.112:9092/3: Connect to ipv4#192.168.208.112:9092 failed: Connection refused
2018-05-07 17:37:40,420 140218522564480 Worker flush took 1019ms, committing to Kafka
Traceback (most recent call last):
  File "consumer.py", line 197, in _flush
    self.consumer.commit(asynchronous=False)
KafkaException: KafkaError{code=ILLEGAL_GENERATION,val=22,str="Commit failed: Broker: Specified group generation id is not valid"}
```

What's more confusing, is that after that occurs it seems like the offsets in the broker are corrupted or removed, because when I restart my consumer I get the following:

```
2018-05-07 17:43:44,120 139943834724224 New partitions assigned: [TopicPartition{topic=snuba,partition=0,offset=-1001,error=None}, TopicPartition{topic=snuba,partition=1,offset=-1001,error=None}, TopicPartition{topic=snuba,partition=2,offset=-1001,error=None}]
2018-05-07 17:43:44,122 139943834724224 KafkaError{code=_NO_OFFSET,val=-168,str="no previously committed offset available"}
2018-05-07 17:43:44,122 139943834724224 KafkaError{code=_NO_OFFSET,val=-168,str="no previously committed offset available"}
2018-05-07 17:43:44,122 139943834724224 KafkaError{code=_NO_OFFSET,val=-168,str="no previously committed offset available"}
```

And then, of course, nothing happens. So I have to reset to earliest or latest (or manually find out the correct offsets).

(Note that without a broker stop I can run multiple consumers, start and stop them regularly, and everything including offset storage is working just fine.)

So I have two questions:
* What's the proper way to survive `Commit failed: Broker: Specified group generation id is not valid`? In some of my research it seems like my only option is to continue to `poll()` and wait? But if so then how do I know when is safe to commit? And by polling wouldn't I be popping new messages off the queue and thus moving the offsets further than what I just wrote to my DB? Is there a "right way" to do what I'm trying to do that I'm missing?
* On a `Commit failed: Broker: Specified group generation id is not valid` I would have expected nothing to be committed, but it seems to break all of my stored offsets? Is that expected?

**Comment by bretthoerner** [comment]
Oh, this *probably* isn't technically Python specific -- though I am using the Python client. Just let me know if I should move this to `librdkafka` issues?

**Comment by bretthoerner** [comment]
* How many brokers do you have in the cluster?

3 brokers

* What's the replication factor on the __consumer_offsets topic, and is the ISR set complete (all replicas are in the ISR (In-Sync-Replica set))?

`Topic:__consumer_offsets` has `ReplicationFactor:3` and `min.insync.replicas=2`, and yes all 3 replicas are in the ISR.

* Which broker are you killing? The group coordinator?

How do I tell? I've been choosing one at random and this typically reproduces my issue.

**Comment by edenhill** [comment]
Could you try to reproduce this with `debug=cgrp,topic,protocol` enabled and provide us the logs? (anonymized as necessary)

**Comment by bretthoerner** [comment]
Here's a debug log: https://gist.githubusercontent.com/bretthoerner/392c137ac415000e87919fcadfadd032/raw/59456d70bac280a27ac67f34201c0acad2d3ba0e/gistfile1.txt

Note that in this case it crashed in the flush+commit during the `on_partitions_revoked`. It's my understanding that this should be allowed (it happens quickly, before any timeouts I know of)?

It will also crash if my consumer is mid-flush (to the external DB) when the broker dies and then it attempts to commit, before it has run the `on_partitions_revoked` callback via the `poll` run (which happens every few seconds, before any timeouts I know of).

**Comment by bretthoerner** [comment]
We upgraded our brokers to 1.1.0 and can't reproduce this issue now... Hopefully this helps someone else on Google in the future. :blush:
