### ISSUE TITLE
instalattion 

### ISSUE THREAD

**Issue by A-AFTAHI** [confluentinc/confluent-kafka-python#369]
Description
===========
i have just cloned the library but i can't find the folder so i can run the setup.py file

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
setup.py resides at the top level directory.

But I suggest you install this module from pypi instead:
`pip install confluent_kafka`
