### ISSUE TITLE
Improper usage of Consumer constructor crashes python interpreter

### ISSUE THREAD

**Issue by aaronhays** [confluentinc/confluent-kafka-python#37]
If you call the Consumer constructor with no parameters, python segfaults. 

```
Python 3.5.2 (default, Aug 16 2016, 08:16:10)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import confluent_kafka
>>> c = confluent_kafka.Consumer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected configuration dict
Fatal Python error: take_gil: NULL tstate
[1]    68631 abort (core dumped)  python
```

Note, that this only happens if there are strictly no parameters. Simply changing the constructor call to `Consumer(**{})` avoids the crash.

```
Python 3.5.2 (default, Aug 16 2016, 08:16:10)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import confluent_kafka
>>> c = confluent_kafka.Consumer(**{})
>>>
```

**Comment by edenhill** [comment]
There's actually already a test for this, that passes.
It only seems to crash when using the interactive REPL, not for scripts.

The crash is related to `Py_DECREF(self);` in the error path in Consumer_new(), still trying to figure out why.

**Comment by aaronhays** [comment]
Interesting - I never actually tried this in a script. I was playing with it in the REPL to get a feeling for the minimal constructor while playing around with mocking out `Consumer` for unit tests.

**Comment by samarthg** [comment]
In my environment with python2.7, integration test "verify_consumer()" results in segmentation fault.

**Comment by edenhill** [comment]
> `Fatal Python error: take_gil: NULL tstate`

This only happens on Python 3, not on 2.7.

**Comment by edenhill** [comment]
This is fixed on master
