### ISSUE TITLE
Pause/resume runs into deadlock when rebalancing

### ISSUE THREAD

**Issue by timvlaer** [confluentinc/confluent-kafka-python#371]
Description
===========
I'm trying to integrate the pause/resume functionality in our kafka service. By moving the actual message processing to a separate worker process, I keep the main thread calling the poll method to quickly react to rebalances by interrupting the worker process.

While developing this it appears to me that it's possible to get the consumer is some sort of paused state. In that case the poll method doesn't return any new messages. See attached example.

What is the appropriate way of using pause and resume in a thread-safe way?

How to reproduce
================
I run the following dummy program twice, next to each other. I interrupt and restart one of the two processes to invoke rebalances. After a couple of times, one of the two processes stops consuming new messages from Kafka.

```
import confluent_kafka
from confluent_kafka import TopicPartition
import time

class TestService(object):
    def __init__(self):
        self.consumer = confluent_kafka.Consumer(
            **{
                'bootstrap.servers': "localhost:29092",
                'group.id': "cg-test-02",
                'api.version.request': True,
                'fetch.wait.max.ms': 1000,
                'fetch.min.bytes': 1,
                'fetch.message.max.bytes': 10*1024*1024,
                'queued.min.messages': 1,
                'queued.max.messages.kbytes': 55000,
                'enable.auto.commit': 'false',
                'receive.message.max.bytes': 900000000,
                'session.timeout.ms': 10000,
                'heartbeat.interval.ms': 1000,
                'socket.timeout.ms': 20000,
                'default.topic.config': {
                    'auto.offset.reset': 'earliest'
                },
            }
        )

        self.partitions = []
        self.paused = False
        self.shutting_down = False

    def on_assign(self, consumer, partitions):
        print partitions
        consumer.assign(partitions)
        self.partitions = partitions
        self.consumer.resume(self.partitions)

    def on_revoke(self, consumer, partitions):
        self.partitions = []
        consumer.unassign()

    def run(self):
        self.consumer.subscribe(topics=["topic-a"], on_revoke=self.on_revoke, on_assign=self.on_assign)

        while True:
            self.consumer.resume(self.partitions)

            msg = self.consumer.poll(timeout=0.2)
            if msg is not None:
                print(str(msg.partition()) + ": " + str(msg.offset()) + "")
                time.sleep(0.1)
                self.commit(msg.topic(), msg.partition(), msg.offset())
            else:
                print "None"

            self.consumer.pause(self.partitions)

    def commit(self, topic, partition, offset):
        topic_partition_to_commit = TopicPartition(topic=topic, partition=partition, offset=offset + 1)
        self.consumer.commit(offsets=[topic_partition_to_commit], async=True)


if __name__ == "__main__":
    service = TestService()
    service.run()
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`('0.11.4', 721920)` and `('0.11.4', 722175)`):
 - [x] Apache Kafka broker version: 1.0.0
 - [x] Client configuration: `{...}`
 - [x] Operating system: MacOS 10.13.3
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I believe this issue has been fixed in librdkafka v0.11.5 (release due in less than a week).
