### ISSUE TITLE
Bad code in CachedSchemaRegistryClient

### ISSUE THREAD

**Issue by rhaarm** [confluentinc/confluent-kafka-python#372]
Description
===========
`compatibility` doesn't exist, so this could cause a exception, is that the purpose?
https://github.com/confluentinc/confluent-kafka-python/blob/71217575e65d5652508d80d0532314acd190fd85/confluent_kafka/avro/cached_schema_registry_client.py#L314

This doesn't `return`, seems to be a bug, so the function would actually return None.
https://github.com/confluentinc/confluent-kafka-python/blob/71217575e65d5652508d80d0532314acd190fd85/confluent_kafka/avro/cached_schema_registry_client.py#L271

What's the purpose of this exception catch? if you are going to raise it without logging or don't care?
https://github.com/confluentinc/confluent-kafka-python/blob/71217575e65d5652508d80d0532314acd190fd85/confluent_kafka/avro/cached_schema_registry_client.py#L207

How to reproduce
================
Just looking at code...

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Oooh, spontaneous code review, much appreciated!

1. You're right, it looks like `compatibility` should be initialized to None and the if check be changed to ` if compatibilty is None:`.  Without looking to deep it might be the case that _send_request() only returns values in the 2xx range, in which case that if-statement should be removed instead. Needs further investigation.

2. Right on! The log line should probably include the code too, for troubleshooting.

3. I believe this is just an attempt of being explicit of when schema loading might fail, which is fine. Code as docs.

Would you care to provide PRs for 1 and 2? :)

**Comment by Enether** [comment]
If not, I'm open for providing PRs ;)

**Comment by rnpridgeon** [comment]
@Enether, still up for submitting PRs for this? If not let me know and I'll go ahead and get these moving.

**Comment by rnpridgeon** [comment]
That works great! Looking forward to your pull request @Enether

**Comment by Enether** [comment]
@edenhill 
> Without looking to deep it might be the case that _send_request() only returns values in the 2xx range, in which case that if-statement should be removed instead. Needs further investigation.

That appears to be false. `_send_request()` simply uses the `requests` library to make an HTTP call.
The `requests` library itself does not raise errors if the status code is not 2xx, but rather simply returns the response object.
```
import requests
print(requests.get('https://httpstat.us/200').status_code) # => 200
print(requests.get('https://httpstat.us/400').status_code) # => 400
```
