### ISSUE TITLE
SystemError: Returned a result with an error set

### ISSUE THREAD

**Issue by edenhill** [confluentinc/confluent-kafka-python#375]
Description
===========
`SystemError: <class 'tests.test_threads.IntendedException'> returned a result with an error set`

This happens frequently on Travis CI and needs to be fixed.

The issue is that some code raises an exception and returns a value, we need to find where and why.

How to reproduce
================

Travis

https://travis-ci.org/confluentinc/confluent-kafka-python/jobs/379136363#L2522

**Comment by rnpridgeon** [comment]
This seems to have subsided. Perhaps one of the recent PRs has fixed the issue. @edenhill , Do you think this is still worth investigating as it was never reproducible locally?

**Comment by edenhill** [comment]
Yep, I believe this, and the failing thread test, was fixed while doing the adminapi.
