### ISSUE TITLE
AttributeError: type object 'AvroException' has no attribute 'SchemaParseException'

### ISSUE THREAD

**Issue by TSheahan** [confluentinc/confluent-kafka-python#376]
https://github.com/confluentinc/confluent-kafka-python/blob/fb9d973a69e9b86afe50dd4260c4f20850bef815/confluent_kafka/avro/load.py#L30

I've found that the line of code above throws the following Traceback:
```
Traceback (most recent call last):
  File "./syphon.py", line 303, in <module>
    args.func(args)
  File "./syphon.py", line 188, in produce
    import ObserviumSyphon
  File "/home/tim.s/orbit-db-utils/observium-syphon/ObserviumSyphon.py", line 14, in <module>
    from OrbitDbProducer import OrbitDbProducer
  File "/home/tim.s/orbit-db-utils/observium-syphon/OrbitDbProducer.py", line 97, in <module>
    class OrbitDbProducer:
  File "/home/tim.s/orbit-db-utils/observium-syphon/OrbitDbProducer.py", line 110, in OrbitDbProducer
    } """), }
  File "/usr/lib64/python2.7/site-packages/confluent_kafka-0.11.4-py2.7-linux-x86_64.egg/confluent_kafka/avro/load.py", line 30, in loads
    except schema.AvroException.SchemaParseException as e:
AttributeError: type object 'AvroException' has no attribute 'SchemaParseException'
```

I also was able to eliminate the error by editing load.py, a diff to my edited version reads as follows:
```
21a22
> from avro.schema import SchemaParseException
30c31
<     except schema.AvroException.SchemaParseException as e:
---
>     except SchemaParseException as e:
```

Before this issue, my code is loading kafka libs via these statements.
from confluent_kafka import avro
from confluent_kafka.avro import AvroProducer
from avro.io import AvroTypeException

I'm hoping this information may be enough to identify an issue. Thanks for your attention.

**Comment by TSheahan** [comment]
the exception itself is legit - after editing load.py I was told the schema string I fed into loads() had an issue:

`  __schemata = {
    'default_key': avro.loads("""\
{
  "type" : "record",
  "name" : "string_key",
  "namespace" : "OrbitDbProducer",
  "fields" : [ {
    "name" : "key",
    "type" : "array",
    "items": "string"
  } ]
} """), }
`

  File "/usr/lib64/python2.7/site-packages/confluent_kafka-0.11.4-py2.7-linux-x86_64.egg/confluent_kafka/avro/load.py", line 32, in loads
    raise ClientError("Schema parse failed: %s" % (str(e)))
confluent_kafka.avro.error.ClientError: Schema parse failed: Type property "array" not a valid Avro schema: Could not make an Avro Schema object from array.

**Comment by rnpridgeon** [comment]
Thanks for reporting this @TSheahan,  it sounds as if you have already made some improvements here. Would you by chance be interested in submitting a Pull Request with those enhancements?
