### ISSUE TITLE
how to start with debug?

### ISSUE THREAD

**Issue by 15663671003** [confluentinc/confluent-kafka-python#381]
Description
===========
how to start with debug

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): sorry not find
 - [ ] Apache Kafka broker version: 0.10.2.0
 - [ ] Operating system: CentOS7.2

**Comment by edenhill** [comment]
Set the `debug` config property.


Consumer example:
` c = confluent_kafka.Consumer({"group.id": "mygroup", "bootstrap.servers": my_brokers, "debug": "consumer"})`

Producer example:
` p = confluent_kafka.Producer({"bootstrap.servers": my_brokers, "debug": "producer"})`

**Comment by patrickherrera** [comment]
For more recent versions, that debug option for `producer` doesn't work any more, but all the available values are listed here: https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
Took me a while to find but there is a `kwarg` to pass your own `logger` instance if you want more control over the messages.  See here: https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#kafka-client-configuration

**Comment by matkalinowski** [comment]
Adding to what @patrickherrera said. You can set your own logger, but you also need to add `debug` argument defined as:
```
A comma-separated list of debug contexts to enable. Detailed Producer debugging: broker,topic,msg. Consumer: consumer,cgrp,topic,fetch
```
With possible values as:
`generic, broker, topic, metadata, feature, queue, msg, protocol, cgrp, security, fetch, interceptor, plugin, consumer, admin, eos, mock, assignor, conf, all`

**Comment by pranavrth** [comment]
Thanks for all the help.

Closing this issue as it has been answered.
