### ISSUE TITLE
Python 3 - undefined symbol: PyString_AsStringAndSize

### ISSUE THREAD

**Issue by dondrake** [confluentinc/confluent-kafka-python#383]
Description
===========

I built librdkafka and confluent-kafka-python from source to get Kerberos support in Python 3.6.4 both from the trunk in github.

When I attempt to run my simple producer script, I get the following error:
```
python /home/drake/kafka_web/producer_confluent.py
   Traceback (most recent call last):
     File "/home/drake/kafka_web/producer_confluent.py", line 2, in <module>
       from confluent_kafka import Producer
     File "/home/drake/anaconda3/lib/python3.6/site-packages/confluent_kafka-0.11.4-py3.6-linux-x86_64.egg/confluent_kafka/__init__.py", line 2, in <module>
       from .cimpl import (Consumer,  # noqa
   ImportError: /home/drake/anaconda3/lib/python3.6/site-packages/confluent_kafka-0.11.4-py3.6-linux-x86_64.egg/confluent_kafka/cimpl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: python /home/drake/kafka_web/producer_confluent.py
   Traceback (most recent call last):
     File "/home/drake/kafka_web/producer_confluent.py", line 2, in <module>
       from confluent_kafka import Producer
     File "/home/drake/anaconda3/lib/python3.6/site-packages/confluent_kafka-0.11.4-py3.6-linux-x86_64.egg/confluent_kafka/__init__.py", line 2, in <module>
       from .cimpl import (Consumer,  # noqa
   ImportError: /home/drake/anaconda3/lib/python3.6/site-packages/confluent_kafka-0.11.4-py3.6-linux-x86_64.egg/confluent_kafka/cimpl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyString_AsStringAndSize 
```

The function `PyString_AsStringAndSize` appears to be a Python2 API call, when this is running in a Python 3 environment.

How to reproduce
================
Install Anaconda Python 3.6 
git clone confluent-kafka-python
setup.py build
setup.py install

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Ubuntu 4.15.0
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I stumbled on this myself the other day, it is fixed on the `adminapi` branch and there will be a fix on master end of this week.

If you want to fix it in your own checkout before that you can change these two lines:
https://github.com/confluentinc/confluent-kafka-python/commit/f6cda946982a47c115297701010a95e1cb2b8fd2#diff-7f37a18128203131290cbd7cf43cd1e4L1015

**Comment by dondrake** [comment]
Yes, that two line change worked!

Thanks.

**Comment by rnpridgeon** [comment]
Fixed with https://github.com/confluentinc/confluent-kafka-python/pull/382
