### ISSUE TITLE
produced message with single quote _jsonparsefailure by logstash

### ISSUE THREAD

**Issue by zjxlinux** [confluentinc/confluent-kafka-python#389]
Description
===========
When i am using syslog-ng and syslogng-kafka to push system logs to kafka Server. I notice that the messages are not json format,  messages use  single quote (which should be double-quotes ) and  can not be recognized and parsed by logstash 

reproduce
================
I use syslog-ng -F to debug and the logs be produced like this 
```bash
1 2018-05-30T13:57:14.721616+08:00 www.test.com syslogng_kafka 32288 - - Message produced: {'FACILITY': 'cron', 'PRIORITY': 'info', 'HOST': 'www.test.com', 'PROGRAM': 'CROND', 'DATE': '1527659821', 'MESSAGE': '(root) CMD (/usr/lib64/sa/sa1 1 1)'}
```

On logstash server i received the _jsonparsefailure error
![image](https://user-images.githubusercontent.com/16369233/40701951-7bba66da-6412-11e8-8478-a8b244dfc59b.png)

syslog-ng  conf 
```
source s_sys {
    file ("/proc/kmsg" program_override("kernel: "));
    unix-stream ("/dev/log" max-connections(512));
    internal();
};
destination syslog_to_kafka {
    python(
        class("syslogng_kafka.kafkadriver.KafkaDestination")
            on-error("fallback-to-string")
            options(
                hosts("xxx:9092")
                topic("system-log")
                verbose("True")
                display_stats("True")
                )
    );
};
log {
    source(s_sys);
    destination(syslog_to_kafka);
};
```

logstash conf 
```
input {
  kafka {
    bootstrap_servers => "xxxx:9092"
    topics => ["system-log"]
    codec => json
  }
}
......
``` 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka (0.11.4) syslogng-kafka (0.1.11) librdkafka-0.11.4 librdkafka-devel-0.11.4
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: centos 6
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This looks like a logstash issue.

**Comment by zjxlinux** [comment]
it seems like syslogng_kafka produce json messages with single-quote rather than double-quote , is there any option i can use to change it  double-quote ?
```
syslogng_kafka 32288 - - Message produced: {'FACILITY': 'local6', 'PRIORITY': 'notice', 'HOST': 'xxx', 'PROGRAM': 'xxx', 'DATE': '1527659837', 'MESSAGE': 'xxx'}
```

**Comment by edenhill** [comment]
You need to ask this question to the syslogng_kafka people.
