### ISSUE TITLE
error with 0.11.4 when consume data from kafka 0.9.0.0

### ISSUE THREAD

**Issue by Joukosucl** [confluentinc/confluent-kafka-python#391]
Description
===========
I would update confluent-kafka-python to 0.11.4 and found that it couldn't comsume from my kafka(0.9.0.0) with a error: SSL handshake failed, but 0.11.0 was fine.

Output
===========
    [pygroup@bogon db]$ sudo pip3 install confluent-kafka==0.11.4
    [sudo] password for pygroup: 
    Collecting confluent-kafka==0.11.4
      Using cached https://files.pythonhosted.org/packages/8f/61/3a4a32daf0ee14d7a28c153dc387e1e4aa80d27db26ef1f6263d50bb2b0c/confluent_kafka-0.11.4-cp36-cp36m-manylinux1_x86_64.whl
    Installing collected packages: confluent-kafka
      Found existing installation: confluent-kafka 0.11.0
        Uninstalling confluent-kafka-0.11.0:
          Successfully uninstalled confluent-kafka-0.11.0
    Successfully installed confluent-kafka-0.11.4
    [pygroup@bogon db]$ python3 kafkacli.py 
    %3|1527744332.185|FAIL|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744332.185|ERROR|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744332.185|ERROR|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: 1/1 brokers are down
    %3|1527744333.221|FAIL|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744333.221|ERROR|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744334.254|FAIL|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744334.254|ERROR|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744335.291|FAIL|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744335.291|ERROR|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744336.326|FAIL|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744336.326|ERROR|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744337.362|FAIL|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744337.362|ERROR|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744338.395|FAIL|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    %3|1527744338.395|ERROR|rdkafka#consumer-1| [thrd:ssl://114.118.8.199:9093/bootstrap]: ssl://114.118.8.199:9093/bootstrap: SSL handshake failed: s3_clnt.c:3641: error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small: 
    ^CTraceback (most recent call last):
      File "kafkacli.py", line 693, in <module>
        res = _consumer.poll(0)
    KeyboardInterrupt
    [pygroup@bogon db]$ sudo pip3 install confluent-kafka==0.11.0
    Collecting confluent-kafka==0.11.0
      Using cached https://files.pythonhosted.org/packages/96/36/516a2b7f592376968296d10de10a20f1ce411e5ff24a86b1a23d5a5f4042/confluent-kafka-0.11.0.tar.gz
    Installing collected packages: confluent-kafka
      Found existing installation: confluent-kafka 0.11.4
        Uninstalling confluent-kafka-0.11.4:
          Successfully uninstalled confluent-kafka-0.11.4
      Running setup.py install for confluent-kafka ... done
    Successfully installed confluent-kafka-0.11.0
    [pygroup@bogon db]$ python3 kafkacli.py 
    <cimpl.Message object at 0x7fba36a19868>
    123

How to reproduce
================
    ssl_path = os.path.join(pp, 'static/kafka_cert')
    _common_cfg = {
        'group.id': 'CONFLUENT-KAFKA-TEST',
        'bootstrap.servers': '192.168.8.199:9093',
        'security.protocol': 'ssl',
        'ssl.key.location': os.path.join(ssl_path, 'client.key.unsecure') if ssl_path else None,
        'ssl.ca.location': os.path.join(ssl_path, 'ca-cert') if ssl_path else None,
        'ssl.certificate.location': os.path.join(ssl_path, 'client.crt') if ssl_path else None,
        'ssl.key.password': '123456',
        'api.version.request': False,
        'broker.version.fallback': '0.9.0.0',
        'log.connection.close': False,
        'heartbeat.interval.ms': 60000,
        'log_level': 6,
        'message.max.bytes': 314572800,
        'statistics.interval.ms': 0, 
        'session.timeout.ms': 30000,  
        # 'topic.metadata.refresh.interval.ms': 40000,  
        'enable.auto.commit': True,
        'auto.commit.interval.ms': 1000,
        'fetch.min.bytes': 1024 * 1024,  
        'fetch.wait.max.ms': 1000, 
        'fetch.message.max.bytes': 1048576,  
        # 'offset.store.method': 'broker',
        # 'enable.auto.offset.store': True,
        'default.topic.config': {
            'auto.offset.reset': 'earliest',
        },
    }
    _consumer = Consumer(**_common_cfg)
    _consumer.subscribe(['bfac980b0ee0d3498f86887c53f2e4cf5afcec5ad8fcee5c6f94667625bd972ae7b845724c17162693db4eaa867c6e31079a05647a3c307b7901d45922811621'])
    while True:
        res = _consumer.poll(0)
        if res:
            print(res)
            break

Checklist
=========
Please provide the following information:

 - [√] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):  libversion: ('0.11.3', 721919)
 - [x] Apache Kafka broker version:
 - [√] Client configuration: `{...}`
 - [√] Operating system: Centos7
 - [√] Provide client logs (with `'debug': '..'` as necessary)
 - [] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
From what I understand this is due to insecure cipher usage on the server/broker.
The OpenSSL version (v1.0.2L) shipped with confluent-kafka-python v0.11.4 is probably more strict than your older system installed openssl that <v0.11.4 clients use.

This answer explains what needs to be done:
https://stackoverflow.com/a/30706878/1821055

**Comment by Joukosucl** [comment]
i have checked the openssl version on the server/client and both are:
> OpenSSL 1.0.1e-fips 11 Feb 2013

i get two point from your reply and don't know if they are right?
1.  0.11.4 shipped it‘s own Openssl(v1.0.2L)， so Openssl installed on the host will not be used
2.  unless i update the Openssl version to >v1.0.2L on the kafka server,  error 'SSL handshake failed' will always occur

**Comment by edenhill** [comment]
That's good, but I think you might want to pay attention to the initial issue since it shows that the Kafka broker is using an insecure SSL cipher. Newer versions of OpenSSL identify this issue, so using an older OpenSSL does not really solve the real problem, only hides it.

**Comment by edenhill** [comment]
Your client OpenSSL version is really really old and contains hundreds of security issues.
I strongly urge you to upgrade or use the one shipped with the python client, which will force you to fix the Kafka SSL issue.
Kafka does not use OpenSSL but the Java SSL / TLS framework, you'll need to refer to the Kafka and Java docs.
