### ISSUE TITLE
python setup.py build ERROR

### ISSUE THREAD

**Issue by garrisa** [confluentinc/confluent-kafka-python#392]
Description
===========
Hi, 
The execution of the command "python setup.py build", having in the same folder, setup.py and test-requirements.txt, gives the following error:
_error in confluent-kafka setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers._
I download the the file from the github as they are, and I was study the dictionary that is refered by the error but I don't see any error:
extras_require={
        'avro': ['fastavro', 'requests', avro],
        'dev': get_install_requirements("test-requirements.txt")
      }

How to reproduce
================
My enviroment is a High Sierra Mac OS and followed the following steps:
brew install librdkafka
pip install confluent-kafka
pip install confluent-kafka[avro]
Download the files setup.py and test-requirements.txt in the same folder and with a zsh or -bash terminal run:
python setup.py build

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
   librdkafka 0.11.4
   confluent-kafka-0.11.4
 - [ ] Apache Kafka broker version:
Two docker containers with:
confluentinc/cp-kafka:4.1.0
confluentinc/cp-zookeeper:4.1.0
 - [ ] Client configuration: `{...}`
Not yet running
 - [ ] Operating system:
macOS HighSierra 10.13.4
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
"python setup.py build"  
error in confluent-kafka setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers._

Thanks

**Comment by edenhill** [comment]
That seems strange, what Python version are you on?

And why are you downloading setup.py and requirements.txt after having installed the packages already?
setup.py and requirements.txt should only be used from the confluent-kafka-python source tree, and with pip you dont need to do that.

Note: with confluent-kafka-python >= 0.11.4 you no longer need to install librdkafka (through brew), it is included in the binary python wheel.

**Comment by garrisa** [comment]
Hi, 

Thanks for your quick answer, I write inline your email:

Kind regards, 

    Iván 

Ivan Garrido Sanz

Email: ivan.garrido@gmail.com
Skype: ohivanivan
Mobile: +34640397215
Linkedin: https://www.linkedin.com/in/iv%C3%A1n-garrido-sanz-05aa3b33/ 

> On 31 May 2018, at 09:03, Magnus Edenhill <notifications@github.com> wrote:
> 
> That seems strange, what Python version are you on?
> 
> [Iván]: I run the command with 3.6.3 version of python


$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
Carloss-MacBook-Pro:confluent-kafka-python carlosivangarridosanz$ python setup.py build
error in confluent-kafka setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.


> And why are you downloading setup.py and requirements.txt after having installed the packages already?
> setup.py and requirements.txt should only be used from the confluent-kafka-python source tree, and with pip you dont need to do that.
> 
> 
> Note: with confluent-kafka-python >= 0.11.4 you no longer need to install librdkafka (through brew), it is included in the binary python wheel.
> 
> 
Ok, I thought I have to follow the instruction of the webpages:

https://www.confluent.io/blog/introduction-to-apache-kafka-for-python-programmers/ <https://www.confluent.io/blog/introduction-to-apache-kafka-for-python-programmers/>

Thats why I did brew…

And https://github.com/confluentinc/confluent-kafka-python <https://github.com/confluentinc/confluent-kafka-python>.  

Thats why I install 

$ pip install confluent-kafka
$ pip install confluent-kafka[avro]
And follow with the Build.


So, It seems that I made a mistake , and I did the build when it is not suppose. If I understood well, can I run the producer and consumer directly?

If its so, I will close the issue and please accept my apologies.


Thanks and kid regards, 

    Iván

**Comment by garrisa** [comment]
Thank you so much, I will close the issue.

Have a nice day and kind regards, 

   Iván


Ivan Garrido Sanz

Email: ivan.garrido@gmail.com
Skype: ohivanivan
Mobile: +34640397215
Linkedin: https://www.linkedin.com/in/iv%C3%A1n-garrido-sanz-05aa3b33/

**Comment by garrisa** [comment]
Thanks you for the great support work.
