### ISSUE TITLE
ImportError: No module named 'confluent_kafka.cimpl'

### ISSUE THREAD

**Issue by dybal** [confluentinc/confluent-kafka-python#405]
Description
===========
I'm writing an application in python3 that uses the confluent-kafka-python package - all in a docker container. When I try to run the container I get:

> docker run --name xxx --network lmap-report-validator_default --env-file env-vars "xxx:current" 
> Traceback (most recent call last):
>   File "/scripts/main.py", line 2, in <module>
>     import confluent_kafka
>   File "/src/confluent-kafka-python/confluent_kafka/__init__.py", line 2, in <module>
>     from .cimpl import (Consumer,  # noqa
> ImportError: No module named 'confluent_kafka.cimpl'

How to reproduce
================
This is just to reproduce the problem... 

- install docker
- create a Dockerfile:

> FROM python:3.6 
>WORKDIR /src
>RUN apt-get update && apt-get install make git 
>
>RUN git clone https://github.com/edenhill/librdkafka.git
>WORKDIR librdkafka
>RUN ./configure && make && make install
>
>WORKDIR /src
>RUN git clone https://github.com/confluentinc/confluent-kafka-python.git
>WORKDIR /src/confluent-kafka-python
>RUN python3 setup.py build 
>
>WORKDIR /scripts
>RUN echo "#!/usr/bin/python3\nimport confluent_kafka\nprint('hello world!')" > main.py
>RUN chmod +x main.py
>WORKDIR /
>ENV PYTHONPATH /usr/local/lib/python3.6/site-packages:/src/confluent-kafka-python
>ENV LD_LIBRARY_PATH /usr/local/lib
>CMD [ "/scripts/main.py" ]

- create image:

`docker build -t "xxx:current" .`

- create and run a container with the image:

`docker run --name xxx "xxx:current"`

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): latest in github's master branch
 - [ ] Apache Kafka broker version: problem happens before looking for a broker
 - [ ] Client configuration: `{...}` problem happens before creating a Consumer or Producer
 - [ ] Operating system: Linux Mint 18.3, kernel 4.10.0-38-generic
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Make sure to run `python setup.py install` in addition to build. Really using `build` is unnecessary as `install` should both build and install the package.

**Comment by dybal** [comment]
Tried running `python3 setup.py install` ... didn't change the result, still got:

> Traceback (most recent call last):
>   File "/scripts/main.py", line 2, in <module>
>     import confluent_kafka
>   File "/src/confluent-kafka-python/confluent_kafka/__init__.py", line 2, in <module>
>     from .cimpl import (Consumer,  # noqa
> ImportError: No module named 'confluent_kafka.cimpl'

**Comment by edenhill** [comment]
Suggest you install confluent-kafka from PyPi instead of building it from source, thus:
`pip install confluent_kafka`

**Comment by dybal** [comment]
That worked!
Thanks!

**Comment by joe-mojo** [comment]
I have the same error message in AWS Lambda runtimes python3.8 and python3.9 with confluent-kafka 1.8.2.
This does not occurs with confluent-kafka 1.7.0. 
I do not build confluent-kafka, I install it with `pip install`
Regression ?

**Comment by CusHoria** [comment]
@joe-mojo same output on my side, with python 3.10.2, it works for me only when using python 3.7

**Comment by wdos3** [comment]
> @joe-mojo same output on my side, with python 3.10.2, it works for me only when using python 3.7

This is belated, but there's no wheel for python 3.10.2, meaning that kafka is not yet usable/implemented for Python 3.10+ (take it from me, I had to reinstall every libraries I have).

**Comment by Lin-K** [comment]
> Suggest you install confluent-kafka from PyPi instead of building it from source, thus: `pip install confluent_kafka`

If confluent-kafka provided support for manylinux_2_31_aarch64 I/we wouldn't be building from source.
