### ISSUE TITLE
Add support for multiple SR urls in CachedSchemaRegistryClient

### ISSUE THREAD

**Issue by rnpridgeon** [confluentinc/confluent-kafka-python#409]
Description
===========

Currently the python client fails to handle multiple schema registry urls. In order to more closely align the python client with its Java counterpart it should be updated to handle multiple URLs. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by higee** [comment]
+1

**Comment by vemuri-nath** [comment]
@rnpridgeon @higee i am facing the same issue, is there a solution or alternative for multiple schema urls ?

**Comment by ethanttbui** [comment]
wow, this has been. since 2018...

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1866
