### ISSUE TITLE
Pip Version Out of Date

### ISSUE THREAD

**Issue by tylerdoll** [confluentinc/confluent-kafka-python#414]
Description
===========

Can someone update the pip package with 0.11.5?  I am working on a project and could really use the AdminClient class to create topics using the client.

https://pypi.org/project/confluent-kafka/

**Comment by edenhill** [comment]
v0.11.5 will be released within two weeks, we'll push a release candidate to test.pypi.org this week that you are more than welcome to try out (and report any issues with).
