### ISSUE TITLE
consumer_lag statistic does not reset after rebalance operation

### ISSUE THREAD

**Issue by coldeasy** [confluentinc/confluent-kafka-python#416]
Description
===========
`consumer_lag` statistic does not reset after rebalance operation. It maintains the previous value when the partition was still assigned.

How to reproduce
================

Run a producer and consumer (part of a cgrp). Allow message to be processed by the consumer and add another consumer. Observe the statistics outputted from both consumers. You'll notice that the `consumer_lag` maintains the last seen value rather than resetting back to zero when partitions are revoked.

Using `0.11.4` of `confluent-kafka-python`.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python: `('0.11.4', 721920)` and librdkafka version `('0.11.4', 722175)`:
 - [x] Apache Kafka broker version: `0.10.2.1`
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Centos6
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You're right, it continues to calculate lag despite the partition being unassigned.
As a workaround you could check that the partition `fetch_state` is `"active"`
