### ISSUE TITLE
Performance comparison of python kafka clients.

### ISSUE THREAD

**Issue by aishwaryadhage** [confluentinc/confluent-kafka-python#418]
To use a kafka client for my project I was trying to compare the performance by using time required by producer and consumer to produce and consume respectively by each Kafka client i.e. Pykafka, Confluent_kafka and kafka-python. I am using one broker and one partition. After comparing the time required for each client. The time i am calculating is my just using time() before and after produce() and consume() methods for 1000 messages.

Following are my results for producer to produce 1000 messages- 
Pykafka- lrdkafka – 
time taken - 1.14 seconds
Pykafka –
time taken - 10.20 seconds
kafka-python – 
time taken - 10.19 seconds
confluent-kafka
time taken - 22.07 seconds

This looks strange to me because when I was reading online, confluent-kafka is faster than other three.
Kafka Version - kafka_2.11-0.9.0.0
Is there something that I am missing here?

**Comment by rnpridgeon** [comment]
You haven't really given us much to go by here. At the very least can you provide the code for the confluent-kafka benchmark. We can start there and branch out as necessary.

**Comment by aishwaryadhage** [comment]
I was following a tutorial to write my consumer and producer. This is the code with modification to print time-
**Producer -**
from confluent_kafka import Producer

def acked(err, msg):
    if err is not None:
        print("Failed to deliver message: {0}: {1}"
              .format(msg.value(), err.str()))
    else:
        print("Message produced: {0}".format(msg.value()))

p = Producer({'bootstrap.servers': 'localhost:9092'})
start_time = time.time()
try:
	for val in xrange(1, 10000):
		p.produce('newtwo5', 'myvalue #{0}'.format(val))#, callback=acked)
		p.poll(0.5)
except KeyboardInterrupt:
    pass

timing=time.time()-start_time
print("Processed 10000 messsages in {0:.2f} seconds".format( timing))

p.flush(30)

**Consumer**
from confluent_kafka import Consumer, KafkaError

settings = {
    'bootstrap.servers': 'localhost:9092',
    'group.id': 'mygroup',
    'client.id': 'client-1',
    'enable.auto.commit': True,
    'session.timeout.ms': 6000,
    'default.topic.config': {'auto.offset.reset': 'smallest'}
}

c = Consumer(settings)

c.subscribe(['newtwo5'])
start_time = time.time()
try:
	while True:
		msg = c.poll(0.1)
		if msg is None:continue
		elif not msg.error():
			pass
			#print('Received message: {0}'.format(msg.value()))
		elif msg.error().code() == KafkaError._PARTITION_EOF:
			timing=time.time()-start_time
			print('End of partition reached {0}/{1} time = {2:.2f} seconds'.format(msg.topic(), msg.partition(),timing))
		else:
			print('Error occured: {0}'.format(msg.error().str()))

except KeyboardInterrupt:
    pass

finally:
    c.close()

**Comment by aishwaryadhage** [comment]
You are saying benchmarking using the start and stop time is not the best way right? Can you suggest any other way for comparison?

**Comment by edenhill** [comment]
A couple of recommendations for benchmarking:
 * Start measuring after the first successful delivery (or more) to avoid including startup costs in the measurement
 * Measure for at least 30s or more, anything shorter than that will be subject to ramp up costs.
 * Repeat the tests multiple times and use the highest/best achieved values as result.
 * Use histograms rather than averages whenever possible.
 * Make sure your run the clients on VM instances with at least 4 vcores/CPUs.
 * Increase throughput by promoting larger batches:
   * set `linger.ms=10`

Additionally, call poll(0) from your producer loop to quickly serve delivery reports.
Call flush(30) when terminating.

**Comment by aishwaryadhage** [comment]
Yes. I will try it out. Thank you so much!

**Comment by zxcv551133** [comment]
@aishwaryadhage Did you figure out cause?

**Comment by poonkothaip** [comment]
Hi, It looks like performance of kafka-python library based consumer is better than confluent-kafka library.  But I see in many forums, its reverse.  So has anyone had similar observations or which library is better when it comes to performance

Thanks
