### ISSUE TITLE
Would this package work with stock Apache Kafka 0.10.x ?

### ISSUE THREAD

**Issue by ericywho** [confluentinc/confluent-kafka-python#42]
Would this package work with stock Apache Kafka 0.10.x or I need to use this with Confluent Kafka ?

**Comment by edenhill** [comment]
It works with both.
The Python client defaults to broker verison 0.9.0.1, for 0.10.x brokers you should pass `"api.version.request": True` in your config dict when creating the Producer or Consumer.

More info here:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
