### ISSUE TITLE
Multiple avro schema for same Topic

### ISSUE THREAD

**Issue by aishwaryadhage** [confluentinc/confluent-kafka-python#421]
Description
===========

Hi,
This is my Producer code - 
from confluent_kafka import avro
from confluent_kafka.avro import AvroProducer

value_schema = avro.load('user.avsc')
key_schema = avro.load('key.avsc')

key = {"name": "Ash"}
value = {"name":"Ash", "flower":"rose", "color":"red"}
avroProducer = AvroProducer(
    {'bootstrap.servers': 'localhost:9092', 'schema.registry.url': 'http://127.0.0.1:8082'
    ,'broker.version.fallback': '0.9.0.0', 'api.version.request': True},
     default_key_schema=key_schema, default_value_schema=value_schema)

avroProducer.produce(topic='topic-1', value=value, key=key, key_schema=key_schema, value_schema=value_schema)    

avroProducer.flush(10)

I was trying to use multiple schemas. 
{
  "namespace":"examplev1.avro",
  "type":"record",
  "name":"Userv1",
  "fields": [
    {"name":"name", "type":"string"},
    {"name":"flower", "type":"string"},
    {"name":"color", "type":"string"},
}
}

This was my previous schema and I tried to add new fields to it. But it gives following error -
File "avro_producer.py", line 54, in <module>
    avroProducer.produce(topic='topic-1', value=value, key=key, key_schema=key_schema, value_schema=value_schema)    
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/confluent_kafka/avro/__init__.py", line 64, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 98, in encode_record_with_schema
    schema_id = self.registry_client.register(subject, schema)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 133, in register
    raise ClientError("Incompatible Avro schema:" + str(code))
confluent_kafka.avro.error.ClientError: Incompatible Avro schema:409

If I am not wrong incompatible avro schema is because I added new fields in the same schema right?
I really wanted to understand how python client adds avro schema in schema registry in python. 
I know that above code will register a single avro schema to a single topic.But if I try to add a new schema or add few fields in same schema how will the topic recognize the schema it is supposed to use?
 Do I need a separate schema-registry-client for multiple schema registry or do I need a REST api call to register my schema rather than using a .avsc file? 
It would also be helpful if you can direct me to any documentation to understand how its done in python client.

Thanks.

**Comment by rnpridgeon** [comment]
Each time you change your Avro schema the schema registry client registers a new version for that subject. Depending on the compatibility policy you have configured, backwards by default, the SR will register or reject this new version. In your case the changes you made conflicted with the configured compatibility policy so a 409 http status code was returned. 

If you have not already done so I recommend reviewing the SR docs, specifically those with regard to schema evolution. 


https://docs.confluent.io/current/avro.html#serialization-and-evolution
