### ISSUE TITLE
config on_commit is not working when commit(asynchronous=False)

### ISSUE THREAD

**Issue by hrchu** [confluentinc/confluent-kafka-python#423]
Description
===========

How to reproduce
================
```

def commit_cb(err, ps):
    print('on_commit: err %s, partitions %s' % (err, ps))


conf = {'bootstrap.servers': 'localhost:19092',
        'enable.auto.commit': False,  
        'enable.auto.offset.store': False,  
        'offset.store.method': 'broker',
        'default.topic.config': {'auto.offset.reset': 'smallest'},
        'on_commit': commit_cb,
        'statistics.interval.ms': 60000,
        'logger':logger
        }

c = Consumer(conf)

c.subscribe(['foo'])

while True:
    msg = c.poll(1.0)

    if msg is None:
        continue
    if msg.error():
        if msg.error().code() == KafkaError._PARTITION_EOF:
            continue
        else:
            print(msg.error())
            break

    print('Received message: {}'.format(msg.value().decode('utf-8')))
    c.commit(msg,asynchronous=False)

c.close()
```
run the above code snipplet, and print nothing. when asynchronous is True, on_commit blah will be shown.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): => 0.11.4
 - [ ] Apache Kafka broker version: => the least
 - [ ] Client configuration: `{...}` => as code
 - [ ] Operating system =>  ubuntu 16.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary) => print nothing. how?
 - [ ] Provide broker log excerpts => N/A
 - [ ] Critical issue => confusing users

**Comment by edenhill** [comment]
This is intentional, the synchronous commit raises an exception on error so there is no need for a commit callback.

**Comment by edenhill** [comment]
The commit_cb is used to get results of asynchronous or auto commits which both happen in the background.

**Comment by hrchu** [comment]
Roger that. I note it in #424.

BTW, 

> the synchronous commit raises an exception on error

so users does not need to check return value of ``c.commit(msg,asynchronous=False)``, right?

**Comment by edenhill** [comment]
Thank you!

Correct

**Comment by hrchu** [comment]
To classify: 
* c.commit(message=msg, asynchronous=False) will raises an exception on error
* c.commit(offsets=offsets, asynchronous=False) will not raise any exception on error. Errors will present in returned list(TopicPartition) instead.

@edenhill is that correct?

**Comment by edenhill** [comment]
If all partitions fail an exception will be raised, but not if only a subset of partitions fail.

**Comment by hrchu** [comment]
Roger that! thanks!
