### ISSUE TITLE
AvroConsumer and AvroProducer are both hardcoded to use Avro schema for both key & value

### ISSUE THREAD

**Issue by cbsmith** [confluentinc/confluent-kafka-python#428]
Description
===========
Unlike the Java equivalents, AvroConsumer & AvroProducer assume keys and values must be encoded with Avro. While that might be a reasonable default, there are a lot of good reasons to avoid an Avro encoding for keys, while still using Avro to encode values. With avro messages, a change in the schema would cause changes to partitioning for otherwise equivalent keys, disrupting Kafka's ordering guarantee.

How to reproduce
================
Consume from a topic created with non-null, non-avro keys. You'll get a serialization error, even if you don't care about the key's content.

**Comment by erhwenkuo** [comment]
Just like Chris mentioned, current AvroConsumer implementation assumes both keys and values must be decoded with Avro.
Is it better to have some flags to control this behavior? To temporary avoid the decoding error, I modify **AvroConsumer** to add two more indicators which allow me to bypass avro decoidng for message key. Ugly solution, but it works.  Since Python3 start to support abc (Abstract Base Class), I think the better solution should abstract out the Serializer & Deserializer class and use configuration to config serde.

```
class AvroConsumer(Consumer):   
    def __init__(self, config, is_key_avro=False,
                 is_value_avro=True, schema_registry=None):

        schema_registry_url = config.pop("schema.registry.url", None)
        schema_registry_ca_location = config.pop("schema.registry.ssl.ca.location", None)
        schema_registry_certificate_location = config.pop("schema.registry.ssl.certificate.location", None)
        schema_registry_key_location = config.pop("schema.registry.ssl.key.location", None)
        # add two indicator to differentiate if key or value need to decode via avro
        self.is_key_avro = is_key_avro
        self.is_value_avro = is_value_avro

        if schema_registry is None:
            if schema_registry_url is None:
                raise ValueError("Missing parameter: schema.registry.url")

            schema_registry = CachedSchemaRegistryClient(url=schema_registry_url,
                                                         ca_location=schema_registry_ca_location,
                                                         cert_location=schema_registry_certificate_location,
                                                         key_location=schema_registry_key_location)
        elif schema_registry_url is not None:
            raise ValueError("Cannot pass schema_registry along with schema.registry.url config")

        super(AvroConsumer, self).__init__(config)
        self._serializer = MessageSerializer(schema_registry)

    def poll(self, timeout=None):
        if timeout is None:
            timeout = -1
        message = super(AvroConsumer, self).poll(timeout)
        if message is None:
            return None
        if not message.value() and not message.key():
            return message
        if not message.error():
            if message.value() is not None and self.is_value_avro:
                decoded_value = self._serializer.decode_message(message.value())
                message.set_value(decoded_value)
            if message.key() is not None and self.is_key_avro:
                decoded_key = self._serializer.decode_message(message.key())
                message.set_key(decoded_key)
        return message
```

**Comment by cricket007** [comment]
**Workaround**:

Regular producer can be setup with `MessageSerializer(schema_registry)`, which is the AvroSerDe equivalent.

Then you can use standard `Producer` and decide which or key and/or value you want to serialize. 

Something like the following

```python
import os

from confluent_kafka import avro
from confluent_kafka import Producer
from confluent_kafka.avro import AvroProducer, CachedSchemaRegistryClient
from confluent_kafka.avro.serializer.message_serializer import MessageSerializer

schema_registry = CachedSchemaRegistryClient(os.environ.get('SCHEMA_REGISTRY', 'http://localhost:8081'))
avro_serde = MessageSerializer(schema_registry)
serialize_avro = avro_serde.encode_record_with_schema

def serialize_str(s):
    return s.encode('utf-8')

p = Producer({'bootstrap.servers': bootstrap_servers})

val_payload = serialize_avro(topic, value_schema, value, is_key=False)
p.produce(topic, val_payload, callback=delivery_report)
```

**Comment by erhwenkuo** [comment]
I do believe the "generic key/value SERDE support" that mentioned in [https://github.com/confluentinc/confluent-kafka-python/issues/211](url) is the good direction。Also, it should behave like kafka client (Java version ). 
Thanks the work around tip from **cricket007** !!

**Comment by OneCricketeer** [comment]
This should probably be closed now with the implementation of [`SerializingProducer`](https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/serializing_producer.py#L26)

**Comment by pranavrth** [comment]
As stated, this issue is resolved with introduction of [deserializing_consumer](https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/deserializing_consumer.py) and [serializing_producer](https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/serializing_producer.py). Closing this issue.

**Comment by cbsmith** [comment]
Sorry, I should have closed it earlier. My bad.
