### ISSUE TITLE
Consumers with partition assignment switches partitions upon consumption of message

### ISSUE THREAD

**Issue by czchlong** [confluentinc/confluent-kafka-python#432]
Description
===========
The following is used in a multiprocessing setting with

`multiprocessing.set_start_method('spawn')`

Create a kafka topic with 2 partitions, 0 and 1

Create 2 consumers in child processes with the same 'group.id' with each child process assigned to either partition 0 or 1, but not both. There will always be 2 consumers, each consuming from their assigned partition.

Partition assignment is correct on creation of consumers, however when the consumers start consuming messages, the consumer assignment changes. consumer1 originally assigned to partition 0 will consume from partition 1 and consumer2 originally assigned to partition 1 will consume from partition 0.

This behavior is erratic, sometimes the assignments do not change.

How to reproduce
================
Create a topic, 'topic' with 2 partitions, partitions 0 and 1

```
        self._consumer1 = Consumer({
            'bootstrap.servers': 'some_servers',
            'group.id': 'some_group',
            'default.topic.config': {
                'auto.offset.reset': 'latest'
            }
        })
        self._tp = TopicPartition('topic', 0)
        self._consumer1.assign([self._tp]) # Assigned to topic with partition 0
        self._consumer1.subscribe(['topic'])

```
However, when message consumption starts, consumer1's partition assignment changes:

```
            while True:
                payload = self._consumer1.consume(num_messages)
                last = payload[-1]
                print("Consumer assignment: ", self._consumer1.assignment()) # consumer1's assignment changes to partition 1

```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent kafka version 0.11.5
 - [x] Apache Kafka broker version: kafka_2.11-1.0.1
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You should use either assign() or subscribe(), not both.

subscribe() makes your consumer join the group and request subscription of the given topics (not partitions, they are ignored), after rebalancing your client will be assigned a subset of partitions for the subscribed topics (at this point the client automatically calls assign() on the assigned partition list).

assign() starts consuming the given partitions immediately.
