### ISSUE TITLE
Wrong 'str' type is used for a schema registry, the 'AvroSchema' should be instead.

### ISSUE THREAD

**Issue by dzhagr** [confluentinc/confluent-kafka-python#433]
https://github.com/confluentinc/confluent-kafka-python/blob/ada0995f8928abd9e8d7dc0314fb510b5e15e488/confluent_kafka/avro/__init__.py#L80

Getting the following error:

>   File ".../python3.6/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 140, in register
>     body = {'schema': json.dumps(avro_schema.to_json())}
> AttributeError: 'str' object has no attribute 'to_json'

Just to be clear: it's a doc issue.

**Comment by test1370** [comment]
Hi, Can anyone help me with the above error please?

**Comment by pranavrth** [comment]
AvroProducer and Avro Consumer are deprecated. Please use AvroSerializer and AvroDeserializer with Producer and Consumer as shown in the examples.

Closing this issue.
