### ISSUE TITLE
Q: when is on_assign and on_revoke triggered?

### ISSUE THREAD

**Issue by elizabethhong** [confluentinc/confluent-kafka-python#435]
When are rebalance and callback handled?  

Local test seems to suggest it is triggered when `consume` is called. Is it the only place? 

Wondering how client's threads work together to execute rebalance and trigger callback. 

Checklist
=========
Please provide the following information:

 - [0.11.0] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
When using `subscribe` you can expect on_assign and on_revoke to be called with each group rebalance or new subscription. 

Group rebalances are triggered each time a consumer joins or leaves the group voluntarily or involuntarily. Involuntary group departures are triggered whenever your client fails to heartbeat back to the coordinator within the configured `session.timeout.ms`

**Comment by elizabethhong** [comment]
Thanks for quick response. 

I am asking about librdkafka implementation details, instead of kafka behavior. 

Which thread is handling on_assign? Is it thread connecting to broker or the main execution thread? If it is main thread, when is it called e.g. if it is executing consume() and then rebalance is happening, does it switch to do rebalance or finish current event first before jumping to do rebalance? e.g. Is it guaranteed that during rebalance, the message will not be consumed by more than one consumer?  

Implementation details are appreciated.

**Comment by edenhill** [comment]
The rebalance_cb will be called from your application thread from the rd_kafka_poll()/rd_kafka_consumer_poll()/consume() calls.

At most one consumer will consume messages for a given partition, during rebalancing the assigned partitions are paused.

**Comment by elizabethhong** [comment]
1. Thanks for confirming that the rebalance **callbacks** is handled during rd_kafka_poll()/rd_kafka_consumer_poll()/consume() calls. To clarify, what about **actual** rebalance, i.e. handling rebalance protocol with coordinator? Is it handled at same time on application thread or background polling thread?

2. During actual rebalance, will the local fetchq always be cleared for all partitions? If not, it sounds the next consume() call might get messages for old/invalid partition that was cached in fetchq before rebalance. 

3. Let's say partition 1 is assigned to consumer A. After rebalance, partition1 is still assigned to consumer A. Right after rebalance, will consumer A fetch from last committed offset or last polled offset?

4. If rebalance happens while a message is being processed, will it cause problem for committing to an old/invalid partition?

**Comment by rnpridgeon** [comment]
Tagged to aid in issue searches
