### ISSUE TITLE
Topic 'stickiness' when subscribing to multiple topics

### ISSUE THREAD

**Issue by jason-brian-anderson** [confluentinc/confluent-kafka-python#441]
Description
===========
I have some production code that creates a consumer that subscribes to multiple topics.  I have noticed that this consumer seems to prefer to consume just one of the multiple topics as i continue to poll that consumer (my polling interval is set to 0.5)

Is this a feature or a bug?  To me, it's rather a bug, I'd prefer to round-robin the topics vs completely consume one, vs moving on the others, if that is even how it works.
thanks!!

How to reproduce
================
consume multiple topics and log the topics of the messages returned by the consumer.poll(x)

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Messages are fetched in batches per partition and enqueued on the internal fetch queue (for the application to read) in the order they are received:
https://github.com/edenhill/librdkafka/wiki/FAQ#how-are-partitions-fetched

**Comment by jason-brian-anderson** [comment]
thank you @edenhill  !
