### ISSUE TITLE
confluent-kafka installation failed with missing dependencies

### ISSUE THREAD

**Issue by sharavanan2010** [confluentinc/confluent-kafka-python#445]
Description
===========
'confluent-kafka-python' package installation failed with dependencies missing error.

How to reproduce
================
Run below command to install package in windows machine,
pip install confluent-kafka

Error:

C:\Windows\system32>pip install confluent-kafka
Collecting confluent-kafka
  Using cached https://files.pythonhosted.org/packages/bf/41/25a4e23a98df212e910aecd445d3b1ea37928ef857749a85365da7108b83/confluent-kafka-0.11.5.tar.gz
Building wheels for collected packages: confluent-kafka
  Running setup.py bdist_wheel for confluent-kafka ... error
  Complete output from command C:\Python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SHARAV~1\\AppData\\Local\\Temp\\pip-install-xvkj7zyl\\confluent-kafka\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\SHARAV~1\AppData\Local\Temp\pip-wheel-pf51qy8a --python-tag cp34:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.4
  creating build\lib.win-amd64-3.4\confluent_kafka
  copying confluent_kafka\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka
  creating build\lib.win-amd64-3.4\confluent_kafka\admin
  copying confluent_kafka\admin\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka\admin
  creating build\lib.win-amd64-3.4\confluent_kafka\avro
  copying confluent_kafka\avro\cached_schema_registry_client.py -> build\lib.win-amd64-3.4\confluent_kafka\avro
  copying confluent_kafka\avro\error.py -> build\lib.win-amd64-3.4\confluent_kafka\avro
  copying confluent_kafka\avro\load.py -> build\lib.win-amd64-3.4\confluent_kafka\avro
  copying confluent_kafka\avro\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka\avro
  creating build\lib.win-amd64-3.4\confluent_kafka\kafkatest
  copying confluent_kafka\kafkatest\verifiable_client.py -> build\lib.win-amd64-3.4\confluent_kafka\kafkatest
  copying confluent_kafka\kafkatest\verifiable_consumer.py -> build\lib.win-amd64-3.4\confluent_kafka\kafkatest
  copying confluent_kafka\kafkatest\verifiable_producer.py -> build\lib.win-amd64-3.4\confluent_kafka\kafkatest
  copying confluent_kafka\kafkatest\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka\kafkatest
  creating build\lib.win-amd64-3.4\confluent_kafka\avro\serializer
  copying confluent_kafka\avro\serializer\message_serializer.py -> build\lib.win-amd64-3.4\confluent_kafka\avro\serializer
  copying confluent_kafka\avro\serializer\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka\avro\serializer
  running build_ext
  building 'confluent_kafka.cimpl' extension
  creating build\temp.win-amd64-3.4
  creating build\temp.win-amd64-3.4\Release
  creating build\temp.win-amd64-3.4\Release\confluent_kafka
  creating build\temp.win-amd64-3.4\Release\confluent_kafka\src
  C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\x86_amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python34\include -IC:\Python34\include /Tcconfluent_kafka/src/confluent_kafka.c /Fobuild\temp.win-amd64-3.4\Release\confluent_kafka/src/confluent_kafka.obj
  confluent_kafka.c
  c:\users\sharavanan_pc\appdata\local\temp\pip-install-xvkj7zyl\confluent-kafka\confluent_kafka\src\confluent_kafka.h(21) : fatal error C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for confluent-kafka
  Running setup.py clean for confluent-kafka
Failed to build confluent-kafka
Installing collected packages: confluent-kafka
  Running setup.py install for confluent-kafka ... error
    Complete output from command C:\Python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SHARAV~1\\AppData\\Local\\Temp\\pip-install-xvkj7zyl\\confluent-kafka\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SHARAV~1\AppData\Local\Temp\pip-record-fakuxsvd\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.4
    creating build\lib.win-amd64-3.4\confluent_kafka
    copying confluent_kafka\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka
    creating build\lib.win-amd64-3.4\confluent_kafka\admin
    copying confluent_kafka\admin\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka\admin
    creating build\lib.win-amd64-3.4\confluent_kafka\avro
    copying confluent_kafka\avro\cached_schema_registry_client.py -> build\lib.win-amd64-3.4\confluent_kafka\avro
    copying confluent_kafka\avro\error.py -> build\lib.win-amd64-3.4\confluent_kafka\avro
    copying confluent_kafka\avro\load.py -> build\lib.win-amd64-3.4\confluent_kafka\avro
    copying confluent_kafka\avro\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka\avro
    creating build\lib.win-amd64-3.4\confluent_kafka\kafkatest
    copying confluent_kafka\kafkatest\verifiable_client.py -> build\lib.win-amd64-3.4\confluent_kafka\kafkatest
    copying confluent_kafka\kafkatest\verifiable_consumer.py -> build\lib.win-amd64-3.4\confluent_kafka\kafkatest
    copying confluent_kafka\kafkatest\verifiable_producer.py -> build\lib.win-amd64-3.4\confluent_kafka\kafkatest
    copying confluent_kafka\kafkatest\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka\kafkatest
    creating build\lib.win-amd64-3.4\confluent_kafka\avro\serializer
    copying confluent_kafka\avro\serializer\message_serializer.py -> build\lib.win-amd64-3.4\confluent_kafka\avro\serializer
    copying confluent_kafka\avro\serializer\__init__.py -> build\lib.win-amd64-3.4\confluent_kafka\avro\serializer
    running build_ext
    building 'confluent_kafka.cimpl' extension
    creating build\temp.win-amd64-3.4
    creating build\temp.win-amd64-3.4\Release
    creating build\temp.win-amd64-3.4\Release\confluent_kafka
    creating build\temp.win-amd64-3.4\Release\confluent_kafka\src
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\x86_amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python34\include -IC:\Python34\include /Tcconfluent_kafka/src/confluent_kafka.c /Fobuild\temp.win-amd64-3.4\Release\confluent_kafka/src/confluent_kafka.obj
    confluent_kafka.c
    c:\users\sharavanan_pc\appdata\local\temp\pip-install-xvkj7zyl\confluent-kafka\confluent_kafka\src\confluent_kafka.h(21) : fatal error C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SHARAV~1\\AppData\\Local\\Temp\\pip-install-xvkj7zyl\\confluent-kafka\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SHARAV~1\AppData\Local\Temp\pip-record-fakuxsvd\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\SHARAV~1\AppData\Local\Temp\pip-install-xvkj7zyl\confluent-kafka\
C:\Windows\system32>

Checklist
=========

Is confluent-kafka package supported for windows?

**Comment by sharavanan2010** [comment]
Any thoughts?

**Comment by rnpridgeon** [comment]
We don't currently support confluent-kafka-python on Windows, so you would need to sort this out yourself and with the help of the community. That said it is on the roadmap though. 

There is some information in this issue on what needs to be done, but it is not straight forward:
confluentinc/confluent-kafka-python#132

**Comment by sharavanan2010** [comment]
Thanks for your information
