### ISSUE TITLE
incorrect broker.version.fallback?

### ISSUE THREAD

**Issue by mhmrahmati** [confluentinc/confluent-kafka-python#454]
Description
===========
I want to see result of describe_configs() method. my code is:

```
A1 = AdminClient({'bootstrap.servers': ip,
                  'api.version.request':True})
A2 = [ConfigResource('ANY', groupId)]
A3 = A1.describe_configs(A2)
for B1, B2 in A3.items():
	B3 = B2.result()
	print(B3)
        B4 = B3.values()
        print(B4)
```

but i face with this error:

```
%3|1537702472.744|PROTOERR|rdkafka#producer-2| [thrd:main]: mohammad:9092/0: Protocol parse
 failure at 81/81 (rd_kafka_DescribeConfigsResponse_parse:2644) 
(incorrect broker.version.fallback?)

%3|1537702472.744|PROTOERR|rdkafka#producer-2| [thrd:main]: mohammad:9092/0: Broker 
returned ConfigResource 0,mygroup3 that was not included in the original request

Segmentation fault (core dumped)
```

kafka-version = 2.0.0
confluent-kafka-python-version = 0.11.5
librdkafka = 0.11.5
oprating-system = ubuntu

**Comment by mhmrahmati** [comment]
/home/mohammad/Pictures/Screenshot from 2018-09-23 08-06-47.png


/home/mohammad/Pictures/Screenshot from 2018-09-23 08-08-39.png

**Comment by mhmrahmati** [comment]
![screenshot from 2018-09-23 08-06-47](https://user-images.githubusercontent.com/42435005/45927867-2d655900-bf47-11e8-88e6-10e097082faf.png)


![screenshot from 2018-09-23 08-08-39](https://user-images.githubusercontent.com/42435005/45927870-36eec100-bf47-11e8-9214-33b43d771035.png)

**Comment by mhmrahmati** [comment]
yes I tried again and your mentioned error was reproduced.
I guessed that the lack of supporting of consumer group in DescribeConfigs method was the problem . But I was not sure.
thanks for response

**Comment by scaoupgrade** [comment]
@edenhill Are we adding this support to describe consumer group  configs?
Need this to get information regarding stored offsets of each topic partition for a certain consumer group to know the position to `seek` to upon consumer restart.
Similar to what has been offered here: https://kafka-python.readthedocs.io/en/master/apidoc/KafkaAdminClient.html#kafka.admin.KafkaAdminClient.describe_consumer_groups

**Comment by pranavrth** [comment]
The solution to the original question is explained.

We now have `describe_consumer_groups` API in the Admin client.

Closing this issue.
