### ISSUE TITLE
Timing issue with create_topics

### ISSUE THREAD

**Issue by ivonindza** [confluentinc/confluent-kafka-python#459]
Description
===========
I'm writing some integration tests for our code and doing create_topics/delete_topics in test set_up/tear_down. Code is something like this:
```
def kafka_create_topics(topics: Iterable[str]):
    new_topics = [NewTopic(t, num_partitions=1, replication_factor=1) for t in topics]
    admin = AdminClient({'bootstrap.servers': ...})

    futures = admin.create_topics(new_topics)
    for f in futures.values():
        f.result()

    time.sleep(1)
    while True:
        cluster_topics = admin.list_topics().topics
        if all(t in cluster_topics for t in topics):
            break
```

Even after this whole thing, the testing code that follows is not guaranteed to encounter created topics and occasionally fails with KafkaError.UNKNOWN_TOPIC_OR_PART. Any idea why this would happen?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('0.11.5', 722176), ('0.11.5', 722431)
 - [x] Apache Kafka broker version: 2.11-1.1.0
 - [ ] Client configuration: `{...}`
 - [x] Operating system: linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
by default, the broker will return a response to the create_topics call without waiting for the operation to complete (i.e. be completely synced across other brokers / zookeeper). to make the broker block until topic creation has completed, you can set the operation_timeout option parameter to a value higher than 0.

https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/admin/__init__.py#L299

**Comment by ivonindza** [comment]
Hi, sorry for the slow reply. This doesn't resolve my issue. I am still unable to reliably create/delete topics through AdminClient.

Setting the operation_timeout doesn't work reliably either. Occasionally I get a KafkaError._TIMED_OUT  with "Failed while waiting for response from broker: Local: Timed out" message. The timeout is set to maximum 3600, however this exception happens immediately, so the operation obviously doesn't wait for this timeout. Configuration of controller.socket.timeout.ms and replica.socket.timeout.ms is set to 30000 for both. Probably unrelated, but if I try to set request_timeout to a value larger than 2147, it fails with KafkaError._TIMED_OUT and "Timed out initializing" message.

Another error I get occasionally is KafkaError.NOT_CONTROLLER with "Broker: Not controller for cluster" message. Why does this happen? AdminClient is configured with a bootstrap server, so it should know all the servers and which one is the controller.

**Comment by edenhill** [comment]
For the UNSUPPORTED_FEATURE, try configuring `broker.version.fallback=0.10.0.0` and `api.version.fallback.ms=0`. This is a workaround for timeouts during broker api version detection heuristics.

Re NOT_CONTROLLER: is it possible that your cluster is unstable and a new controller is being elected while you are running?

**Comment by ivonindza** [comment]
Yes, the cluster was unstable due to a Zookeeper issue, and brokers kept disconnecting, which resulted in these different KafkaErrors. It would always start with a number of _TIMED_OUT errors and sometimes one of the other two types would follow.

**Comment by ainiml** [comment]
I'm having something similar, where `AdminClient.create_topic` just doesn't create a topic at all.

`AdminClient.list_topics('new_topic')` works, however
