### ISSUE TITLE
Segmentation fault while running integration test.

### ISSUE THREAD

**Issue by samarthg** [confluentinc/confluent-kafka-python#46]
I have installed kafka (kafka_2.11-0.10.0.0), confluent-kafka-python and librdkafka properly.
If I run the integration test without testing consumer it works fine. However with "verify_consumer()" it fails with error `Segmentation fault (core dumped)`

**Comment by edenhill** [comment]
What version (or git sha1) of librdkafka are you using?

Can you do this and provide the output?
```
$ rm core
$ ulimit -c unlimited
$ py.test tests/test_Consumer.py
# wait for it to crash
$ gdb python core
gdb> bt
```

Thanks

**Comment by ryanjmccall** [comment]
I think by 'integration test' OP means https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/integration_test.py

I can reproduce the problem by specifying an 'on_commit' for the Consumer:
(Using confluent_kafka module version 0.9.1, librdkafka version 0.9.1, and Python 3.5.2)

`>>> from confluent_kafka import Consumer
>>> def foo():
...     pass
>>> consumer = Consumer({'bootstrap.servers': 'localhost:9092',
...                          'group.id': 'confluent-group',
...                          'on_commit': foo,
...                          'default.topic.config': {
...                              'auto.offset.reset': 'smallest'}})

>>> consumer.subscribe(["confluent-topic"])
>>> msg = consumer.poll()
>>> consumer.commit(msg, async=False)
Fatal Python error: PyEval_RestoreThread: NULL tstate

Current thread 0x00007fffa1dfc3c0 (most recent call first):
  File "<stdin>", line 1 in <module>
Abort trap: 6 (core dumped)`

**Comment by edenhill** [comment]
This was most likely fixed by this commit:
https://github.com/confluentinc/confluent-kafka-python/commit/63fcfec0ad5902b583a2d867b2dbb181a7293e52

**Comment by edenhill** [comment]
integration_test.py passes on master
