### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by ivonindza** [confluentinc/confluent-kafka-python#460]
Description
===========
Apologies if this is stated somewhere, but I've been unable to find it. How thread-safe is this library? Is there anything to watch out for?

In particular, I want to use the consumer from multiple threads - one to consume, and another to commit offsets, which must be a common use-case, so I assume at least this is thread-safe.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The client is thread-safe, your use-case should work fine.
