### ISSUE TITLE
pip installation issue (command 'aarch64-linux-gnu-gcc' failed)

### ISSUE THREAD

**Issue by alexxtasi** [confluentinc/confluent-kafka-python#462]
Description
===========
Hi all !
I am trying to install  ```confluent-kafka``` into NVIDIA's Jetson TX2
The platform is : 
```$ uname -a
Linux tegra-ubuntu 4.4.38-tegra #1 SMP PREEMPT Fri Jul 28 09:55:22 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
```

trying to ```pip install confluent-kafka```, the output is : 
```
In file included from confluent_kafka/src/confluent_kafka.c:17:0:
  confluent_kafka/src/confluent_kafka.h:21:32: fatal error: librdkafka/rdkafka.h: No such file or directory
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for confluent-kafka
```
and in the end : 
```
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
```

Can anybody explain me : 
* can confluent-kafka be installed via pip in this machine or I have an architecture (aarch64) problem in general ?
* is there another method or a workaround for the installation ?

regards

How to reproduce
================
see above

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Linux tegra-ubuntu 4.4.38 (aarch64 GNU/Linux)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
We don't provide prebuilt binary wheels for aarch64, so you will need to compile it yourself, which requires you to first build and install librdkafka from source, which pretty much boils down to:
```
 $ sudo apt-get install -y libssl-dev zlib1g-dev gcc g++ make
 $ git clone https://github.com/edenhill/librdkafka
 $ cd librdkafa
 $ ./configure --prefix=/usr
 $ make
 $ sudo make install

Then go to the confluent-kafka-python source directory:
 $ python setup.py build
```

**Comment by bandwiches** [comment]
Is this a permanent answer?

**Comment by HoangTienDuc** [comment]
Hello @edenhill  I follow your instruction, but i cannot install confluent kafka python on my jetson tx2.
The error is in your last step:
```
Then go to the confluent-kafka-python source directory:
 $ python setup.py build
```
```
/data/confluent-kafka-python/src/confluent_kafka/src/confluent_kafka.c: In function ‘common_conf_setup’:
/data/confluent-kafka-python/src/confluent_kafka/src/confluent_kafka.c:2087:17: warning: implicit declaration of function ‘rd_kafka_conf_set_oauthbearer_token_refresh_cb’; did you mean ‘rd_kafka_conf_set_throttle_cb’? [-Wimplicit-function-declaration]
                 rd_kafka_conf_set_oauthbearer_token_refresh_cb(conf, oauth_cb);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 rd_kafka_conf_set_throttle_cb
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
```

**Comment by edenhill** [comment]
Your librdkafka version is likely too old. Use the latest release, 1.7.0

**Comment by HoangTienDuc** [comment]
thank for your quick reply. It works

**Comment by Helloyanxuan** [comment]
building 'confluent_kafka.cimpl' extension
creating build/temp.linux-aarch64-cpython-39
creating build/temp.linux-aarch64-cpython-39/opt
creating build/temp.linux-aarch64-cpython-39/opt/confluent-kafka-python-master
creating build/temp.linux-aarch64-cpython-39/opt/confluent-kafka-python-master/src
creating build/temp.linux-aarch64-cpython-39/opt/confluent-kafka-python-master/src/confluent_kafka
creating build/temp.linux-aarch64-cpython-39/opt/confluent-kafka-python-master/src/confluent_kafka/src
gcc -pthread -B /root/miniconda3/envs/pack/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -n1 .2-a+fp16+rcpc+dotprod+crypto -isystem /root/miniconda3/envs/pack/include -I/root/miniconda3/envs/pack/include -fPIC -O2 -n1 .2-a+fp16+rcpc+dotprod+crypto -isystem /root/miniconda3/envs/pack/include -fPIC -I/root/miniconda3/envs/pack/include/python3.9 -c /opt/confluent-kafka-python-master/src/confluent_kafka/src/Admin.c -o build/temp.linux-aarch64-cpython-39/opt/confluent-kafka-python-master/src/confluent_kafka/src/Admin.o
gcc: error: .2-a+fp16+rcpc+dotprod+crypto: No such file or directory
gcc: error: .2-a+fp16+rcpc+dotprod+crypto: No such file or directory
gcc: error: unrecognized command line option ‘-n1’; did you mean ‘-n’?
gcc: error: unrecognized command line option ‘-n1’; did you mean ‘-n’?
error: command '/usr/bin/gcc' failed with exit code 1

please help
