### ISSUE TITLE
Update doc with avro api

### ISSUE THREAD

**Issue by DrPyser** [confluentinc/confluent-kafka-python#467]
Description
===========
The "avro" section in the documentation is empty. It would be nice to have at minimum a description of the interface of the AvroConsumer and AvroProducer.

Thanks!

**Comment by rnpridgeon** [comment]
Agreed, I will get on that after the upcoming releases

**Comment by edenhill** [comment]
This is supposedly already fixed but not yet deployed.
https://github.com/confluentinc/confluent-kafka-python/commit/d6138947a89572c8e653a6d431c3ab2fb8035b36#diff-e3e2a9bfd88566b05001b02a3f51d286
