### ISSUE TITLE
Allow AvroProducer to get schemas from registry 

### ISSUE THREAD

**Issue by DrPyser** [confluentinc/confluent-kafka-python#468]
Description
===========
This is a feature request.

I'm wondering if it could be possible to consider having the `AvroProducer` get its schemas directly from the registry(i.e. query the registry for schemas associated with the topic on initialization)?

This would allow us to just push the schemas to the registry beforehand, and not have to put the schemas in the producer code local file system.

Thanks!

**Comment by rnpridgeon** [comment]
@DrPyser, we aim to keep the API surface area of this client as concise as possible; adding only features which are critical to Producing/Consuming to/from kafka. This helps us to keep the library maintainable while catering to the larger Kafka user base. For this reason I am going to mark this request as `wontfix`. 

With that said we enthusiastically encourage the development of wrapper libraries which cater to more specific use cases. Two such examples are [kafkian](https://github.com/saabeilin/kafkian/blob/master/README.md
), and [confluent_kafka_helpers](https://github.com/fyndiq/confluent_kafka_helpers
). I have not personally reviewed their entire API but you may find what you are looking for there. 

If you do wish to write your own I recommend reviewing the SchemaRegistryClient code; specifically get_latest_schema. 

https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/cached_schema_registry_client.py#L185-L222

**Comment by rooom13** [comment]
Hello,

Is this issue gonna be implemented? If not, which alternatives exist for such purpose?

**Comment by brifordwylie** [comment]
So @DrPyser is describing the exact thing that I thought would be 'standard practice'... meaning in the same way that we're encouraged to setup topics (formally) before having producers and consumers use them. I would assume the same is true of schemas... you would register them before and then producers would 'pull' the schema and use it.

I am fairly new to Avro.. so just trying to understand the best practices. My current setup is:
1) Create Topic
2) Create Avro Schema for that topic
3) Have Producer code pull schema from Registry

```
    """Produces data into the Kafka Topic"""
    schema_registry = CachedSchemaRegistryClient({'url': registry})
    schema_id, click_schema, version = schema_registry.get_latest_schema('com.scp.click-value')
    p = AvroProducer({'bootstrap.servers': server},
                     default_value_schema=click_schema,
                     schema_registry=schema_registry)
     ...
     p.produce(topic=topic, value=message)  # Not specifying schema (producer has default)
```

Is this basically the 'best practice' way...? Sorry for asking a question on a closed topic thread ;p
