### ISSUE TITLE
Disconnected error

### ISSUE THREAD

**Issue by gzliudan** [confluentinc/confluent-kafka-python#473]
Description
===========
Consumers report below errors in supervisord error log files somtimes:
%3|1540199111.115|FAIL|chuanglan#consumer-1| [thrd:kafka1a:9092/bootstrap]: kafka1a:9092/bootstrap: Disconnected
%3|1540199111.115|ERROR|chuanglan#consumer-1| [thrd:kafka1a:9092/bootstrap]: kafka1a:9092/bootstrap: Disconnected
%3|1540225213.163|FAIL|chuanglan#consumer-1| [thrd:kafka1c:9092/bootstrap]: kafka1c:9092/bootstrap: Disconnected
%3|1540225213.163|ERROR|chuanglan#consumer-1| [thrd:kafka1c:9092/bootstrap]: kafka1c:9092/bootstrap: Disconnected

Checklist
=========
Please provide the following information:

 - [ ] confluent_kafka.version() is ('0.11.5', 722176), confluent_kafka.libversion() is ('0.11.5', 722431)
 - [ ] Apache Kafka broker version: 1.0.0
 - [ ] Client configuration: 
    "bootstrap.servers": "kafka1a:9092,kafka1b:9092,kafka1c:9092",
    "group.id": "cg-lottery-prize",
    "session.timeout.ms": 30000,
    "default.topic.config": {
        "auto.offset.reset": "latest"
    }

 - [ ] Operating system: centos 7.5

**Comment by rnpridgeon** [comment]
@gzliudan are you noticing that you see these disconnects at regular intervals for each broker? i.e. kafka1a sees these disconnects every 10 minutes? Assuming the application continues running as expected I suspect you are just being spammed when the broker's idle connection reaper terminates the idle connections. The underlying client library, librdkafka, has a wiki which explains this situation quite well which I have linked below. 

https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected

**Comment by rnpridgeon** [comment]
Closed due to inactivity.
