### ISSUE TITLE
Is there any documentation of AvroConsumer? I can't find it.

### ISSUE THREAD

**Issue by EKenny31** [confluentinc/confluent-kafka-python#474]

**Comment by rnpridgeon** [comment]
It looks like there must have been some conflict building the docs. The avro module is present in the sphinx index but as you have correctly pointed out there is no content. 

I'll try to look into it tomorrow or early next week. In the meantime the docs are generated from the doc comments in the source itself. 

https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/__init__.py

**Comment by rnpridgeon** [comment]
Fixed: 

https://docs.confluent.io/current/clients/confluent-kafka-python/#module-confluent_kafka.avro

**Comment by ddboline1** [comment]
FYI, it's broken again.
