### ISSUE TITLE
PyPI wheel for 0.11.6 (Python 3.6 x86-64, manylinux) causes BadWheelFile

### ISSUE THREAD

**Issue by vtermanis** [confluentinc/confluent-kafka-python#482]
Description
===========
At least one of the wheels for version `0.11.6` on PyPI seems to contain an invalid hash. The previous version (`0.11.5`) for the below mentioned platform etc. does not seem to have said problem.

- `confluent_kafka==0.11.6` (via PyPI)
- Ubuntu 16.04, Python 3.6.2, x86-64
- `pip==18.1,wheel=0.31.1,setuptools=40.5.0`

How to reproduce
================
**Procedure**
```shell
wget https://files.pythonhosted.org/packages/dd/0a/c8bbf50a0b8e1d623521565e4c3211aebf7c9a7cf7eeb35b5360132a0ccc/confluent_kafka-0.11.6-cp36-cp36m-manylinux1_x86_64.whl
# Alternatively run (assuming have Linux x86-64 & CPython 3.6):
pip wheel --no-cache -w . confluent_kafka==0.11.6

md5sum confluent_kafka-0.11.6-cp36-cp36m-manylinux1_x86_64.whl 
72bf2e29ab1608e49bbc36d0a51546a8  confluent_kafka-0.11.6-cp36-cp36m-manylinux1_x86_64.whl

# Trigger wheel check
wheel unpack -d /tmp confluent_kafka-0.11.6-cp36-cp36m-manylinux1_x86_64.whl
```

**Actual outcome**
Wheel unpack/install fails with:
`wheel.install.BadWheelFile: Bad hash for file 'confluent_kafka/cimpl.cpython-36m-x86_64-linux-gnu.so`

**Expected outcome**
Wheel unpack/install succeeds.

**Comment by rnpridgeon** [comment]
Thanks for reporting this @vtermanis. This seems related to the changes we made to include confluent monitoring interceptors. I'll dig into it a bit more next week to.

**Comment by switchtrue** [comment]
This also appears to be occurring with the `confluent_kafka-1.0.0-cp34-cp34m-manylinux1_x86_64.whl` any progress on this?

**Comment by azfaraziz** [comment]
I am getting this issue on the latest version `1.3.0` I tried earlier version up to `1.0.0` and still having the same error
`wheel.install.BadWheelFile: No expected hash for file 'confluent_kafka/.dylibs/monitoring-interceptor.dylib'`

Any updates on this?

**Comment by shanwei8** [comment]
same here.

**Comment by shanwei8** [comment]
same here.
wheel.install.BadWheelFile: No expected hash for file 'confluent_kafka/.dylibs/monitoring-interceptor.dylib'
version is confluent-kafka==1.3.0

**Comment by yukon71** [comment]
> I am getting this issue on the latest version `1.3.0` I tried earlier version up to `1.0.0` and still having the same error
> `wheel.install.BadWheelFile: No expected hash for file 'confluent_kafka/.dylibs/monitoring-interceptor.dylib'`
> 
> Any updates on this?

Hi azfaraziz, i have same problem on 1.4.0. Did you resolve this one in your side? thanks

**Comment by yukon71** [comment]
> Thanks for reporting this @vtermanis. This seems related to the changes we made to include confluent monitoring interceptors. I'll dig into it a bit more next week to.

Hi sir, is there any solution on this error now? thanks!
