### ISSUE TITLE
Please put 0.11.6 source file on pypi

### ISSUE THREAD

**Issue by takaomag** [confluentinc/confluent-kafka-python#483]
Description
===========
There is no 0.11.6 source file archive on pypi.

How to reproduce
================
```
# pip3 download --no-deps --no-binary :all: confluent-kafka==0.11.6
Collecting confluent-kafka==0.11.6
  Could not find a version that satisfies the requirement confluent-kafka==0.11.6 (from versions: 0.9.1.1, 0.9.1.2, 0.9.2, 0.9.4, 0.11.0, 0.11.4, 0.11.5)
No matching distribution found for confluent-kafka==0.11.6
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python version: 0.11.6

**Comment by rnpridgeon** [comment]
@takaomag, sorry about that you should be able to access it now. 

pip download --no-deps --no-binary :all: confluent-kafka==0.11.6
Collecting confluent-kafka==0.11.6
  Downloading https://files.pythonhosted.org/packages/83/e1/433c7a5761d1356bd0a03cdffa1438cdc4b3c22a325ffa4de28fcb385d50/confluent-kafka-0.11.6.tar.gz (72kB)
    100% |████████████████████████████████| 81kB 1.7MB/s
  Saved ./confluent-kafka-0.11.6.tar.gz
Successfully downloaded confluent-kafka
