### ISSUE TITLE
single producer send messages to multiple topics in sequence (in callback functions)

### ISSUE THREAD

**Issue by jinjinqing** [confluentinc/confluent-kafka-python#487]
Description
===========
I create one producer and send messages to one topic by produce() function. After the message has been delivered, in the callback function, I want to send some other message to another topic (within the same producer). I can see that the messages to both topics are able to push, but the program gets stuck somehow. Is there any problem with such kind of implementation?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
1. Please fill out the checklist including the version and configuration you are using

2. Could you elaborate a bit more on what you mean by the program gets stuck? Perhaps share if you share you code it would be easier to diagnose. 

The following example demonstrates what I believe you are trying to achieve. 

```Python
from confluent_kafka import Producer, Consumer, KafkaError


p = Producer({'bootstrap.servers': 'localhost:29092'})
p.produce("test", 'Hello  Python!', callback=lambda err, msg: p.produce("test2", 'goodbye Python!'))
p.flush(10)

c = Consumer({'bootstrap.servers': 'localhost:29092',
              'group.id': 'tester',
	          'auto.offset.reset': 'earliest'})
c.subscribe(["^test.*"])

cnt = 0
while cnt < 2:
    msg = c.poll(1.0)

    if msg is None:
        continue
    if msg.error():
        continue 
    cnt += 1
    print('Received message {}: {}'.format(cnt, msg.value().decode('utf-8')))

c.close()
```

If we run this we will see the following output
```bash
python /tmp/test.py
Received message 1: Hello  Python!
Received message 2: goodbye Python!
```
