### ISSUE TITLE
How to send basic authentication parameters

### ISSUE THREAD

**Issue by sssshah** [confluentinc/confluent-kafka-python#489]
Description
===========
I'm trying the same python 3.6 AvroConsumer program in Python and it keep failing because basic authentication information is not provided. 

In Java, you can add these properties, is there similar for Python?
props.put(“basic.auth.user.info”,“admin:xxxx");
   props.put(“basic.auth.credentials.source”,“USER_INFO”);

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Currently this is not supported but there is a PR under review which adds this functionality. 

https://github.com/confluentinc/confluent-kafka-python

In the meantime you can add your user info the schema registry url itself. 

i.e.
https://user:password@localhost:8081

https://tools.ietf.org/html/rfc3986#section-3.2

**Comment by sssshah** [comment]
Thank you! Yes, that worked!! Spent hours to figure out why our code wouldn't work and we were just hitting a wall :-( Thank you! 👍

**Comment by mahdizolqadr** [comment]
> Currently this is not supported but there is a PR under review which adds this functionality.
> 
> #440
> 
> In the meantime you can add your user info the schema registry url itself.
> 
> i.e.
> https://user:password@localhost:8081
> 
> https://tools.ietf.org/html/rfc3986#section-3.2

in config i insert correctly format 'https://<USERNAME>:PASSWORD@DOMAin:PORT' but when use produce raise error with this format 
```
InvalidURL: Failed to parse: https://<MYPASSWORD>:SITE:PORT/subjects/TOPIC/versions
```
:|
