### ISSUE TITLE
Update docs to include cached schema registry client

### ISSUE THREAD

**Issue by rnpridgeon** [confluentinc/confluent-kafka-python#495]
Description
===========

For one reason or another cached schema registry docs are not being generated. This should be fixed. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by lowercase24** [comment]
This seems to still be the case.  I'd like to take a crack at this point.  It seems like this is adding the appropriate markup to support Sphinx.  Please advise.  Thanks!

**Comment by rnpridgeon** [comment]
Please do! I've been away on a few other projects and now I'm trying to play catch up so this is a bit low on the priority list. I'll be more than happy to review and merge your pr for this!

**Comment by lowercase24** [comment]
Awesome.  I've got a fix.  Should my PR be against master? @rnpridgeon

**Comment by lowercase24** [comment]
I have the changes on a local branch but I can't push them up to master.  I've signed the contributor agreement.  What do I need to do to be able to get this branch and PR up?    Here is what I am seeing.

(env) bradh@reef ~/proj/confluent-kafka-python (avro_cache_fix)*$ 
(env) bradh@reef ~/proj/confluent-kafka-python (avro_cache_fix)*$ git push -u origin avro_cache_fix
ERROR: Permission to confluentinc/confluent-kafka-python.git denied to lowercase24.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lowercase24** [comment]
@AkhilGNair any idea how I can get access here?  Am I doing this incorrectly?

**Comment by rnpridgeon** [comment]
@lowercase24 you should perform the following: fork the repo, create new branch, push changes, open a pr against this repo. 

Thanks again for your efforts!

**Comment by lowercase24** [comment]
See this:
https://github.com/confluentinc/confluent-kafka-python/pull/652

**Comment by lowercase24** [comment]
I wanted to follow up on next steps here.  @rnpridgeon can you take a look and let me know?  Thanks!

**Comment by lowercase24** [comment]
What needs to be done to wrap this up?  I'd like to become more active in this project, but currently turn around time is really laggy...

**Comment by edenhill** [comment]
@lowercase24 Merged now. Sorry to keep you waiting, we're very much looking forward to your future contributions!
