### ISSUE TITLE
import confluent_kafka fails on macOS 10.12.6

### ISSUE THREAD

**Issue by Sword-Breaker** [confluentinc/confluent-kafka-python#499]
Description
===========

import confluent_kafka fails on MacOS Sierra 10.12.6 with Python 2.7.10 and Python 3.5.2。

How to reproduce
================

pip install 'confluent-kafka==0.11.6'

Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from confluent_kafka import Consumer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sword-breaker/venv/backend/lib/python2.7/site-packages/confluent_kafka/__init__.py", line 2, in <module>
    from .cimpl import (Consumer,  # noqa
ImportError: dlopen(/Users/sword-breaker/venv/backend/lib/python2.7/site-packages/confluent_kafka/cimpl.so, 2): Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Users/sword-breaker/venv/backend/lib/python2.7/site-packages/confluent_kafka/.dylibs/libcrypto.1.0.0.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/sword-breaker/venv/backend/lib/python2.7/site-packages/confluent_kafka/.dylibs/libcrypto.1.0.0.dylib

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): librdkafka: stable 0.11.6, confluent-kafka 0.11.6
 - [ ] Operating system: MacOS Sierra 10.12.6

**Comment by edenhill** [comment]
Interesting.
Do you have xcode installed? (xcode-select --install)

**Comment by Sword-Breaker** [comment]
Yes.

**Comment by cricket007** [comment]
> Python 2.7.10

Is that the system pre-installed Python2?

You might want to give [pyenv](https://github.com/pyenv/pyenv) a try. 

This repo works for me when using Miniconda2 installed through that

```
[jomoore@ipynb] $ pip install 'confluent-kafka==0.11.6'
Requirement already satisfied: confluent-kafka==0.11.6 in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (0.11.6)
Requirement already satisfied: enum34 in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from confluent-kafka==0.11.6) (1.1.6)
Requirement already satisfied: futures in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from confluent-kafka==0.11.6) (3.2.0)

[jomoore@ipynb] $ pip install 'confluent-kafka[avro]==0.11.6'
Requirement already satisfied: confluent-kafka[avro]==0.11.6 in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (0.11.6)
Requirement already satisfied: enum34 in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from confluent-kafka[avro]==0.11.6) (1.1.6)
Requirement already satisfied: futures in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from confluent-kafka[avro]==0.11.6) (3.2.0)
Requirement already satisfied: avro; extra == "avro" in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from confluent-kafka[avro]==0.11.6) (1.8.2)
Requirement already satisfied: requests; extra == "avro" in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from confluent-kafka[avro]==0.11.6) (2.19.1)
Requirement already satisfied: fastavro; extra == "avro" in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from confluent-kafka[avro]==0.11.6) (0.21.14)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from requests; extra == "avro"->confluent-kafka[avro]==0.11.6) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from requests; extra == "avro"->confluent-kafka[avro]==0.11.6) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from requests; extra == "avro"->confluent-kafka[avro]==0.11.6) (2018.8.24)
Requirement already satisfied: idna<2.8,>=2.5 in /Users/jomoore/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages (from requests; extra == "avro"->confluent-kafka[avro]==0.11.6) (2.7)

[jomoore@ipynb] $ pyenv global
miniconda2-latest
[jomoore@ipynb] $ python --version
Python 2.7.15 :: Anaconda, Inc.
```

**Comment by xmavrck** [comment]
+1

**Comment by elahika** [comment]
same here. I have the package installed, but when I try to run the app using it, I get the same error
pip3 install confluent_kafka
Requirement already satisfied: confluent_kafka in /usr/local/lib/python3.7/site-packages (0.11.6)

at runtime : 
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/confluent_kafka/cimpl.cpython-37m-darwin.so, 2): Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /usr/local/lib/python3.7/site-packages/confluent_kafka/.dylibs/libcrypto.1.0.0.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.7/site-packages/confluent_kafka/.dylibs/libcrypto.1.0.0.dylib

**Comment by rnpridgeon** [comment]
It would appear that travis upgraded xcode on the build images a few months ago which is likely related to this issue. 

https://changelog.travis-ci.com/default-macos-image-is-now-xcode-9-4-67738

For the moment the work around is to build librdkafka and link it manually as it were prior to the pre-compiled wheels. I'll work on experimenting with older OSX build images but for the moment the work around will have to suffice.

**Comment by lcary** [comment]
My colleagues and I recently hit this error mentioned in @Sword-Breaker's initial post, and I can confirm that the same version of confluent_kafka (0.11.6) worked for me a month ago. I'm running on macOS version 10.12.6.

I'm able to work around the issue by downgrading confluent_kafka locally:
```
pip install confluent-kafka==0.11.5
```

**Comment by edenhill** [comment]
@lcary Thank you! That's very useful.

**Comment by wangjunqi001** [comment]
@lcary It's really help！My mac os version is 10.12.6，"confluent-kafka==0.11.6" has not work，but when i change this fucking package version into "confluent-kafka==0.11.6", it works.
