### ISSUE TITLE
how to display the timestamp while consuming through kafka-avro-console-consumer 

### ISSUE THREAD

**Issue by gmdun** [confluentinc/confluent-kafka-python#501]
Description
===========
 I have published the message using librdkafka API producev and trying to display the timestamp avro-using following command  but it does not display the timestamp but i can see the consumed message.  
bin/kafka-avro-console-consumer --topic  confluent \
 --bootstrap-server localhost:9092 \
 --property print.timestamp=true

How to reproduce
================

Checklist
=========
Please provide the following information:

 - librdkafka version is 0.11.4

**Comment by rnpridgeon** [comment]
Please open a issue with the schema registry as that repo owns and maintains the avro-console-consumer. The avro-console-consumer wraps the Apache Kafka console consumer which is not a librdkafka derived client. 

https://github.com/confluentinc/schema-registry
