### ISSUE TITLE
what's the behavior of the client when one of the brokers is down?

### ISSUE THREAD

**Issue by dalejin2014** [confluentinc/confluent-kafka-python#51]
I have a question regarding 0 downtime scenario.
Let's say I have 8 kafka nodes in a cluster.
A topic with 100 partitions. The partition leaders are on different nodes.
When I take one node down for OS patch, what will happen to the publisher and consumer?
The publisher and consumer both have a list of the 8 brokers.
Will they encounter errors when they try to publish and consume?
I can see that publisher and consumer can talk to any node in the cluster to find out which node
has the partition leader for the data they try to write or read. But if the node happened to be the partition leader will there be any downtime (perceived by publisher/subscriber) due to rebalancing (leader re-election, or preferred replica election and the partition rebalancing)?

**Comment by edenhill** [comment]
The underlying Kafka client (librdkafka) will automatically handle leader failures and switchovers by asking remaining active brokers for updated metadata to learn of new leader's for the failed partitions.
As soon as a new leader is available for a partition the client will resume producing or consuming.

**Comment by ewencp** [comment]
I'm going to close this as the question has been answered. @dalejin2014 feel free to reopen if you need further clarification.
