### ISSUE TITLE
Authentification error while connecting to kafka broker with kerberos

### ISSUE THREAD

**Issue by ellouminisrine** [confluentinc/confluent-kafka-python#513]
Description
===========
 I'm using confluent-kafka-python with kerberos in my producer whitch i add all the conf 
 like i specified the sasl.kerberos.principal, sasl.kerberos.keytab, sasl.kerberos.service.name as kafka, security.protocol as SASL_PLAINTEXT and the sasl.mechanisms as GSSAPI.

However i get this issue with  "SASL authentication failure: Disconnected"
Any suggesion.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Please clarify the following:

1. What OS are you running your client on 
2. How did you install confluent-kafka-python 
3. Please provide your complete configuration.
4. Have you verified the broker is configured correctly. I.e. Can you authenticate with other clients.

**Comment by rnpridgeon** [comment]
Closing due to lack of response.
