### ISSUE TITLE
Consumer re-reads the same partition

### ISSUE THREAD

**Issue by robinaly** [confluentinc/confluent-kafka-python#514]
Description
===========
If subscribe to a topic in a consumer and position the offset to some non-stanard position in on_assing, the consumer first reads correctly the partition from the specified positon and then 'sometimes' jumps back to that original offset / partition it already read. 

So, for example it would read 

0,10
0,11
0,12
and then again
0,10
0,11
0,12

I couldn't work out when exactly this occurs. I can't imagine that is desired bahavior. Any help is appreciated.

Here is the basic code. 
def on_assign_rewind(c, ps):
    for p in ps:
        low, high = c.get_watermark_offsets(p)
        p.offset = max(high - args.Rewind, 0)
    r = c.assign(ps)

c = Consumer(**consumer_config)
c.subscribe([topic_str], on_assign=on_assign)

# example
while True:
    msg = c.poll(0)

    if msg is None:
        continue
    if msg.error():
        print("Consumer error: {}".format(msg.error()))
        continue

    print('Received message: {}'.format(msg.value().decode('utf-8')))

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('0.11.6', 722432) and ('0.11.6', 722687)
 - [x] Apache Kafka broker version: 2.0.0 / 
 - [ ] Client configuration: 'bootstrap.servers': 'xxx,
        'group.id': 'xxx'},
 - [ ] Operating system: Ubuntu Linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
How certain are we that the output of `max(high - args.Rewind, 0)` actually changes? Recall that your fetcher will seek to this offset each time your consumer receives a new partition assignment(group rebalance).

**Comment by rnpridgeon** [comment]
I'm not sure I follow you here, please find my responses below. 

> I guess my question could be reformulated: why my consumer gets reassigned the same partition after hitting eof.

An EOF will not cause your consumer to leave the group. If it is then you have some logic within your code telling it to do so as its not part of the library logic. 

Your consumer's partition assignment is determined by the number of consumers in your consumer group and the configured `partition.assignment.strategy`. 

>In principle I just want to start args.Rewind before the earliest and then
keep on reading (wait for new messages if necessary).

If you rewind to the beginning of the queue each time you are assigned a partition its expected that you will reread the offsets in the queue. If you are just looking to start from the earliest then pick up where you left off you should be using `auto.offset.reset` instead of implementing your own logic.

**Comment by rnpridgeon** [comment]
Is this still something you need assistance with, if not I'll go ahead and mark this as closed for now as I'm not sure there is a bug here. 

One other thing to note, your assingnor is named `on_assign` but your function calls `on_assign_rewind`. I don't have access to all your code so this may be fine but it based on the snippets your provided alone it seems like we may just have some reference issues.

**Comment by jeverick** [comment]
I'm having the same experience as @robinaly. What I'm noticing is that the `on_assign` callback is called multiple times not just once. Each time it's called, my partitions get reassigned and my consumers begin back from the beginning.

Is there a reason the `on_assign` callback would be fired more than once? Is it possible to prevent this?

There are ways for me to get around this in my implementation but I want to understand why/when the `on_assign` callback should be fired. And if it's a bug that it's firing multiple times, hopefully it can be fixed.

**Comment by edenhill** [comment]
on_assign will be called on each group rebalance, no more no less.   You can set the `debug` config property to `consumer` (or `cgrp` for more detail) to see why the group is rebalancing, or check the broker logs.
