### ISSUE TITLE
Is there some consumer timeout?

### ISSUE THREAD

**Issue by robooo** [confluentinc/confluent-kafka-python#521]
Description
===========
Sometime when I don't subscribe to a topic for a longer time, I get error consumer is closed. 
Is there some config attribute to make it infinite?

**Comment by rnpridgeon** [comment]
Could you please elaborate on what you mean by `closed`? 

If you are referring to the connection to Kafka this is actually the underlying connection being reaped by the broker's idle connection reaper. This ensures the broker is not needlessly hanging on to resources which no longer need to be held. In the event this happens however your consumer should establish a new connection with the broker.

**Comment by robooo** [comment]
When you don't subscribe for a long time and then I get only one message from confluent-kafka `Consumer closed` don't know how to debug it more.
My case looks similar to this (But using it with combination of RobotFramework):

```

from confluent_kafka import Consumer, KafkaError


c = Consumer({
    'bootstrap.servers': 'mybroker',
    'group.id': 'mygroup',
    'auto.offset.reset': 'earliest'
})

// commands which takes about 5-10 min

c.subscribe(['mytopic'])

-> Consumer closed.

```

**Comment by rnpridgeon** [comment]
Thanks @roboo, 

Would it be possible for you to share the logs which document this behavior. There is nothing in librdkafka(the client which underpins confluent-kafka-python) which actually closes an idle consumer. You may see idle connection timeouts but those connections will be reestablished. There may be something I'm missing but it's hard to say without more context.

**Comment by robooo** [comment]
Well as I said I can't debug it any way deeper but it looks like there will be some issue on my side. So I'm closing this.
Thanks!
