### ISSUE TITLE
SSL: Is it possible to not verify the broker certificate?

### ISSUE THREAD

**Issue by voiprodrigo** [confluentinc/confluent-kafka-python#522]
Couldn't find a way to do this, is it possible somehow?

Thanks

**Comment by rnpridgeon** [comment]
When you say verify are you referring to endpoint verification as performed by `https` or are you referring to verifying the CA is within your chain of trust. 

For the former I do not believe endpoint verification is performed as the Kafka protocol is a custom protocol built atop TCP. As such the endpoint verification rules described in the HTTPS specification do not technically apply. 

For the latter I do not believe this is possible.

**Comment by voiprodrigo** [comment]
Just skip trust chain verification of the certificate presented by the broker.

Thanks for the clarification.
