### ISSUE TITLE
consumer.seek(TopicPartition(...)) raises KafkaException: KafkaError{code=_INV ...

### ISSUE THREAD

**Issue by nmvega** [confluentinc/confluent-kafka-python#528]
Hello Friends:

I am getting this exception -- `KafkaException: KafkaError{code=_INV ...` when issuing this sequence:

```
from confluent_kafka import Consumer as kafka_Consumer, KafkaError, TopicPartition

conf = {'bootstrap.servers': 'vps00:9092',
        'group.id': 'myGroup01',
        'client.id': 'client01',
        'enable.auto.commit': True,
        'session.timeout.ms': 6000,
        'default.topic.config': {'auto.offset.reset': 'smallest'}
       }

kc = kafka_Consumer(conf)
kc.subscribe(['topic01'])
print(kc.seek(TopicPartition('topic01', 0, 0)))  # Exception Raised Here.
```

The environment:
---
- `PYTHON` is within a virtual environment (venv) via `ANACONDA`, with `PYTHON` version: `v3.6.7`
- `confluent-kafka` is also via the `ANACONDA` venv with version: `v0.11.4`
- `ANACONDA` installs the `librdkafka` dependency at the same time `confluent-kafka` is, but I'm unsure which version that is (possibly `v11.5` from the following output):

```
(pyvenv.d) jdoe@fedora$ find . -ls | grep librd
 93716762      8 -rw-r--r--   1  jdoe   jdoe       5460 Jan 23 19:58 ./conda-meta/librdkafka-0.11.5-ha79af3b_1000.json
 93716758   1552 -rwxrwxr-x   1  jdoe   jdoe    1585464 Sep 18 04:20 ./lib/librdkafka++.so.1
 93716756   2640 -rwxrwxr-x   1  jdoe   jdoe    2699468 Sep 18 04:20 ./lib/librdkafka++.a
 93716761   5600 -rwxrwxr-x   1  jdoe   jdoe    5734056 Sep 18 04:20 ./lib/librdkafka.so.1
 93716759   7960 -rwxrwxr-x   1  jdoe   jdoe    8148156 Sep 18 04:20 ./lib/librdkafka.a
 93716760      0 lrwxrwxrwx   1  jdoe   jdoe         15 Jan 23 19:58 ./lib/librdkafka.so -> librdkafka.so.1
 94110307   6784 -rwxr-xr-x   1  jdoe   jdoe     6944424 Jan 24 12:24 ./lib/python3.6/site-packages/confluent_kafka/.libs/librdkafka.so.1
 93716757      0 lrwxrwxrwx   1  jdoe   jdoe          17 Jan 23 19:58 ./lib/librdkafka++.so -> librdkafka++.so.1
 93985947      4 drwxr-xr-x   2  jdoe   jdoe        4096 Jan 23 19:58 ./include/librdkafka
 93985949     76 -rwxrwxr-x   1  jdoe   jdoe       74175 Sep 18 04:20 ./include/librdkafka/rdkafkacpp.h
 93985948    180 -rwxrwxr-x   1  jdoe   jdoe      180645 Sep 18 04:20 ./include/librdkafka/rdkafka.h
```
- Finally -- and this may or may-not be important -- because `ANACONDA` (or any of the 3rd-party ANACONDA channels like `conda-forge`) didn't offer `v0.11.6` -- which I need for its additions/enhancements over the available `v0.11.4` -- I performed a `(pyvenv.d) jdoe@fedora$ pip install confluent-kafka --upgrade` to upgrade it. I did that hesitantly, but needed to try.

Note that at the `FEDORA` system library level, the `librdkafka` RPM is installed and is version `librdkafka-0.11.3-2.fc28.x86_64`; however, I don't believe that gets consulted when operating within the PYTHON venv.

Any ideas? Also, is there a ANACONDA channel that has `v0.11.6`?

Thank you in advance!

**Comment by mhowlett** [comment]
you can only call seek on partitions that are currently being consumed from. in your case, you're calling seek immediately after the subscribe call, so the partition assignment won't have been made available to the client yet. instead of what you're doing, you may want to:

1. never commit offsets, i.e. turn off enable.auto.commit and never call commit. In that case, the consumer will always start from the earliest available message in a partition.
2. provide an `on_assign` callback to the `subscribe` method and call `consumer.assign` in that to specify the desired start offset. see https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/consumer.py#L89
3. don't use `subscribe` (i.e. don't use the consumer rebalance feature of kafka). instead, assign to a fixed set partitions with the consumer.assign method (and specify a start offset when doing that).

**Comment by nmvega** [comment]
@mhowlett Matt, thank you for getting back so quickly and so thoroughly. Option `C` in my question should have been pilot error as I'm switching from the `kafka` client to the ` v0.11.6 confluent_kafka` client (or trying to). Again, I appreciate your response and it gives me a few options to try. Thank you again.

**Comment by snagacarl** [comment]
Thank you for that clarification, @mhowlett !

The [documentation](https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.subscribe) for `subscribe`'s `on_assign` argument currently says:

> on_assign (callable) – callback to provide handling of customized offsets on completion of a successful partition re-assignment.

Which suggests to me that the assignment is already complete ("on *completion* of...re-assignment"), and therefore that `seek` should be usable.  If the assignment has not actually completed when `on_assign` is called, or if `seek` is invalid and (`consumer.assign` is necessary0 for some other reason, I think the documentation is confusing.
