### ISSUE TITLE
Union types upcast to last matching union type instead of first in AvroProducer

### ISSUE THREAD

**Issue by Paxanator** [confluentinc/confluent-kafka-python#530]
Description
===========
Per the avro spec https://avro.apache.org/docs/1.8.1/spec.html#Unions unions should return the _first_ matching element in array of candidates.

Because of this property of python https://stackoverflow.com/questions/37888620/python-comparing-boolean-and-int-using-isinstance booleans will be cast to doubles/ints if a union contains that specification after the boolean

The offending line is in thee avro library here: 
https://github.com/apache/avro/blob/master/lang/py/src/avro/io.py#L873-L875

This impacts the AvroProducer in this library. I don't think there isn't anything to be done in this library, but want to make sure the issue is raised. This can be closed once the upstream avro library is fixed

How to reproduce
================
```
import io
import avro.schema
import avro.io



if __name__ == '__main__':
    test_schema ='''{"type":"map","values":["null","boolean","int","long","double","bytes",{"type":"string","avro.java.string":"String"}]}'''
    record = {"value":False}
    schema = avro.schema.parse(test_schema)
    writer = avro.io.DatumWriter(schema)

    bytes_writer = io.BytesIO()
    encoder = avro.io.BinaryEncoder(bytes_writer)
    writer.write(record,encoder)
    bytes_writer.flush()

    raw_bytes = bytes_writer.getvalue()
    print(len(raw_bytes))
    print(raw_bytes)
    print(type(raw_bytes))

    bytes_reader = io.BytesIO(raw_bytes)
    bytes_reader.flush()
    decoder = avro.io.BinaryDecoder(bytes_reader)
    reader = avro.io.DatumReader(schema)
    result = reader.read(decoder)
    print(result)
```

returns 

{u'value': 0.0}

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
('0.11.6', 722432)
('0.11.6', 722687)

 - [ ] Apache Kafka broker version:
N/A
 - [ ] Client configuration: `{...}`
N/A
 - [x] Operating system:
macOS 10.13.6
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
N/A
 - [ ] Provide broker log excerpts
N/A
 - [ ] Critical issue
N/A

**Comment by mhowlett** [comment]
thanks for pointing this out @Paxanator - only looked at this quickly, but it seems especially not great that the result `value` is a `float` (an `int` would have been less surprising). And yes, I don't think this is something we could/should fix in this library.
