### ISSUE TITLE
japronto request process hanging on producer.flush()

### ISSUE THREAD

**Issue by jkdntc** [confluentinc/confluent-kafka-python#531]
Description
===========
Source code here : https://github.com/jkdntc/LogReceiver

How to reproduce
================
# make build
# make run
# curl http://localhost:8080/async

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`('0.11.6', 722432)` and `('0.11.6', 722687)`):
 - [x] Apache Kafka broker version: 1.0.1
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
when I ran your program it did not hang in `producer.flush`. if you are running kafka in a docker image, perhaps you don't have networking set up correctly (check the `advertised.listeners` property)? does the sync method work when you uncomment `KafkaProducer.put2Kafka`? finally, you could paste client logs obtained when setting the config property `debug` to `all` and we can take a look at those.
