### ISSUE TITLE
Recommended way of managing multiple topics on one consumer

### ISSUE THREAD

**Issue by tszumowski** [confluentinc/confluent-kafka-python#535]
Description
===========
I noticed that there aren't consume callbacks exposed in the Python bindings, e.g. `consume_cb` in [config options](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). So I was curious if there is a recommended method for managing multiple topics in a single consumer.

Is it safe to just check the topic on every event and loop forever like the `README`  example? e.g. 

```
def process_topic_one(msg):
    ...

def process_topic_two(msg):
    ...

c.subscribe(['topic-one', 'topic-two])

while True:
    msg = c.poll(1.0)

    if msg is None:
        continue
    if msg.error():
        print("Consumer error: {}".format(msg.error()))
        continue

    if msg.topic() == "topic-one":
        process_topic_one(msg)
    elif msg.topic() == "topic-two":
        process_topic_two(msg)

c.close()
```

I was just curious if there was a more pythonic way of managing multiple topics, or other means of using callbacks.

How to reproduce
================
N/A

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by cricket007** [comment]
> more pythonic way of managing multiple topics

You could make a function dictionary 

```python
func_dict = {  "topic-one": process_topic_one,  "topic-two": process_topic_two} 

while True:
    msg = c.poll(1.0)

    if msg is None:
        continue
    if msg.error():
        print("Consumer error: {}".format(msg.error()))
        continue

    func_dict[msg.topic()](msg) 
```

**Comment by tszumowski** [comment]
> > more pythonic way of managing multiple topics
> 
> You could make a function dictionary
> 
> ```python
> func_dict = {  "topic-one": process_topic_one,  "topic-two": process_topic_two} 
> 
> while True:
>     msg = c.poll(1.0)
> 
>     if msg is None:
>         continue
>     if msg.error():
>         print("Consumer error: {}".format(msg.error()))
>         continue
> 
>     func_dict[msg.topic()](msg) 
> ```

Nice tip! I'll consider something like that. 
I'll close the issue since this will probably suffice.
