### ISSUE TITLE
Calling `flush()` method in another thread/process does not work

### ISSUE THREAD

**Issue by bagherbal** [confluentinc/confluent-kafka-python#536]
Description
===========
I want to produce my messages asynchronous, So for sending messages to Kafka server I use method below:
```
def store(topic, data):
    try:
        producer.produce(topic, json.dumps(data).encode('utf-8'), callback=_delivery_report)
        producer.poll(0)
    except:
        pass
```
In order to be sure every message has been delivered, I tried to call `flush` in another process (in Cron for example) but it seems this doesn't work as I expected and no delivery_report is being called;
But flush works if it's in the same thread/process. ( For example:
```
...
producer.produce()
# producer.poll(0)
producer.flush()
```
works and delivery_report is being called, but makes the process synchronous. )

Am I using it right?
What is the right way to use flush method and don't block the producer's process?

How to reproduce
================
1. Call method `store` in a Django view ( 1st process )
2. Call `producer.flush()` in Django shell Or in a Cronjob ( 2nd process )

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python (`confluent-kafka==0.11.6`)
 - [x] librdkafka  ( `('0.11.6', 722687)`):
 - [x] Apache Kafka broker version ( 2.11-2.1.0)
 - [x] Client configuration: 
```
{
    'bootstrap.servers': 'localhost:9092',
    'queue.buffering.max.ms': 100,
    'linger.ms': 100,
    'queue.buffering.max.messages': '1000000',
}
```
 - [x] Operating system: Ubuntu 16.04.5 LTS
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
confluent-kafka-python (or rather librdkafka) uses background threads, which means it will not survive a fork to a child process. The client must only be used in the same process as it was instantiated.

As for accessing the client instance from multiple threads, that should not pose a problem.

**Comment by bagherbal** [comment]
@edenhill Thanks :pray:
