### ISSUE TITLE
error_cb best practices

### ISSUE THREAD

**Issue by m-burst** [confluentinc/confluent-kafka-python#537]
Hi,

I would like to ask what are the best practices for implementation of `error_cb` in a consumer.
Are there any non-recoverable errors where the correct approach would be to raise an exception, or should the application just log the error and continue `poll`ing?

Thanks in advance!

**Comment by rnpridgeon** [comment]
Typically librdkafka, the client this client wraps, hides any non-permanent errors from the application and handles them gracefully internally by retrying. This means that the application needn't take any additional action. 

The one error you may run into that requires some sort of intervention would be the `__ALL_BROKERS_DOWN` error. This could be intermittent or it could be permanent depending on your situation. If it was just a network blip or something along those lines the client library will automatically reconnect to Kafka. 

 If you just enabled SSL or SASL or both and you start seeing this error it's likely a misconfiguration of sorts causing your requests to be refused. 

At any rate you will want to be mindful of this error but you probably don't need to take action unless it persist for some amount of time. Mind you your messages will be hanging out on the outbuf at this time where they may timeout. 

`LEADER_NOT_AVAILABLE` is another tricky one as it's actually fairly normal to see these during leadership transitions but if they stick around something is wrong. Depending on how many partitions you have and how busy the controller is it could take a little while for a new leader to be elected and for that change to be propagated. Again I would react on the first instance of such an error but if it sticks around for more than a minute or some something is probably wrong with that Topic Partition. This would be a good time to try and describe the the topic to check the ISRs. 

All of you `*AUTHORIZATION_FAILED` errors are not likely to self-remedy. This means your client does not have adequate permissions to do what they asked so you'll need to act accordingly. 

Hope that helps

**Comment by m-burst** [comment]
Thanks for such a detailed explanation! I'm closing this, will open a new issue if I have any more questions.
