### ISSUE TITLE
Deleting topic before creating causes race condition

### ISSUE THREAD

**Issue by David-Warnke** [confluentinc/confluent-kafka-python#541]
Description
===========
From my limited understanding of the API, it seems like you should be able to create and use multiple AdminClients in the same program. When I try to use more than one, I get futures (for example from create_topics()) that never execute, and are always in the running state. The following test code fails with "True != False". Debugging a little bit shows that the future created from create_topics() never executes and is always in the running state.

I don't fully understand how AdminClients works, so this might be intended behavior, I don't know.

I can work around it by taking an AdminClient as a parameter to my utility function, but it would be nice to abstract as much of the Kafka API away, so my teammates don't have to deal with it.

How to reproduce
================
kafka_utils.py
```
CONFIGURATION = {'bootstrap.servers': '0'}
def create_kafka_topic(topic: str):
        new_topic = admin.NewTopic(topic, 1, 1)
        admin.AdminClient(CONFIGURATION).create_topics([new_topic])
```
kafka_utils_test.py
```
client = admin.AdminClient(kafka_utils.CONFIGURATION)
client.delete_topics([topicName])
kafka_utils.create_kafka_topic(topicName)
topic_exists = topicName in client.list_topics().topics
self.assertEqual(True, topic_exists)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
('0.11.6', 722432) and ('0.11.6', 722687)
 - [x] Apache Kafka broker version:
?? kafka_2.12-2.1.0
 - [x] Client configuration: `{...}`
default
 - [x] Operating system:
Ubuntu 16.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by David-Warnke** [comment]
Okay It has nothing to do with the client. I changed the name of the issue to reflect new information. I used the same client in my code above (passing the client into create_kafka_topic(), and it still fails. I soon as I remove the deletion code it succeeds. It is definitely a race condition. What's weird is that adding the following code to the deletion part, passes the deletion assertion, but still fails on creation.
```
future = client.delete_topics([topicName], operation_timeout=1)[topicName]
while future.running():
    pass
topic_exists = topicName in client.list_topics().topics
self.assertEqual(False, topic_exists)
```
But as soon as I add a sleep(5) in there it succeeds. So the question I still have is... how do I make sure that it is truly and completely done deleting before I can create.

**Comment by edenhill** [comment]
This is a known broker issue.
Topic deletions are asynchronous and depending on the cluster load and state it may take a long time for a topic to be completely removed from all brokers in the cluster.
It is therefore strongly recommended not to delete and re-create topics in this manner, but instead create new unique topics, or maintain (commit) the last read offset for the topic partitions to make sure no old messages are picked up by a consumer.

**Comment by David-Warnke** [comment]
I see. That doesn't really help my unit test scenario, so I'll just keep using sleep for that and document the issue in my code. Thanks.
