### ISSUE TITLE
Unable to register rebalance_cb

### ISSUE THREAD

**Issue by gtadamson** [confluentinc/confluent-kafka-python#544]
Description
===========
When I try to register a rebalance_cb I get:
`KafkaError{code=_INVALID_ARG,val=-186,str="Property "rebalance_cb" must be set through dedicated .._set_..() function"}`
I'm registering by passing it to the client in the configuration like:
`Consumer({"rebalance_cb": rebalance_cb_function, "other config parameters"})`

Specifically what I'm trying to do is have a group of consumers all listen to all partitions on a topic. I'm using `assign` to assign all partitions to the consumer but I need the ability to re-assign dynamically if partitions are added.

I suspect I'm making a stupid mistake, but I can't figure out the incantation to get the rebalance call back to work.

UPDATE: after further investigation, I found this note in the 11.5 release of librdkafka [0.11.5](https://github.com/edenhill/librdkafka/releases/tag/v0.11.5):
Enhancements:
- Callback based event notifications (@fede1024)

Is that the answer, I need the new version (getting new versions in the environment I work in is difficult, that is why I haven't tried that already)?

How to reproduce
================
Pass a rebalance_cb parameter to a new Consumer.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka-python 0.11.5, librdkafka 0.11.3
 - [x] Apache Kafka broker version: 0.11.0.1
 - [x] Client configuration: `{'bootstrap.servers': 'blah1,blah2,...', 'log.connection.close': False, 'group.id': 'some_group', 'client.id': 'name_of_client', 'rebalance_cb': rebalance_cb_function}`
 - [x] Operating system: CentOS 7
 - [x] Provide client logs (with `'debug': '..'` as necessary): `KafkaError{code=_INVALID_ARG,val=-186,str="Property "rebalance_cb" must be set through dedicated .._set_..() function"}`
 - [ ] Provide broker log excerpts: N/A
 - [ ] Critical issue: No

**Comment by edenhill** [comment]
Pass your rebalance callbacks to `subscribe(.., on_assign=.. and on_revoke=..)`

**Comment by gtadamson** [comment]
For this case I'm manually assigning all partitions on a topic using `assign()` so that multiple consumers can see all messages. Is there a way to register the callbacks for `assign`?

We previously used `subscribe` with a consumer group set to a UUID to force each consumer into its own consumer group, but a Confluent person told a co-worker that using `assign` was a better way to achieve the goal of seeing all messages on a topic. Do you suggest we revert back to using `subscribe`?

**Comment by gtadamson** [comment]
But how do I detect a rebalance when using `assign()`?

Example: I have 2 partitions on a topic and I've `assign()`'ed a consumer to both partitions. Then another partition is added so now there are 3 partitions on the topic. How can the consumer be notified to read from the newly created partition?

**Comment by edenhill** [comment]
Rebalances are caused by joining a group after calling subscribe(), the outcome being a received assignment.

The assignment is then passed to assign() to start the actual fetching of the assigned partitions.

If you want to detect new topics or partitions you will need to call list_topics() every now and then to find them and then call assign() with the new set of partitions you want to consume.
