### ISSUE TITLE
Implement SASL/OAUTHBEARER support

### ISSUE THREAD

**Issue by shawnsarwar** [confluentinc/confluent-kafka-python#545]
Description
===========

SASL/OAUTHBEARER is currently supported as an authentication method in Kafka 2.1 brokers. We would love for the python client to support this as well.

How to reproduce
================
N/A: Feature request

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version: 2.1
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Work is ongoing in librdkafka PR https://github.com/edenhill/librdkafka/pull/2189, which will be included in the v1.1.0 release, probably April or May. We'll have release candidates to try before that.

**Comment by tkaymak** [comment]
As the librdkafka PR has been merged, we could now implement the support here in the library as well right?

**Comment by edenhill** [comment]
Yes, that's the plan.

**Comment by malthe** [comment]
Bump :-)

**Comment by MichalKosowski** [comment]
Any updates on the subject? I will really appreciate this functionality to be added... 🥺

**Comment by 2phost** [comment]
Hey, any updates? What is the roadmap for this feature?

**Comment by ernani** [comment]
This is targeted for April/May right? Are there any plans for a release candidate sooner?

**Comment by edenhill** [comment]
Yep, we'll create an RC pretty soon.

**Comment by stonelazy** [comment]
Just wanted to check whether this is available or if it can be expected ?

**Comment by edenhill** [comment]
OAUTHBEARER support was added to v1.6.1
