### ISSUE TITLE
1/1 Brokers Are Down

### ISSUE THREAD

**Issue by jkim049** [confluentinc/confluent-kafka-python#547]
Description
===========
When I try and run a python file the terminal throws this at me

Currently running Confluent-Kafka v0.11.6 and have tried to run this using the Apache Kafka Quickstart Guide as well. Still throws the same errors.

> config_string: {"manager": {"host": "XXXXX", "ip": "127.0.1.1", "port": 6101}}
> %3|1551203089.453|FAIL|rdkafka#producer-1| [thrd:rc-metrics.org:9092/bootstrap]: rc-metrics.org:9092/bootstrap: Connect to ipv4#10.84.235.56:9092 failed: Connection refused (after 80ms in state CONNECT)
> %3|1551203089.453|ERROR|rdkafka#producer-1| [thrd:rc-metrics.org:9092/bootstrap]: rc-metrics.org:9092/bootstrap: Connect to ipv4#10.84.235.56:9092 failed: Connection refused (after 80ms in state CONNECT)
> %3|1551203089.453|ERROR|rdkafka#producer-1| [thrd:rc-metrics.org:9092/bootstrap]: 
> 1/1 brokers are down

This is the code that I'm trying to execute currently
````
from flask import Flask, render_template
from routes import manager
import gevent.monkey
import gevent.pywsgi
import socket
import configparser
import json
from confluent_kafka import Producer

def create_app():
    app = Flask('rc')
    register_blueprints(app)
    return app

def register_blueprints(app):
    app.register_blueprint(manager.blueprint)

app = create_app()

def acked(err, msg):
    if err is not None:
        print("Failed to deliver message: {0}: {1}"
              .format(msg.value(), err.str()))
    else:
        print("Message produced: {0}".format(msg.value()))

def post_config(port):
    config = configparser.ConfigParser()
    config.read('../config.ini')
    hostname = socket.gethostname()
    IPAddr = socket.gethostbyname(hostname)

    kafka_server = config['kafka']['Host'] + ':' + config['kafka']['Port']
    p = Producer({'bootstrap.servers': kafka_server})
    config_string = json.dumps({'manager': {'host': hostname, 'ip': IPAddr, 'port': port}})
    print("config_string: " + config_string)
    try:
        p.produce('config', config_string, callback=acked)
        p.poll(0.5)
    except KeyboardInterrupt:
        pass

    p.flush(30)

def run(host: str = '0.0.0.0', port: int = 6101) -> None:
    post_config(port)
    gevent.monkey.patch_all()
    wsgi = gevent.pywsgi.WSGIServer((host, port), app)
    wsgi.serve_forever()

if __name__ == '__main__':
    print("run")
    run()`
````

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): Confluent-Kafka v0.11.6 
 - [x] Apache Kafka broker version: Apache Kafka 2.11-2.1.0
 - [x] Client configuration: `{address=0.0.0.0, port=12781, messageProducer=localhost:9092, dummyKafka=1}`
 - [x] Operating system: Ubuntu 18.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue: No

**Comment by rnpridgeon** [comment]
@jkim049 , The error message "Connect to ipv4#10.84.235.56:9092 failed: Connection refused " tells us that no one on host 10.84.235.56 is listening on port 9092. 

If you are using docker make sure that the port mapping aligns with your client configuration. It's also a good idea to ensure that Kafka actually came up. It's possible that something prevented Kafka from starting so nothing is bound to port 9092.

**Comment by mingtongzaohua** [comment]
I have encountered the same problem, I followed the quick start tutorial.
I have tried to modify advertised.listeners=PLAINTEXT://x.x.x.x:9092
Where x is the public IP of the server, but other machines still cannot access the server's kafka. The local producers and consumers on the server are normal. What should I do to allow other machines to put messages into kafka?
