### ISSUE TITLE
tag compatibility question ?

### ISSUE THREAD

**Issue by HeChuanXUPT** [confluentinc/confluent-kafka-python#550]
hi, 
Can I use client tag 0.11.6  to communication with broker 0.10.x, or better to use 0.10.x tag ?
What is the relationship with confluent-kafka-python tag and brokers ?

**Comment by edenhill** [comment]
confluent-kafka-python is compatible with all broker versions >= 0.8, but you may need to configure the client for older broker versions, see https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
