### ISSUE TITLE
Kafka Offset

### ISSUE THREAD

**Issue by ykishorereddy** [confluentinc/confluent-kafka-python#551]
Description
===========
I have a consumer process and has been running fine. but when I change consumer group name the kafka offset is not repositioning though I have (auto.offset.reset: 'earliest').  

im using version ==> confluent-kafka==0.11.5

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by z0u** [comment]
I think I may be seeing something similar. With `confluent-kafka` 0.11.0, I could do something like:

```
consumer.subscribe([topic], callback)
consumer.poll(2)
```

Where `callback` assigns partitions with offsets to seek to the end of the stream. Now, I need to increase the timeout for `poll` to something much larger, or the offsets may not actually be applied. Also I'm not sure but I think I also need to make the process sleep for a couple of seconds after the callback runs or else subsequent calls to `poll` may not receive the next message.

**Comment by mhowlett** [comment]
@ykishorereddy - if you change the consumer group name, all previous offsets will no longer apply (offsets belong to a consumer group). if you have `auto.offset.reset: 'earliest`, the consumer should start reading from the earliest available offset in each partition after you change the consumer group.

@z0u - are you calling seek in your callback? this client isn't analogous to the java client here - call assign instead of seek. if you past a complete example we may be able to offer more help.

both - definitely recommend upgrading to 1.0.

**Comment by MichaelZhangCA** [comment]
HI, I think there is a mapping bug from the conf init function.
* I'm using confluent-kafka 1.0 package for the testing on both Linux and Windows

by giving "earliest" to the auto.offset.rest, it works well on Linux but doesn't work on Windows.
set the value to "smallest" works on both Linux and Windows.

More detail difference **on Windows** is,
1, when set to "earliest", the consumer point to the very last of partition and waiting for a new message.
2, when set to "smallest", the consumer actually will grab the last "uncommitted" message, even the consumer has a different group id.

I just roughly tested the scenarios above, I might miss something during the testing.

**Comment by mhowlett** [comment]
`auto.offset.reset` determines the consumer start position if (and only if) there are no committed offsets for the partition for the group. are you clear on that? `auto.offset.reset` will be ignored if there are committed offsets.

**Comment by MichaelZhangCA** [comment]
yes, sir, I think we are clear about the group id and the committed offset.

Try a different group id each time and see how it works differently on Windows with "earliest" and "smallest"

**Comment by edenhill** [comment]
Can you reproduce this with the debug config property set to cgrp,topic,fetch and provide us with the logs?

**Comment by MichaelZhangCA** [comment]
Thanks @edenhill for pointing out the way to dig more... and @mhowlett, apologize for my inaccurate testing... 

I might rush out the testing after just upgrading my package to v1.0. To be straight forward, I cannot repeat the issue when I redo all the tests again. both "smallest" and "earliest" option works well when assigning a new group id. 

I might be confused by my messed environments. but **It's definitely my fault to confuse you guys and the lesson learned**, I would have tested more before posting these misleading info. :(
