### ISSUE TITLE
import of module 'cimpl' failed"

### ISSUE THREAD

**Issue by ingridlpwang** [confluentinc/confluent-kafka-python#553]
Description
===========
I am using AvroProducer to get ssl access, this is my code: 
producer = AvroProducer({'bootstrap.servers': ','.join(kafka_servers),
                                 'schema.registry.url': schema_registry,
                                 'security_protocol': 'SASL_PLAINTEXT',
                                 'sasl_mechanism': 'PLAIN',
                                 'sasl.kerberos.keytab':'/etc/security/keytabs/kafka.keytab',
                                 'sasl.kerberos.principle':'kafkaclient.com',
                                 'sasl.kerberos.service.name': 'kafka',
                                 'default.topic.config':
                                     {'auto.offset.reset': consumer_config['auto_offset_reset']}},
                                default_key_schema=value_schema, default_value_schema=value_schema)

I am getting an error message as: 
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f8b7d725128>'. Reason: 'PicklingError("Can't pickle <class 'cimpl.KafkaException'>: import of module 'cimpl' failed",)'

here is the content of confluent_kafka:
~/venv/lib/python3.5/site-packages/confluent_kafka]$ ls -l
total 440
4096 Mar 11 14:34 admin
4096 Mar 11 14:34 avro
         Mar 11 14:34 cimpl.cpython-35m-x86_64-linux-gnu.so
3338 Mar 11 14:34 __init__.py
4096 Mar 11 14:34 kafkatest
4096 Mar 11 14:34 __pycache__

I installed librdkafka-0.9.4. My OS is CentOS 7.5. It looks like everything installed properly but I am keep running into that erro. 
 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ingridlpwang** [comment]
confluent-kafka-python and librdkafka version (confluent_kafka.version() and confluent_kafka.libversion()):confluent_kafka.version()
('0.11.6', 722432)
>>> confluent_kafka.libversion()
('0.11.6', 722687)

 Apache Kafka broker version:0.10.1.2

 Operating system:CentOS 7.5

 Provide client logs (with 'debug': '..' as necessary):
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f8b7d725128>'. Reason: 'PicklingError("Can't pickle <class 'cimpl.KafkaException'>: import of module 'cimpl' failed",)'

**Comment by ingridlpwang** [comment]
now I export PATHONPATH to site-packages, and got the following errors:

Reason: 'PicklingError("Can't pickle <class 'cimpl.KafkaException'>: it's not the same object as cimpl.KafkaException",)'

**Comment by jaredthecoder** [comment]
I am also getting this error now in production with confluent-kafka-python.

```MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f4d58141f40>'. Reason: 'PicklingError("Can't pickle <class 'cimpl.KafkaException'>: import of module 'cimpl' failed")'```

This is with version 1.6.0.

**Comment by DanWertheimer** [comment]
@jaredthecoder did you manage to solve this?

**Comment by ygag-fayis** [comment]
> # Description
> I am using AvroProducer to get ssl access, this is my code: producer = AvroProducer({'bootstrap.servers': ','.join(kafka_servers), 'schema.registry.url': schema_registry, 'security_protocol': 'SASL_PLAINTEXT', 'sasl_mechanism': 'PLAIN', 'sasl.kerberos.keytab':'/etc/security/keytabs/kafka.keytab', 'sasl.kerberos.principle':'kafkaclient.com', 'sasl.kerberos.service.name': 'kafka', 'default.topic.config': {'auto.offset.reset': consumer_config['auto_offset_reset']}}, default_key_schema=value_schema, default_value_schema=value_schema)
> 
> I am getting an error message as: multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f8b7d725128>'. Reason: 'PicklingError("Can't pickle <class 'cimpl.KafkaException'>: import of module 'cimpl' failed",)'
> 
> here is the content of confluent_kafka: ~/venv/lib/python3.5/site-packages/confluent_kafka]$ ls -l total 440 4096 Mar 11 14:34 admin 4096 Mar 11 14:34 avro Mar 11 14:34 cimpl.cpython-35m-x86_64-linux-gnu.so 3338 Mar 11 14:34 **init**.py 4096 Mar 11 14:34 kafkatest 4096 Mar 11 14:34 **pycache**
> 
> I installed librdkafka-0.9.4. My OS is CentOS 7.5. It looks like everything installed properly but I am keep running into that erro.
> 
> # How to reproduce
> # Checklist
> Please provide the following information:
> 
> * [ ]  confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
> * [ ]  Apache Kafka broker version:
> * [ ]  Client configuration: `{...}`
> * [ ]  Operating system:
> * [ ]  Provide client logs (with `'debug': '..'` as necessary)
> * [ ]  Provide broker log excerpts
> * [ ]  Critical issue

Does any body has solution for this ?

**Comment by Hawool** [comment]
I'm also have same issue:
`Reason: ''PicklingError("Can\'t pickle <class \'cimpl.KafkaException\'>: import of module \'cimpl\' failed")''.`

**Comment by lewesche** [comment]
I'm also stuck on this, trying to build [v1.9.2](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v1.9.2)

**Comment by di2pro** [comment]
Did you guys manage to solve the issue? I have same problem with 2.4.0 on ubuntu 22.04 and can't find the way
