### ISSUE TITLE
Please add Kerberos support in pre-built Linux wheels

### ISSUE THREAD

**Issue by venthur** [confluentinc/confluent-kafka-python#554]
Description
===========

In the README it says:

> The pre-built Linux wheels do NOT contain SASL Kerberos/GSSAPI support. If you need SASL Kerberos/GSSAPI support you must install librdkafka and its dependencies using the repositories below and then build confluent-kafka using the command in the "Install from source from PyPi" section below.

Is there a reason why the pre-built Linux wheels come without Kerberos support? And is there any chance we can get Kerberos support in the Linux wheels as well?

**Comment by infecto** [comment]
I may be wrong but it could be something to do with the underlying libraries having C dependencies.

**Comment by jnavarro86** [comment]
+1

**Comment by edenhill** [comment]
Yes, librdkafka relies on cyrus-sasl and mit or heimdal kerberos libraries to provide GSSAPI Kerberos auth on unix-based platforms.
These libraries and plugins are not trivial to package into a wheel.
The workaround for now is to install librdkafka-dev from Confluent Yum/Apt repos and build the python client from source.
