### ISSUE TITLE
Support regex topic pattern in consumer group topic subscribe?

### ISSUE THREAD

**Issue by jeffwidman** [confluentinc/confluent-kafka-python#56]
I'm not seeing anything in the docs about how to pass a regex topic pattern for a consumer group subscription? 

My coworker checked a few months back and didn't see it, but in this morning's [blog post](https://www.confluent.io/blog/confluent-contributions-to-the-apache-kafka-client-ecosystem) @jkreps said the Python client has feature parity (I assume with Java) so did we just miss it?

We're redoing our internal Kafka python wrapper and trying to decide whether to bet on the Confluent python library or the Kafka-python library.

**Comment by edenhill** [comment]
The next version of librdkafka (0.9.2, or master) that will be released within a week (or so.., there is an 0.9.2-RC1 for the restless) provides proper support for regex subscriptions.

Any subscribe()d topic name that begins with "^" will be treated as a regexp and matched with the full set of topics in the cluster.

**Comment by jeffwidman** [comment]
Great. When this is released, it'd be nice to add an example of how to do this to the docs for this Python wrapper.

**Comment by jianbin-wei** [comment]
Does this support topics created in the future?

**Comment by edenhill** [comment]
@jianbin-wei Yes it does

@jeffwidman Absolutely, will see to it.

**Comment by edenhill** [comment]
Make sure to use librdkafka 0.9.2 or later (master) with regex subscriptions.

**Comment by jeffwidman** [comment]
The docstring update isn't appearing in the actual docs... I'm guessing Sphinx just needs to do a rebuild?

**Comment by edenhill** [comment]
By actual docs you mean http://docs.confluent.io/...?

This commit was added after v0.9.2 which the confluent docs are based on.

**Comment by jeffwidman** [comment]
That makes sense. I couldn't find a way to switch the version I was viewing to master so wasn't sure if I was just missing it or was an error.

**Comment by edenhill** [comment]
The syntax is standard .subscribe(topic_list) but prefix regexp-patterns with "^", e.g.:
 `c.subscribe(["fixedtopic", "^a_regex.*", "otherfixed", "^or_this_[0-9]"])`

**Comment by Kashyap23** [comment]
@edenhill I want to match a pattern which has changing pre-fix.
Eg :
```
testsetup-test-topic
prodsetup-test-topic
```
I tried the following 
```
c.subscribe(["*test-topic"])
```
But didnt get the message at the consumer.

Then
```
c.subscribe(["^*test-topic"])
```


But got the following error
```
KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to set subscription: Local: Invalid argument or configuration"}
```

Can you please help me in the above ?

Thanks in advance.

**Comment by edenhill** [comment]
`^.*-test-topic$`

**Comment by shubhang93** [comment]
> `^.*-test-topic$`

What if I want to use the `^` character to match the start of the string? Can I do this `^^.*-test-topic$`

**Comment by edenhill** [comment]
It behaves like a standard regexp as-is, `^` anchoring the beginning of the string.
`^a.*` - must start with `a`
`^.*a.*` - must contain `a`
