### ISSUE TITLE
Serialize/deSerialize function provided to Consumer/Producer instance

### ISSUE THREAD

**Issue by brunifrancesco** [confluentinc/confluent-kafka-python#560]
It seems there is no possibility to set up a value serializer/de-serializer when producing/consuming messages. 
Is this feature planned to be supported?

Thanks,
FB

**Comment by cricket007** [comment]
You would set them up before/after reading the messages to create/parse the bytes. 

e.g. I externalized the Avro serializer for the regular Producer class here - https://gist.github.com/cricket007/4db67f51fcaa02776340237762950b67#file-confluent-kafka-avroapp-py-L29-L35

**Comment by mhowlett** [comment]
there is a PR open for this #502.... which would probably be in already if i wasn't so intent on arguing over the details :-). it'll likely be in the next release. this feature has wider impact than it might first seem, so it'll pay for it to be well considered.

**Comment by rnpridgeon** [comment]
As @mhowlett mentioned this is on the roadmap. The PR stalled a bit while I worked on a few other projects but i'll be picking it back up to get it into the project soon. Thank you for your patience.
