### ISSUE TITLE
How to install the latest version?

### ISSUE THREAD

**Issue by marcosschroh** [confluentinc/confluent-kafka-python#561]
Description
===========
Hi,

thanks for this amazing library. I have noticed that the latestes version on pip is `confluent-kafka 0.11.6 ` which was released on Oct 24, 2018. Is there any plan to update it?

Thanks in advance!!

**Comment by cricket007** [comment]
That is the "latest" version. 

https://github.com/confluentinc/confluent-kafka-python/releases/tag/v0.11.6

If you want the current state of the code, I think you'd want to [build from source](https://github.com/confluentinc/confluent-kafka-python#build)

**Comment by marcosschroh** [comment]
Hi @cricket007 

Thanks for the reply!
