### ISSUE TITLE
Failed  when install avro kafka

### ISSUE THREAD

**Issue by xlionet** [confluentinc/confluent-kafka-python#565]
Description
===========
$ pip3 install confluent-kafka[avro]
zsh: no matches found: confluent-kafka[avro]

How to reproduce
================

Checklist
=========
Please provide the following information:
$ pip3 -V
pip 19.0.3 from ../py-dev/kafka/lib/python3.7/site-packages/pip (python 3.7)
 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by andreysfc** [comment]
Please change your shell to bash, I haven't check what is wrong with zsh but I think it is related to the shell and the path. @xlionet

**Comment by fheinrichs** [comment]
With zsh your command should be (this would also work for bash):

    pip install "confluent-kafka[avro]"

**Comment by rnpridgeon** [comment]
Thanks @fheinrichs , I confirmed this solution as well closing out the issue. 

```
pip install confluent-kafka[avro]
zsh: no matches found: confluent-kafka[avro]

pip install "confluent-kafka[avro]"
Looking in indexes: https://tools:****@nexus.confluent.io/repository/pypi/simple
Requirement already satisfied: confluent-kafka[avro] in /private/tmp/env/lib/python3.7/site-packages (1.1.0)
Requirement already satisfied: requests; extra == "avro" in /private/tmp/env/lib/python3.7/site-packages (from confluent-kafka[avro]) (2.22.0)
Requirement already satisfied: fastavro; extra == "avro" in /private/tmp/env/lib/python3.7/site-packages (from confluent-kafka[avro]) (0.22.3)
Requirement already satisfied: avro-python3; python_version > "3.0" and extra == "avro" in /private/tmp/env/lib/python3.7/site-packages (from confluent-kafka[avro]) (1.9.0)
Requirement already satisfied: certifi>=2017.4.17 in /private/tmp/env/lib/python3.7/site-packages (from requests; extra == "avro"->confluent-kafka[avro]) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /private/tmp/env/lib/python3.7/site-packages (from requests; extra == "avro"->confluent-kafka[avro]) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /private/tmp/env/lib/python3.7/site-packages (from requests; extra == "avro"->confluent-kafka[avro]) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /private/tmp/env/lib/python3.7/site-packages (from requests; extra == "avro"->confluent-kafka[avro]) (2.8)
```
