### ISSUE TITLE
Poducer report incorrect written offset

### ISSUE THREAD

**Issue by hrchu** [confluentinc/confluent-kafka-python#570]
Description
===========
I produce some messages and then consume them.
Producer reports produced message offsets by delivery callback, but the reported offset is not equal to what consumer read.

Sample output:
2019-04-04 14:37:49,679 INFO     % Message delivered to TestTopicReader [0] @ 27
2019-04-04 14:37:49,680 INFO     % Message delivered to TestTopicReader [0] @ 30
2019-04-04 14:37:49,681 INFO     % TestTopicReader [0] at offset 23 with key b'qq':
2019-04-04 14:37:49,682 INFO     % TestTopicReader [0] at offset 24 with key b'qq':

where 27, 30 != 23, 24

How to reproduce
================
Produce messages with delivery_callback:
```
def delivery_callback(err, msg):
        logger.info('%% Message delivered to %s [%d] @ %o\n' %
                    (msg.topic(), msg.partition(), msg.offset()))

p.produce(topic, value, 'qq', callback=delivery_callback, headers=headers)
p.flush(timeout)
```

and then consume messages by the loop
```
while True:
    msg = c.poll(timeout=1.0)
    if msg is None:
        continue
    if msg.error() is not None:
        raise KafkaException(msg.error())
    logger.info('%% %s [%d] at offset %d with key %s:\n' %
                (msg.topic(), msg.partition(), msg.offset(),
                 str(msg.key())))
```

Checklist
=========
confluent-kafka==0.11.4
kafka-clients-1.1.0-cp1.jar
ubuntu 16.04

**Comment by mhowlett** [comment]
you're printing out the offset in the delivery report as an octal. 0o27 = 2*8 + 7 = 23, so the offsets match.

**Comment by hrchu** [comment]
@mhowlett My freaking hero!!
