### ISSUE TITLE
'cimpl.Consumer' object has no attribute 'list_topics'

### ISSUE THREAD

**Issue by amrx101** [confluentinc/confluent-kafka-python#573]
Description
===========

`'cimpl.Consumer' object has no attribute 'list_topics'.`
Trying to list all topics using the method `consumer.list_topics()` as documented [here](https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.list_topics)

How to reproduce
================
Call `consumer.list_topics()`

Checklist
=========
Please provide the following information:

      python -c 'from confluent_kafka import version ; print(version())'
      ('0.11.0', 720896)

**Comment by edenhill** [comment]
You'll need at least version v0.11.5, but should use the latest release, v1.0.0
