### ISSUE TITLE
msg.headers none in the produce callback

### ISSUE THREAD

**Issue by russau** [confluentinc/confluent-kafka-python#574]
Description
===========

I don't see headers populated in the produce callback.  Am I making an incorrect assumption that this is provided in the callback, or is the library missing some functionality?  I haven't supplied all the checklist below as I might just be making an incorrect assumption.  I can supply more details if this isn't the expected behavior.

How to reproduce
================

``` python
from confluent_kafka import Producer
import pprint

p = Producer({'bootstrap.servers': 'kafka'})

def delivery_report(err, msg):
    pprint.pprint(msg.headers())  # always prints None

for data in ["larry", "moe", "curly"]:
    p.poll(0)
    p.produce('mytopic', data.encode('utf-8'), callback=delivery_report, headers=[('headerkey', 'headervalue')])

p.flush()
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.0.0
 - [x] Apache Kafka broker version: 2.0.0-cp1
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Ubuntu 18.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
looks like this hasn't been implemented yet:
https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/src/Producer.c#L147
https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/src/confluent_kafka.c#L662

**Comment by russau** [comment]
Thanks for the quick response! Is there somewhere I can track this as a feature?

**Comment by russau** [comment]
FYI - I just noticed this is in the documentation: 

> Currently message headers are not supported on the message returned to the callback. The msg.headers() will return None even if the original message had headers set.

https://docs.confluent.io/current/clients/confluent-kafka-python/index.html?highlight=admin#confluent_kafka.Producer.produce

**Comment by russau** [comment]
I'm asking on behalf of a customer. Maybe something unique is needed to correlate the callback to the original produce.  Let me ask and get back to you.

**Comment by edenhill** [comment]
@russau For such uses it is advised to use a bound produce() on_delivery callback, or using a lambda for the same.

**Comment by russau** [comment]
@edenhill just confirming, I now have a bound callback like this.  Do I have this correct?

``` python
import uuid
from confluent_kafka import Producer

class Event:
    def __init__(self, headers):
        self.headers = headers

    def callback(self, err, msg):
        print("Headers: %s Value: %s" % (self.headers, msg.value()))

p = Producer({'bootstrap.servers': 'kafka'})

for data in ["larry", "moe", "curly"]:
    p.poll(0)
    e = Event([('headerkey', str(uuid.uuid4()))])
    p.produce('mytopic',
              data.encode('utf-8'),
              headers=e.headers,
              callback=e.callback)
p.flush()
```

I am seeing the output I want..

``` bash
$ python3 main.py
Headers: [('headerkey', '8239c4d4-71e2-4dc5-bb20-c208bb5b66e6')] Value: b'larry'
Headers: [('headerkey', 'b41fb09a-0172-49f5-a034-4564026a66f3')] Value: b'moe'
Headers: [('headerkey', '6b278fa6-3a8b-4ee4-afd4-4e817907eb4c')] Value: b'curly'

$ kafkacat -b kafka -C -t mytopic -f 'Headers: %h: Value: %s\n'
Headers: headerkey=8239c4d4-71e2-4dc5-bb20-c208bb5b66e6: Value: larry
Headers: headerkey=b41fb09a-0172-49f5-a034-4564026a66f3: Value: moe
Headers: headerkey=6b278fa6-3a8b-4ee4-afd4-4e817907eb4c: Value: curly
% Reached end of topic mytopic [0] at offset 3
```

**Comment by edenhill** [comment]
Yep, looks good!

**Comment by mhowlett** [comment]
yep. i do find it a bit unfortunate that the message data is split between two places. For best out-of-the-box experience, I think we do really want to include headers (not just headers, all details of what is produced) in the delivery report. There are always going to be use cases where this is not enough, but it will be enough for many use cases.

Alternatively, below is how to do it with a closure (again more complex than I'd like). The outer lambda is necessary to capture the `hdrs` variable.

```
for data in ["larry", "moe", "curly"]:
    p.poll(0)
    hdrs = [('headerkey', str(uuid.uuid4()))]
    p.produce('mytopic',
        data.encode('utf-8'),
        headers=hdrs,
        callback=(lambda h: (lambda err, dr: print("Headers: %s Value %s" % (h, dr.value()))))(hdrs))
```

**Comment by russau** [comment]
Thanks Matt 🦘

Closing the issue.

**Comment by bodepd** [comment]
Just ran into this same issue and the fix works for me. To answer your question as to why I want the header here @edenhill 

the callback is sending errors to a DLQ, for my implementation, I want to be able to forward the following header information:

* trace id - storing my trace/span ids as headers for tracing
* retry_count - the DLQ is keeping track of how many times a message has been retried which is persisted and incremented as a header
* ERROR -  as an event fails to delivery, I'm appending the error messages to a header (just like the connectors do)
