### ISSUE TITLE
Broker does not support KIP-62 with kafka when using Kafka version 0.9.0

### ISSUE THREAD

**Issue by dvhh** [confluentinc/confluent-kafka-python#577]
Description
===========
Using kafka 0.9.0 with version 1.0.0 is breaking ( workaround is going back to 1.0.0rc1 )
```
%5|1554770547.333|MAXPOLL|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/506: Broker does not support KIP-62 (requires Apache Kafka >= v0.10.1.0): consumer configuration `max.poll.interval.ms` (300000) is effectively limited by `session.timeout.ms` (10000) with this broker version
Traceback (most recent call last):
  File "/usr/src/app/kafka/kafka_read_topic.py", line 109, in <module>
    main()
  File "/usr/src/app/kafka/kafka_read_topic.py", line 102, in main
    print(message.value().decode('utf-8'), file=sys.stdout)
BrokenPipeError: [Errno 32] Broken pipe
I0409 00:42:29.103595 32116 process.cpp:1068] Failed to accept socket: future discarded
```

How to reproduce
================
[kafka_read_topic.py.txt](https://github.com/confluentinc/confluent-kafka-python/files/3056829/kafka_read_topic.py.txt)
```
Consumer({
        'bootstrap.servers': brokers,
        'group.id': group,
        'auto.offset.reset': 'earliest',
        'api.version.request': False,
        'broker.version.fallback': '0.9.0'
    })
```
And start reading message

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 
('1.0.0', 1048576)
('1.0.0', 16777471)
 - [x] Apache Kafka broker version:
0.9.0
 - [ ] Client configuration: `{
        'bootstrap.servers': brokers,
        'group.id': group,
        'auto.offset.reset': 'earliest',
        'api.version.request': False,
        'broker.version.fallback': '0.9.0'
    }`
 - [x] Operating system: debian stretch

 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It is just a log message (at the NOTICE) level saying that your broker is too old to support max.poll.interval.ms, and that you need to set max.poll.interval.ms <= session.timeout.ms to avoid further log messages.

**Comment by dvhh** [comment]
`I0409 00:42:29.103595 32116 process.cpp:1068] Failed to accept socket: future discarded` indicate a failure

Additionally, I would like to point out that would mean that the default are not sane.

**Comment by edenhill** [comment]
`I0409 00:42:29.103595 32116 process.cpp:1068] Failed to accept socket: future discarded`

That error message is not from the Kafka client.

**Comment by edenhill** [comment]
The defaults are tailored for modern Kafka broker versions and match the java client counterpart.
