### ISSUE TITLE
what difference between consumer.poll() and consumer.consume()?

### ISSUE THREAD

**Issue by ybbiubiubiu** [confluentinc/confluent-kafka-python#580]
Description
===========

How to reproduce
================

ret = consumer.poll()
ret1 = consumer.consume(num_messages=500, timeout=2)
if consumer get result,ret will be a message,and ret1 will be some messages.

Questions:
Is there any other difference?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
poll is newer, use that. In the .net api, which is where I mainly like to hang out, we don't use the batch consume variant at all. i believe it pre-dates the 'new' consumer api (kafka 0.9) and excludes functionality for working with librdkafka's auto offset commit capability. IIRC there is talk of depreciating consume.

**Comment by bmoscon** [comment]
Personally I hope `consume` stays. I like being able to periodically call it and consume all the outstanding updates. Poll returning 1 at a time seems less useful for high volume applications (unless I'm missing something).

**Comment by mhowlett** [comment]
@bmoscon - behind the scenes messages in broker communication are still batched - poll/consume both read from an internal queue. the poll command abstracts the batching away from you. you can call poll with a timeout of 0, which will allow you to effectively read batches if your application requires this. I'm not completely sure what the per-call interop overhead is in python (it is probably true that delivering messages in batches from C -> python is probably going to be more performant) but I have benchmarked consumer.poll at ~400k msg/s (for small messages), so I think the overhead is likely pretty small and also whatever else you're likely to be doing in python is probably going to be the bottle neck.

**Comment by jeffwidman** [comment]
+1 for killing/deprecating `consume()` in favor of standardizing on `poll()`

**Comment by mkmoisen** [comment]
@mhowlett Do you happen to know why the confluent_kafka's poll api batches behind the scene instead of following the Java poll api? I think people assume that confluent_kafka does not batch because of this.

**Comment by edenhill** [comment]
Since messages are fetched in batches from the broker, all kafka consumers will do internal batching/queueing.

We've discussed pros and cons of an API that returns multiple messages but we're not convinced it is the best way to perform stream processing.
The max-time-to-wait for max-messages to accumulate and then return to the application is orthogonal to the actual constraint that limits the number of messages to process at once, which is the processing time. And since the processing time may vary (depending on the input message, system load, availability of aux systems, etc) it makes more sense to consume and process messages one by one until the overall processing time threshold is reached.

Example with a batch-consume API:

```python
producer.begin_transaction()

msgs = consumer.poll(cnt=100)

for msg in msgs:
  outmsg = process(msg)
  producer.produce(outmsg)

producer.send_offsets_to_transaction(...)
producer.commit_transaction()
```

Example with a single-message streaming API:
```python
producer.begin_transaction()

max_time = time.now() + max_total_processing_time
while time.now() < max_time:
  msg = consumer.poll()
  outmsg = process(msg)
  producer.produce(outmsg)

producer.send_offsets_to_transaction(...)
producer.commit_transaction()
```

If process() starts to run slow, in the batch example the entire transaction will be delayed until all 100 messages are processed, while in the non-batch one the transaction will finish on time with a fewer number of messages, allowing downstream consumers to still pick up on the new messages in time.

Additionally, if there is only 99 messages available in the consumed topics the batch example will block until timeout before processing, again delaying downstream consumers to pick up new messages.

**Comment by jizhilong** [comment]
I issued a benchmark, which shows the `consume` API has a better throughput.

the benchmark script:

```filename=benchmark.py
# coding: utf-8
import time
from confluent_kafka import Consumer
from confluent_kafka import TopicPartition

consumer = Consumer({'bootstrap.servers': 'kafka:9092', 'group.id': 'poll_vs_consume', 'auto.offset.reset': 'earliest'})
origin = TopicPartition('mytopic', 0, 0)
consumer.subscribe(['mytopic'])

for i in range(10):
    consumer.poll(1)

def consume_by_poll():
    consumer.seek(origin)
    count = 0
    while count < 50000:
        m = consumer.poll(1)
        if m is not None:
            count += 1
            
def consume_by_batch():
    consumer.seek(origin)
    count = 0
    while count < 50000:
        msgs = consumer.consume(500, timeout=1)
        count += len(msgs)
        

def measure(fname):
    start = time.time()
    exec('%s()' % fname)
    end = time.time()
    print('%s(): %sS' % (fname, (end-start)))


measure('consume_by_batch')
measure('consume_by_poll')
measure('consume_by_batch')
measure('consume_by_poll')

import cProfile

print('profiling batch')
cProfile.run('consume_by_batch()')

print('profiling poll')
cProfile.run('consume_by_poll()')
```

the result:

```
onsume_by_batch(): 0.05126619338989258S
consume_by_poll(): 1.768373966217041S
consume_by_batch(): 0.06994342803955078S
consume_by_poll(): 1.7566173076629639S
profiling batch
         205 function calls in 0.074 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.074    0.074 <string>:1(<module>)
        1    0.006    0.006    0.074    0.074 benchmark.py:21(consume_by_batch)
        1    0.000    0.000    0.074    0.074 {built-in method builtins.exec}
      100    0.001    0.000    0.001    0.000 {built-in method builtins.len}
      100    0.067    0.001    0.067    0.001 {method 'consume' of 'cimpl.Consumer' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'seek' of 'cimpl.Consumer' objects}


profiling poll
         50005 function calls in 2.567 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    2.567    2.567 <string>:1(<module>)
        1    0.457    0.457    2.567    2.567 benchmark.py:13(consume_by_poll)
        1    0.000    0.000    2.567    2.567 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
    50000    2.110    0.000    2.110    0.000 {method 'poll' of 'cimpl.Consumer' objects}
        1    0.000    0.000    0.000    0.000 {method 'seek' of 'cimpl.Consumer' objects}

```

**Comment by markns** [comment]
@jizhilong Using the `AvroConsumer`, I also saw a gigantic improvement in throughput using `consume` ... until I added deserialization (not handled automatically by `AvroConsumer`) back in. With deserialization, both methods have approximately equal throughput.

**Comment by aman-quartic** [comment]
@edenhill Can you pls expand on this
>  and excludes functionality for working with librdkafka's auto offset commit capability.

So when using `consume`, are offsets not automatically committed irrespective of the value of `auto.offset.reset`?
