### ISSUE TITLE
Not getting KafkaError._PARTITION_EOF in msg.error() after consumer.poll()

### ISSUE THREAD

**Issue by ordogfioka** [confluentinc/confluent-kafka-python#581]
Description
===========
In version 1.0.0 of confluent_kafka python package I can not receive the KafkaError._PARTITION_EOF (for example to check if I have reached the end of the stream). 
In version 0.11.6 I have got the "Consumer error" without any problem.

How to reproduce
================
from confluent_kafka import Consumer, TopicPartition, KafkaError
c = Consumer({'bootstrap.servers': 'server', 'group.id': 'test', 'enable.auto.commit': False,
              'auto.offset.reset': 'earliest'})
c.assign([TopicPartition('mondaymorning1.json', partition=0)])

while True:
  msg = c.poll(1.0)
  if msg is None:
    continue
  if msg.error():
    print("Consumer error: {}".format(msg.error()))
    break
    continue
  print('Received message: {}'.format(msg.value().decode('utf-8')))
c.close()

Checklist
=========
Please provide the following information:

 - [ 1.0.0 ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ - ] Apache Kafka broker version:
 - [ + ] Client configuration: `{...}`
 - [ ubuntu ] Operating system:
 - [ - ] Provide client logs (with `'debug': '..'` as necessary)
 - [ - ] Provide broker log excerpts
 - [ + ] Critical issue

**Comment by MichaelZhangCA** [comment]
Yes, I could repeat this on both Linux and Windows with package v1.0.

There is no _PARTITION_EOF error returned when using the same conf parameters. I assume there are some changes on the default behavior but didn't have the chance to dig yet.

**Comment by mhowlett** [comment]
yes, the default value for `enable.partition.eof` has changed from `true` to `false` between 0.11.6 and 1.0.

**Comment by MichaelZhangCA** [comment]
Thanks @mhowlett, the EOF partition message is back once set enable.partition.eof to True.

**Comment by ordogfioka** [comment]
@mhowlett Is it going to remain 'enable.partition.eof' false by default in the next releases or is just a bug and you will change back to true? Do you have any suggestion how to detect EOF without setting 'enable.partition.eof' to true?

**Comment by edenhill** [comment]
@ordogfioka See the release notes: https://github.com/confluentinc/confluent-kafka-python/releases/tag/v1.0.0

enable.partition.eof will remain disabled.
There is no way to detect EOF without enabling that property.

**Comment by ordogfioka** [comment]
@edenhill Thank you very much.
