### ISSUE TITLE
Idempotent Producer and retry count.

### ISSUE THREAD

**Issue by tamaroth** [confluentinc/confluent-kafka-python#585]
Description
===========

The idempotent producer silently requires that the retry count be set to at least one.

```
>>> import confluent_kafka as ck
>>> p = ck.Producer({
...  'bootstrap.servers': 'localhost:12345',
...  'enable.idempotence': True,
...  'retries': 0,
... })
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create producer: `retries` must be set >= 1 when `enable.idempotence` is true"}
```

 I could not find any mention anywhere that it is required. At your release statement [here](https://github.com/confluentinc/confluent-kafka-python/releases) one can read:

> There are no required application changes, but it is recommended to add
support for the newly introduced fatal errors that will be triggered when the idempotent producer encounters an unrecoverable error that would break the ordering or duplication guarantees.

I think it would be beneficial if that requirement was mentioned somewhere. 

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): version: `('1.0.0', 1048576)`, libversion: `('1.0.0', 16777471)`

**Comment by edenhill** [comment]
It is in the documentation for enable.idempotence:
https://github.com/edenhill/librdkafka/blame/master/CONFIGURATION.md#L105

Configuration changes are not considered application/code changes.

**Comment by tamaroth** [comment]
Ohh, thank you for pointing that out. I apologise for needlessly creating a ticket. I will close it.
