### ISSUE TITLE
How to get the last message produced

### ISSUE THREAD

**Issue by Fanduzi** [confluentinc/confluent-kafka-python#586]
Description
===========
I want the full message

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
i'm not sure exactly what you want to know, can you be more specific? (ideally provide some code showing what you're trying to do).

**Comment by Fanduzi** [comment]
> i'm not sure exactly what you want to know, can you be more specific? (ideally provide some code showing what you're trying to do).

If there is a topic A, I want to get the last message of this topic.

Same problem as this issue
Https://github.com/confluentinc/confluent-kafka-go/issues/252

**Comment by edenhill** [comment]
You will need look up the high watermark offset of the given partitions, using `get_watermark_offsets(partitions, cached=False)`, decrease each partitions `.offset` by 1, and then call `assign(partitions)` with the updated partitions.

**Comment by Fanduzi** [comment]
> You will need look up the high watermark offset of the given partitions, using `get_watermark_offsets(partitions, cached=False)`, decrease each partitions `.offset` by 1, and then call `assign(partitions)` with the updated partitions.

Thank you 😆 @edenhill @mhowlett
