### ISSUE TITLE
Broker: Request timed out

### ISSUE THREAD

**Issue by ybbiubiubiu** [confluentinc/confluent-kafka-python#587]
Description
===========

When I was using a high-level consumer, I registered the on_commit callback function. I now encountered an error that is Broker: Request timed out.
I want to ask:
1. What happens if this happens or what bad effects it will bring. Does this error result in a lost message?
2. What should I do with this kind of error. Adjust the kafka configuration or adjust the consumer's configuration parameters.

Looking forward to hearing from you。☺
Thanks。

How to reproduce
================

This is my call-back function of my consumer:

```
def _on_send_response(err, partations):
    """
    callback will be called when a commit request has succeeded or failed.
    :param args:
    :param kwargs:
    :return:
    """
    pt = partations[0]
    if isinstance(err, KafkaError):
        logger.error('Topic {} 偏移量 {} 提交异常: {}'.format(pt.topic,pt.offset,err.str()))
        raise err
        # aelog.error(err)
    else:
        # logger.info('Topic {} 偏移量 {} 提交成功'.format(pt.topic,pt.offset))
        pass
```
the config of my consumer:
```
     consumer = Consumer({'bootstrap.servers': "ip:port",
                         "group.id": name,
                         # 'enable.auto.commit':False,
                         "fetch.wait.max.ms": 500,
                         # 'fetch.min.bytes':1024 * 512,
                         'message.max.bytes':1024*1024*32,
                         "socket.keepalive.enable":True,
                         "log.connection.close": False,
                         "max.poll.interval.ms": 600000,
                         'session.timeout.ms': 300000,
                         "on_commit": _on_send_response,
                         "default.topic.config": {"auto.offset.reset": "latest"}
                         })

```
And the last is the config of kafka------server.properties
```
############################# Server Basics #############################

# The id of the broker. This must be set to a unique integer for each broker.
broker.id=110
message.max.bytes=33554432
request.timeout.ms=30000
broker.rack='RACK2'
auto.create.topics.enable=true
delete.topic.enable=true
##########################################################
```

Checklist
=========
Please provide the following information:

 - [ 0.11.6] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [2.1.0 ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [CentOS Linux release 7.6.1810 ] Operating system:
 - [ERROR: Topic mgr_zyx_logdata 偏移量 73145092 提交异常: Broker: Request timed out] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The broker failed to accept the commit request, possibly because there were not enough replicas available for the __consumer_offsets topic.

Since you are using auto commit the client will retry the commit after auto.commit.interval.ms, so you
dont really need to do anything.

**Comment by ybbiubiubiu** [comment]
> The broker failed to accept the commit request, possibly because there were not enough replicas available for the __consumer_offsets topic.
> 
> Since you are using auto commit the client will retry the commit after auto.commit.interval.ms, so you
> dont really need to do anything.

Thanks very much.  Get IT,
