### ISSUE TITLE
Unable to Decompress ZSTD broker compressed message

### ISSUE THREAD

**Issue by zelong430** [confluentinc/confluent-kafka-python#589]
Description
===========

The python client v1.0.0 is unable to decompress messages that compressed by broker. I recently set up the broker with configuration compression.type='zstd' which suppose to compress every message for every topic using ZSTD. Then, I set up a python producer and consumer to test the set up. The python producer is able to produce message to the broker but the consumer is unable to consume the message with Error 76. On the other hand, the JAVA based Kafka cli is able to read the same message fine. 

A following test is conducted. I remove the default compression.type setting from the broker. Then use the Python produce to explicitly compressed messages using "zstd". Now, the python consumer is able to decompress the message correctly.

These tests results confused me as 1) Seems like the client side 'zstd' library is fine as the producer is able to compress the message and consumer is able to decompress in the second test 2) the server-side(broker) 'zstd' compression seems also fine, as in the first the case the Java client is able to decompress the message

I open this Issue as I believe that there may be a potential bug either on the Python Kafka client or the Kafka broker itself. And I suggest contributor to take a look into it as this is not supposed behavior. 

How to reproduce
================
Configure a Kafka broker with compression.type='zstd'. Produce a message using Python client(without setting producer compression) and consume it using Python client. This should return Error 76.

Configure a Kafka broker without compression setting. Produce message using Python client(set producer compression to zstd) and consume it using Python client. This works fine for me.

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): both are V1.0.0 build from source code downloaded form Github release page
 - [X] Apache Kafka broker version: confluent-kafka-5.2
 - [ ] Client configuration: `{...}`
 - [X] Operating system: Ubuntu 18.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is a known issue in librdkafka which is being addressed in PR https://github.com/edenhill/librdkafka/pull/2183 .

The workaround for now is to leave/revert the broker topic configuration property to compression.type=producer

**Comment by zelong430** [comment]
Thanks, just to confirm when will this PR get released as stable version? probably in release 1.1.0 or something?

Also, the reason that Java CLI works for both case is that it doesn't use the librdkafka as Python does. Correct?

**Comment by edenhill** [comment]
Yeah, we're aiming to include that fix in v1.1.0 (in a couple of months).

You are correct about the CLI.

**Comment by rnpridgeon** [comment]
Update: v1.1.0 is out but the fix for librdkafka is still pending. Looks like we are shooting for v1.2.0 (after the summer).

**Comment by BrysonsDadRocks** [comment]
Where are we at with this issue? Switching from gzip to zstd will help reduce our CPU costs and maybe squeak out a bit more performance on data storage. Any ideas on a work-around in the meantime?

**Comment by rnpridgeon** [comment]
Looks like the PR is still under review although appears to have stagnated a bit. It's marked as a 1.3.0 milestone(just released) but it doesn't not appear to be in yet. It looks like the author has picked back up though as they chimed in on Matt's review notes 12 days ago. 

You can monitor edenhill/librdkafka#2183 for progress. Once its in librdkafka we can build the python wrapper on top the release that includes the fix.

**Comment by lorines** [comment]
Is the decompression on the consumer side automatically handled?
