### ISSUE TITLE
Avro Consumer not supporting consume?

### ISSUE THREAD

**Issue by BiggieSmells** [confluentinc/confluent-kafka-python#591]
Description
===========
Avro Consumer not supporting consume?   I was trying to convert my poll (single message) to use a batched approach but see that Consume isn't supported by the Avro Consumer.   While searching around in here I see people thinking that the consume may be deprecated but isn't that the pattern I should be using?   

I was trying to convert to this with the idea of configuring batchsize to adjust how many msgs i can stand to have replayed.

Consume batch loop
----for each msg in batch loop
--------do something
--------produce msg to next topic
----flush producer      
----commit() offset of consumer 

If not can someone link a pattern that does at lest once while trying to keep repeats to low?  I don't want to go thru the effort of changing this if its going away anyway.
  
How to reproduce
================
Create an instance of the AvroConsumer and call consume on it.   The msg.value() and msg.key() both return non-decode values.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
yes, we're considering depreciating the `consume` method.

typically, the best pattern for at-least once processing is to leave `enable.auto.commit` as `true` but set the `enable.auto.offset.store` config property to `false` then call the `store_offsets` method after successful processing of every consumed message. this avoids the synchronous commit (at the expense of possibly reprocessing more messages than you have to in the event of failure).

**Comment by BiggieSmells** [comment]
The application in question is processes the polled/consumed messages and producing them to another topic.   The culmination of the processing is the produced message.  I can't allow offsets of the consume/poll to be committed till the produce is 100% completed(flushed).   Currently its doing this after each message which every here knows is a terrible idea as its really slow.  Any replacement solution I use needs to account for a flush like action somewhere.

Consume seemed like the way to easily batch these.   The batch size is how far ahead one is willing to run without a flush/commit.   The really cool thing about commit() is that it automagically remembers all the messages that were consumed and does the appropriate commit across all topics/partitions that were part of the consume(at least thats how the description of consume reads to me)

**Comment by rnpridgeon** [comment]
If you are using the default value for `enable.auto.offset.store` which is true and calling `commit` with no arguments you are actually stating the entire batch has been committed. Checkout the librdkafka wiki below which explains offset management. 

https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management

I suggest you use the setup described by @mhowlett which should give you the best results. You can call `store_offsets` in your producer callback upon receipt of a successful delivery report.
