### ISSUE TITLE
no module named concurrent.futures

### ISSUE THREAD

**Issue by adjkldd** [confluentinc/confluent-kafka-python#592]
Description
===========
when using [adminapi](https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/adminapi.py) to create partitions, python2.7 complains :

```
ImportError: No module named concurrent.futures
```  

How to reproduce
================
run the example code. Google tells me concurrent.futures is a python3.2 module. However, I am using confluent_kafka-1.0.0-py2.7-linux-x86_64.whl

Checklist
=========
Please provide the following information:

 - python version 2.7
- confluent_kafka version (1.0.0, 1048576)
- librdkafka version 1.0.0

**Comment by lithammer** [comment]
On Python 2, you can install [futures](https://pypi.org/project/futures/) (a backport of `concurrent.futures` to Python 2) to get around this.

**Comment by rnpridgeon** [comment]
Note if you are running on  python 2.7 you will also need `enum34` for the adminapi to work. If you decide to use the AvroConsumer and AvroProducer you will need to install `requests`.
