### ISSUE TITLE
Question: Metadata update

### ISSUE THREAD

**Issue by maverickagm** [confluentinc/confluent-kafka-python#594]
Description
===========
I'm reading through the code but can't seem to find the answer. Is it possible to refresh a consumer's metadata explicitly, or am I reliant on the metadata.max.age.ms configuration property?

**Comment by mhowlett** [comment]
`list_topics` (with `None` as the topic) will do this. behind the scenes, this method calls `rd_kafka_metadata`. When parsing the response of a metadata request - whether user triggered or not - librdkafka's internal info is updated (see `rd_kafka_parse_Metadata` in librdkafka).

why do you want to do this explicitly? - metadata will be refreshed automatically as required, either periodically or in response to a problem.

**Comment by maverickagm** [comment]
Thanks for the response! That clears up a few things. I'm not yet sure if I have to do this explicitly. When I do a rolling restart of my cluster (waiting for ISRs to be synced in between each broker), some of my consumers encounter a NOT_LEADER_FOR_PARTITION error. I tried sleeping for 2 seconds and re-polling, but they continue to get this error for over 10 minutes. I was wondering if they've cached partition leader information for the half-minute a broker was down and it's partition leaders were transferred over.

**Comment by mhowlett** [comment]
if you set the `debug` config property to `cgrp,fetch,metadata` (or `all` - maybe i'm missing a useful context in that list) that will tell you more about what's going on, including metadata requests.

**Comment by jeffwidman** [comment]
This can be useful in a test harness. 

For example, I have a test that checks whether regex-based subscription is working. So the test sets up a consumer, then creates the topic, and then checks the consumer's assignment. You want to order it that way to prove that regex-based picks up new topics that are created after the consumer is already working.

Rather than sleeping and waiting for the consumer's metadata to refresh, I instead trigger a metadata refresh immediately after creating the topic.

**Comment by maverickagm** [comment]
I recently ran into this scenario again. It's difficult to catch. My client process is as follows:
1) Get message
2) Process message
3) call store_offsets() to commit locally
4) autocommit is set to run every 3 seconds

If a partition leader changes in between calling store_offsets() and committing the offset to the broker, that the partition leader information cached in the local offset store becomes out of date? I had a look at librdkafka and noticed references to partition leaders (rktp_leader and rktp_leader_id) within a topic-partiton structure:
```
/**
 * Topic + Partition combination
 */
struct rd_kafka_toppar_s { /* rd_kafka_toppar_t */
	TAILQ_ENTRY(rd_kafka_toppar_s) rktp_rklink;  /* rd_kafka_t link */
	TAILQ_ENTRY(rd_kafka_toppar_s) rktp_rkblink; /* rd_kafka_broker_t link*/
        CIRCLEQ_ENTRY(rd_kafka_toppar_s) rktp_activelink; /* rkb_active_toppars */
	TAILQ_ENTRY(rd_kafka_toppar_s) rktp_rktlink; /* rd_kafka_itopic_t link*/
        TAILQ_ENTRY(rd_kafka_toppar_s) rktp_cgrplink;/* rd_kafka_cgrp_t link */
        rd_kafka_itopic_t       *rktp_rkt;
        shptr_rd_kafka_itopic_t *rktp_s_rkt;  /* shared pointer for rktp_rkt */
	int32_t            rktp_partition;
        //LOCK: toppar_lock() + topic_wrlock()
        //LOCK: .. in partition_available()
        int32_t            rktp_leader_id;   /**< Current leader broker id.
                                              *   This is updated directly
                                              *   from metadata. */
	rd_kafka_broker_t *rktp_leader;      /**< Current leader broker
                                              *   This updated asynchronously
                                              *   by issuing JOIN op to
                                              *   broker thread, so be careful
                                              *   in using this since it
                                              *   may lag. */
        rd_kafka_broker_t *rktp_next_leader; /**< Next leader broker after
                                              *   async migration op. */
	rd_refcnt_t        rktp_refcnt;
	mtx_t              rktp_lock;
```
I'm not sure if these values get updated with new metadata when offset_store() has already been called.

My consumer catches NOT_LEADER_FOR_PARTITION errors then handles them by calling list_topics() (to update the client metadata), but the client just spins in a loop getting NOT_LEADER_FOR_PARTITION errors and fetching metadata. However, restarting the process calls subscribe() and this fixes the problem.
