### ISSUE TITLE
Implement API for operating on consumer groups

### ISSUE THREAD

**Issue by eshepelyuk** [confluentinc/confluent-kafka-python#595]
Description
===========

Java has API  a class `kafka.admin.ConsumerGroupCommand` which allows to delete a consumer group and other operations upon consumer groups

e.g. it can be used from shell script

    $ kafka-consumer-groups.sh --bootstrap-server .... --delete my_consumer_group

It would be great if this functionality could be duplicated in python API as well.

**Comment by mhowlett** [comment]
thanks for the +1, we agree.

**Comment by shreesha15** [comment]
this is required

**Comment by edenhill** [comment]
We'll be releasing DeleteGroups, DeleteRecords and DeleteConsumerGroupOffsets in v1.6.0 which is scheduled in a month.
