### ISSUE TITLE
Kafka consumer performance issues inside a single process

### ISSUE THREAD

**Issue by skmatti** [confluentinc/confluent-kafka-python#597]
Description
===========
For our use case, we need to read messages from a Kafka topic in batches. Each batch is defined by a partition and an interval of starting and ending offsets as shown the script below. These batches are then executed in a thread pool or process pool to consume the messages between the starting offset and last offset of that interval. 

The script for generating batches and consuming the messages using ProcesPoolExecutor/ ThreadPoolExecutor:
```
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from time import time
import random

import confluent_kafka as ck

def r(v):
        part_no, low, high = v
        consume_batch_size = 10000
        
        topic = 'topic-1'
        conf = {
            'bootstrap.servers': 'localhost:9092',
            'group.id': 'my-group'
        }
        
        c = ck.Consumer(conf)
        tp = ck.TopicPartition(topic, part_no, low)
        c.assign([tp])
        
        start_offset = low
        end_offset = low

        while high > low:
            curr_high = min(low + consume_batch_size, high)
            for m in c.consume(curr_high-low):
                end_offset = max(end_offset, m.offset())
                m.value()
            low = curr_high
            
        return "{}-{}".format(start_offset , end_offset)

def main():
    topic = 'topic-1'
    batch_size = 100000
    consumers = {}
    
    # to define the initial order of batches
    shuffle = False
    interleave = False
    if interleave:
        shuffle = False

    conf = {
        'bootstrap.servers': 'localhost:9092',
        'group.id': 'my-group'
    }

    start = time()
    master_consumer = ck.Consumer(conf)
    parts_metadata = master_consumer.list_topics(topic).topics[topic].partitions

    total_offset = [0]
                
    parts = []
    for part_no in range(len(parts_metadata)):
        low, high = master_consumer.get_watermark_offsets(ck.TopicPartition(topic, part_no))
        index = part_no
        while high > low:
            curr_high = min(low + batch_size, high)
            if interleave:
                parts.insert(index, (part_no, low, curr_high))
                index += (part_no+1)
            else:
                parts.append((part_no, low, curr_high))
            low = curr_high
    print('Partition set count:', len(parts))
    
    if shuffle:
        random.shuffle(parts)

    futures = []
    with ThreadPoolExecutor(max_workers=len(parts_metadata)) as e:
        for p in parts:
            futures.append(e.submit(r, p))
    
    [f.result() for f in futures]        
            
    took = time() - start
    count = sum(x[2]-x[1] for x in parts)
    rate = (count / 1024) / took
    print('read:', count, 'msgs', 1024 * count, 'b', 'in:', took, 's', 'rate:', rate, 'mb/s')

if __name__ == '__main__':
    main()
```

I need to vary `consume_batch_size`(Number of messages to be consumed using `consumer.consume` method) from the above script to get maximum throughput in each case. Below are maximum throughput in both cases and their corresponding `consume_batch_size`.

**Results:**
With ProcessPoolExecutor (consume_batch_size = 100000):
`read: 22806000 msgs 23353344000 b in: 14.148 s rate: 1574.17 mb/s`
With ThreadPoolExecutor (consume_batch_size = 10000):
`read: 22806000 msgs 23353344000 b in: 59.965 s rate: 371.409 mb/s`

I am trying to understand the reason behind the drop in performance using a single process. Is it because of Python GIL? or some Kafka consumer configuration issue?.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version(1.0.0)` and `confluent_kafka.libversion(1.0.0)`):
 - [x] Apache Kafka broker version: 2.2.0
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is most likely due to the GIL.
The Python interpreter will only execute one single Python thread at the time, so there is really no benefit of processing parallelism.

**Comment by mrocklin** [comment]
Perhaps it would make sense to release the GIL around expensive C calls that don't touch Python objects.  This is fairly common in other data-intensive libraries like numpy, pandas, and scikit-learn.  

@edenhill (or anyone else who is familiar with the confluent-kafka-python codebase) are there a few obvious places where this library calls into some other non-python library (presumably `librdkafka`) for a non-trivial amount of time?  If so then we can probably safely release the GIL around those calls to improve performance here?

To be clear, I'm not expecting the maintainers of this library to do this work, I'm just asking if such places exist and pointers as to where they might be.  I suspect that I can find someone to do the actual GIL-releasing if folks here aren't familiar with the process.

**Comment by edenhill** [comment]
We already do release the GIL for any blocking C call, in which case the python interpreter can switch execution to another thread.
But **python** code will not execute in parallel.

**Comment by edenhill** [comment]
CallState_begin() release the GIL, CallState_end() re-acquires it.
Example for Consumer.consume() here:
https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/src/Consumer.c#L938-L947

**Comment by mrocklin** [comment]
Ah, I had assumed that most of the call time in this library would be taken up by fast C code rather than Python code, and so thread-based parallelism would be effective. Given your previous statement though, and @skmatti 's experience above, it sounds like this library is spending most of its time in Python code rather than in `librdkafka` then.  Is that correct?

**Comment by edenhill** [comment]
I don't believe that's true, for a consumer consuming messages from a high-rate topic, there will be virtually no delay in the C consume() call since there will always be messages available (no wait time).

**Comment by jsmaupin** [comment]
Could we be hitting some sort of concurrency bottleneck here while calling `consume(...)` on multiple instances of the consumer object concurrently?
```python
for m in c.consume(curr_high-low)
```

**Comment by edenhill** [comment]
Nothing obvious comes to mind.
Have you tried running a Python profiler to see where it is spending its time?

**Comment by mrocklin** [comment]
I had this pending in my comment box :)

It might be interesting to profile a fully sequential (single-threaded) version of the code snippet above under the cProfile module and figure out what's taking time.  That might help to identify what's actually taking up time.  *Hopefully* this highlights some `librdkafka` function call that isn't GIL-released, but it sounds like it's more likely some Python loop

**Comment by mrocklin** [comment]
@skmatti do you have time to try profiling a sequential version?

Personally, I usually do this with the following:

```
python -m cProfile -o profile.out myscript.py

# I like using snakeviz to visualize cProfile outputs
pip install snakeviz
snakeviz profile.out
```

**Comment by skmatti** [comment]
Yeah I do, I can try this out and post the results here.

**Comment by skmatti** [comment]
So, I replaced
```
futures = []
    with ThreadPoolExecutor(max_workers=len(parts_metadata)) as e:
        for p in parts:
            futures.append(e.submit(r, p))
    
    [f.result() for f in futures]  
```
with 
```
for part in parts:
        print(r(part))
```
to make it sequential. Also, the name of the script is `kafka_perf_test`. 

Below are the top10 contributors to the execution time:
![image](https://user-images.githubusercontent.com/22752968/58132295-c0898800-7bd5-11e9-8813-36ed24494b17.png)

**Comment by mrocklin** [comment]
I'm guessing that that method is here:

https://github.com/confluentinc/confluent-kafka-python/blob/bff6ed2b47162697de59aa3fb1160034716536e5/confluent_kafka/src/Consumer.c#L911-L978

So from @edenhill 's comments the guess is that we're likely spending much more time at the bottom of this function creating all of the Python bytes objects than in the `rd_kafka_consume_batch_queue` call.

**Comment by mrocklin** [comment]
If we wanted to pursue this further we might try to figure out where within that function we're spending the most time.  One straightforward way to accomplish this would be to put in manual timers and rebuild this library.  I suspect that there are also low-level profilers that we could use (though I'll admit that I don't know much here).

**Comment by edenhill** [comment]
Object creation is unfortunately a really expensive task in Python, that's why we are using accessor methods on the Message object to delay object creation until it is actually wanted.

How many messages are you typically getting back for each consume() call?
You could try setting the num_messages parameter to 1 to see if the profiling numbers change.

**Comment by skmatti** [comment]
You mean to use `consumer.poll` instead of `consumer.consume`?. We typically read 10k messages in one go. This seems to give the best throughput. I can try it once again to see if this changes.

**Comment by skmatti** [comment]
No so much change by reading one messages at a time.
![image](https://user-images.githubusercontent.com/22752968/58208513-bc26a300-7c99-11e9-904f-6e522fe12139.png)
I will try using a low-level profiler to pin down the exact line in `consume` method like @mrocklin suggested.

**Comment by mrocklin** [comment]
> I will try using a low-level profiler to pin down the exact line in consume method like @mrocklin suggested.

Good luck!  I'll be curious to know what you use here.  I don't have much experience here.

**Comment by mrocklin** [comment]
> Object creation is unfortunately a really expensive task in Python, that's why we are using accessor methods on the Message object to delay object creation until it is actually wanted.

@edenhill Do you have thoughts on accepting a delimiter from the user and using that to join all of the values of a batch together on the C side before passing back to Python?  In @skmatti 's case he immediately joins his 10k Python bytes objects back into a single bytes object and then passes that to a bulk parsing function.  In this case (and I imagine others) it's unfortunate that we spend so much time creating and then destroying Python objects.

```python
batch = consumer.consume(num_messages=10000, delimiter='\n')
```

**Comment by edenhill** [comment]
Using in-data delimiters is fragile, requires escaping and is generally a mess.
It would be better to have a binary TLV-based format, e.g.:
```
  u8 MSG_FIELD_TYPE
  i32 LENGTH
  u8 DATA[LENGTH]
```

While this wouldn't be hard to do, it does seem to be a bit of a niche use-case, effectively providing a binary protocol between the client and application.

What kind of data is it that you are passing, and how is it parsed?

**Comment by mrocklin** [comment]
> Using in-data delimiters is fragile, requires escaping and is generally a mess.

Totally understood.  

I suspect that a common case here is line-delimited JSON:

```python
messages = read_batch()
pandas.read_json('\n'.join(messages))
```

One nice thing about the delimiter keyword is that they're opting into it and choosing their own delimitere, so the responsibility to keep things clean is on them rather than this library.

**Comment by skmatti** [comment]
We are passing binary encoded Json strings. The decoded batch of strings are concatenated with new line delimiter(`\n`) and passed to `Pandas.read_json`.

**Comment by mrocklin** [comment]
To summarise things here.  I think that there are two things to do:

1.  Decide if passing in a user defined delimiter, like `\n` is in scope for this library
2.  Do some low-level profiling to isolate where the slowdown is coming from within the consume function.

**Comment by chinmaychandak** [comment]
I added manual timers in the `static PyObject *Consumer_consume()` method — measuring the time taken by `rd_kafka_consume_batch_queue()` and by the loop for creating PyObjects. 

I found that, on an average, ~20% of the time is spent creating Python objects. Since PyObject creation is sequential, this is a considerable bottleneck on the consumer side.

I am trying out the delimiter-based (`\n`) approach @mrocklin suggested, by basically appending the payload of a maximum of 1000 `rd_kafka_message_t` objects to a new `rd_kafka_message_t` object, and then creating a single PyObject from this "bulk" obejct.

My consume() function now looks like this: 

```
static PyObject *Consumer_consume(Handle *self, PyObject *args, PyObject *kwargs) {

        unsigned int num_messages = 1;
        double tmout = -1.0f;
        static char *kws[] = { "num_messages", "timeout", NULL };
        rd_kafka_message_t **rkmessages;
        PyObject *msglist;
        rd_kafka_queue_t *rkqu = self->u.Consumer.rkqu;
        CallState cs;
        Py_ssize_t i, n;

        if (!self->rk) {
                PyErr_SetString(PyExc_RuntimeError,
                                "Consumer closed");
                return NULL;
        }

        if (!PyArg_ParseTupleAndKeywords(args, kwargs, "|Id", kws,
					 &num_messages, &tmout))
		return NULL;

        if (num_messages > 1000000) {
                PyErr_SetString(PyExc_ValueError,
                                "num_messages must be between 0 and 1000000 (1M)");
                return NULL;
        }

        CallState_begin(self, &cs);

        rkmessages = malloc(num_messages * sizeof(rd_kafka_message_t *));

        n = (Py_ssize_t)rd_kafka_consume_batch_queue(rkqu,
                tmout >= 0 ? (int)(tmout * 1000.0f) : -1,
                rkmessages,
                num_messages);

        if (!CallState_end(self, &cs)) {
                for (i = 0; i < n; i++) {
                        rd_kafka_message_destroy(rkmessages[i]);
                }
                free(rkmessages);
                return NULL;
        }

        if (n < 0) {
                free(rkmessages);
                cfl_PyErr_Format(rd_kafka_last_error(),
                                 "%s", rd_kafka_err2str(rd_kafka_last_error()));
                return NULL;
        }

/*  
    ****************
ALL CHANGES AFTER THIS LINE
    **************** 
*/
        char *delimiter = "\n";
        int maxMessageCharacters = 5000;
        int maxNumberOfMessages = 1000;
        int num_PyObjects = (int)ceil(n/maxNumberOfMessages);

        msglist = PyList_New(num_PyObjects);

        for (i = 0; i < num_PyObjects; i++) {

            rd_kafka_message_t bulk;
            bulk.payload = (char*)malloc(maxNumberOfMessages*maxMessageCharacters*sizeof(char));
            strcat(bulk.payload, (char*)rkmessages[maxNumberOfMessages*i]->payload);

            for(int j = maxNumberOfMessages*i+1; j < MIN(maxNumberOfMessages*(i+1),n); j++) {
                strcat(bulk.payload, delimiter);
                strcat(bulk.payload, (char*)rkmessages[j]->payload);
            }
            printf("Bulk payload length: %d\n", (int)strlen(bulk.payload));

            PyObject *msgobj = Message_new0(self, &bulk);

            PyObject *tempHeader = Message_new0(self, rkmessages[0]);

#ifdef RD_KAFKA_V_HEADERS
// Have to detach headers outside Message_new0 because it declares the
// rk message as a const

                for(int j = maxNumberOfMessages*i; j < MIN(maxNumberOfMessages*(i+1),n); j++) {
                    rd_kafka_message_detach_headers(rkmessages[j], &((Message *)tempHeader)->c_headers);
                }

#endif
                PyList_SET_ITEM(msglist, i, msgobj);

                for(int j = maxNumberOfMessages*i; j < MIN(maxNumberOfMessages*(i+1),n); j++) {
                    rd_kafka_message_destroy(rkmessages[j]);
                }

        }
        free(rkmessages);

        return msglist;
}
```

However, I encounter a segmentation fault with the multi-threaded consumer and an error with the multi-process consumer: 
`concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.` 

@edenhill, could you take a look and please tell me what I'm missing out?
