### ISSUE TITLE
No module named avro

### ISSUE THREAD

**Issue by tulasigss** [confluentinc/confluent-kafka-python#600]
Description
===========
**i am a new bee for confluent kafka and the following error pops up at this line in python code as below: not sure what is missing**
from confluent_kafka.avro import AvroProducer, CachedSchemaRegistryClient
error: 
Traceback (most recent call last):
  File "/Producers/ConfluentPRoducer.py", line 3, in <module>
    from confluent_kafka.avro.serializer.message_serializer import MessageSerializer as AvroSerde
  File "\FirstKafkaApp\venv\lib\site-packages\confluent_kafka\avro\__init__.py", line 13, in <module>
    from confluent_kafka.avro.serializer.message_serializer import MessageSerializer
  File "\FirstKafkaApp\venv\lib\site-packages\confluent_kafka\avro\serializer\message_serializer.py", line 28, in <module>
    import avro
ModuleNotFoundError: No module named 'avro'

**-Ran the following pip and requirements are already satisfied** 
C:\Windows\System32>pip install confluent-kafka[avro]
Requirement already satisfied: confluent-kafka[avro] in c:\programdata\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: requests; extra == "avro" in c:\programdata\anaconda3\lib\site-packages (from confluent-kafka[avro]) (2.18.4)
Collecting fastavro; extra == "avro" (from confluent-kafka[avro])
  Downloading https://files.pythonhosted.org/packages/66/9d/18dee49e551e1c92c6f7d792ed552f232eb2d707ef0829cec37e719e682f/fastavro-0.21.23-cp36-cp36m-win_amd64.whl (306kB)
    100% |████████████████████████████████| 307kB 730kB/s
Requirement already satisfied: avro-python3; extra == "avro" in c:\programdata\anaconda3\lib\site-packages (from confluent-kafka[avro]) (1.8.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests; extra == "avro"->confluent-kafka[avro]) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests; extra == "avro"->confluent-kafka[avro]) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests; extra == "avro"->confluent-kafka[avro]) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests; extra == "avro"->confluent-kafka[avro]) (2018.4.16)
distributed 1.21.8 requires msgpack, which is not installed.
Installing collected packages: fastavro
  The script fastavro.exe is installed in 'C:\ProgramData\Anaconda3\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed fastavro-0.21.23
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

How to reproduce
================

Checklist
=========
Please provide the following information:
using Confluent 5.2
was able to publish messages using confluent-kafka-python libraries

**Comment by tulasigss** [comment]
can someone please highlight what is missing here?

**Comment by Arun211** [comment]
I am too facing this issue when using AvroProducer. Issue persists even after installing confluent-kafka[avro]

> pip3 install confluent-kafka[avro]

`Traceback (most recent call last):
  File "test_kafka_avro.py", line 6, in <module>
    from confluent_kafka import avro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/confluent_kafka/avro/__init__.py", line 13, in <module>
    from confluent_kafka.avro.serializer.message_serializer import MessageSerializer
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 29, in <module>
    import avro.io
ModuleNotFoundError: No module named 'avro.io'`

**Comment by edenhill** [comment]
The `avro` PyPi package is for python2 (but is still installable on python3 unfortunately), for python3 you will need to install the `avro-python3` PyPi package and remove the `avro` package.
Also make sure to use the latest version of avro-python3.
So:
```
 $ pip uninstall -y avro  # repeat until all versions are uninstalll
 $ pip install -U avro-python3
```
