### ISSUE TITLE
How to config sasl_plain related properties in consumer

### ISSUE THREAD

**Issue by clairexiayanping** [confluentinc/confluent-kafka-python#604]
Description
===========
c = Consumer({
    'bootstrap.servers': mybroker,
    'group.id': 'mygroup',
    'client.id': 'python_client',
    'sasl_mechanism' : 'PLAIN',
    'security_protocol' : 'SASL_PLAINTEXT',
    'sasl_plain_username' : 'xxx',
    'sasl_plain_password' : 'xxx',
    'default.topic.config': {
    'auto.offset.reset': 'smallest'
    }
})

The consumer config as above. When I request, got error:
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "sasl_mechanism""}

How to config sasl_plain related properties in consumer.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by clairexiayanping** [comment]
@edenhill could you help anwser this question?

**Comment by edenhill** [comment]
Use dots, not underscores.
sasl.username

 https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by clairexiayanping** [comment]
Thank you. It works
