### ISSUE TITLE
consumer received PARTITION_EOF error while there is data to be consumed in kafka

### ISSUE THREAD

**Issue by zealot-shin** [confluentinc/confluent-kafka-python#605]
Description
===========
I used confluent_kafka.Consumer to initiate a kafka consumer, before reached the end of the specified partition of topic while in the loop of client.poll(2), all things ran normal.
but when the consumer met KafkaError._PARTITION_EOF, the consumer became weird.
poll() method constantly returned partition_eof error, however, some data can be consumed, while more and more data accumulated in kafka. 
As a result , consumer can never catch up with the newest data in kafka anymore.

How to reproduce
================
restart my program.
wait until the consumer receive partition_eof error.
delay  appears again.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
confluent_kafka.version():
('0.11.0', 720896)
confluent_kafka.libversion():
('0.11.4', 722175)
 - [ ] Apache Kafka broker version:  2.12-0.10.2.1
 - [ ] Client configuration: `{...}` 
conf  {
'bootstrap.servers': self.args["bootstrap.servers"],
            'client.id': self.args["client.id"],
            'group.id': self.args["group.id"],
            'session.timeout.ms': 20000,
            'auto.commit.interval.ms': 5000,
            "on_commit": self.on_commit,
            'default.topic.config': {
                'auto.offset.reset': self.args["offset.reset"],
                'enable.auto.commit': "true",
                'offset.store.method': 'broker',
                'offset.store.sync.interval.ms': 1000,
                'request.timeout.ms': 5000}
}
 - [ ] Operating system: Red Hat 7.4(Maipo)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
......
[DEBUG] KafkaError{code=_PARTITION_EOF, val=-191,str="Broker: No more messages"}
TOPIC [0] at offset 27574281
......

however , the real bigest offset is like 27581234, always bigger than consumer gets.
and as time goes by, the difference also increase. Thus data delay appears.

 - [ ] Provide broker log excerpts
 - [ ] Critical issue
unreasonable partition_eof error caused data delay

**Comment by edenhill** [comment]
Please upgrade to v1.0.0, v0.11.0 is very old

**Comment by zealot-shin** [comment]
> Please upgrade to v1.0.0, v0.11.0 is very old

before this, the problem is : in my dev and other production env, confluent and kafka with the same version works fine.
So , mind if I ask , the problem which I met is caused by old version bugs or not?

**Comment by zealot-shin** [comment]
updated to version 1.0.0, it seems like the problem has been solved.
