### ISSUE TITLE
Producer message headers on macOS

### ISSUE THREAD

**Issue by kontrafiktion** [confluentinc/confluent-kafka-python#606]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Simply pass a list of tuples or a dict as `headers=` to `produce()`.
Example:
https://github.com/confluentinc/confluent-kafka-python/blob/d0496eb9db8682a3e0288902b5569c6d5e7ecab8/tests/soak/soakclient.py#L87-L89

**Comment by kontrafiktion** [comment]
We do that. And it works on Linux, but not when sending from macOS

**Comment by kontrafiktion** [comment]
ah, just see, this has been created accidentally. The real issue is: https://github.com/confluentinc/confluent-kafka-python/issues/607
