### ISSUE TITLE
sending message headers seems not to work from macOS

### ISSUE THREAD

**Issue by kontrafiktion** [confluentinc/confluent-kafka-python#607]
Description
===========
headers sent from macOS are not available in a Java consumer on Linux. But when using the exact same producer to send messages from Linux, the headers are available in the Java consumer.

How to reproduce
================

Produce a message with headers from macOS and consume it (on Linux): no headers
Use the exact same producer code on Linux and consume it (on Linux): headers are there

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()` ('0.11.6', 722432) ('0.11.6', 722687)
 - [ x Apache Kafka broker version: 0.9.x
 - [x] Client configuration: 
```  'plugin.library.paths': 'monitoring-interceptor'
  'auto.offset.reset': 'earliest'
  'enable.auto.offset.store': false
  'api.version.request': false
```
 - [x] Operating system: producer on macOS 10.13
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts: --
 - [ ] Critical issue: No

----
We have looked into Producer.c and think that RD_KAFKA_V_HEADERS is set, because otherwise it looks like there should be an error message.
We have looked at integration_test.py but do not understand how to run it, but it looks like there is a test case verifying that headers are received.

**Comment by edenhill** [comment]
Headers are not supported until broker version v0.11.

**Comment by kontrafiktion** [comment]
hm, why does it work with the same broker and the same producer code (and versions) on Linux?

**Comment by edenhill** [comment]
You're stating that you are using broker version 0.9, which does not have support for message headers, so I too find that strange.

**Comment by kontrafiktion** [comment]
Mea culpa! I 've been misinformed.
Broker: 2.1.1
log.format.message: 2.0.0

**Comment by edenhill** [comment]
That's better.
Make sure you are running the latest version of the python client (v1.0.0) on both osx and linux.
And you shouldn't use `api.version.request: False` with brokers >= 0.10, that will disable new features, such as headers..

**Comment by kontrafiktion** [comment]
AH, yes. I still had `api.version.request: False` configured. 
That is no solved.
(I still do not understand, why it worked from Linux, though.)
