### ISSUE TITLE
AvroProducer and AvroConsumer without key schema

### ISSUE THREAD

**Issue by kontrafiktion** [confluentinc/confluent-kafka-python#608]
Description
===========

Our Java producers send messages with a schema for the _value_, but use a simple string for the _key_. The Python AvroProducer does not allow a key without a schema. We cannot simply change the existing Java producers. Is there a way to have the exact same string keys used on the Python side. How must the schema be defined? Or can we get rid of the requirement to have a schema for the key?

How to reproduce
================
---

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('0.11.6', 722432) ('0.11.6', 722687)

**Comment by mhowlett** [comment]
there's a general serde API in progress that will address this ( #502 ). work will commence on that again before too long ...

**Comment by kontrafiktion** [comment]
For now we just created a sub class of the AvroProducer.

If someone else needs such a workaround:
```
class PatchedAvroProducer(AvroProducer):
    def __init__(self, config, default_key_schema=None, default_value_schema=None, schema_registry=None):
        super(PatchedAvroProducer, self).__init__(config, default_key_schema=default_key_schema,
                                                  default_value_schema=default_value_schema,
                                                  schema_registry=schema_registry)

    def produce(self, **kwargs):
        key_schema = kwargs.pop('key_schema', self._key_schema)
        value_schema = kwargs.pop('value_schema', self._value_schema)
        topic = kwargs.pop('topic', None)
        if not topic:
            raise ClientError("Topic name not specified.")
        value = kwargs.pop('value', None)
        key = kwargs.pop('key', None)

        if value is not None:
            if value_schema:
                value = self._serializer.encode_record_with_schema(topic, value_schema, value)
            else:
                raise ValueSerializerError("Avro schema required for values")

        if key is not None:
            if key_schema:
                key = self._serializer.encode_record_with_schema(topic, key_schema, key, True)
            else:
                pass

        super(AvroProducer, self).produce(topic, value, key, **kwargs)
```

**Comment by kontrafiktion** [comment]
Now we have the Problem on the Consumer side. When  the Java producer sends a message with a key _without_ a Schema, we get an error:

    "message does not start with magic byte"

from `confluent_kafka/avro/serializer/message_serializer.py`

We do not know whether there is a simple solution like our workaround above.

Would you consider that as a bug?

**Comment by rooom13** [comment]
I was obtaining 

> "message does not start with magic byte as well"

I did my own "AvroCodec" for encoding & decoding messages with an Avro Schema from the schema-_registry_

`from confluent_kafka.avro.cached_schema_registry_client import CachedSchemaRegistryClient
from avro.io import DatumReader, BinaryDecoder, BinaryEncoder, DatumWriter
import io

class AvroCodec():
    """Kafka message decoder,
    The built-in confluent_kafka Avro (from confluent_kafka.avro import 
    AvroConsumer) wasn't working. Hopefully in a future it will.
        -> [REF] https://github.com/confluentinc/confluent-kafka-python
    """

    def a(self, schema_registry_url, subject):
        """Args:
            schema_registry_url (str): url where the schema registry is (http://schema-registry:8081,  100.64.251.33:8081)
            subject (str). Name of the subject related with the topic: # Obtained from 'http://schema-registry:8081/subjects/avrotransactionannouncedevent/versions/latest'
        """
        self.schema_registry =CachedSchemaRegistryClient(schema_registry_url)
        _, self.schema, _ = self.schema_registry.get_latest_schema(subject)
        self.reader = DatumReader(self.schema)
        self.writer = DatumWriter(self.schema)

    def decode_message(self, msg_value):
        """Decode message using Avro Schema from schema_registry
        """
        message_bytes = io.BytesIO(msg_value)
        decoder = BinaryDecoder(message_bytes)
        event_dict = self.reader.read(decoder)
        return event_dict
 
    def encode_message(self, msg_dict):
        """Decode message using Avro Schema from schema_registry
        """
        bytes_writer = io.BytesIO()
        encoder = BinaryEncoder(bytes_writer)
        self.writer.write(msg_dict, encoder)
        return bytes_writer.getvalue()
`

**Comment by SoerenHenning** [comment]
We're currently still using the patch by @kontrafiktion. Can someone say if it is now possible to use the Confluent Python library without a key schema, i.e. only a value schema?

**Comment by SoerenHenning** [comment]
@edenhill So the way to go would now be to use a [`DeserializingConsumer`](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/index.html#serde-consumer)/[`SerializingProducer`](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/index.html#serde-producer) with specifying individual `key/value.serializer/deserializer`s? It this right?

**Comment by mhowlett** [comment]
yes. apologies that we've been slow to stabilize the new API - we don't anticipate significant changes.

**Comment by nbonavia** [comment]
I ran into the same issue and for the time being, I am using @kontrafiktion's workaround to mitigate my issue.
