### ISSUE TITLE
QUESTION: Way to programmatically determine if there's under replicated partitions?

### ISSUE THREAD

**Issue by minddrive** [confluentinc/confluent-kafka-python#613]
Given that the 'kafka-topic.sh' script has an '--under-replicated-partitions' option (usually used in combination with the '--describe' option), I was wondering if there was a way to programmatically do this with confluent-kafka?  I've gone through the docs a fair amount and done some digging on the web, but haven't been able to determine this.  Might someone be able to answer this definitively?

**Comment by mhowlett** [comment]
the `PartitionMetadata` class (via `list_topics`) should give you the information you need about current number of in-sync replicas. if you need it dynamically, the value of `min.insync.replicas`  should be available via the `describe_configs` admin client method.

**Comment by minddrive** [comment]
@mhowlett Thanks; I have that data, but I'm not sure how to properly interpret it.  As an example, here is the data from one of our test topics:

`Topic: <redacted>-metrics with 10 partitions
    Partition 0 - leader: 1004, replicas: [1004, 1006, 1007], isrs: [1006, 1004, 1007]
    Partition 1 - leader: 1005, replicas: [1005, 1007, 1002], isrs: [1002, 1005, 1007]
    Partition 2 - leader: 1006, replicas: [1006, 1002, 1004], isrs: [1004, 1006, 1002]
    Partition 3 - leader: 1007, replicas: [1007, 1004, 1005], isrs: [1005, 1004, 1007]
    Partition 4 - leader: 1002, replicas: [1002, 1005, 1006], isrs: [1005, 1002, 1006]
    Partition 5 - leader: 1004, replicas: [1004, 1007, 1002], isrs: [1002, 1004, 1007]
    Partition 6 - leader: 1005, replicas: [1005, 1002, 1004], isrs: [1005, 1004, 1002]
    Partition 7 - leader: 1006, replicas: [1006, 1004, 1005], isrs: [1006, 1005, 1004]
    Partition 8 - leader: 1007, replicas: [1007, 1005, 1006], isrs: [1005, 1006, 1007]
    Partition 9 - leader: 1002, replicas: [1002, 1006, 1007], isrs: [1006, 1002, 1007]`

From my (possibly naive) reading of the definition of under replicated partitions, the healthy topic above should be having that issue, so I suspect I'm interpreting the above incorrectly... or am I missing further necessary information?

**Comment by minddrive** [comment]
Just curious, any update for this question, perchance?

**Comment by minddrive** [comment]
The incorrect assumption I was making has been corrected and have a working understanding now; closing this issue.
