### ISSUE TITLE
Kafka deploy on Google Cloud - cannot create topic

### ISSUE THREAD

**Issue by dkajtoch** [confluentinc/confluent-kafka-python#617]
Description
===========
I deployed kafka on google cloud compute using prepared image: https://console.cloud.google.com/marketplace/details/click-to-deploy-images/kafka?q=kafka&id=f19a0f63-fc57-47fd-9d94-8d5ca6af935e

Know, I want to connect externally (from outside google cloud) to kafka and create topic. The problem is it does not work using AdminClient. I can create AdminClient (code below) and list topics (I created a few locally using kafka cli), but it hangs on create_topics. Any idea what I should change? 
I opened firewall for tcp connection on port 9092 (all ip addresses).

How to reproduce
================
# this piece works
from confluent_kafka.admin import AdminClient, NewTopic

cli = AdminClient({'bootstrap.servers': 'gcloud_external_ip:9092'})

cli.list_topics().topics

# this piece does not work
from confluent_kafka.admin import AdminClient, NewTopic
import logging

cli = AdminClient({'bootstrap.servers': 'gcloud_external_ip:9092'})

topics = []
topics.append(
  NewTopic('queries', num_partitions=2, replication_factor=1)
)

fs = cli.create_topics(topics, request_timeout=10.0)

for topic, f in fs.items():
    try:
        f.result()  # The result itself is None
        print("Topic {} created".format(topic))
    except Exception as e:
        print("Failed to create topic {}: {}".format(topic, e))

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.0.0 and 1.0.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Debian 9.9
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Try setting this in the client config `"debug": "admin,broker,protocol"`

**Comment by rnpridgeon** [comment]
Closed due to inactivity. Feel free to reopen with the requested information if you wish to proceed.
