### ISSUE TITLE
Missing source package for 1.0.1

### ISSUE THREAD

**Issue by asyd** [confluentinc/confluent-kafka-python#621]
Description
===========

It's not possible to install confluent-kafka 1.0.1 from source since there is .tar.gz packages on pypi. Thereforce it's impossible to install confluent-kafka on alpine based system for examples.

(Same issue than #568)

How to reproduce
================

```
python3 -m venv test
./test/bin/pip download --no-binary=:all: --no-deps confluent-kafka==1.0.1
Collecting confluent-kafka==1.0.1
  Could not find a version that satisfies the requirement confluent-kafka==1.0.1 (from versions: 0.9.1.1, 0.9.1.2, 0.9.2, 0.9.4, 0.11.0, 0.11.4, 0.11.5, 0.11.6, 1.0.0)
No matching distribution found for confluent-kafka==1.0.1
```

**Comment by rnpridgeon** [comment]
Thanks @asyd , You should be able to access them now. Sorry for the delay

**Comment by asyd** [comment]
Thanks @rnpridgeon, indeed the source package was available few hours/1 day after.
