### ISSUE TITLE
Allow configuring request timeout on Schema Registry client

### ISSUE THREAD

**Issue by m-burst** [confluentinc/confluent-kafka-python#622]
This is a feature request.

We have encountered a problem in production. Our Kafka ops were doing some maintenance of the cluster, during which a HTTP request to schema registry hung for some reason, and the whole consumer hung with it. We had to go through a lot of pain to abort the request without restarting the whole app.

Inspecting the [source code], I've noticed that there is no request timeout in the `CachedSchemaRegistryClient` in its calls to `requests`. My proposal is to allow configuring the timeout and expose it as a configuration parameter in `AvroProducer` and `AvroConsumer`.

If you agree that this should be implemented, I can try to implement it myself.

Yours,
Mikhail

[source code]: https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/cached_schema_registry_client.py#L166

**Comment by jordaniversen** [comment]
Any update on this?  Thank you

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1852
