### ISSUE TITLE
Consumer blocked by other thread

### ISSUE THREAD

**Issue by ghost** [confluentinc/confluent-kafka-python#625]
Description
===========
I created my own consumer class to abstract out all the configuration. The problem is that if I put multiple consumers on different threads, their poll methods will block each other. The workaround I have been using is to have a relatively small timeout, but that is not ideal.

How to reproduce
================

1. Create a consumer class.
2. Create two threads.
3. Instantiate an object of the class on each thread.
4. Have while loops in both threads that have consumer continuously polling.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
Using docker so it should be the latest for python3
 - [x] Apache Kafka broker version:
Using wurstmeister/kafka docker image
 - [x] Client configuration: `{...}`
bootstrap.servers and group.id set
 - [x] Operating system:
python:3-onbuild docker image
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please provide the exact `confluent_kafka.version()` you are using.

Can you explain more in detail what you mean by the blocking behaviour?
What calls are blocking, for how long, and in what relation to other threads?

**Comment by David-Warnke** [comment]
I am sorry I am not on this project anymore and don't have access to it so cannot give you the version. If you cannot recreate from the following example, just go ahead and close the issue.

If thread one subscriber calls poll(timeout=15), and thread two subscriber calls poll(timeout=15), and there are 15 messages subscriber 1 reads, and 30 messages subscriber 2 reads. Thread 1 consumes 15 messages and then trys to consume with nothing there and waits 15 seconds. Meanwhile thread 2 reads about 15 messages before stopping and waiting for 15 seconds, and then resuming to read the final 15 messages. Why would one subscribers poll function timeout effect a completely different subscriber on a different thread.

**Comment by edenhill** [comment]
Maybe it is the other way around, that due to pythons GIL the consumer processing the messages is blocking the polling-consumer's python code to run.
