### ISSUE TITLE
Supress Retrying MetadataRequest logs

### ISSUE THREAD

**Issue by aakashres** [confluentinc/confluent-kafka-python#632]
Description
===========
I just want some logs to be supressed completly.

2019-04-25_11:44:58.92622 %4\|1556192698.926\|REQTMOUT\|lpc_kafka_producer#consumer-1\| [thrd:10.48.207.5:9094/bootstrap]: 10.48.207.5:9094/bootstrap: Timed out 0 in-flight, 2 retry-queued, 0 out-queue, 0 partially-sent requests
--
 

How to reproduce
================

NA

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version(0.11.6)` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{
            'session.timeout.ms': 6000,
            'enable.auto.commit': False,
            'default.topic.config': {'auto.offset.reset': 'earliest'},
        }`
 - [ ] Operating system: Linux Ububtu
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
To filter out >= warning logs, set the `log_level` config property to `3`.

But the log is there to tell you that something is wrong, that requests are timing out which will degrade the functionality or performance of the client. I suggest looking into the issue instead of ignoring it.
Also upgrade to v1.0.1 and see if the problem persists.

**Comment by aakashres** [comment]
Logs are seen when the connection is broken. You mean to say Set `log_level` in `log4j.properties`

**Comment by edenhill** [comment]
set `log_level` in the configuration dict you pass to the Consumer constructor, like so:
```
c = Consumer({ 'session.timeout.ms': 6000, 'enable.auto.commit': False, 'log_level': 3, 'auto.offset.reset': 'earliest'})
```

Also note that `default.topic.config` is deprecated, the topic-level config properties should be set on the outer dict as in my example above.

**Comment by aakashres** [comment]
These configurations did suppress this log. But I am unable to figure out the reason behind these logs. Once the connection gets broken and these logs start to appear. But even when the connection is restored and the consumer starts to consume log, these logs don't disappear. What might be the problem?
