### ISSUE TITLE
How to use example applications of confluent-kafka-python

### ISSUE THREAD

**Issue by vikramindian** [confluentinc/confluent-kafka-python#633]
Description
===========
Hey,

I'am new to this. Can you prescribe the step by step process on how to run the example applications (specifically `adminapi.py`).

I have llibrdkafka installed in `/u/markiv/librdkafka` and confluent-kafka-python in `/u/markiv/confluent-kafka-python/`

I tried running `python setup.py build` inside confluent-kafka-python directory, but it says (below)

> In file included from confluent_kafka/src/confluent_kafka.c:17:0:
> confluent_kafka/src/confluent_kafka.h:22:10: fatal error: librdkafka/rdkafka.h: No such file or directory
>  #include <librdkafka/rdkafka.h>
>           ^~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.

How to link librdkafka to confluent-kafka-python?

Thanks in advance.

**Comment by mhowlett** [comment]
you don't need to install librdkafka separately for most platforms, just use pip to install the self contained binary wheels: https://github.com/confluentinc/confluent-kafka-python#install

having done that, you'll be able to run adminapi.py. side note: generally you should be working in a venv. e.g. (for python 3):

```
python3 -m venv ~/venvs/mytestvenv
source ~/venvs/mytestvenv/bin/activate
pip install confluent-kafka
cd /u/markiv/confluen-kafka-python/examples
python3 adminapi.py 127.0.0.1:9092 list all
deactivate
```

**Comment by vikramindian** [comment]
I did not use pip to install. I have cloned both of them separately( e.g. `git clone https://github.com/confluentinc/confluent-kafka-python.git`). Is it possible to use those applications by this way?
I would definitely give a try to install using pip.

Thanks.

**Comment by rnpridgeon** [comment]
It is possible but hardly worth the trouble especially when getting started which was the motivation for making the wheels. If for some reason the precompiled wheels do not work for you please feel free to reopen the issue.
