### ISSUE TITLE
Producer cannot be pickled 

### ISSUE THREAD

**Issue by remiadon** [confluentinc/confluent-kafka-python#637]
Description
===========
My use case is the following:
I want to be able to process some data using the PySpark.streaming API, manipulating `DStreams` objects
At the end I want to "sink" the results into Kafka, using an instance of `confluent_kafka.Producer`

How to reproduce
================
Here is the pseudo-code :
```python
from pyspark.streaming.kafka import KafkaUtils
import pyspark
import pyspark.streaming
from confluent_kafka import Producer

sc = pyspark.SparkContext()
poll_interval = 10
ssc = pyspark.streaming.StreamingContext(sc, poll_interval)

kafka_conf = {"bootstrap.servers": "localhost:9092,"}
stream = KafkaUtils.createDirectStream(ssc, ['kafka-test'], kafka_conf)
producer = Producer(kafka_conf)

def my_produce(e):
    producer.poll(0)
    producer.produce(key=e[0], value=e[1], topic='kafka-test-output')

stream.foreachRDD(lambda rdd: rdd.foreach(my_produce))
stream.pprint()
ssc.start()
``` 

I get an error saying the producer cannot be pickled via `cloudpickle` : 
* `TypeError: can't pickle cimpl.Producer objects`

Checklist
=========
Please provide the following information:
 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.0.1', 16777472) and ('1.0.1', 16777727)
 - [X] Apache Kafka broker version: 1.0.0

**Comment by mwz** [comment]
Hi @remiadon, did you manage to solve this issue?

**Comment by remiadon** [comment]
@nwz nope. I guess as long as the Producer has no `__reduce__` method, it's not possible
