### ISSUE TITLE
confluent_kafka.Message is not user-instantiable - how to test/mock?

### ISSUE THREAD

**Issue by joefromct** [confluentinc/confluent-kafka-python#639]
Description
===========

I want to test a function consuming kafka messages and I'm looking for a good way to mock `confluent_kafka.Message` however (as per the docs) [is not user-instantiatable](https://docs.confluent.io/current/clients/confluent-kafka-python/index.html#confluent_kafka.Message).

I was hoping to get some clues from the test files for however even the consumer test states [these wont really do anything since there is no broker configured.](https://github.com/confluentinc/confluent-kafka-python/blob/master/tests/test_Consumer.py#L10)

Curious how are folks doing this when building/testing data processing pipelinse...  maybe it's just not possible.

Any tips appreciated, and apologies if this isn't the right place to post questions such as this.

**Comment by joefromct** [comment]
I opted for clojure transducers to aid in the testing... not sure if there is a nice way to do this with python.

Maybe [this](https://engineering.fundingcircle.com/blog/2019/08/27/kafka-streams-the-clojure-way/) is useful for anyone else that comes across this:

>Transducers are “a powerful and composable way to build algorithmic transformations that you can reuse in many contexts”. Basically, they allow you to encapsulate the logic of transforming a stream of data, without specific knowledge of what the stream is. The stream could be a seq, a core.async channel, or a Kafka topic.

**Comment by 1Mark** [comment]
Use [forbidden fruit](https://github.com/clarete/forbiddenfruit)
```
from confluent_kafka import Consumer
forbiddenfruit.curse(Consumer, "poll", MockKafkaMessage())
consumer = Consumer(...)
```

**Comment by cal97g** [comment]
@1Mark this doesn't actually explain how to mock a kafka message

**Comment by 1Mark** [comment]
You can't instantiate an instance of it since it's written in C. That's why you need to use forbiddenfruit.

The MockedKafkaMessage is just a class that implements the functions that would access on the object as if it existed. For my test, I had to implement `error()` and `message()`
