### ISSUE TITLE
Producer: different callback per message

### ISSUE THREAD

**Issue by patrickviet** [confluentinc/confluent-kafka-python#64]
Version: librdkafka 0.9.1 and last pip confluent lib

```python

from confluent_kafka import Producer

p = Producer({'bootstrap.servers':'kafkahost'})

def callback(err,msg,k):
  print "callback received k: %s and v: %s" % (k,msg.value())

data = {
  'k1':'v1',
  'k2':'v2',
  'k3':'v3',
}

for k,v in data.iteritems():
  print "sending k: %s" % k
  p.produce('patricktest', v, callback=lambda err,msg: callback(err,msg,k))

p.flush()
```

The result is:
```
Mac:~$ python producertest.py
sending k: k3
sending k: k2
sending k: k1
callback received k: k1 and v: v3
callback received k: k1 and v: v2
callback received k: k1 and v: v1
```

and I would expect in the three last lines to be k3 k2 k1 rather than three times k1

After looking at the source code, it seems that each time a callback is defined, it's defined as a global parameter for the whole producer, rather than per message.

This breaks the general expectation that if you give a callback to a function/method, it's THIS function which will be called. I didn't find a workaround either to give arbitrary extra data to the callback - which was what I attempted via this intermediate lambda.

--Thanks

**Comment by fillest** [comment]
After a quick glance it looks like a scoping problem (e.g. https://mail.python.org/pipermail/python-ideas/2008-October/002109.html)

**Comment by fillest** [comment]
Try something like
```python
def make_cb (k):
    return lambda err, msg: callback(err, msg, k)
p.produce('patricktest', v, callback = make_cb(k))
```

**Comment by edenhill** [comment]
Yes, I believe the lambda binds to the k variable, rather than its temporary value per loop-iteration.
