### ISSUE TITLE
Admin API’s NewPartitions missing replication factor

### ISSUE THREAD

**Issue by polarctis** [confluentinc/confluent-kafka-python#644]
Description
===========
The documentation of Admin API for NewPartitions has replication factor in it, but the implementation lacks it.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Right you are this should say `replica_assignment` which oddly enough is correct in the Parameters section despite being wrong in the usage. We will get that updated unless you wish to open a PR. 

https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/src/AdminTypes.c#L440

**Comment by lowercase24** [comment]
I'm happy to pick up this change.  As @rnpridgeon mentions it looks like we have the block below correctly formed but have an unsupported optional parameter in the py:function section.  Feel free to push my way.

**Comment by edenhill** [comment]
@lowercase24 That'd be great! Let us know if you need any guidance.

**Comment by lowercase24** [comment]
@edenhill I'm trying to figure out how to push this PR into the project but I get permission errors.  Am I missing something?

**Comment by rnpridgeon** [comment]
@lowercase24 the easiest thing would be to fork the repo, create a new branch, push your changes to your own repo and then open a PR against this one.

**Comment by lowercase24** [comment]
Here is the relevant PR:

https://github.com/confluentinc/confluent-kafka-python/pull/653

**Comment by lowercase24** [comment]
Just wanted to follow up on next step here @rnpridgeon can you take a look?

**Comment by lowercase24** [comment]
What needs to be done to wrap this up?  I'd like to become more active in this project, but currently turn around time is really laggy...

**Comment by edenhill** [comment]
Merged, thanks for driving this!
