### ISSUE TITLE
Feature Request/Question: Produce data with avro schema for value but not for key

### ISSUE THREAD

**Issue by lsimmons2** [confluentinc/confluent-kafka-python#645]
Description
===========
Using `AvroProducer` if you try to produce data with a value schema but no key schema, this package will raise an exception. Why does this need to happen? We are trying to mock data in our production environment where our records have string keys and avro values. We get around it by monkey-patching the package and removing lines 87-88 in `confluent_kafka/avro/__init__.py` but were wondering why this requirement is set in the library.

Relevant StackOverflow question: https://stackoverflow.com/questions/54900184/can-confluent-python-produce-data-with-value-in-avro-and-key-in-string
 

How to reproduce
================
Produce data with `AvroProducer` with a schema for record values but no schema for record keys.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.1.0 and 1.1.0
 - [x] Apache Kafka broker version: 2.1.0
 - [x] Client configuration: `{
        'bootstrap.servers': KAFKA_BOOTSTRAP_URI,
        'schema.registry.url': SCHEMA_REGISTRY_URI,
        'queue.buffering.max.ms' : 5,
        'batch.num.messages': 1,
        'linger.ms':5,
        }`
 - [x] Operating system: Debian
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rjmccabe3701** [comment]
[This](https://github.com/confluentinc/confluent-kafka-python/pull/650) is probably related

**Comment by pranavrth** [comment]
You should use AvroSearializer and AvroDeserializer with Producer and Consumer shown in the examples https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_producer.py and https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_consumer.py.

AvroConsumer and AvroProducer are deprecated now.

Closing this issue.
