### ISSUE TITLE
Producer.produce() raises cimpl.KafkaException: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Unable to produce message: Broker: Message size too large"}

### ISSUE THREAD

**Issue by tamaroth** [confluentinc/confluent-kafka-python#655]
Description
===========

When a large enough message is being produced to a topic in Kafka (larger than allowed size), the producer will raise the following exception:

```
cimpl.KafkaException: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Unable to produce message: Broker: Message size too large"}
```

It was my understanding, that if an exception inside producer is raised and `error_cb` is set, that error will be propagated to said callback rather than be raised by producer itself.

Is it a possible bug, or is it an expected behaviour. If it is the latter, is there a list of errors or documentation that describes fully what errors are passed to the callback and what errors can be raised by producer?

 - [:heavy_check_mark:] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.0.1

**Comment by mhowlett** [comment]
"errors" exposed via `error_cb` are all informational in nature, unless `err.fatal()` returns `True`, which can only happen in rare cases when idempotent producer is being used.

per message errors are always exposed as exceptions on `produce` if known immediately, or via the delivery callback if not.

**Comment by lowercase24** [comment]
@tamaroth does this answer your question?

**Comment by pranavrth** [comment]
I think the question is already answered. Closing this issue right now. Open a new issue if required.
