### ISSUE TITLE
Support disable auto register schema

### ISSUE THREAD

**Issue by Matthijsy** [confluentinc/confluent-kafka-python#659]
Description
===========
Currently the schemas you submit when producing messages using the AvroProducer are always registered in the schema registry. However, the documentation recommends to [disable this](https://docs.confluent.io/current/schema-registry/schema_registry_tutorial.html#auto-schema-registration). I couldn't find a configuration to do this. Did I miss it or is it not supported at the moment?

How to reproduce
================
Produce messages using the AvroProducer.

Checklist
=========
Please provide the following information:

Versions:
confluent-kafka-python==1.1.0
librdkafka==1.1.0
broker: enterprise:5.2.1

**Comment by rnpridgeon** [comment]
Agreed, this is supported by Java and the .NET client we should add support for it here as well.

**Comment by dpfeif** [comment]
This lacking feature is also preventing the production of messages on Confluent Cloud when the schema registry is full. It returns “403: Schema Limit Exceeded” instead of producing the message, even when the schema had already been registered.

**Comment by pintodragon** [comment]
Great work on this! Any ideas when this will be included in a release?

**Comment by IsmailFahmy** [comment]
Any news about this feature?
