### ISSUE TITLE
kafka consumer not working sasl_ssl setup

### ISSUE THREAD

**Issue by datta90** [confluentinc/confluent-kafka-python#662]
Description
===========
i have done a single broker setup with **SASL_SSL** settings using self-signed certificate. I was able to successfully able to produce and consume using java code. But my python code is not working. i have installed latest librdkafka using binary wheels and python package i installed using **pip install --no-binary :all: confluent-kafka**

i followed the instructions for sasl-ssl setup mentioned here 

> [https://docs.confluent.io/current/security/security_tutorial.html]

Do I have to build librdkafka manually for this to  work?

I don't want to use kerebros for authentication

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ 1.1.0 0.11.5] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [2.0.0 ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ubuntu 16.04.6] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
SSL, SASL PLAIN SCRAM mechanisms are supported by the prebuilt binary wheels, so you should be fine.

Can you share your client configuration?

**Comment by datta90** [comment]
@edenhill i am using java trustore hope that is not going to be an issue

since my consumer is in the same machine as broker do i have to create a separate keystore for my consumer ?


--kafka settings server.properties
listeners=SSL://192.168.1.38:9093,SASL_SSL://192.168.1.38:9094
security.inter.broker.protocol=SSL
ssl.client.auth=required
ssl.truststore.location=/var/ssl/private/kafka.server.truststore.jks
ssl.truststore.password=test1234
ssl.keystore.location=/var/ssl/private/kafka.server.keystore.jks
ssl.keystore.password=test1234
ssl.key.password=test1234
sasl.enabled.mechanisms=PLAIN

authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
super.users=User:datta

--kafka server jaas.conf
KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="datta"
   password="datta"
   user_datta="datta"
   user_rohit="rohit#123";
};

Client {
   org.apache.zookeeper.server.auth.DigestLoginModule required
   username="datta"
   password="datta";
};

--client properties file for my java consumer
security.protocol=SASL_SSL
ssl.truststore.location=/var/ssl/private/kafka.client.truststore.jks
ssl.truststore.password=test1234
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username=\"datta\" \
    password=\"datta\";


--for python consumer following properties i am passing
{
"security.protocol":"SASL_SSL" # in the docs it is written it should be type enum i am passing it as string
"sasl.mechanisms":"PLAIN"
"sasl.username":"datta"
"sasl.password":"datta"

}

**Comment by datta90** [comment]
is it possible to have both java trust store and standard pem keys side by side i will have java and python clients connecting to the same kafka cluster

**Comment by datta90** [comment]
@rnpridgeon  thanks your link worked for me. but did it using SSL setup. SASL_PLAIN i was not able to get it running. This is my config dict

consumer_dict = {'bootstrap.servers': '192.168.1.38:9093', 
              'group.id': 'jaya_b22122','enable.auto.commit':True,
              'security.protocol':'SSL',
#               'sasl.mechanisms':'PLAIN',
              
            'ssl.ca.location':'/home/datta/Pictures/ca-cert',
            'ssl.certificate.location':'/home/datta/Pictures/client_192.168.1.38_client.pem',

            # Client's key
            'ssl.key.location':'/home/datta/Pictures/client_192.168.1.38_client.key',
            
            # Key password, if any.
            'ssl.key.password':'abcdefgh',

             'debug':'consumer', 
              
              
            'auto.commit.interval.ms':5000,
             'default.topic.config': {'auto.offset.reset': 'earliest',
                                      
              },
            # 'on_commit':delivery_callback
             }

**Comment by rnpridgeon** [comment]
`'security.protocol':'SSL'`, should be `'security.protocol':'SASL_SSL'` when trying to connect to a listener using TLS and SASL authentication. If you wisht o use SASL_PLAIN as in SASL without TLS you will want to set the `security.protocol` to SASL_PLAIN. And of course don't forget to uncomment out the` sasl.mechanism`.

**Comment by ammurdoch** [comment]
I've been trying to get `sasl_ssl` to work as well and have had no luck.

```
from confluent_kafka import Producer
from confluent_kafka import Consumer
import os
user = 'asdf'
password = 'asdf'
consumer = Consumer({
  "bootstrap.servers": "167.172.15.238:19092",
  'security.protocol': 'SASL_SSL',
  'sasl.mechanisms': 'PLAIN',
  'sasl.username': user,
  'sasl.password': password,
  'ssl.ca.location': os.path.join(os.getcwd(), 'ca-cert'),
  'group.id': 'terminal'
})
```

Here's the kafka log output
```
[2020-04-16 07:34:14,441] INFO [SocketServer brokerId=0] Failed authentication with 10.244.0.219/10.244.0.219 (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```

**Comment by Boggartfly** [comment]
@ammurdoch This is probably due to self-signed cert error. If you can install the root ca on that machine it should work.
