### ISSUE TITLE
Difference between Local & Broker Kafka Error Handling

### ISSUE THREAD

**Issue by kasturichavan** [confluentinc/confluent-kafka-python#664]
**Goal:**
Handle the kafka consumption error failures.

**Issue:**
The docs shared below arent explanatory.
https://docs.confluent.io/5.0.0/clients/confluent-kafka-python/index.html#kafkaerror

Poll method only fires a runtimeError but the Message returned by poll can then on message.error() fire a KafkaError. 
` message: Optional[Message] = self.kafka_consumer.poll(
                timeout=self.timeout
            )
error: Optional[KafkaError] = message.error()
`

1. Can poll() always fail if there is any kafka connection issue or any issue with getting a message from kafka topic ? In that case why is there a need for message.error() call check?
2. Also Based on KafkaError documentation shared above the errors seem to be broken down into Local vs Broker, which of these errors does message.error() & poll fire ? 
3. Or do we not care about error details, and retry consumption of same offset unless its a EOF exception.
4. Also what happens when enable.auto.commit= False when there is an exception, will offset get updated on broker side ? A call to poll() should read from same failed offset right ?

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python (`confluent_kafka.version()`): 0.11.5 
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
`Local` denotes an error internal to the client itself. 

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L245-L249

All error messages returned by librdkafka derived clients, including confluent-kafka-python, are intended to be informational and temporary. The client will try to recover from all errors in a graceful fashion (by retrying, etc). This includes connectivity issues communicating with the broker, committing offsets,etc.

**Comment by akosel** [comment]
@rnpridgeon In my application, I am seeing instances where `KafkaException: KafkaError{code=OFFSET_OUT_OF_RANGE,val=1,str="Unable to produce message: Broker: Offset out of range"}` is thrown when calling `produce`. This is in an idempotent producer. 

Do I trust that the client has the message and will eventually `produce` it? Or do I need to trigger a retry in my application code? I know application-level retries are discouraged in idempotent producers in favor of letting the client handle retries, but it's not clear to me that message is being produced successfully.

**Comment by a6kme** [comment]
@akosel - I am also facing similar issue in my producers. Did you come across any way to mitigate this issue?
