### ISSUE TITLE
Do you support same functionality as kafka-configs.sh ?

### ISSUE THREAD

**Issue by jrask** [confluentinc/confluent-kafka-python#667]
Hi, we are looking into replacing our current setup with java and was looking into this module.
We want to replace our kafka-config.sh commands so I was wondering if this is supported by confluent-kafka-python?

There seem to be something called describe/alter_configs but I am not really sure that is what I am looking for.

Sample with java-cli

```
kafka-configs 
  --zookeeper $zookeeper:2181/analytics1
   --alter 
    --add-config 'producer_byte_rate=1024000, consumer_byte_rate=1024000' 
   --entity-type users 
   --entity-name userXXX
   --entity-type clients
  --entity-name client_id_xxx
```

**Comment by rnpridgeon** [comment]
We do not provide a CLI but if you are looking to write your own you should check out this libraries admin module which includes a `alter_configs` function. 

Currently we only support a subset of the kafka admin api so you wouldn't be able to replace all of the java clis(namely kafka-acls). You can check out the docs to see if we cover what you need though. 

https://docs.confluent.io/current/clients/confluent-kafka-python/#module-confluent_kafka.admin

You can see an example of the alter_config usage in our tests. 

https://github.com/confluentinc/confluent-kafka-python/blob/master/tests/test_Admin.py

**Comment by edenhill** [comment]
There's a full blown admin api example here:
https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/adminapi.py#L143

**Comment by jrask** [comment]
Thanks for you answers, I really appreciate this! 
From my understanding, this is either not supported or I am unable to figure out how to do it...
I can alter and describe configs for topics and brokers but these are configs per username and/or client_id and is not a broker or topic configuration.
 https://kafka.apache.org/documentation/#design_quotasconfig

If this is possible, could you please guide me in the correct direction, otherwise I guess I am wondering if there are any plans to support this in the future?

Thanks /Johan

**Comment by jrask** [comment]
Let me re-phrase this, **Is it possible to configure quotas using confluent-kafka-python library?**
Would be awesome if someone could let me know since I do not understand from the docs or from the samples.

**Comment by edenhill** [comment]
No, this might be addressed in Q2

**Comment by danielsinai** [comment]
Hi 👋 @edenhill, sorry for reopening it, but I couldn't find any other thread.
Any news about this issue? Is it something you guys plan to address?
