### ISSUE TITLE
Improve speed of Kafka Producer

### ISSUE THREAD

**Issue by QuanVan95** [confluentinc/confluent-kafka-python#669]
Description
===========
Hi Mr. Edenhill,
I'm working with Kafka Producer - Python, when I tried to produce messages to Kafka, for example, 10k message. It took too long(>7s for 10k simple message). I reduce the config producer.poll(0.001) (I tried to reduce this config more, but it only works with min is 0.001) it will run faster than poll(0.001++) 
Could u please recommend for me the right config to improve the speed of Producer and Consumer as well?
Thank you so much, hope to hear from you soon!

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by QuanVan95** [comment]
I added the config  'acks': 0, and now it pushed 10k message/s. Is there any way to improve it? ><

**Comment by edenhill** [comment]
You never want to use acks=0, since messages may (and will) be dropped without any warning or notification.

For optimal throughput increase linger.ms to 50..500ms, depending on your produce rate.
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#high-throughput

**Comment by edenhill** [comment]
Please elaborate on "cannot run well".

Good config is `linger.ms=500`, don't change any other properties.
