### ISSUE TITLE
SerializerError is not indented correctly

### ISSUE THREAD

**Issue by ferozed** [confluentinc/confluent-kafka-python#674]
Description
===========

he class confluent_kafka.avro.serializer.SerializerError is not authored correctly. The indents are wrong for __str__ and __repl__ methods.

--
https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/serializer/__init__.py#L25-L32
--

This is the result:

--
$ ./bin/python
Python 2.7.15 (default, Jun 17 2018, 13:05:56)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from confluent_kafka.avro.serializer import SerializerError
>>> s = SerializerError("foo is not bar")
>>> s
SerializerError()
>>> str(s)
''
>>> s.message
'foo is not bar'
--

Expected:

str(s) == 'foo is not bar'

How to reproduce
================

$ ./bin/python
Python 2.7.15 (default, Jun 17 2018, 13:05:56)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from confluent_kafka.avro.serializer import SerializerError
>>> s = SerializerError("foo is not bar")
>>> s
SerializerError()
>>> str(s)
''
>>> s.message
'foo is not bar'

Checklist
=========
Please provide the following information:

Not necessary as repro is self contained.

 - [X ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
Thanks for the contribution.

This PR is merged. Closing the issue.
