### ISSUE TITLE
Question: How does max.poll.interval.ms differ between Java and rdkafka poll() api?

### ISSUE THREAD

**Issue by mkmoisen** [confluentinc/confluent-kafka-python#681]
Under the [Detecting Consumer Failures](https://kafka.apache.org/23/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html) of the Java Consumer API, it states that if `poll` is not called at least as frequently as `max.poll.interval.ms`, then the client will leave the group and trigger a rebalance.

The rdkafka poll API differs from the Java API: the Java API returns an arraylist of messages to the calling code, while rdkafka returns a single message to the calling code; I think behind the scenes, rdkafka has an internal queue that actually received a batch of messages from the broker, but only one is returned to the user.

So in the rdkafka api, will calling poll() cause the clock to reset on the `max.poll.interval.ms` upon each and every invocation of poll(), or will the clock only reset once the internal queue is depleted?

This is not a bug, just a question.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.2.0', 16908288) and ('1.2.0', 16908543)
 - [x] Apache Kafka broker version: 2.3
 - [x] Client configuration: `{...}` n/a
 - [x] Operating system: Linux, Windows
 - [x] Provide client logs (with `'debug': '..'` as necessary) n/a
 - [x] Provide broker log excerpts n/a
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
max.poll.interval.ms is reset with each invocation of `poll`. This mechanism was added to ensure we catch applications which have died and/or become unresponsive but continue to send heartbeats(which are handled by a separate thread).

Please see [KIP-62 ](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread) for full details.
