### ISSUE TITLE
Timed out waiting for controller while creating topic

### ISSUE THREAD

**Issue by NiravLangaliya** [confluentinc/confluent-kafka-python#682]
Description
===========

I am able to list existing topics but I am not able to create a new topic or change partitions to an existing topic

Failed to create topic EDW_TEST_DATA: KafkaError{code=_TIMED_OUT,val=-185,str="Timed out waiting for controller"}

How to reproduce
================

import confluent_kafka.admin, pprint

conf = {'bootstrap.servers': 'localhost:9092'}

kafka_admin = confluent_kafka.admin.AdminClient(conf)

topics = ['EDW_TEST_DATA']
new_topics = [confluent_kafka.admin.NewTopic(topic, num_partitions=3, replication_factor=1) for topic in topics]

fs = kafka_admin.create_topics(new_topics)

for topic, f in fs.items():
    try:
        f.result()  # The result itself is None
        print("Topic {} created".format(topic))
    except Exception as e:
        print("Failed to create topic {}: {}".format(topic, e))

pprint.pprint(kafka_admin.list_topics().topics)

topic_list = []
topic_list.append(confluent_kafka.admin.NewPartitions('EDW_EMP_DATA1', 3))
kafka_admin.create_partitions(topic_list)

pprint.pprint(kafka_admin.list_topics().topics)

Checklist
=========
Please provide the following information:

 - [X ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):  ('1.1.0', 16842752)  and ('1.1.0', 16843007)
 - [X] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [X ] Operating system: MacOS 10.14
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by NiravLangaliya** [comment]
Logs: 

%7|1570131362.961|BROKER|rdkafka#producer-1| [thrd:app]: localhost:9092/bootstrap: Added new broker with NodeId -1
%7|1570131362.961|CONNECT|rdkafka#producer-1| [thrd:app]: localhost:9092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1570131362.961|BRKMAIN|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Enter main broker thread
%7|1570131362.961|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1570131362.961|CONNECT|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Received CONNECT op
%7|1570131362.961|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.1.0 (0x10100ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, GCC GXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x2)
%7|1570131362.961|STATE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1570131362.961|CONNECT|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1570131362.961|STATE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1570131362.961|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: lookup controller
%7|1570131362.961|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: lookup controller
%7|1570131362.963|CONNECT|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connecting to ipv6#[::1]:9092 (plaintext) with socket 9
%7|1570131362.963|CONNECT|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected to ipv6#[::1]:9092
%7|1570131362.963|CONNECTED|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connected (#1)
%7|1570131362.963|FEATURE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1570131362.963|STATE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1570131362.963|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 47ms: lookup controller
%7|1570131362.963|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 47ms: lookup controller
%7|1570131362.964|FEATURE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD
%7|1570131362.964|STATE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1570131362.965|BROKER|rdkafka#producer-1| [thrd:main]: 172.16.0.9:9092/0: Added new broker with NodeId 0
%7|1570131362.965|CLUSTERID|rdkafka#producer-1| [thrd:main]: localhost:9092/bootstrap: ClusterId update "" -> "ke8ck2sHSJSHVLACiLhs2Q"
%7|1570131362.965|CONTROLLERID|rdkafka#producer-1| [thrd:main]: localhost:9092/bootstrap: ControllerId update -1 -> 0
%7|1570131362.965|BRKMAIN|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Enter main broker thread
%7|1570131362.965|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Received CONNECT op
%7|1570131362.965|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state INIT -> TRY_CONNECT
%7|1570131362.965|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: broker in state TRY_CONNECT connecting
%7|1570131362.965|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1570131362.965|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connecting to ipv4#172.16.0.9:9092 (plaintext) with socket 12
%7|1570131374.003|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker transport failure: (errno: Connection refused)
%7|1570131374.003|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state CONNECT -> DOWN
%7|1570131375.005|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state DOWN -> INIT
%7|1570131375.005|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Received CONNECT op
%7|1570131375.005|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state INIT -> TRY_CONNECT
%7|1570131375.005|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: broker in state TRY_CONNECT connecting
%7|1570131375.005|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1570131375.006|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connecting to ipv4#172.16.0.9:9092 (plaintext) with socket 12
%7|1570131376.021|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker transport failure: (errno: Connection refused)
%7|1570131376.021|FAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connect to ipv4#172.16.0.9:9092 failed: Connection refused (after 1015ms in state CONNECT)
%7|1570131376.021|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state CONNECT -> DOWN
%7|1570131377.022|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state DOWN -> INIT
%7|1570131377.022|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Received CONNECT op
%7|1570131377.022|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state INIT -> TRY_CONNECT
%7|1570131377.022|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: broker in state TRY_CONNECT connecting
%7|1570131377.022|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1570131377.022|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connecting to ipv4#172.16.0.9:9092 (plaintext) with socket 12
%7|1570131378.033|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker transport failure: (errno: Connection refused)
%7|1570131378.033|FAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connect to ipv4#172.16.0.9:9092 failed: Connection refused (after 1011ms in state CONNECT)
%7|1570131378.033|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state CONNECT -> DOWN
%7|1570131379.033|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state DOWN -> INIT
%7|1570131379.033|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Received CONNECT op
%7|1570131379.034|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state INIT -> TRY_CONNECT
%7|1570131379.034|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: broker in state TRY_CONNECT connecting
%7|1570131379.034|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1570131379.034|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connecting to ipv4#172.16.0.9:9092 (plaintext) with socket 12
%7|1570131381.058|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker transport failure: (errno: Connection refused)
%7|1570131381.058|FAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connect to ipv4#172.16.0.9:9092 failed: Connection refused (after 2024ms in state CONNECT)
%7|1570131381.058|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state CONNECT -> DOWN
%7|1570131382.063|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state DOWN -> INIT
%7|1570131382.063|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Received CONNECT op
%7|1570131382.063|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state INIT -> TRY_CONNECT
%7|1570131382.063|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: broker in state TRY_CONNECT connecting
%7|1570131382.063|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1570131382.063|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connecting to ipv4#172.16.0.9:9092 (plaintext) with socket 12
%7|1570131383.069|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker transport failure: (errno: Connection refused)
%7|1570131383.069|FAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connect to ipv4#172.16.0.9:9092 failed: Connection refused (after 1005ms in state CONNECT)
%7|1570131383.069|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state CONNECT -> DOWN
%7|1570131384.072|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state DOWN -> INIT
%7|1570131384.072|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Received CONNECT op
%7|1570131384.072|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state INIT -> TRY_CONNECT
%7|1570131384.072|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: broker in state TRY_CONNECT connecting
%7|1570131384.072|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1570131384.072|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connecting to ipv4#172.16.0.9:9092 (plaintext) with socket 12
%7|1570131391.109|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker transport failure: (errno: Connection refused)
%7|1570131391.109|FAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connect to ipv4#172.16.0.9:9092 failed: Connection refused (after 7037ms in state CONNECT)
%7|1570131391.109|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state CONNECT -> DOWN
%7|1570131392.113|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state DOWN -> INIT
%7|1570131392.113|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Received CONNECT op
%7|1570131392.113|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state INIT -> TRY_CONNECT
%7|1570131392.113|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: broker in state TRY_CONNECT connecting
%7|1570131392.113|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1570131392.114|CONNECT|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Connecting to ipv4#172.16.0.9:9092 (plaintext) with socket 12
Failed to create topic EDW_TEST_DATA: KafkaError{code=_TIMED_OUT,val=-185,str="Timed out waiting for controller"}
{'EDW_EMP_DATA1': TopicMetadata(EDW_EMP_DATA1, 1 partitions),
 '__confluent.support.metrics': TopicMetadata(__confluent.support.metrics, 1 partitions),
 '__consumer_offsets': TopicMetadata(__consumer_offsets, 50 partitions),
 '_confluent-ksql-default__command_topic': TopicMetadata(_confluent-ksql-default__command_topic, 1 partitions),
 '_schemas': TopicMetadata(_schemas, 1 partitions),
 'connect-configs': TopicMetadata(connect-configs, 1 partitions),
 'connect-offsets': TopicMetadata(connect-offsets, 25 partitions),
 'connect-statuses': TopicMetadata(connect-statuses, 5 partitions),
 'default_ksql_processing_log': TopicMetadata(default_ksql_processing_log, 1 partitions)}
{'EDW_EMP_DATA1': TopicMetadata(EDW_EMP_DATA1, 1 partitions),
 '__confluent.support.metrics': TopicMetadata(__confluent.support.metrics, 1 partitions),
 '__consumer_offsets': TopicMetadata(__consumer_offsets, 50 partitions),
 '_confluent-ksql-default__command_topic': TopicMetadata(_confluent-ksql-default__command_topic, 1 partitions),
 '_schemas': TopicMetadata(_schemas, 1 partitions),
 'connect-configs': TopicMetadata(connect-configs, 1 partitions),
 'connect-offsets': TopicMetadata(connect-offsets, 25 partitions),
 'connect-statuses': TopicMetadata(connect-statuses, 5 partitions),
 'default_ksql_processing_log': TopicMetadata(default_ksql_processing_log, 1 partitions)}
%7|1570131422.972|DESTROY|rdkafka#producer-1| [thrd:app]: Terminating instance (destroy flags none (0x0))
%7|1570131422.972|DESTROY|rdkafka#producer-1| [thrd:main]: Destroy internal
%7|1570131422.972|DESTROY|rdkafka#producer-1| [thrd:main]: Waiting for background queue thread to terminate
%7|1570131422.972|DESTROY|rdkafka#producer-1| [thrd:main]: Removing all topics
%7|1570131422.972|DESTROY|rdkafka#producer-1| [thrd:main]: Sending TERMINATE to 172.16.0.9:9092/0
%7|1570131422.972|DESTROY|rdkafka#producer-1| [thrd:main]: Sending TERMINATE to localhost:9092/bootstrap
%7|1570131422.972|TERM|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Received TERMINATE op in state CONNECT: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1570131422.972|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1570131422.972|TERM|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1570131422.972|BROKERFAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1570131422.972|TERM|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Received TERMINATE op in state INIT: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1570131422.972|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: strerror_r(316) failed (ret 22))
%7|1570131422.972|FAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Client is terminating (after 60010ms in state INIT)
%7|1570131422.972|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> DOWN
%7|1570131422.972|FAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Client is terminating (after 30858ms in state CONNECT)
%7|1570131422.972|TERMINATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Handle is terminating in state DOWN: 1 refcnts (0x7f86c981ed28), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1570131422.972|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: strerror_r(316) failed (ret 22))
%7|1570131422.972|STATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Broker changed state CONNECT -> DOWN
%7|1570131422.972|TERMINATE|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: Handle is terminating in state DOWN: 1 refcnts (0x7f86c906c728), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1570131422.972|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1570131422.972|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Client is terminating (after 60007ms in state UP)
%7|1570131422.972|STATE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Broker changed state UP -> DOWN
%7|1570131422.972|TERMINATE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Handle is terminating in state DOWN: 1 refcnts (0x7f86c981f928), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1570131422.972|BROKERFAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)

Process finished with exit code 0

**Comment by edenhill** [comment]
`%7|1570131374.003|BROKERFAIL|rdkafka#producer-1| [thrd:172.16.0.9:9092/0]: 172.16.0.9:9092/0: failed: err: Local: Broker transport failure: (errno: Connection refused)`

It fails to connect to your cluster, see https://rmoff.net/2018/08/02/kafka-listeners-explained/
