### ISSUE TITLE
unable to register schema errorcode 503

### ISSUE THREAD

**Issue by test1370** [confluentinc/confluent-kafka-python#684]
Description
===========
I am trying to use producer in python using confluent-avro modules. everything is running fine(kafka server, schemaReg url). I can post string messages to the server but not Avro!!

This is the code i am using..
avroProducer = AvroProducer({
            'bootstrap.servers': 'server1',
            'schema.registry.url': 'url',
            'api.version.request': 'true'
          },  default_key_schema=schema, default_value_schema=schema)
        result = avroProducer.produce(topic='topic1', value=value, key=key)
        avroProducer.flush()

Output:
raise ClientError("Unable to register schema. Error code:" + str(code))
confluent_kafka.avro.error.ClientError: Unable to register schema. Error code:503

It would be great if some one helpss.

**Comment by rnpridgeon** [comment]
HTTP 503 implies the SR isn't ready to serve requests. If you are using docker its possible that although the SR image has started SR has not finished starting up. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

I recommend checking the SR logs to ensure its up and working as expected first. Once you have confirmed SR is up and operational use curl to verify functionality before proceeding. 

https://docs.confluent.io/current/schema-registry/develop/api.html
