### ISSUE TITLE
confluent_kafka.avro.error.ClientError: Unable to register schema. Error code:400

### ISSUE THREAD

**Issue by demoonism** [confluentinc/confluent-kafka-python#685]
Description
===========

Unable to publish avro message with any version above 1.0.0
got:
confluent_kafka.avro.error.ClientError: Unable to register schema. Error code:400

How to reproduce
================

from confluent_kafka import avro
from confluent_kafka.avro import AvroProducer

value_schema_str = """
{
   "namespace": "this",
   "name": "values",
   "type": "record",
   "fields" : [
     {
       "name" : "name",
       "type" : "string"
     }
   ]
}
"""

key_schema_str = """
{
   "namespace": "this",
   "name": "keys",
   "type": "record",
   "fields" : [
     {
       "name" : "name",
       "type" : "string"
     }
   ]
}
"""

value_schema = avro.loads(value_schema_str)
key_schema = avro.loads(key_schema_str)

value = {"name": "Value"}
key = {"name": "Key"}

avroProducer = AvroProducer({
    'bootstrap.servers': 'xxxx',
    'schema.registry.url': 'xxxx',
    }, default_key_schema=key_schema, default_value_schema=value_schema)

avroProducer.produce(topic='topicxxxx', value=value, key=key)

tested with version confluent kafka 1.0 and above, using librdkafka.x86_64 0:0.11.5-1.el7

This seems to only happen in rhel, ubuntu is not showing this.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version(1.2.0)` and `confluent_kafka.libversion(1.1.0)`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{}`
 - [x] Operating system: RHEL 7 in docker
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by rnpridgeon** [comment]
HTTP 400 implies there is something wrong with the request being sent to SR. If this were a SR client issue we would expect failures to be consistent across all distributions. Can you reproduce this with curl and have you inspected the SR logs?

**Comment by demoonism** [comment]
Hi,
I unfortunately don't have access to the SR logs, but this error is not happening with versions below 1.0 nor in linux. (I am using the same code (the sample code on github) in all tests).
It seems to happen only in RHEL, with version 1.0 and above.

**Comment by demoonism** [comment]
and yes, I am able to register the schema manually with curl.
{
   "namespace": "test.namespace",
   "name": "values",
   "type": "record",
   "fields" : [
     {
       "name" : "name",
       "type" : "string"
     }
   ]
}
