### ISSUE TITLE
Consumer restart is ignoring previous manual reset offset

### ISSUE THREAD

**Issue by andreportela** [confluentinc/confluent-kafka-python#693]
Description
===========

Sometimes we can have an external error while processing a message that implies in an agent shutdown (like the database we are inserting stuff is shutting down). The problem is that we want our agent completely stateless so we are trying to manually reset that offset on the broker before the agent shutdown so next time it should resume at the offset of the failed message. 

I tried `seek()` before shutting down the agent with no luck. 
```
consumer.seek(TopicPartition(message.topic(), message.partition(), message.offset()))
```
On the restart the agent resumed like the message was properly consumed. It completely ignored the previous call to seek() function and I loose the message I want to reprocess.

I also tried `seek()` + `poll()` with no luck:
```
topic_partition = TopicPartition(message.topic(), message.partition(), message.offset() - 1)
consumer.seek(topic_partition)
time.sleep(6)
message_to_discard = consumer.poll(timeout=0.5)
```
The agent behaves exactly the same on restart. Regardless `message_to_discard` having exactly the offset I expect.

I also tried `commit()` with no luck:
```
reset_succeeded = False
topic_partition = TopicPartition(message.topic(), message.partition(), message.offset() - 1)
while not reset_succeeded:
    [partition] = consumer.commit(offsets=[topic_partition], asynchronous=False)
    reset_succeeded = not partition.error
```
The agent behaves exactly the same on restart. 

I have `'enable.auto.commit': True` on the consumer so I can speed up our message consumption rate. The consumer gets the message from the broker, do some business logic and then insert the relevant stuff on postgres. Consumer also uses `subscribe()` method on initialization so it gets the stored offset message on the broker everytime it starts up but this works fine when message is processed.

Please help guys! What am I missing here? 
What I am really trying to achieve here is at-least-once semantics with the lowest possible overhead (message consuming rate is something sensitive to me). To achieve that I don't care if I may have a few duplicate messages in the end. Manually committing the messages are something that I want avoid if possible because it sensible slows things down.

How to reproduce
================
1. Run
```
consumer.subscribe(['topic_name'])
msg = consumer.poll(timeout=0.5) # assume msg.offset() == 12
try:
    process(msg)
except Exception as error: # assume a database shutting down exception here
    topic_partition = TopicPartition(msg.topic(), msg.partition(), msg.offset() - 1)
    consumer.seek(topic_partition)
    time.sleep(6) # we think it should be safe for a default auto.commit.interval.ms
    msg_discard = self.poll(timeout=0.5)  # msg_discard.offset() == 11
    consumer.close()
    sys.exit(0)
```
2. Start the agent again
```
consumer.subscribe(['topic_name'])
msg = consumer.poll(timeout=0.5) # msg.offset() == 13
# message 12 was lost!
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka-python ('1.0.1', 16777472) librdkafka ('1.0.1', 16777727)
 - [x] Apache Kafka broker version: Azure Event Hubs for Kafka
 - [x] Client configuration: `{...}`
{
    'bootstrap.servers': 'blahblahblah.servicebus.windows.net:9093',
    'group.id': 'group1',
    'client.id': 'client1',
    'request.timeout.ms': 60000,
    'session.timeout.ms': 60000,
    'default.topic.config': {'auto.offset.reset': 'earliest'},
    'enable.auto.commit': True,
    'security.protocol': 'SASL_SSL',
    'ssl.ca.location': 'cacert.pem',
    'sasl.mechanism': 'PLAIN',
    'sasl.username': 'ConnectionStringNameForEventHub',
    'sasl.password': 'CONNECTION_STRING',
}
 - [x] Operating system: mac OS x
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by rnpridgeon** [comment]
Rather than trying to catch exceptions and then rollback the the consumer I would instead defer storing the offset until after I have successfully processed the message. 

```python
consumer = Consumer({...
           'enable.auto.offset.store' : False})

consumer.subscribe(['topic_name'])

while True:

    msg = consumer.poll(timeout=0.5)
    if msg is None: 
        continue
    if msg.error():
      print("Message receive error {}".format(msg.error())
      continue # maybe raise exception depending on your use case 
   
    try:
        process(msg)
        store_offsets(msg)
    except Exception as error:
        consumer.close()
        sys.exit(0)
```

Taking control over the offset storage gives you all the advantages of auto offset commit without the pain associated with storing the offset when the application calls poll. You can read a bit more about it on the librdkafka wiki here. 

https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management
