### ISSUE TITLE
failed: err: Local: SSL error: (errno: Undefined error: 0)

### ISSUE THREAD

**Issue by Suresh-KM** [confluentinc/confluent-kafka-python#697]
Description
===========

When trying to produce messages the broker fails and does not send the message.

%7|1571426373.697|SASL|rdkafka#producer-1| [thrd:app]: Selected provider PLAIN (builtin) for SASL mechanism PLAIN
%7|1571426373.697|OPENSSL|rdkafka#producer-1| [thrd:app]: librdkafka built with OpenSSL version 0x1000212f
%7|1571426373.700|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1571426373.700|BROKER|rdkafka#producer-1| [thrd:app]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: Added new broker with NodeId -1
%7|1571426373.700|BRKMAIN|rdkafka#producer-1| [thrd:sasl_ssl://x.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: Enter main broker thread
%7|1571426373.700|CONNECT|rdkafka#producer-1| [thrd:app]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1571426373.700|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl:/x.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: Received CONNECT op
%7|1571426373.700|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.0.0 (0x10000ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd, GCC GXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM CRC32C_HW, debug 0x282)
%7|1571426373.700|STATE|rdkafka#producer-1| [thrd:sasl_ssl://x.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1571426373.700|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://x.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1571426373.700|STATE|rdkafka#producer-1| [thrd:sasl_ssl://x.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1571426373.865|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://x.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: Connecting to ipv4#x.x.x.x:9092 (sasl_ssl) with socket 11
%7|1571426373.886|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://x.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: Connected to ipv4#x.x.x.x:9092
%7|1571426373.965|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_ssl:/x.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://x.gcp.confluent.cloud:9092/bootstrap: failed: err: Local: SSL error: (errno: Undefined error: 0)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version:`1.2.0` and `1.2.1`
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `{
    'bootstrap.servers': bootstrap,
    'broker.version.fallback': '0.10.0.0',
    'sasl.mechanisms': 'PLAIN',
    'security.protocol': 'SASL_SSL',
    'sasl.username': username,
    'sasl.password': password
    }`
 - [x] Operating system: OS X
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Try with 'debug' : 'security,broker' in your config

**Comment by Suresh-KM** [comment]
%7|1571433997.906|SASL|rdkafka#producer-1| [thrd:app]: Selected provider PLAIN (builtin) for SASL mechanism PLAIN
%7|1571433997.906|OPENSSL|rdkafka#producer-1| [thrd:app]: librdkafka built with OpenSSL version 0x1000212f
%7|1571433997.911|BROKER|rdkafka#producer-1| [thrd:app]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Added new broker with NodeId -1
%7|1571433997.911|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1571433997.911|BRKMAIN|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Enter main broker thread
%7|1571433997.911|CONNECT|rdkafka#producer-1| [thrd:app]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1571433997.911|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.0.0 (0x10000ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd, GCC GXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM CRC32C_HW, debug 0x202)
%7|1571433997.911|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Received CONNECT op
%7|1571433997.911|STATE|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1571433997.911|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1571433997.911|STATE|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
{"id": 1, "party_id": 97800, "cookie_id": "85a94261-30bd-4035-a77c-4b766453f271", "ip": "192.173.136.70", "cookie": "69c836cd08ed30cdb7fb808a0a64b4474ab1e3e7bc3f78ebeea15e63218484a4"}
%7|1571433997.951|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Connecting to ipv4#35.236.85.34:9092 (sasl_ssl) with socket 11
%7|1571433997.972|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Connected to ipv4#35.236.85.34:9092
%7|1571433998.034|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: failed: err: Local: SSL error: (errno: Undefined error: 0)
%7|1571433998.034|STATE|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1571433998.034|STATE|rdkafka#producer-1| [thrd:sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstra]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Broker changed state DOWN -> INIT
%7|1571433998.912|CONNECT|rdkafka#producer-1| [thrd:main]: sasl_ssl://pkc-l7nkp.us-west2.gcp.confluent.cloud:9092/bootstrap: Selected for cluster connection: refresh unavailable topics (broker has 1 connection attempt(s)) 

This is the debug log for 'debug' : 'security,broker'

**Comment by trunsky** [comment]
@Suresh-KM did you ever figure this out? I'm having the same issue.

**Comment by naartjie** [comment]
@Suresh-KM I hit this same problem as well.

I managed to get around it by installing the CA certificates manually using a python lib.

You can test it by disabled cert verification in your config

```python
'enable.ssl.certificate.verification': 'false'
```

If the above works it means that the SSL certificate verification part is failing.

What you can do is load the CA certs in your python code using the `certify` lib:

```
$ pip install certifi
```

Then in your program:
```python
# at the top
import certifi

# and in your consumer/producer configs
'ssl.ca.location': certifi.where(),
```

This will use the CA's from the python package `certify` instead of your default system ones.

Hope this helps you, or someone else. I logged another issue about the errors not propagating through here: #722.

**Comment by skp1995** [comment]
People on MacOS: don't forget to add 'cacert.pem' file in the downloaded certifi module to the MacOS Keychain Access.

Initially I tried the solution suggested by @naartjie but still it threw up the same error. However, once I added the 'cacert.pem' to Keychain Access, it worked like a charm

**Comment by a523** [comment]
> People on MacOS: don't forget to add 'cacert.pem' file in the downloaded certifi module to the MacOS Keychain Access.
> 
> Initially I tried the solution suggested by @naartjie but still it threw up the same error. However, once I added the 'cacert.pem' to Keychain Access, it worked like a charm
Hi, @skp1995 , I use mac now , I have the same problem. I have tried  import  'cacert.pem'  to MacOS Keychain Access, why it doesn't works. Is my method wrong, could you describe "How to add  'cacert.pem' file  to the MacOS Keychain Access " in detail？

**Comment by edenhill** [comment]
Add this to your config dict:
```python
'ssl.ca.location': certifi.where()
```

That should hopefully work, also make sure that certifi is up to date: `python -m pip install -U certifi`

**Comment by a523** [comment]
Yeah， I changed the code according to this[ commit ](https://github.com/confluentinc/examples/commit/b2905f4aeb2c1d6d7c1cc4b903bfed582027c8f7) and now it works fine. Thanks @edenhill
