### ISSUE TITLE
Avro(Consumer|Producer) don't support logger parameter

### ISSUE THREAD

**Issue by venthur** [confluentinc/confluent-kafka-python#698]
Description
===========
According to the [Docs](https://docs.confluent.io/current/clients/confluent-kafka-python/#configuration) there is a `logger` parameter that can be passed to Consumer or Producer. But the Avro-counterparts are not supporting it.

How to reproduce
================

Just try: 

```python
>>> kc = confluent_kafka.avro.AvroConsumer(
    {'schema.registry.url': 'http://example.com',
     'group.id': 'test',
     'debug': 'all'},
    logger=logger)
 ```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.2.0', 16908288), ('1.2.1', 16908799)
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [X] Operating system: Debian/Linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by slepkin** [comment]
This is an issue for us, too. Thanks for opening a PR!

**Comment by chrisjbremner** [comment]
For anyone who comes across this, see the workaround suggested in https://github.com/confluentinc/confluent-kafka-python/issues/657#issuecomment-523842549. Also note that https://github.com/confluentinc/confluent-kafka-python/pull/699 is created.
