### ISSUE TITLE
Authorization issues are not loud and clear

### ISSUE THREAD

**Issue by bpradeep20** [confluentinc/confluent-kafka-python#704]
Description
===========

I am not getting any authorization error when I am using ACL based authentication in my Kafka broker and my python client code is authenticated via kerberos. Should I get TOPIC_AUTHORIZATION_ERROR?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by bpradeep20** [comment]
Can anyone please help me to get some sort of exception/error when a client is not authorized for an action with KAfka broker? I am unable to figure it out.

**Comment by bpradeep20** [comment]
Can somebody please help on how to get correct authorization error?

**Comment by rnpridgeon** [comment]
Can you please provide the version of the client you are using along with your client configuration. Specifically I'm curious if you have an `error_cb` registered with your client(for global errors) and/or a delivery callback configured (For per message error reporting). 

Thanks, 
Ryan

**Comment by rnpridgeon** [comment]
#746

**Comment by astoliarov** [comment]
Same issue here.

```python
        self.producer.poll(0)
        
        def delivery_report(err, msg):
            """ Called once for each message produced to indicate delivery result.
                Triggered by poll() or flush(). """
            if err is not None:
                print('Message delivery failed: {}'.format(err))
            else:
                print('Message delivered to {} [{}]'.format(msg.topic(), msg.partition()))

        serialized = self.serializer.dumps(event)
        self.producer.produce(
            self.kafka_topic_name, serialized.encode("utf-8"), on_delivery=delivery_report
        )
```
In this code callback fires when message successfully delivered and do not triggers if I'am trying to write to topic without access

**Comment by edenhill** [comment]
@astoliarov The next version, v1.6.0, will provide improved authentication error reporting.

**Comment by astoliarov** [comment]
@edenhill Thanks, maybe you can tell us when to wait for the new version?

**Comment by edenhill** [comment]
We're aiming for october.

**Comment by edenhill** [comment]
Or january, whichever comes first
