### ISSUE TITLE
Are there missing feature as compared to Kafka's Java client APIs

### ISSUE THREAD

**Issue by bpradeep20** [confluentinc/confluent-kafka-python#707]
I am not able to verify if all features which are supported by KAfka's java client APIs are also available with confluent-kafka python APIs. 

Has someone from community has verified this already. This will help me in avoiding extra efforts if this is already verified.

**Comment by rnpridgeon** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#supported-kips
