### ISSUE TITLE
Provide better documentation for SSL setup (especially dealling with keystores/truststores)

### ISSUE THREAD

**Issue by rootVIII** [confluentinc/confluent-kafka-python#708]
I'm extracting a CARoot.pem, a certificate chain, and a private key from a keystore. This worked for me at one point in time but it is now not working for my consumer authentication. I guess that's besides the point.

In reality there should be better documentation for this procedure. Maybe at least mention that the keystore/truststore cannot be used directly with the Python client like you can with the bin/ scripts.

**Comment by edenhill** [comment]
Addressed here: https://github.com/confluentinc/confluent-kafka-python/pull/709
