### ISSUE TITLE
Python sample doesn't work on CentOS 7

### ISSUE THREAD

**Issue by yokawasa** [confluentinc/confluent-kafka-python#710]
Description
===========

the sample code I've tested - `confluent_cloud.py`
- https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/confluent_cloud.py

I tried to run the sample but the program doesn't go further from [this part](https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/confluent_cloud.py#L77). It doesn't flush and wait forever..  

```
python confluent_cloud.py
```

I tested the same sample on  Ubuntu 18.04.3 LTS and found it workd well with the same configuration.  I don't know why it doesn't work on CentOS

How to reproduce
================

```bash
git clone https://github.com/confluentinc/confluent-kafka-python.git
cd confluent-kafka-python/example
# Added info on 'bootstrap.servers', 'sasl.mechanisms',  'security.protocol',  'sasl.username',   'sasl.password'
vi  confluent_cloud.py
# install prerequisite 
pip install confluent-kafka
pip install "confluent-kafka[avro]"
pip install --no-binary :all: confluent-kafka

# finally run the sample
python confluent_cloud.py
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```bash
$ yum list |grep confluent-kafka
confluent-kafka-2.12.noarch             5.3.1-1                        @Confluent
confluent-kafka-connect-elasticsearch.noarch
confluent-kafka-connect-jdbc.noarch     5.3.1-1                        @Confluent
confluent-kafka-connect-jms.noarch      5.3.1-1                        @Confluent
confluent-kafka-connect-replicator.noarch
confluent-kafka-connect-s3.noarch       5.3.1-1                        @Confluent
confluent-kafka-connect-storage-common.noarch
confluent-kafka-mqtt.noarch             5.3.1-1                        @Confluent
confluent-kafka-rest.noarch             5.3.1-1                        @Confluent
confluent-kafka-2.11.noarch             5.3.1-1                        Confluent
```

 - [ ] Apache Kafka broker version:

 - [ ] Client configuration: `{...}`
```
    'bootstrap.servers': '*****************.gcp.confluent.cloud:9092',
    'sasl.mechanisms': 'PLAIN',
    'security.protocol': 'SASL_SSL',
    'sasl.username': '5CNWEYHVQNX4WFBC',
    'sasl.password': '******************************'
```
 - [ ] Operating system:
```
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

$ python --version
Python 3.6.8
```

 - [ ] Provide client logs (with `'debug': '..'` as necessary)
```
NO LOG came out
```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Might be a problem with CA certs, try adding an `import certifi` and `'ssl.ca.location': certifi.where()` (as client config) to confluent_cloud.py

**Comment by yokawasa** [comment]
@edenhill thank you so much for your advice!! It worked perfect!!

But a question is why the sample works on Ubuntu and MacOS but not CentOS without the additional client config??

**Comment by edenhill** [comment]
The client will use CA certificates to verify the broker's certificate.
The embedded OpenSSL library will look for CA certificates in `/usr/lib/ssl/certs/`
or `/usr/lib/ssl/cacert.pem`. CA certificates are typically provided by the
Linux distribution's `ca-certificates` package which needs to be installed
through `apt`, `yum`, et.al.

If your system stores CA certificates in another location you will need to
configure the client with `'ssl.ca.location': '/path/to/cacert.pem'`. 

Alternatively, the CA certificates can be provided by the [certifi](https://pypi.org/project/certifi/)
Python package. To use certifi, add an `import certifi` line and configure the
client's CA location with `'ssl.ca.location': certifi.where()`.

**Comment by yokawasa** [comment]
@edenhill Thank you for the detailed explanation. Well understood!!
