### ISSUE TITLE
No difference in producer performance with different 'acks' setting

### ISSUE THREAD

**Issue by vikramindian** [confluentinc/confluent-kafka-python#715]
Description
===========

I made some changes to the confluent kafka python producer example application and ran it for doing some performance tests.
I sent messages to a topic (partition = 1, replication-factor = 3) continuously in a loop by setting acks to 1 initially and then to -1.

Test Details:
- message size = 100 bytes
- 5 node cluster

Observations:
1. There is no difference in throughput (msgs/sec) numbers in both the tests (i.e with acks = 1 and acks = -1 and keeping all other configs same)
2. Even on a different topic with higher partitions (like with topic of partitions = 5, replication-factor = 3), the throughput did not change. In all three cases it stood around 80,000 msgs/sec.

Question:

1. Why is this happening? This was not the case with Java API, where acks = 1 setting had higher throughput that acks = -1.
 

How to reproduce
================
Run the below code. I made changes to []( https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/producer.py) and added command line options to accept configs.

`
import argparse
import logging
from   threading                import Lock, Timer
from   confluent_kafka          import Producer

import os
import random
import signal
import time
import uuid
import sys

TEST_DATA      = "TestData"

total_msgs_sent = 0
interval_msgs_sent = 0
lock = Lock()

def get_test_msg_len(msg_size, test_data):
    """
    Returns appropriate length for test message.
    """
    test_data_len = len(test_data)
    count = 0 if msg_size % test_data_len == 0 else 1
    count = count + (msg_size // test_data_len)

    return count

def get_text_msg(msg_size):
    """
    Returns a test message of given length.
    """
    return TEST_DATA * get_test_msg_len(msg_size, TEST_DATA)
	
def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--kafka_hosts",
        type=str,
       required=True,
        help = "The kafka hosts to connect to.")
    parser.add_argument(
        "--client_id",
        type=str,
        required=True,
        help = "The client id for this producer.")
    parser.add_argument(
        "--topic_prefix",
        type=str,
        help = "The topic prefix to used when publishing on multiple topics." 
		       "If --topic_name is also specified then it will take priority.")
    parser.add_argument(
        "--topic_count",
        type=int, default = 5,
        help = "The number of topics to produce on when using --topic_prefix."  
		       "Default is 5.")
    parser.add_argument(
        "--topic_name",
        type = str,
        help = "The topic on which this producer will send messages.")
    parser.add_argument(
        "--num_msgs",
        type=int, default = 10000,
        help = "Total number of messages to be sent. 0 means infinite.")
    parser.add_argument(
        "--msg_size",
        type=int, default = 100,
        help = "Size of each message to be sent, in bytes. Defaults to 100 bytes.")
    parser.add_argument(
        "--sleep_time", 
        type=int, default = 1,
        help = "The interval between two consecutive bursts of messages, in" 
               " seconds.")
    parser.add_argument(
        "--stats_interval",
        type=int, default = 30,
        help = "Time (in seconds) after which stats are printed.")
    parser.add_argument(
        "--msgs_per_burst",
        type = int, default = 100,
        help = "The number of messages to be sent in a single burst before " 
               "sleeping.")
    parser.add_argument(
        "--ack_mode",
        type = str, default = '1',
        help = "Acknowledgement mode for producer. Valid values are 0,1, and -1 ")
    parser.add_argument(
        "--debug_mode",
        type = str,
        help = "Debugging level for producer")

    #parser.set_defaults()i

    opts  = parser.parse_args()

    logging.basicConfig(filename="{}.python_producer.log".format(opts.client_id),
                    format='%(asctime)s %(message)s',
                    filemode='a')
    logger=logging.getLogger()
    logger.setLevel(logging.DEBUG)

    print(opts)

    if not opts.topic_prefix and not opts.topic_name:
        logger.critical("Please specify the topic name or prefix.")
    elif opts.topic_name:
        opts.topic_count = 1

    producer_conf = {}		
    producer_conf['bootstrap.servers'] =  opts.kafka_hosts
    producer_conf['client.id'] = opts.client_id 
    producer_conf['acks'] = int(opts.ack_mode)
    print(producer_conf)
	
    if opts.debug_mode:
        producer_conf['debug'] = opts.debug_mode
			
    def handler(signum, frame):
        print("Interrupted with the signal number: " + str(signum))
        os._exit(os.EX_OK)

    def delivery_callback(err, msg):
        logging.basicConfig(filename="callback_details.log",
                    format='%(asctime)s %(message)s',
                    filemode='a')
        logger1=logging.getLogger()
        logger1.setLevel(logging.DEBUG)

        if err:
            logger1.info('%% Message failed delivery: %s\n' % err)
        else:
            logger1.info('%% Message delivered to %s [%d] @ %d\n' %
                             (msg.topic(), msg.partition(), msg.offset()))

    # Configure to handle the interrupt signal.
    signal.signal(signal.SIGTERM, handler)
    signal.signal(signal.SIGINT, handler)

    def log_stats():
        global total_msgs_sent, interval_msgs_sent, lock
        def get_rate(msgs_sent, interval):
            if interval > 0:
                return round(float(msgs_sent) / (interval * 1000), 2)
            else:
                return 0

        with lock:
            rate = get_rate(interval_msgs_sent, opts.stats_interval)
            logger.info("Interval Count: " + str(interval_msgs_sent) + " @ " + \
                  str(rate) + "K/s, Total Count: " + str(total_msgs_sent))
            interval_msgs_sent = 0

        Timer(opts.stats_interval, log_stats).start()

    Timer(opts.stats_interval, log_stats).start()

    producer = Producer(**producer_conf)

    global total_msgs_sent, interval_msgs_sent, lock

    send_shutdown = False
    send_call_latency = 0

    logger.info("Starting to send messages")

    while True:
        for msg_num in range(opts.msgs_per_burst):
            msg = get_text_msg(opts.msg_size)
            for topic_num in range(opts.topic_count):
                msg_key = random.randrange(1, 10000, 1)
                send_time = time.time() * 1000
                if opts.topic_name:
                    topic_name = opts.topic_name
                else:
                    topic_name = opts.topic_prefix + '-' + str(topic_num)
                try:
                    producer.produce(topic_name, key = str(msg_key), value = msg, callback = delivery_callback)
                except BufferError:
                    logger.warning('Local producer queue is full ({} messages awaiting delivery): try again\n'.format(len(producer)))

                
                send_call_latency += time.time() * 1000 - send_time
                producer.poll(0)

                with lock:
                    total_msgs_sent += 1
                    interval_msgs_sent += 1
                    if opts.num_msgs!=0 and total_msgs_sent >= (opts.num_msgs - 1):
                        send_shutdown = True
                        break
            if send_shutdown:
                break
        if send_shutdown:
            break
        if opts.sleep_time:
            time.sleep(opts.sleep_time)
			
    producer.flush()		
    logger.info("Sent {} messages.".format(total_msgs_sent))	
					
    os._exit(os.EX_OK)

# Call the main function now.
if __name__ == "__main__" : main()
`

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The performance drop with acks=all in a healthy cluster and with proper batching is minimal, and most likely not even noticeable with Python due to its poor runtime performance.

**Comment by vikramindian** [comment]
Is that true even for different topics (say, partitions = 1 vs partitions = 10) ?

**Comment by edenhill** [comment]
If the partitions are spread over multiple brokers the throughput should increase with more partitions.
