### ISSUE TITLE
Recommendations to achieve behavior of max.poll.records in python

### ISSUE THREAD

**Issue by bpradeep20** [confluentinc/confluent-kafka-python#717]
Description
===========
Is there any recommendation to achieve behavior of 'max.poll.records' property of Java consumer in python using consumer.poll()?

**Comment by mhowlett** [comment]
the `consume` method (an alternative to `poll`) has a `num_messages` parameter. however it's recommended to use `poll`. this thread has more information: https://github.com/confluentinc/confluent-kafka-python/issues/580

**Comment by aman-quartic** [comment]
@mhowlett So since `poll` is recommended, is there no way to set `max.poll.records`?
