### ISSUE TITLE
Questions: No messages with consumer's poll() when using 'auto.offset.reset': 'latest' 

### ISSUE THREAD

**Issue by robooo** [confluentinc/confluent-kafka-python#719]
Description
===========

I ran into this issue during the usage of one consumer with  `'auto.offset.reset': 'earliest'` and another one with `'auto.offset.reset': 'latest'`. I use it like:
```
init consumer + producer
subscribe to topic
produce data
flush
poll messages
```
The `'auto.offset.reset': 'earliest'` returns all messages + the new messages which were delivered after the subscription but the  `'auto.offset.reset': 'latest'` will return only `None`'s
Even in the examples you are always using `'auto.offset.reset': 'earliest'`.

**1. Shouldn't be then the earliest default?**

Maybe it's related to https://github.com/confluentinc/confluent-kafka-python/issues/373
because I found that when I do "dummy poll" before produce() then I'm able to get messages with `'auto.offset.reset': 'latest'` poll(). (so that dummy poll + next produced message will set correct offset for the consumer with `'auto.offset.reset': 'latest'`?)
**2. If the logic is to run consumer+subscribe+poll in cycle, in thread and the producer in another one, could you make clear example of this case? with some description why this won't work sequentially**

Note: I know I can use assign() to OFFSET_END, but I wanted to make the usability same and user will just change the `earliest` -> `latest` and in `earliest` scenario he gets all the data + new produced after subscription and in the `latest` only produced after subscription.

I will appreciate any help because I can't find the correct answer to my questions.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):('1.2.0', 16908288), ('1.2.0', 16908543)
 - [ ] Client configuration: `{'enable.auto.commit': True,
                'default.topic.config': {
                    'auto.offset.reset': 'latest'
                },}`
 - [ ] Operating system: Ubuntu 18
 - [ ] Provide client logs (with `'debug': '..'` as necessary)

**Comment by edenhill** [comment]
subscribe() is asynchronous and it may take a long time (depending on broker availability and group rebalancing) for the consumer to actually start fetching messages.

See the answer in #720 for a workaround

**Comment by robooo** [comment]
@edenhill how is this possible:
I just print the topic in the on_assign callback and with `'auto.offset.reset': 'earliest'` or `'auto.offset.reset': 'latest'` it returns offset=-1001 but the earliest fetch first messages but the latest won't last (produced after callback)? why do I need to use assign in callback for latest to fetch them if the partition is -1001 in both? or if you could point me to some documentation I'll be more than happy!
