### ISSUE TITLE
produce() right after assign() makes poll unable to get messages

### ISSUE THREAD

**Issue by robooo** [confluentinc/confluent-kafka-python#720]
How to reproduce
================
Create producer + create consumer as described below, assign the consumer to the topic partition with OFFSET_END right after this produce some message (use flush to wait till it will be delivered) to topic and then try to poll the message. 

-> empty list is returned
-> when I use 5 second sleep right after the assign() the message is polled without any issue
in documentation there is after the assignment "starts consuming.", so is that consuming start interrupted with the produce call? or the assignment was not complete? is there some other way how to fix this instead of sleep?

Thank you!

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):('1.2.0', 16908288), ('1.2.0', 16908543)
 - [ ] Client configuration: `{'enable.auto.commit': True,
                'default.topic.config': {
                    'auto.offset.reset': 'latest'
                },}`
 - [ ] Operating system: Ubuntu 18
 - [ ] Provide client logs (with `'debug': '..'` as necessary)

**Comment by edenhill** [comment]
assign() is asynchronous: it tells the fetcher to start fetching messages for the assigned partitions, but before it can do so the fetcher needs to look up the partition leaders, initial offsets, etc.

Sleeps will not work reliably since it can take more than 5s to perform the above mentioned steps in case there is a temporary network outage or similar.

What you could do is manually look up the current end offsets of the partitions prior to producing and then pass those offsets as starting points to assign, you would use get_watermark_offsets() for this purpose.

**Comment by robooo** [comment]
@edenhill thank you for the fast response! but related to https://github.com/confluentinc/confluent-kafka-python/issues/719 
I can get the last offset with get_watermark_offsets() but how I can use it for subscribe()? only via callback on_assign?

**Comment by edenhill** [comment]
Yes, from on_assign.

**Comment by robooo** [comment]
@edenhill so I've tried the assign at callback with consumer `'auto.offset.reset': 'latest'`

```
def callback_fun(self, consumer, topic_partitions):
        for partition in topic_partitions:
            offset = consumer.get_watermark_offsets(partition)
            partition.offset = offset[1]  #this should set the latest offset
        consumer.assign(topic_partitions)
```
and after subscribe() I run produce() then poll(), but still don't get any messages, any hints?

**Comment by robooo** [comment]
@edenhill have you found some issue or what am I doing wrong? I'm bit afraid I need to wait for this callback in my main program right? if yes you can close this issue
