### ISSUE TITLE
No route to host failure

### ISSUE THREAD

**Issue by joukosusi** [confluentinc/confluent-kafka-python#721]
Description
===========
i see a  "No route to host failure" when use a nginx to forward connections to kafka. Could u help me on this?

...
%7|1574255921.562|REQERR|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: HeartbeatRequest failed: Local: Broker transport failure: actions Retry
%7|1574255921.562|RETRY|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Retrying HeartbeatRequest (v0, 95 bytes, retry 1/2, prev CorrId 0) in 100ms
[2019-11-20 21:18:41,562][36115][140412040099648-MainThread][ERROR]<kafka.py:737> _TRANSPORT(-195) >> GroupCoordinator: Connect to ipv4#20.123.4.96:9092 failed: No route to host (after 7026ms in state CONNECT)
%7|1574255922.020|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: Group "RAW_DATA_ROUTER_SYSTEM": no broker available for coordinator query: intervaled in state query-coord
...

kafka hosts config: kafka-sasl-server 20.123.4.98
nginx hosts config: kafka-sasl-server 20.123.4.96
consumer client hosts config:  kafka-sasl-server 20.123.4.96

nginx config:
...
stream {
    log_format proxy '$remote_addr [$time_local] '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time "$upstream_addr" '
                 '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';
    access_log  logs/tcp-access.log proxy;

    upstream ssl{
        hash $remote_addr consistent;
        server 20.123.4.98:9092 max_fails=3 fail_timeout=10s;
    }
    server {
        listen 9092;
        proxy_timeout 20s;
        proxy_pass ssl;
    }
}
...

How to reproduce
================

    import functools
    logger=log.LogHandler("test_kafka", path=".", log_level="DEBUG")
    config = {
        'sasl.mechanism': 'SCRAM-SHA-256',
        'sasl.username': 'test',
        'sasl.password': '123',
        'ssl.key.location': '/root/ssl/client.key.unsecure',
        'ssl.ca.location': '/root/ssl/ca-cert',
        'ssl.certificate.location': '/root/ssl/client.crt',
        'ssl.key.password': 123456,
        'group.id':'RAW_DATA_ROUTER_SYSTEM',
        'bootstrap.servers': "kafka-sasl-server:9092",
        'security.protocol': "SASL_SSL",
        'api.version.request': True,
        'broker.version.fallback': "1.1.1",
        'log.connection.close': False,
        'heartbeat.interval.ms': 10000,
        'log_level': 6,
        'message.max.bytes': 314572800,
        'statistics.interval.ms': 0,
        'session.timeout.ms': 60000,
        'debug': 'all',
        'enable.auto.commit': True,
        'auto.commit.interval.ms': 1000,
        'fetch.min.bytes': 1024 * 1024,
        'fetch.wait.max.ms': 1000,
        'fetch.message.max.bytes': 1048576,
        'error_cb': functools.partial(_error_cb, logger),
        'default.topic.config': {
            'auto.offset.reset': 'earliest',
        },
    }
    _consumer = Consumer(**config)
    _consumer.subscribe(["TOPIC_ANALYSIS_OFFLINE_JOB_RESULT_PIPE"])
    while True:
        result = _consumer.poll(timeout=0.00001)
        if not result:
            continue
        if result.error():
            if result.error().code() == KafkaError._PARTITION_EOF:
                logger.warning('{0} [{1}] reached end at offset {2}'.format(
                    result.topic(), result.partition(), result.offset()
                ))
            else:
                logger.error('encourage error:\n{}'.format(json.dumps(
                    {
                        'name': result.error().name(),
                        'code': result.error().code(),
                        'description': result.error().str()
                    }, indent=1)))
        else:
             print(result)

logs
[kafka.log](https://github.com/confluentinc/confluent-kafka-python/files/3869468/kafka.log)

Checklist
=========
Please provide the following information:

 - [✔ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.2.0 1.2.0
 - [✔ ] Apache Kafka broker version: 1.1.1
 - [ ✔] Client configuration: `{...}`
 - [ ✔] Operating system: centos7
 - [ ✔] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
` Connect to ipv4#20.123.4.96:9092 failed: No route to host (after 7026ms in state CONNECT)`

That means there is no network route between the client system and the broker.
https://www.techjunkie.com/no-route-to-host-error-in-linux-what-to-do/
