### ISSUE TITLE
Producer does not produce on AWS Lambda

### ISSUE THREAD

**Issue by RohitJacob** [confluentinc/confluent-kafka-python#736]
Description
===========
I’ve used a virtualenv and installed confluence Kafka via pip3 install. I deploy my zip to lambda with a connect statement with SSL and it runs that line without any issues. But when I try to produce a message, it times out.
I checked the VPC and everything, it wouldn’t connect if it weren’t in the same vpc as my Kafka, so is there something I’m missing? Even the poll function completes running. Just the produce function that doesn’t.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is usually an issue with the broker's advertisted.listeners not being reachable from the client host, see this blog: https://rmoff.net/2018/08/02/kafka-listeners-explained/

You can troubleshoot the issue by enabling `'debug':'broker'` on your producer and capturing the stderr logs.

**Comment by rohitgcs** [comment]
hi @edenhill I added debug broker and it seems like its an ssl problem maybe
These are the logs

```
%7|1576014826.041|CONNECT|carrierapiPipeline#producer-1| [thrd:ssl://b-3.kafka.abcdefg.c3.kafka.us-west-2.amazonaws.]: ssl://b-3.kafka.abcdefg.c3.kafka.us-west-2.amazonaws.com:9094/bootstrap: Connecting to ipv4#10.31.162.81:9094 (ssl) with socket 12

%7|1576014826.049|CONNECT|carrierapiPipeline#producer-1| [thrd:ssl://b-3.kafka.abcdefg.c3.kafka.us-west-2.amazonaws.]: ssl://b-3.kafka.abcdefg.c3.kafka.us-west-2.amazonaws.com:9094/bootstrap: Connected to ipv4#10.31.162.81:9094

%7|1576014826.053|BROKERFAIL|carrierapiPipeline#producer-1| [thrd:ssl://b-3.kafka.abcdefg.c3.kafka.us-west-2.amazonaws.]: ssl://b-3.kafka.abcdefg.c3.kafka.us-west-2.amazonaws.com:9094/bootstrap: failed: err: Local: SSL error: (errno: Success)

%7|1576014826.089|STATE|carrierapiPipeline#producer-1| [thrd:ssl://b-3.kafka.abcdefg.c3.kafka.us-west-2.amazonaws.]: ssl://b-3.kafka.abcdefg.c3.kafka.us-west-2.amazonaws.com:9094/bootstrap: Broker changed state CONNECT -> DOWN
```

I run my kafka using MSK (so fully managed - so assuming advertised.hosts are set properly) and I am able to connect using the below code from an ec2 server using a pem file

Below is my code:

```

#Produce data to a topic in kafka
def queueProducer(TO_TOPIC, data):
	producer = Producer({'bootstrap.servers': server,
				'client.id': 'abc',
				'security.protocol': 'ssl',
				'ssl.certificate.location': 'some.pem'})
	logger.debug("Connected to Kafka")
	try:
		# Trigger any available delivery report callbacks from previous produce() calls
		producer.poll(0)
		logger.debug("Polling for leftover report callbacks")
		# Asynchronously produce a message, the delivery report callback
		# will be triggered from poll() above, or flush() below, when the message has
		# been successfully delivered or failed permanently.
		producer.produce(TO_TOPIC, data.encode('utf-8'), callback=delivery_callback)
	except Exception as e:
		logger.error('Kafka Exception: %s', e)
	finally:
		# Wait for any outstanding messages to be delivered and delivery report
		# callbacks to be triggered.
		producer.flush()
		logger.debug("Producer flushed")
	return
```

**Comment by edenhill** [comment]
If you were to register an error_cb you would get the actual SSL error.
Yes, this is a known issue that we're looking to fix, making sure errors are propagated correctly.

**Comment by rohitgcs** [comment]
So is there any reason why the SSL is failing? It worked fine on a server (EC2) but the minute I put the pem along with this producer on lambda (same VPC as Kafka) it fails. Is there something I'm missing?

**Comment by edenhill** [comment]
Please add the error_cb so we can see the actual SSL error. Thanks

**Comment by rnpridgeon** [comment]
It's hard to say without the error_cb configured (possibly even with) but one possibility is that you have client authentication enabled with MSK. Based on the link below MSK uses mTLS for this so you will need to configure your client appropriately. 

https://docs.aws.amazon.com/msk/latest/developerguide/msk-authentication.html

In your case that means supplying the producer with its private key and certificate.

**Comment by nadeesh-garg** [comment]
> So is there any reason why the SSL is failing? It worked fine on a server (EC2) but the minute I put the pem along with this producer on lambda (same VPC as Kafka) it fails. Is there something I'm missing?

Facing the same issue:
error_cb is:
`KafkaError{code=_SSL,val=-181,str="sasl_ssl://<cloud_id>.ap-southeast-1.aws.confluent.cloud:9092/bootstrap: SSL handshake failed: s3_clnt.c:1269: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:  (after 14ms in state CONNECT)"}`

**Comment by edenhill** [comment]
Easiest fix is to install certifi (pypi) on the target host and set ssl.ca.location to `certifi.where()`, see https://github.com/confluentinc/confluent-kafka-python#ssl-certificates
