### ISSUE TITLE
Messages are not pushing into the queue

### ISSUE THREAD

**Issue by manasaDivakaraRao** [confluentinc/confluent-kafka-python#740]
Description
===========
I start the producer when service starts and reuse the connection
I am doing producer.poll(0) after each producer. But still, messages are not going into the topic.

kafka logs

7|1576146447.418|TOPIC|rdkafka#producer-1| [thrd:app]: New local topic: TOPIC
%7|1576146447.418|TOPPARNEW|rdkafka#producer-1| [thrd:app]: NEW TOPIC [-1] 0x3640ba0 (at rd_kafka_topic_new0:393)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Please provide you client version, configuration and client logs per the checklist. It would be helpful if you could set `{'debug' : 'broker, topic, metadata'}` prior to generating the logs.

**Comment by manasaDivakaraRao** [comment]
python version - 3.7
confluent-kafka - 1.2.0

Configuration

Producer(
    {
        "bootstrap.servers": KAFKA_BROKER_URL,
        "default.topic.config": {"acks": "all"},
        "retries": 5,
        "queue.buffering.max.messages": 10,
        "batch.num.messages": 1,
        "debug": "msg,topic",
    }
)

Code to push the messages

class KafkaTest(APIView):
    def delivery_report(self, err, msg):
        """ Called once for each message produced to indicate delivery result.
            Triggered by poll() or flush(). """
        if err is not None:
            loggers
        else:
            print("Message delivered to {} [{}]".format(msg.topic(), msg.partition()))
           

    def get(self, request):
        try:
            self.data ={'hello':124}
            producer = settings.KAFKA_CONNECTION
            topic = TOPIC
            import json

            producer.produce(
                topic, (json.dumps(self.data)), callback=self.delivery_report
            )
            producer.poll(0)
        except Exception as e:
            logger
            status = False

        return None


Am calling above function as https call

**Comment by rnpridgeon** [comment]
> Am calling above function as https call

Can you elaborate on that a bit? 

Kafka does not actually speak HTTP although it does support wire encryption with TLS(SSL). Perhaps this is what you meant? If that is the case you do not have your client configured correctly. 

See https://github.com/confluentinc/confluent-kafka-python#ssl-certificates for more on configuring clients with TLS. 

I also recommend you configure your producer with an `error_cb` to report global errors to make debugging things a bit easier. This callback will report any global errors which may happen prior to message delivery failures. 

```python
def error_cb(err):
    print('Error: %s' % err)

p = Producer({ ..., 
               error_cb=error_cb})
```

**Comment by pranavrth** [comment]
Closing this issue as there is no update on the same. Please raise a new one if required.
