### ISSUE TITLE
Need manylinux1 wheels for 1.3.0

### ISSUE THREAD

**Issue by kerrick-lyft** [confluentinc/confluent-kafka-python#751]
Description
===========
For `confluent-kafka` 1.2.0 and earlier, `manylinux1` wheel files are provided on PyPI (see https://pypi.org/project/confluent-kafka/1.2.0/#files).

For 1.3.0, no `manylinux1` files were published, only `manylinux2010` (see https://pypi.org/project/confluent-kafka/1.3.0/#files).

In some of our environments at Lyft, we use an older version of `pip` that does not support the `manylinux2010` files, only the older `manylinux1` files, and so instead of using the binary wheel package, `pip` tries to compile the source package. This prevents us from using 1.3.0 or later of the package, because we do not have the necessary environment set up to compile the package from source.

How to reproduce
================
1. Install `pip==1.18.1` or earlier.
2. Install `confluent-kafka` using pip.

pip will attempt to build confluent-kafka from source.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.3.0
 - [x] Apache Kafka broker version: N/A
 - [x] Client configuration: N/A
 - [x] Operating system: Ubuntu Xenial 16.04.6 LTS
 - [x] Provide client logs (with `'debug': '..'` as necessary): N/A
 - [x] Provide broker log excerpts: N/A
 - [x] Critical issue: No

**Comment by rnpridgeon** [comment]
Thanks for reporting this @kerrick-lyft, 

I have put `maylinux1` wheels on `test.pypi` for now however I only have the narrow-width unicode variant available today (abi flag `m`). I'm working on getting the wide-unicode wheels built now (abi flag `mu`) which are vastly more common. Once I have them both building correctly successfully I'll get them uploaded to pypi proper

**Comment by rnpridgeon** [comment]
Update: The wide-unicode binary compatible wheels are up on test.pypi. Cursory tests seem to suggest they are working fine. Once I've run all of our standard packaging tests against it I'll get both variants added to the proper pypi for distribution.

**Comment by afalko** [comment]
@rnpridgeon: Any news on this? :)

**Comment by rnpridgeon** [comment]
PR has been merged and wheels have been uploaded.

**Comment by kerrick-lyft** [comment]
@rnpridgeon thanks! We will test on our end.

In general, can we expect that in the future, whenever a new confluent-kafka release goes out, it will include manylinux1 wheels? In our CI system, we have some tests that always pull the latest version of dependencies (including confluent-kafka), and in this environment the source release doesn't build because the necessary Kafka header files aren't installed. So if, in the future, confluent-kafka 1.4.0 is released with only source and manylinux2010 packages, and then manylinux1 packages are released e.g. a day later, our CI will break in that 1-day interval. If this disruption is expected in future releases we will have to work around it on our side.

**Comment by rnpridgeon** [comment]
Yes you can expect to see continued support for manylinux1 from us in the future.  We actually do have automated tests for verifying wheels however as part of that validation it updates pip to a current version which is how we missed this. I'll add some additional logic to sanity check the contents of the wheelhouse as an additional measure. 

https://github.com/confluentinc/confluent-kafka-python/blob/master/tools/test-manylinux.sh#L54


https://github.com/confluentinc/confluent-kafka-python/blob/master/tools/test-manylinux.sh#L54

**Comment by kerrick-lyft** [comment]
This is fixed for us.

**Comment by rnpridgeon** [comment]
Thanks, adding a script for validating the contents of the wheel dir to be run as part of the test manylinux test.
