### ISSUE TITLE
py38 windows wheels for 1.3.0

### ISSUE THREAD

**Issue by scarchik** [confluentinc/confluent-kafka-python#753]
Description
===========
It will be great to have wheels for new python 3.8 for Windows. 

How to reproduce
================

`pip3.8.exe install confluent-kafka==1.3.0`

pip will attempt to build confluent-kafka from source and fail with error:

> fatal error C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.3.0
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Windows 10 x64
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue: No

**Comment by rnpridgeon** [comment]
Thanks, we are working on getting Appveyor to build these properly. It high up on the priority list but just behind transaction(eos) support which should be wrapping up soon.

**Comment by ofek** [comment]
@rnpridgeon Any progress?

**Comment by hari010904068** [comment]
I face the same problem mentioned , just curious to know if there was any progress made. Thank you.

**Comment by mschuch** [comment]
Is there a workaround to install the library on Windows? Thanks.

**Comment by alexey-kleymenov** [comment]
Looking for a solution or workaround as well, the same setup as mentioned above (Windows 10 + Python38).

**Comment by dingobar** [comment]
Hi guys, just wanted to hear if there has been any progress towards this?

**Comment by Iamcerba** [comment]
> Hi guys, just wanted to hear if there has been any progress towards this?

+1

**Comment by DenisBochert** [comment]
> Hi guys, just wanted to hear if there has been any progress towards this?

+1

**Comment by edenhill** [comment]
The wheel building situation on Windows is a bit of a mess with various prehistoric MSVC toolchains and a decaying Python2 ecosystem, but we're working on it.

**Comment by codingadvocate** [comment]
Hi @edenhill or others at Confluent:

Is there a product roadmap for the client release/support on Windows?

Details for why I ask, follows:

I switched our enterprise application code base from using a previous python Kafka client to this one, about 2 years ago - since it was closer to the vendor.  Python 3.7 worked with this client, but it's been over a year since 3.8 came out - where nothing worked, and now 3.9 is out.  It's been 2 years and now, good or bad - I have the recurring, open-source decision to make on dependent technologies.  I need to decide if there is an active Kafka Python client on Windows, or if I need to move us to something else.

Please understand, I'm simply trying to determine what's best for the future in this space.  Thanks!

**Comment by ryanscovill** [comment]
I had success building the Windows 3.8 wheels locally.  Hopefully this will help in the meantime until the build system adds support.

1. Clone this repo.  All commands are run in <repo> on a Windows 10 machine.

2. Install Python (Must be in these directories)
Install Python 3.8 32 bit to `C:\Python38`
Install Python 3.8 64 bit to `C:\Python38-x64`

3. Install Microsoft Build Tools
Instructions from: https://wiki.python.org/moin/WindowsCompilers
   - Install Microsoft Build Tools for Visual Studio 2019.
   - In Build tools, install C++ build tools and ensure the latest versions of MSVCv142 - VS 2019 C++ x64/x86 build tools and Windows 10 SDK are checked.
   - The setuptools Python package version must be at least 34.4.0.

4. Add Python 38 to the list of supported python versions
Add `38` to Line 16 and remove the other versions in `tools/windows-install-librdkafka.bat`
 
4. Add the librdkafka to the python includes directories.
Run `tools/windows-install-librdkafka.bat 1.5.0 dest`

5. Build the wheels to dist/
`C:\Python38\python.exe setup.py bdist_wheel`
`C:\Python38-x64\python.exe setup.py bdist_wheel`

7. Add the dlls to the wheels.  Make sure 7zip is installed and on the PATH.
Bat script: https://gist.github.com/ryanscovill/0cc93f84606b2e751315e330badec235

8. Built windows wheels should be in `dist/`

**Comment by MagicJack** [comment]
I follow the steps to build ver. 1.6.0 for python 3.9 and python 3.8 successfully.
And, there're 2 points new comers may missing:

1. You will need `nuget.exe` installed. (from [https://nuget.org](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe)
2. Make sure you've package `wheel` installed by `pip install wheel` for each version of python you want to compile.

Great thanks to @ryanscovill

**Comment by edenhill** [comment]
@MagicJack Did you try the Py3.8 wheels for windows on PyPi?

**Comment by MagicJack** [comment]
I'm trying to compare my version from the official one. And hoping I didn't do it wrong.

**Comment by scarchik** [comment]
Seems like everything is OK now. I successfully installed confluent-kafka through official PyPi.
Do you think about making wheels for py3.9 as well? It will be great to have them.

Great thanks to you guys.

**Comment by MagicJack** [comment]
@edenhill I've wrote a letter to contact@confluent.io (is that you?), to describe how to make build-wheels.bat run again.
Maybe you can solve the problem of build and test on windows platform soon.

**Comment by edenhill** [comment]
I think it'll be quickier if you shared your improvements to the build script as a PR on this repository.

**Comment by MagicJack** [comment]
OK, I'll pull this request, and push my change ASAP.

**Comment by MagicJack** [comment]
@edenhill PR have been made.

**Comment by pranavrth** [comment]
Windows wheels are provided with all the releases. Closing this issue.
