### ISSUE TITLE
Docs missing for confluent_kafka.avro

### ISSUE THREAD

**Issue by cdeil** [confluentinc/confluent-kafka-python#757]
The `confluent_kafka.avro` content like `AvroProducer`, `AvroConsumer`, ... currently do not appear in the `confluent_kafka` docs.

This makes it hard to learn and use them, without any info about them.

I see there's a `.. automodule:: confluent_kafka.avro` here:

https://github.com/confluentinc/confluent-kafka-python/blob/master/docs/index.rst#avro

However in the rendered HTML docs that section is currently empty:

https://docs.confluent.io/current/clients/confluent-kafka-python/index.html#avro

Another way to check if e.g. `AvroProducer` shows up in the docs is this, which currently yields no match:

https://docs.confluent.io/current/clients/confluent-kafka-python/search.html?q=avroproducer&check_keywords=yes&area=default

Probably this is easy to fix, just some `__all__` list or something in the Sphinx config missing?

**Comment by rnpridgeon** [comment]
I believe this is fixed with this commit 

https://github.com/confluentinc/confluent-kafka-python/commit/bbf61f74349b56cb165fef711c6e1780e8a113dd 

but the main confluent docs still point to an older version. I'm working with our docs team now enable versioning similar to that of read the docs so we can more readily fix these issues and keep things up to date. 

Thanks for reporting this.

**Comment by beregon87** [comment]
+1 for published up-to-date documentation. The current version available on https://docs.confluent.io/current/clients/confluent-kafka-python/index.html is over 6 months old.

**Comment by cdeil** [comment]
Any news?

Is moving docs to Readthedocs an option?
Their support for multiple versions hosting is very good and not easy to replicate.

Alternatively, maybe you could do a one time manual update, given that implementing a better process likely will take time?

**Comment by cdeil** [comment]
I see v1.4 is out: https://github.com/confluentinc/confluent-kafka-python/releases/tag/v1.4.0

@rnpridgeon - Any chance to get the docs updated?

**Comment by pranavrth** [comment]
The were updated though AvroConsumer and AvroProducer are deprecated in favor of AvroSerializer and AvroDeserializer. Closing this issue.
