### ISSUE TITLE
Document schema_registry option

### ISSUE THREAD

**Issue by cdeil** [confluentinc/confluent-kafka-python#758]
Could you please document the `schema_registry` option in the `AvroConsumer` and `AvroProducer`?

I think it must be a [CachedSchemaRegistryClient](https://github.com/confluentinc/confluent-kafka-python/blob/df649a44a4c97a72b062e38d2b0172836e5bb9d6/confluent_kafka/avro/cached_schema_registry_client.py#L47)?

https://github.com/confluentinc/confluent-kafka-python/blob/df649a44a4c97a72b062e38d2b0172836e5bb9d6/confluent_kafka/avro/__init__.py#L93-L107

https://github.com/confluentinc/confluent-kafka-python/blob/df649a44a4c97a72b062e38d2b0172836e5bb9d6/confluent_kafka/avro/__init__.py#L16-L30

x-ref #757

**Comment by rnpridgeon** [comment]
Standby we have an avro refactor in the works which will include improved documentation.

**Comment by pranavrth** [comment]
The doc is not updated as these APIs are deprecated in favor of AvroSerializer and AvroDeserializer. Closing this issue.
