### ISSUE TITLE
Memory Issue when consumer backlog is high

### ISSUE THREAD

**Issue by arunshankerprasad** [confluentinc/confluent-kafka-python#759]
Description
===========

We noticed an issue with the consumers using up a lot of memory when the backlog/lag increases. We were able to consistently reproduce this as well. Also confirmed that this is not application specific, since we commented out all of our application code and it was just polling messages and doing nothing with it.

The issue seems to only happen if we have a huge backlog/lag built up in Kafka. In our use-case, we saw that the backlog was around 20K messages, each of about 175KB in size, all JSON strings. We run the application in Kubernetes, and the pods have a request limit of 1GB RAM, when we have a backlog of messages, as soon as the pod starts up, it seems to be requesting for over 1GB of RAM, causing the pod to be terminated. We are only polling for *1 message* at a time, so it should not have required this much resources. We did try updating several config values, like setting `fetch.message.max.bytes`, `max.partition.fetch.bytes`, but nothing seems to have worked.

Unclear as to how the consumer works internally, does it build a buffer internally, even if we are polling for 1 message at a time?

To resolve this issue we switched to using the [kafka-python](https://github.com/dpkp/kafka-python/) library, and are not seeing any memory issues when using it.

How to reproduce
================

* Build a backlog/lag in Kafka for a topic
* Start the consumer and poll for 1 message at a time
* Monitor memory usage, it will spike based on the backlog

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka: 0.11.6 & 1.1.0 librdkafka: 1.0.0
 - [x] Apache Kafka broker version: 1.1.0
 - [x] Client configuration: `{"bootstrap.servers":[],"group.id":"group_id","auto.offset.reset":"earliest","max.poll.interval.ms":300000}`
 - [x] Operating system: CentOS 7.5
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
by default, the consumer very aggressively caches messages in the background (is tuned for v.high throughput). To reduce memory usage, tune down `queued.max.messages.kbytes` (which is the maximum cache size **per partition**). By default, this is set to 1Gb.

**Comment by arunshankerprasad** [comment]
Hi @mhowlett,

Thank you for the response. I will try this out and close this.

**Comment by arunshankerprasad** [comment]
Set `queued.max.messages.kbytes` to 100MB and it looks good, Thank you @mhowlett.

**Comment by rj-cord4** [comment]
Hello @mhowlett 

Can you please tell me where can I find `queued.max.messages.kbytes` setting? I'm using Ubuntu 20.04. I tried to find but no luck.

**Comment by pklejch** [comment]
> Hello @mhowlett
> 
> Can you please tell me where can I find `queued.max.messages.kbytes` setting? I'm using Ubuntu 20.04. I tried to find but no luck.

@rj-cord4 : You set `queued.max.messages.kbytes` when creating Consumer instance
```python
from confluent_kafka import Consumer

c = Consumer({
    'bootstrap.servers': 'mybroker',
    'group.id': 'mygroup',
    'auto.offset.reset': 'earliest',
    'queued.max.messages.kbytes': 1024,  # <--- set it here
})
```

**Comment by mvadde** [comment]
We are facing the same issue in Sarama Golang consumers. What to be set for `queued.max.messages.kbytes`  ?
