### ISSUE TITLE
close consumer without committing

### ISSUE THREAD

**Issue by patrickviet** [confluentinc/confluent-kafka-python#76]
Documentation says Consumer.close() commits all offsets
But what if something failed in my processing/batch? Say, my disk was full, I was able to read the messages but not write my processing of them? I'd like to be able to exit properly... And them maybe clear my disk, and then relaunch and be able to re-process, not pretend that the unprocessed messages were processed - which is the current undesirable behavior. 

Is there some way to close() without committing?

--thanks

**Comment by edenhill** [comment]
In these cases you typically disable auto commits (`"enable.auto.commit": False`) and do manual commits `consumer.commit(async=True)` after succesful processing.

**Comment by patrickviet** [comment]
Yes, it's what I do. And I want to close()  WITHOUT commit
But docs say that:

close()
Close down and terminate the Kafka Consumer.

Actions performed:

Stops consuming
**Commits offsets**
Leave consumer group
Return type:	None


I want to stop consuming, leave consumer group, but not commit the offset.
It doesn't give me the choice to not do so

**Comment by edenhill** [comment]
It wont commit offsets if enable.auto.commit is turned off.

**Comment by patrickviet** [comment]
In my observations, it still does commit when I call close(), regardless of my options.
According to what you just said, this code sample should never commit, since I have run no commit() and I have set autocommit to false

Here is a sample to show it

```python
from confluent_kafka import Consumer, KafkaError

def on_assign(c,part):
  print "assign", part

def on_commit(err, part):
  print "commit", part

c = Consumer({
  'bootstrap.servers':'***',
  'group.id':'patricklaptop2',
  'default.topic.config': {'auto.offset.reset':'smallest', 'auto.commit.enable':False },
  'topic.metadata.refresh.interval.ms': 20000,
  'on_commit':on_commit
})

c.subscribe(['mytopic'],on_assign=on_assign)

while True:
  msg = c.poll(timeout=1.0)
  if msg is None:
    continue

  print "Received message with key: %s" % msg.key()
  c.close()
  exit()
```

When I run it, it does commit.

```
$ python simple_consumer.py
assign [TopicPartition{topic=mytopic=0,offset=%lld,error=%s}]
Received message with key: ***
commit [TopicPartition{topic=mytopic=0,offset=%lld,error=%s}]
```

**Comment by edenhill** [comment]
Aah, the config property that you want to use is named `enable.auto.commit` and it is a global config property.
The one you use, `auto.commit.enable` in the `default.topic.config` dict is for the legacy consumer.
This is what happens when you try to be both backward and forward compatible with the Scala/Java clients that renamed some of their properties when the new clients were rewritten. :(

**Comment by patrickviet** [comment]
Right now I see it. Thanks!

Maybe it would make sense in this case to add this mention to the documentation of close()
Currently it says

```
close()
Close down and terminate the Kafka Consumer.

Actions performed:

Stops consuming
Commits offsets
Leave consumer group
Return type: None
```


My suggestion would be to make it evolve for it do be:

```
close()
Close down and terminate the Kafka Consumer.

Actions performed:

Stops consuming
Commits offsets (default) except if the Consumer property 'enable.auto.commit' is set to False
Leave consumer group
Return type: None
```

**Comment by edenhill** [comment]
Wanna create a PR? :)

**Comment by patrickviet** [comment]
Yes!
