### ISSUE TITLE
Produce errors not causing catchable errors

### ISSUE THREAD

**Issue by DrStrangepork** [confluentinc/confluent-kafka-python#762]
Description
===========
We recently experienced a zookeeper issue which prevented me from writing to my kafka cluster. How this exhibited to me was the following callback error on `flush()`:

```
KafkaError{code=NOT_ENOUGH_REPLICAS,val=19,str="Broker: Not enough in-sync replicas"}
```

This did not result in either a `KafkaError` or a `KafkaException`, and `producer.flush()` returned 0 which doesn't reflect the success or failure of the method. I only found out about it when I saw nothing being added to the kafka topic. I'm not sure whether my code is not catching errors correctly or confluent-kafka is not passing them or something else.

How to reproduce
================
```
from confluent_kafka import Producer
from kafka.errors import KafkaError

def get_producer_config():
    return Producer(get_config())

def get_config():
    conf = {
        'bootstrap.servers': 'localhost:9092',
        'acks': 'all',
    }
    return conf

try:
    producer = get_producer_config()
    producer.produce('test', 'test message from local app')
    producer.flush()
except KafkaError as error:
    print(str(error))
```
The above code doesn’t produce to the topic because replication factor is 1, `min.insync.replicas` is set to 2 and acks = all, but we have no indication of a failure; the producer doesn’t return any error.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`('1.2.0', 16908288)` and `('1.2.0', 16908543)`):
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `{'bootstrap.servers': 'localhost:9092','acks': 'all'}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue: NO

**Comment by rnpridgeon** [comment]
`Producer.produce` is an asynchronous operation; an application may use the `on_delivery` argument to pass a function (or lambda) that will be called from `poll()`(or flush()`) when the message has been successfully delivered or permanently fails delivery. This will not raise an exception but it will inform you of the failure. 

https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Producer.produce

**Comment by DrStrangepork** [comment]
The `KafkaError` in the **Description** is coming from the `on_delivery` argument, so clearly `Producer.produce` is failing. I'm not sure why a failure would not qualify as an exception.

**Comment by rnpridgeon** [comment]
Error handling is deferred to the application with the `on_delivery` callback. This done to facilitate the asynchronous behavior of the `produce` method. Keep in mind that there is no guarantee on the ordering of delivery reports in the response queue or how long it will take for a delivery report to be generated. Throwing an exception upon receipt of a failed message delivery report would result in undefined behavior which is less than desirable.

**Comment by pranavrth** [comment]
Closing the issue as the explanation is provided by Ryan. Please create a new issue if required more help.
