### ISSUE TITLE
How should a consumer handle message errors in `if consumer.poll(1.0).error()` ?

### ISSUE THREAD

**Issue by mkmoisen** [confluentinc/confluent-kafka-python#767]
Description
===========

This is not an error report - just a question on best practices.

What should a consumer do in a loop if it detects that a message has an error, and doesn't want to lose any data?

Say you have some loop like:

    batch = []
    offsets = {}
    while True:
        msg = consumer.poll(1.0)

        if msg:
            if msg.error(): 
                # Is it safe to continue here? Could it lose any data?
                continue
            offets[message.partition()] = message.offset() + 1
            batch.append(msg.value())

        if len(batches) > 20:
            commit_to_rdbms(batches, offsets)
            batches.clear()

Are the errors safe to ignore in a loop (e.g. with `continue`)? For example, if these errors were always timeout related errors it might be safe to ignore.

Or, if you don't want to skip any message/offset, do you need to break out of the loop without committing offsets and try again later?

Going through the librdkafka code, I saw three possibilities for an error to be set on the return message, one in `rd_kafka_consumer_poll` and two in `rd_kafka_consume0` . From this I gather that it would be OK to just `continue` instead of breaking out of the loop, but I am not positive.

[This](https://github.com/edenhill/librdkafka/blob/7098d5bdd5f5aed6383244c0f1092f3f9232430c/src/rdkafka.c#L2880) which returns an error for an invalid kafka group. This isn't a concern for losing data.

[This](https://github.com/edenhill/librdkafka/blob/7098d5bdd5f5aed6383244c0f1092f3f9232430c/src/rdkafka.c#L2787), I think means that the callback was somehow called before this line of code which shouldn't happen normally. I'm not using callbacks so this might not apply to my case.

[This](https://github.com/edenhill/librdkafka/blob/7098d5bdd5f5aed6383244c0f1092f3f9232430c/src/rdkafka.c#L2799) checks for timeouts and sets the error. I also doubt this is a concern for losing data.

How to reproduce
================

N/A

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.2.0
 - [ ] Apache Kafka broker version:
 - [X] Client configuration: `{...}` {'bootstrap.servers': ..., 'group.id': ...., 'auto.offset.reset': 'earliest', 'enable.auto.commit': false, 'isolation.level': 'read_committed', 'max.poll.interval.ms': '60000'
 - [X] Operating system: RHEL
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
I would log the error then continue. I'd also set `enable.auto.offset.store=False` and instead opt to manually store each offset with [store_offsets](https://docs.confluent.io/4.1.2/clients/confluent-kafka-python/index.html#confluent_kafka.Consumer.store_offsets) only after successfully committing the message to the rdbms. This way I can ensure the consumer never considers a message to be committed until its been persisted downstream. Otherwise with the default `enable.auto.offset.store=True` will consider the message to be persisted once it passes from the internal message queue to your application.
