### ISSUE TITLE
Why there is no transitive compatibility level such as BACKWARD_TRANSITIVE and so on?

### ISSUE THREAD

**Issue by mpyatishev** [confluentinc/confluent-kafka-python#772]
Description
===========

Why there is no transitive compatibility level such as BACKWARD_TRANSITIVE and so on?

How to reproduce
================

Try to set compatibility level to BACKWARD_TRANSITIVE

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python: 1.3.0
 - [ ] librdkafka: 1.2.1

**Comment by rnpridgeon** [comment]
The valid compatibility levels list just needs to be updated. There is no technical reason. Will update with the most recent list of valid values.

**Comment by mpyatishev** [comment]
Ok, I see. Thanks for your response!

**Comment by frankgrimes97** [comment]
@rnpridgeon It still doesn't appear to support all compatibility levels... was this issue closed prematurely? Or did the change somehow get reverted?
https://github.com/confluentinc/confluent-kafka-python/blob/d961259dfe25a65c23e2921be381da24eb24d253/src/confluent_kafka/avro/cached_schema_registry_client.py#L37
