### ISSUE TITLE
Kafka-python package is deleting values from app config

### ISSUE THREAD

**Issue by agates4** [confluentinc/confluent-kafka-python#775]
Description
===========
https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/__init__.py#L32

python does direct mutations to original memory location of dictionaries. with the line I linked, this will remove the value of this config from our passed through dict. if I'm using app.config, this means that the confluent kafka package is actually modifying my app's config value. 

How to reproduce
================
pass it a dict with "schema.registry.url"

produce a message

print the original dict after the message was produced

notice that the dict no longer contains a value for "schema.registry.url"

Checklist
=========
Please provide the following information:

latest version 
 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [X] Apache Kafka broker version:
 - [X] Client configuration: `{...}`
 - [X] Operating system:
 - [X] Provide client logs (with `'debug': '..'` as necessary)
 - [X] Provide broker log excerpts
 - [X] Critical issue

**Comment by agates4** [comment]
the solution should just be to use a shallow copy of the dict

dict.copy() should suffice

**Comment by rnpridgeon** [comment]
I'm not sure that's accurate. We are using a dictionary comprehension to iterate over the original configurations values, mutating a copy of the selected items, then placing it into a new dictionary. 

The following tests can be used to back this claim up as well. 

    def test_immutable_conf(self):
        orig = {'bootstrap.servers': 'localhost:9092',
                'schema.registry.url': 'http://127.0.0.1:9001'}
        producer = AvroProducer(orig)
        assert orig == orig

    def test_dict_comprehension_copy(self):
        orig = {'bootstrap.servers': 'localhost:9092',
                'schema.registry.url': 'http://127.0.0.1:9001'}
        new = {key.replace("schema.registry.", ""): value
                   for key, value in orig.items() if key.startswith("schema.registry")}
        assert orig != new

I'll keep them in the refactor for future reference.
