### ISSUE TITLE
Kafka producer becomes unresponsive when trying to connect to a non-existing broker

### ISSUE THREAD

**Issue by JoaoVasques** [confluentinc/confluent-kafka-python#780]
Description
===========

Kafka producer blocks forever when connecting to a broker list that does not exist.

How to reproduce
================

Run the following set of commands where `mybroker1,mybroker2` are invalid broker names. if you do you will notice that the console blocks forever. The expected behaviour, in my opinion, is that the client would crash when trying to setup a producer with invalid brokers.

```python
from confluent_kafka import Producer

p = Producer({'bootstrap.servers': 'mybroker1,mybroker2'})

def delivery_report(err, msg):
    """ Called once for each message produced to indicate delivery result.
        Triggered by poll() or flush(). """
    if err is not None:
        print('Message delivery failed: {}'.format(err))
    else:
        print('Message delivered to {} [{}]'.format(msg.topic(), msg.partition()))

some_data_source = ["ola", "adeus"]

for data in some_data_source:
    # Trigger any available delivery report callbacks from previous produce() calls
    p.poll(0)
    # Asynchronously produce a message, the delivery report callback
    # will be triggered from poll() above, or flush() below, when the message has
    # been successfully delivered or failed permanently.
    p.produce('mytopic', data.encode('utf-8'), callback=delivery_report)
# Wait for any outstanding messages to be delivered and delivery report
# callbacks to be triggered.
p.flush()
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python version 1.3.0
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: `{'bootstrap.servers': 'mybroker1,mybroker2'}`
 - [ ] Operating system: MacOS Majove 10.14
 - [ ] Provide client logs : N/A
 - [ ] Provide broker log excerpts: N/A
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
LIbrdkafka derived clients, including this one, intentionally treat disconnect issues as if they were temporary. Realistically there is no way to determine if a failure is intermittent or permanent. As such we optimistically attempt to reconnect. I'll add a mention of this in the documentation.

**Comment by JoaoVasques** [comment]
Thanks @rnpridgeon 👍

**Comment by jackcasey-visier** [comment]
Wrestling with this a bit and hoping to get some insight 😄 I'm running into the same behaviour where if the brokers are offline or doesn't exist, the `Producer` initialization will block indefinitely.

Is there a config to get around this? Like a timeout or limited number of retries? I've tried the following config elements with no success. The `retries` value was set as 2 during testing: 

- `socket.timeout.ms`
- `transaction.timeout.ms`
- `request.timeout.ms`

For context, we're running the producer in ephemeral containers that are load their config at startup. The containers are then expected to die in the case they aren't able to bootstrap properly (setting up the Producer is part of the bootstrapping). This allows any misconfigurations to be corrected and have the containers basically "self heal" on next start. In the case the Kafka brokers network configuration is incorrect, the `Producer` would block and the container would stay alive. We could add a global timeout or something, but that is a bit delicate and a route I'm hoping not to go down 😅 

Any insight on how to force the `Producer` initialization to fail would be greatly appreciated! 

Thanks!

**Comment by edenhill** [comment]
@jackcasey-visier It really shouldn't block. Can you provide your config and the code around the Producer constructor?

**Comment by jackcasey-visier** [comment]
@edenhill Thank you for following up! 

This is embarrassing, I was so focused on the configs I missed a simple thing 😅 

The constructor wasn't blocking, it was a call to `list_topics()` immediately after that was. 

Configuring a timeout with `list_topics(timeout=5)` gave the expected behaviour.

Thanks!
