### ISSUE TITLE
on_assign with multiple consumers not dispatched to the correct consumer when group.id are the same

### ISSUE THREAD

**Issue by arthurandres** [confluentinc/confluent-kafka-python#782]
Description
===========

I have two `Consumer`s, they both have the same `group.id`, but they subscribe to different topics (topic1 and topic2) and have a different on_assign callback regIstered

I can subscribe the first consumer to topic1 and poll until on_assign is called.
But when I subscribe to the second consumer to topic2 and poll until on_assign is called, it hangs.

Note that:
* if I keep polling the first consumer after subscribing the second consumer, both on_assign call back are called, with their respective topic (In other world, on_assign callback for topic1 is called a second time, on_assign callback for topic2 is called)
* it works fine when I have different group.id.

How to reproduce
================
* Broken version:
```
def subscribe_consumer(consumer, topic):
    print('SUBSCRIBING', topic)
    assigned = threading.Event()

    def on_assign(consumer, partitions):
        print(f"ASSIGNED {topic} {partitions}")
        assigned.set()

    consumer.subscribe([topic], on_assign=on_assign)
    while not assigned.is_set():
        msg = consumer.poll(1)
        if msg:
            print(msg.error(), msg.value())
    print('SUBSCRIBED', topic)

print(confluent_kafka.__version__)
group_id = str(uuid.uuid4())
print(group_id)
    
consumer1 = Consumer(
     {
         'bootstrap.servers': bootstrap_servers,
         'group.id': group_id, 
         'enable.auto.commit': False},
    )

subscribe_consumer(consumer1, topic1)


consumer2 = Consumer(
     {
         'bootstrap.servers': bootstrap_servers,
         'group.id': group_id,
         'enable.auto.commit': False},
    )

subscribe_consumer(consumer2, topic2)
```
Prints:
```
1.3.0
6761b369-df8b-4955-a318-ed87063fa685
SUBSCRIBING topic1
ASSIGNED topic1 <topic1 partitions>
SUBSCRIBED topic1
SUBSCRIBING topic2
```
And hangs from there...

* Working version with different group.id:
```
def subscribe_consumer(consumer, topic):
    print('SUBSCRIBING', topic)
    assigned = threading.Event()

    def on_assign(consumer, partitions):
        print(f"ASSIGNED {topic} {partitions}")
        assigned.set()

    consumer.subscribe([topic], on_assign=on_assign)
    while not assigned.is_set():
        msg = consumer.poll(1)
        if msg:
            print(msg.error(), msg.value())
    print('SUBSCRIBED', topic)

print(confluent_kafka.__version__)
group_id = str(uuid.uuid4())
print(group_id)
    
consumer1 = Consumer(
     {
         'bootstrap.servers': bootstrap_servers,
         'group.id': group_id, 
         'enable.auto.commit': False},
    )

subscribe_consumer(consumer1, topic1)


consumer2 = Consumer(
     {
         'bootstrap.servers': bootstrap_servers,
         'group.id': group_id + '_topic2',
         'enable.auto.commit': False},
    )

subscribe_consumer(consumer2, topic2)
```
Prints:
```
1.3.0
0d8c8d41-211f-424f-8962-c916c99a7e78
SUBSCRIBING topic1
ASSIGNED topic1 <topic1 partitions>
SUBSCRIBED topic1
SUBSCRIBING topic2
ASSIGNED topic2 <topic2 partitions>
SUBSCRIBED topic2
```
* Working version, polling consumer1 while subscribing consumer2
```
def subscribe_consumer(consumer, topic):
    print('SUBSCRIBING', topic)
    assigned = threading.Event()

    def on_assign(consumer, partitions):
        print(f"ASSIGNED {topic} {partitions}")
        assigned.set()

    consumer.subscribe([topic], on_assign=on_assign)
    while not assigned.is_set():
        msg = consumer.poll(1)
        if msg:
            print(msg.error(), msg.value())
    print('SUBSCRIBED', topic)

print(confluent_kafka.__version__)
group_id = str(uuid.uuid4())
print(group_id)
    
consumer1 = Consumer(
     {
         'bootstrap.servers': bootstrap_servers,
         'group.id': group_id, 
         'enable.auto.commit': False},
    )

subscribe_consumer(consumer1, topic1)

def poll(consumer):
    while True:
        msg = consumer.poll(1)
        if msg:
            print(msg.error(), msg.value(), msg.topic())

thread = threading.Thread(target=lambda: poll(consumer1))
thread.start()

consumer2 = Consumer(
     {
         'bootstrap.servers': bootstrap_servers,
         'group.id': group_id,
         'enable.auto.commit': False},
    )

subscribe_consumer(consumer2, topic2)
```
Prints (note the spurious call to ASSIGNED on topic1 the second time:
```
1.3.0
0d8c8d41-211f-424f-8962-c916c99a7e78
SUBSCRIBING topic1
ASSIGNED topic1 <topic1 partitions>
SUBSCRIBED topic1
SUBSCRIBING topic2
ASSIGNED topic1 <topic1 partitions>
ASSIGNED topic2 <topic2 partitions>
SUBSCRIBED topic2
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python ('1.3.0', 16973824) and librdkafka version ('1.3.0', 16974079)
 - [x] Apache Kafka broker version: 2.2
 - [x] Client configuration: 
```
{
         'bootstrap.servers': bootstrap_servers,
         'group.id': group_id,
         'enable.auto.commit': False
}
```
 - [x] Operating system: centos 7
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
My understanding is as follows:

consumer 1 -> subscribe -> poll until assignment 
consumer 2 -> subscribe to a different -> poll until assignment (hangs) 

This is actually the expected behavior for the `subscribe` API. Subscribe is a group-wide operation prompting a rebalance with each invocation. Consumer 2 hangs because it waiting for consumer 1 to leave the group, revoke its partitions and then rejoin. This doesn't happen however because consumer 1 is no longer calling poll.

You can see the consumer group protocol wiki for more details:

 https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Client-side+Assignment+Proposal 

I also find the following diagram useful. 

https://github.com/edenhill/librdkafka/blob/df6bcbf11e1bd9ed53423514de30d59dbe5fac07/src/librdkafka_cgrp_synch.png

If you'd like consumer 1 and consumer 2 to operate independently of one another you can either form 2 groups as you have noted or use the `assign` API. 

https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.assign

**Comment by arthurandres** [comment]
@rnpridgeon, thanks for your answer, it all makes sense.

I've assumed that consumer instances worked in isolation provided they were subscribed to different topics. It looks like I was wrong.
