### ISSUE TITLE
poll timeout is ignored

### ISSUE THREAD

**Issue by OblackatO** [confluentinc/confluent-kafka-python#783]
Description
===========
When creating a simple Producer, the timeout of poll is ignored. I use poll() right after creating a Producer to check if the kafka broker(s) is up and running. 
Everything seems correct, because I got two kafka errors that are supposed to happen: _TRANSPORT && _ALL_BROKERS_DOWN. 
The only problem is that the timeout that I specify in poll() is not respected, no matter what value I specify.

How to reproduce
================
```
from confluent_kafka import Producer

def error(err):
  print("An error occurred: {}".format(err))

def delivery(err, msg):
  if err is not None:
    print("Error occurred while delivering msg")
  else:
    print("{} has been delivered.".format(msg))
conf={
  'bootstrap.servers': 'non_working_broker',
  'error_cb': error,
  'on_delivery': delivery
}

producer = Producer(conf)
producer.poll(timeout=5.0)
```
Checklist
=========
Please provide the following information:
 - [ X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
   - ('1.3.0', 16973824) and  ('1.3.0', 16974079)
 - [ ] Apache Kafka broker version:
 - [ X] Client configuration: `{...}`: On the code
 - [ X] Operating system: Ubuntu 19.04 (Disco Dingo)
 - [ X] Provide client logs (with `'debug': '..'` as necessary) :
%7|1582294700.989|BROKER|rdkafka#producer-1| [thrd:app]: non_working_broker:9092/bootstrap: Added new broker with NodeId -1
%7|1582294700.989|CONNECT|rdkafka#producer-1| [thrd:app]: non_working_broker:9092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1582294700.989|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1582294700.989|BRKMAIN|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: Enter main broker thread
%7|1582294700.989|CONNECT|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: Received CONNECT op
%7|1582294700.989|STATE|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1582294700.989|CONNECT|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1582294700.989|STATE|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1582294700.989|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.3.0 (0x10300ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x2)
An error occurred: KafkaError{code=_RESOLVE,val=-193,str="non_working_broker:9092/bootstrap: Failed to resolve 'non_working_broker:9092': Temporary failure in name resolution (after 23ms in state CONNECT)"}
An error occurred: KafkaError{code=_ALL_BROKERS_DOWN,val=-187,str="1/1 brokers are down"}
%7|1582294701.012|BROKERFAIL|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: failed: err: Local: Host resolution failure: (errno: Bad address)
%7|1582294701.012|STATE|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1582294701.013|DESTROY|rdkafka#producer-1| [thrd:app]: Terminating instance (destroy flags none (0x0))
%7|1582294701.013|DESTROY|rdkafka#producer-1| [thrd:main]: Destroy internal
%7|1582294701.013|DESTROY|rdkafka#producer-1| [thrd:main]: Removing all topics
%7|1582294701.013|DESTROY|rdkafka#producer-1| [thrd:main]: Sending TERMINATE to non_working_broker:9092/bootstrap
%7|1582294701.013|TERM|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1582294701.013|BROKERFAIL|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Bad address)
%7|1582294701.013|FAIL|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: Client is terminating (after 1ms in state DOWN)
%7|1582294701.013|TERMINATE|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: Handle is terminating in state DOWN: 1 refcnts (0x20750e0), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1582294701.013|BROKERFAIL|rdkafka#producer-1| [thrd:non_working_broker:9092/bootstrap]: non_working_broker:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Bad address)
%7|1582294701.013|TERM|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Received TERMINATE op in state INIT: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1582294701.013|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1582294701.013|FAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Client is terminating (after 25ms in state INIT)
%7|1582294701.013|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> DOWN
%7|1582294701.013|TERMINATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Handle is terminating in state DOWN: 1 refcnts (0x2074350), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1582294701.013|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)

**Comment by edenhill** [comment]
poll() will return immediately if callbacks are triggered.
I.e., the timeout is maximum amount of time to wait.

**Comment by OblackatO** [comment]
Thank you for your answer. 
Given that I handle the _ALL_BROKERS_DOWN error in a callback function, how can I tell the Producer to retry in X seconds and a max number of tries?
I am trying to looking for something like that here: https://kafka.apache.org/documentation/
Do I have such an option in this py wrapper?

**Comment by edenhill** [comment]
The error callbacks are typically informational, the underlying client will retry on pretty much all errors and there is nothing the application needs to do.

In fact the client is designed to let you as the application developer not have to care about the operational state of the Kafka cluster, but instead focus on the data.
For the producer that means definining the maximum amount of time allowed to deliver a message through the `message.timeout.ms` configuration property.

**Comment by OblackatO** [comment]
I understand.
https://kafka.apache.org/documentation/ , does not seem to have the option: 
_message.timeout.ms_
Would it be equivalent to use:
_delivery.timeout.ms_ ?

**Comment by edenhill** [comment]
kafka.apache.org only documents the Java clients, while confluent-kafka-python is based on librdkafka which is documented in its [manual](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md) and configuration properties in [CONFIGURATION.md](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)

**Comment by OblackatO** [comment]
That makes total sense. -.- 
I will close this issue. Thank you for your time.
