### ISSUE TITLE
request(s) timed out: disconnect in combination with all brokers down

### ISSUE THREAD

**Issue by rubinatorz** [confluentinc/confluent-kafka-python#789]
Description
===========
Several times a day (varying from a few times up to around 30) we get the following combination of log lines in our logging:

```
Wed Feb 26 13:56:52 2020, 59876: INF KafkaProducerConnection reported an error: other. Err code: -185. Reason: ssl://node3.hostname:9093/3: 1 request(s) timed out: disconnect (after 2699273ms in state UP).

Wed Feb 26 13:56:52 2020, 59876: ERR KafkaProducerConnection reported an error: all brokers down. Err code: -187. Reason: 3/3 brokers are down. (ConfluentKafkaProducerConnection)
```

The combination of 2 events happens almost at the same time, and those happens several times a day.

A bit of clarification of the log lines: those are printed by our error handling function:

```
def _error_handling(self, err):
	loglvl = self._logger.Informational
	errtype = "other"
	if err.code() == KafkaError._ALL_BROKERS_DOWN:
	    self._in_error_state = True
	    loglvl = self._logger.Error
	    errtype = "all brokers down"
	elif err.code() == KafkaError._TRANSPORT:
	    loglvl = self._logger.Warning
	    errtype = "one broker down"
	self._logger.log("%s reported an error: %s. Err code: %d. Reason: %s." % (self._short_identifier, errtype, err.code(), err.str()), loglvl)
```

The questions we have:
- We wonder why this is happening.
- We don't understand that one node is timing out and "all brokers down" is reported just after the timeout.
- What can we do to fix this?
- Is there something we can do to prevent the timeout? Increasing the timeout time for example. Or trigger a function on the producer to keep the connection alive, or somehting.

How to reproduce
================
We have an application running with around 10 consumers and 2 producers. The error only occurs with the producers. And it occurs with all 3 nodes. The application runs as a python application on a Debian environment. If connects to a Kafka cluster with 3 nodes. We just started using confluent-kafka because pykafka is not maintained anymore. We are now running in an acceptance environment where not very much messages are produced.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 

confluent_kafka.version()
('1.3.0', 16973824)

confluent_kafka.libversion()
('1.3.0', 16974079)

 - [x] Apache Kafka broker version: 2.2.1
 - [x] Client configuration: 

`{'bootstrap.servers': 'node1:9093,node2:9093,node3:9093,
'linger.ms': 5,
'error_cb': self._error_handling,
'security.protocol': 'SSL',
'ssl.ca.location': 'cafile',
'ssl.certificate.location': 'location',
'ssl.key.location': 'keyfile',
'ssl.key.password': 'keyfile_password}`

 - [x] Operating system: Debian Linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If your producer is mostly idle then what you are seeing is most likely the broker's idle connection reaper kicking in. This is nothing to worry about, the client will automatically reconnect.
See https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected

**Comment by rubinatorz** [comment]
hi @edenhill thanks for your fast reply. It seems indeed that the connection restores correctly. But how can I distinguish between an ALL_BROKERS_DOWN error in this idle/timeout case and a real ALL_BROKERS_DOWN error? In the idle/timeout case, I don't want to log the ALL_BROKERS_DOWN error, but in case of a real scenario where all brokers are down I do want to log that error.

**Comment by edenhill** [comment]
There is no way for a client to know the reason of a broker-side disconnect, thus it can't differentiate between a idle disconnect, or a disconnect for some other reason.

We generally recommend you not to bother trying to track the cluster's state, since that is nearly impossible in distributed systems.
Instead focus on data delivery, for the producer that means setting `message.timeout.ms` for the maximum time allowed to produce some data, any recoverable errors during that time will trigger automatic retries by the producer.
