### ISSUE TITLE
module 'avro.schema' has no attribute 'Parse'

### ISSUE THREAD

**Issue by juliechen727** [confluentinc/confluent-kafka-python#790]
Description
===========
When I trying to run the AvroProducer example, I got an AttributeError said 
```
Exception has occurred: AttributeError
module 'avro.schema' has no attribute 'Parse'
  File "C:\Projects\TEST\web-scrape-python\demo-github.py", line 33, in <module>
    value_schema = avro.loads(value_schema_str)
```
I'm using python 3.7.5

How to reproduce
================
```
from confluent_kafka import avro
from confluent_kafka.avro import AvroProducer


value_schema_str = """
{
   "namespace": "my.test",
   "name": "value",
   "type": "record",
   "fields" : [
     {
       "name" : "name",
       "type" : "string"
     }
   ]
}
"""

key_schema_str = """
{
   "namespace": "my.test",
   "name": "key",
   "type": "record",
   "fields" : [
     {
       "name" : "name",
       "type" : "string"
     }
   ]
}
"""

value_schema = avro.loads(value_schema_str)
key_schema = avro.loads(key_schema_str)
value = {"name": "Value"}
key = {"name": "Key"}


def delivery_report(err, msg):
    """ Called once for each message produced to indicate delivery result.
        Triggered by poll() or flush(). """
    if err is not None:
        print('Message delivery failed: {}'.format(err))
    else:
        print('Message delivered to {} [{}]'.format(
            msg.topic(), msg.partition()))


avroProducer = AvroProducer({
    'bootstrap.servers': 'localhost:29092',
    'on_delivery': delivery_report,
    'schema.registry.url': 'http://localhost:8081'
}, default_key_schema=key_schema, default_value_schema=value_schema)

avroProducer.produce(topic='my_topic', value=value, key=key)
avroProducer.flush()

```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 2.4.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: windows 10
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by adelcast** [comment]
I ran into this error, then realized that I had the avro library installed, instead of the avro-python3 one (I am using python3). Maybe you are having the same issue?

**Comment by rnpridgeon** [comment]
Created wheel for avro-python3: filename=avro_python3-1.9.2.1-py3-none-any.whl size=43513 sha256=979a9fa7b0f0ac106ccd69e46f5160b2b79f3726a07c1799f24452e5cf36b3a3

**Comment by juliechen727** [comment]
I solved the issue by downgrading avro-python3 to 1.8.2.

**Comment by brifordwylie** [comment]
Thanks @rnpridgeon exactly what I needed 👍
