### ISSUE TITLE
Consumer takes ~5 seconds to poll the first message

### ISSUE THREAD

**Issue by JosepSampe** [confluentinc/confluent-kafka-python#793]
Each time I create a Consumer, the first poll takes ~5 seconds. Subsequent polls run much faster (as expected). However, I have an app that stops for a while and then starts again, having to create the Consumer each time, and then having these 5 seconds of overhead each time.

- I have a kafka installation (kafka_2.12-2.2.0) on a single VM.
- I have a topic with 5K messages before start the consumer.
- The VM and the consumer are located in the same local network (no interference by other 
services)
- I use confluent-kafka 1.3.0
```
import json
import time
from confluent_kafka import Consumer

TOPIC='mytopic'

def consume_events():

    config = {'bootstrap.servers': '192.168.2.51:9092',
              'group.id': 'test-group',
              'default.topic.config': {'auto.offset.reset': 'earliest'},
              'enable.auto.commit': False
              }
    consumer = Consumer(config)
    consumer.subscribe([TOPIC])
    start = None
    total = 0
    while True:
        try:
            message = consumer.poll(timeout=10)
            start = time.time() if not start else start
            payload = message.value().decode('utf-8')
            event = json.loads(payload)
            total = total+1
            #print("[{}] Received event {}".format(TOPIC, total))
            end = time.time()
        except Exception as e:
            break

    print('Total time: {}'.format(end-start))


if __name__ == '__main__':
    consume_events()
```
Is this the expected behavior? why is this overhead present each time I start to poll messages?

**Comment by rnpridgeon** [comment]
5 seconds seems high but it is expected that the initial poll will take some time. This is because each time you call subscribe you must go through the consumer group protocol dance prior to receiving an assignment and starting the fetchers. 

https://github.com/edenhill/librdkafka/blob/master/src/librdkafka_cgrp_synch.png

If you are using a single consumer and your partition count is fixed you could use the assign API instead which would speed things up. 

https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.assign

**Comment by JosepSampe** [comment]
@rnpridgeon Thanks a lot for the response. 5 seconds is the highest poll time I get. Doing some experiments I saw that depending of the resources of the client machine, and depending of the resources of the server machine, it takes more or less time to start polling messages. For example, if I start consuming from another client machine with better resources and it takes ~3 seconds,  and from another with better network it takes ~1.5 seconds.

**Comment by forgoty** [comment]
I noticed, that you can provide an "on_assign" keyword argument as a callback to "subscribe" method. 
[Docs](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Consumer.subscribe)
