### ISSUE TITLE
Consume continues reading messages when enable.auto.commit=false and manual commits are not done

### ISSUE THREAD

**Issue by hackmad** [confluentinc/confluent-kafka-python#796]
Description
===========

We have a requirement to reprocess messages in case we detect failures during message processing that are application specific errors such as not being able to connect to an interval rest endpoint. 

What we found is that setting `enable.auto.commit`: False, and not performing commit manually the consumer keeps receiving newer messages. What happens now is when our services recover from the failure, the offset for latest message that passes gets committed and we have effectively lost the prior messages that weren't committed.

Unless I'm missing something, isn't the consumer supposed to stall on the current offset?

How to reproduce
================

The consumer code below doesn't commit any offset.

**consumer.py:**
```
from confluent_kafka import Consumer, KafkaError
c = Consumer({
    'bootstrap.servers': 'localhost:29092',
    'group.id': 'mygroup',
    'auto.offset.reset': 'earliest',
    'enable.auto.commit': 'false',
})
c.subscribe(['mytopic'])
while True:
    messages = c.consume(num_messages=1, timeout=1.0)
    if messages is None or len(messages) == 0:
        continue
    msg = messages[0]
    if msg.error():
        print("Consumer error: {}".format(msg.error()))
        continue
    print('Received message: {}'.format(msg.value().decode('utf-8')))
c.close()
```

**Pipfile:**
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[dev-packages]
confluent-kafka = {extras = ["avro"],version = "*"}
pylint = "*"
[packages]
[requires]
python_version = "3.7"
```

**Run consumer:**
```
pipenv install
pipenv run python consumer.py
```

**Run producer:**
```
kafka-console-producer --broker-list localhost:29092 --topic mytopic
```

As you send new messages in the consumer will receive them. The only way it'll reprocess old messages that aren't committed is if you stop the consumer and restart it.

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```
>>> confluent_kafka.version()
('1.3.0', 16973824)
>>> confluent_kafka.libversion()
('1.3.0', 16974079)
```
 - [X] Apache Kafka broker version:
```
2.1.0-cp1 (Commit:bda8715f42a1a3db)
```
 - [X] Client configuration: `{...}`
See code above
 - [X] Operating system:
MacOS Catalina (running Kafka using confluent docker images.
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by hackmad** [comment]
So this solves it for me. 

```
    c.seek(TopicPartition(
        partition=msg.partition(),
        topic=msg.topic(),
        offset=msg.offset(),
    ))
```

I'm not sure if this is the best way to do it but it does work.

**Comment by rnpridgeon** [comment]
If you want to manage offsets manually I suggest leaving `auto.offset.commit=True` and instead using `enable.auto.offset.store=False`. When you are ready to consider an offset committed you will call `store_offsets`.

https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.store_offsets

This will give you all the benefits of auto offset (synchronous offset commit on close and rebalance) while maintaining control over when an offset is considered committed.

**Comment by hackmad** [comment]
That would give control for committing offsets. However, it doesn't stop the `consume()` or `poll()` methods from continuing to send messages to the application code.
