### ISSUE TITLE
Install confluent-kafka on Windows

### ISSUE THREAD

**Issue by godestalbin** [confluentinc/confluent-kafka-python#800]
Hello,
I am trying to install Kafka for Python on Windows 10 with Visual Studio Code but I am stuck.

When I run `confluent-kafka` I got an error message `'librdkafka/rdkafka.h': No such file`
I understand, I shoud first install the NuGet package `librdkafka.redist` but I cannot find anyway to perform this task. I need some step by step guidelines for newbie.

What I already tried:
- Initial issue was `Required C++ build tools`: Solved by installing Visual Studio 2019 community and GB of packages. I would like to be able to install the strict required minimum.
- Default instruction `Install-Package librdkafka.redist -Version 1.3.0` does not work. Option `-Version` is not recognized. It is better with `-MinimumVersion 1.3.0` option but package is not found
- Tried to play with `Set-PackageSource `
```
Name                             ProviderName     IsTrusted  Location
----                             ------------     ---------  --------
nuget.org                        NuGet            True       https://api.nuget.org/v3/index.json
NewNuGet                         NuGet            True       https://www.nuget.org/api/v2
PSGallery                        PowerShellGet    False      https://www.powershellgallery.com/api/v2
```
- Installed .NET CLI to try the other option to install the package `dotnet add package librdkafka.redist --version 1.3.0`. It does not work neither, it requires to specify a project file that I don't have. Also tried `NuGet Gallery` and `NuGet4Code` extensions: They allow me to retrieve the `librdkafka.redist` but I cannot manage to install it.
- I read the various issues on Github regarding installing `librdkafka.redist`, it looks like, it was not supported on Windows some time ago but the issue has now been solved.

**Comment by edenhill** [comment]
v1.6.0 will have up to date windows wheels.
