### ISSUE TITLE
avro.io is missing after replacement avro with avro-python3

### ISSUE THREAD

**Issue by mykhas** [confluentinc/confluent-kafka-python#801]
Description
===========
I'm working through the Kafka course on Udacity, and as a part of it I'm trying to load avro scheme loading locally. Unfortunately, I'm getting an error ```AttributeError: module 'avro.schema' has no attribute 'Parse'``` while executing it having pip3's `avro` installed locally. This issues was reported several times already (#600, #790), so I've just replaced it with `avro-python3`. Now, it fails even sooner giving the next error: 
```
Traceback (most recent call last):
  File "exercise3.4.error.py", line 1, in <module>
    from confluent_kafka import avro, Consumer, Producer
  File "/usr/local/lib/python3.7/site-packages/confluent_kafka/avro/__init__.py", line 13, in <module>
    from confluent_kafka.avro.serializer.message_serializer import MessageSerializer
  File "/usr/local/lib/python3.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 29, in <module>
    import avro.io
ModuleNotFoundError: No module named 'avro.io'
```

How to reproduce
================
Code to reproduce:
```from confluent_kafka import avro, Consumer, Producer
from confluent_kafka.avro import AvroConsumer, AvroProducer, CachedSchemaRegistryClient

schema = avro.loads("""{
    "type": "record",
    "name": "click_event",
    "namespace": "com.udacity.lesson3.exercise4",
    "fields": [
        {"name": "email", "type": "string"},
        {"name": "timestamp", "type": "string"},
        {"name": "uri", "type": "string"},
        {"name": "number", "type": "int"}
    ]
}""")
```

```
➜  UDSND pip3 list | grep avro
avro-python3              1.9.2.1
fastavro                  0.22.13
➜  UDSND pip3 list | grep kafka
confluent-kafka           1.3.0
➜  UDSND python3 --version
Python 3.7.6
➜  UDSND pip3 --version
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```
Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.3.0', 16973824), ('1.3.0', 16974079)
 - [X] Apache Kafka broker version: 2.4.0
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: MacOS
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
did you install the avro `extra` (as distutils calls it) when you installed the client. `pip install confluent_kafka[avro]`

**Comment by mykhas** [comment]
Ok, I've just found it. Looks like I've installed my `confluent_kafka` with `--user`, and `avro-python3` without that attribute, which made it installed in different location. Still, somehow it was able to find `avro`, but not `avro.io`. `pip3 uninstall avro-python3 && pip install avro-python3 --user` help in my case.

@rnpridgeon thanks for the direction anyway :)

**Comment by rnpridgeon** [comment]
Did you install with `pip install confluent_kafka[avro]`. When I do  this with a fresh virtualenv I see the following 

  Created wheel for avro-python3: filename=avro_python3-1.9.2.1-py3-none-any.whl size=43513 sha256=979a9fa7b0f0ac106ccd69e46f5160b2b79f3726a07c1799f24452e5cf36b3a3
