### ISSUE TITLE
Exception raising

### ISSUE THREAD

**Issue by royreznik** [confluentinc/confluent-kafka-python#806]
After working with your client for a long time, i found out that a have written those line over and over:
```python
if msg.error():
                raise Exception()
```
In the consumer, most of the exception you will get will make `msg.error` be not `None`.
I think it will be much better api, to throw an exception after getting one, and not make the exception apear in the `msg.value()`.

is there a plan to change this into exception base? or would you like to get a PR about this?

**Comment by rnpridgeon** [comment]
Great news we are doing exactly this in #787
