### ISSUE TITLE
Docs missing for class `confluent_kafka.admin.NewTopic`

### ISSUE THREAD

**Issue by SoloSynth1** [confluentinc/confluent-kafka-python#809]
Description
===========
Documentation for class `confluent_kafka.admin.NewTopic` is missing the current version of the API documentation. 

How to reproduce
================
Visit [the Documentation](https://docs.confluent.io/current/clients/confluent-kafka-python/) and search for `confluent_kafka.admin.NewTopic`. This class is referenced in [AdminClient.create_topics()](https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.admin.AdminClient.create_topics) method but the decription of this class cannot be found.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.3.0 (https://docs.confluent.io/current/clients/confluent-kafka-python/)
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: N/A
 - [ ] Operating system: N/A
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by infinityplus1** [comment]
doc still missing 1 year after

**Comment by pranavrth** [comment]
Thanks for reporting this.

Doc is present now - https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.admin.NewTopic

Closing the issue.
