### ISSUE TITLE
delete_topics does not work

### ISSUE THREAD

**Issue by jfinzel** [confluentinc/confluent-kafka-python#813]
Description
===========
The delete_topics method does not work.  After it has been run, you can still view the topic with the ccloud cli.  It is only by using the ccloud cli that you can actually delete the topic.

How to reproduce
================
Create a kafka topics and run KafkaAdminClient delete_topics using that topic name.  The method will succeed.  Check if the topic still exists using the ccloud cli, and it is still there.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 
```
>>> confluent_kafka.version()
('1.3.0', 16973824)
>>> confluent_kafka.libversion()
('1.3.0', 16974079)
```
 - [ ] Apache Kafka broker version: confluent ccloud kafka
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Mac OSX
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

Please let me know if you need any of the other above information if necessary.

**Comment by edenhill** [comment]
Topic deletions are asynchronous in Kafka, it will take some time (perhaps a long time) for the delete to propagate through the cluster if any of topic's partition replicas are unavailable.

It is generally recommended to not delete and re-create topics in Kafka.

**Comment by jfinzel** [comment]
@edenhill the use case is for testing a data pipeline.  I need to be able to reset the scenario.  Actually I can think of many use cases for deleting a topic in a data pipeline, where I actually don't care about the offsets, etc.  So, if it isn't recommended, why is the method provided?

**Comment by candlerb** [comment]
`admin.delete_topics(TOPICS)` works for me, but I put in a `time.sleep(3)` before recreating the deleted topics.

For more robust tests it might be better to use topics with a random ID suffix, and then delete them at the end of the test.

**Comment by edenhill** [comment]
@jfinzel 
> So, if it isn't recommended, why is the method provided?
It is the quick topic delete and re-create cycle that is not recommended.

**Comment by jfinzel** [comment]
@edenhill and @candlerb I have never quickly re-created the topic, and a 3 second sleep is nowhere near sufficient to actually show the topic as deleted.  I have waited a period of minutes with the topic metadata still showing up.

**Comment by candlerb** [comment]
It works for me, although I'm only testing small topics with a few hundred messages, on a one-node cluster (running `confluentinc/cp-kafka:5.2.1`)

**Comment by edenhill** [comment]
@jfinzel That doesn't sound right. Are all the brokers in the cluster up and operational?
Can you show me your delete code?

**Comment by flavienbwk** [comment]
> @jfinzel
> 
> > So, if it isn't recommended, why is the method provided?
> 
> It is the quick topic delete and re-create cycle that is not recommended.

Do you mean deletion must be fully asynchronous ?

Does kafka-python provide a way to "wait" for this deletion ?

**Comment by edenhill** [comment]
There's no rock solid way for a client to know when a topic has been truly deleted throughout the cluster, it is thus not recommended to delete and re-create topics with the same name.

[KIP-516](https://cwiki.apache.org/confluence/display/KAFKA/KIP-516%3A+Topic+Identifiers) sets out to address this, but it is not yet implemented.

**Comment by flavienbwk** [comment]
Thank you @edenhill. It seems I've found a way to achieve this without getting an error :+1: 

```python3
admin_client = KafkaAdminClient(bootstrap_servers=kafka_servers)
if topic_name in broker_topics:
    deletion = admin_client.delete_topics([topic_name])
    try:
        future = client.cluster.request_update()
        client.poll(future=future)
    except KafkaError as e:
        print(e)
        pass
admin_client.create_topics(new_topics=topic_list, validate_only=False)
```

These two lines seem to make it work : 

```python3
future = client.cluster.request_update()
client.poll(future=future)
```

Is it normal or do you think it's a side effect for the code to "wait", but not exactly waiting for deletion ?

**Comment by edenhill** [comment]
That's [kafka-python](https://github.com/dpkp/kafka-python), not confluent-kafka-python

**Comment by lowjiajin** [comment]
@edenhill will support for KIP-516 be coming soon? Just noticed that it has been supported since Apache Kafka 2.8.0 in April this year.
