### ISSUE TITLE
Consumer lag always by one in every partition

### ISSUE THREAD

**Issue by doshu** [confluentinc/confluent-kafka-python#817]
Every partition lag always by 1 in every topic

One producer with many cosumer, even if the producer is not producing messages. The consumer are not able to get the latest message of every partition.
offset are stored and commited manually in a loop.

confluent-kafka-python ('1.3.0', 16973824)
librdkafka ('1.3.0', 16974079)
kafka broker version 3.1.4.0-315
debian 9
`settings = {
            'bootstrap.servers': ",".join(
                ['{}:{}'.format(broker['host'], broker['port']) for broker in self.config['kafka']['brokers']]
            ),
            'group.id': 'consumer1',
            'enable.auto.commit': False,
            'enable.auto.offset.store': False,
            'default.topic.config': {
                'auto.offset.reset': 'smallest'
            },
            'error_cb': self._on_error_cb,
            'queued.min.messages': 1000
        }`

**Comment by doshu** [comment]
my consumer commit offset using
consumer.commit(offsets = [TopicPartition(*offset)], asynchronous = False)

the offset is the offset of the last message.
probably i must increment the offset by one. isn't it?

**Comment by edenhill** [comment]
Yes, the committed offset should be the offset of the next message to process, not the last message processed. So commit offset + 1.
