### ISSUE TITLE
Issue installing librdkafka-devel

### ISSUE THREAD

**Issue by khoanguyen123** [confluentinc/confluent-kafka-python#818]
Description
===========
Can't install rpm librdkafka-devel on RHEL 6 due to unresolved dependencies. Error messages:

> yum install librdkafka-devel
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-disabled-repos, security, subscription-manager

>Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package librdkafka-devel.x86_64 0:1.3.0_confluent5.4.1-1.el7 will be installed
--> Processing Dependency: librdkafka1 = 1.3.0_confluent5.4.1 for package: librdkafka-devel-1.3.0_confluent5.4.1-1.el7.x86_64
--> Processing Dependency: librdkafka++.so.1()(64bit) for package: librdkafka-devel-1.3.0_confluent5.4.1-1.el7.x86_64
--> Processing Dependency: librdkafka.so.1()(64bit) for package: librdkafka-devel-1.3.0_confluent5.4.1-1.el7.x86_64
--> Running transaction check
---> Package librdkafka1.x86_64 0:1.3.0_confluent5.4.1-1.el7 will be installed
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) for package: librdkafka1-1.3.0_confluent5.4.1-1.el7.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.16)(64bit) for package: librdkafka1-1.3.0_confluent5.4.1-1.el7.x86_64
--> Processing Dependency: openssl-libs for package: librdkafka1-1.3.0_confluent5.4.1-1.el7.x86_64
--> Processing Dependency: libsasl2.so.3()(64bit) for package: librdkafka1-1.3.0_confluent5.4.1-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: librdkafka1-1.3.0_confluent5.4.1-1.el7.x86_64 (Confluent.dist)
           Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
Error: Package: librdkafka1-1.3.0_confluent5.4.1-1.el7.x86_64 (Confluent.dist)
           Requires: openssl-libs
Error: Package: librdkafka1-1.3.0_confluent5.4.1-1.el7.x86_64 (Confluent.dist)
           Requires: libc.so.6(GLIBC_2.16)(64bit)
Error: Package: librdkafka1-1.3.0_confluent5.4.1-1.el7.x86_64 (Confluent.dist)
           Requires: libsasl2.so.3()(64bit)

How to reproduce
================
`sudo rpm --import https://packages.confluent.io/rpm/5.4/archive.key`

`sudo yum install librdkafka-devel`

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: RHEL 6
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Confluent Platform no longer supplies Centos 6 builds of librdkafka, just centos 7.

You will need to install librdkafka from source or perhaps from another repo:
https://rpmfind.net/linux/rpm2html/search.php?query=librdkafka
