### ISSUE TITLE
Consumer fails for a Kafka Cluster with large number of topics.

### ISSUE THREAD

**Issue by gmohandass** [confluentinc/confluent-kafka-python#82]
%4|1479929770.581|PROTOERR|rdkafka#consumer-1| 10.64.64.59:31000/bootstrap: Protocol parse failure at rd_kafka_parse_Metadata:1582
%4|1479929770.581|PROTOERR|rdkafka#consumer-1| 10.64.64.59:31000/bootstrap: TopicMetadata_cnt 17202 > TOPICS_MAX 10000
%4|1479929771.021|PROTOERR|rdkafka#consumer-1| 10.64.64.59:31000/1: Protocol parse failure at rd_kafka_parse_Metadata:1582
%4|1479929771.021|PROTOERR|rdkafka#consumer-1| 10.64.64.59:31000/1: TopicMetadata_cnt 17202 > TOPICS_MAX 10000

**Comment by edenhill** [comment]
The good news is that's an arbitrary limit in librdkafka, it can easily be increased by a small edit and recompile.
The bad news is that it requires you to edit librdkafka and rebuild it.
If you're up for that, simply increase RD_KAFKAP_TOPICS_MAX in `src/rdkafka_int.h`, recompile and reinstall, and you should be (fairly) good.

**Comment by edenhill** [comment]
I bumped the limit in librdkafka master branch.
