### ISSUE TITLE
Two packages written to the same partition/offset

### ISSUE THREAD

**Issue by mfjinreno** [confluentinc/confluent-kafka-python#820]
Description
===========
We pass a key to correlate the partition/offset to a message, and found logs of two different messages producing to the same partition/offset

How to reproduce
================
I am unsure if there are re-production steps. The two messages were sent together at the same time, and only one is recorded in our logs (the message with ID ending in 13).

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.3.0 
 - [X] Apache Kafka broker version:  confluent 3.3.2
 - [X] Client configuration: `{
        "bootstrap.servers": config_data['bootstrap_servers'],
        "schema.registry.url": config_data['schema_registry_url'],
        "<redacted>": <redacted>,
        ""<redacted>": <redacted>,
       "<redacted>": <redacted>,,
        "client.id": config_data['client_id'],
        "security.protocol": "SSL",
        "ssl.certificate.location": "/tmp/cert.pem",
        "ssl.key.location": "/tmp/key.key",
        "ssl.ca.location": "cert/sdproot.pem",
        "datawise.environment.config": config_data['datawise_environment_config'],
        "datawise.cache.refresh.time.minutes.config": 1
    }`: 
 - [X] Operating system: AWS Linux
 - [X] Provide client logs (with `'debug': '..'` as necessary) See photos below
 - [X] Provide broker log excerpts: co-worker will attach below once ticket is open
 - [ ] Critical issue

![Screen Shot 2020-03-25 at 12 00 24 PM copy](https://user-images.githubusercontent.com/8055341/78380522-9d6f8900-7599-11ea-9fc7-dd3d87389a02.jpg)
![Screen Shot 2020-03-25 at 12 01 14 PM](https://user-images.githubusercontent.com/8055341/78380531-9ea0b600-7599-11ea-903a-1180ffc9dbda.jpg)

**Comment by edenhill** [comment]
Maybe the messages were partitioned to the same partition.
