### ISSUE TITLE
Mirror Maker 2.0 Support

### ISSUE THREAD

**Issue by jondeandres** [confluentinc/confluent-kafka-python#822]
Description
===========

We are considering using Mirror Maker 2.0 to handle failovers. We've checked that kafka provides some utils classes to find the consumer group offsets in the failover cluster but we cannot see nothing on Python or this library.

Do you expect to add a functionality to this library to handle that situation? If not, do you have an idea of what steps we could follow to do it ourself?

Thank you very much.

**Comment by edenhill** [comment]
No such plans
