### ISSUE TITLE
fetch.max.bytes does not work as advertised

### ISSUE THREAD

**Issue by candlerb** [confluentinc/confluent-kafka-python#823]
Description
===========

The [documentation](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) for `fetch.max.bytes` says:

> Maximum amount of data the broker shall return for a Fetch request. Messages are fetched in batches by the consumer and if the first message batch in the first non-empty partition of the Fetch request is larger than this value, then the message batch will still be returned to ensure the consumer can make progress. The maximum message batch size accepted by the broker is defined via `message.max.bytes` (broker config) or `max.message.bytes` (broker topic config). `fetch.max.bytes` is automatically adjusted upwards to be at least `message.max.bytes` (consumer config).

This implies that a value of 1 is acceptable: (a) because any single message larger than `fetch.max.bytes` will still be fetched, and (b) because it should be "automatically adjusted upwards" if required.

However, in reality, small values of `fetch.max.bytes` cause an exception.

How to reproduce
================

```
consumer = Consumer({
...
"fetch.max.bytes": 1,
...
})
```

gives the following exception:

```
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create consumer: `fetch.max.bytes` must be >= `message.max.bytes`"}
```

Checklist
=========
Please provide the following information:

 - confluent-kafka-python and librdkafka version: `('1.3.0', 16973824)` and  `('1.3.0', 16974079)`
 - Apache Kafka broker version: `confluentinc/cp-kafka:5.2.1` (docker)
 - Operating system: Ubuntu 18.04

Background
==========

What I'm trying to do is to subscribe to multiple topics and fetch them in priority order: e.g. if a message exists in `T1` then I always prefer to consume that first over a message in `T2`.

It's my understanding that the fetch request in the wire protocol supports [topics to fetch in the order provided](https://kafka.apache.org/protocol#The_Messages_Fetch).

But for this to work, I need to minimise the number of messages fetched and buffered locally, preferably fetching one at a time for each `poll()`.  Yes, I do realise this is a high-latency, low-throughput approach.

**Comment by rnpridgeon** [comment]
>Maximum Kafka protocol response message size. This serves as a safety precaution to avoid memory exhaustion in case of protocol hickups. This value must be at least fetch.max.bytes + 512 to allow for protocol overhead; the value is adjusted automatically unless the configuration property is explicitly set.


https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by rnpridgeon** [comment]
Looks like this only true if it hasn't been set manually. I agree the doc is a bit misleading about that. 

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_conf.c#L3409-L3410

I recommend reviewing the following for an explanation on how offsets are fetched. 

https://github.com/edenhill/librdkafka/wiki/FAQ#how-are-partitions-fetched
