### ISSUE TITLE
Memory leak when assign/unassign consumer without consume

### ISSUE THREAD

**Issue by vane4karock** [confluentinc/confluent-kafka-python#831]
Description
===========
Found that when assign / unassign consumer without consume, my app start use more memory.

In the end of  investigation found that it is some metadata that consumer store in heap.
`
{ "name": "controller_2#consumer-1", "client_id": "controller_2", "type": "consumer", "ts":12976427600, "time":1586772699, "replyq":6458, "msg_cnt":0, "msg_size":0, "msg_max":0, "msg_size_max":0, "simple_cnt":0, "metadata_cache_cnt":1, "brokers":{ "localhost:9092/1": { "name":"localhost:9092/1", "nodeid":1, "nodename":"localhost:9092", "source":"learned", "state":"UP", "stateage":3499950259, "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":1, "waitresp_msg_cnt":0, "tx":20644, "txbytes":1865746, "txerrs":0, "txretries":0, "req_timeouts":0, "rx":20643, "rxbytes":1851988, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "zbuf_grow":0, "buf_grow":0, "wakeups":46970, "connects":1, "disconnects":0, "int_latency": { "min":0, "max":0, "avg":0, "sum":0, "stddev": 0, "p50": 0, "p75": 0, "p90": 0, "p95": 0, "p99": 0, "p99_99": 0, ... }
`

That is bad, because servers sometimes stop sending data more then few hours.
Looks like some BUG.

How to reproduce
================
```python
import os
import time

from confluent_kafka import Consumer, TopicPartition

def assign_to(consumer, data, topics):
    assign_lst = []
    for tpc in topics:
        if data.get(tpc) is None:
            cmd = consumer.list_topics(topic=tpc)
            part_lst = list(cmd.topics[tpc].partitions.keys())
            data[tpc] = [TopicPartition(tpc, part, 0) for part in part_lst]

        try:
            assign_lst += data[tpc]
        except KeyError:
            print('ERROR')

    consumer.assign(assign_lst)

config = {
    "bootstrap.servers": "localhost:9092",
    "group.id": "fc_kafka_parser_parsed_consumers",
    "auto.offset.reset": "earliest",
    "enable.auto.commit": False,
    "client.id": "controller_2",
    "socket.keepalive.enable": True,
    "statistics.interval.ms": 500,
    "session.timeout.ms": 90000,
    "heartbeat.interval.ms": 1000,
    "max.poll.interval.ms": 86400000
}

print(os.getpid())
c = Consumer(config)

while True:
    print('ASSIGN')
    assign_to(c, {}, ['gameStat'])
    print('SLEEP 5 SEC...')
    time.sleep(5)
    print('UNASSIGN')
    c.unassign()
```

After some time (2 hours in my case) in console:
```bash
pmap -x <pid>
```
Find many big anon blocks using 65500+ memory, like this:
```bash
00007fe32c000000   83012   83012   83012 rw---   [ anon ]
00007fe32c000000       0       0       0 rw---   [ anon ]
00007fe331111000   48060       0       0 -----   [ anon ]
00007fe331111000       0       0       0 -----   [ anon ]
00007fe334000000     132      24      24 rw---   [ anon ]
00007fe334000000       0       0       0 rw---   [ anon ]
00007fe334021000   65404       0       0 -----   [ anon ]
00007fe334021000       0       0       0 -----   [ anon ]
00007fe338000000     132      40      40 rw---   [ anon ]
00007fe338000000       0       0       0 rw---   [ anon ]
00007fe338021000   65404       0       0 -----   [ anon ]
00007fe338021000       0       0       0 -----   [ anon ]
00007fe33f5e4000       4       0       0 -----   [ anon ]
00007fe33f5e4000       0       0       0 -----   [ anon ]
```
Then we using `gdb` to dump the content of these blocks:
```bash
sudo gdb -pid <pid>
dump memory mem.bin 0x00007fe32c000000 0x00007fe32c000000+83012
```
```bash
cat mem.bin | strings
```
And this is consumer metadata.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```python
import confluent_kafka
confluent_kafka.version()
('1.4.0', 17039360)
confluent_kafka.libversion()
('1.4.0', 17039615)
```
 - [x] Apache Kafka broker version:
```bash
root@remotehost:~# /usr/local/kafka/bin/kafka-topics.sh --version
2.3.0 (Commit:fc1aaa116b661c8a)
```
 - [x] Client configuration: `See above`
 - [x] Operating system: `Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-55-generic x86_64)`
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is expected;
You have statistics enabled (with and interval of 2 hz), which makes the client generate a JSON object with statistics two times per second and enqueue it for your application to trigger the stats_cb on the next call to poll. If you don't call poll these stats will queue up.

**Comment by vane4karock** [comment]
Ok, I understand.
Thanks.
