### ISSUE TITLE
Installation fails on Windows with Python 3.8 using pip install

### ISSUE THREAD

**Issue by DarkBlueSky18** [confluentinc/confluent-kafka-python#836]
Description
===========
On a Windows 10 machine with Python 3.8 my installation fails.
OS: Windows 10
Python: 3.8
pip: 20.0.2

Attached the full install log file. The pip command is issued at a CMD prompt with administrator privileges. Added 4 other python packages through pip in the same session with no error or issues.

How to reproduce
================
 pip install confluent-kafka 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ Y] Operating system: Windows 10
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [Y ] Critical issue

----------------
[confluent-kafka-install-log.txt.log](https://github.com/confluentinc/confluent-kafka-python/files/4484858/confluent-kafka-install-log.txt.log)

**Comment by marzetas** [comment]
Looks very similar to the issue described at https://github.com/confluentinc/confluent-kafka-python/issues/830

It seems there is an issue with a number of `requirements.txt` files being specified in setup.py, but not included in the package:
```
2020-04-16T00:01:05,283     FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cmj\\AppData\\Local\\Temp\\pip-install-7i_miaxz\\confluent-kafka\\confluent_kafka\\requirements.txt'
```

**Comment by chintanj80** [comment]
I have seen the same on someone's machine. The dev's need to review the issue as high priority.

**Comment by Kaifee-Mohammad** [comment]
oh so it's not limited to my machine only, something is wrong with the latest release.

**Comment by chintanj80** [comment]
Does anyone think this issue will be looked into soon enough ?

**Comment by marzetas** [comment]
> Does anyone think this issue will be looked into soon enough ?

According to @rnpridgeon, it should be solved in version 1.4.1

**Comment by TechnoShakeel** [comment]
> > Does anyone think this issue will be looked into soon enough ?
> 
> According to @rnpridgeon, it should be solved in version 1.4.1

I still this issue on version 1.4.1  :-(

**Comment by AshwinNS** [comment]
Is there any update on this, I'm trying to install `confluent-kafka~1.4.2` on `CentOs` with `python3.8` im still having trouble. Error is `command 'gcc' failed with exit status 1`. What am i missing here ?

**Comment by marzetas** [comment]
I think you need to install `gcc` to compile the library. You should be able to do it in CentOs by running `yum -y install gcc`

**Comment by AshwinNS** [comment]
The OS is `alpine-slim`, Updated the previous comment as well. `gcc` is already available in the machine.

**Comment by marzetas** [comment]
> The OS is `alpine-slim`, Updated the previous comment as well. `gcc` is already available in the machine.

You'll need to give more details that just the final gcc error. I'd recommend to open a different issue altogether, as your problem is probably not related to this one.

**Comment by AshwinNS** [comment]
Before adding the issue i cross checked again and i found out the `RC`. I had `librdkafka~1.2.2` and `confluent-kafka` was complaining about the same. `confluent-kafka~1.4.2` require `librdkafka~1.4.0` or higher. Updated `librdkafka` version and started working. Thanks.
