### ISSUE TITLE
Multiple topics with different schemata for DeserializingConsumer

### ISSUE THREAD

**Issue by shavera** [confluentinc/confluent-kafka-python#838]
Description
===========
Consumers can subscribe to multiple topics and include the topic information in the message returned from 'poll()'. The DeserializingConsumer is constructed with a single key.deserializer and value.deserializer. It is not clear if it is possible to register seperate deserializers for each topic.

Similar arguments could be made for the SerializingProducer as well.

This parallels issue #834 , but is slightly different. Should #834 be resolved in such a way that the SerializationClients are able to query for the schema of a topic, then hopefully if multiple topics were used by either, they could generate the appropriate (De)Serialization classes themselves.

However, independently of that issue, perhaps key.deserializer, value.deserializer could take a dictionary of serializer objects? The string key being the topic that the deserializers would be associated with.

How to reproduce
================
(Feature Request)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.4.1', 17039616), libversion: ('1.4.0', 17039615)
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: CentOS 8
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Thank you for your input and for linking the similar issue used for tracking. I suspected this may be  a high-demand area. 

>key.deserializer, value.deserializer could take a dictionary of serializer objects

I was thinking something along the same lines. Where the deserializers are keyed by the records name falling through to "default" which just uses the writer schema and returns a dictionary. I'll bring it up in our upcoming team meeting.

**Comment by JordanGardiner-enable** [comment]
Hi!

I see this has been marked as completed yet I don't see any documentation for how to provide multiple schemas to the consumer? Can you please link me to some?

Also the same functionality for producers would be helpful too! 

Kind Regards
-Jordan
