### ISSUE TITLE
Expose OAUTH config options

### ISSUE THREAD

**Issue by serkef** [confluentinc/confluent-kafka-python#839]
Description
===========
When creating a Producer/Consumer, user is expected to provide configuration based on librdkafka [configuration](https://github.com/edenhill/librdkafka/blob/2590e9c36c925fbda0c953725350906e0f36a414/CONFIGURATION.md). When we try to set OAUTH options, we get an error:

```
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Property "oauthbearer_token_refresh_cb" must be set through dedicated .._set_..() function"}
```

We want kafka to contact our OAUTH server and get authenticated to de/serialize messages.

How to reproduce
================
```
from confluent_kafka import DeserializingConsumer

config = {
    "bootstrap.servers": "localhost:9094",
    "group.id": "test-01",
    "enable.auto.commit": "true",
    "auto.commit.interval.ms": "1000",
    "auto.offset.reset": "earliest",
    "sasl.mechanism": "OAUTHBEARER",
    "oauthbearer_token_refresh_cb": lambda x: logger.info(f"TEST {x}"),
    "security.protocol": "SASL_SSL",
}
consumer = DeserializingConsumer(config)
```
Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.4.0', 17039360), ('1.4.0', 17039615)
 - [x] Apache Kafka broker version: 2.4
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Linux Mint 19.2
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Thanks, we have put this off until we got some demand for it. I'll mark this issue for consideration. PRs are of course also welcome.

**Comment by serkef** [comment]
@rnpridgeon I would be glad to contribute on this, but I will need some guidance, especially if I have to touch the C-bindings :)
