### ISSUE TITLE
Usage of Schema Registry for Protbuf

### ISSUE THREAD

**Issue by hfjn** [confluentinc/confluent-kafka-python#845]
Hi, I'm trying to set up a consumer which deserializes protobuf messages written by a .NET Confluent Producer. The Schema resides in the Schema Registry. 
If I understand the [example code](https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/protobuf_consumer.py) correctly it never uses the schema registry but simply reads in generated protobuf code to deserialize the kafka messages. 
Is the schema registry support for protobuf just a WIP or am I missing something? I'm super confused right now.

**Comment by hfjn** [comment]
For clarification: What I want to achieve is the python equivalent to this command: ```./kafka-protobuf-console-consumer --topic t1 --bootstrap-server localhost:9092 --property schema.registry.url=http://localhost:8081```

**Comment by mhowlett** [comment]
we don't yet support dynamically reading protobuf encoded messages in python. you're required to provide a class generated by `protoc` to the protobuf deserializer (which needs to be compatible with, but does not need to exactly match the schema used to write the data), which provides a convenient way to work with the data programmatically. unlike avro, protobuf serialized data can be deserialized without access to the writer schema, so there's no real need to lookup the writer schema in Schema Registry, given we have a reader schema to interpret the data.

there is not yet a good story for reading from topics that contain data written with different schemas.

**Comment by hfjn** [comment]
Hm. I always assumed the schema registry to be the central hub for schemas so reader and writer have a single point of truth for the schemas needed to serialize and deserialize the messages. At least this is how e.g. debezium uses is to keep track of schema changes in the observed databases. 
This method is especially helpful when updating schemas in the producer with new fields without having the need to redeploy the consumers. It makes you able to perfectly sync the switch of the schema between produced and consumer.
Tbh I don't really see the point of having the schema registry at all if the consumer can't access and use it to interpret the consumed data.

**Comment by mhowlett** [comment]
if you upgrade your producer schema in a forwards compatible way, this will sbe deserialized correctly by deserializers that are still using the previous schema version in the protobuf case, even without schema registry integration, since protobuf serializes tag and type information (avro doesn't, so the writer schema is needed to read it even if a reader schema is provided).

it is true that there could be some benefit to having the writer schema present on read if you want to consider field names in determining compatibility, but even the compatibility checker implementation inside Schema Registry doesn't do this and I would guess it never will, due to the way protobuf defines compatibility.

**Comment by hfjn** [comment]
Okay. Thanks for your time! 👍 Would be super happy to see support for the schema registry in the future, but will implement it with a generated class for now.

**Comment by nivgold** [comment]
> we don't yet support dynamically reading protobuf encoded messages in python. you're required to provide a class generated by `protoc` to the protobuf deserializer (which needs to be compatible with, but does not need to exactly match the schema used to write the data), which provides a convenient way to work with the data programmatically. unlike avro, protobuf serialized data can be deserialized without access to the writer schema, so there's no real need to lookup the writer schema in Schema Registry, given we have a reader schema to interpret the data.
> 
> there is not yet a good story for reading from topics that contain data written with different schemas.

What about the use-cases when you want to deploy a consumer which it's topic is configurable and determined at runtime?
then, the requested feature is requried
