### ISSUE TITLE
confluent-kafka 0.9.2 does not provide the extra 'avro'

### ISSUE THREAD

**Issue by co-dh** [confluentinc/confluent-kafka-python#85]
while install like below:

`C_INCLUDE_PATH=/PATH/TO/librdkafka/0.9.1/include LIBRARY_PATH=/PATH/librdkafka/0.9.1/lib pip install --user --upgrade confluent-kafka[avro]`

I got following error:

You are using pip version 7.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting confluent-kafka[avro]
  Using cached confluent-kafka-0.9.2.tar.gz
  confluent-kafka 0.9.2 does not provide the extra 'avro'

Can you help?

**Comment by edenhill** [comment]
avro support was just merged so it is only available on the master branch, which means you'll have to download/clone latest master and do:
```
$ C_INCLUDE_PATH=... LIBRARY_PATH=.. pip install .
$ C_INCLUDE_PATH=... LIBRARY_PATH=.. pip install .[avro]
```

**Comment by co-dh** [comment]
It works, thanks.
