### ISSUE TITLE
Unable to register schema with logical types

### ISSUE THREAD

**Issue by zachary-povey** [confluentinc/confluent-kafka-python#852]
Description
===========
Related to #614. When registering a schema which contains a logical type, the following error is raised:
`TypeError: Object of type 'mappingproxy' is not JSON serializable` 

This is seemingly due to [this issue](https://issues.apache.org/jira/browse/AVRO-2411) with the python avro library. This article suggests that rather than doing  

```python
body = {'schema': json.dumps(avro_schema.to_json())}
```

to create the request body (as in `confluent-kafka-python/confluent_kafka/avro/cached_schema_registry_client.py`) you should do:

```python
body = {'schema': str(avro_schema)}
```
How to reproduce
================
```python
from confluent_kafka import avro
from confluent_kafka.avro import CachedSchemaRegistryClient
import json
schema = {
    "name": "a_schema",
    "type": "record",
    "fields": [
        {
            "name": "date_field",
            "type": {
                "type": "int",
                "logicalType": "date"
            }
        }
    ]
}
value_schema = avro.loads(json.dumps(schema))
client = CachedSchemaRegistryClient("http://fake_url")
client.register("a_subject", value_schema)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.4.1', 17039616), ('1.4.0', 17039615)
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: N/A
 - [ ] Operating system: Mac OS -> Docker (CentOS)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by rnpridgeon** [comment]
This is actually the result of a breaking change made in the Apache Avro implementation. The new Serialization API, which uses FastAvro exclusively, handles this well. 

https://docs.confluent.io/current/clients/confluent-kafka-python/#schemaregistryclient
https://docs.confluent.io/current/clients/confluent-kafka-python/#schema
