### ISSUE TITLE
AdminClient.delete_topics returns before propagating delete

### ISSUE THREAD

**Issue by spenczar** [confluentinc/confluent-kafka-python#856]
Description
===========
Even when `operation_timeout` is set, `AdminClient.delete_topics` appears to return before topic deletion has actually propagated. If I follow a delete call with an immediate create_topics call, then topic creation consistently errors with `TOPIC_ALREADY_EXISTS`. If I sleep after the delete call, though, it works.

How to reproduce
================
Run the following script, and you'll get an error. Modify it to set `SHOULD_SLEEP = True` and the error goes away.
```python
#!/usr/bin/env python
import confluent_kafka
import confluent_kafka.admin
import time


SHOULD_SLEEP = False


def main():
    admin_config = {
        "bootstrap.servers": "localhost:9092",
    }
    admin_client = confluent_kafka.admin.AdminClient(admin_config)
    topic_name = "demo-topic-deletion"
    new_topic = confluent_kafka.admin.NewTopic(
        topic=topic_name,
        num_partitions=1,
        replication_factor=1,
    )
    create_response = admin_client.create_topics([new_topic],
                                                 operation_timeout=1.0)
    create_response[topic_name].result()

    delete_response = admin_client.delete_topics([topic_name],
                                                 operation_timeout=1.0)
    delete_response[topic_name].result()

    if SHOULD_SLEEP:
        time.sleep(5)

    create_response = admin_client.create_topics([new_topic],
                                                 operation_timeout=1.0)
    create_response[topic_name].result()


if __name__ == "__main__":
    main()
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```
>>> import confluent_kafka
>>> confluent_kafka.version()
('1.4.1', 17039616)
>>> confluent_kafka.libversion()
('1.4.0', 17039615)
```
 - [x] Apache Kafka broker version:
5.1.4, run as `confluentinc/cp-kafka:5.1.4` docker container.

 - [x] Client configuration: `{...}`
See above.
 - [x] Operating system:
Linux 5.4.0 (x86_64)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by spenczar** [comment]
This could be related to https://github.com/apache/kafka/pull/7343. Is there a configuration change I can make to be _really_ sure the delete has propagated?

**Comment by spenczar** [comment]
@edenhill was this fixed in a particular recent release? Just wondering why this was closed.

**Comment by edenhill** [comment]
This is an AK issue that we can't do much about.
