### ISSUE TITLE
Message is missing len method

### ISSUE THREAD

**Issue by spenczar** [confluentinc/confluent-kafka-python#859]
Description
===========
Documentation says that Message has a `len()` method: https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Message.len

This field doesn't appear to actually exist. However, there _is_ an undocumented `__len__()` method: https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/src/confluent_kafka.c#L678-L680. Perhaps the documentation missed this.

How to reproduce
================
Create a consumer, call consume, and try to call `msg.len()`.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```
>>> import confluent_kafka
>>> confluent_kafka.version()
('1.4.1', 17039616)
>>> confluent_kafka.libversion()
('1.4.0', 17039615)
```
 - [x] Apache Kafka broker version:
5.1.4, run as `confluentinc/cp-kafka:5.1.4` docker container.

 - [x] Client configuration: `{...}`
See above.
 - [x] Operating system:
Linux 5.4.0 (x86_64)

**Comment by edenhill** [comment]
The intended use is the standard Python `len(msg_object)`

**Comment by spenczar** [comment]
I see. This might just be a documentation issue, then.
