### ISSUE TITLE
setting offset INVALID for commit

### ISSUE THREAD

**Issue by co-dh** [confluentinc/confluent-kafka-python#86]
Hello:
    I have the following error when debug=cgrp

```
%7|1480085699.790|OFFSET|rdkafka#consumer-1| Topic dev-ny-email5 [2]: stored off -1001, committted off -1001
%7|1480085699.790|OFFSET|rdkafka#consumer-1| Topic dev-ny-email5 [2]: setting offset INVALID for commit
```
and here is the code
```
c = Consumer({
      'bootstrap.servers'    : 'nyzls70d:19000',
      'group.id'             : 'mygroup99',
      'debug'                : 'cgrp', #'cgrp', #,topic,fetch',
      'default.topic.config' : {'auto.offset.reset': 'smallest'}
      })

  c.subscribe(['dev-ny-email5'])
  running = True
  while running:
      print 'polling... '
      msg = c.poll()
      print 'polled'

```
I believe it try to save offset -1001, but don't know how to fix it.
Any idea?
Thanks in advance.

**Comment by edenhill** [comment]
That's not an error, just a debug message saying there are no offsets to commit so it defaults to offset INVALID, which it wont commit.

**Comment by co-dh** [comment]
Thanks @edenhill. 
Then my problem is the above process hangs at c.poll().  "polled" never get printed.

I'm new to Kafka. the Kafka manager has a setting like : Please enable consumer polling here, so it's seemed that polling might not enabled, do you think this is the issue?

**Comment by edenhill** [comment]
Without a timeout it will "hang" on poll() until a new message is available (produced)

**Comment by co-dh** [comment]
but I set it to start from beginning in default.topic.config auto.offset.reset, and there are a lot of messages in the queue, so I don't understand why it's not getting any messages. I also changed to a new group.id with the same effect. The console consumer is able to retrieve messages, so the queue has no problem.

Thanks for your fast response

**Comment by co-dh** [comment]
I need to see that my message is very big and will exceed the max fetch size at beginning.
The console consumer gives me that error.

**Comment by co-dh** [comment]
Ok, I figured out it's the fetch max size, adding below works:

'fetch.message.max.bytes': 21000000,

Can we have an error for this case? thanks.

**Comment by edenhill** [comment]
Which librdkafka version are you on? (`print(confluent_kafka.libversion())`)
librdkafka v0.9.2 automatically increases the fetch size until it can completely receive a large message.
