### ISSUE TITLE
Producer error_cb is not called when messages are rejected by the broker for being too large

### ISSUE THREAD

**Issue by spenczar** [confluentinc/confluent-kafka-python#860]
Description
===========
I have a producer configured with a `message.max.bytes` of `10_000_000` (10MB), and an error_cb which loudly prints errors. I have a broker with `message.max.bytes` left at the default, `1_000_000` (1MB).

I call `producer.produce`, sending a message which is 2MB. From turning on debug logging with `"debug": "msg"` in my producer config, I can see that the message is rejected for being too large, but I didn't get an error in the error_cb like I would have expected.

How to reproduce
================
With a broker up and running at `localhost:9092` with `message.max.bytes` left at the default:
```python
import confluent_kafka
def error_callback(err):
    print("callback hit!")
    raise(err)
p = confluent_kafka.Producer({
    "bootstrap.servers": "localhost:9092",
    "message.max.bytes": 10_000_000,
    "error_cb": error_callback,
    "debug": "msg",
})
p.produce("test-topic", "a" * int(2e6))
p.flush()
```
When I run this program I see this:
```%7|1588885316.913|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.4.0 (0x10400ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, STATIC_LINKING GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL ZSTD HDRHISTOGRAM SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x40)
%7|1588885316.915|PROTOERR|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Protocol parse failure for ApiVersion v3 at 3/6 (rd_kafka_handle_ApiVersion:1911) (incorrect broker.version.fallback?)
%7|1588885316.915|PROTOERR|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: ApiArrayCnt -1 out of range
bugdemo.py:11: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  p.produce("test-topic", "a" * int(2e6))
%7|1588885318.915|PRODUCE|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: test-topic [0]: Produce MessageSet with 1 message(s) (2000074 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid}, uncompressed)
%7|1588885318.922|MSGSET|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/1: test-topic [0]: MessageSet with 1 message(s) (MsgId 0, BaseSeq -1) encountered error: Broker: Message size too large (actions Permanent,MsgNotPersisted)
%7|1588885318.931|DESTROY|rdkafka#producer-1| [thrd:app]: Terminating instance (destroy flags none (0x0))
%7|1588885318.931|DESTROY|rdkafka#producer-1| [thrd:main]: Destroy internal
```

Note in particular the `encountered error: Broker: Message size too large (actions Permanent,MsgNotPersisted)` line, but the absence of any `callback hit!` text.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```
>>> import confluent_kafka
>>> confluent_kafka.version()
('1.4.1', 17039616)
>>> confluent_kafka.libversion()
('1.4.0', 17039615)
```
 - [x] Apache Kafka broker version:
5.1.4, run as `confluentinc/cp-kafka:5.1.4` docker container.

 - [x] Client configuration: `{...}`
See above.
 - [x] Operating system:
Linux 5.4.0 (x86_64)

**Comment by edenhill** [comment]
The `error_cb` is for general client-level errors and events.

Per-message delivery report status/error is propagated through the delivery report callback which you can pass to the produce() call.

**Comment by spenczar** [comment]
Aha! That explains it. Thanks.
