### ISSUE TITLE
Please release version 1.4.2

### ISSUE THREAD

**Issue by gandalf013** [confluentinc/confluent-kafka-python#862]
Description
===========

Our code is affected by [librdkafka issue 2782](https://github.com/edenhill/librdkafka/issues/2782), which seems to have been fixed in version 1.4.2.  It would be great to see updated Python packages that use the fixed librdkafka.

(I know it's only been 3 days so this might already be in the works, apologies in that case.)

How to reproduce
================

https://github.com/edenhill/librdkafka/issues/2782

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.0.1', 16777472)
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Linux (Ubuntu 18.04)
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by dimon222** [comment]
Seems it's out

**Comment by gandalf013** [comment]
Thanks!
