### ISSUE TITLE
Conda distribution of confluent_kafka package does not contain Admin module

### ISSUE THREAD

**Issue by rkredux** [confluentinc/confluent-kafka-python#870]
Description
===========
The admin module is missing in the confluent_kafka when installed from the Conda distribution

How to reproduce
================
Run  `conda install -c conda-forge python-confluent-kafka`

 (which appears as one of the ways to install the client on this page - https://anaconda.org/conda-forge/python-confluent-kafka)

set up a demo.py with the code below 

#demo.py 
from confluent_kafka.admin import AdminClient
print(AdminClient)

run the code 
python demo.py 

#error 
ModuleNotFoundError: No module named 'confluent_kafka.admin'

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): the version on conda distribution page shows 1.3.0 at the time of typing this issue
 - [ ] Apache Kafka broker version: happens before the broker is set up
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: 
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
We don't provide conda packages.
