### ISSUE TITLE
How to add SASL_PLAINTEXT in variable in Kafka

### ISSUE THREAD

**Issue by quanghn96** [confluentinc/confluent-kafka-python#876]
Description
===========
 
I want this string in kafka.properties is sasl_plaintext

How to reproduce
================
KAFKA_LISTENER_NAME_SASL_PLAINTEXT_SASL_ENABLED_MECHANISMS: PLAIN

In kafka.properties

sasl.plaintext

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
my_conf = 
{...
   'security.protocol': "SASL_PLAINTEXT",
   'sasl.username': "my_user",
   'sasl.password': "my_password",
...}

**Comment by edenhill** [comment]
`'sasl.mechanism': 'PLAIN'` is also required
