### ISSUE TITLE
Provide manylinux2014 wheel for aarch64

### ISSUE THREAD

**Issue by hrw** [confluentinc/confluent-kafka-python#877]
Description
===========

confluent_kafka is not installable on AArch64 architecture. Debian stable, Ubuntu xenial/bionic/focal, CentOS 7/8 all have too old 'librdkafka' package (as 1.4.0+ is needed).

How to reproduce
================

pip install confluent_kafka

Suggestion
=======

I see that you are using Travis CI to build wheels. Will take a look and try to add aarch64 manylinux2014 target there.

**Comment by mhowlett** [comment]
Building librdkafka from source is really easy, so suggest doing that:

https://github.com/edenhill/librdkafka#build-from-source

**Comment by odidev** [comment]
@mhowlett, building librdkafka from source is of course easy but user needs to have the development environment installed. This is again painful rather than deploying AArch64 wheels and allowing user to install from the PyPi.

**Comment by kpark-hrp** [comment]
agreed, would love a `manylinux2014` build
