### ISSUE TITLE
|FAIL|rdkafka#producer-2| [thrd:sasl_ssl:///bootstrap]: sasl_ssl:///bootstrap: Connect to ipv4# failed: Connection refused (after 0ms in state CONNECT)

### ISSUE THREAD

**Issue by venkatrmrddy** [confluentinc/confluent-kafka-python#878]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by nick4fake** [comment]
Seriously, you've created ticket with no description and no information even while this repo has issue template?
