### ISSUE TITLE
pylint: prefix local error codes with CLIENT_ rather than _

### ISSUE THREAD

**Issue by co-dh** [confluentinc/confluent-kafka-python#88]
the KafkaError._PARTITION_EOF is private because it starts with underscore, however,  we need 
check if msg.error().code() != KafkaError._PARTITION_EOF to know if it's a real error.

Either we provide a function on this, or make this _PARTITION_EOF public by change it to PARTITION_EOF.

**Comment by edenhill** [comment]
The underscore-errors relate to local error codes, while the non-underscore ones relate to broker error codes.
In hind-sight the underscore prefix might have been a lapse, but changing this would be a break existing apps.
Also, the underscore-is-private is not a hard rule, just a convention, so what is the real problem? Pylint?

**Comment by co-dh** [comment]
Yes pylint.  How about we provide both the underscored and non underscored? and deprecated the underscored?

**Comment by edenhill** [comment]
Yeah, that make sense, we could use other means of differentiating between local and remote errors (not really sure it matters to the app though).
@ewencp comments?

**Comment by ewencp** [comment]
@edenhill Sounds good to me.

**Comment by edenhill** [comment]
There's a bunch of local errors that are likely to collide with future broker errors, such as UNKNOWN_PARTITION, UNKNOWN_TOPIC, TIMED_OUT, etc, so I think it might be better to prefix the local errors with something, or the broker errors.
Most of the error checks in applications will be using the local error codes, so it might make more sense to keep them unprefixed.
Suggestions?

**Comment by hqin** [comment]
Could we prefix with "CLT_" or "CLIENT_" for client side errors? In the days of SOAP faults, there is a separation of client side and server side faults
