### ISSUE TITLE
Not able to verify compression working correctly

### ISSUE THREAD

**Issue by deepaksood619** [confluentinc/confluent-kafka-python#881]
Description
===========
I have set compression in producer to `"compression.type": "snappy"` and created topic beforehand with `./kafka-topics.sh --create --bootstrap-server my-cluster-kafka-brokers.kafka:9092 --replication-factor 2 --partitions 3 --topic test --config compression.type="snappy"`.

With this configurations too if I inspect `bin/kafka-run-class.sh kafka.tools.DumpLogSegments --files /var/lib/kafka/data-0/kafka-log0/test-0/00000000000000000000.log --print-data-log`, I can see plaintext messages.

If I do Kafkacat too I can see plaintext messages with bigger payload size.
`kafkacat -C -b kafka0.stashfin.com:9094,kafka1.stashfin.com:9094,kafka2.stashfin.com:9094 -t test_bank_data_2 -o -2000 -f '\n%S,%T,%p,%o'`

I can't understand if payload is compressed or not. My single payload is huge and I want to compress each one of them.

If I am manually compressing using `python-snappy` I am able to see reduced payload with Kafkacat.

How can I verify that my payload is getting compressed or not?

If compressing manually send sending the compressed payload a right way?

My code:
```
p = Producer({
    "bootstrap.servers": os.environ.get("KAFKA_BOOTSTRAP_SERVERS"),
    "queue.buffering.max.messages": "1000000",
    "queue.buffering.max.kbytes": "1048576",
    "message.max.bytes": "15728640",
    "delivery.timeout.ms": "10000",
    "request.timeout.ms": "5000",
    "compression.type": "snappy"
})
push_data_compressed = snappy.compress(push_data)
p.produce('test', push_data_compressed, callback=delivery_report)
p.flush()
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka==1.4.1
 - [x] Apache Kafka broker version: 2.4.0 (Commit:77a89fcf8d7fa018)
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You can use `'debug': 'msg'` to see if a messageSet was compressed or not

**Comment by deeTEEcee** [comment]
that can be used as a quick check but it's not accurate enough if you have a mixed bag of compressions and uncompressed. https://stackoverflow.com/questions/36590471/how-can-i-verify-if-compression-is-working-correctly-in-kafka-0-8-2-2 provides something more detailed.
