### ISSUE TITLE
Is poll must there are no callbacks?

### ISSUE THREAD

**Issue by vikramindian** [confluentinc/confluent-kafka-python#885]
Description
===========

Hi, 
Is calling poll() mandatory when we do not register any callbacks (both error and delivery) for the producer?
What all things poll() do, apart from triggering callbacks?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
The python client sets a delivery callback internally: https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/src/Producer.c#L805 so you'll need to call poll periodically to flush the op queue that keeps track of this. You might find this blog post helpful: https://www.confluent.io/blog/kafka-python-asyncio-integration/
