### ISSUE TITLE
Message timed out

### ISSUE THREAD

**Issue by hhhhman** [confluentinc/confluent-kafka-python#888]
Description
===========
l use docker-compse.yml
### ### ### ### ### ### ### ### ### 
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 100
      KAFKA_ZOOKEEPER_CONNECT: 192.168.162.138:32181  
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.162.138:29092,PLAINTEXT_HOST://192.168.162.138:9092 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3

### ### ### ### ### ### ### ### ### ### ### 

_l can produce and comsumer in my container
but l git librdkafka and confluent-kafka-python
and use the example with producer  in con-kafka-python_
### ### ### ### ### ### ### ### ### ### ### ### 

from confluent_kafka import Producer

p = Producer({'bootstrap.servers': '192.168.162.138:29092'})

def delivery_report(err, msg):
    """ Called once for each message produced to indicate delivery result.
        Triggered by poll() or flush(). """
    if err is not None:
        print('Message delivery failed: {}'.format(err))
    else:
        print('Message delivered to {} [{}]'.format(msg.topic(), msg.partition()))

for data in ["eee%d"%i for i in range(10)]:
    # Trigger any available delivery report callbacks from previous produce() calls
    p.poll(0)

    # Asynchronously produce a message, the delivery report callback
    # will be triggered from poll() above, or flush() below, when the message has
    # been successfully delivered or failed permanently.
    p.produce('mytopic', data.encode('utf-8'), callback=delivery_report)

# Wait for any outstanding messages to be delivered and delivery report
# callbacks to be triggered.
p.flush()

if __name__ == '__main__':
    pass

### ### ### ### ### ### ### ### ### ### ### ### ### ### 

it raise 

> Message` delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed 

- out"}

why????????????????????????????????????????????????????????????????????????????????

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by yuviabhi** [comment]
How to solve this ? I'm facing the same issue.
