### ISSUE TITLE
Wrong Documentation in Schema Registry Client in confluent kafka 1.4.2

### ISSUE THREAD

**Issue by safaozturk93** [confluentinc/confluent-kafka-python#890]
Description
===========
For Schema Registry Client, `ssl.ca.location` specified with `*` as a required field.

https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/schema_registry/schema_registry_client.py#L263

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [1.4.2] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks!
