### ISSUE TITLE
Check topic memory usage

### ISSUE THREAD

**Issue by tatianafrank** [confluentinc/confluent-kafka-python#902]
Description
===========
Is there a way to check the total memory usage of a topic? We have a retention policy set to a max number of bytes and we're trying to check if we are hitting that max because messages are missing and we think that may be why. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.4
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
you can use the consumer's `get_watermark_offsets` method to get the offset of the first message in a topic/partition (which will be > 0 if messages have been removed from the partition).

the client doesn't allow you to get the total size of bytes currently in a partition. you could just go to kafka's log directory to the topic/partition(s) of interest and do `ls -l` to see total size on disk.

**Comment by edenhill** [comment]
Note that for compacted topics there may be gaps between the low and high watermark offsets.
