### ISSUE TITLE
No entry point to get and use delegation token

### ISSUE THREAD

**Issue by justinlinlin** [confluentinc/confluent-kafka-python#903]
Description
===========
https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_delegation.html
as above page metioned...
> You authenticate with the Kafka cluster via SASL or SSL, and obtain a delegation token. You can do this using the **AdminClient APIs** or the kafka-delegation-tokens script.

but in the **AdminClient** section, I didn't find a way to get delegation token.
https://docs.confluent.io/current/clients/confluent-kafka-python/index.html?highlight=delegation#module-confluent_kafka.admin

and in the **KafkaError** section, we indeed have some kind of error message related to delegation token here.
https://docs.confluent.io/current/clients/confluent-kafka-python/index.html?highlight=delegation#kafkaerror

I also checked the configuration of **librdkafka**, but didn't find any settings that related to get/use delegation token.
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

would like to know is there a way that we can **GET** and **USE** delegation token in **confluent-kafka-python**? THANKS.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent_kafka.version() -> ('1.4.2', 17039872), confluent_kafka.libversion() -> ('1.4.2', 17040127)
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Red Hat Enterprise Linux Workstation release 7.5
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Delegation tokens are not supported by the Python client and there are no immediate plans for this feature.
