### ISSUE TITLE
Get count of pending messages in kafka topic overall or per each partition

### ISSUE THREAD

**Issue by brshravan-tech** [confluentinc/confluent-kafka-python#904]
Description
===========

Is there any API to get count of pending messages in kafka topic (overall or per each partition).

I am connecting to Azure EventHub using the confluent-kafka python library and following https://docs.confluent.io/current/clients/confluent-kafka-python/ for API references but could not find any API to get details of pending messages

**Comment by edenhill** [comment]
That's what is generally called the consumer lag, namely the difference between a partition's high watermark (last message produced) and a consumer's (or rather consumer group's) current position.

You can calculate this at runtime in the consumer with get_watermark_offsets() and position() or committed(), or enable statistics and extract the per-partition consumer_lag field (https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md).

**Comment by brshravan-tech** [comment]
Thanks a lot @edenhill 

Combination of above APIs helped in obtaining the pending message count.
