### ISSUE TITLE
Error trying to use ProtobufSerializer

### ISSUE THREAD

**Issue by leoGalani** [confluentinc/confluent-kafka-python#907]
Description
===========
if you try to instatiate the class `ProtobufSerializer`, you will get a `ModuleNotFoundError: No module named 'google'`
After doing a `pip install protobuf` locally, the error is gone.

Searched the whole repo and there is no reference to this dependency on the multiples `requirements.txt` files.

```
confluent_kafka/schema_registry/protobuf.py:24: in <module>
    from google.protobuf.message import DecodeError
E   ModuleNotFoundError: No module named 'google'
```

How to reproduce
================
I think that the protobuf producer example from this repo will trigger this error.

Checklist
=========
Please provide the following information:

 - [latest] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [macOs] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to install the sub-package: `pip install confluent-kafka[protobuf]`

**Comment by leoGalani** [comment]
Gonna do a PR on the README.md
