### ISSUE TITLE
Give developers ability to pre-load and check Avro registry schema IDs.

### ISSUE THREAD

**Issue by arthurlm** [confluentinc/confluent-kafka-python#913]
# Description

Give developers ability to pre-load and check Avro registry schema IDs.

# Details description

Problem is on function `AvroSerializer.__call__(self, obj, ctx)`.

Currently it does the serialization __and__ loading data from registry.

This results in really poor performances when inserting the first message into Kafka.
It is particularly visible in applications which restart often and does not produce messages frequently.

Second problem is when `auto.register.schemas` equals `False`.
The app crash only on first message insertion and not at init.

Moreover (I have not tested it on my own), there might also be an error when same serializer instance is used for multiple topics.
Problem may comes from having only one `self._schema_id` per `AvroSerializer`.

# Example usage

Load / init the app (non critical section):

```python
avro_serializer = AvroSerializer(json.dumps(schema), schema_registry)

# Load registry info at init (feature request)
avro_serializer.load_registry_schema_id(SerializationContext(topic_name1, MessageField.VALUE))
avro_serializer.load_registry_schema_id(SerializationContext(topic_name2, MessageField.VALUE))
avro_serializer.load_registry_schema_id(SerializationContext(topic_name3, MessageField.KEY))

producer = SerializingProducer({
    'bootstrap.servers': ...,
    'key.serializer': avro_serializer,
    'value.serializer': avro_serializer,
})
```

Critical section (app need constant performances):

```python
producer.produce(...)
```

# Example of implementation

See below a possible implementation for the new `__call__` function.
Please note that I have not run tests suite on it.

```python
class AvroSerializer(Serializer):
    ...

    def load_registry_schema_id(self, ctx):
        subject = self._subject_name_func(ctx, self._schema_name)

        # Check to ensure this schema has been registered under subject_name.
        if self._auto_register and subject not in self._known_subjects:
            # The schema name will always be the same. We can't however register
            # a schema without a subject so we set the schema_id here to handle
            # the initial registration.
            self._schema_ids[subject] = self._registry.register_schema(subject,
                                                                       self._schema)
            self._known_subjects.add(subject)
        elif not self._auto_register and subject not in self._known_subjects:
            registered_schema = self._registry.lookup_schema(subject,
                                                             self._schema)
            self._schema_ids[subject] = registered_schema.schema_id
            self._known_subjects.add(subject)

        return self._schema_ids[subject]

    def __call__(self, obj, ctx):
        if obj is None:
            return None

        schema_id = self.load_registry_schema_id(ctx)

        if self._to_dict is not None:
            value = self._to_dict(obj, ctx)
        else:
            value = obj

        with _ContextStringIO() as fo:
            # Write the magic byte and schema ID in network byte order (big endian)
            fo.write(pack('>bI', _MAGIC_BYTE, schema_id))
            # write the record to the rest of the buffer
            schemaless_writer(fo, self._parsed_schema, value)

            return fo.getvalue()
```

Please note that `self._known_subjects` is only keep here for backward compatibility.
It can be replace by `self._schema_ids.keys()`.

## Checklist

- _Versions_: `confluent_kafka.version(1.4.2)`
- _Operating system_: ALL
- _Critical issue_: NO

**Comment by mhowlett** [comment]
if you look up the relevant schema(s) using the `schema_registry` instance prior to passing it into the `AvroSerializer` constructor, the results should be cached iirc, and those results used by the serializer.

**Comment by arthurlm** [comment]
Hi @mhowlett 

I may have miss understand you answer.
There is no cache in `confluent_kafka.schema_registry.schema_registry_client.SchemaRegistryClient.lookup_schema`.
You can check it by yourself using the following code:

```python
import confluent_kafka.schema_registry.schema_registry_client
from confluent_kafka.schema_registry import Schema

import logging
logging.basicConfig()
logging.getLogger("urllib3").setLevel(logging.DEBUG)

schema_registry = confluent_kafka.schema_registry.schema_registry_client.SchemaRegistryClient({
	"url": "http://coreinfra-dev-nye-1-schemaregistry.infra.aws.exoduspoint.com"
})

schema = Schema(..., schema_type='AVRO')
topic_name = ...

schema_registry.lookup_schema(topic_name, schema)
schema_registry.lookup_schema(topic_name, schema)
schema_registry.lookup_schema(topic_name, schema)
schema_registry.lookup_schema(topic_name, schema)
```

Output is:

```log
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ....com:80
DEBUG:urllib3.connectionpool:http://....com:80 "POST /subjects/... HTTP/1.1" 200 204
DEBUG:urllib3.connectionpool:http://....com:80 "POST /subjects/... HTTP/1.1" 200 204
DEBUG:urllib3.connectionpool:http://....com:80 "POST /subjects/... HTTP/1.1" 200 204
DEBUG:urllib3.connectionpool:http://....com:80 "POST /subjects/... HTTP/1.1" 200 204
```

Moreover this does not fix the problem with `self._shema_id` shared for multiple topics.

On my side I have partially "fix" the issue using the following code:

```python
def prefech_avro_registry(serializer: AvroSerializer, topic: str, field: str):
    ctx = SerializationContext(topic, field)
    try:
        serializer({}, ctx)
    except Exception:
        # We expect being here because data is incorrect
        pass
```

But this is __really far__ from perfect, because:

* I need to call `fastavro` related code and `StringIO` context with bad data
* I cannot know if pre load is success or failure

This is why my question is more related to a "feature request".

If required I can do a PR on it.

**Comment by mhowlett** [comment]
you're right, i was answering from memory. we definitely should allow the schema registry cache to be primed. feel free to open a PR.
