### ISSUE TITLE
When Idempotence write is lacking ACLs producer succeeds to write but no ack.

### ISSUE THREAD

**Issue by lethrez** [confluentinc/confluent-kafka-python#916]
Description
===========
As per the title, when trying to produce to a topic with "enable.idempotence": True, the producer will produce the record but fail to ack. I'd expect the producer to fail or an error thrown. Debug logs make it more apparent that auth is failing, with the log lines failing authentication over and over. 
Happy to close if this is expected behaviour, however, I'd expect an error to be thrown in the producer. 

producer_configuration =
{
            "ssl.ca.location": certifi.where(),
            "acks": "all",
            "bootstrap.servers": bootstrap_servers,
            "client.id": group_name,
            "enable.idempotence": True,
            "max.in.flight.requests.per.connection": 1,
            "retries": 3,
            "retry.backoff.ms": 100,
            "sasl.mechanism": "PLAIN",
            "security.protocol": "SASL_SSL",
            "sasl.password": ...,
            "sasl.username": ...,
            "value.serializer": AvroSerializer(schema_str=schema, schema_registry_client=client, conf=serializer_conf),
            "key.serializer": AvroSerializer(schema_str=schema, schema_registry_client=client, conf=serializer_conf)
            ),
        }

%7|1594947434.495|GETPID|t24.api.connector#producer-3| [thrd:main]: sasl_ssl://<removed>.confluent.cloud:9092/bootstrap: Acquiring ProducerId
%7|1594947434.495|IDEMPSTATE|t24.api.connector#producer-3| [thrd:main]: Idempotent producer state change WaitTransport -> WaitPID
%7|1594947434.495|SEND|t24.api.connector#producer-3| [thrd:sasl_ssl:///<removed>confluent.cloud:9092/bo]: sasl_ssl:///<removed>confluent.cloud:9092/bootstrap: Sent InitProducerIdRequest (v1, 37 bytes @ 0, CorrId 57)
%7|1594947434.514|RECV|t24.api.connector#producer-3| [thrd:sasl_ssl://pkc-lqnx6.ap-southeast-2.aws.confluent.cloud:9092/bo]: sasl_ssl:///<removed>.confluent.cloud:9092/bootstrap: Received InitProducerIdResponse (v1, 16 bytes, CorrId 57, rtt 18.97ms)
%7|1594947434.514|GETPID|t24.api.connector#producer-3| [thrd:main]: sasl_ssl://<removed>.confluent.cloud:9092/bootstrap: Failed to acquire PID: Broker: Cluster authorization failed

Checklist
=========
Please provide the following information:

 - [ 1.4.2] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ Confluent Cloud] Apache Kafka broker version:
 - [ provided] Client configuration: `{...}`
 - [ MacOs / Docker / OS indempendent] Operating system:
 - [ yes] Provide client logs (with `'debug': '..'` as necessary)
 - [ yes] Provide broker log excerpts
 - [No ] Critical issue

**Comment by edenhill** [comment]
That's definitely a bug, created upstream issue in librdkafka https://github.com/edenhill/librdkafka/issues/2994. This will be fixed in the next maintenance release (after v1.5.0)
