### ISSUE TITLE
Could someone please publish Windows wheels for Python 3.8?

### ISSUE THREAD

**Issue by gt6989b** [confluentinc/confluent-kafka-python#919]
Description
===========
I found Python 3.7 build for Windows, could someone please publish the wheels for Python 3.8? I tried to build from source but cannot get the link to `librdkafka` to work properly.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{Python 3.8}`
 - [x] Operating system: Windows 10
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Will be available in v1.6.0

**Comment by gt6989b** [comment]
> Will be available in v1.6.0

Is there any timeframe in which we expect 1.6.0 to be available? Also, will it include the fix for the fastavro decoding bug currently present in 1.5.0?
