### ISSUE TITLE
Tarball of 1.5.0 is not published on PyPi

### ISSUE THREAD

**Issue by dimon222** [confluentinc/confluent-kafka-python#921]
Description
===========

Tarball with source code wasn't published for new version 1.5.0 to Pypi. Only wheels are there.

How to reproduce
================

`pip install --no-binary :all: "confluent-kafka==1.5.0"`

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Red Hat Linux 7
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Sorry, missed the sdist upload.
sdist 1.5.0 is now on PyPi.


Den fre 24 juli 2020 kl 17:37 skrev Dmitry Romanenko <
notifications@github.com>:
