### ISSUE TITLE
AdminClient will go in infinite loop where there is wrong bootstrap.servers configuration provided

### ISSUE THREAD

**Issue by MohitAsingh** [confluentinc/confluent-kafka-python#922]
Description
===========
 While creating AdminClient object in python  noticed that it will go in infinite loop when there is a wrong bootstrap.servers configuration is provided so i was expecting it throw some kind of exception like TimeOutException but it won't it will go in loop..

How to reproduce
================

Provide wrong value in bootstrap.servers.
`client = AdminClient({'bootstrap.servers': 'wrongvalue:9090'})`
the program will stuck at this point in my case it's waiting for more then 30 min.

===============
I have checked the document but not sure that is there is timeout limit that we can provide because 30 min is huge we want the program report failure within 2-5 min

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Mac OS
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
yes, this trips people up a lot. this is relevant: https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down

IMO client creation is a special case, and we should expose a blocking client creation API, however that is not the case at present.
