### ISSUE TITLE
how to error on initial AdminClient connection if broker is unavailable

### ISSUE THREAD

**Issue by jdye64** [confluentinc/confluent-kafka-python#923]
Description
===========
To keep things simple lets say I have a Kafka cluster that consists of a single broker. What I would like to be able to do is attempt to make a connection to that broker using AdminClient. If the connection does not succeed in 10 seconds I would like to throw an exception.

I feel like there must be a configuration from [here](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) that I am overlooking. It seems like `socket.timeout.ms` would be what I want but that doesn't seem to be honored?

Any advice on how to achieve this?

python-confluent-kafka version: 1.3.0
librdkafka version: 1.4.2
Apache Broker version: 1.4.0
OS: Ubuntu 18

How to reproduce
================
from confluent_kafka.admin import AdminClient

kafka_configs = {
        "metadata.broker.list": "localhost:9092",
        "group.id": "groupid",
        "socket.timeout.ms": 10000
    }

# hangs indefinitely
a = AdminClient(kafka_configs)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
first, have a read of this: https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down

with that said, perhaps you will find constructing a consumer then using list_topics with a timeout of 10s useful.

there are some inadequacies in the API related to this IMO, and some improvements are under discussion / consideration.

**Comment by jdye64** [comment]
@mhowlett thanks for the response. My intention was to use this outside of the normal operation. The idea was to use this in my pytest to determine if a Kafka cluster is actually in that environment. If so run those pytests if not skip them all. I have a rudimentary approach using `socket` which does work but I wanted something more elegant.

**Comment by mhowlett** [comment]
thanks for the context - sounds good. just trying to connect to the bootstrap server address outside the client and checking for success/failure actually sounds like a pretty good solution to me.
