### ISSUE TITLE
Java Python Protobuf MessageIndex Mismatch

### ISSUE THREAD

**Issue by efaurie** [confluentinc/confluent-kafka-python#926]
Description
===========

I know the Protobuf Registry isn't fully supported here and the Python decoder ignores the indices following the schema-id for now but this seems like something that may bite someone in the future. There's a discrepancy between Java and Python Protobuf MessageIndex generation.

Java encodes and decodes Protobuf MessageIndexes as (Zig-Zag encoded) VarInts where Python treats them strictly as UVarInts which causes mismatches.

Java Implementation:
[MesageIndex Encoding](https://github.com/confluentinc/schema-registry/blob/1b19d5e35b9bb6272ddad1f95a5effe479de3a9b/protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/MessageIndexes.java#L57)
[Varint Encoding](https://github.com/confluentinc/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/utils/ByteUtils.java#L189)

Python Implementation:
[MessageIndex Decoding](https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/schema_registry/protobuf.py#L413)
[UVarInt Decoding](https://github.com/confluentinc/confluent-kafka-python/blob/5aa6439df081ead048932ee395085236ef0bca9d/confluent_kafka/schema_registry/protobuf.py#L357)

How to reproduce
================

Not entirely reproducible with the python protobuf decoder as-is. But publishing protobuf records of the second message defined inside of a multi-message .proto file from Java/Scala will result in a header like:

00 00 00 00 01 02 02 <serialized-payload>  
That is: 0-magic, schema-id 1, varint-index-size 1, varint-index 1

Where python will then decode this header as: 0-magic, schema-id 1, uvarint-index-size 2, uvarint-index 2, ???

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by cemeyer2** [comment]
i am running into this as well. worked around it with custom python serdes, but the issue in the OSS libraries still exists

**Comment by cemeyer2** [comment]
can this be closed given what was released in 1.8.2?

**Comment by jliunyu** [comment]
Close this one due it's released in v1.8.2: https://github.com/confluentinc/confluent-kafka-python/pull/1256/files
