### ISSUE TITLE
got undefined symbol: : rd_kafka_consumer_group_metadata_write error

### ISSUE THREAD

**Issue by lcalviny** [confluentinc/confluent-kafka-python#928]
Description
===========
from confluent_kafka.avro import AvroProducer gets ImportError: python3.7/site-packages/confluent_kafka/cimpl.cpython-37m-x86_64-linux-gnu.so: undefined symbol: rd_kafka_consumer_group_metadata_write

How to reproduce
================
1, sudo yum install librdkafka-devel python-devel
2, pip install confluent-kafka
3, ln -s /usr/lib64/librdkafka-cedc1a93.so.1 python3.7/site-packages/confluent_kafka.libs/librdkafka.so.1

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your yum-installed librdkafka is outdated, and replacing the bundled librdkafka is not supported.
Either use the bundled librdkafka (through the wheels) or provide your own librdkafka (e.g. through yum) and then build confluent-kafka-python from source.

**Comment by prashantochatterjee** [comment]
Hi @edenhill . I ran into the same issue. 

I followed these steps to have librdkafka available with SASL authentication:

> - Download librdkafka source
> `$ git clone https://github.com/edenhill/librdkafka.git`
> 
> - Install prerequisite libraries
> `$ sudo apt-get install libssl-dev libsasl2-dev`
> 
> - Build and install librdkafka from source
> `Refer: https://github.com/edenhill/librdkafka/blob/master/README.md`
> 
> 
> - Install confluent-kafka from source
> `$ pip install --no-binary :all: confluent-kafka`
> Refer: https://github.com/confluentinc/confluent-kafka-python/blob/master/README.md

When I try to import the Consumer I get the following error:
```
$ python
Python 3.7.4 (default, Dec 17 2021, 20:49:59) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from confluent_kafka import Consumer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prashanto/PYTHON37/lib/python3.7/site-packages/confluent_kafka/__init__.py", line 19, in <module>
    from .deserializing_consumer import DeserializingConsumer
  File "/home/prashanto/PYTHON37/lib/python3.7/site-packages/confluent_kafka/deserializing_consumer.py", line 19, in <module>
    from confluent_kafka.cimpl import Consumer as _ConsumerImpl
ImportError: /home/prashanto/PYTHON37/lib/python3.7/site-packages/confluent_kafka/cimpl.cpython-37m-x86_64-linux-gnu.so: undefined symbol: rd_kafka_consumer_group_metadata_write
```

Any pointers will be sincerely appreciated.

**Comment by edenhill** [comment]
Remove any system installed librdkafka packages (e,g, `sudo apt purge librdkafka1 librdkafka-dev`)

**Comment by prashantochatterjee** [comment]
Worked. I had removed `librdkafka-dev` but not `librdkafka1`. Thanks once again for your pointer.
