### ISSUE TITLE
Avro Producer get error only when string field in scheme

### ISSUE THREAD

**Issue by danielman111** [confluentinc/confluent-kafka-python#932]
Description
===========
I have the following code that tries to produce data via avro producer to kafka.
I am getting the following error: (only when having string field in my scheme)

```
avro.io.AvroTypeException: The datum {'first': 'asd'} is not an example of the schema {
  "namespace": "com.example", 
  "type": "record", 
  "name": "FullName", 
  "fields": [
    {
      "type": "string", 
      "name": "first"
    }
  ]
}

```

I am using python 2.7.

This is my code

```
def main():

    subject = 'testAvroString-value'
    sr = CachedSchemaRegistryClient('http://localhost:5081')
    (schema_id, schema, version) = sr.get_latest_schema(subject)

    value_schema = avro.loads(str(schema))
    value = {'first': 'asd'}


    avroProducer = AvroProducer({
        'bootstrap.servers': 'localhost:9092',
        'on_delivery': delivery_report,
        'schema.registry.url': 'http://localhost:5081'
    }, default_value_schema=value_schema)


    topics = avroProducer.list_topics()
    avroProducer.produce(topic='testAvroString', value=value)
    avroProducer.flush()
```

When using other types as boolean or int, it works fine.
Any ideas why this is happening?

**Comment by mhowlett** [comment]
from the error, it looks like the problem is with the connection to schema registry.

try using the `sr` instance to interact with schema registry outside the context of the produce request (I'm guessing it won't work).

**Comment by sangmeshcp** [comment]
having the same issue .. 
lib/python3.6/site-packages/avro/io.py", line 809, in write
raise AvroTypeException(self.writer_schema, datum)
avro.io.AvroTypeException: The datum {"test_name": "work"} is not an example of the schema {
"type": "record",
"name": "TEST",
"namespace": "test1",
"fields": [
{
"type": "string",
"name": "test_name"
}
]
}

and schema registry seems to be working fine
