### ISSUE TITLE
Asynchronous commit: which messages are committed?

### ISSUE THREAD

**Issue by fcracker79** [confluentinc/confluent-kafka-python#933]
Description
===========
Given a consumer with manual commit configured, the `commit(asynchronous=True)` invocation commits all the messages that are fetched at the real commit time, not all the messages that are fetched before the `commit` function invocation.
Is this a normal behavior? What is the rationale behind an asynchronous commit that commits messages unpredictably?

How to reproduce
================
This code causes the consumer to be at offset 1
```python
consumer = Consumer(
            {
                'bootstrap.servers': ','.join(bootstrap_servers),
                'group.id': consumer_group,
                'auto.offset.reset': 'earliest',
                'session.timeout.ms': 50000,
                'enable.auto.commit': False,
                'fetch.message.max.bytes': _MAX_MESSAGE_SIZE,
                "debug": "consumer"
            }
        )
consumer.subscribe([topic_name])
msgs = consumer.poll(timeout=5000)
print(msgs)
consumer.commit(asynchronous=False)
consumer.poll(timeout=5000)
```

This code causes the consumer to be at offset 2
```python
consumer = Consumer(
            {
                'bootstrap.servers': ','.join(bootstrap_servers),
                'group.id': consumer_group,
                'auto.offset.reset': 'earliest',
                # 'auto.offset.reset': 'latest',
                'session.timeout.ms': 50000,
                'enable.auto.commit': False,
                'fetch.message.max.bytes': _MAX_MESSAGE_SIZE,
                "debug": "consumer"
            }
        )
consumer.subscribe([topic_name])
msgs = consumer.poll(timeout=5000)
print(msgs)
consumer.commit()  # by default, asynchronous=True
consumer.poll(timeout=5000)
```

This code causes the consumer to be at offset 1
```python
consumer = Consumer(
            {
                'bootstrap.servers': ','.join(bootstrap_servers),
                'group.id': consumer_group,
                'auto.offset.reset': 'earliest',
                # 'auto.offset.reset': 'latest',
                'session.timeout.ms': 50000,
                'enable.auto.commit': False,
                'fetch.message.max.bytes': _MAX_MESSAGE_SIZE,
                "debug": "consumer"
            }
        )
consumer.subscribe([topic_name])
msgs = consumer.poll(timeout=5000)
print(msgs)
consumer.commit()  # by default, asynchronous=True
time.sleep(3000)
consumer.poll(timeout=5000)
```

Checklist
=========
>>> confluent_kafka.version()
('1.4.2', 17039872)
>>> confluent_kafka.libversion()
('1.4.2', 17040127)

Kafka broker 2.12
Please see the attached source code for client configuration.
Ubuntu 18.0
[log_sync.txt](https://github.com/confluentinc/confluent-kafka-python/files/5064057/log_sync.txt)
[logs_async.txt](https://github.com/confluentinc/confluent-kafka-python/files/5064061/logs_async.txt)

**Comment by edenhill** [comment]
commit() will commit the offsets of the last message passed from poll() to the application (for each assigned partition).

**Comment by fcracker79** [comment]
Thanks for your response @edenhill .
Your response does not clarify the two different behaviours though.

**Comment by mhowlett** [comment]
by "cause the consumer to be at offset", you mean the result of a call to `position()`, or the committed offset?
the committed offset should be the same.
