### ISSUE TITLE
how to get offset by timestamp?

### ISSUE THREAD

**Issue by Fanduzi** [confluentinc/confluent-kafka-python#934]
Description
===========
Did not understand the purpose of offsets_for_times,
I want to get the offset through timestamp and then consume. This method has no parameters to receive the timestamp? Does confluent kafka python support getting the offset through the given timestamp?

**Comment by edenhill** [comment]
You specify the timestamp (milliseconds since the epoch) as the `offset` field on each partition.
Example:
https://github.com/confluentinc/confluent-kafka-python/blob/master/tests/integration/integration_test.py#L472
