### ISSUE TITLE
Bug: Future in AdminClient is set before the topic is created

### ISSUE THREAD

**Issue by gshaikov** [confluentinc/confluent-kafka-python#937]
Description
===========
`AdminClient.create_topics` returns a map of Futures, each is supposed to block until an underlying topic gets created.
However, the Futures are set to None before the topics are created.

The method in question:
https://github.com/confluentinc/confluent-kafka-python/blob/5aa6439df081ead048932ee395085236ef0bca9d/confluent_kafka/admin/__init__.py#L292

How to reproduce
================
`confluent-kafka-python==1.5.0`
`librdkafka==1.5.0`
A cluster with broker `confluentinc/cp-server:5.4.0` running locally

This script illustrates the problem. The gist: after Future is set, the topic is still not in the list retrieved by Consumer.
```
from uuid import uuid4
from time import sleep

from confluent_kafka.avro import Consumer
from confluent_kafka.admin import AdminClient, NewTopic


def topic_exists(topic_name: str) -> bool:
    """
    Return True if topic with topic_name exists; False otherwise
    """
    consumer_config = {
        "bootstrap.servers": "localhost:9092",
        "group.id": "topic_exists_checker",
    }
    con = Consumer(consumer_config)
    cluster_metadata = con.list_topics()
    con.close()
    return topic_name in cluster_metadata.topics


def create_new_topic(topic_name: str) -> None:
    """
    Create a topic with topic_name.
    """
    admin_client = AdminClient({"bootstrap.servers": "localhost:9092"})
    new_topic = NewTopic(topic_name, num_partitions=1, replication_factor=1)
    futures_map = admin_client.create_topics([new_topic])
    for topic, future in futures_map.items():
        future.result()  # <---- supposed to block until the topic is actually created; doesn't block though


if __name__ == "__main__":
    topic_name = str(uuid4())

    assert topic_exists(topic_name) is False

    create_new_topic(topic_name)

    # sleep(1)  # <---- without sleeping for 1 second, the line below fails; uncommenting this line makes the assert pass

    assert topic_exists(topic_name) is True

```

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [X] Apache Kafka broker version:
 - [X] Client configuration: `{...}`
 - [X] Operating system: MacOS 10.15.5
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the future completes on receiving a response to the create topics call from the controller. however, it takes some time for the topic metadata to propagate after the broker sends the response, so the `list_topics` immediately following the create topics call may not include the new topic.

this is a known broker side usability issue (I think not addressed yet, but I may be wrong).

**Comment by gshaikov** [comment]
Thanks for the quick response! Which way of checking for a topic to exist would you recommend then? Is there something blocking until the topic is available? I didn't find a better candidate than `list_topics` in the repo.

**Comment by mhowlett** [comment]
i think `list_topics` is as good as it gets.

**Comment by gshaikov** [comment]
Ok thanks, closing then
