### ISSUE TITLE
on_revoke as coroutine instead of callable

### ISSUE THREAD

**Issue by victorcadena** [confluentinc/confluent-kafka-python#939]
Description
===========
Right now I have an application that takes messages from Kafka and what I do is add a task to Asyncio per message received so all the incoming messages are processed concurrently. My issue is that I want to flush an in-memory queue when an `on_revoke` event happens but this flushing function is an `async def flush_queue()` sort of function and I cannot just add it as a callable (because it is a coroutine and needs an `await`) when my consumer gets some partitions revoked. How do I handle this case?. Also when a consumer joining gets new partitions assigned I would like to call an `await asyncio.sleep(x_seconds)`, but again, this can only happen in a coroutine. Any ideas?

**Comment by mhowlett** [comment]
i'm pretty confident this isn't possible - you'll need to make the calls blocking. the rebalance callbacks occur as a side effect of the consumer poll call, and this is arranged inside librdkafka - there's no (current) way for the python layer to know what it needs to know to make the async stuff work as far as i understand it.

**Comment by victorcadena** [comment]
Thanks for the reply. Will close the issue @mhowlett
