### ISSUE TITLE
avro extras not on pypi

### ISSUE THREAD

**Issue by andrewjshults** [confluentinc/confluent-kafka-python#94]
Hey folks,

I was able to install the base package fine, but when I tried to install the avro extras, I got this error.
```
pip install confluent-kafka[avro]
confluent-kafka 0.9.2 does not provide the extra 'avro'
```

Also downloaded the tarball from pypi directly and it appears to be missing the avro package. Installed from source locally, but would like to be able to grab it from a pypi mirror for our build system.

**Comment by ewencp** [comment]
@andrewjshults Glad you're interested in the Avro support! However, it has only recently been merged, so it isn't in a release yet. It landed after the 0.9.2 release, so it's expected that you wouldn't be able to install it via PyPI yet.

We'll have to wait until the next release to make it available from PyPI, but the alternative for the moment would be to use a reference to a specific git commit [as described in the pip VCS docs](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support).

We can also potentially think about an intermediate release just so these features (and other bug fixes) become available sooner. I think the primary overhead would be running the release through the Kafka system test gauntlet that validates lots of functionality. At the moment that's a manual process (something @edenhill is anxious to automate).

**Comment by andrewjshults** [comment]
Make sense - we'll probably build for our internal mirror in the meantime. It is a bit confusing that the documentation says you can install via pip, but that doesn't work. Happy to open a PR with a clarifying comment if you think that would be useful.

**Comment by ewencp** [comment]
@andrewjshults Fair enough, this is what happens when `master` is your default branch on GitHub :)
