### ISSUE TITLE
Question: Cannot catch KafkaException when Kafka broker not available

### ISSUE THREAD

**Issue by DonIvanCorleone** [confluentinc/confluent-kafka-python#941]
Description
===========
Hi there,

first of all! Thank you very much for providing such a good product!

Unfortunately, I came across something I cannot solve on my own. I have create a simple test below. 
I try to connect to some kafka-broker which is not running/available. When I run the script below, I get the following librdkafka error message `%3|1598533906.989|FAIL|rdkafka#consumer-1| [thrd:172.17.0.1:9092/bootstrap]: 172.17.0.1:9092/bootstrap: Connect to ipv4#172.17.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)` but I am not able to catch the KafkaException although the documentation says (https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.subscribe) that it will raise a KafkaException or a RuntimeError depending on the type of the error. Unfortunately, I cannot catch any of them...

Can one of you shed some light what I am doing wrong?
Thanks a lot! 
Looking forward to your suggestions :)

How to reproduce
================

```
from  confluent_kafka import Consumer, KafkaException 
config = {
            "bootstrap.servers": "127.0.0.1:9092",
            "group.id": "test",
            "auto.offset.reset": "earliest",

        }
consumer = Consumer(config)
try:
    consumer.subscribe(['myTopic'])
except KafkaException as e:
    print("ERROR")
consumer.close()

```

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka ('1.5.0', 17104896) , libversion ('1.5.0', 17105151)
 - [X] Apache Kafka broker version: N/A
 - [X] Client configuration: see above example 
 - [X] Operating system: Docker-Ubuntu
 - [X] Provide client logs (with `'debug': '..'` as necessary): Not needed
 - [X] Provide broker log excerpts: Not needed
 - [X] Critical issue: n/a

**Comment by jayesh6297** [comment]
## check your local ip
as seen you may be trying to connect different ip than 127.0.0.1 if your ip is correct then 
## set producer config for ip
the problem with librdfkafka is when you're running it on unix like system then it resolve both ipv4 and ipv6 entries on /etc/hosts and the round robin fashion attempt to connect all address that host resolve to so possible solution is you can limit the address family whichare trying to connect to..
set `broker.address.family` to `v4` in producer config.
i think that will help

**Comment by DonIvanCorleone** [comment]
Hi @jayesh6297 ,

thanks for your suggestion but the IP address could be anything in my use case. I want to **intentionally do not provide a valid IP address** to a running Kafka broker. In such a case I would like to catch an error, which says `KafkaException` or `RuntimeError`
Somehow this is not working properly for me... 
Any suggestions?

Cheers

**Comment by jayesh6297** [comment]
you can catch kafka_exception in try except block... try importing kafkaException and print the msg associated with it.

**Comment by DonIvanCorleone** [comment]
Hi @jayesh6297 ,

I agree it **shoud**  be possible, but somehow it was not that obvious and I am not sure if this is the intended way.
In my current solution / workaround I am actively trying to list all available topics on the **not existing** Kafka Broker. The moment the timeout hits an exception is thrown. Feels cumbersome to be honest but it works now :)

```python
try:
   available_topics = self.consumer.list_topics(timeout=5)
   logger.debug("Currently we have those topics {} availalbe".format(available_topics.topics))
except KafkaException:
   logger.critical("We cannot connect to the specified notificaiton topic {}.".format(topic))
   logger.critical("Shutting down the process")
``` 

Thanks for your suggestions and support.

Closing this one.
Cheers

**Comment by abhinandanshresthawiseyak** [comment]
Hello @DonIvanCorleone
have you resolved this issue?
