### ISSUE TITLE
Unsure how consumer offsets are handled in transactions

### ISSUE THREAD

**Issue by lowjiajin** [confluentinc/confluent-kafka-python#943]
Description
===========
In [another issue](https://github.com/confluentinc/confluent-kafka-python/issues/580), @edenhill offered the following pattern for batch consumption, assuming that `enable.auto.commit` is True, and `enable.auto.offset.store` is False:
```
producer.begin_transaction()

max_time = time.now() + max_total_processing_time
while time.now() < max_time:
  msg = consumer.poll()
  outmsg = process(msg)
  producer.produce(outmsg)

producer.send_offsets_to_transaction(...)
producer.commit_transaction()
```
Assuming we are using transactions because we want to achieve exactly-once semantics, I'm not sure how the consumer offsets are handled here. In particular, I would have expected `consumer.store_offsets()` to be called, but it never is. How can we ensure that the consumer offsets are committed iff `producer.commit_transaction()` succeeds?

**Comment by lowjiajin** [comment]
### Update

I just found this [Confluent blog post](https://www.confluent.io/blog/simplified-robust-exactly-one-semantics-in-kafka-2-5/) describing how to achieve exactly-once semantics, where they provided the following snippet:
```
producer.initTransactions();

consumer.subscribe(singletonList(“inputTopic”));

while (true) {
  ConsumerRecords consumed = consumer.poll(Duration.ofMillis(5000));
  Map<TopicPartition, OffsetAndMetadata> consumedOffsets = offsets(consumed);
 
  List processed = process(consumed);
    
  try {
    producer.beginTransaction();
    for (ProducerRecord record : processed)
      producer.send(record);    
    **producer.sendOffsetsToTransaction(consumedOffsets, consumer.groupMetadata());**

    producer.commitTransaction();
  } catch(ProducerFencedException e) {
    producer.close();
  } catch(KafkaException e) {
    producer.abortTransaction();
    **resetToLastCommittedPositions(consumer);**
  }
}
}
```

This partially solved one of my questions, which was that the consumer's offsets are fed into `send_offsets_to_transaction(...)` as the `...` (apologies, should have read the documentation more closely). 

But I also noticed a second method, `resetToLastCommittedPositions(consumer)`, which doesn't seem to have a Python equivalent in the first snippet. How is the resetting of the consumer offset handled if the commit fails?

**Comment by edenhill** [comment]
@lowjiajin resetToLastCommittedPositions() is something the application will have to provide, typically it is something like this:
```python
def resetToLastCommittedPositions(consumer):
    offsets = consumer.committed(consumer.assigned())
    for part in offsets:
       consumer.seek(part)
```

**Comment by lowjiajin** [comment]
Ah I see. Thanks @edenhill!

**Comment by chweeee** [comment]
Hi @edenhill , I'm just wondering about the behaviour of `producer.commitTransaction()`.
Suppose that `producer.commitTransaction()` errors out halfway while commiting all the messages of a transaction and returns an abortable error, does that mean the offset gets advanced according to the number of successful messages?

E.g. transaction consists of 10 messages, and errors out at message 6. Does that mean that the offset would be advanced by 5?
