### ISSUE TITLE
Error creating SSL Consumer with Kerberos encryption  

### ISSUE THREAD

**Issue by AdrianaTheo** [confluentinc/confluent-kafka-python#944]
Hello,

I am trying to create a Consumer with SSL protocol but I am getting this error.

**KafkaError{code=_INVALID_ARG,val=-186,str="Java TrustStores are not supported, use `ssl.ca.location` and a certificate file instead. See https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka for more information."}**

I tried some solutions as bellow but nothing,

- if I change the line **ssl.truststore.location** to **ssl.ca.location** is fine, but then produces another error in the line **ssl.truststore.password** 
KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "ssl.truststore.password""} 
and if i change it as well the line **ssl.truststore.password** to **ssl.ca.password** it throws the error that this property dosen't exist.

- Another approach was to change **ssl.truststore.location**, **ssl.truststore.password** to **ssl.key.location, ssl.key.password** accordingly and was working fine, but I don't know if it's correct method because inside of the documentation [consumer config parameters](https://docs.confluent.io/current/installation/configuration/consumer-configs.html#ssl.truststore.location) there is such a config parameters (ssl.truststore.location/password).

and one last thing I don't have any clue about this line **java.security.krb5.conf** it doesn't support at all .

Thank you in advance

How to reproduce
================
Create a simple consumer using this to initiate :
c = Consumer({
"bootstrap.servers":	                             "10.34.12.78:2091,10.32.31.78:9011,12.34.37.79:1111",
"security.protocol":	                             "SASL_SSL",
"sasl.kerberos.service.name":               "kafka",
"sasl.mechanism":                                "GSSAPI",
"ssl.truststore.location":                       "./kafka.client.truststore.jks",
"ssl.truststore.password":                     "pass",
"java.security.krb5.conf":                      "./krb5.conf",
"user":                                                   "user",
"group.id":                                            "userid",
"java.security.auth.login.config":           "./kafka_user_jaas.properties"

Checklist
=========
Please provide the following information:
 - [x] confluent-kafka-python version (1.4.2):

**Comment by edenhill** [comment]
Java KeyStores (JKS) and JAAS are Java-specific things and will not work with non-Java clients, instead use ssl.ca.location (to verify the broker's cert), ssl.key.location (the client's private key, if any), ssl.certificate.location (the client's public key, if any) and ssl.key.password (if any).
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by edenhill** [comment]
As for the JAAS Kerberos config you'll need to translate that into keytabs, see https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka and other Kerberos resources.
