### ISSUE TITLE
Latency of the list_topics() metadata API

### ISSUE THREAD

**Issue by chinmaychandak** [confluentinc/confluent-kafka-python#949]
How expensive is the list_topics() API to get the metadata for a single topic? 

The use case I am dealing with is as follows:

I have a streaming pipeline which polls Kafka periodically and then reads the new messages as a batch. Currently, this supports only static number of partitions. I would like to add a feature where increasing the number of partitions is handled by the stream — for this, I was planning to call `list_topics()` to get the latest number of partitions every time I poll the Kafka topic. 

Is this going to be really expensive? I was thinking that a metadata object for a single topic would typically be smaller than a single actual message being read in a batch, so calling `list_topics()` should be okay.

**Comment by edenhill** [comment]
list_topics() sends a MetadataRequest to the broker and waits for a response, so this is relatively speaking a costly operation that you really shouldn't do each time you receive a message.
My recommendation would be to not call this API more than once very second or so.

**Comment by chinmaychandak** [comment]
Thanks for the quick response, @edenhill. 

> shouldn't do each time you receive a message.

Agree, although I would be calling this API every time before I poll _a batch of messages_, which would be once every 10s-60s (this is the poll interval). Maybe I'm better of calling this API every N cycles then?
