### ISSUE TITLE
there is no consumer.seek() function like java client

### ISSUE THREAD

**Issue by zhangmoon** [confluentinc/confluent-kafka-python#95]
there is no consumer.seek() function like java client

**Comment by edenhill** [comment]
That's right, but depending on your use-case you might get around it.

If you dont want to actively seek, skip and jump in your partition, but only set the starting offset, the existing assign() method allows you to do that by setting the `TopicPartition.offset` field to your starting offset.
It can either be an absolute offset (>=0) or one of the logical ones (there will be proper constants for these later):
 * -1 : latest offset
 * -2 : oldest offset
 * -1001 : default/stored offset

Is this sufficient for your needs?

**Comment by zhangmoon** [comment]
I want to store consumer offset in mysql, so i need to seek offset in consumer's on_assign callback function.

**Comment by zhangmoon** [comment]
if i use assign at the start,so the kafka can't rebalance kafka consumers automatically, right?

**Comment by edenhill** [comment]
This is exactly the use-case I'm talking about.
In your on_assign callback you extract the start offset(s) from mysql, update the partition list with the new offset for each partition, and then call assign() with the updated partition list.

**Comment by zhangmoon** [comment]
it works, thank you
