### ISSUE TITLE
SchemaRegistryClient.get_compatibility returns the incorrect value

### ISSUE THREAD

**Issue by choogeboom** [confluentinc/confluent-kafka-python#951]
https://github.com/confluentinc/confluent-kafka-python/blob/77681916850ec5902dd0b9f270f8274d73d81b25/confluent_kafka/schema_registry/schema_registry_client.py#L621

The docs say that the return type is supposed to be a `str`, but instead the full json blob is returned ([API Docs](https://docs.confluent.io/current/schema-registry/develop/api.html#post--compatibility-subjects-(string-%20subject)-versions-(versionId-%20version))). This is easily fixed in the following way

```python
...
result = self._rest_client.get(url)
return result['compatibilityLevel']
```

**Comment by mhowlett** [comment]
i agree with you (in the .net client i did as both you and the docstring suggest). i'd argue this isn't a breaking change since the docs already state what you're changing it to.

thanks!
