### ISSUE TITLE
Create a test_compatibility method for SchemaRegistryClient

### ISSUE THREAD

**Issue by choogeboom** [confluentinc/confluent-kafka-python#955]
Description
===========
The Schema Registry API has an [endpoint for testing compatibility](https://docs.confluent.io/current/schema-registry/develop/api.html#post--compatibility-subjects-(string-%20subject)-versions-(versionId-%20version)), but `SchemaRegistryClient` does not currently have a method that supports this operation. It would be nice to have and useful for me.

Checklist
=========
Please provide the following information:

confluent-kafka-python: v1.5.0

**Comment by mhowlett** [comment]
it looks like this was implemented in the old SR client, but is not in the new: https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/cached_schema_registry_client.py#L391

it would be good to add this, yes.
