### ISSUE TITLE
No such configuration property: "key.serializer"

### ISSUE THREAD

**Issue by Chloejay** [confluentinc/confluent-kafka-python#961]
Description
===========
I'm trying to add more config parameters `key.serializer` and `value.serializer` on my Kafka Producer, returned error 
`cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "key.serializer""}`

I'm using
```
librdkafka >= 1.4.0
confluent-kafka ==1.2.0
Kafka broker==5.3.0
```

How to reproduce
================
```
config= {
'bootstrap.servers': BROKER,
"client.id":"driver.producer",
"key.serializer": "",
"value.serializer":"",
'plugin.library.paths': 'monitoring-interceptor',
'partitioner': 'murmur2_random'}
```

Checklist
=========
Please provide the following information:

 - [ x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ x] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jayesh6297** [comment]
you have to use SerializeProducer class to add key and value serialize configs

**Comment by Chloejay** [comment]
Thank you, I have realized this when checked the doc, though Java API supports call key.serializer directly.
