### ISSUE TITLE
Test suite fails locally and on travis-ci

### ISSUE THREAD

**Issue by gridaphobe** [confluentinc/confluent-kafka-python#962]
Description
===========

I've been having an embarrassingly hard time getting the testsuite to run on my mac and linux machines. The unit tests fail for various reasons, but most commonly due to `ModuleNotFoundError: No module named 'confluent_kafka.cimpl'`. I believe the issue is that `tox` is installing `confluent_kafka` into the local python environment, but the project root still contains a `confluent_kafka` directory that takes precedence in import resolution. This directory is just the python source, so it won't contain the native `cimpl` module.

I spent a good while yesterday trying various hacks and scripts in `tools` and `tests` to no avail. I also tried to reproduce the `.travis.yml` instructions, only to discover that they fail similarly, even on [travis](https://travis-ci.org/github/confluentinc/confluent-kafka-python/jobs/725589553#L1155-L1179), but the errors are swallowed by the test script.

How to reproduce
================

```
$ tox -e py36
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
(Looong delay here)

We recently rearranged the directory structure to avoid dir-local tests to pick up the confluent_module from the source tree rather than what is installed through pip/setup.py, and this supposedly fixes this issue.
