### ISSUE TITLE
Confluent kafka does not support python 3.9

### ISSUE THREAD

**Issue by MikkelHJuul** [confluentinc/confluent-kafka-python#968]
Description
===========
confluent kafka cannot be installed into docker image python:3.9-slim-buster (the problem is probably more widespread than that)
works:
```
FROM python:3.8-slim-buster

RUN pip install confluent_kafka
```
does not work
```
FROM python:3.9-slim-buster

RUN pip install confluent_kafka
```
throws errors on missing gcc
when after installing gcc, it throws errors on librdkafka, then after installing that you try installing confluent_platform, and it still doesn't work.

How to reproduce
================
Dockerfile
```Dockerfile
FROM python:3.8-slim-buster

RUN pip install confluent_kafka

FROM python:3.9-slim-buster

RUN pip install confluent_kafka
```
>/ docker build .

I have tried installing `gcc`, `librdkafka-dev` and `confluent_platform` current versions as I write (in docker image using `apt`)
Attachment: log output of stated dockerfile run with gcr.io/kaniko using a gitlab-runner

At least there should be some kind of note of this limitation in install descriptions, until it is fixed. 

[error.log](https://github.com/confluentinc/confluent-kafka-python/files/5377152/error.log)

**Comment by dangreenisrael** [comment]
This happened to me. I'm putting this here in care others are googling for a similar error:

```
 #include <librdkafka/rdkafka.h>
 ^~~~~~~~~~~~~~~~~~~~~~
 compilation terminated.
 error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by dangreenisrael** [comment]
If you need a quick fix to get yourself unblocked for on 3.9, you could build the binaries from source. 

The following works:

```dockerfile
# Install librdkafka from source
RUN git clone https://github.com/edenhill/librdkafka
WORKDIR /app/librdkafka/
RUN ./configure
RUN make
RUN make install
RUN ldconfig
WORKDIR /app
```

**Comment by dangreenisrael** [comment]
@edenhill 

https://github.com/confluentinc/confluent-kafka-python/pull/987

**Comment by olasd** [comment]
As far as I can tell and I've tested locally, confluent-kafka-python works fine with Python 3.9. You just need a recent enough version of librdkafka. However, the version of librdkafka-dev **packaged in Debian buster** (which is what you've seemingly tried to installed in the docker python3.9 image) is much too old for confluent-kafka-python 1.5.0.

In light of this I don't think #987 should be merged.

I suspect @edenhill  could just run cibuildwheel again on the 1.5.0 release, which would build it against 3.9 on all platforms directly. Or just tag a "noop" 1.5.1 release to get a new set of clean binary builds.

**Comment by dangreenisrael** [comment]
It works fine if you have `librdkafka` installed on your host. But for versions before 3.9 you don't need to.  Also, I spoke to someone at Confluent who acknowledged that this was a bug.

**Comment by edenhill** [comment]
Py 3.9 packages coming
