### ISSUE TITLE
Consumer Offsets

### ISSUE THREAD

**Issue by 2020testuser** [confluentinc/confluent-kafka-python#971]
Description
===========
Hi,
Could anyone please help me?
Some of the offsets are not committed during message processing when suddenly the consumer goes down. When I restart the consumer, I want it to read only the missed offsets . Is there any way to read only the missed offsets?
When I have enable_auto_commit = false and auto_offset_reset='earliest', on consumer restart, I see both missed offsets and new offsets being read. I want the consumer only to read the missed offsets.

Thanks !

How to reproduce
================
1. Start Producer program and send messages to a topic

2. Start Consumer Program with enable_auto_commit = false and auto_offset_reset='earliest', .Consume the messages and commit by calling close.

3. While step 2 is happening, shut down consumer. 

4. Start Consumer. Consumer should read only the missed offsets. Since, I have  auto_offset_reset='earliest', it reads the missed the new offsets.

Checklist
=========
Please provide the following information:

- Latest version of confluent-kafka-python

**Comment by edenhill** [comment]
Enable auto commit must be true, or you need to commit manually.
