### ISSUE TITLE
Official 1.5.2 release on PyPI

### ISSUE THREAD

**Issue by amotl** [confluentinc/confluent-kafka-python#973]
Dear Magnus,

thanks again for appreciating my comments at https://github.com/edenhill/librdkafka/issues/3109 the other day. I see that you are currently busy preparing a 1.5.2 release within [tree/v1.5.2rc1](https://github.com/confluentinc/confluent-kafka-python/tree/v1.5.2rc1) and [tree/v1.5.2rc1b](https://github.com/confluentinc/confluent-kafka-python/tree/v1.5.2rc1b), right?

I just wanted to take the chance to humbly ask if we can expect a new release on https://pypi.org/project/confluent-kafka/ soon, which will include all the important improvements you have been bringing to librdkafka in the recent ~weeks~ months?

Good luck with all the nitty gritty details, keep up the spirit and with kind regards,
Andreas.

**Comment by dimon222** [comment]
Any update on this? librdkafka 1.5.3 is already out there, and we're still on 1.5.0

**Comment by amotl** [comment]
[librdkafka](https://github.com/edenhill/librdkafka) is actually approaching version 1.6.0, see [tree/v1.6.0-PRE4](https://github.com/edenhill/librdkafka/tree/v1.6.0-PRE4). So, I believe this might be the next version we can expect here. Resources are scarce.

**Comment by edenhill** [comment]
The chaotic Python2 situation messed up our packaging, but that's solved now. v1.6.0 will be released shortly.
