### ISSUE TITLE
Authorization with key tab fail with "No provider for SASL mechanism GSSAPI" error in python virtual environment

### ISSUE THREAD

**Issue by ThejYapa** [confluentinc/confluent-kafka-python#976]
Description
===========
Consumer authorization fails with the following error: 
consumer = Consumer(conf)
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create consumer: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM OAUTHBEARER"}

How to reproduce
================
Deployed in a **python-virtual environment :Python 3.6.8**

from confluent_kafka import Consumer
conf ={'bootstrap.servers':"server1:9092,server2:9092",
        "enable.auto.commit": "false",
        "session.timeout.ms": "30000",
        "group.id": "kafka_admin",
        "security.protocol": "SASL_PLAINTEXT",
        'auto.offset.reset': 'latest',
        'sasl.mechanisms': 'GSSAPI',
        'sasl.kerberos.service.name': 'kafka',
        'sasl.kerberos.keytab': '/data/keytabs/myadmin.keytab',
        'sasl.kerberos.principal':"myadmin@DOMAIN.COM"}
consumer = Consumer(conf)
print ("success.")

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version:
confluent-kafka 1.5.0
librdkafka1.x86_64            1.5.0_confluent6.0.0-1.el7  @Confluent.dist
librdkafka-devel.x86_64    1.5.0_confluent6.0.0-1.el7  @Confluent.dist 
 - [x] Apache Kafka broker version: kafka_2.13-2.6.0
 - [x] Client configuration: `{'bootstrap.servers':"server1:9092,server2:9092",
        "enable.auto.commit": "false",
        "session.timeout.ms": "30000",
        "group.id": "kafka_admin",
        "security.protocol": "SASL_PLAINTEXT",
        'auto.offset.reset': 'latest',
        'sasl.mechanisms': 'GSSAPI',
        'sasl.kerberos.service.name': 'kafka',
        'sasl.kerberos.keytab': '/data/keytabs/myadmin.keytab',
        'sasl.kerberos.principal':"myadmin@DOMAIN.COM"}`
 - [x] Operating system:"Red Hat Enterprise Linux Server VERSION="7.9 (Maipo)"
 - [x] Provide client logs ([2020-10-28 16:00:10,940] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-10-28 16:00:12,661] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)

[2020-10-28 16:36:04,329] TRACE [Controller id=0] Checking need to trigger auto leader balancing (kafka.controller.KafkaController)
[2020-10-28 16:41:04,330] INFO [Controller id=0] Processing automatic preferred replica leader election (kafka.controller.KafkaController)
)
 - [x] Provide broker log excerpts
[2020-10-14T07:16:43.733+0530][gc,heap,exit] Heap
[2020-10-14T07:16:43.733+0530][gc,heap,exit]  garbage-first heap   total 524288K, used 9316K [0xc6c00000, 0xe6c00000)
[2020-10-14T07:16:43.733+0530][gc,heap,exit]   region size 1024K, 9 young (9216K), 4 survivors (4096K)
[2020-10-14T07:16:43.733+0530][gc,heap,exit]  Metaspace       used 5253K, capacity 5368K, committed 5400K, reserved 5424K
 - [x] Critical issue
Cannot authenticate

**Comment by edenhill** [comment]
Due do dependency issues libsasl2/GSSAPI is not included in the prebuilt binary Linux wheels, you'll need to install librdkafka separately, see https://github.com/confluentinc/confluent-kafka-python/#prerequisites

**Comment by EnriqueV3ga** [comment]
Hello @edenhill 
How can I prepare a packaged version of Python Confluent Kafka that includes all the Librdkafka dependencies for a Cloud Foundry app, I think we might just need to package with Ubuntu specific dependencies ?
Is that possible and how can I do that ?
