### ISSUE TITLE
Can't tell if Kafka broker is unreachable

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#98]
I have a python app that uses the confluent Kafka client, which in turn relies on librdkafka. We are using librdkafka version 0.9.1.

I am trying to set up a Kafka producer (and later, a consumer). The actual addresses or FQDNs of the brokers is, of course, configurable. From the point of view of my app, one of the first things I am interested in before I can start my work is, did I successfully connect to a broker? I create a Producer, and I produce(), but what if the broker is down or unreachable, or the user simply entered garbage in the broker list? I find that flush() hangs for an unacceptably long time in these cases.

What I'd like is visibility and control. After I create the Producer, I want to be able to ask it, did you succeed in establishing a connection with at least one broker? I see that in the C code in librdkafka-master, there is the rd_kafka_broker_any(rk, RD_KAFKA_BROKER_STATE_UP) routine. Is there anything like this through the python API? I might want to be able to walk the broker list and ask the connection state of each. My app might want to take different actions depending on our failure to connect to the broker cluster. The closest I think I can some is a loop, asking for len(my_producer) after I produce(), and waiting for it to go fro m 1 to 0. Is there nothing better?

Is there something clever I could do with callbacks that would solve my problems?

Thanks,

-John Gregg

Here is a portion of my dummy test script:

def my_kafka_cb(err, msg):
    print("my_kafka_cb, err {}, msg {}".format(str(err), str(msg)))

conf = {'bootstrap.servers': '1.2.3.4',
        'group.id': 'mygroup',
        'debug': 'all',
        'socket.timeout.ms': 5000,
        'socket.max.fails': 1,
        'session.timeout.ms': 3000}

kafka_producer = Producer(**conf)

print("just created, len {}, about to poll 4.5".format(len(kafka_producer)))
print("************************** poll returned {}".format(kafka_producer.poll(4.5)))
kafka_producer.produce("Fred_topic", "Fred the dog went for a walk".encode('utf-8'), on_delivery=my_kafka_cb)
print("************************** just produced (len {}), about to poll 1.0".format(len(kafka_producer)))
print("************************** poll returned {}".format(kafka_producer.poll(1.0)))
kafka_producer.flush()
print("************************** after flush")

**Comment by edenhill** [comment]
There's currently no API in Python client to query any broker state (there's the metadata() API in C which would do the trick, but it hasn't been ported yet).

But what you can do which I think would serve you quite well is registering an error_cb and look for the _ALL_BROKERS_DOWN error event the first couple of seconds after starting your program.

This is okay to do on startup as some sort of precaution, but since the brokers may actually be valid but currently unreachable for whatever temporary networking reason, you might exit your program wrongfully.
This is why you shouldnt exit if you see _ALL_BROKERS_DOWN later while your program runs, librdkafka will automatically reconnect and resume operation as soon as brokers start coming up again.

**Comment by johnrgregg3** [comment]
OK, so how do I register an error_cb? I tried this:

def my_kafka_error(err):
    print("my_kafka_error")

conf = {'bootstrap.servers': '1.2.3.4',
            'error_cb': my_kafka_error}
kafka_producer = Producer(**conf)

But it doesn't like it:

Producer() caught KafkaException: code -186, name _INVALID_ARG, str Property "error_cb" must be
set through dedicated .._set_..() function

What should the API signature of my callback look like? Is there a way to pass in a python function at all to the callbacks of type _RK_C_PTR?

**Comment by edenhill** [comment]
error_cb was added to confluent-kafka-python 0.9.2
