### ISSUE TITLE
consumer polling

### ISSUE THREAD

**Issue by 2020testuser** [confluentinc/confluent-kafka-python#983]
Description
===========
Hi, 
Could anyone please help me?
I've like 100 messages in my topic and my consumer uses polling mechanism to get the messages.
I'm getting the message and writing to a file by  creating the filename with index 1,2,3,4,5, etc. in the filename.

I see the files are getting created randomly eventhough I increment the index after I write the message to the file. 
Below is my kafka consumer code snippet. Could anyone please let me know whether I need to incease my polling timeout or do anything else?

I'm using latest version of confluent kafka. I get the filenames created as app1data.json, app5data.json, app8data.json, app2data.json etc. 

Is there anyway for I can get the files created in order, app1data.json, app2data.json, app3data.json etc. 
```python
        index = 1
        while True:
            try:
                msg = consumer.poll(.5)
            except Exception as e:
                print("Message deserialization failed for {}: {}".format(msg, e))
                break

            if msg is None:
                continue

            if msg.error():
                if msg.error().code() == KafkaError._PARTITION_EOF:
                    continue
                else:
                    print(msg.error())
                    return jsonify({'Kafka Exception while get messages from Kafka Consumer': msg.error()})
         
            print('Message Received: {}\n'.format(msg.value()))
            filename = 'app' + str(index) + 'data.json' ## save the 100 messages - each in one file
            decoded_msg = msg.value().decode('utf-8') # Decode using the utf-8 encoding
            print("Saving msgs to a file")
            with open(filename 'w') as outfile:
               json.dump(decoded_msg , outfile)
            index = index + 1

        return json.dumps("Successfully dumped " + index + " files to the filesystem"), 200, {'Content-Type': 'application/json'}

```
Thanks in advance!

**Comment by edenhill** [comment]
This is unrelated to Kafka since it is your loop that increments index and writes the files. Recommend adding additional debug prints (printing the index) to your loop to see what is going on.
