### ISSUE TITLE
"Current" documentation still show 1.4.0

### ISSUE THREAD

**Issue by lindycoder** [confluentinc/confluent-kafka-python#985]
Description
===========
Hello!

The documentation at https://docs.confluent.io/current/clients/confluent-kafka-python/index.html, linked in https://github.com/confluentinc/confluent-kafka-python/blob/master/README.md says 1.4.0 on the top left while the current version is 1.5.0.

I don't know if the publication failed or the doc was not modified and still says 1.4.0.

Thank you!

How to reproduce
================
N/A

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Will fix, thank you.

**Comment by edenhill** [comment]
This is now fixed, but will take a couple of days before it is live.

Thanks for reporting!
