### ISSUE TITLE
Stop the Poll()

### ISSUE THREAD

**Issue by 2020testuser** [confluentinc/confluent-kafka-python#986]
Could anyone shed some light on the below?

I'm calling the poll(1.0) inside a while loop. Once the messages are fetched and processed, I want to exit the while loop.
Is there any timeout setting that I can set on the consumer side, so I don't see poll() happening continuously. I checked the consumer config and didn't find any.
 Thanks in advance!

`
while True:
try:
msg = consumer.poll(1.0)
except Exception as e:
print("Message deserialization failed for {}: {}".format(msg, e))
break

        if msg is None:
            continue

        if msg.error():
            if msg.error().code() == KafkaError._PARTITION_EOF:
                continue
            else:
                print(msg.error())
                return jsonify({'Kafka Exception while get messages from Kafka Consumer': msg.error()})
                

        print('Message Received: {}\n'.format(msg.value()))
`
I'm using latest version of Kafka Confluent package.

**Comment by edenhill** [comment]
If you want to read up until there are no more messages you can track the PARTITION_EOF of each assigned partition: get the current with assignment() and check if PARTITION_EOF has been seen. If all partitions are at PARTITION_EOF you can break your loop. Don't forget to clear the EOF flag on a partition if a new message arrives.
This requires `enable.partition.eof` to be set to `True` in the config.
