### ISSUE TITLE
pool() still trying to connect to old IP from broker

### ISSUE THREAD

**Issue by jeanfinck** [confluentinc/confluent-kafka-python#990]
Description
===========
While Investigating why consumer didn't retrieve some messages from broker while in a loop using "pool()" was identified that actually it wasn't connected to broker. It seems that broker restarted (pod from Kubernetes) and it received a new IP, but consumer kept trying to connect in old IP.

` ...
while True:
    msg = c.poll(1.0)

    if msg is None:
... `

Reading logs seems that it tries to connect to new IP automatically, but it also seems that it also tries to connect in old IP.
With no success in any situation, doing that the "while" still there forever and without connecting/receiving new messages.

Initially I was concerned about that could be a DNS cache, but as we can see in logs, new IP was there.
(https://github.com/edenhill/librdkafka/pull/269)

Later I found it this phrase from documents, but it isn't clear to me if it is related. And I could notice that only two IPs continues to appear in log, always an old one and the correct one (I repeatedly killed broker to see behaviour in logs).
_brokers - eternally cached, the broker list is additative._
(https://docs.confluent.io/5.4.3/clients/librdkafka/md_INTRODUCTION.html#simple-consumer-api-legacy)

**Broker:**
Kafka® 2.4.0

**python3 versions.py** 
`import confluent_kafka

print(confluent_kafka.version())
print(confluent_kafka.libversion())`
('1.5.0', 17104896)
('1.5.0', 17105151)

**Kubernetes Pod**
_Previously running and working with Consumer_
Name:         kafka-0
Start Time:   Tue, 17 Nov 2020 20:28:06 -0300
Status:       Running
IP:           10.0.0.81

_When it got restarted and Consumer lost connection_
Name:         kafka-0
Start Time:   Tue, 17 Nov 2020 20:35:13 -0300
Status:       Running
IP:           10.0.0.82

**Knowing that IP changed, those lines from log took my attention:**
%7|1605656033.988|METADATA|rdkafka#consumer-1| [thrd:main]: kafka:9092/bootstrap:   Broker #0/1: 10.0.0.81:9092 NodeId 0
%7|1605656033.989|WAKEUPFD|rdkafka#consumer-1| [thrd:main]: 10.0.0.81:9092/0: Enabled low-latency ops queue wake-ups
%7|1605656033.989|BROKER|rdkafka#consumer-1| [thrd:main]: 10.0.0.81:9092/0: Added new broker with NodeId 0
...
%7|1605656034.020|METADATA|rdkafka#consumer-1| [thrd:main]: kafka:9092/bootstrap: 1 brokers, 2 topics
%7|1605656034.020|METADATA|rdkafka#consumer-1| [thrd:main]: kafka:9092/bootstrap:   Broker #0/1: 10.0.0.81:9092 NodeId 0
...
%7|1605656159.990|METADATA|rdkafka#consumer-1| [thrd:main]: kafka:9092/bootstrap: 1 brokers, 2 topics
%7|1605656159.990|METADATA|rdkafka#consumer-1| [thrd:main]: kafka:9092/bootstrap:   Broker #0/1: 10.0.0.82:9092 NodeId 0
...
%7|1605656159.991|UPDATE|rdkafka#consumer-1| [thrd:10.0.0.81:9092/0]: 10.0.0.81:9092/0: Nodename changed from 10.0.0.81:9092 to 10.0.0.82:9092
%7|1605656159.991|UPDATE|rdkafka#consumer-1| [thrd:10.0.0.81:9092/0]: 10.0.0.82:9092/0: Name changed from 10.0.0.81:9092/0 to 10.0.0.82:9092/0
...
%7|1605656161.296|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.81:9092/0]: 10.0.0.82:9092/0: Connecting to ipv4#10.0.0.82:9092 (plaintext) with socket 12
%7|1605656161.296|CONNECT|rdkafka#consumer-1| [thrd:10.0.0.81:9092/0]: 10.0.0.82:9092/0: Connected to ipv4#10.0.0.82:9092
%7|1605656161.296|CONNECTED|rdkafka#consumer-1| [thrd:10.0.0.81:9092/0]: 10.0.0.82:9092/0: Connected (# 14)
...
%7|1605656162.099|BROADCAST|rdkafka#consumer-1| [thrd:GroupCoordinator]: Broadcasting state change
%7|1605656162.099|CONNECT|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Connecting to ipv4#10.0.0.81:9092 (plaintext) with socket 13
%7|1605656162.099|CONNECT|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Connected to ipv4#10.0.0.81:9092
%7|1605656162.099|CONNECTED|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Connected (# 14)
...
%7|1605656202.341|RECV|rdkafka#consumer-1| [thrd:10.0.0.81:9092/0]: 10.0.0.82:9092/0: Received FindCoordinatorResponse (v2, 31 bytes, CorrId 1498, rtt 1.72ms)
%7|1605656202.341|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: 10.0.0.82:9092/0: Group "cgroudid-2" coordinator is 10.0.0.82:9092 id 0
%7|1605656203.030|CONNECT|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: broker in state TRY_CONNECT connecting
%7|1605656203.030|STATE|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Broker changed state TRY_CONNECT -> CONNECT
%7|1605656203.030|BROADCAST|rdkafka#consumer-1| [thrd:GroupCoordinator]: Broadcasting state change
%7|1605656203.030|CONNECT|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Connecting to ipv4#10.0.0.81:9092 (plaintext) with socket 13
%7|1605656203.030|CONNECT|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/0: Connected to ipv4#10.0.0.81:9092

[lib-log.txt](https://github.com/confluentinc/confluent-kafka-python/files/5557086/lib-log.txt)

Is there something that I'm missing? Or could be something misconfigured?

How to reproduce
================
In a Kubernetes environment with a broker properly configured and a consumer connected, somehow kill broker pod and check logs from consumer app to check that it won't connect again in broker when it comes up and running again.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [x] Operating system: Container-Optimized OS
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It looks like you have a single broker in your cluster that you then change the IP address of (by restarting the pod), unless your bootstrap.servers (or learnt broker names from broker metadata) has a DNS record that points to the new address there is no way for the client to find out the new IP address for the broker.

**Comment by jeanfinck** [comment]
Oh sorry, I missed those details.. sorry

But yes, there is only one broker and it is configured together with a service (k8s) to resolve a DNS to corresponding pod.
Configuration properties:
`        {
            'bootstrap.servers': "kafka:9092",
            'group.id': "xxyyzz,
            'schema.registry.url': "http://schema-host:8081",
            "api.version.request": True,
            "enable.auto.commit": False,
            "debug": "all"
        }
`

Indeed, it was able to find the new IP address from configured DNS in bootstrap.servers, as in log it points to "10.0.0.82".
What I couldn't figure out is why it continues to try to establish connection using old IP "10.0.0.81" (if I restart the script, it starts correctly).

Checking dnslookup for example in configured hostname, returns only new IP. I can't identify who is "holding" this cache..

**Comment by edenhill** [comment]
Because the broker advertised itself as 10.0.0.81:9092 (see advertised.listeners broker config), and librdkafka never forgets (a broker).

**Comment by jeanfinck** [comment]
Hum, so just the fact that while it was running it was configured with:
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.0.0.81:9092
and when kafka pod restarted and came back with:
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.0.0.82:9092

As I didn't restart my consumer script, librdkafka will maintain cache and will still try to connect in the wrong IP?

There is some way to detect that my poll() isn't connected to decide to kill process? Or maybe the way that I configured advertised is wrong?

My concern is how to identify, fix and/or kill process to establish connection to receive new messages.

**Comment by edenhill** [comment]
It will stop trying to connect to an old broker if a new broker takes over its broker.id.

**Comment by jeanfinck** [comment]
You were faster than I editing previous comment lol

I would say it, that wouldn't be a problem to mantain old IP, since that identifying a new one and could connect again.. other behaviour that I identified, is that even 30 minutes later, those messages in log, saying that it still tries to connect to old one and didn't receive any message remains.

**Comment by jeanfinck** [comment]
Investigating this behaviour.. 

root@xxxxxxx-55988495c8-t2x6p:/nnnnnxxxxxxx# nslookup 10.0.0.82
** server can't find 82.0.0.10.in-addr.arpa: NXDOMAIN

root@xxxxxxx-55988495c8-t2x6p:/nnnnnxxxxxxx# traceroute 10.0.0.82
traceroute to 10.0.0.82 (10.0.0.82), 30 hops max, 60 byte packets
 1  xxxxxxx-55988495c8-t2x6p (10.0.0.66)  3089.498 ms !H  3089.397 ms !H  3089.381 ms !H
root@xxxxxxx-55988495c8-t2x6p:/nnnnnxxxxxxx# telnet 10.0.0.82 9092
Trying 10.0.0.82...
Connected to 10.0.0.82.
Escape character is '^]'.
Connection closed by foreign host.

Seems that something is still responding TCP connection in this IP..
Could it be a problem to librdkafka thinks that "old" IP is still valid? I mean this connection being accepted even being closed right after
