### ISSUE TITLE
How to use jwt callback for consumer - works in python-kafka but zero examples on this lib

### ISSUE THREAD

**Issue by davidmontgom** [confluentinc/confluent-kafka-python#993]
I have a python-kafka that works and is the code below:

    class TokenProvider(object):
        
        def __init__(self,client_id,client_secret):
            self.client_id = client_id
            self.client_secret = client_secret
        def token(self):
            token_url = 'https://test.com/protocol/openid-connect/token'
            client = BackendApplicationClient(client_id=self.client_id)
            oauth = OAuth2Session(client=client)
            token_json = oauth.fetch_token(token_url=token_url, client_id=self.client_id, client_secret=self.client_secret)
            token = token_json['access_token']
            #print(token)
            return token

    consumer = KafkaConsumer(
        group_id=None,
        bootstrap_servers=['test.com:9094'],
        security_protocol='SASL_SSL',
        sasl_mechanism='OAUTHBEARER',
        sasl_oauth_token_provider=TokenProvider(client_id,client_secret),
        ssl_check_hostname=False,
        ssl_context=create_ssl_context(),
        auto_offset_reset=offset,
        enable_auto_commit=False,
        value_deserializer=lambda m: decode(m)
        )
    consumer.subscribe(topics=['test.stream'])
	
My confluent python is the below and I get this error.  I am hoping that confluent with be faster under pypy3.
	

    cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Property "oauthbearer_token_refresh_cb" must be set through dedicated .._set_..() function"}
	
	c = Consumer({
	    'bootstrap.servers': 'test.com:9094',
	    'sasl.mechanism': 'OAUTHBEARER',
	    'security.protocol': 'SASL_SSL',
	    'oauthbearer_token_refresh_cb': TokenProvider(client_id,client_secret),
	    'group.id': str(uuid.uuid1()),
	    'auto.offset.reset': 'earliest'
	})

	c.subscribe(['test.stream']) 

So how do I get confluent kafka to work?  I appear to have an issue with oauthbearer_token_refresh_cb using OAUTHBEARER and SASL_SSL.  

In essence I auth with a jwt token

**Comment by mataralhawiti** [comment]
@davidmontgom I found the following links that might help : 
https://github.com/confluentinc/confluent-kafka-python/issues/839

https://github.com/confluentinc/confluent-kafka-python/pull/960

**Comment by edenhill** [comment]
OAUTHBEARER is not yet supported by the Python client

**Comment by davidmontgom** [comment]
Any idea when it will be supported?

**Comment by stevenylai** [comment]
@edenhill I have a pull request to add support to Python client. Perhaps if you have time you can take a look and if it makes sense, I can carry on to update that branch?

**Comment by pranavrth** [comment]
OAUTHBEARER support was added in v1.6.1 and further improved in v1.9.0 and v1.9.2. Closing this issue.
