### ISSUE TITLE
Licence information missing from PyPI

### ISSUE THREAD

**Issue by faph** [confluentinc/confluent-kafka-python#994]
Description
===========

The PyPI package page https://pypi.org/project/confluent-kafka/ does not list the OSS licence. Typically, PyPI displays the licence in the left-hand column under the header "Meta". This information is taken from the package's "classifiers" in `setup.py`.

Missing licence information stops some privately hosted PyPI indices from automatically pulling in such packages.

PR #603 actually solves this. Please merge.

For the avoidance of doubt, the required classifier is `License :: OSI Approved :: Apache Software License`

How to reproduce
================

See https://pypi.org/project/confluent-kafka/, left-hand column under "Meta". It should display the Apache licence.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Thanks for bringing that old PR back into the light.

**Comment by faph** [comment]
Many thanks for merging!
