### ISSUE TITLE
Building wheel for confluent-kafka (setup.py): finished with status 'error'

### ISSUE THREAD

**Issue by sgreszcz** [confluentinc/confluent-kafka-python#995]
Description
===========

I'm trying to import confluent_kafka python library in Docker (using python:3.9.0-slim image).  I'm getting errors when the setup.py routine is executed:

```
  Building wheel for confluent-kafka (setup.py): started
  Building wheel for confluent-kafka (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iyrn0ukj/confluent-kafka/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iyrn0ukj/confluent-kafka/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1y9yvixx
       cwd: /tmp/pip-install-iyrn0ukj/confluent-kafka/
  Complete output (49 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/confluent_kafka
  copying confluent_kafka/deserializing_consumer.py -> build/lib.linux-x86_64-3.9/confluent_kafka
  copying confluent_kafka/__init__.py -> build/lib.linux-x86_64-3.9/confluent_kafka
  copying confluent_kafka/error.py -> build/lib.linux-x86_64-3.9/confluent_kafka
  copying confluent_kafka/serializing_producer.py -> build/lib.linux-x86_64-3.9/confluent_kafka
  creating build/lib.linux-x86_64-3.9/confluent_kafka/serialization
  copying confluent_kafka/serialization/__init__.py -> build/lib.linux-x86_64-3.9/confluent_kafka/serialization
  creating build/lib.linux-x86_64-3.9/confluent_kafka/kafkatest
  copying confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-x86_64-3.9/confluent_kafka/kafkatest
  copying confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-x86_64-3.9/confluent_kafka/kafkatest
  copying confluent_kafka/kafkatest/__init__.py -> build/lib.linux-x86_64-3.9/confluent_kafka/kafkatest
  copying confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-x86_64-3.9/confluent_kafka/kafkatest
  creating build/lib.linux-x86_64-3.9/confluent_kafka/schema_registry
  copying confluent_kafka/schema_registry/avro.py -> build/lib.linux-x86_64-3.9/confluent_kafka/schema_registry
  copying confluent_kafka/schema_registry/__init__.py -> build/lib.linux-x86_64-3.9/confluent_kafka/schema_registry
  copying confluent_kafka/schema_registry/json_schema.py -> build/lib.linux-x86_64-3.9/confluent_kafka/schema_registry
  copying confluent_kafka/schema_registry/error.py -> build/lib.linux-x86_64-3.9/confluent_kafka/schema_registry
  copying confluent_kafka/schema_registry/protobuf.py -> build/lib.linux-x86_64-3.9/confluent_kafka/schema_registry
  copying confluent_kafka/schema_registry/schema_registry_client.py -> build/lib.linux-x86_64-3.9/confluent_kafka/schema_registry
  creating build/lib.linux-x86_64-3.9/confluent_kafka/avro
  copying confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-x86_64-3.9/confluent_kafka/avro
  copying confluent_kafka/avro/__init__.py -> build/lib.linux-x86_64-3.9/confluent_kafka/avro
  copying confluent_kafka/avro/error.py -> build/lib.linux-x86_64-3.9/confluent_kafka/avro
  copying confluent_kafka/avro/load.py -> build/lib.linux-x86_64-3.9/confluent_kafka/avro
  creating build/lib.linux-x86_64-3.9/confluent_kafka/admin
  copying confluent_kafka/admin/__init__.py -> build/lib.linux-x86_64-3.9/confluent_kafka/admin
  creating build/lib.linux-x86_64-3.9/confluent_kafka/avro/serializer
  copying confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-3.9/confluent_kafka/avro/serializer
  copying confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-3.9/confluent_kafka/avro/serializer
  running build_ext
  building 'confluent_kafka.cimpl' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/tmp
  creating build/temp.linux-x86_64-3.9/tmp/pip-install-iyrn0ukj
  creating build/temp.linux-x86_64-3.9/tmp/pip-install-iyrn0ukj/confluent-kafka
  creating build/temp.linux-x86_64-3.9/tmp/pip-install-iyrn0ukj/confluent-kafka/confluent_kafka
  creating build/temp.linux-x86_64-3.9/tmp/pip-install-iyrn0ukj/confluent-kafka/confluent_kafka/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c /tmp/pip-install-iyrn0ukj/confluent-kafka/confluent_kafka/src/Admin.c -o build/temp.linux-x86_64-3.9/tmp/pip-install-iyrn0ukj/confluent-kafka/confluent_kafka/src/Admin.o
  In file included from /tmp/pip-install-iyrn0ukj/confluent-kafka/confluent_kafka/src/Admin.c:17:
  /tmp/pip-install-iyrn0ukj/confluent-kafka/confluent_kafka/src/confluent_kafka.h:22:10: fatal error: librdkafka/rdkafka.h: No such file or directory
   #include <librdkafka/rdkafka.h>
            ^~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for confluent-kafka
```

How to reproduce
================

Dockerfile:
```
FROM python:3.9.0-slim
RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean

# set work dir
WORKDIR /app
COPY requirements.txt /app/requirements.txt
```

requirements.txt:

```
confluent_kafka
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
```
Collecting confluent_kafka
  Downloading confluent-kafka-1.5.0.tar.gz (97 kB)
```

 - [ ] Operating system: 
Docker python:3.9.0-slim image (Debian)

**Comment by edenhill** [comment]
When building the python client from source  you need to install librdkafka separately.

**Comment by jjmmolina** [comment]
I'm trying to install after install before librdkafka and the result is the same. I can't install confluent-kafka: 

   ```
creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/jobandtalent/Code/training/Python/flask-kafka/venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.c -o build/temp.macosx-10.9-universal2-3.10/private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.o
      In file included from /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.c:17:
      /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: 'librdkafka/rdkafka.h' file not found
      #include <librdkafka/rdkafka.h>
               ^~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for confluent-kafka 
```

**Comment by SmartXingZhou** [comment]
I solved this problem by following steps：

1. brew install librdkafka.
2. set environment variables. export C_INCLUDE_PATH=/opt/homebrew/Cellar/librdkafka/1.9.2/include
    export LIBRARY_PATH=/opt/homebrew/Cellar/librdkafka/1.9.2/lib


> I'm trying to install after install before librdkafka and the result is the same. I can't install confluent-kafka:
> 
> ```
> creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src
>    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/jobandtalent/Code/training/Python/flask-kafka/venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.c -o build/temp.macosx-10.9-universal2-3.10/private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.o
>    In file included from /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.c:17:
>    /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: 'librdkafka/rdkafka.h' file not found
>    #include <librdkafka/rdkafka.h>
>             ^~~~~~~~~~~~~~~~~~~~~~
>    1 error generated.
>    error: command '/usr/bin/clang' failed with exit code 1
>    [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ERROR: Failed building wheel for confluent-kafka 
> ```

**Comment by sitholephila** [comment]
> I solved this problem by following steps：
> 
> 1. brew install librdkafka.
> 2. set environment variables.
>    export C_INCLUDE_PATH=/opt/homebrew/Cellar/librdkafka/1.9.2/include
>    export LIBRARY_PATH=/opt/homebrew/Cellar/librdkafka/1.9.2/lib
>    Remember to modify '1.9.2' to your own version
> 3. pip install confluent_kafka
> 
> > I'm trying to install after install before librdkafka and the result is the same. I can't install confluent-kafka:
> > ```
> > creating build/temp.macosx-10.9-universal2-3.10/private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src
> >    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/jobandtalent/Code/training/Python/flask-kafka/venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.c -o build/temp.macosx-10.9-universal2-3.10/private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.o
> >    In file included from /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/Admin.c:17:
> >    /private/var/folders/td/w1gcl5210h74qmvykhkskw2w0000gn/T/pip-install-tm3qpthm/confluent-kafka_ddc7b2ef0808474590dbb1625805f03e/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: 'librdkafka/rdkafka.h' file not found
> >    #include <librdkafka/rdkafka.h>
> >             ^~~~~~~~~~~~~~~~~~~~~~
> >    1 error generated.
> >    error: command '/usr/bin/clang' failed with exit code 1
> >    [end of output]
> > 
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> > ERROR: Failed building wheel for confluent-kafka 
> > ```

Worked for me as well :) Thanks
