### ISSUE TITLE
Producer error_cb didn't triggered by Connection refused

### ISSUE THREAD

**Issue by lixiaomei-git** [confluentinc/confluent-kafka-python#996]
Description
===========
I create a producer with error_cb handling, then I stop the kafka in local.
I expected that the connection refused error will trigger the error_cb handling. Unfortunately, it didn't.

How to reproduce
================

```
from confluent_kafka import Producer


def error(err):
    raise Exception(err.str())


if __name__ == '__main__':
    for i in range(10):
        try:
            producer = Producer({
                'bootstrap.servers': 'localhost:9092',
                'session.timeout.ms': 10,
                'retries': 0,
                'error_cb': error
            })
        except Exception as e:
            print("Create Producer error: {}".format(e.message))
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
confluent-kafka=1.5.0,
I don't know how to get libversion
 - [x] Apache Kafka broker version: 2.6.0
 - [x] Client configuration: `{'bootstrap.servers': 'localhost:9092',
                'session.timeout.ms': 10,
                'retries': 0,
                'error_cb': error}`
 - [x] Operating system: macOS 10.15.7
 - [x] Provide client logs 
%3|1606279483.722|FAIL|rdkafka#producer-2| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 3ms in state CONNECT)
%3|1606279483.724|FAIL|rdkafka#producer-4| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 1ms in state CONNECT)
%3|1606279483.733|FAIL|rdkafka#producer-6| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 8ms in state CONNECT)
%3|1606279483.740|FAIL|rdkafka#producer-8| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 5ms in state CONNECT)
%3|1606279483.741|FAIL|rdkafka#producer-10| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 1ms in state CONNECT)

 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to call producer.poll() to trigger callbacks.

**Comment by lixiaomei-git** [comment]
> You need to call producer.poll() to trigger callbacks.

Thank you, I called poll() after I read the api. And if I set timeout = 0, sometimes, the error_cb still can not be triggered. If I set timeout =3, it seems the error_cb can be triggered every time. Is there any advice how to set the timeout?

**Comment by lixiaomei-git** [comment]
> You need to call producer.poll() to trigger callbacks.

And I also have problem when I use consumer to get lag. The consumer only call list_topics(),committed() and get_watermark_offsets() to get lag, so if the kafka is stoped, the process will always print 
`%3|1606314296.007|FAIL|rdkafka#consumer-7| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 1ms in state CONNECT, 1 identical error(s) suppressed)
`
And finally, my process crush by `Fatal Python error: unexpected exception during garbage collection`
So what should I do to catch the connection refused exception when I just want to get lag?

**Comment by Alfex4936** [comment]
I have the same problem, I guess when the broker is down, consumer doesn't produce any exceptions.

It keeps producing messages like, `%6|1608028203.597|FAIL|rdkafka#consumer-1| blahblah` not in msg.error block

I tried to catch, KafkaException, KafkaError.UNKNOWN, KafkaError.NETWORK_EXCEPTION ... but couldn't catch any of these errors

How can I catch the broker down exception using KafkaError?

**Comment by edenhill** [comment]
Tracking single broker connection statuses isn't very useful for a client or application to do, there's the ERR__ALL_BROKERS_DOWN error event for when no brokers are available.

See https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down
