### ISSUE TITLE
Performance drop producing from Windows versus from an Alpine docker container

### ISSUE THREAD

**Issue by emmanuel-pic** [confluentinc/confluent-kafka-python#998]
Description
===========
I was investigating a drop in producer performance in one of our docker containers. I wrote a crude benchmark tool and  noticed that there is a significant difference between running it in Windows versus the same code running in a Docker container. The performance drop appears both when running the container locally on my windows host, and when the container runs in the kubernetes cluster. Here are the results measured:

### Windows
```
confluent : 870.74µs ± 2.08µs, throughput 1148.4461054484002 msg/s, (total messages: 350000, total time: 304.76s)
```
### Alpine Linux container
```
confluent : 2.83ms ± 343.87ns, throughput 353.1951241012652 msg/s, (total messages: 350000, total time: 990.95s)
```

For the sake of verification, I also built a Ubuntu container which yields roughly the same results as the Alpine one. Did I misconfigure something here? What am I missing?

## OS versions
Windows 10
Alpine Linux 3.12

### Windows
Python 3.7.2
### Alpine Linux
Python 3.7.9

## Broker
Kafka 2.3.1

### Windows
```
print(confluent_kafka.version())
print(confluent_kafka.libversion())
('1.5.0', 17104896)
('1.5.0', 17105151)
```
### Alpine Linux
```
print(confluent_kafka.version())
print(confluent_kafka.libversion())
('1.5.0', 17104896)
('1.4.4', 17040639)
```

How to reproduce
================
In an environment with a broker properly configured, build a docker container, then run the benchmark script in Windows and in the container and observer the output.

The benchmark `kafka-benchmark.py`:
```
# -*- coding: utf-8 -*-
"""
"""
import math
import random
import string
import time
from collections import namedtuple
from typing import Dict, List, Tuple

from confluent_kafka import Producer as ConfluentProducer


def generate_messages(
        N: int,
        message_size: int = 5128,
        encoding: str = "ascii"
) -> Dict[bytes, bytes]:
    return {
        bytes(hex(i), encoding): bytes("".join(random.choices(string.hexdigits, k=message_size)), encoding)
        for i in range(N)
    }


BenchmarkResult = namedtuple("BenchmarkResult", ["sent_count", "elapsed"])


def benchmark_confluent_kafka(
        bootstrap_servers: List[str],
        topic: str,
        messages: Dict[bytes, bytes]
) -> BenchmarkResult:
    buffer_count = 10000
    p = ConfluentProducer(**{
        "bootstrap.servers": ",".join(bootstrap_servers),
        "request.required.acks": 0,
        "linger.ms": 0,
        "compression.level": 4,
        "queue.buffering.max.messages": buffer_count,
        "message.send.max.retries": 1,
        "batch.num.messages": 1000,
        "partitioner": "random"
    })

    messages_in_error = {}
    messages_to_retry = {}

    def delivery_report(err, msg):
        """
        Called once for each message produced to indicate delivery result.
        Triggered by poll() or flush().
        """
        nonlocal messages_in_error

        if err is not None:
            messages_in_error[msg.key()] = msg.value()

    t = time.time()
    for j, (key, message) in enumerate(messages.items()):
        try:
            p.produce(topic, key=key, value=message, callback=delivery_report)
        except BufferError:
            messages_to_retry[key] = messages
        if j % buffer_count == 0:
            p.flush()

    p.flush()
    return BenchmarkResult(len(messages) - len(messages_in_error) - len(messages_to_retry), time.time() - t)


time_units: List[Tuple[int, str]] = [
    (1, "s"),
    (1e3, "ms"),
    (1e6, "µs"),
    (1e9, "ns")
]


def format_time(t: float) -> str:
    if t <= 0:
        return f"{t}s"

    for mult, unit in time_units:
        t_mult = t * mult
        if math.log(t_mult) > 0:
            return f"{t_mult:.2f}{unit}"
    mult, unit = time_units[-1]
    return f"{t * mult:.2f}{unit}"


def report(libname: str, results: List[BenchmarkResult]) -> None:
    total_messages_sent = 0
    total_time = 0
    for result in results:
        total_messages_sent += result.sent_count
        total_time += result.elapsed

    avg_time_per_message = total_time / total_messages_sent
    stddev_time_per_message = math.sqrt(math.fsum(
        ((result.elapsed / result.sent_count) - avg_time_per_message) ** 2
        for result in results
    ) / total_messages_sent)
    throughput = total_messages_sent / total_time

    print(
        f"{libname:<10}: {format_time(avg_time_per_message)} ± "
        f"{format_time(stddev_time_per_message)}, throughput {throughput} msg/s, "
        f"(total messages: {total_messages_sent}, total time: {format_time(total_time)})"
    )


if __name__ == "__main__":
    bootstrap_servers = [
        "broker1:12345",
        "broker2:12345"
    ]
    topic = "kafka.benchmark.test"

    run_count = 7
    messages_to_send = generate_messages(50000)

    results = []
    for i in range(run_count):
        results.append(benchmark_confluent_kafka(bootstrap_servers, topic, messages_to_send))
    report("confluent", results)
```

The Dockerfile:
```
FROM docker.io/library/python:3.7-alpine3.12

COPY ./kafka-benchmark.py /

WORKDIR /

RUN    apk add --no-cache gcc musl-dev librdkafka librdkafka-dev \
    && python --version \
    && python -m pip install --no-cache-dir -U pip \
    && python -m pip install --no-cache-dir confluent-kafka~=1.5.0
```
that can be built with:
`docker build .  --no-cache --tag kafka-benchmark:1.5.0-alpine3.12`
and ran with:
`docker run -it kafka-benchmark:1.5.0-alpine3.12 python /kafka-benchmark.py`

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
	- Windows: `('1.5.0', 17104896)` and `('1.5.0', 17105151)` resp.
	- Alpine Linux: `('1.5.0', 17104896)` and `('1.4.4', 17040639)` resp.
 - [x] Apache Kafka broker version: 2.3.1
 - [x] Client configuration:
	`{
        "bootstrap.servers": ",".join(bootstrap_servers),
        "request.required.acks": 0,
        "linger.ms": 0,
        "compression.level": 4,
        "queue.buffering.max.messages": buffer_count,
        "message.send.max.retries": 1,
        "batch.num.messages": 1000,
        "partitioner": "random"
    }`
 - [x] Operating systems: Windows and Alpine Linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Recommend using default settings/config unless you explicitly need to change it.
In particular:
 *  you should never set acks to 0 since you will have silent data loss. Leave at its default (all) or acks=1.
 * linger.ms=0 yields low throughput, leave it at its default setting, or if end2end latency is crucial, at least a couple of milliseconds.
 * batch.num.messages -1 there is no point in limiting this as it yields lower throughput, leave at its default.

**Comment by emmanuel-pic** [comment]
Thanks for the quick reply. I am aware of the `request.required.acks` setting, but since this was a benchmark I was merely trying to get a barebone idea. That being said, I took your comments in consideration and reran the benchmark:
## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),
	"compression.level": 4,
	"message.send.max.retries": 1,
	"partitioner": "random"
}
```
### Windows
`confluent : 829.68µs ± 1.70µs, throughput 1205.2817917413738 msg/s, (total messages: 350000, total time: 290.39s)`
### Alpine Linux container
`confluent : 2.49ms ± 541.02ns, throughput 401.36716499870346 msg/s, (total messages: 350000, total time: 872.02s)`

## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),
}
```
### Windows
`confluent : 861.15µs ± 1.86µs, throughput 1161.2342331805492 msg/s, (total messages: 350000, total time: 301.40s)`
### Alpine Linux container
`confluent : 2.48ms ± 658.68ns, throughput 403.8512175816836 msg/s, (total messages: 350000, total time: 866.66s)`

So there is a slight performance improvement, but the overall performance drop still present.

**Comment by edenhill** [comment]
Oh, the problem is that you are calling p.flush() after each message you produce(), which effectively makes it a synchronous producer (and that's a very slow boring thing). Replace the loop p.flush() with p.poll(0) and you should be fine.

**Comment by emmanuel-pic** [comment]
I am not calling `p.flush()` with every message, rather with every `buffer_count` (10000) messages:
```
for j, (key, message) in enumerate(messages.items()):
	try:
		p.produce(topic, key=key, value=message, callback=delivery_report)
	except BufferError:
		messages_to_retry[key] = messages
	if j % buffer_count == 0:
		p.flush()
```
I removed the calls to `p.flush()` and replaced the production loop following your recommandations:
```
for j, (key, message) in enumerate(messages.items()):
	try:
		p.produce(topic, key=key, value=message, callback=delivery_report)
	except BufferError:
		messages_to_retry[key] = messages
	p.poll(0)
```
It didn't change much of my results:
## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),
}
```
### Windows
`confluent : 910.02µs ± 2.11µs, throughput 1098.881815825357 msg/s, (total messages: 350000, total time: 318.51s)`
### Alpine Linux container
`confluent : 2.47ms ± 615.82ns, throughput 404.362536220272 msg/s, (total messages: 350000, total time: 865.56s)`

**Comment by edenhill** [comment]
To rule out producer setup time, can you change your benchmark to run one loop (instead of 7) and produce a couple of hundred thousand messages in that single run?

**Comment by emmanuel-pic** [comment]
So I tried a few things in light of your comments. First off, when I left everything to default values and tried to produce 200000 messages, I reached a full queue on both systems:
```
Traceback (most recent call last):
  File "/app/benchmark/baam_kafka_benchmark.py", line 195, in <module>
    results.append(benchmark_confluent_kafka(bootstrap_servers, topic, messages_to_send))
  File "/app/benchmark/baam_kafka_benchmark.py", line 109, in benchmark_confluent_kafka
    p.produce(topic, key=key, value=message)
BufferError: Local: Queue full
```
This prompted me to try a few approaches, which results are below. It seems that overall the `poll(0)` call in the loop helps a bit, but the overall performance gap seems to remain.


## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),
	"queue.buffering.max.messages": 200000,

}
```
- [ ] `try`/`catch` around `produce()`
- [ ] delivery report callback
- [ ] `flush()`
- [x] `poll(0)`
### Windows
`confluent : 1.02ms ± 0.0s, throughput 977.6920242454663 msg/s, (total messages: 200000, total time: 204.56s)`
### Alpine Linux container
`confluent : 1.51ms ± 0.0s, throughput 663.3832089253232 msg/s, (total messages: 200000, total time: 301.48s)`


## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),

}
```
- [ ] `try`/`catch` around `produce()`
- [ ] delivery report callback
- [x] `flush()`
- [x] `poll(0)`
### Windows
`confluent : 593.42µs ± 0.0s, throughput 1685.1503358533598 msg/s, (total messages: 200000, total time: 118.68s)`
### Alpine Linux container
`confluent : 2.42ms ± 0.0s, throughput 413.03548679485607 msg/s, (total messages: 200000, total time: 484.22s)`


## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),

}
```
- [ ] `try`/`catch` around `produce()`
- [x] delivery report callback
- [x] `flush()`
- [x] `poll(0)`
### Windows
`confluent : 685.50µs ± 0.0s, throughput 1458.7897691560515 msg/s, (total messages: 200000, total time: 137.10s)`
### Alpine Linux container
`confluent : 2.47ms ± 0.0s, throughput 405.60407264898043 msg/s, (total messages: 200000, total time: 493.09s)`


## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),

}
```
- [x] `try`/`catch` around `produce()`
- [x] delivery report callback
- [x] `flush()`
- [x] `poll(0)`
### Windows
`confluent : 535.19µs ± 0.0s, throughput 1868.505154357187 msg/s, (total messages: 200000, total time: 107.04s)`
### Alpine Linux container
`confluent : 2.49ms ± 0.0s, throughput 400.9548064793969 msg/s, (total messages: 200000, total time: 498.81s)`

**Comment by edenhill** [comment]
Is there any difference if you set `'linger.ms': 100` in the config?

**Comment by emmanuel-pic** [comment]
Not much luck there either:
## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),
	"linger.ms": 100,
}
```
- [x] `try`/`catch` around `produce()`
- [x] delivery report callback
- [x] `flush()`
- [x] `poll(0)`
### Windows
`confluent : 871.16µs ± 0.0s, throughput 1147.89650068931 msg/s, (total messages: 200000, total time: 174.23s)`
### Alpine Linux container
`confluent : 2.50ms ± 0.0s, throughput 400.5221752627457 msg/s, (total messages: 200000, total time: 499.35s)`

**Comment by edenhill** [comment]
What's your message sizes?

**Comment by emmanuel-pic** [comment]
I generate random messages of 5kB each

**Comment by edenhill** [comment]
If you shortcut/take out the produce(), what numbers are you getting?

**Comment by emmanuel-pic** [comment]
If I do that (while keeping the calls to `poll(0)` and `flush()`), I do get similar numbers.

## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),
	"linger.ms": 100,
}
```
- [ ] `produce()` enabled
- [x] `try`/`catch` around `produce()`
- [x] delivery report callback
- [x] `flush()`
- [x] `poll(0)`
### Windows
`confluent : 718.71ns ± 0.18ns, throughput 1391382.501830052 msg/s, (total messages: 450000, total time: 323.42ms)`
### Alpine Linux container
`confluent : 573.30ns ± 0.15ns, throughput 1744275.3968070606 msg/s, (total messages: 450000, total time: 257.99ms)`

## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers)
}
```
- [ ] `produce()` enabled
- [x] `try`/`catch` around `produce()`
- [x] delivery report callback
- [x] `flush()`
- [x] `poll(0)`
### Windows
`confluent : 690.06ns ± 0.15ns, throughput 1449153.3973515884 msg/s, (total messages: 450000, total time: 310.53ms)`
### Alpine Linux container
`confluent : 652.98ns ± 0.04ns, throughput 1531442.3140117668 msg/s, (total messages: 450000, total time: 293.84ms)`

**Comment by edenhill** [comment]
So if you take the produce() call out of the tests and still get the same numbers it means the problem is not with the producer but with your test case that generates data too slowly.

**Comment by edenhill** [comment]
Okay, that's good, we now know the latency is in the producer.

What kind of cloud/hardware instance are you running this on?

**Comment by emmanuel-pic** [comment]
We are running our containers on AWS in a Kubernetes cluster. However this issue being reproducible on my local docker environment (ie the docker VM on Windows) this is what I have been using for the benchmarks above.

**Comment by edenhill** [comment]
Can you reproduce with `'debug': 'protocol'` and provide the logs?

**Comment by emmanuel-pic** [comment]
So I just reran the script. The Windows logfile generated is significantly larger than the the docker one. Here are the results nonetheless:
## Configuration
```
{
	"bootstrap.servers": ",".join(bootstrap_servers),
	"debug": "protocol"
}
```
- [x] `produce()` enabled
- [x] `try`/`catch` around `produce()`
- [x] delivery report callback
- [x] `flush()`
- [x] `poll(0)`
### Windows
`confluent : 1.31ms ± 1.35µs, throughput 765.6429506056529 msg/s, (total messages: 450000, total time: 587.74s)`
### Alpine Linux container
`confluent : 3.14ms ± 1.12µs, throughput 318.4986404321433 msg/s, (total messages: 428213, total time: 1344.47s)`

[windows.log](https://github.com/confluentinc/confluent-kafka-python/files/5629851/windows.log)
[alpine.log](https://github.com/confluentinc/confluent-kafka-python/files/5629852/alpine.log)

**Comment by edenhill** [comment]
Looking at all the partial sends and the high broker latencies (rtt) my guess is that you are saturating the network.

**Comment by emmanuel-pic** [comment]
Ok, I noticed that 2 issues were being compounded and I hadn't noticed. Your initial advices (using the default parameters, and the calling to `poll(0)` within the production loop) seem to actual do the trick. I apologize for wasting your time, thanks for sticking with me on this. Closing the issue.
